sPHENIX-Collaboration/coresoftware

offline/packages/trackreco/PHTrackClusterAssociator.cc
offline/packages/trackreco/PHTrackClusterAssociator.h

This fixes a bug in the track-cluster associator to use the track associated vertex position to determine the cluster eta when matching.

Add vertex to cluster eta

---

simulation/g4simulation/g4detectors/PHG4CylinderCellReco.cc
simulation/g4simulation/g4detectors/PHG4CylinderCellReco.h
simulation/g4simulation/g4detectors/PHG4FullProjSpacalCellReco.cc
simulation/g4simulation/g4detectors/PHG4FullProjSpacalCellReco.h
simulation/g4simulation/g4detectors/PHG4HcalCellReco.cc
simulation/g4simulation/g4detectors/PHG4HcalCellReco.h

This PR introduces a maximal time limit to the g4hit energy depositions within the EMCal, as well as the HCal systems of 100 ns. Any g4hit that has a lifetime longer than 100 ns is not counted towards the determined tower energy. This was discussed in a software meeting on November 1st: https://indico.bnl.gov/event/17577/contributions/70185/attachments/44178/74532/Long%20time-steps%20in%20geant.pdf   …

added maximum g4hit lifetime limit to the cell reconstruction in Calorimeters

---

simulation/g4simulation/g4eval/TrackEvaluation.cc

This fills track evaluation structure in the output disregarding whether the track has Micromegas clusters or not. 
One can always select tracks with micromegas offline using a cut like "m_tracks.nclusters_micromegas > 0"

removed check on has_mm

---

offline/packages/trackbase/AlignmentTransformation.cc
offline/packages/trackbase/AlignmentTransformation.h
offline/packages/trackbase/Calibrator.h
offline/packages/trackbase/alignmentTransformationContainer.cc
offline/packages/trackbase/alignmentTransformationContainer.h
offline/packages/trackreco/MakeActsGeometry.cc
offline/packages/trackreco/MakeActsGeometry.h

This PR allows subsystem specific misalignment factors to be set, e.g. for the MVTX a 150 micron misalignment is a lot but for the TPC this is not a lot. Will improve misaligned Acts::KF fitting performance in commissioning.

Make detector specific misalignment factors possible

---

simulation/g4simulation/g4calo/HcalRawTowerBuilder.cc
simulation/g4simulation/g4ihcal/PHG4IHCalDetector.cc
simulation/g4simulation/g4ohcal/PHG4OHCalDetector.cc

fixing HCal scintillator mapping after rotating detector
This fixes the HCal tower mapping in phi after the rotation of the detector.
Will need this change to the macros to reset the phi start of HCal towers to zero: https://github.com/sPHENIX-Collaboration/macros/pull/572

fixing hcal tower phi mapping

---

offline/packages/CaloBase/Makefile.am
offline/packages/KFParticle_sPHENIX/KFParticle_Container.cc
offline/packages/KFParticle_sPHENIX/KFParticle_sPHENIX.cc
offline/packages/KFParticle_sPHENIX/KFParticle_sPHENIX.h
offline/packages/KFParticle_sPHENIX/Makefile.am
offline/packages/NodeDump/Makefile.am
offline/packages/PHGeometry/Makefile.am
offline/packages/TrackerMillepedeAlignment/Makefile.am
offline/packages/compressor/Makefile.am
offline/packages/micromegas/Makefile.am
offline/packages/tpc/Makefile.am
offline/packages/trackbase_historic/Makefile.am
offline/packages/vararray/Makefile.am

It was observed that the KFParticle ID gets reset when written to the KFParticle container on the DST. I removed this line so we can reassociate the reco track to the KFParticle particle.

Removed line in KFParticle_Container.cc that resets track ID

---

offline/packages/tpccalib/PHTpcCentralMembraneClusterizer.cc
offline/packages/tpccalib/PHTpcCentralMembraneClusterizer.h
offline/packages/tpccalib/PHTpcCentralMembraneMatcher.cc
offline/packages/tpccalib/PHTpcCentralMembraneMatcher.h
simulation/g4simulation/g4tpc/PHG4TpcCentralMembrane.cc
simulation/g4simulation/g4tpc/PHG4TpcCentralMembrane.h
simulation/g4simulation/g4tpc/PHG4TpcElectronDrift.cc

This PR makes a number of adjustment to the central membrane generation and reconstruction code, including: 
- fixing the guarding bins and r binning of the distortion correction histograms in the CM cluster matching code
- increase the delta_r matching cut to +/- 0.5cm to accomodate input distortions while still preventing mismatches
- fix an issue with generating truth positions for the CM cluster matching: there needs to be one truth position per CM stripe and TPC side for the matching to work in both TPC sides simultaneously
- decrease the number of primary electrons per stripes from 300 to 100. 
See https://indico.bnl.gov/event/17800/contributions/70979/attachments/44597/75247/talk.pdf for details …

Central membrane

---

offline/packages/trackbase/sPHENIXActsDetectorElement.cc

If the alignment file in the cdb is not found, currently the code just defaults to the ideal geometry. This is not good for 
1. What happened today, where the CDB went down
2. In any case, if we have real alignment parameters and we can't find them for some reason, defaulting to ideal geometry will lead to some more difficult to debug behavior. 
Now we just exit if this isn't found.

Don't default to ideal geometry

---

offline/packages/TrackerMillepedeAlignment/MakeMilleFiles.cc
offline/packages/TrackerMillepedeAlignment/MakeMilleFiles.h
offline/packages/trackbase_historic/Makefile.am
offline/packages/trackbase_historic/SvtxAlignmentState.cc
offline/packages/trackbase_historic/SvtxAlignmentState.h
offline/packages/trackbase_historic/SvtxAlignmentStateLinkDef.h
offline/packages/trackbase_historic/SvtxAlignmentStateMap.cc
offline/packages/trackbase_historic/SvtxAlignmentStateMap.h
offline/packages/trackbase_historic/SvtxAlignmentStateMapLinkDef.h
offline/packages/trackbase_historic/SvtxAlignmentStateMap_v1.cc
offline/packages/trackbase_historic/SvtxAlignmentStateMap_v1.h
offline/packages/trackbase_historic/SvtxAlignmentStateMap_v1LinkDef.h
offline/packages/trackbase_historic/SvtxAlignmentState_v1.cc
offline/packages/trackbase_historic/SvtxAlignmentState_v1.h
offline/packages/trackbase_historic/SvtxAlignmentState_v1LinkDef.h
offline/packages/trackreco/ActsAlignmentStates.cc
offline/packages/trackreco/ActsAlignmentStates.h
offline/packages/trackreco/Makefile.am
offline/packages/trackreco/PHActsTrkFitter.cc
offline/packages/trackreco/PHActsTrkFitter.h

This PR is a major overhaul of the Acts Kalman Filter fit based alignment workflow. There is currently a bug that causes the iteration through Acts::Trajectory::States to look up the wrong  cluster key. The reason is that the Acts source link only stores the address to it's internal information, which means the cluster key is lost when looking in different Fun4All modules since we create cluster keys on the fly (thus, their addresses change). Therefore, currently the alignment state preparation compares the wrong cluster to the track state.
This PR fixes this problem by adding a new map object that stores the Acts …

Acts::KF Alignment Overhaul

---

offline/packages/tpccalib/TpcDirectLaserReconstruction.cc
offline/packages/tpccalib/TpcDirectLaserReconstruction.h

remove looking up ActsSurfaceMap from node tree: it is both obsolete and unused in the code
This fixes a crash (assert) when running the direct laser reconstruction

Fix TpcDirectLaserReconstruction

---

offline/packages/trackreco/PHActsTrkFitter.cc
offline/packages/trackreco/PHActsTrkFitter.h
offline/packages/trackreco/PHActsVertexPropagator.cc
offline/packages/trackreco/PHSiliconTpcTrackMatching.cc
offline/packages/trackreco/PHSiliconTpcTrackMatching.h

Allows tracks which only have TPC clusters to be fitted by PHActsTrkFitter and added to the SvtxTrackMap. 
This also adds a "pp mode" switch to PHActsTrkFitter that only strictly checks for crossing info when in pp running. Since TPC-only tracks have no crossing info, their crossing in AuAu running is assumed to be 0. In pp running, TPC-only tracks are still skipped. …

Enabled TPC-only track fitting

---

calibrations/tpc/generator/AnnularFieldSim.cc
calibrations/tpc/generator/AnnularFieldSim.h

This adds a new feature to the distortion generator, allowing to write out the internal representation of the charge distritbuion in the TPC for debugging purposes
Minor mods to the AnnularFieldSim code.
It might be slightly nicer to have this handle the field sim twin for north and south together, rather than exporting only north or south's histogram.
[comment]: <> ( In case this is a draft PR, e.g. for running checks using Jenkins, please make the pull request as a draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/ …

Distortion gen save charge hist

---

offline/packages/TrackerMillepedeAlignment/MakeMilleFiles.cc
offline/packages/TrackerMillepedeAlignment/MakeMilleFiles.h
offline/packages/trackreco/ActsAlignmentStates.cc
offline/packages/trackreco/ActsAlignmentStates.h

This fixes the Acts alignment state creation to take the fully fitted tracks and produce sensible alignment parameters with millepede in the case of perfect alignment. From the full alignment workflow I can produce sub O(mrad) and O(micron) alignment residuals in the MVTX and INTT with the fully fitted tracks now with the default geometry. Need to start testing with actual misaligned surfaces.

Fitted Alignment Parameters

---

offline/packages/CaloBase/TowerInfo.h
offline/packages/CaloBase/TowerInfoContainer.cc
offline/packages/CaloBase/TowerInfoContainer.h
offline/packages/CaloBase/TowerInfoContainerv1.cc
offline/packages/CaloBase/TowerInfoContainerv1.h
offline/packages/CaloBase/TowerInfov1.cc
offline/packages/CaloBase/TowerInfov1.h

This PR restructures the on the fly map generation to happen during the call for the iterator range rather than happen as a separate stage. Prevents the user themselves from directly accessing the map, and fixes a problem with the map not being reset between events. Additionally standardized the calls to match that of other classes

Reformatting the on the fly map production of the TowerInfoContainer class

---

offline/packages/CaloReco/CaloTowerBuilder.cc
offline/packages/CaloReco/CaloTowerBuilder.h
offline/packages/CaloReco/Makefile.am

Module to reconstruct the various calorimeter layers from PRDF to DST
It introduces the jet reconstruction code to go from raw PRDFs to TowerInfo objects stored in DSTs.

Calorimeter Reconstruction Code

---

offline/packages/tpccalib/TpcDirectLaserReconstruction.cc
offline/packages/tpccalib/TpcDirectLaserReconstruction.h

This PR fixes how hit z position is calculated from hits time bin.
This matches what is done in TpcClusterizer and fixes direct laser reconstruction

Direct laser reconstruction

---

simulation/g4simulation/g4mvtx/PHG4MvtxSubsystem.cc

point to a symbolic link file with proper material
This PR change the filename for the gdml file used to create the MVTX end_wheel geometry with right material (Al)

YCM rename gdml file for end_wheels

---

offline/packages/CaloBase/TowerInfoContainer.h
offline/packages/CaloBase/TowerInfoContainerv1.cc
offline/packages/CaloBase/TowerInfoContainerv1.h

This PR adds the ability for the CaloInfoContainer to decode key values (I.E. etabin phi bin coordinates) into the corresponding tower index. This combined with the pre-allocation of the TowerInfoContainer size enables the user to write towers to the object in any order (key for implementation into the simulations without a significant rewrite).

Add ability to fill TowerInfoContainer based on physical location

---

offline/packages/trackbase/ActsGeometry.cc

This PR improves the lookup speed of tpc subsurfaces by a factor of 10 by passing the surface vector by reference instead of copy.

Tpc subsurface lookup speed up

---

calibrations/calorimeter/calo_emc_pi0_tbt/CaloCalibEmc_Pi0.cc

bug fix which removed spurious extra line that was added in last pr (no one nows how it got added) that sneakily reduced the number of clusters saved in the output and therefore available for iterating in the later iterations.

removed spurious line bug added in previous pr

---

simulation/g4simulation/g4epd/PHG4EPDDetector.cc

PR rotates epd sectors so that the first sector starts a phi = 0. See attached image for details- The numbers [0-11] are the sector ids.

shifting epd sector phi shift

---

simulation/g4simulation/g4ohcal/PHG4OHCalDetector.cc

Allow installing new G4 subsystem installed inside the HCal envelope air volume via macros, in particular the HCal support rings.

Allow installing new G4 subsystem installed inside the HCal envelope 

---

simulation/g4simulation/g4detectors/PHG4CylinderDetector.cc
simulation/g4simulation/g4detectors/PHG4CylinderSubsystem.cc
simulation/g4simulation/g4ohcal/PHG4OHCalSubsystem.h

1. Enabling `CanBeMotherSubsystem()` for outer HCal for support ring installation, which was missed in https://github.com/sPHENIX-Collaboration/coresoftware/pull/1811 
2. Allow [`PHG4CylinderSubsystem`](https://github.com/sPHENIX-Collaboration/coresoftware/compare/master...blackcathj-ohcal-try2?quick_pull=1#diff-61dfe0fd92407a82134dc0182c34afe81d22a83a27b5807e1e907add0af7bd61) to cover partial azimuth, configurable from macro, e.g.: 
```c++
PHG4CylinderSubsystem * cyl = new PHG4CylinderSubsystem("TestCylinder"); …
```

Enabling `CanBeMotherSubsystem()` and allowing PHG4CylinderSubsystem to cover partial azimuth

---

simulation/g4simulation/g4micromegas/PHG4MicromegasDetector.cc

this allows not to have to create a G4Rotation on the stack, than then never gets deleted

use G4Transform3D to pass positioning of Micromegas modules to geant4

---

offline/packages/CaloReco/CaloWaveformProcessing.cc
offline/packages/CaloReco/CaloWaveformProcessing.h

This PR introduce a new waveform processing option that use a cubic spline to interpolate three samples around the maximum sample, and then solve for the local maximum analytically(see the calculation for the derivative [here](https://root.cern.ch/doc/master/TSpline_8h_source.html#l00134)) giving a peak ADC and time, the pedestal is calculated as the average of the first three samples. The processing speed of this method is fast, during the benchmarking it takes 6 ms per event for 3072 calorimeter channels(in comparison it takes on average 360 ms per event for the template fit).
This could serve as a fast alternative …

New interpolation peak extraction method for CaloWaveformProcessing

---

offline/framework/fun4all/Fun4AllBase.cc

If someone creates a module and gave it an empty string as name, it leads to a failure creating a TDirectory for this module deep in the guts of fun4all. This PR makes the Fun4AllBase ctor quit if it gets an empty string as a name

quit if the name of a funall object is an empty string

---

simulation/g4simulation/g4tpc/PHG4TpcCentralMembrane.cc
simulation/g4simulation/g4tpc/PHG4TpcCentralMembrane.h

Added event number counter to CM hit generation and a modulo so that hits will only be generated every Nth event (event%modulo != 0 will increment event number and return). Default modulo is 10. Also added function to change modulo in macro and added corresponding function to macro.
feature: only generate CM hits every Nth event …

Added event number tracking and modulo to CM hit generation

---

offline/packages/KFParticle_sPHENIX/KFParticle_sPHENIX.cc
offline/packages/ResonanceJetTagging/ResonanceJetTagging.cc
offline/packages/ResonanceJetTagging/ResonanceJetTagging.h

- fixed a typo in KFParticle printout
- generalized tagging code to run on the multiple HF tagged particles without the need of recompiling - a new parameter has been added as an input to the code which must be properly reflected by the analysis/macro
- removed hardcoded variables, moved from arrays to vectors
- fixed a bug to properly select jet algorithm and scheme, now it properly set them instead of using CA and Et2
- in case the HEPMC vector does not exist, it will look for GEANT vertex - this fixes crashes on ccbar data samples
- fixed memory leaks using valgrind, insure tested
while running on ccbar sample, there is an issue that the reconstructed jets does not have truth …

Updates to Jet Tagging macros - new features, bug fixes

---

simulation/g4simulation/g4micromegas/PHG4MicromegasDetector.cc
simulation/g4simulation/g4micromegas/PHG4MicromegasDetector.h

This is the first of a few PR aiming at making the TPOT description offline more realistic in terms of detector positioning, with respect to what was surveyed in the IR. 
This one: 
- fix  the z positioning of the central sector Micromegas detectors to better match the CAD model. (beside, there was a typo in the old positioning that was making the last detector at the wrong z) 
- re-organize GEANT4 volumes creation so that it should now be possible to assign different placements to the Z and Phi layers of a given module.
@pinkenburg once Jenkins is finished, this can be merged as is. However I plan to push a couple more commits on this topic before end of the week.
[comment]: <> ( What types of changes does your code …

Tpot geometry

---

offline/packages/micromegas/CylinderGeomMicromegas.cc
offline/packages/trackreco/MakeActsGeometry.cc
simulation/g4simulation/g4micromegas/Makefile.am
simulation/g4simulation/g4micromegas/PHG4MicromegasDetector.cc
simulation/g4simulation/g4micromegas/PHG4MicromegasSurvey.cc
simulation/g4simulation/g4micromegas/PHG4MicromegasSurvey.h

This is the last update about TPOT geometry, this time implementing the survey geometry completely. 
Now that not all tiles seat at the exact same radius, MakeActsGeometry had to be modified to keep associating the TPOT tiles to the proper surfaces
Some modifications were also necessary to CylinderGeomMicromegas

Tpot geometry 3

---

simulation/g4simulation/g4tpc/TpcClusterBuilder.cc
simulation/g4simulation/g4tpc/TpcClusterBuilder.h

Function cluster_and_reset in TpcClusterBuilder copied from TpcClusterizer but missing:
if(side == 0) clusz = -clusz;
clust = clust + m_sampa_tbias;
Also, iphi and iz wrongly used a relative bin number.
This fixed all the issues.

Fixed phi and z bin number and added sampa_tbias

---

simulation/g4simulation/g4main/PHG4Reco.h

This PR reverts the default decayer back to pythia6. EvtGen modifies cout which affects all printouts, That needs to be fixed before we can go back to the EvtGen decayer. Also - now it is possible to change the decayer in a macro

fall back to pythia6 decayer

---

offline/packages/CaloBase/TowerInfoContainer.cc
offline/packages/CaloBase/TowerInfoContainer.h
offline/packages/CaloBase/TowerInfoContainerv1.h
offline/packages/NodeDump/DumpTowerInfoContainer.cc

This PR adds a missing getTowers() method to the base class. The code is in real need of cleanup, typedefs are all over the place, unimplemented access methods in the base class are confusing, and you want a const iterator access, not just iterator

Fix towerinfo

---

simulation/g4simulation/g4tpc/PHG4TpcDigitizer.cc
simulation/g4simulation/g4tpc/PHG4TpcDigitizer.h

This PR adds a flag that tells PHG4TpcDigitizer to skip adding noise to all empty time bins. If the flag is set to true, the code adds noise only to time bins that contain a g4hit, and the four time bins following a hit above threshold. This reproduces the old behavior.
The flag is intended to be used only to speed up execution for testing purposes. It reduces the time for TPC digitization in a few-track event from 10.5 s to 0.6 s. For AuAu events it makes no significant …

Add flag to skip noise addition for empty time bins

---

offline/packages/tpccalib/TpcDirectLaserReconstruction.cc
offline/packages/tpccalib/TpcDirectLaserReconstruction.h
simulation/g4simulation/g4tpc/PHG4TpcDirectLaser.cc

Files Affected:
offline/packages/tpccalib/TpcDirectLaserReconstruction.cc
offline/packages/tpccalib/TpcDirectLaserReconstruction.h 
simulation/g4simulation/g4tpc/PHG4TpcDirectLaser.cc
Changes:
TpcDirectLaserReconstruction: Adds in functionality for locating clusters from laser fire hits with respect to TPC GEM Modules and counting how many clusters hit which GEMs. Also adds additional histograms useful for visualization/debugging.
PHG4TpcDirectLaser: Clears up ambiguity with angles in AimToThetaPhi (line 272) for abitrary pointing angle in process_event. User must multiply by deg_to_rad in G4_TPC.
TODO:
Need to make relative angle finding (line 390 - TpcDirectLaserReconstruction) more fancy implementation and re-adjust track …

Add functionality for counting number of GEM modules hit + clearing up ambiguity w/ arbitrary pointing

---

simulation/g4simulation/g4decayer/EvtGenExtDecayerPhysics.cc

EvtGen model initialization (carried out as class member initialization in `G4VExtDecayer`) changed the behavior of std::cout float print. Recover the default float print format

Recover `std::cout` to previous behavior after EvtGen load

---

simulation/g4simulation/g4tpc/PHG4TpcDirectLaser.cc

Files Affected:
PHG4TpcDirectLaser.cc
Changes:
1. Adjusts the position of the 4 line lasers to their correct position on the TPC (lines 356, 362)
2. Correct the pointing of the lasers by making the axis of rotation for the phi angle direction dependent (-1 for +z laser, +1 for -z laser). (lines 444 & 445)

Fixing issue with pointing of lasers in TPC

---

offline/packages/tpccalib/TpcDirectLaserReconstruction.cc
offline/packages/tpccalib/TpcDirectLaserReconstruction.h

Files Affected:
TpcDirectLaserReconstruction.cc
TpcDirectLaserReconstruction.h
Changes:
Takes GEM counting functionality and switches it from counting clusters from laser fires to counting hits associated to laser tracks. This is to get around a bug in clustering which needs more time to be fixed. In addition histograms are added to count the number of unique G4 layers the hits from a laser occur in, and relative angle finding histograms for all 8 lasers.
TODO:
Must debug clustering. There is an issue with tracks at middle theta angles (~40 - 60 degrees) that breaks clustering. Double check the Locate function and make sure its not double counting. Also implement finite size sector boundaries.

Moving GEM counting functionality to associated hits instead of clusters + adding histograms

---

offline/framework/frog/CreateFileList.pl

This PR changes the default for CreateFileList.pl to run 6, jenkins does not test this - lets skip it
[skip-ci]

make run 6 the default for CreateFileList.pl

---

simulation/g4simulation/g4tpc/PHG4TpcElectronDrift.cc
simulation/g4simulation/g4tpc/TpcClusterBuilder.cc

This request undoes a few lines modified in [PR 1834](https://github.com/sPHENIX-Collaboration/coresoftware/pull/1834/files) which inadvertantly place the clusters reconstruction out of bounds and therefore don't make truth clusters for many tracks. I think this re-correction is the proper way to do things but will cast a weathered eye over it tomorrow, and would appreciate any expert opinion.
Essentially what happend in PR 1834 is the offset corrections to phi and time put the clusters out of bounds for the number of possible bins (the checks at TpcClusterBuilder.cc lines 105 and 109) and therefore removes many …

Update the phi and z clustering locations

---

offline/packages/CaloBase/TowerInfoContainerv1.cc

…range
trivial change to the code to add a catch for "packet < 0 || packet > 3" within the encode emcal and encode hcals in order to introduce a crash if attempting to access an array from outside its bounds.

updated the encode_ key classes to include a catch for packet out of range for arrays

---

offline/packages/trackreco/PHActsTrkFitter.cc
offline/packages/trackreco/PHActsTrkFitter.h

This provides an option to skip an arbitrary layer in the track fit. If a layer is requested to skip, any measurement associated to a track in that layer is skipped over and not added to the Acts kalman filter fit.
@blackcathj 

Skip layer in track fit

---

offline/packages/micromegas/Makefile.am
offline/packages/micromegas/MicromegasMapping.cc
offline/packages/micromegas/MicromegasMapping.h
offline/packages/micromegas/MicromegasRawDataDecoder.cc
offline/packages/micromegas/MicromegasRawDataDecoder.h

This implements a small class to handle micromegas mapping, namely: 
- fiber (or fee) id mapping to hitsetkey and detector names
- channel_id (0-255) into physical strip number
For the first, hitsetkeys and detector names are mapped to reality and is hardcoded, according to diagram at https://wiki.sphenix.bnl.gov/index.php/File:ModuleMapping_hp.png
The mapping to fee_id (or fiber_id) is also hardcoded and matches noise data taken at 1008 on March 2nd 2023, but changing to read the mapping from an actual text file should be straightforward.
For the second (channel id to physical strip), right now this is only a placeholder. True implementation is ongoing work.
[comment]: <> ( What types of changes does your code introduce? …

Micromegas mapping

---

offline/packages/trackbase/ActsAborter.h
offline/packages/trackbase/Makefile.am
offline/packages/trackreco/Makefile.am
offline/packages/trackreco/PHActsTrackPropagator.cc
offline/packages/trackreco/PHActsTrackPropagator.h

This adds a module that uses the Acts propagator to propagate the track map to an arbitrary chosen user defined layer in sPHENIX coordinates. It adds an Acts::Aborter that tells the propagator to abort propagation at the sensitive surfaces of the provided layer. It can also act as a template for other Acts propagation modules which need custom defined aborters (e.g. those envisioned for iterative tracking to propagate TPC tracks back to the silicon).
You can add it to your macro and select the layer like the following:
```
auto prop = new PHActsTrackPropagator;
prop->setPropagationLayer(someLayer); …
```

Acts propagator with custom aborter for sPHENIX defined layer

---

offline/packages/TrackerMillepedeAlignment/HelicalFitter.h

Some private functions in HelicalFitter are useful for analysis modules; this commit makes them public instead of private, so they can be used outside of the HelicalFitter module.
Module that uses these: https://github.com/sPHENIX-Collaboration/analysis/pull/67

Exposes useful functions in HelicalFitter

---

offline/packages/tpccalib/PHTpcResiduals.cc
offline/packages/tpccalib/PHTpcResiduals.h

The old code was crashing with latest versions of ACTS because one cannot create a BoundTrackParameter with a nullptr surface (failed assert)

use std::optional to detect extrapolation failures.

---

offline/packages/trackreco/ALICEKF.cc

A check on the elements of the transformation between the local-coordinates and global-coordinates covariance matrices has been interfering with cosmics reconstruction. If there's a problem with these elements, then the offending seed is currently thrown out. Now that the covariance matrix is not included in the TrackSeed object, and is effectively discarded after the seeding stage anyway, this check is no longer necessary, both in cosmics reconstruction and in the general tracking chain. This PR removes that check.
[comment]: <> ( In …

ALICEKF cosmics compatibility changes

---

offline/packages/TrackerMillepedeAlignment/HelicalFitter.h
offline/packages/trackreco/PHSiliconHelicalPropagator.cc
offline/packages/trackreco/PHSiliconHelicalPropagator.h

For cosmics tracking, we use the HelicalFitter class to find silicon clusters associated with a given TPC seed. The module PHSiliconHelicalPropagator does this, modifying existing SvtxTracks (converted from TPC seeds) to insert a corresponding silicon seed.
This PR also makes HelicalFitter::addSiliconClusters a public method, as it's needed by this module. …

Introduce PHSiliconHelicalPropagator

---

offline/packages/trackreco/MakeActsGeometry.cc
offline/packages/trackreco/PHCASeeding.cc

Remove print out from CASeeder
Fixes the scan build error introduced by me and somehow not caught by jenkins on the initial PR and also removes some verbosity from tpc seeding.

Fix scan build error

---

simulation/g4simulation/g4mvtx/PHG4MvtxHitReco.cc

put print statement behind a `if (Verbosity()>5)` to remove excessive output

---

offline/packages/trackreco/Makefile.am
offline/packages/trackreco/PHSiliconHelicalPropagator.cc
offline/packages/trackreco/PHSiliconHelicalPropagator.h

PHSiliconHelicalPropagator originally worked by modifying SvtxTrack objects. This made it incompatible with PHMicromegasTpcTrackMatching, which acts on SvtxTrackSeed objects. This PR converts PHSiliconHelicalPropagator into something that creates SvtxTrackSeeds, so micromegas clusters can be incorporated.
In addition, it now creates the silicon seed container if it's not found, so no silicon seeding module needs to be run beforehand. …

Redesign PHSiliconHelicalPropagator for micromegas matching compatibility

---

offline/packages/trackreco/PHSiliconHelicalPropagator.cc
offline/packages/trackreco/PHSiliconHelicalPropagator.h

In order to match TPOT clusters using current machinery, the crossing of the silicon seed paired with the TPC seed must be known. PHSiliconHelicalPropagator now does this, by choosing the most common crossing associated with the hits in any INTT clusters in the silicon seed.

Added crossing determination to PHSiliconHelicalPropagator

---

offline/packages/trackreco/ActsPropagator.cc
offline/packages/trackreco/ActsPropagator.h
offline/packages/trackreco/PHActsTrackProjection.cc
offline/packages/trackreco/PHActsTrackProjection.h

The track projection module was running with the default field map which only exists in the tracking volume when it should be running with a constant field. This fixes that

Fix constant field in projection

---

offline/framework/fun4all/Fun4AllServer.cc
offline/framework/fun4all/Fun4AllSyncManager.h

This PR adds a flag which enables running different runs under other sync managers. Needed to read fake raw data while reading simulated DSTs to run the actual processing

add flag to override exit when mixing runs in embedding

---

offline/packages/KFParticle_sPHENIX/KFParticle_Tools.cc
offline/packages/KFParticle_sPHENIX/KFParticle_Tools.h
offline/packages/KFParticle_sPHENIX/KFParticle_sPHENIX.h

After discussions in the HF/Q TG meeting on 3/24/23, I've added the ability to select tracks with a minimum umber of MVTX or TPC hits. This is defautlted to 3 and 20 respectively. The user can set this in their macro with:
```c++
void setMinMVTXhits(int nHits) { m_nMVTXHits = nHits; }
void setMinTPChits(int nHits) { m_nTPCHits = nHits; }
```
Also, I added a flag so you can disable the extrapolation of tracks to their secondary vertices. This was found to cause issues in K-short resonstuction. This flag is defaulted to true (whcih covers most use scenarios).
```c++
void extraolateTracksToSV(bool extrapolate) { …
```

Kf particle

---

offline/packages/trackreco/PHActsTrkFitter.cc
offline/packages/trackreco/PHActsTrkFitter.h

Updates the skip layer feature of the track fit to use multiple layers if desired (e.g. for silicon-TPOT fitting)

Generalize ignore layer in track fit

---

offline/packages/tpccalib/PHTpcResiduals.cc

a one line commit to make PHTpcResiduals not crash when switching to cluster v5

adapt to cluster v5

---

offline/packages/trackreco/PHActsTrkFitter.cc
offline/packages/trackreco/PHActsTrkFitter.h

This PR recovers the performance of the silicon+TPOT fit. It removes the use of the directed fitter and just uses the standard Acts::KF for the fit, which simplifies the code. The attached plot shows the performance of the silicon only fit (left) vs. silicon + TPOT fit (right) for single tracks.
[fit_tpot_silicon.pdf](https://github.com/sPHENIX-Collaboration/coresoftware/files/11100983/fit_tpot_silicon.pdf)

Silicon+TPOT fit update

---

offline/packages/trackreco/PHActsTrkFitter.cc
offline/packages/trackreco/PHActsTrkFitter.h

Reverts sPHENIX-Collaboration/coresoftware#1917
This reverts the above PR. Interestingly the performance with the full fit seems to neglect the TPOT measurement in the residual calculations, despite it explicitly being added and propagated to by Acts when performing the Kalman Filter. Even more strangely, the fit performance with the TPOT measurement is improved substantially as one would expect. So somehow this keeps similar performance in the actual fit but worsens the residuals. Reverting this for now until more debugging can be performed.

Revert "Silicon+TPOT fit update"

---

simulation/g4simulation/g4bbc/BbcSimReco.cc

This PR removes the vertex printout for the first 20 event, now behind Verbosity() setting
[skip-ci]

put printout behind verbosity

---

offline/packages/trackreco/ActsPropagator.cc
offline/packages/trackreco/ActsPropagator.h
offline/packages/trackreco/PHActsTrackProjection.cc
offline/packages/trackreco/PHActsTrackPropagator.cc

This PR makes the propagation machinery consistently use Acts units of mm and GeV. It is noted in the comments, and is not easily modified because of the const correctness of the package. The PR also adds some comments to note this for downstream users.

Consistent use of Acts units

---

offline/packages/CaloReco/CaloWaveformFitting.cc
offline/packages/CaloReco/CaloWaveformFitting.h

Resolved the need for the template fit function being a static in the CaloWaveformFitting code. This introduced issues when processing multiple calorimeter systems in the same job. 

fixed the need for the template functions to be static in CaloWaveformFitting

---

offline/packages/epd/EpdGeom.h
offline/packages/epd/EpdGeomV1.cc
offline/packages/epd/EpdGeomV1.h
offline/packages/epd/Makefile.am
simulation/g4simulation/g4epd/PHG4EPDModuleReco.cc
simulation/g4simulation/g4epd/PHG4EPDModuleReco.h

This PR adds sEPD geometry using TowerInfoDefs keys and fills in the geometry in the tile reconstruction

Updating sEPD geometry with TowerInfoDefs

---

simulation/g4simulation/g4bbc/BbcSimReco.cc
simulation/g4simulation/g4bbc/BbcSimReco.h
simulation/g4simulation/g4vertex/GlobalVertex.h
simulation/g4simulation/g4vertex/GlobalVertexFastSimReco.cc
simulation/g4simulation/g4vertex/GlobalVertexFastSimReco.h
simulation/g4simulation/g4vertex/GlobalVertexMap.cc
simulation/g4simulation/g4vertex/GlobalVertexMapv1.cc
simulation/g4simulation/g4vertex/GlobalVertexMapv1.h
simulation/g4simulation/g4vertex/GlobalVertexReco.cc
simulation/g4simulation/g4vertex/GlobalVertexReco.h
simulation/g4simulation/g4vertex/GlobalVertexv1.cc
simulation/g4simulation/g4vertex/GlobalVertexv1.h
simulation/g4simulation/g4vertex/Makefile.am

This PR adds the new Bbc Vertex to our global vertices. Major rewrite - now vertices are added via an enum which dtermines the order of precedence, not just the order in which vertices are added which allows now to have multiple modues adding vertices independently. Still needs a lot of work - the Bbc currently produces two vertex objects, the global reco for the svtx vertex needs the old bbc vertex map which is not provided anymore. Also no consistency between old smeared t0 and bbc reconstructed t0 (~8ns offset)  
[comment]: <> ( What does this PR do? …

Bbc vertex

---

offline/packages/PHField/PHField2D.cc
offline/packages/PHField/PHField2D.h
offline/packages/PHField/PHField3DCartesian.cc
offline/packages/PHField/PHField3DCartesian.h
offline/packages/PHField/PHField3DCylindrical.cc
offline/packages/PHField/PHField3DCylindrical.h
offline/packages/PHField/PHFieldConfig.cc
offline/packages/PHField/PHFieldConfig.h
offline/packages/PHField/PHFieldConfigv1.cc
offline/packages/PHField/PHFieldConfigv1.h
offline/packages/PHField/PHFieldConfigv2.cc
offline/packages/PHField/PHFieldConfigv2.h
offline/packages/PHField/PHFieldUniform.cc
offline/packages/PHField/PHFieldUtility.cc
offline/packages/PHField/PHFieldUtility.h
simulation/g4simulation/g4ohcal/PHG4OHCalDetector.cc
simulation/g4simulation/g4ohcal/PHG4OHCalFieldSetup.cc
simulation/g4simulation/g4ohcal/PHG4OHCalFieldSetup.h
simulation/g4simulation/g4ohcal/PHG4OHCalSteppingAction.cc
simulation/g4simulation/g4ohcal/PHG4OHCalSubsystem.cc
simulation/g4simulation/g4ohcal/PHG4OHCalSubsystem.h

This PR finally allows to run sPHENIX with a uniform field instead of fieldmaps. Needed for zero field (for real sims) and quick tests since the fieldmap takes time and tons of memory. For a uniform field the outer hcal does not load it's absorber map which crashed things before.
Replaced the old boost::tuples by std::tuples in our fieldmaps …

Ohcal const field

---

simulation/g4simulation/g4bbc/BbcSimReco.cc

The BbcSimReco kept crashing. The reason was that arm 0 of the BbcNS TClonesArray has to be filled if arm 1 is set. Otherwise this crashes during writing in TTree->Write(). If there is no signal in the arm it's now filled with -99999. We should later replace this with nan but then we have competing bbc output objects  …

fill bbcns with -999999 if arm has no signal to avoid crashes

---

simulation/g4simulation/g4intt/PHG4InttDigitizer.cc
simulation/g4simulation/g4intt/PHG4InttDigitizer.h

Small change in code for efficiency and readability. See changes in code. Swap from forced loop over 
`vector< pair<bound0, bound1>,pair<bound1,bound2>,...pair<boundN,FLT_MAX>>` to find a range to `std::upper_bound(vec.begin(), vec.end(),val)` where vec is now `bound0, bound1, ..., boundN`.

Small commit to code -- efficiency of lookup in adc value

---

offline/packages/CaloReco/Makefile.am

I need to work on the dbtools in a life environment. They are commented out from the build but CaloReco uses them in one source. I took it out of the Makefile.am so the build does not crash. Will put it back when this is done
[skip-ci]

remove CaloTowerCalib.cc to build without dbtools

---

offline/packages/tpccalib/PHTpcResiduals.cc
offline/packages/tpccalib/PHTpcResiduals.h

This cleans up the Distortion reconstruction code by stripping away all the evaluation code. It is now (thanks to Joe !) in QAG4SimulationDistortions.
Also, added the possibility to cut on the mean pT of the tracks considered for distortion reconstruction. (I had this in my own repository since forever and never pushed it to the official code). The default cut is 0.5 GeV/c. …

Distortion cleanup

---

offline/packages/trackreco/PHActsTrackProjection.cc

State of track projections was changed to save at the pathlength which is typical for the actual track states. For the calo projections it makes it hard to look up the state info, so this changes the saving back to the calo radius.

Save state at calo radius

---

offline/packages/bbc/BbcReconstruction.cc
offline/packages/bbc/BbcReconstruction.h

This PR fixes a bug I introduced by creating a histogram every event, which root complains about. This PR moves the histo creation to one time in Init

Fix bbc root memory issue

---

offline/packages/globalvertex/GlobalVertexReco.cc

There are some instances (e.g. single tracks) where, despite the vertex id being unavailable, the vertex map returns a non-nullptr vertex. To fix the unassigned track to vertex association, just check if the end of the map has been reached.

Fix vertex lookup

---

offline/packages/mvtx/Makefile.am
offline/packages/mvtx/MvtxRawDataDecoder.cc
offline/packages/mvtx/MvtxRawDataDecoder.h

first version of MVTX data unpacker, currently no online_distributions calls are implemented since there is no decoder, there is hardcoded fill for the DST: 1 hitsetkey with 10 hitsets
first version of MVTX data unpacker
implement actual online_distributions calls once we have decoder

first version of MVTX unpacker

---

simulation/g4simulation/g4tpc/PHG4TpcDirectLaser.cc
simulation/g4simulation/g4tpc/PHG4TpcDirectLaser.h

Files Affected:
-  simulation/g4simulation/g4tpc/PHG4TpcDirectLaser.h
-  simulation/g4simulation/g4tpc/PHG4TpcDirectLaser.cc
Changes:
- Added functionality to open a .root file which contains the theta and phi angles required to hit all the "pixels" of the central membrane.
- Pull NTuple of angles from root file
- Provides NTuple angles to the laser to be fired
TODO:
- suppress std::cout statements in AimToPatternStep_File function in the .cc
- general cleanup

Adding Functionality for Laser Stepping Over Angles in ROOT file

---

offline/packages/globalvertex/GlobalVertexReco.cc

This just checks for the track map instead of returning `ABORTEVENT` so that DSTs where no track map is made can still fill the global vertex reco map

Check for track map rather than returning

---

offline/packages/TrackerMillepedeAlignment/AlignmentDefs.cc
offline/packages/TrackerMillepedeAlignment/AlignmentDefs.h
offline/packages/TrackerMillepedeAlignment/HelicalFitter.cc
offline/packages/TrackerMillepedeAlignment/HelicalFitter.h
offline/packages/TrackerMillepedeAlignment/MakeMilleFiles.cc
offline/packages/TrackerMillepedeAlignment/MakeMilleFiles.h
offline/packages/TrackerMillepedeAlignment/Makefile.am

This PR condenses duplicate code into an `AlignmentDefs` class which both the helical and acts based fitter can access. This simplifies the code and makes sure we have consistent labeling schemes for both methods. It also adds a scheme by which each layer can have an error inflation factor applied to it, to artificially blow up the measurement uncertainties on a layer by layer basis since pede only has the ability to increase all errors in the same way. …

Common alignment tools

---

offline/packages/micromegas/Makefile.am
offline/packages/micromegas/configure.ac

title says it all. 
"online" library only includes MicromegasDefs and MicromegasMapping.
MicromegasDefs depends on TrkrDefs, and the corresponding trimmed libtrackbase_io that chris just built for online
This will avoid duplicated code in the TPOT online monitoring

enable online build

---

offline/packages/globalvertex/GlobalVertexReco.cc
offline/packages/globalvertex/GlobalVertexv1.cc

This PR removes print out that is just wrong from the GlobalVertexv1::identify function and adds global vertices to the map based on the current map size. 

fix: GlobalVertex ID 

---

offline/packages/TrackingDiagnostics/TrackResiduals.cc
offline/packages/TrackingDiagnostics/TrackResiduals.h

Adds an option to dump the alignment state information fed to pede into a tree instead of the raw residual information.

Alignment Tree Dump

---

offline/packages/micromegas/Makefile.am
offline/packages/micromegas/MicromegasRawDataCalibration.cc
offline/packages/micromegas/MicromegasRawDataCalibration.h
offline/packages/micromegas/MicromegasRawDataEvaluation.cc
offline/packages/micromegas/MicromegasRawDataEvaluation.h
offline/packages/micromegas/MicromegasRawDataEvaluationLinkDef.h

Moved raw data evaluation from MicromegasRawDataCalibration to ..RawDataEvaluation
Use a TTree rather than histograms
The evaluation tree can be used to estumate pedestal, study common noise, signal timing, etc. 

Micromegas raw data evaluation

---

offline/framework/fun4all/Fun4AllBase.h
offline/framework/fun4all/Fun4AllDstInputManager.cc
offline/framework/fun4all/Fun4AllDstInputManager.h
offline/framework/fun4all/Fun4AllHistoManager.cc
offline/framework/fun4all/Fun4AllMemoryTracker.cc
offline/framework/fun4all/Fun4AllOutputManager.h
offline/framework/fun4all/Fun4AllRunNodeInputManager.cc
offline/framework/fun4all/Fun4AllRunNodeInputManager.h
offline/framework/fun4all/Fun4AllServer.cc
offline/framework/fun4all/Fun4AllServer.h
offline/framework/fun4all/Fun4AllSyncManager.cc
offline/framework/fun4all/Fun4AllSyncManager.h
offline/framework/fun4all/Makefile.am
offline/framework/fun4all/PHTFileServer.cc
offline/framework/fun4all/PHTFileServer.h
offline/framework/fun4all/SubsysReco.h
offline/framework/fun4all/TDirectoryHelper.cc

This PR adds a new input manager to read only runwise information (needed to replace geometry node in sim DSTs)

add input manager for run nodes (no eventwise dst)

---

offline/packages/CaloBase/TowerInfoContainer.h
offline/packages/CaloBase/TowerInfoContainerv1.cc
offline/packages/CaloBase/TowerInfoContainerv1.h
offline/packages/CaloBase/TowerInfoDefs.cc
offline/packages/CaloBase/TowerInfoDefs.h
offline/packages/CaloReco/CaloTowerBuilder.cc
offline/packages/CaloReco/CaloTowerBuilder.h

This PR adds the MBD to TowerInfoContainer and CaloTowerBuilder with the mapping implemented.
Right now the default processing method is FAST, need to switch that to template fit when we have it. Also the encoding method from this PR only gives the south/north side, time/charge type, and channel number of the MBD, maybe need to add a channel number -> eta/phi or xyz map later(?) …

add MBD to TowerBuilder

---

offline/packages/tpc/TpcLoadDistortionCorrection.cc
offline/packages/tpccalib/PHTpcCentralMembraneMatcher.cc

Moved the TPC distortions to be stored on the runNode rather than the dstNode. This allows them to persist across events until they are overwritten, which is essential for the fluctuation corrections.

TPC Distortions on runNode

---

offline/packages/trackbase/AlignmentTransformation.cc
offline/packages/trackbase/AlignmentTransformation.h
offline/packages/trackbase/Calibrator.h
offline/packages/trackbase/alignmentTransformationContainer.cc
offline/packages/trackbase/alignmentTransformationContainer.h
offline/packages/trackreco/MakeActsGeometry.cc
offline/packages/trackreco/MakeActsGeometry.h

Allows certain layers to blow up measurement covariance in the KF instead of an entire subsystem.
https://github.com/sPHENIX-Collaboration/macros/pull/636

Enable layer misalignment in acts kf

---

offline/packages/trackreco/MakeActsGeometry.h

Removes warning about misalignment that is disrupting macro processing for some in nvim, which is why this behavior hasn't shown up in any of the builds apparently

Remove verbosity

---

simulation/g4simulation/g4tpc/PHG4TpcElectronDrift.cc
simulation/g4simulation/g4tpc/TpcClusterBuilder.cc

Checks for a rare seg fault and removes some verbosity left in tpc cluster builder. Also uses switches to using TrkrClusterv5 since that is our latest cluster version.

Clean up TpcClusterBuilder

---

simulation/g4simulation/g4detectors/LightCollectionModel.cc
simulation/g4simulation/g4detectors/LightCollectionModel.h
simulation/g4simulation/g4detectors/Makefile.am
simulation/g4simulation/g4detectors/PHG4FullProjSpacalCellReco.cc
simulation/g4simulation/g4detectors/PHG4FullProjSpacalCellReco.h
simulation/g4simulation/g4detectors/PHG4FullProjTiltedSpacalDetector.cc
simulation/g4simulation/g4detectors/PHG4FullProjTiltedSpacalDetector.h
simulation/g4simulation/g4detectors/PHG4SpacalDetector.cc
simulation/g4simulation/g4detectors/PHG4SpacalDetector.h
simulation/g4simulation/g4detectors/PHG4SpacalSteppingAction.cc
simulation/g4simulation/g4detectors/PHG4SpacalSteppingAction.h
simulation/g4simulation/g4detectors/PHG4SpacalSubsystem.cc
simulation/g4simulation/g4detectors/PHG4SpacalSubsystem.h

a continuation from [PR1998](https://github.com/sPHENIX-Collaboration/coresoftware/pull/1998), this PR introduce a new stepping  action for EMCAL that skips creating G4Hits and directly add energy to TowerInfo.
The tower energy from the same HIJING event using two different stepping action agrees within 3%, the difference is coming from applying the fiber transmission efficiency is applied on the G4Step level instead of G4Hit level. While only using the light guide efficiency correction(as shown in the plot below), the tower energy mostly agrees.
Running the default full sim(with the absorberactive = false) the new …

New steppingaction for EMCal

---

offline/database/cdbobjects/CDBTTree.cc
offline/database/cdbobjects/CDBTTree.h

The CDBTTree was not saved properly if it had more than a handful of entries. The reason was that you have to open a TFile before creating the TTree. Just writing a memory resident TTree to a file doesn't seem to work

Fix cdbttree

---

simulation/g4simulation/g4main/PHG4Reco.cc

Adds a new gas mixture in PHG4Reco.cc that matches the TPC gas mixture selected when Neon became too difficult to acquire.   ArCF4 60:40 has very similar properties for amplification and drift as the original mix, and is labeled as "sPHENIX_TPC_Gas_ArCF4"
/

added Ar:CF4 60:40 gas mixture as sPHENIX_TPC_Gas_ArCF4

---

offline/packages/intt/InttMapping.cc
offline/packages/intt/InttRawDataDecoder.cc

Fixes the strip_x/y convention to be consistent with tracking group's
Improved guard clause in process_event for the intt decoder (e.g., exit(1) instead of return 1)
Slightly more debugging information (behind Verbosity checks)

Slight improvements to InttRawDataDecoder, Fixed strip_x/strip_y convention in InttMapping

---

offline/packages/trackreco/SecondaryVertexFinder.cc

Found that the rotation direction was wrong in the get_DCA method of SecondaryVertexFinder. The rotation should be clockwise. This may be wrong elsewhere that the track DCA is calculated.

Fixerd rotation direction in get_DCA.

---

offline/framework/frog/CreateFileList.pl

This PR adds G4HitsOld to the pre defined DST types so the old G4Hits stay available until the cemc geometry is fixed [skip-ci]

Add G4HitsOld for old G4Hits files until repaired

---

offline/QA/modules/QAG4SimulationTracking.cc
offline/QA/modules/QAG4SimulationTracking.h
offline/packages/TrackingDiagnostics/TrkrNtuplizer.cc
offline/packages/trackbase_historic/Makefile.am
offline/packages/trackbase_historic/TrackAnalysisUtils.cc
offline/packages/trackbase_historic/TrackAnalysisUtils.h
simulation/g4simulation/g4eval/SvtxEvaluator.cc

This removes a lot of duplicated DCA calculation code and consolidates it to use a single function in track analysis utilities. It also corrects a bug Tony found that rotates the vector clockwise rather than counter clockwise to make the y component of the 3D DCA 0.

fix: DCA calculation and duplication

---

offline/packages/tpc/TpcMap.cc

The online monitoring did not find the tpc mapping. The reason was a forgotten /, so it looked in the wrong place

add forgotten / so the online monitoring finds the csh files

---

offline/packages/TrackingDiagnostics/TrackResiduals.cc
offline/packages/TrackingDiagnostics/TrackResiduals.h
offline/packages/trackbase/AlignmentTransformation.cc
offline/packages/trackbase/AlignmentTransformation.h

This PR fixes the applications of rotational misalignments such that they can be successfully and correctly replicated in the Acts KF alignment workflow. This means that given some input rotational misalignment, the workflow can reproduce that input before any input to pede. Now that the rotations are correctly being applied, we can test how pede interprets them.

fix: misalignment rotations

---

offline/database/cdbobjects/CDBHistos.cc
offline/database/cdbobjects/CDBTTree.cc
offline/database/cdbobjects/Makefile.am

This PR makes the cdbobjects library a standlone lib, only dependent on ROOT so we can use it online

make cdbobjects standalone library - only dependent on root

---

offline/packages/CaloReco/CaloWaveformFitting.cc

Shift the bin center to align with the time
Without this, the template fit's time has a systematic shift( for example, sample 1 will be in the bin centered at 1.5). 

Shift the time of the template fit by 0.5

---

offline/framework/fun4allraw/SinglePrdfInput.cc

Some BOR packets crash in the decoder. This patch just ignores non data events (and doesn't pass them on). That needs to be taken care off later [skip-ci]

patch for crash in begin run event, ignore special events

---

offline/packages/TrackerMillepedeAlignment/AlignmentDefs.cc
offline/packages/TrackerMillepedeAlignment/AlignmentDefs.h

The functions which return all global labels for a given grouping only returned the translation labels. They now return all labels, including rotations.

fix: All global label functions

---

offline/packages/micromegas/Makefile.am

Should only depend on already available libraries/code, namely online build of track_io and cdbobjects
This is necessary for TPOT calibrations to be seemlessly used in online monitoring code

Added MicromegasCalibrationData to online build

---

simulation/g4simulation/g4eval/FillClusMatchTree.cc

When not using the verbose option on the clusters, an unnecessary blank line is sent to cout once per process_event(). This update removes that line.

Small update -- remove cout of blank line in FillClusMatchTree

---

offline/framework/fun4allraw/Fun4AllPrdfInputPoolManager.cc
offline/framework/fun4allraw/SinglePrdfInput.cc
offline/framework/fun4allraw/SinglePrdfInput.h

The previous pool combiner just went for the event number. The beam clock counter is much more reliable, some packets start with a non zero event counter but their beam clock indicates they belong to a given event.
The code now collects all packets from a given beam clock counter and discards all packets which disagree (the ones I found were really pathological, though one seems to have stuck bits). This approach should prevent event mixing. Older files have more serious problems, for those this needs more work
[comment]: <> ( What does this PR do? Linking …

Prdf beamclock

---

offline/packages/CaloReco/CaloGeomMapping.cc
offline/packages/CaloReco/CaloGeomMapping.h
offline/packages/CaloReco/Makefile.am

This PR introduces a module `CaloGeomMapping` under `offline/packages/CaloReco`. The module creates a new node on the nodetree to hold a `RawTowerGeomContainer`, which contains the mapping from calorimeter tower index to the corresponding tower spatial coordinates. The mapping is read from the "CALO_TOWER_GEOMETRY" file in the Conditions Database. The new node is added as RUN-->[detector]-->TOWERGEOM_[detector], where [detector] is one of "CEMC", "HCALIN" or "HCALOUT".
In the future we will want to use run-specific mapping information …

Initial commit for CaloGeomMapping

---

offline/packages/intt/InttMapping.cc
offline/packages/intt/InttRawDataDecoder.cc
offline/packages/intt/Makefile.am
offline/packages/intt/configure.ac

Added a USE_ONLINE switch to the makefile in the style of the CaloBase/Makefile.am, I will likely change INTT's OnlMon to use the InttMapping library to standardize event readouts

(INTT) updated Makefile, fixed mapping conventions/conversions

---

calibrations/tpc/generator/generate_distortion_map.C

This fixes an issue in the tpc distortion generator.  Default argument values were causing an ambiguous call.  The ambiguity was a legacy interface that is no longer in use, so it was removed, and default values were rearranged for convenience.
A minor change fixing the invocation of generate_distortion_map.  

remove legacy distortion gen options

---

offline/packages/trackreco/Makefile.am

Trackreco should not depend on the alignment package. This PR fixes this and hopefully will remove the circular dependency problem present in https://github.com/sPHENIX-Collaboration/coresoftware/pull/2150 once the packages are reordered in the build.

fix: Remove circular dependency

---

offline/packages/TrackerMillepedeAlignment/AlignmentDefs.h
offline/packages/TrackerMillepedeAlignment/HelicalFitter.cc
offline/packages/TrackerMillepedeAlignment/MakeMilleFiles.cc
offline/packages/TrackerMillepedeAlignment/MakeMilleFiles.h
offline/packages/TrackerMillepedeAlignment/Makefile.am
offline/packages/trackbase_historic/ActsTransformations.cc
offline/packages/trackbase_historic/Makefile.am
offline/packages/trackbase_historic/SvtxTrackState.h
offline/packages/trackbase_historic/SvtxTrackState_v2.cc
offline/packages/trackbase_historic/SvtxTrackState_v2.h
offline/packages/trackbase_historic/SvtxTrackState_v2LinkDef.h
offline/packages/trackreco/ActsAlignmentStates.cc
offline/packages/trackreco/ActsPropagator.cc
offline/packages/trackreco/ActsPropagator.h

This PR :
1. Adds additional propagation helper methods in the ActsPropagator class, which are then used in the alignment scheme.
2. Adds a new track state version which contains a cluster key, allowing for better cluster-state association rather than just matching by minimum radius.
3. Adds a vertex constraint option to the Acts KF alignment scheme. The vertex position can be added in the alignment as an external constraint applicable to all tracks in an event. …

feat: Add vertex constraint to Acts KF alignment

---

simulation/g4simulation/g4eval/SvtxEvaluator.cc

This adds the number of truth charged hadrons (pi/K/p) to the output gtuple, which can be useful for pythia analysis since pythia calls every final state particle a truth particle.

feat: Add num charged hadrons to tuple

---

offline/packages/trackbase/AlignmentTransformation.cc
offline/packages/trackbase/AlignmentTransformation.h
offline/packages/trackreco/MakeActsGeometry.cc
offline/packages/trackreco/MakeActsGeometry.h

This PR allows us to bypass the simulation geometry and directly input survey geometry transformation parameters into Acts. There is an option for the INTT which already has some survey information (but is set to false by default), other detectors default to false. 

feat: Survey geometry

---

simulation/g4simulation/g4eval/SvtxEvaluator.cc

Suppress verbosity that snuck into evaluator

fix: suppress verbosity

---

offline/packages/micromegas/MicromegasDefs.h
offline/packages/micromegas/MicromegasRawDataCalibration.cc
offline/packages/micromegas/MicromegasRawDataDecoder.cc
offline/packages/micromegas/MicromegasRawDataEvaluation.cc

Starting from July 28 2023 TPOT will use packets 5001 and 5002 instead of 5000 and 5001, following request from @mpurschke 
Register packets 5000, 5001 and 5002 for TPOT to handle the transition gracefully 
Hide complains about packet not found behind Verbosity

accomodate new packet ids

---

offline/packages/trackbase/ClusterErrorPara.cc

Found another dynamic_cast that was unnecessary while digging

fix: remove another dynamic_cast

---

simulation/g4simulation/g4eval/SvtxEvaluator.cc
simulation/g4simulation/g4eval/SvtxTrackEval.cc
simulation/g4simulation/g4eval/SvtxTrackEval.h

Add branches and capability in the evaluation machinery to determine the number of clusters that don't match between a given truth/reco track per subsystem instead of only on the track as a whole.

feat: determine nwrong layers per subsystem in evaluator

---

offline/framework/frog/CreateFileList.pl

run 6 is superseeded and should not be used at least for calorimeter analysis, CreateFileList.pl now defaults to run 7. Also updated the file types (removed obsolete DST_VERTEX, added DST_GLOBAL with new content, added DST_TRUTH_RECO for the digested track truth info
It is just the script which does not get tested by jenkins, skip jenkins: [skip-ci] …

default run = 7, update filetypes for CreateFileList.pl

---

offline/packages/trackreco/PHActsSiliconSeeding.cc

This improves the rate at which the correct INTT clusters are associated to a silicon seed by a factor of 2-3 by selecting only the clusters in each layer set that closest to the circle fit trajectory. This gives us a ~95% rate at which INTT clusters are associated to tracks, with <~5% having wrong measurements associated to them according to the evaluation machinery.

fix: INTT purity improvement

---

offline/framework/frog/CreateFileList.pl

This PR fixes the behavior Virginia noticed. The reason was that I removed a line accidentally during cleanup which puts the modified argument back into $ARGV
[skip-ci]

put accidentally removed line back in

---

offline/framework/fun4allraw/Fun4AllPrdfInputPoolManager.cc

For some unknown reason event -1 makes it into the list and the pool manager crashed when trying to remove this event from its lists. This PR protects against this crash and the combiner gets over this event. Still need to figure out what's wrong here.

protect against crash when trying to delete event -1

---

offline/framework/fun4allraw/Fun4AllPrdfInputPoolManager.cc
offline/framework/fun4allraw/Fun4AllPrdfInputPoolManager.h

With this PR the pool input manager can now deal with larger differences to the reference beam clock (previously the diff being negative because of rollovers wasn't handled). This gets the hcal on board. Also increased the pool depth to 150 to see if we can process all of run 20508.

deal with negative diffs to get the hcal on board

---

offline/packages/CaloBase/TowerInfoContainerv1.cc

This PR sets the number of epd channels back to 744 which is the real number of channels. This avoids filling our disks with empty channels

set epd channel number back to 744

---

offline/packages/CaloReco/CaloTowerBuilder.cc

This updates the packet ranges and channel numbers in the EPD section of the CaloTowerBuilder initialization, which fixes the error message ```Error in <TClonesArray::At>: index 768 out of bounds (size: 768, this: 0x7274270)```. 

Updated sEPD packet ranges and channel numbers

---

offline/packages/CaloReco/CaloTowerBuilder.cc

This masks channels 0-63, 78, and 110 in the sEPD within the CaloTowerBuilder. This should prevent out of bounds errors after the number of channels was changed to 744 in commit ae7dabf . 

sEPD Channel masking

---

offline/packages/CaloReco/CaloTowerBuilder.cc

This will mask the 15th channel in every sector, regardless of whether a packet has been received or not.

Masked 15th channel in each sector

---

generators/phhepmc/HepMCFlowAfterBurner.cc
generators/phhepmc/HepMCFlowAfterBurner.h

This PR changes the rapidity range for the flow afterburner from -4,4 to -5,5 to cover the sEPD acceptance. That's been known for ~3 years but nobody though of updating this range.

change default rapidity range from -4,4 to -5,5 to cover sEPD

---

offline/packages/trackreco/PHActsSiliconSeeding.cc

This PR improves the silicon seed track parameters by circle fitting the MVTX+INTT clusters after any INTT measurements are found. Previously only the MVTX was fit because of the poor INTT z resolution screwing up the line fit in r-z. Since we split this functionality into the track seeds, it was apparently never updated to also include the INTT clusters in the x-y fit, for which the INTT provides much needed lever arm than the MVTX has alone. Some plots to show the improvement of the track parameters in single track events, where red is the (current) version and black is after the inclusion of the INTT. Note the PCA_z …

fix: improve silicon seed momentum resolution

---

offline/packages/micromegas/MicromegasRawDataEvaluation.cc
offline/packages/micromegas/MicromegasRawDataEvaluation.h

This PR implements more robust association between waveforms and level1 full (64 bits) BCO counter. 
Unlike before, it supports previous BCO leaking into the next (RCDAQ) event, and RCDAQ events containing multiple lvl1_bco taggers. 
The association is performed using the 16bits waveform BCO as an indication for jumping from one trigger to the other. 
This is done on a per-FEE_ID basis, because the waveform BCO counter vary from FEE to FEE, in a non predictable way. 
So far this is used only  for assembling full events offline in an evaluation tree, but could be used as a basis to perform full event assembly "on the fly" within fun4all. 
Only known case of failure is when waveforms for a given lvl1 trigger are sent before …

Tpot fix bco

---

simulation/g4simulation/g4eval/SvtxEvaluator.cc

Adds a flag to the reconstructed track tree to indicate whether or not the associated truth track also points back to that same reconstructed track, i.e. whether or not there is a one-to-one match

feat: add a purity flag to track tree

---

simulation/g4simulation/g4eval/SvtxEvaluator.cc

The commit from yesterday worked for low multiplicity but can segfault in AuAu. This PR fixes that mistake

fix: nullptr check

---

offline/packages/TrackingDiagnostics/TrkrNtuplizer.cc

Added protection to TrkrNtuplizer for if no tracks exist (particularly important if no tracking is being done).

TrkrNtuplizer no track protection

---

offline/framework/fun4all/Fun4AllServer.cc
offline/framework/fun4all/Fun4AllServer.h
offline/framework/fun4all/InputFileHandler.cc

This PR fixes the behavior when a TFile is opened before an instance of the Fun4AllServer is created. Doing this set the default directory used by Fun4All to set up its TDirectory structure to the file which resulted in quitting with this strange error message:
/home/phnxbld/sPHENIX/gcc-12.1.0/ana/source/coresoftware/offline/framework/fun4all/Fun4AllServer.cc:871: Unexpected TDirectory Problem cd'ing to TOP - send e-mail to off-l with your macro
Now the default is hardcoded to …

Tdirectory fix

---

offline/packages/TrackerMillepedeAlignment/HelicalFitter.cc
offline/packages/trackbase/TrackFitUtils.cc
offline/packages/trackbase/TrackFitUtils.h

This just moves a useful function from HelicalFitter into TrackFitUtils so that it can be used by other modules.

refactor: Move get_helix_tangent to TrackFitUtils for outside use

---

offline/packages/KFParticle_sPHENIX/KFParticle_Tools.cc
offline/packages/KFParticle_sPHENIX/KFParticle_Tools.h
offline/packages/KFParticle_sPHENIX/KFParticle_sPHENIX.h
offline/packages/KFParticle_sPHENIX/KFParticle_truthAndDetTools.cc

From yesterdays HF&Q meeting. Tony has asked for gluon information in the truth tracing branch of the output nTuple. This will allow him and Reese to tag events from gluon splitting.
I used the opportunity to also add a new selection on the secondary vertex volume and change some default values to be less restrictive (the track IP chisq and the mother flight distance chisq) …

KFParticle update, gluon records

---

offline/packages/HFTrackEfficiency/HFTrackEfficiency.cc
offline/packages/HFTrackEfficiency/HFTrackEfficiency.h

As discussed in yesterdays HF&Q meeting (see minutes emailed from Jin) I have updated the HFTrackEfficiency module to:
1. Calcualte the mass of the mother particle using the truth variables of the daughters
2. Take the PID of the daughter from truth particle rather than the DecayFinder tag (in case the matching is wrong)
3. Add a new matching feature to initially try and match the truth particle to the reco. track using the PHG4ParticleSvtxMap. This should improve the low pT tagging …

track efficiency updates

---

offline/packages/CaloBase/Makefile.am
offline/packages/CaloBase/TowerInfoContainerv2.cc
offline/packages/CaloBase/TowerInfoContainerv2.h
offline/packages/CaloBase/TowerInfoContainerv2LinkDef.h
offline/packages/CaloBase/TowerInfoContainerv3.cc
offline/packages/CaloBase/TowerInfoContainerv3.h
offline/packages/CaloBase/TowerInfoContainerv3LinkDef.h
offline/packages/CaloBase/TowerInfov1.h
offline/packages/CaloBase/TowerInfov2.cc
offline/packages/CaloBase/TowerInfov2.h
offline/packages/CaloBase/TowerInfov2LinkDef.h
offline/packages/CaloBase/TowerInfov3.cc
offline/packages/CaloBase/TowerInfov3.h
offline/packages/CaloBase/TowerInfov3LinkDef.h
offline/packages/CaloReco/CaloTowerBuilder.cc
offline/packages/CaloReco/CaloTowerBuilder.h

This PR introduces two new derived classes of `TowerInfo` along with corresponding downstream changes.
- **`TowerInfov2`**: 
- Derived from `TowerInfov1`.
- Contains three additional fields: `pedestal`, `chi2`, and `status`.
- The `status` is an 8-bit int that includes information like whether the tower is a hot tower and if the tower is instrumented.
- The peak time of this class can be stored with three more significant figures compared to `v1` (which uses a `short`).
- **`TowerInfov3`**: 
- Derived from `TowerInfov2`.
- Contains an additional field for waveform information. 
- This is primarily utilized to create a …

new towerinfo version class

---

offline/framework/fun4allraw/SingleInttInput.cc
offline/framework/fun4allraw/SingleTpcInput.cc

While working on Micromegas (TPOT) event combiner, I stumbled on a few inconsistencies/typos in the existing code for INTT and TPC:
1/ fixed a typo on the master node to be created for the TPC (code creates INTT while looking for TPC node ...)
2/ removed some unnecessary code when accessing a map. Calling map[XXX] when element XXX does not exist, automatically creates that element with default constructor (https://en.cppreference.com/w/cpp/container/map/operator_at) so there is no need to do that pre-emptively
3/ Fix, I think a bug with handling of the roll-over for GTM BCO:My understanding of the code is that m_Rollover[FEE] was actually added twice in case current BCO is < previous BCO, whereas one should only add the …

Couple of fixes on event combiner

---

offline/packages/CaloBase/TowerInfov1.h
offline/packages/CaloBase/TowerInfov2.h

This PR reverts TowerInfov1.h to its previous state. Using access methods should allow one to have private data members

revert TowerInfov1.h change

---

offline/packages/tpccalib/TpcDirectLaserReconstruction.cc
offline/packages/tpccalib/TpcDirectLaserReconstruction.h

**Files Affected:**
- offline/packages/tpccalib/TpcDirectLaserReconstruction.cc
- offline/packages/tpccalib/TpcDirectLaserReconstruction.h
**Changes:**
- Added functionality to apply Hough Transform to hits event by event and store in TH2 for each laser (and reset for new event)
- Added functionality to find Hough Transform maximum within +/- 5 degrees of fire direction in theta/phi
- Added histogram to store reconstructed laser angle residuals as a function of laser theta/phi (true - reco) for laser 1 only
- Added histogram to store reconstructed laser angle residuals (true - reco) for all lasers
- Added functionality to screen out empty hitmaps and hitmaps with no hits > 10 ADC above pedestal 
**TODO:**
- Add functionality to calculate ADC spectra of associated hits (assuming direction …

Screen out empty hitmaps + hitmaps with no hits 10 ADC above pedestal + Hough Transform Method

---

offline/packages/CaloReco/CaloWaveformFitting.cc

This PR changed the initial guess of the fit parameter closer to the actual value.
the first parameter should really be peak - ped instead of peak, also change the software ZS to be the sample 6 - sample 1.

change the initial parameter setting in the template fit

---

offline/packages/CaloBase/TowerInfo.h
offline/packages/CaloBase/TowerInfov1.cc
offline/packages/CaloBase/TowerInfov1.h
offline/packages/CaloBase/TowerInfov2.cc
offline/packages/CaloBase/TowerInfov2.h
offline/packages/CaloBase/TowerInfov3.cc
offline/packages/CaloBase/TowerInfov3.h
offline/packages/CaloReco/CaloTowerBuilder.cc

define virtual functions of the methods implement in `TowerInfov3` and `TowerInfov3` to the base class so and remove the type casting in `CaloTowerBuilder`.

Add virtual towerinfov2 and v3 methods to the base class

---

offline/packages/CaloReco/CaloTowerCalib.cc

This PR changes the calibrated node name from "TOWERS_Calib_" to "TOWERINFO_CALIB" to be consistent with pre-QM production
Just a name change that should be transparent to downstream.

Update to CaloTowerCalib Node Name

---

offline/database/sphenixnpc/CDBUtils.cc
offline/database/sphenixnpc/CDBUtils.h
offline/database/sphenixnpc/SphenixClient.cc

The end of validity time stamp should be excluded from the validity range but the selection included it. The CDB does not allow begin validity = end validity, so for single time stamps validity ranges like our run numbers we use begin = ts, end = ts+1. With the old client asking for the next run (ts+1) returned the calibration of ts if the calibration for that run did not exist. We only have a few runs where this might play a role but they all have calibrations so this is just …

fix end iov (exclude ts = end iov), add delete methods

---

offline/packages/CaloReco/DeadHotMapLoader.cc

Two primary updates: 
1) Changes deadmap name to "BadTowerMap" to reflect CDB payload name
2) The Maps/CDBTTrees are 1-dimensional, so the tower-by-tower loop has been collapsed by one layer to go through the towers sequentially. 

Update to handle pre-QM bad tower map loader

---

offline/framework/ffarawobjects/MvtxRawHitv1.cc

There was a bug in MvtxRawHitv1::identify(). The layer, stave and chip were stored as uint8_t which std::cout was interpreting as a char. I casted the values to unsigned's and the print outs work now

Fixed bug in MvtxRawHit::identify()

---

offline/packages/tpc/Makefile.am
offline/packages/tpc/TpcCombinedRawDataUnpacker.cc
offline/packages/tpc/TpcCombinedRawDataUnpacker.h

Adding Tpc raw data unpacker module based on Cristof's code 
Takes tpc info from tpcrawhitcontainer and appropriately adds it to the trkrhitsetcontainer

DRAFT PR Do Not Merge Yet

---

offline/packages/CaloReco/CaloTowerCalib.cc
offline/packages/CaloReco/CaloTowerCalib.h

PR allows for the creation of ZDC calibrated towers using the Lagrange multiplier method, see slide 7 of: https://indico.bnl.gov/event/19944/contributions/78023/attachments/48370/82183/Steinberg_sPHENIX20230630.pdf
Method puts single neutron peak at 100 GeV. Weights extracted per channel numbers as follows:
channel number, weights
0, 0.825664
2, 0.670553
4, 0.723938
8, 0.69576
10, 0.615914
12, 0.631928
Distribution in S/N arm:

Add zdc calibration functionality

---

generators/HIJINGFlipAfterburner/HIJINGFlipAfterburner.cc
generators/HIJINGFlipAfterburner/HIJINGFlipAfterburner.h
generators/HIJINGFlipAfterburner/Makefile.am
generators/HIJINGFlipAfterburner/autogen.sh
generators/HIJINGFlipAfterburner/configure.ac

HIJING's multiplicity is not symmetrical in +- z.
This afterburner adjusts the z-coordinates of particles and vertices, inverting their positions every other event. When aggregating data from multiple events, this method effectively balances out the asymmetry, yielding a symmetrical multiplicity distribution  for the sum of entire event set.

afterburner that z flip the every other HEPMC event

---

offline/framework/frog/CreateFileList.pl

This PR fixes the selection for central hijing events (0-4.88fm), it did not work for no-pileup and selected files with embedded pythia8 jets. jenkins does not check this anyway [skip-ci]

fix the type 6 selection

---

offline/packages/CaloReco/CaloWaveformFitting.cc

Set the error for the waveform histogram for the template fit to 1 instead of sqrt(N), so that the bias from the non-perfect template is a constant ratio. Change the initial time parameter of the template fit to around sample 6 to reduce bias.
Also make the fast method and ZS case push back a 0 chi2 to avoid potential seg faults.

Set the error on the template fit histogram to 1

---

offline/framework/ffamodules/CDBInterface.cc

This PR reshuffles the verbositis of the CDBInterface a bit to remove confusing duplicates and clarifies messages. The verbosity is currently enabled for the calo production and the current output indicates non existing problems which is bad

remove confusing printouts from CDBInterface

---

offline/packages/intt/InttCombinedRawDataConverter.cc
offline/packages/intt/InttCombinedRawDataDecoder.cc
offline/packages/intt/InttDeadMapHelper.cc
offline/packages/intt/InttFelixMap.cc
offline/packages/intt/InttFelixMap.h
offline/packages/intt/InttMapping.cc
offline/packages/intt/InttMapping.h
offline/packages/intt/InttRawDataConverter.cc
offline/packages/intt/InttRawDataConverter.h
offline/packages/intt/InttRawDataDecoder.cc
offline/packages/intt/InttVertexFinder.cc

This PR fixes a name clash of the Intt namespace with the Intt() function in the G4_TrkrSimulations.C macro. A change in the macro requires everybody to update their macros, changing the namespace name is less intrusive

fix name clash in Intt namespace with sims - rename Intt to InttDefs

---

offline/packages/trackbase/InttEventInfo.h
offline/packages/trackbase/InttEventInfov1.h

On compiling trackbase with the new build there is a ROOT warning that appears in the compiler log but does not actually fail the compilation that is due to the fact that the `InttEventInfo` is missing a `ClassDefOverride` statement. This PR fixes that and a few other minor related things that gets the inheritance structure right.

fix: Clean up InttEventInfo

---

offline/packages/intt/CylinderGeomIntt.cc
offline/packages/trackreco/MakeActsGeometry.cc

The new INTT ladder geometry had the first ladder at a negative phi value in two of the layers. This was not anticipated in the algorithm that calculates the hitsetkeys. This PR fixes the algorithm so that it works with the new geometry.

Fixed bug in INTT index calculation for new INTT ladder offsets.

---

offline/packages/trackreco/ActsPropagator.cc
offline/packages/trackreco/MakeActsGeometry.cc
offline/packages/trackreco/PHCosmicsTrkFitter.cc

This fixes a bug from Actsv30 which only allowed you to create track parameters on a perigee surface if they were within 0.1 micron tolerance, and reverts back to the previous behavior of (effectively) any tolerance to the perigee.

fix: Updates for Actsv30.3.0

---

offline/packages/CaloReco/CaloTowerBuilder.cc
offline/packages/CaloReco/CaloTowerBuilder.h

Adds set_outputNodePrefix function to CaloTowerBuilder to allow for user defined prefix for DST node name of calorimeter towers.

Add set prefix option to CaloTowerBuilder DST node name

---

offline/packages/tpccalib/TpcDirectLaserReconstruction.cc
offline/packages/tpccalib/TpcDirectLaserReconstruction.h

**Files Affected:**
- offline/packages/tpccalib/TpcDirectLaserReconstruction.cc
- offline/packages/tpccalib/TpcDirectLaserReconstruction.h
**Changes:**
- Added functionality to calculate ADC spectra of associated hits (for true direction and reco. direction from max of H.T. direction)
- Added functionality to calculate N_hits spectra of associated hits (for true direction and reco. direction from max of H.T. direction)
- Added functionality to calculate ratios of sum(ADC) and sum(N_hits) for true(DCA)/true_ALL
- Added functionality to calculate ratios of sum(ADC) and sum(N_hits) for reco(DCA)/true(DCA)
**TODO:**
- (may need to) swap reco(DCA)/true(DCA) to reco(DCA)/true_ALL
- add machinery to investigate specific angles with empty hitmaps
- add machinery to investigate specific angles …

Added Functionality to calculate ADC spectra and sum(ADC) and sum(N_hits) ratios for given DCA cut

---

offline/packages/CaloBase/TowerInfoContainer.h
offline/packages/CaloBase/TowerInfoContainerv1.cc
offline/packages/CaloBase/TowerInfoContainerv1.h
offline/packages/CaloBase/TowerInfoContainerv2.cc
offline/packages/CaloBase/TowerInfoContainerv2.h
offline/packages/CaloBase/TowerInfoContainerv3.cc
offline/packages/CaloBase/TowerInfoContainerv3.h

The CaloTowerContainer copy ctor didn't copy the _detector enum which then killed the calibration

fix copy ctors - add forgotten _detector

---

offline/packages/trackbase_historic/Makefile.am
offline/packages/trackbase_historic/SvtxTrackSeed_v1.cc
offline/packages/trackbase_historic/SvtxTrackSeed_v2.cc
offline/packages/trackbase_historic/SvtxTrackSeed_v2.h
offline/packages/trackbase_historic/SvtxTrackSeed_v2LinkDef.h
offline/packages/trackbase_historic/SvtxTrack_v1.cc
offline/packages/trackbase_historic/SvtxTrack_v2.cc
offline/packages/trackbase_historic/SvtxTrack_v3.cc
offline/packages/trackbase_historic/SvtxTrack_v4.cc
offline/packages/trackbase_historic/TrackSeed.h
offline/packages/trackbase_historic/TrackSeed_v1.cc
offline/packages/trackreco/PHActsTrkFitter.cc
offline/packages/trackreco/PHActsTrkFitter.h
offline/packages/trackreco/PHSiliconTpcTrackMatching.cc
offline/packages/trackreco/PHSiliconTpcTrackMatching.h

This PR introduces redundancy in the determination of the bunch crossing during extended-readout pp running. It will prevent loss of tracking acceptance if a part of the INTT is not working. The changes are:
1) Estimate the bunch crossing in PHSiliconTPCTrackMatcher using the z offset between (otherwise) matched silicon and tpc seeds. This is accurate to +/- 2 bunch crossings.
2) Make SvtxTrackSeed_v2 and add the bunch crossing estimate to it.
3) In PHActsTrkFitter, fit …

Add ability to get bunch crossing independent of INTT in pp

---

offline/framework/fun4allraw/tpc_pool.cc

There is one more speed-up provision that I need to test some more first.
[comment]: <This back-ports the speed up from the packet decoder.> (Please tell us something about this pull request)

mlp - back-ported the speed-up fix fromm the packet decoder.

---

offline/packages/jetbackground/CopyAndSubtractJets.cc
offline/packages/jetbackground/DetermineTowerBackground.cc
offline/packages/jetbackground/RetowerCEMC.cc
offline/packages/jetbackground/SubtractTowers.cc
offline/packages/jetbase/TowerJetInput.cc

Updating jetbackground and jetbase code that was using TowerInfov1 and TowerInfoContainerv1 instead of the generic versions. Also updated so that when we create retowered EMCal towers and subtracted versions of towers, those objects inherit the version that was used in the original input towers.

updating jet code to use generic TowerInfo objects instead of v1

---

offline/framework/ffarawobjects/Makefile.am
offline/framework/ffarawobjects/MvtxRawEvtHeader.h
offline/framework/ffarawobjects/MvtxRawEvtHeaderv1.h
offline/packages/mvtx/MvtxClusterizer.cc
offline/packages/mvtx/MvtxClusterizer.h
offline/packages/mvtx/MvtxCombinedRawDataDecoder.cc
offline/packages/mvtx/MvtxCombinedRawDataDecoder.h
offline/packages/trackbase/ClusHitsVerbose.h
offline/packages/trackbase/ClusHitsVerbosev1.h
offline/packages/trackbase/Makefile.am
offline/packages/trackbase/MvtxEventInfo.cc
offline/packages/trackbase/MvtxEventInfo.h
offline/packages/trackbase/MvtxEventInfov1.h
offline/packages/trackbase/MvtxEventInfov2.cc
offline/packages/trackbase/MvtxEventInfov2.h
offline/packages/trackbase/MvtxEventInfov2LinkDef.h

I just noticed that the MVTX event header can only store strobe BCOs when there is an associated L1 trigger BCO seen in the event. I made a new version that inherits from v1 so the strobe BCO is saved for every event, irregardless of whether there is a L1 BCO

New MvtxEventInfov2

---

offline/framework/ffarawobjects/InttRawHitContainerv1.cc
offline/framework/ffarawobjects/MicromegasRawHitContainerv1.cc
offline/framework/ffarawobjects/MvtxRawHitContainerv1.cc
offline/framework/ffarawobjects/TpcRawHitContainerv1.cc

Use GetEntriesFast() instead of GetEntries() for TC Array to speed up code (Thanks Jin)

use GetEntriesFast for TCArrays

---

offline/framework/ffarawobjects/TpcRawHitContainerv1.cc
offline/packages/tpc/TpcCombinedRawDataUnpacker.cc

As discussed in the last online offline meeting that the TPC unpacker has been slow. The problem trace to repeated call of the `TpcRawHitContainerv1::get_nhits()`  function which trace to slow `TClonesArray::GetEntries()` call
Solution is two folds:
* Switch to the faster `TClonesArray::GetEntriesFast()`
* Locally cache repeatedly used variables
Speed improvement seems about one order of magnitude. 
There are plenty further opportunities to speed up this unpacker, to come later …

Improve TPC Unpacker speed

---

offline/packages/mbd/MbdEvent.cc
offline/packages/mbd/MbdEvent.h
offline/packages/mbd/MbdReco.cc

for some runs the first event does not contain both mbd packets which then crashes the mbd code further down. If a packet is missing it now returns ABORTEVENT. For non data events or if there is no mbd packet it returns now DISCARDEVENT which does not abort the event reconstruction but can be picked up by an output manager to not save this event …

return ABORTEVENT if packet is missing, not crash

---

offline/packages/TrackingDiagnostics/TrackResiduals.cc
offline/packages/trackreco/PHCosmicsTrkFitter.cc
offline/packages/trackreco/PHCosmicsTrkFitter.h

1. The target surface is moved from the negative y edge of the TPC to the positive y edge to better match the data
2. State-cluster relations in track residuals are now determined by the cluster key stored in the state rather than by dr, which can lead to misleading results by associating a cluster and state on different layers.
3. A diagnostic tuple is added to the cosmic track fitter to look at the seed parameter determination for testing why Acts fits fail …

feat: cosmic development

---

offline/framework/fun4all/Fun4AllDstOutputManager.cc
offline/framework/fun4all/Fun4AllDstOutputManager.h
offline/framework/phool/PHNodeIOManager.cc
offline/framework/phool/PHNodeIOManager.h

This PR adds a magic string (?reproducible=filename-without-path) to the TFile name which tells root to create binary identical files (no time stamps or path to output file stored anymore) This disables the use of TRef which we don't use anyway

add a magic string to TFile opening to enforce binary identity

---

offline/framework/fun4allraw/Fun4AllStreamingInputManager.cc
offline/framework/fun4allraw/Fun4AllStreamingInputManager.h
offline/framework/fun4allraw/SingleTpcPoolInput.cc
offline/framework/fun4allraw/SingleTpcPoolInput.h

This PR adds matching of earlier bco to the gl1 (just like mvtx and micromegas)

Add negative bco range for tpc

---

simulation/g4simulation/g4intt/PHG4InttSubsystem.cc

Copied over the values from the macro, except for `offsetphi[]`, which was correct here. It's worth letting Tony test this to make sure it's okay.

PHG4InttSubsystem geometry fix

---

offline/packages/trackbase/TrackFitUtils.cc
offline/packages/trackbase/TrackFitUtils.h
offline/packages/trackreco/Makefile.am
offline/packages/trackreco/PHCosmicSiliconPropagator.cc
offline/packages/trackreco/PHCosmicSiliconPropagator.h
offline/packages/trackreco/PHCosmicsTrkFitter.cc

Adds a new module that is less restrictive than the current helicalpropagator module. The new module only propagates to the silicon and checks for clusters within some configurable dca xy and z cut. It also makes no restriction on the quadrant, which the previous module does as it was intended to be used in beam like conditions.
The PR also cleans up the `TrackFitUtils::addSiliconClusters` function by only iterating over silicon hitsetkeys and not making any requirement on the silicon layer, which there previously was (I'm guessing due to some copy paste error...) …

feat: Add cosmic helical propagator module

---

offline/packages/jetbase/Jetv1.cc
offline/packages/jetbase/Jetv1.h

I added a size_t field to Jetv1 with the last PR that merged the JetContainer. This causes an error when reading Jetv1's from existing TTrees, but that wasn't checked by Jenkins. This is the fix, which just removes that member field for Jetv1.

Fix bug introduced by changing size of Jetv1

---

offline/packages/micromegas/Makefile.am
offline/packages/micromegas/MicromegasCombinedDataDecoder.cc
offline/packages/micromegas/MicromegasCombinedDataDecoder.h
offline/packages/micromegas/MicromegasHotChannelMapData.cc
offline/packages/micromegas/MicromegasHotChannelMapData.h

This is a first shot at implementing hot channel maps in Micromegas/TPOT
CombinedDataDEcoder reads the list of hot channels from a CDBTTree object, and masks them out automatically.
The code to generate these lists is still an uncommitted work in progress.

Tpot hot channels

---

offline/packages/intt/InttCombinedRawDataDecoder.cc
offline/packages/mvtx/MvtxCombinedRawDataDecoder.cc

The silicon hitsetkeys were not filled properly WRT the timing information. They now get the gl1 bco, bit shift by 24 bits to compare to the raw hit bcos, and then fill the hitsets with the relative difference between the gl1 bco and the hit bco.

fix: Silicon unpackers calculate crossing WRT GL1 

---

offline/packages/mvtx/MvtxCombinedRawDataDecoder.cc
offline/packages/mvtx/MvtxCombinedRawDataDecoder.h

This fixes the unpacking (really this time, after more discussion) to be the relative strobe to the gl1 bco for each hit in the trigger frame.

fix: Correct strobe index

---

offline/packages/CaloReco/CaloTowerStatus.cc

Fix typo from badchi2 field to meantime field for getting meantime from cdb

Fix typo from badchi2 to meantime field for CaloTowerStatus

---

offline/packages/jetbackground/DetermineTowerBackground.cc
offline/packages/jetbackground/DetermineTowerBackground.h
offline/packages/jetbase/JetContainerv1.cc

Update to DetermineJetBackground module to use the method's for adding jet properties in the 
Jetv2 paradigm instead of the Jetv1 paradigm. This is a bug fix that Jenkins didn't test for in the migration to JetContainer and was initially overlooked.

Update Jetv1 method to Jetv2 method in jetbackground

---

offline/packages/tpc/TpcCombinedRawDataUnpacker.cc

As just mentioned in the software meeting, there is a z-flip in the TPC unpacker which translate the detector naming convention to offline naming conversion on the sectors and sides. 
This PR fixes the z flip, but watch out for other inconsistencies between detector and offline indexing. Let me know if any problem and I can help check. 

Fix TPC side mapping: north sector 00..11->side 1

---

offline/packages/mbd/MbdCalib.cc
offline/packages/mbd/MbdCalib.h
offline/packages/mbd/MbdEvent.cc
offline/packages/mbd/MbdEvent.h
offline/packages/mbd/MbdReco.cc
offline/packages/mbd/MbdReco.h
offline/packages/mbd/MbdSig.cc
offline/packages/mbd/MbdSig.h
simulation/g4simulation/g4bbc/MbdDigitization.cc

[comment]: Enabled template fit to waveforms.  Also added debug code to evaluate z-vertex reconstruction.
[comment]: From now on, the default is to use template fits.

Turn on template fits, add debugging output

---

offline/packages/jetbackground/FastJetAlgoSub.cc
offline/packages/jetbackground/FastJetAlgoSub.h

FastJetAlgoSub inherits from JetAlgo (and not FastJetAlgo), and was quietly not filling the JetContainer. This is, to the best I can tell, only used in the HIJetReco package. In any case, this fix should fix all instances where it is used.

Make FastJetAlgoSub fill JetContainer (it wasn't)

---

offline/packages/micromegas/MicromegasCalibrationData.cc
offline/packages/micromegas/MicromegasCalibrationData.h
offline/packages/micromegas/MicromegasClusterizer.cc
offline/packages/micromegas/MicromegasClusterizer.h
offline/packages/micromegas/MicromegasCombinedDataDecoder.cc
offline/packages/micromegas/MicromegasMapping.cc

This PR allows to read calibrations in the micromegas clusterizer. This is necessary to subtract the correct pedestal from the hits ADC before calculating the cluster ADC weighted centroid.

Micromegas calibrations

---

offline/packages/TrackingDiagnostics/TrackResiduals.cc
offline/packages/TrackingDiagnostics/TrackResiduals.h
offline/packages/trackreco/PHCosmicSeeder.cc

Before the great SDCC outage of December 2023, this PR adds some useful diagnostic tools to one of the ntuplizing modules for cosmic and/or real data analysis.
1. Adds the full 64 bit GL1 BCO and the 40 bit shifted tracker BCOs, so that we can do direct comparisons to the preliminary plots that were hand stitched together. Useful for validating the full O2O workflow.
2. Adds a hit tree and capability to fill the clusters associated to tracks and/or track seeds if the track state is not present (e.g. in the event the fitter is not run). The hits and clusters are saved with their specific subsystem information (e.g. …

feat: update TrackResiduals to output more O2O debug info

---

offline/packages/tpc/TpcCombinedRawDataUnpacker.cc

Missed two lines in the last PR https://github.com/sPHENIX-Collaboration/coresoftware/pull/2406 . Giving another try. 
There is possible swap in the phi direction in the sectors, which need to be checked with cross-sector cosmic track display. 

TPC `side` fix, try 2

---

offline/framework/frog/CreateFileList.pl

This add an option (4) to the pileup which selects 1MHz pileup for pp where the pileup window is set to 100us. Jenkins does not see this anyway [skip-ci]

add 1MHz streaming selection for pileup

---

offline/packages/CaloReco/RawClusterBuilderTemplate.cc
offline/packages/CaloReco/RawClusterBuilderTemplate.h

Applies TowerInfov2 selections to the pool of towers given to the clusterizer. The selections can be turned off at macro level by setting RawClusterBuilderTemplate::set_ApplyTowerSelection(false). 
This change was done during the Calo workfest (Dec 14 and 15) and discussed on mattermost (https://chat.sdcc.bnl.gov/sphenix/pl/a7wx93eraffr9ymn356dgjteua)

Added TowerInfov2 selections to towers being clusterized

---

offline/packages/CaloReco/CaloTowerBuilder.cc
offline/packages/CaloReco/CaloTowerBuilder.h
simulation/g4simulation/g4waveformsim/CaloWaveformSim.cc
simulation/g4simulation/g4waveformsim/CaloWaveformSim.h
simulation/g4simulation/g4waveformsim/Makefile.am
simulation/g4simulation/g4waveformsim/autogen.sh
simulation/g4simulation/g4waveformsim/configure.ac

The CaloWaveFormSim module takes in the G4Hits and produce towerinfov3 object that contains the simulated waveform.
Added a new option(when `m_isdata == false`) to processed the simulated waveform(a towerinfov3 object) generated by calowaveformsim module from G4Hits.
Need to apply the fiber efficiency for EMCal

add option to process simulated waveforms

---

simulation/g4simulation/g4tpc/PHG4TpcDetector.cc
simulation/g4simulation/g4tpc/PHG4TpcPadPlane.h
simulation/g4simulation/g4tpc/PHG4TpcPadPlaneReadout.cc
simulation/g4simulation/g4tpc/PHG4TpcPadPlaneReadout.h
simulation/g4simulation/g4tpc/PHG4TpcSubsystem.cc

The TPC extended readout time is currently fixed to 2x the drift time. This PR fixes this to be some extended readout time + 1 drift time, to match our envisioned streaming environment of 7+13 mus. It also allows for configuring this value when looking at the large 100 mus streamed data.

fix: add extended readout time to tpc subsystem

---

offline/packages/tpc/TpcClusterizer.cc

This fixes a hard coded time bin maximum that was in the clusterizer, preventing clusters from being produced at later times. We never noticed because the nominal time is 26 mus which covers our nominal hybrid streaming case.

fix: hard coded tpc time bin limit

---

offline/framework/fun4allraw/Fun4AllStreamingInputManager.cc
offline/framework/fun4allraw/Fun4AllStreamingInputManager.h
offline/framework/fun4allraw/SingleInttPoolInput.cc
offline/framework/fun4allraw/SingleInttPoolInput.h

The INTT is sometimes off by one BCO. This PR copies the bco matching mechanics from the other streaming systems, the range is configurable in a macro. This also recovers the ability to combine the intt standalone (without gl1 data) where it then provides its own reference bco

allow bco range for intt-gl1 bco match

---

simulation/g4simulation/g4tpc/PHG4TpcDistortion.cc

This comments out a few lines in PHG4TpcDistortion so that distortion files that lack the 'ReachesReadout' histogram can still be used. 
A more elegant fix is to check for the existence of each hist before loading, and to allow to switch off the ReachesReadout behavior itself.

Reaches readout short term

---

offline/packages/jetbase/FastJetAlgo.cc
offline/packages/jetbase/FastJetAlgo.h
offline/packages/jetbase/FastJetOptions.cc
offline/packages/jetbase/FastJetOptions.h
offline/packages/jetbase/Makefile.am

Presented to the JS-Topical Group on 1/17 and was ok'd. This is an option on jet reconstruction and doesn't change any default behaviors of the system.
Add's FastJet 3's default Constituent Background Subtractor option to FastJetAlgo.

Add fastjet::contrib::ConstituentSubtractor to FastJetAlgo

---

offline/packages/tpc/TpcCombinedRawDataUnpacker.cc
offline/packages/tpc/TpcCombinedRawDataUnpacker.h

Turns the ntuple creation in the TPC unpacker to off by default, settable by a switch at the macro level.

fix: NTuple turned off by default in tpc unpacker

---

offline/packages/HFTrackEfficiency/HFTrackEfficiency.cc
offline/packages/HFTrackEfficiency/HFTrackEfficiency.h

At today's HF&Q meeting, Charles showed some reconstructed eta plot which had a cross structure around 0. This is due to the default value of each track being 0 so if the reco track doesn't exist, this isn't updated. I changed the default values to use numeric limits
[Link to Charles' presentation](https://indico.bnl.gov/event/22058/contributions/86 …

Changed HFTrackEff defaults from 0 to numeric_limits

---

offline/packages/CaloEmbedding/Makefile.am
offline/packages/CaloEmbedding/caloTowerEmbed.cc
offline/packages/CaloEmbedding/caloTowerEmbed.h
offline/packages/jetbase/Jet.h
offline/packages/jetbase/TowerJetInput.cc

[comment]: <> Changed embedding to only run over the passed calorimeter, will need to be loaded separately for each calorimeter
Data towers are no longer overwritten by embedding, new containers for each calorimeter tower are added to the node tree for embedding and sim
New sources in Jet.h and TowerJetInput.cc to use these new containers

Calo embed cleaning

---

offline/packages/eventplaneinfo/EventPlaneReco.cc
offline/packages/eventplaneinfo/EventPlaneReco.h
offline/packages/eventplaneinfo/Makefile.am

Recentering histograms are filled by the module during first run. On second run, these histograms are used for MBD event plane calibration. Currently uses the MBD total charge instead of centrality.

add MBD event plane recentering histograms

---

offline/packages/tpc/TpcDistortionCorrection.cc
offline/packages/tpc/TpcDistortionCorrection.h
simulation/g4simulation/g4tpc/PHG4TpcDistortion.cc
simulation/g4simulation/g4tpc/PHG4TpcDistortion.h

This adds flags to the simulation and the reco that allow it to interpret phi distortions as either d(r*phi), in centimeters, or as d(phi), in radians.  The flag is set to true by default, which makes the distortion framework compatible with recent simulated distortion datasets.  This approach makes these compatible with the fewest flags.
The handling in the reconstruction is currently in TpcDistortionCorrection, but probably more correctly belongs to the TpcDistortionCorrectionContainer.  This is a minor issue that would only apply if we were swapping from current to old datasets and back.
Also, if we are deprecating …

Rphi toggle

---

offline/packages/KFParticle_sPHENIX/KFParticle_Tools.cc

I was working with @chughes90 on the Lambda_c analysis when I found that KFParticle was crashing. I traced it down to there being no vertices stored as KFParticle objects so the first time it tried to access the primary vertex vector, Fun4All would crash.
Further invesitgation showed that SVTX vertices were being created and saved. KFParticle would then request SVTX vertices from the global vertex map and a check on the VTX type (400) showed this worked and there was one vertex to use. Then a check as to whether we were at the end of the vertex map was run which stopped the conversion of the SvtxVertex to a KFVertex, …

A check on the global vertex causes KFParticle to crash

---

offline/packages/trackbase/TrackFitUtils.cc
offline/packages/trackreco/PHCosmicSiliconPropagator.cc
offline/packages/trackreco/PHCosmicTrackMerger.cc
offline/packages/trackreco/PHCosmicTrackMerger.h

The line fit algorithm fails for tracks that are nearly vertical - it is a result of dividing by something close to 0. This PR does two things:
1. Performs the line fit in both x-y and y-x. Whichever line fit minimizes the residuals is the line fit that is actually returned (i.e. the determined parameters for x-y fit or the inverse parameters for y-x fit). This improves line fits for nearly vertical tracks dramatically (quite a few cosmics).
2. Tunes the seed merger to remove outlier clusters from the line fit that got picked up by some seed merging. 
The cosmic seeding now performs pretty well and doesn't create so many …

feat: cosmic development and line fitter fix

---

offline/packages/CaloReco/RawClusterBuilderTemplate.cc

fix bug - when clusterizer is rerun the old clusters are now erased

---

offline/packages/TrackingDiagnostics/TrackResiduals.cc
offline/packages/TrackingDiagnostics/TrackResiduals.h
offline/packages/trackreco/PHCosmicSiliconPropagator.cc
offline/packages/trackreco/PHCosmicTrackMerger.cc

This PR adds a few things
1. Fixes a bug in the r-z fit for seed 2 when combining seeds
2. Ensures TPOT clusters are treated differently since they are 1D in nature and thus don't satisfy a 2D DCA line cut
3. Removes the MVTX cluster size cut since the MVTX hot/dead map is now applied
4. Adds a line-surface intersection algorithm to determine a "track state" for a line fit to the clusters on track in `TrackResiduals`

fix: cosmic track seeding

---

offline/packages/globalvertex/GlobalVertexv2.cc

Jakub noticed that the counter `mosttracks` was not updated in the `get_position` call of `GlobalVertexv2`. This fixes this and the other instances that existed. 

fix: get_position mosttracks not updated

---

offline/framework/frog/CreateFileList.pl

ampt files now have the b range as postfix, this PR adapts CreateFileList.pl to this, jenkins does not test this, skipping it [skip-ci]

use 0_20fm b range postfix for ampt

---

offline/packages/eventplaneinfo/EventPlaneReco.cc
offline/packages/eventplaneinfo/EventPlaneReco.h
offline/packages/eventplaneinfo/Eventplaneinfo.h
offline/packages/eventplaneinfo/Eventplaneinfov1.h

PR implements Equation (6) of arxiv:nucl-ex/9805001. Some runs require recentering in addition to shifting. In particular some of the zero field runs. See plot for implementation result.

Implementing plane shifting 

---

offline/packages/particleflow/ParticleFlowReco.cc

Change the calculation of eta and phi of track state at OHCAL position from momentum coords to position coords.

Eta and phi track state calculation changed to position coords at OHCAL

---

offline/framework/fun4all/Fun4AllBase.cc
offline/framework/fun4all/Fun4AllBase.h
offline/framework/fun4all/Fun4AllDstInputManager.cc
offline/framework/fun4all/Fun4AllInputManager.h
offline/framework/fun4all/Fun4AllOutputManager.cc
offline/framework/fun4all/Fun4AllReturnCodes.h
offline/framework/fun4all/Fun4AllRunNodeInputManager.h
offline/framework/fun4all/Fun4AllServer.cc
offline/framework/fun4all/Fun4AllServer.h
offline/framework/fun4all/Fun4AllSyncManager.cc
offline/framework/fun4all/InputFileHandler.cc
offline/framework/fun4all/InputFileHandler.h
offline/framework/fun4all/TDirectoryHelper.cc
offline/framework/fun4allraw/SinglePrdfInput.cc
offline/framework/fun4allraw/SingleZdcInput.cc

a / in the module name (where a filepath was used for the module name) lead to misleading errors when Fun4All tried to create a TDirectory using this name. Now all names are checked in Fun4AllBase if they are made up of character, numbers or _, -. More can be added but I don't think we should go overboard here. If the check fails, the bad characters are printed out with an error message followed by an exit …

Check Fun4All names

---

offline/packages/intt/InttClusterizer.cc

Enables nontrivial INTT Z clustering by switching from a hard-coded cluster Z size of 1 to the value calculated in the clusterizer. Under default running conditions, Z clustering is switched off, and there is no change to that pathway.

INTT Z clustering fix

---

offline/packages/trackbase_historic/SvtxTrackInfo.h
offline/packages/trackbase_historic/SvtxTrackInfo_v1.cc
offline/packages/trackbase_historic/SvtxTrackInfo_v1.h
offline/packages/trackbase_historic/TrackStateInfo.h
offline/packages/trackbase_historic/TrackStateInfo_v1.cc
offline/packages/trackbase_historic/TrackStateInfo_v1.h
simulation/g4simulation/g4eval/DSTTrackInfoWriter.cc

This cleans up the track state info to 
1. use a 15 entry covariance
2. use phi, theta, and q/p for momentum storage instead of px, py, pz, which allows us to save the charge on the track

Trackstateinfo cleanup

---

offline/packages/tpc/TpcClusterizer.cc
offline/packages/tpc/TpcClusterizer.h
simulation/g4simulation/g4tpc/PHG4TpcDetector.cc
simulation/g4simulation/g4tpc/PHG4TpcDigitizer.cc
simulation/g4simulation/g4tpc/PHG4TpcPadPlaneReadout.cc

This PR fixes a bug in the TPC clustering code that affected the calculation of the cluster z position from the readout time in pp running when analyzing extended readout data. 

Streaming TPC cluster z fix

---

offline/packages/trackreco/PHSimpleKFProp.cc

PHSimpleKFProp was searching for "TpcDistortionCorrectionContainer" which does not exist, leading to it using the uncorrected cluster positions. It now looks for "TpcDistortionCorrectionContainerStatic", which does exist.

Fixed TPC propagator searching for wrong distortion correction container name

---

offline/packages/TrackingDiagnostics/TrackResiduals.cc
offline/packages/TrackingDiagnostics/TrackResiduals.h
offline/packages/trackreco/PHCosmicsTrkFitter.cc
offline/packages/trackreco/PHCosmicsTrkFitter.h

This PR gets the Acts Kalman Filter in shape to run on the cosmic data. We can now build tracks and fit them with the Kalman Filter to get real cluster-state residuals as determined by Acts. Tested on zero field data, when we start taking field on cosmics we will have to retune to ensure the charge and circle fit determination is functional in the same way as it is for zero field. Attached are some (cherry picked) examples from run 25926 and segment 15 that show
1. Red - all clusters in the event
2. Blue lines - initial track seed momentum and PCA at perigee surface of radius of 80 cm, for input to Acts
3. Black - …

feat: cosmic track fitting

---

offline/packages/TrackingDiagnostics/TrackResiduals.cc
offline/packages/TrackingDiagnostics/TrackResiduals.h

Fixes a bug that was introduced in the streaming reco development which returns NANs for cluster lzs in the cosmics data since we don't have a crossing defined.

fix: streaming/triggered lz

---

offline/packages/decayfinder/DecayFinder.cc
offline/packages/decayfinder/DecayFinder.h

There was a logic error in a high verbosity print out in decay finder. The logic was both backwards and checked a variable global to a decay instead of local to a track. This had been fixed a couple of weeks ago but I forgot to make the PR

DecayFinder: Patched logic error in print out

---

offline/packages/decayfinder/DecayFinder.cc

Some mothers can be tagged twice as a decay if they have a radiative correction. This only applies to resonant mothers like upsilons, phis and J/psi. There was a check for radiative or resonant decays but this only applied to intermediate states. This has been extended to cover reonant mothers tool

DF: Remove resonant mothers

---

offline/packages/intt/InttCombinedRawDataDecoder.cc
offline/packages/intt/InttCombinedRawDataDecoder.h

I added some flags to allow the INTT unpacker to work standalone. This is for the dN/deta and v_n analyses which will make separate INTT and centrality nTuples then combine them offline. This will allow analysers to use the latest sPHENIX software.
I tested the INTT combiner macro in https://github.com/sPHENIX-Collaboration/macros/blob/master/InttProduction/Fun4All_Intt_Combiner.C which would work if I set
```c++
sngl->SetNegativeBco(0);
```
and give me a DST with raw hits. However, when I added 
```c++
InttCombinedRawDataDecoder *myDecoder = new InttCombinedRawDataDecoder("myUnpacker");
```
then I would get an abort …

Made INTT unpacker work standalone

---

offline/packages/KFParticle_sPHENIX/KFParticle_truthAndDetTools.cc

@josephbertaux uncovered a bug in a truth vertex matching addition where I would try to associate a truth particle to a truth vertex without checking if the truth particle was valid. This would cause a segfault and has been patched

KFP: Truth matching bug fix

---

offline/packages/trackbase_historic/Makefile.am
offline/packages/trackbase_historic/SvtxTrackInfo.h
offline/packages/trackbase_historic/SvtxTrackInfo_v1.cc
offline/packages/trackbase_historic/SvtxTrackInfo_v1.h
offline/packages/trackbase_historic/SvtxTrackInfo_v2.cc
offline/packages/trackbase_historic/SvtxTrackInfo_v2.h
offline/packages/trackbase_historic/SvtxTrackInfo_v2LinkDef.h
offline/packages/trackbase_historic/SvtxTrackInfo_v3.cc
offline/packages/trackbase_historic/SvtxTrackInfo_v3.h
offline/packages/trackbase_historic/SvtxTrackInfo_v3LinkDef.h
offline/packages/trackbase_historic/TrackInfoContainer_v1.cc
offline/packages/trackbase_historic/TrackInfoContainer_v1.h
offline/packages/trackbase_historic/TrackInfoContainer_v2.cc
offline/packages/trackbase_historic/TrackInfoContainer_v2.h
offline/packages/trackbase_historic/TrackInfoContainer_v2LinkDef.h
offline/packages/trackbase_historic/TrackInfoContainer_v3.cc
offline/packages/trackbase_historic/TrackInfoContainer_v3.h
offline/packages/trackbase_historic/TrackInfoContainer_v3LinkDef.h

This introduces a SvtxTrackInfo_v2 that is intended to be used for the propagation of tracks from the outermost TPC layer to the calorimeters. SvtxTrackInfo_v3 will be used to hold the projection information to the calorimeters for analyses purposes. 
Later, other classes will be modified to make use of SvtxTrackInfo_v2 and SvtxTrackInfo_v3

Adding SvtxTrackInfo/Containers v2 and v3

---

offline/packages/tpc/TpcDistortionCorrection.cc
offline/packages/tpc/TpcDistortionCorrection.h
offline/packages/tpc/TpcDistortionCorrectionContainer.h
offline/packages/tpc/TpcLoadDistortionCorrection.cc
offline/packages/tpc/TpcLoadDistortionCorrection.h
offline/packages/tpccalib/PHTpcCentralMembraneMatcher.cc
offline/packages/trackreco/PHActsTrkFitter.h
simulation/g4simulation/g4tpc/PHG4TpcDistortion.cc
simulation/g4simulation/g4tpc/PHG4TpcDistortion.h

This PR is a follow up to https://github.com/sPHENIX-Collaboration/coresoftware/pull/2460
It moves the flag  m_phi_hist_in_radians flag from TpcDistortionCorrection to TpcLoadDistortionCorrection.
The former is only an helper class that should not keep any configurable flag as it is never accessible externally.
The latter is the right place to set the flag, then properly propagated to TpcDistortionContainer and then used internally by the TpcDistortionCorrection helper class.
This way one can set whether the input maps use radians or centimeters for the phi (rphi) distortions from the calling macro.
Default behavior is unchanged with respect to the previous PR: the default is true.
[comment]: <> ( What types of changes does …

Distortion map flags

---

offline/framework/fun4allraw/Makefile.am

This PR fixes the build ordering. If a library depends on another local library, one has to put he .la file into the library dependency to force make to build it before it tries to link the library
libfun4allraw_la_LIBADD = \
libmvtx_decoder.la \
-lffarawobjects \
...
instead of
libfun4allraw_la_LIBADD = \
-lmvtx_decoder \
-lffarawobjects \
... …

fix build order, libs need to depend on .la if lib is local

---

simulation/g4simulation/g4ihcal/PHG4IHCalDetector.cc
simulation/g4simulation/g4ihcal/PHG4IHCalSteppingAction.cc
simulation/g4simulation/g4ihcal/PHG4IHCalSteppingAction.h
simulation/g4simulation/g4ihcal/PHG4IHCalSubsystem.cc
simulation/g4simulation/g4ohcal/PHG4OHCalDetector.cc
simulation/g4simulation/g4ohcal/PHG4OHCalSteppingAction.cc
simulation/g4simulation/g4ohcal/PHG4OHCalSteppingAction.h
simulation/g4simulation/g4ohcal/PHG4OHCalSubsystem.cc

The gdml files for the calorimeters are now read by default from the cdb. While at it, the Mephi maps are now also read by default from the cdb as is the steel magnetic field map for the outer hcal. This can be overridden by the macro which is currently the case. Once this PR is through the G4_Hcal*_ref.C macros will be adapted and then the new outer hcal gdml with the support ring will be implemented
[comment]: <> ( In case this is a draft PR, e.g. for running checks …

Hcal cdb gdml

---

simulation/g4simulation/g4ohcal/PHG4OHCalDetector.cc
simulation/g4simulation/g4ohcal/PHG4OHCalDisplayAction.cc
simulation/g4simulation/g4ohcal/PHG4OHCalDisplayAction.h

This PR superseeds https://github.com/sPHENIX-Collaboration/coresoftware/pull/2526
The new version can read both old and new gdml files. It will only add the ring to the display if it is found in the gdml file. There is an issue with the G4 logical volume management which existed in the old PR as well which needs to be sorted out before we can use the ring from the gdml file …

Hcal support gdml

---

offline/packages/tpc/TpcCombinedRawDataUnpacker.cc

The TPC mapping for the antennae needs to be updated but hasn't gone through into the DB yet. This gets us back running again for the time being.

fix: bug in unpacking with new mapping

---

offline/packages/trackreco/PHCosmicTrackMerger.cc
offline/packages/trackreco/PHCosmicTrackMerger.h
offline/packages/trackreco/TrackQA.cc

This PR adds a function to take the closest two clusters to the line fit per layer. It improves the silicon residuals. It improves the widths of the residuals especially since many clusters per layer are created for the TPC in the run 23 conditions.

feat: take two best clusters per layer

---

simulation/g4simulation/g4ohcal/PHG4OHCalDisplayAction.cc

The inner hcal support ring from the outer hcal gdml was displayed in red to be easily seen. This PR reverts this back to grey

make support ring grey

---

simulation/g4simulation/g4waveformsim/CaloWaveformSim.cc
simulation/g4simulation/g4waveformsim/CaloWaveformSim.h

add a switch to simulate high gain calo waveforms.

add option to simulate different gain mode

---

offline/packages/KFParticle_sPHENIX/KFParticle_eventReconstruction.cc

Add duplicate tracks check in final track list to avoid same tracks being used in different intermediate resonances.

KFP: avoid duplicate tracks used in different intermediate resonances

---

offline/packages/CaloReco/RawTowerCalibration.cc
offline/packages/CaloReco/RawTowerCalibration.h

This PR is the first of three (One to coresoftware, one to macros/common, and one to the MDC2 area) that will enable TowerInfoV2 functionality in simulation, making it easier to model the data acceptance in simulation via the masking stored in the status fields of the TowerInfoV2 objects. 
A setter and corresponding boolean have been added telling the software whether to store V1 or V2 objects. 

Adding TowerInfoV2 Compatibility for Simulation

---

offline/database/rundb/CaloTemp.cc
offline/database/rundb/CaloTemp.h
offline/database/rundb/Makefile.am
offline/database/rundb/autogen.sh
offline/database/rundb/configure.ac

Creates new module to find the run time and calorimeter temperatures from the daq database. Calorimeter temperatures that are closest to the begin run time of the run of interest are output. Histograms of tower by tower calorimeter temperatures are output to file of choice. 

Module to find run time and calorimeter temperatures from daq db

---

offline/packages/trackbase_historic/TrackSeed.h
offline/packages/trackbase_historic/TrackSeed_v1.cc
offline/packages/trackbase_historic/TrackSeed_v1.h

- pass const_ref rather than ref to get_phi method. Using a non-const ref is quite dangerous, as it might mean that the passed argument gets modified internally. 
- also somewhat cleaned up get_phi implementation. 

add const to trackseed get_phi implementation and cleanup

---

offline/packages/mbd/Makefile.am
offline/packages/mbd/MbdPmtHit.h
offline/packages/mbd/MbdPmtSimContainerV1.cc
offline/packages/mbd/MbdPmtSimContainerV1.h
offline/packages/mbd/MbdPmtSimContainerV1LinkDef.h
offline/packages/mbd/MbdPmtSimHitV1.cc
offline/packages/mbd/MbdPmtSimHitV1.h
offline/packages/mbd/MbdPmtSimHitV1LinkDef.h
simulation/g4simulation/g4bbc/MbdDigitization.cc
simulation/g4simulation/g4bbc/MbdDigitization.h

[comment]: Added MbdPmtSimContainer. Allows standard MBD q (now stored with the same units as data), retains npe as separate field.

MBD digitization updated so that it matches data better

---

offline/packages/intt/InttClusterQA.cc
offline/packages/intt/InttClusterQA.h
offline/packages/intt/InttFeeMap.cc
offline/packages/intt/InttFeeMap.h
offline/packages/intt/InttFeeMapLinkDef.h
offline/packages/intt/InttFeeMapv1.cc
offline/packages/intt/InttFeeMapv1.h
offline/packages/intt/InttFeeMapv1LinkDef.h
offline/packages/intt/InttMap.cc
offline/packages/intt/InttMap.h
offline/packages/intt/InttMaskedChannelSet.cc
offline/packages/intt/InttMaskedChannelSet.h
offline/packages/intt/InttMaskedChannelSetv1.cc
offline/packages/intt/InttSurveyMap.cc
offline/packages/intt/InttSurveyMap.h
offline/packages/intt/InttSurveyMapv1.cc
offline/packages/intt/InttSurveyMapv1.h
offline/packages/intt/Makefile.am

to eventually replace the autogenerated switch statements InttFelixMap uses. Expanded functionality of InttMap, implemented comparators and inc/dec operators for the structs

Added an InttFeeMap class that loads the fee mapping from CDB

---

offline/framework/fun4allraw/Fun4AllStreamingInputManager.cc

The streaming readout combining crashes in the tpc with an overflow in root (which uses ints for sizes???)
Fatal in <TBufferFile::AutoExpand>: Request to expand to a negative size, likely due to an integer overflow: 0x800002c6 for a max of 0x7ffffffe.
aborting
This PR resets the tpc hit container if it has > 500k entries (for the current cosmics/calibrations the number of entries is ~160k), the crash occurs with 4702171 entries
[comment]: <> ( In case this is a draft PR, e.g. …

apply cut on number of entries for tpc container, reset if > 500000

---

offline/packages/eventplaneinfo/EventPlaneReco.cc
offline/packages/eventplaneinfo/EventPlaneReco.h
offline/packages/eventplaneinfo/EventplaneinfoMap.h
offline/packages/eventplaneinfo/EventplaneinfoMapv1.h
offline/packages/eventplaneinfo/Makefile.am

Talked to Chris, we need to produce the event plane reco now. Ok :) This adds some additions from a local version- the z-vertex cuts. This is already ok for mass production. Keep in mind that the corrections will also be done as a function of z-vertex (testing in progress for optimal width, run by run variations etc...).

add vertex info the event plane reco

---

offline/database/cdbobjects/CDBHistos.cc
offline/database/cdbobjects/CDBHistos.h

This PR adds a flag to CDBHisto::getHisto to suppress the error message. It will still return null ptrs for non existing histograms but now this can be used to check if a histogram exists in the cdb

add flag to suppress histogram not found error message

---

offline/packages/intt/InttMap.cc
offline/packages/intt/InttSurveyMap.cc

Fixed a bug in the InttSurveyMap::GetStripTransform method
Improved inc/dec implementation so it is easy to configure loops over subsets of the INTT's channels

Intt GetStripTransform fix and inc/dec changes

---

generators/phhepmc/Makefile.am
generators/phhepmc/PHHepMCDefs.h
offline/packages/CaloEmbedding/HepMCCollisionVertex.cc
offline/packages/NodeDump/DumpPHHepMCGenEventMap.cc
simulation/g4simulation/g4main/EicEventHeaderv1.cc
simulation/g4simulation/g4main/Fun4AllDstPileupInputManager.h
simulation/g4simulation/g4main/Fun4AllDstPileupMerger.h
simulation/g4simulation/g4main/HepMCNodeReader.cc
simulation/g4simulation/g4main/HepMCNodeReader.h
simulation/g4simulation/g4main/PHG4Detector.cc
simulation/g4simulation/g4main/PHG4Hitv1.cc
simulation/g4simulation/g4main/PHG4MagneticField.cc
simulation/g4simulation/g4main/PHG4MagneticField.h
simulation/g4simulation/g4main/PHG4ParticleGeneratorD0.cc
simulation/g4simulation/g4main/PHG4ParticleGeneratorVectorMeson.cc
simulation/g4simulation/g4main/PHG4Particlev2.cc
simulation/g4simulation/g4main/PHG4Particlev2.h
simulation/g4simulation/g4main/PHG4PhenixStackingAction.h
simulation/g4simulation/g4main/PHG4Showerv1.cc
simulation/g4simulation/g4main/PHG4StackingAction.h

This PR fixes the embedding. The HepMCNodeReader aborted the event reconstruction if the GenEvent ptr inside the PHHepMCGenEventMap was a nullptr. We use the first entry in this map to propagate the event vertex to the embedding generator (pythia8) but leave GenEvent null.
The new code skips over null pointers and removes those entries from the  PHHepMCGenEventMap so they are not stored on the DST confusing subsequent analysis code
[comment]: <> ( In case this is a draft PR, …

Fix embedding

---

offline/packages/trackreco/PHCASeeding.cc

There was a small bug in PHCA seeding in which the call to find neighboring clusters across the periodic phi boundaries were not found. This is fixed. The effect is quit small, as it is relatively rare to have the phi search across the boundary.

Fix boost::geometry::index intersect call

---

offline/packages/eventplaneinfo/EventPlaneReco.cc
offline/packages/eventplaneinfo/EventPlaneReco.h

Some cosmetic changes (no change in the physics output) based on Chris' request:
- Move loop over orders from 1 to 0
- include changes to cdbhist (turn off warning messages for unavailable hists)
- use rc flag for run number 
The fetching of the final calibration from the cdb for the reconstruction pass so that this can be added to the production cannot be implemented at this time. This will require direct insertion of the calibration histograms into the cdb, which is currently solely under expert (Chris') control.

Minimal additions to event plane reco

---

offline/packages/eventplaneinfo/EventPlaneReco.cc
offline/packages/eventplaneinfo/EventPlaneReco.h

I added a second dimension to the event plane calibration histograms to address the vertex dependence of the calibration constants. Attached pngs shows the results.

add vertex dependent calibration to event plane reconstruction

---

simulation/g4simulation/g4detectors/PHG4DetectorSubsystem.cc
simulation/g4simulation/g4micromegas/PHG4MicromegasDetector.cc
simulation/g4simulation/g4micromegas/PHG4MicromegasSubsystem.cc
simulation/g4simulation/g4micromegas/PHG4MicromegasSubsystem.h

Make whether survey is applied to Micromegas geometry or not configurable, for testing purposes. 
Default is to apply the survey data.

Micromegas survey flag

---

offline/packages/tpccalib/PHTpcResiduals.cc
offline/packages/tpccalib/PHTpcResiduals.h

This consolidates PHTPCResiduals to get more robust distortion correction maps. 
- extrapolate from any track state rather than only the one at beginning
- check from not-a-number in matrix calculation. one could also track down the reasons for nan in the first place, but since any single occurence, no matter how rare, breaks the whole matrix calculation (and all processed past events), better keep the check in place.
[comment]: <> ( In case this is a draft PR, e.g. for running checks using Jenkins, please make the pull request as a …

Phtpcresiduals update

---

offline/packages/trackbase_historic/TrackSeed_v1.h

m_phi was introduced not only to trackseed_v2 (as it should) but also to trackseed_v1, by mistake
This breaks backward readability of DSTs in which seeds are stored.
This fixes that.

removed m_phi

---

offline/packages/CaloReco/CaloWaveformFitting.cc

This is for HCal TP runs, for some runs we have the peak around 4 which caused using the average of first three samples as pedestal being not accurate. This PR switch to use last two samples for the pedestal if the peak appears before sample 5.

FAST: use last two samples for pedestal if peak is too early

---

simulation/g4simulation/g4main/PHG4DisplayAction.cc
simulation/g4simulation/g4main/PHG4Reco.cc

This PR prepares for reading the fieldmap from the cdb, if the name of the calibration is used for the fieldmap it will be read from the cdb. This allows comparing between old and new fieldmaps

read fieldmap from optional from cdb

---

offline/framework/fun4allraw/Fun4AllStreamingInputManager.cc
offline/packages/mvtx/MvtxCombinedRawDataDecoder.cc
offline/packages/mvtx/MvtxCombinedRawDataDecoder.h

When we run the event combiner for the MVTX and no other detectors, all hits are deleted. This is due to a check on the reference BCO and the BCO range to look for hits in. All values are unsigned ints and the reference BCO defaults to 0. When we subtract the range from the reference, we wrap around to almost the max value of and unsigned 64-bit int.
Also, in the unpacker, there's a check for the GL1 so we can figure out the MVTX time bucket. There's no GL1 in standalone mode so flags were put in to avoid this
[comment]: <> ( In case …

MVTX standalone event combining

---

offline/packages/tpc/TpcLoadDistortionCorrection.h

- added convenience enum for setting the right distortion filename
- removed deprecated (and ambiguous) setter.
This requires https://github.com/sPHENIX-Collaboration/macros/pull/794

cleanup loading distortion correction files.

---

offline/packages/trackbase_historic/TrackSeed_v2.cc

This gets the cosmic seeding back in order by placing guards around the new circle and line fit functions for cluster key set sizes that are unfittable.

fix: add guards for unfittable cluster set sizes

---

offline/packages/mbd/MbdCalib.h
offline/packages/mbd/MbdSig.cc
offline/packages/mbd/MbdSig.h

The MbdSig printed excessive messages (10MB) if the spline fit failed. This PR puts this behind a verbosity flag

put execessive printouts behind verbosity

---

offline/packages/tpc/TpcLoadDistortionCorrection.cc
offline/packages/tpccalib/TpcSpaceChargeMatrixInversion.cc
offline/packages/tpccalib/TpcSpaceChargeMatrixInversion.h
offline/packages/tpccalib/TpcSpaceChargeReconstructionHelper.cc
offline/packages/tpccalib/TpcSpaceChargeReconstructionHelper.h

This PR complete the extrapolation code for TPC distortion corrections.
TpcSpaceChargeMatrixInversion can now load 2D central-membrane distortion corrections, and use it to perform the extrapolation from TPOT acceptance to TPC acceptance.
Still missing is a steering macro (JobB), which will look like this: 
TpcSpaceChargeMatrixInversion matrix_inversion;
matrix_inversion.load_average_distortion_corrections( inputfile );
matrix_inversion.load_cm_distortion_corrections( inputfile_cm );
matrix_inversion.extrapolate_distortion_corrections();
matrix_inversion.save_distortion_corrections( outputfile ); …

Tpc distortion extrapolation 2

---

offline/packages/tpccalib/PHTpcResiduals.cc
offline/packages/tpccalib/TpcSpaceChargeReconstruction.cc

This PR changes the derivatives calculation that enter the distortion correction matrices, so that when inverted, delta_phi (in rad) is provided, rather than rdelta_phi (in cm).
This was verified to have no impact on the performances of the distortion reconstruction.

Distortion correction model

---

offline/packages/tpccalib/TpcSpaceChargeMatrixInversion.cc
offline/packages/tpccalib/TpcSpaceChargeMatrixInversion.h

This PR fixes the remaining perennial clang-tidy complaint, this should now give us a clean clang-tidy report if no new errors crept in with a PR

fix remaining perennial clang-tidy warning

---

offline/packages/KFParticle_sPHENIX/KFParticle_sPHENIX.cc
offline/packages/KFParticle_sPHENIX/KFParticle_sPHENIX.h

The new magnetic field doesn't have an entry at the origin. KFParticle was hardcoded to read this value. This PR now performs a radial sweep of the field map along z until it finds the first entry of the map and sets the KFParticle field to this.

KFP: Safer magnetic field reading

---

offline/packages/trackreco/Makefile.am
offline/packages/trackreco/PHSiliconCosmicSeeding.cc
offline/packages/trackreco/PHSiliconCosmicSeeding.h

The first cosmic seeder was intended to be deployed in the TPC and search for long chains, which is not suitable for silicon only cosmic seeding. The Acts seeder also doesn't work well here due to the non-beam like conditions. This PR adds a simple CA seeder to be used in the silicon that creates straight line tracks traversing the MVTX and INTT.

feat: silicon cosmic seeder

---

offline/framework/fun4allraw/Fun4AllStreamingInputManager.cc

When using data without the GL1 the reference bco wasn't set correctly, now it is set to the first subsystem in the order of gl1, intt, mvtx, tpot, tpc

Handle RefBCO correctly if running without the GL1

---

offline/QA/Trigger/Makefile.am
offline/QA/Trigger/TriggerValid.cc
offline/QA/Trigger/TriggerValid.h

This fixes the trigger QA module to use the qautils library so all QA histograms in any given macro are handled in the same way

fix: use qautils in TriggerValid

---

offline/packages/trackreco/PHCASeeding.cc
offline/packages/trackreco/PHCASeeding.h

This small pull request adds setters for the PHCASeeding module to expand the tolerance windows when adding clusters to a track seed.

update windows for growing track seeds

---

offline/packages/micromegas/MicromegasCombinedDataDecoder.cc
offline/packages/micromegas/MicromegasCombinedDataEvaluation.cc
offline/packages/micromegas/MicromegasDefs.h
offline/packages/micromegas/MicromegasRawDataCalibration.cc
offline/packages/micromegas/MicromegasRawDataDecoder.cc
offline/packages/micromegas/MicromegasRawDataEvaluation.cc
offline/packages/micromegas/MicromegasRawDataEvaluation.h

This PR makes the Micromegas decoding, calibration and evaluation code ignore all samples for which ADC value is invalid, with 'invalid' value being set to 65000, as per @tsakagu prescription. 
Also include a change on RawDataEvaluation to get tagger's in the output tree.

Micromegas fix data decoding

---

offline/framework/fun4allraw/SingleTpcPoolInput.cc

TPC data decoder has been modified to accommodate ZS-mode that is needed to check the ZS data by ddump and online monitoring. This fix is a temporary prescription so that offline codes won't get hiccup by the change. 

Temporary prescription for decoder change in TPC readout

---

offline/framework/fun4allraw/SingleTpcPoolInput.cc

Temp remedy was added for production of zero-suppression data.
The data looks almost same as non-ZS data, except for those time samples that
are not existing are set to zero.

Temp remedy for ZS data for production

---

offline/packages/CaloBase/TowerInfoContainerv1.cc
offline/packages/CaloBase/TowerInfoContainerv2.cc
offline/packages/CaloBase/TowerInfoContainerv3.cc
offline/packages/CaloBase/TowerInfoDefs.cc
offline/packages/CaloReco/CaloTowerBuilder.cc

Changes:
For ZDC-SMD: reconstruct all 52 channels
For sEPD: Mask channels not instrumented using updated 2024 map

reconstruct SMD, update sEPD masking

---

offline/packages/mbd/MbdCalib.cc
offline/packages/mbd/MbdCalib.h
offline/packages/mbd/MbdEvent.cc
offline/packages/mbd/MbdEvent.h
offline/packages/mbd/MbdReco.cc
offline/packages/mbd/MbdSig.cc

[comment]: Added a new feature where, if the sampmax calib doesn't exist, the reco will determine it from the first 1000 events (and discardevent).  After that, all will be as usual.  This requires that the other calibrations that are not run-dependent exist.
[comment]: In principle, one should run a calibration pass, then do the production.  But if the production is done first, this will allow the production to bootstrap itself, even if the run-to-run MBD calibrations don't exist.

MBD: added on the fly sampmax calib for runs where it doesn't exist

---

offline/QA/Jet/Makefile.am
offline/QA/Jet/TrksInJetQA.cc
offline/QA/Jet/TrksInJetQA.h
offline/QA/Jet/TrksInJetQABaseFiller.cc
offline/QA/Jet/TrksInJetQABaseFiller.h
offline/QA/Jet/TrksInJetQABaseManager.cc
offline/QA/Jet/TrksInJetQABaseManager.h
offline/QA/Jet/TrksInJetQAClustManager.cc
offline/QA/Jet/TrksInJetQAClustManager.h
offline/QA/Jet/TrksInJetQAConfig.h
offline/QA/Jet/TrksInJetQAHist.h
offline/QA/Jet/TrksInJetQAHitManager.cc
offline/QA/Jet/TrksInJetQAHitManager.h
offline/QA/Jet/TrksInJetQAInJetFiller.cc
offline/QA/Jet/TrksInJetQAInJetFiller.h
offline/QA/Jet/TrksInJetQAInclusiveFiller.cc
offline/QA/Jet/TrksInJetQAInclusiveFiller.h
offline/QA/Jet/TrksInJetQAJetManager.cc
offline/QA/Jet/TrksInJetQAJetManager.h
offline/QA/Jet/TrksInJetQATrkManager.cc
offline/QA/Jet/TrksInJetQATrkManager.h
offline/QA/Jet/TrksInJetQATypes.h
offline/QA/Jet/autogen.sh
offline/QA/Jet/configure.ac

This PR adds a QA module which accumulates histograms for tracks and their constituent clusters and hits both in jets and inclusively. The code is designed to be flexible with respect to inputs (it will work for jets made from tracks, particle flow elements, calorimeter towers/clusters, or any combination of them) and easy to extend with respect to outputs (additional histograms are easily generated for different populations of jets, tracks, etc.).
Furthermore, the module can be run both as a plain `SubsysReco` with output being written to a specified file, or with histograms being handled by the QA Histogram Manager.
This PR adds a new feature, and the module was developed as part of the Jet Structure QA workfest. A macro illustrating usage of the module and a README with further …

Add general tracks-in-jets QA module

---

offline/framework/ffarawmodules/ClockDiffCheck.cc

the clock diff check just prints out too much, and it's likely a false positive after some unhandled rollover

limit clockdiff printouts to 1k

---

offline/packages/mbd/MbdEvent.h
offline/packages/mbd/MbdReco.cc

[comment]: fixed bug which caused aborts when processing on sim dsts
[comment]: when running on sim dst, we processed it as if it were a real dst

fixed bug which caused aborts when processing on sim dsts

---

offline/packages/trackreco/PHCASeeding.cc
offline/packages/trackreco/PHCASeeding.h

All changes are at the pre-processer level, controlled by a `#define _CLUSTER_LOG_TUPOUT_` 
variable that can be uncommented prior to compiling. Without this un-commenting, this PR makes
no changes to the code. It will, however, be helpful with diagnosing changes and effects in the
PHCASeeding code.

Add TNtuple to track progress of seeding

---

calibrations/xingshift/XingShiftCal.cc
calibrations/xingshift/XingShiftCal.h

This PR expands the capability of the crossing shift calculation to match all unfilled bunches instead of relying only on the abort gap. This can be useful for fills with less than 111 bunches.

xingshift - match general unfilled bunches

---

offline/packages/TrackingDiagnostics/TrackResiduals.cc
offline/packages/TrackingDiagnostics/TrackResiduals.h
offline/packages/TrackingDiagnostics/TrackSeedTrackMapConverter.cc
offline/packages/TrackingDiagnostics/TrackSeedTrackMapConverter.h
offline/packages/trackreco/AzimuthalSeeder.cc
offline/packages/trackreco/AzimuthalSeeder.h

This adds a number of diagnostic tools
1. Can configure the outlier limit for azimuthal seeder from the macro
2. Adds line fit with DCA to track back to (0,0,0) for zero field alignment testing
3. Enables field on running/diagnostic for individual track seed containers

feat: more track diagnostic tools

---

simulation/g4simulation/g4ohcal/PHG4OHCalDetector.cc

The ohcal steel fieldmap was loaded even for constant magnetic fields. It wasn't used but the logs and saved cdb files made the impression that it was. This moves the loading after the check if we have a constant field. This works for zero field, if a non zero strength is used the outer hcal magnet field does not work …

move ohcal fieldmap loading after check for constant field

---

offline/packages/mbd/MbdCalib.cc
offline/packages/mbd/MbdCalib.h
offline/packages/mbd/MbdEvent.cc
offline/packages/mbd/MbdEvent.h
offline/packages/mbd/MbdReco.cc
offline/packages/mbd/MbdSig.cc
offline/packages/mbd/MbdSig.h

[comment]: Cleaning up code for on-the-fly calibrations, online and rawdst processing
[comment]: Cleaned up the way the calibration of samp max is done (potential for confusion between online mon, on-the-fly, and regular calibration).  Fixed up the h2_trange so that it is in the correct calib pass.  Fixed reco so events with 1 hit pmt on a side  get a time in that pmt.

Cleaning up code for on-the-fly calibrations, online and rawdst processing

---

offline/packages/intt/InttCombinedRawDataDecoder.cc
offline/packages/micromegas/MicromegasCombinedDataDecoder.cc
offline/packages/mvtx/MvtxCombinedRawDataDecoder.cc
offline/packages/tpc/TpcCombinedRawDataUnpacker.cc

This changes the raw hit unpackers to unregister the module and continue processing the job if their respective raw hit container does not exist on the node tree. This change is being made to allow our production to be more flexible with the files/DSTs that are produced.

fix: Unregister modules if raw hit container does not exist

---

offline/packages/mbd/MbdEvent.cc

[comment]: Added additional _is_online to see if this fixes the problem of bad data at the beginning of a run.
[comment]: Suspicious that the online mon issue with bad data in the first few hundred events or so is due to the sampmax not being recalibrated on every run.  Changes here should help to make sure that the on-the-fly sampmax calib is done on every run change.

ensure sampmax on the fly calib is done in online when runs change

---

calibrations/xingshift/XingShiftCal.cc

This PR will write spin patterns, fillnumber, polarizations, and xingshift=-999 to the spinDB in the event that the crossing shift calibration fails. Previously, if the crossing shift calibration failed, nothing would be written to spinDB.

Write to spinDB even if XingShift calibration fails

---

offline/packages/CaloEmbedding/caloTowerEmbed.cc

Propagates TowerInfo status from data to embedding automatically during embedding (requires use of TowerInfov2 for sim)

Propagate tower status to embed DST from data DST

---

calibrations/xingshift/XingShiftCal.cc

This PR fixes the bug where xingshiftcal will write to the spin db even if the run doesn't exist.

Fix improper writing to spin db with no run

---

offline/packages/trackreco/PHCASeeding.cc
offline/packages/trackreco/PHCASeeding.h

The code revises PHCASeeding for efficiency of execution. The result is that PHCASeeding now runs ~12-30% faster for generating the bilinks (the most time consuming part of the code). Some changes are:
* The boost trees are now 2D instead of 3D
* The cached map is now a std::unordered_map instead of a std::map
* `using` statements are now scoped internal to the namespace of the PHCASeeding class (before they were set in the global namespace)
* The keyLinks now are just std::pair<TrkrDefs::cluskey,TrkrDefs::cluskey> instead of the std::array<coordKey,2> with coordkey=std::pair<std::array<float,3>,TrkrDefs::cluskey. This is because in the code, as implemented, the global position of the links was always taken from the cached …

Update PHCASeeding with more efficient code to execute same algorithm.

---

simulation/g4simulation/g4tpc/PHG4TpcSubsystem.cc

@mohaas33 
- Please double check the value.  If I understand right, it is the correct one. 
- in any case, with a coming PR in the macros repository, this is overriden by G4TPC::tpc_layer_rphi_count_inner, as defined in macros/common/G4_TrkrVariables.C
Note: only the value set in PHG4TpcSubsystem is relevant for offline reconstruction of real data.
However, the values must be the same between PHG4TpcSubsystem and PHG4TpcPadPlaneReadout in the simulations, to have consistency between were hits are generated and where they are reconstructe.d
[comment]: <> ( What does this PR do? Linking to talk in software meeting …

- use the same default parameter values as that as PHG4TpcPadPlaneReadout

---

offline/packages/TrackingDiagnostics/TrackResiduals.cc
offline/packages/micromegas/MicromegasClusterizer.cc
offline/packages/micromegas/MicromegasClusterizer.h
offline/packages/trackreco/PHMicromegasTpcTrackMatching.cc
offline/packages/trackreco/PHMicromegasTpcTrackMatching.h

Found that in real data there are multiple micromegas clusters with different positions associated with a single track. Traced this to the micromegas clustering finding many single strip clusters in addition to what appear to be more realistic 2 or more strip clusters. Modified the clustering to not add single strip clusters to the cluster container. This may not be the optimal fix, that needs more study.
Also, modified micromegas-TPC matcher to not skip tracks with no silicon …

Drop single strip clusters in Micromegas clusterizer

---

offline/packages/trackreco/PHCASeeding.cc
offline/packages/trackreco/PHCASeeding.h

[comment]: A typo snuck into the PHCASeeding update, but only for the code with the debugging macro's turning on. This corrects that error and some of the code comments. It has no effect on the default-compiled code.

Phca seeding minor update

---

offline/packages/TrackingDiagnostics/TrackResiduals.cc

This fixes a bug in the dE/dx calculation in TrackResiduals. It was assumed that the TPC seed clusters were all TPC clusters, but matched TPOT clusters are also added to the TPC seed cluster list. This produced a fatal geometry lookup error for the TPOT clusters.

Fix bug in TrackResiduals dE/dx calculation

---

offline/packages/CaloReco/RawClusterBuilderTopo.cc

Fixing a but where the sorting and removal of duplicated elements in the vector of neighbors was inside a if statement, taking effect only when the verbosity was higher than 5.

Fix to vector of neighbors having unique elements in splitting phase

---

offline/framework/fun4allraw/SingleMicromegasPoolInput.cc
offline/framework/fun4allraw/SingleMicromegasPoolInput.h
offline/packages/micromegas/MicromegasDefs.h
offline/packages/micromegas/MicromegasMapping.cc
offline/packages/micromegas/MicromegasMapping.h
offline/packages/micromegas/MicromegasRawDataEvaluation.cc
offline/packages/micromegas/MicromegasRawDataEvaluation.h

This is a new attempt at full event assembly for TPOT, taking advantage of the new FEE firmware. 
It uses the gtm bco information, projected back to the 20 bits FEE BCO to decide which waveform belongs to which trigger. 
Works much better than what we had before. 
I am aware that Jin is working on a similar code for the TPC, but having two independantly written codes to do the same here: it will help debug the many foreseen error conditions from the high trigger rate, zero suppressed data we will soon have to assemble. 
Once everything is ironed out, we will converge on a unique version applicable to both the TPC and TPOT. 
In the meanwhile this PR will allow to properly assemble the recent high trigger rate, non-zero …

Micromegas full event assembly

---

offline/packages/TrackingDiagnostics/TrkrNtuplizer.cc

Fixes de/dx segfault when there are tpot clusters on track

fix: dedx seg fault

---

offline/QA/Jet/JetKinematicCheck.cc
offline/QA/Jet/JetKinematicCheck.h
offline/QA/Jet/Makefile.am

Adding code to QA/Jet to monitor jet kinematics in p+p collisions. 
This PR adds the source files JetKinematicCheck.cc and JetKinematicCheck.h to the QA/Jet directory. These files are used to generate histograms for the jet spectra, jet eta-phi distribution, and jet mass spectra (for pt and eta) for reconstructed jets with radii R = 0.2, 0.3, and 0.4 in p+p collisions. …

Adding Code for Jet Kinematics QA in QA/Jet

---

offline/QA/Tracking/InttClusterQA.cc
offline/QA/Tracking/InttClusterQA.h
offline/QA/Tracking/MicromegasClusterQA.cc
offline/QA/Tracking/MicromegasClusterQA.h
offline/QA/Tracking/MvtxClusterQA.cc
offline/QA/Tracking/MvtxClusterQA.h
offline/QA/Tracking/TpcClusterQA.cc
offline/QA/Tracking/TpcClusterQA.h

Removes per run histograms as they don't make sense in the offline qa framework that now exists

fix: remove per run histos

---

offline/packages/trackreco/PHCASeeding.cc
offline/packages/trackreco/PHCASeeding.h

Talked with Michael. This allows the PHCASeeder to follow seeds not at a fix value of 6 clusters, but from N-M clusters, where N and M are set with the already existing setter `PHCASeeding::SetNClustersPerSeedRange`
I've tested it with short and longer values and it works as intended.

Update to use the values for min and max length of seeds

---

offline/packages/TrackingDiagnostics/TrackResiduals.cc
offline/packages/TrackingDiagnostics/TrackResiduals.h
offline/packages/TrackingDiagnostics/TrackSeedTrackMapConverter.cc
offline/packages/tpc/TpcCombinedRawDataUnpacker.cc
offline/packages/tpc/TpcCombinedRawDataUnpacker.h
offline/packages/trackreco/PHActsSiliconSeeding.cc
offline/packages/trackreco/PHSiliconTpcTrackMatching.cc
offline/packages/trackreco/PHSiliconTpcTrackMatching.h
offline/packages/trackreco/PHSimpleKFProp.cc
offline/packages/trackreco/PHSimpleKFProp.h

This PR contains development that allows us to match tracks in the silicon and tpc in the run 24 data. A few changes that need noting:
1. The tpc unpacker now has a pre sample shift that can be set. This is to accommodate the change from 80 to 120 pre samples in the readout that occurred at run 41624. @blackcathj your comment would be valuable on this - for example do we need to store this in the run db and look it up automatically? Is this planning to be changed again? See [this](https://github.com/sPHENIX-Collaboration/coresoftware/commit/32eac34ed5514f5dc80726e413c17f9a9b7ab1ce) commit for more details
2. The setting …

feat: match silicon and tpc track seeds

---

offline/packages/jetbackground/DetermineTowerBackground.cc
offline/packages/jetbackground/DetermineTowerBackground.h
offline/packages/jetbackground/RetowerCEMC.cc
offline/packages/jetbackground/RetowerCEMC.h
offline/packages/jetbackground/SubtractTowers.cc
offline/packages/jetbase/TowerJetInput.cc

This PR updates the jetbase and jetbackground packages to account for the updates to calorimeter masking based on the calo tower status. Additionally, this introduces a method of propogating masking to the retowered EMCal towers, which scales the retowered tower energy to account for the masked area. Towers with > 50% of their area masked are fully masked, with the 50% threshold being configurable using set_frac_cut(CUT).
This was discussed in the jet structure TG meeting on 5/22: https://indico.bnl.gov/event/23535/
[comment]: <> ( In …

Updating jet reconstruction to properly account for masked towers

---

offline/packages/trackreco/PHCASeeding.cc
offline/packages/trackreco/PHCASeeding.h

This fixes a bug that was duplicating links in the PHCASeeding which massively increased the size of seeds produced. The results are much smaller numbers of seeds and chains.
It also fixes a transition from old version of code from eta to Z (as well as the names)
It also contains some compile-time options to fill yet more tuples that show locations in which the chains fork
  …

Fix duplication of chains in PHCASeeding

---

offline/packages/CaloBase/TowerInfo.h
offline/packages/CaloBase/TowerInfov2.h
offline/packages/CaloReco/CaloTowerBuilder.cc

Add ZS status getter(`get_isZS()` ) and setter ( `set_isZS(ZS)` ), and set it in `CaloTowerBuilder`, also the `isNotInstr` setting is obsolete and I updated it also ;)

add isZS status getter and setter, and set it in the `calotowerbuilder`

---

offline/packages/TrackingDiagnostics/TrackResiduals.cc
offline/packages/TrackingDiagnostics/TrackResiduals.h
offline/packages/tpc/Makefile.am
offline/packages/tpc/TpcGlobalPositionWrapper.cc
offline/packages/tpc/TpcGlobalPositionWrapper.h
offline/packages/trackreco/MakeSourceLinks.cc
offline/packages/trackreco/MakeSourceLinks.h
offline/packages/trackreco/PHCASeeding.h

This introduces a wrapper class which applies the distortion corrections in one place when obtaining the global position of a tpc cluster. It leaves the other function alone so that we still have the ability to obtain only the uncorrected global position.

fix: call distortion corrections in global position determination

---

offline/packages/jetbackground/CopyAndSubtractJets.cc
offline/packages/jetbackground/CopyAndSubtractJets.h
offline/packages/jetbackground/DetermineTowerBackground.cc
offline/packages/jetbackground/DetermineTowerBackground.h
offline/packages/jetbackground/RetowerCEMC.cc
offline/packages/jetbackground/RetowerCEMC.h
offline/packages/jetbackground/SubtractTowers.cc
offline/packages/jetbackground/SubtractTowers.h
offline/packages/jetbase/TowerJetInput.cc
offline/packages/jetbase/TowerJetInput.h

Updating the jet reconstruction code so that the tower node names aren't hard coded and a user can define a prefix for the nodes. It defaults to use "TOWERINFO_CALIB" as the prefix, which is what was previously hard coded in there. 
Update to HIJetReco.C so it takes in the user defined prefix: …

adding configurable tower prefix to jet reco

---

offline/framework/ffarawmodules/ClockDiffCheck.cc
offline/framework/ffarawmodules/ClockDiffCheck.h

This change drops packets in ClockDiffCheck.cc when the clock difference of a given packet does not match the GL1 packet. Note that this will cause productions to fail as soon as the GL1 is out of sync - this is a stopgap before the event combiner can be fixed.

Added dropping packets when clock difference does not match.

---

offline/framework/ffarawobjects/Gl1Packet.h
offline/framework/ffarawobjects/Gl1Packetv1.cc
offline/framework/ffarawobjects/Gl1Packetv2.cc
offline/framework/ffarawobjects/Gl1Packetv2.h
offline/framework/fun4allraw/SingleGl1TriggerInput.cc

added a data member to the Gl1Packetv2; TriggerVector is deprecated
The new "IDGL1V1" packet provides a new data member, the "Scaled" trigger vector.
I added the new "ScaledVector" member to the Gl1Packetv2; deprecated the "TriggerVector" name in favor of "LiveVector"; Gl1Packetv1 returns 0 when asked for "ScaledVector" but doesn't emit a warning. 
The use of "TriggerVector" will continue to work.
[comment]: <> ( In case this is a draft PR, e.g. for running checks using …

mlp - added a data member to the Gl1Packetv2; TriggerVector is deprecated

---

offline/packages/tpc/TpcCombinedRawDataUnpacker.cc

Adds a check to apply the presample shift to the offline hits based on the runnumber in fun4all. Allows correct processing of data before 41624 when the number of pre samples changed from 80 to 120.

fix: check run number for number of presamples

---

offline/packages/TrackerMillepedeAlignment/HelicalFitter.cc
offline/packages/TrackerMillepedeAlignment/HelicalFitter.h
offline/packages/TrackingDiagnostics/TrackResiduals.cc

Generalizes the helical fitter to use the silicon tpc track seed container, and also adds a check for a track size of at least 4 since 3 cluster tracks trivially have all of their circle-fit residuals == 0.

fix: generalize helical fitter use

---

offline/packages/trackreco/PHCASeeding.cc
offline/packages/trackreco/PHCASeeding.h

[comment]: <> 
Apologies for yet another commit. Some work that I had done updating the legacy (and some carryover into new) "phi" naming in variables and tuple tags to "z" was lost in one branch or another. This corrects that. Minus potential typo (I've run the code myself, and it all appears to be working fine) these don't change any numeric functionality in the code.

Name changes only -- legacy (and new) phi to Z

---

offline/packages/CaloReco/RawClusterBuilderTopo.h

Fixing the towers alignment between EMCal and HCal for topo-clusters reconstructed using EMCal+HCal reconstruction mode.

Fix to the EMCal<->HCal alignment

---

offline/framework/frog/CreateDstList.pl

CreateDstList.pl now selects runs according to the selected dst type. It doesn't abort anymore if a run from a runlist is not found. jenkins does not check this: [skip-ci] 

no abort if run is not found, fix run selection

---

offline/packages/TrackingDiagnostics/TrackResiduals.cc
offline/packages/TrackingDiagnostics/TrackResiduals.h

Uses the distortion wrapper in the circle/line fits of track residuals

fix: use wrapper in circle/line fits

---

offline/framework/fun4allraw/Fun4AllStreamingInputManager.cc
offline/framework/fun4allraw/MicromegasBcoMatchingInformation.cc
offline/framework/fun4allraw/SingleMicromegasPoolInput.cc
offline/framework/fun4allraw/SingleMicromegasPoolInput.h

This is a first shot at keeping track of dropped data for TPOT
A new method 'FillBcoStatistics' is added to SingleMicromegasInput, called from Fun4AllStreamingInputManager
It stores how many packets and waveforms are found in TPOT for a BCO (from tagger) matching the requested BCO, by, e.g. GL1.
In non ZS mode, the expected number of waveform is about 4096. Anything below is dropped data.
In both ZS and non ZS mode, the expected number of packets is 2. Anything below is dropped data. …

Tpot bco statistics

---

offline/packages/jetbase/TowerJetInput.cc

Put a flag in TowerJetInput to skip events which have a z vertex > 1000. Very large z vertex values (appearing very rarely) were causing the code to crash. I also updated the error message that prints if the vertex container is empty to be Verbosity > 0, since the vertex is somewhat regularly not reconstructed and this causes confusion.

fix for crash with extremely large z vertex

---

offline/QA/Tracking/TpcClusterQA.cc
offline/QA/Tracking/TpcClusterQA.h

Adds region-separated histograms for computing fraction of clusters with phi size equal to 1 as a function of pT, and number of clusters per track histogram.

Adding Cluster Phi Size and Clusters/Track Histograms to QA Output

---

offline/packages/mbd/Makefile.am
offline/packages/mbd/MbdEvent.cc
offline/packages/mbd/MbdEvent.h
offline/packages/mbd/MbdGeom.h
offline/packages/mbd/MbdGeomV2.cc
offline/packages/mbd/MbdGeomV2.h
offline/packages/mbd/MbdGeomV2LinkDef.h
offline/packages/mbd/MbdReco.cc
offline/packages/mbd/MbdReco.h

[comment]: reads in gl1packet from DST_TRIGGERED_EVENT, uses only MBDNS triggered events for calibration.  Also added hv map to MbdGeom (in v2 class). 

Added gl1packet info so that only MBDNS triggered events are used in calibration

---

offline/packages/trackbase/ActsTrackingGeometry.h

This PR just gets rid of this annoying warning (by disabling the warnings via pragma for this include in the header file)
In file included from /cvmfs/sphenix.sdcc.bnl.gov/gcc-12.1.0/release/release_new/new.7/include/trackbase/ActsSurfaceMaps.h:9:
In file included from /cvmfs/sphenix.sdcc.bnl.gov/gcc-12.1.0/release/release_new/new.7/include/trackbase/ActsTrackingGeometry.h:4:
In file included from /cvmfs/sphenix.sdcc.bnl.gov/gcc-12.1.0/release/release_new/new.7/include/Acts/Defin …

suppress cling warning when including ActsTrackingGeometry.h

---

offline/QA/Jet/JetSeedCount.cc
offline/QA/Jet/JetSeedCount.h
offline/QA/Jet/StructureinJets.cc
offline/QA/Jet/StructureinJets.h

This PR adds a flag to a couple jet QA modules to avoid accidentally trying to save to a file when not needed.
Bug fix: user will now be able to turn off writing to output files in relevant jet QA modules.
This will let all modules be run by [macros#844](https://github.com/sPHENIX-Collaboration/macros/pull/844).

Add flag to turn off output file writing

---

offline/framework/fun4allraw/Fun4AllStreamingInputManager.cc
offline/framework/fun4allraw/MicromegasBcoMatchingInformation.cc
offline/framework/fun4allraw/MicromegasBcoMatchingInformation.h
offline/framework/fun4allraw/SingleMicromegasPoolInput.h
offline/packages/micromegas/MicromegasRawDataTimingEvaluation.cc

This PR updates TPOT sub-event assembly to adjust FEE and GTM BCO clock multiplier on the fly, thus correcting from clock shift. 
It was tested on the 42 segments of run 00045288
Will test on more runs in the near future. 
Also @jdosbo @rosstom2232 this fixes broken code from https://github.com/sPHENIX-Collaboration/coresoftware/pull/2826

Tpot decoding update

---

offline/packages/micromegas/MicromegasRawDataCalibration.cc
offline/packages/micromegas/MicromegasRawDataCalibration.h

This fixes inconsistency between processing  old data with new calibration file, due to fiber swapping.

also use 'old' fee_id for calibrations.

---

offline/packages/mvtx/MvtxCombinedRawDataDecoder.cc

This puts a check for the run number to determine the strobe length. We cannot access the database where this information is available in SDCC, so this will have to do for now so that we aren't producing nonsensical data in the offline. We need to return to this to get the information either into the CDB or into a db that is accessible in SDCC.

fix: unpacking strobe length

---

offline/framework/fun4allraw/MicromegasBcoMatchingInformation.cc
offline/framework/fun4allraw/MicromegasBcoMatchingInformation.h
offline/framework/fun4allraw/SingleMicromegasPoolInput.cc
offline/packages/micromegas/MicromegasDefs.h
offline/packages/micromegas/MicromegasRawDataCalibration.cc
offline/packages/micromegas/MicromegasRawDataDecoder.cc
offline/packages/micromegas/MicromegasRawDataEvaluation.cc
offline/packages/micromegas/MicromegasRawDataTimingEvaluation.cc
offline/packages/micromegas/MicromegasRawDataTimingEvaluation.h

This PR
- ignores heartbeat in decoding, calibration, event assembly, etc.
- uses modebits tagger to set clock reference, when found. The old method, using data, is kept, so that one can still process non-zero file segment when necessary
With this: could fully assembled several entire runs of TPOT zero-suppressed data with a failure rate < 0.3% (FEE data not associated to a trigger). …

Micromegas decoding 4

---

.gitignore
.vscode/settings.json
offline/packages/tpc/TpcDistortionCorrection.cc
offline/packages/tpc/TpcDistortionCorrection.h
offline/packages/tpc/TpcDistortionCorrectionContainer.h
offline/packages/tpc/TpcLoadDistortionCorrection.cc
offline/packages/tpc/TpcLoadDistortionCorrection.h

[comment]: <> This adds a 'module edge' distortion type, per Mariia's work.
[comment]: <> Up to four distortion corrections can now be applied.  2D corrections default to assuming they should be interpolated from stated values (at CM) to zero (at Readout), but the interpolation flag can also be set to false, which treats it as a z-independent distortion correction.  The module edge correction is expected to be z-independent for z more than ~few cm away from the readout.
It would be good to modify this to take 'n' distortions.  We can still hard-code that 'N', but '3' and now '4' appear in several places as a magic number.

New distortion correction type

---

offline/packages/intt/InttSurveyMap.h

Added ifdef to suppress undefined internal message when class is included in ROOT macros

(INTT) ifdef to suppress warning

---

calibrations/xingshift/XingShiftCal.cc
calibrations/xingshift/XingShiftCal.h
offline/packages/uspin/SpinDBInput.cc
offline/packages/uspin/SpinDBOutput.cc

This PR provides functionality for XingShiftCal to read gl1p scalers from the daq db and write them to the spin db. Additionally, the uspin package is updated to reflect a change in the naming convention of columns in the spin db.

Write GL1P scalers to SpinDB

---

offline/packages/trackreco/PHCASeeding.cc
offline/packages/trackreco/PHCASeeding.h

Fixes algorithm in `PHCASeeding` module to not match the same new "link" (matching cluster in next successive layer) to multiple previous links. (switch std::vector for std::set)

remove duplicate key matches in chain growth

---

offline/QA/Jet/JetKinematicCheck.cc

This PR resolves an exception thrown by a jet QA module.
This bug fix resolves an exception thrown in the `JetKinematicCheck` module: one histogram title was using a poorly formatted boost string.

hotfix: Fix poorly formatted boost string in jet QA

---

offline/framework/fun4allraw/MicromegasBcoMatchingInformation.cc
offline/framework/fun4allraw/SingleMicromegasPoolInput.cc
offline/packages/micromegas/MicromegasRawDataTimingEvaluation.cc

This PR cleans up internal lists/maps even when reference is not found to avoid ever-increasing, resulting in job crash.
Also hides some more printout behind a Verbosity statement.
Thanks to @jdosbo for pointin this out. 
Note: the run you are looking at (44681) will still bomb, because of not being able to assemble a single event for TPOT. 

Micromegas decoding 5

---

offline/framework/fun4allraw/SingleInttPoolInput.cc

This uses Martin's new INTT API to get the BCOs for each server without any hit requirement. The auto produced histos are filled in the same way

fix: use new intt hit api for auto produced histos

---

offline/packages/mvtx/MvtxCombinedRawDataDecoder.cc
offline/packages/mvtx/MvtxCombinedRawDataDecoder.h

This introduces a run-depended strobe length. This pulls from the read-only DB and only returns values as long as the info is there. We should default to 89 us in all other cases
Test results
```c++
Fun4AllServer::BeginRun: InitRun for MvtxCombinedRawDataDecoder
executable_command: 
psql -h sphnxdaqdbreplica daq --csv -c "SELECT strobe FROM mvtx_strobe WHERE hostname = 'mvtx0' AND runnumber = 45825;" | tail -n 1
strobe_query: 
9.9
The strobe length is 9.9
Registering Subsystem CDBInterface
``` …

CD: Run-dependent MVTX strobe length

---

offline/packages/TrackingDiagnostics/TrackResiduals.cc
offline/packages/TrackingDiagnostics/TrackResiduals.h

Modifies TrackResiduals by adding to residualtree the distortion corrected cluster position before the cluster mover puts it back on the surface. Now we have:
clusgxideal etc.        = cluster position with no corrections
clusgxunmoved etc. = cluster position after distortion corrections
clusgx etc.                = corrected cluster position moved to surface
stategx etc.               = track state at the cluster surface
[comment]: <> ( In case this is a draft PR, e.g. …

More TrackResiduals changes for better distortions handling 

---

offline/packages/TrackingDiagnostics/TrackSeedTrackMapConverter.cc
offline/packages/trackreco/PHActsSiliconSeeding.cc
offline/packages/trackreco/PHActsSiliconSeeding.h
offline/packages/trackreco/PHSiliconTpcTrackMatching.cc

This puts the assignment of the crossing number for silicon seeding into the actual silicon seeding algorithm, rather than in the matching. Will allow us to monitor crossing assignment for silicon seeds

refactor: crossing assignment into silicon seeding

---

offline/packages/micromegas/MicromegasCalibrationData.cc
offline/packages/micromegas/MicromegasCombinedDataDecoder.cc
offline/packages/micromegas/MicromegasCombinedDataEvaluation.cc
offline/packages/micromegas/MicromegasMapping.cc
offline/packages/micromegas/MicromegasMapping.h
offline/packages/micromegas/MicromegasRawDataCalibration.cc
offline/packages/micromegas/MicromegasRawDataDecoder.cc
offline/packages/micromegas/MicromegasRawDataEvaluation.cc

This PR attempts to fix my proprietary mess resulting from the latest (May 29) fiber swaping:
- Use new fiber ID rather than old, everywhere, as it should be
- Attempt at keeping backward compatibility with old data (old fiber ID) and old calibration files. This will become unnecessary as time passes by.
A similar commit to online monitoring will follow.  …

Fix fiber swap mess for TPOT

---

offline/packages/mvtx/MvtxCombinedRawDataDecoder.cc

MVTX strobe index (think of as timing info) was calculated as the difference between the GL1 BCO and strobe BCO. The variable used to store this was an unsigned int so if the strobe was larger than the GL1, we'd overflow.

MVTX strobe index patch

---

offline/packages/intt/InttCombinedRawDataDecoder.cc
offline/packages/mvtx/MvtxCombinedRawDataDecoder.cc

To keep old DSTs reconstructible, we need to check for the `GL1RawHit` container which was used before `GL1Packet`. At some point this will become obsolete when we reprocess DSTs, but we aren't there yet.

fix: option to look for old gl1 container

---

offline/framework/fun4allraw/Fun4AllStreamingInputManager.cc

Fixes a large memory leak in the mvtx event combining

fix: mvtx memory leak

---

offline/framework/fun4allraw/Fun4AllStreamingInputManager.cc
offline/framework/fun4allraw/SingleMvtxPoolInput.cc
offline/framework/fun4allraw/SingleMvtxPoolInput.h

Overloaded FillPool for SingleMvtxPoolInput so it rejects strobe frame hits that are below the current reference BCO window. This speeds up event processing with regards to the previous method that fills a pool then rejects these hits at the event combiner stage

CD: Moved MVTX BCO range check to pooler

---

offline/packages/tpc/TpcLoadDistortionCorrection.cc
offline/packages/tpc/TpcLoadDistortionCorrection.h

This allows different corrections to have different settings (interpolation type, treatment of the phi axis units) instead of being required to all share the same pair of flags.  To use this correctly it also needs the matching macro PR which will have the same title.
Without this, the default static distortion and default edge corrections can not both work correctly simultaneously.
Will post shortly in macros.  This compiles and …

extended radians and interpolation flags to be distortion dependent.

---

offline/framework/fun4all/Fun4AllBase.h

This PR changes the Fun4All verbosity from int to uint64_t to enable a decent bitwise verbosity setting if needed

use uint64_t for verbosity so we can also use bits

---

offline/QA/Jet/ConstituentsinJets.cc
offline/QA/Jet/ConstituentsinJets.h
offline/QA/Jet/JetKinematicCheck.cc
offline/QA/Jet/JetKinematicCheck.h
offline/QA/Jet/JetQADefs.h
offline/QA/Jet/JetSeedCount.cc
offline/QA/Jet/JetSeedCount.h
offline/QA/Jet/Makefile.am
offline/QA/Jet/RhosinEvent.cc
offline/QA/Jet/RhosinEvent.h
offline/QA/Jet/StructureinJets.cc
offline/QA/Jet/StructureinJets.h
offline/QA/Jet/TrksInJetQA.cc
offline/QA/Jet/TrksInJetQA.h
offline/QA/Jet/TrksInJetQABaseFiller.cc
offline/QA/Jet/TrksInJetQABaseFiller.h
offline/QA/Jet/TrksInJetQABaseManager.cc
offline/QA/Jet/TrksInJetQABaseManager.h

This PR makes two major updates to the Jet QA:
1. Certain inputs and parameters have been made user-configurable in order to avoid name clashes across modules and histograms, and to allow for the same module to be run on different jet populations in parallel;
2. And functionality has been added to all modules to allow the user to select on a specific trigger by specifying the desired trigger's index in the GL1 trigger vector.
This PR introduces the new features described above. There have been modest changes to the API for certain modules (e.g. adding additional arguments to ctor's), and so users should update their downstream macros accordingly.

Avoid Name Clashes and Add Functionality to Select Triggers in Jet QA

---

offline/QA/Jet/JetSeedCount.cc
offline/QA/Jet/JetSeedCount.h

This PR introduces a "pp mode" flag to the `JetSeedCount` QA module which, when set to true, turns off code that isn't relevant to pp collisions (e.g. trying to determine the centrality).
This is a bug fix: previously, in order for this module to be ran in a macro, one would need to ensure that the `CentralityInfo` was  on the node tree and filled. This is, naturally, not relevant for pp collisions and it would be wasteful to try to create an empty `CentralityInfo` node or empty QA histograms plotting various quantities vs. centrality.

Add "pp mode" Flag to Jet Seed Counter

---

offline/packages/tpc/LaserClusterizer.cc
offline/packages/tpc/LaserClusterizer.h

This lets the user change the default range of where the diffuse laser clusterizer will look for the laser peak, in time bins.  It defaults to 360, the previous value, but may now be changed by adding a  LaserClusterizer->set_max_time_samples(int val) call in your macro somewhere before InitRun() takes place.
This runs, but does not seem to completely solve the boundary problem yet, since something is still preventing any hits from registering after t=370 or so.  See attached.   …

added controls to set n time samples in the LaserClusterizer

---

offline/framework/fun4allraw/Fun4AllStreamingInputManager.cc
offline/framework/fun4allraw/SingleMvtxPoolInput.h

@cdean-github found some more sets that grow in size with time for certain runs. This adds some clearing functions to reset them after each time the qa uses them. Also changes the bco matching to within 3, which per @ycorrales is the matching range for the gtm and gl1 bcos for the mvtx. Strobe bco matching histograms to be added in another development

fix: clear sets in mvtx pooling

---

offline/QA/Tracking/Makefile.am
offline/QA/Tracking/MvtxClusterQA.cc
offline/QA/Tracking/MvtxClusterQA.h
offline/QA/Tracking/TpcSiliconQA.cc
offline/QA/Tracking/TpcSiliconQA.h

New TPC-Silicon QA module that shows the x, y, z, eta, and phi difference between TPC and silicon seeds for all tracks, and histograms for the crossing value for each track as well as a histogram that shows the fraction of tracks with both a TPC and Silicon seed
New MVTX TH2F shows the distribution of cluster size vs total number of clusters in the MVTX 
No QAHtml module made for these yet, but I will try to get that done as soon as possible …

New TPC-Silicon Tracking QA Module and New MVTX Histogram

---

offline/framework/fun4allraw/SingleInttPoolInput.cc

In discussion with @mpurschke and @hahahachiya , there are INTT pooling job where the job abruptly ends due to a mismatched run number. Martin traced this down and it appears that the end run event is filled and data after this is corrupted, due to some interplay between the INTT RCDAQ plugin and RCDAQ itself. Until further upstream changes in the firmware can be made to handle this, this PR puts a flag in that if the `ENDRUNEVENT` is found the INTT pooler exits gracefully. …

fix: add flag end run in INTT pooling

---

offline/QA/Mvtx/MvtxRawHitQA.cc

Fix NodeTree not found problem
If data has no MVTX detector information, MvtxRawHitContainer NodeTree may not be found which will cause event aborting problem. I remove ``return Fun4AllReturnCodes::ABORTEVENT;`` to let this event continue processing, but histogram will no save any information.

Fix NodeTree not found problem

---

offline/QA/Jet/ConstituentsinJets.cc
offline/QA/Jet/JetKinematicCheck.cc
offline/QA/Jet/JetSeedCount.cc
offline/QA/Jet/RhosinEvent.cc
offline/QA/Jet/StructureinJets.cc
offline/QA/Jet/TrksInJetQA.cc

This PR fills in the missing R = 0.5 histograms in the `JetKinematicCheck` module, as well as prevents code from adding histogram tags to their names if the tag is empty.
This PR fixes 2 issues:
1. The 1st is with the `JetKinematicModule`: while the R = 0.5 jets were added as input and the corresponding histograms were created, they weren't filled or registered with the histogram manager.
2. And the 2nd is with how the jet QA modules handle histogram tags: functionality to add tags to the end of all histograms created by a module was added in a previous PR, but all of the module will still attempt to add the "tag" even if it's empty. This results in a hanging "_" at the end of each …

Add Missing R = 0.5 Jet Kinematic Histograms (and make tag-handling better)

---

offline/QA/Intt/InttRawHitQA.cc

add checks for missing intt raw hit node

fix: add check for no hit map

---

offline/packages/jetbase/ClusterJetInput.cc
offline/packages/jetbase/Jet.h

Additional Jet::SRC constant for EMCal+HCal topo-clusters and corresponding modification in the ClusterJetInput module. Previously only the EMCal only and HCal only options were available as jet input.

Adding EMCal+HCal topoclusters as jet input

---

offline/packages/trackreco/PHActsTrackProjection.cc

- Calo cluster requirement for the track projection was removed. Only calo towers and geometry are required.
- Small fix in the TowerInfoContainer cast when getting it from the node

Removing calo cluster requirement

---

offline/packages/trackreco/PHActsTrkFitter.cc
offline/packages/trackreco/PHActsTrkFitter.h

Adds a flag to ignore the silicon clusters/seed in the track fit, for distortion development

feat: add ignore silicon flag to track fit

---

offline/framework/fun4allraw/MicromegasBcoMatchingInformation.cc
offline/framework/fun4allraw/MicromegasBcoMatchingInformation.h
offline/framework/fun4allraw/SingleMicromegasPoolInput.cc
offline/packages/micromegas/MicromegasClusterizer.cc
offline/packages/micromegas/MicromegasClusterizer.h
offline/packages/micromegas/MicromegasCombinedDataDecoder.cc

By default clock synchronization is now done via the fee clock reset event sent to the TPOT/TPC FEE at begin of run. 
However, this does not work when running in local mode. One has to keep relying on synchronizing from data. 
This PR attempts at improving the robustness of data synchronization. 
In addition: 
- added some statitics to micromegas clusterizer
- simplified dropping of size 1 clusters
- simplified QA histogram creation in MicromegasSingleInput
[comment]: <> ( In case this is a draft PR, e.g. for running checks using …

Micromegas decoding 6

---

offline/framework/fun4allraw/MicromegasBcoMatchingInformation.cc
offline/framework/fun4allraw/MicromegasBcoMatchingInformation.h
offline/framework/fun4allraw/SingleMicromegasPoolInput.cc
offline/packages/micromegas/MicromegasRawDataEvaluation.cc
offline/packages/micromegas/MicromegasRawDataTimingEvaluation.cc

More changes to BCO synchronization logic:
- always check for BX_COUNTER_SYNC_T events even if bco matching is already verified, because any such event will break previous matching.
-  with this change, forcing re-sync for too many dropped channels becomes unnecessary <- remove

Micromegas decoding 7

---

offline/framework/fun4allraw/Fun4AllStreamingInputManager.cc
offline/framework/fun4allraw/Fun4AllStreamingInputManager.h
offline/framework/fun4allraw/SingleInttPoolInput.cc
offline/framework/fun4allraw/SingleMvtxPoolInput.cc
offline/framework/fun4allraw/SingleMvtxPoolInput.h
offline/framework/fun4allraw/SingleStreamingInput.h
offline/framework/fun4allraw/SingleTpcPoolInput.h

This PR improves the packet QA to deal with missing prdfs in the silicon. It also improves the mvtx packet qa greatly by properly associating the LL1 to GL1 BCOs and also adding histograms for relating the strobe BCO to the GL1

feat: packet qa improvement

---

offline/framework/frog/CreateFileList.pl

The default runnumber was still 7 which doesn't exist anymore. With the split of systems along run numbers a default doesn't make sense anymore and is misleading. The run number is now a require argument, if it is not given a list of available runs is printed out. Jenkins doesn't check this [skip-ci]  …

remove default for run number, print run numbers if not given

---

calibrations/calorimeter/calo_emc_pi0_tbt/pi0EtaByEta.cc
calibrations/calorimeter/calo_emc_pi0_tbt/pi0EtaByEta.h

gives option to save the 24,576 tower inv mass histograms as single TH3F instead of individual 24576 TH1F's, and associated functions to switch between TH1F's and TH3F modes.  Using the TH3F's until right before fitting, speeds up merging by a large factor.  

added th3 option for merging efficiency

---

offline/framework/fun4allraw/Fun4AllStreamingInputManager.cc
offline/framework/fun4allraw/Fun4AllStreamingInputManager.h
offline/framework/fun4allraw/SingleMvtxPoolInput.cc
offline/framework/fun4allraw/SingleMvtxPoolInput.h

This reduces the memory growth of the mvtx pooler. There is still one set that needs to be improved upon but this at least gets us going, I think. Memory profile results before and after for 100 events

fix: memory usage

---

offline/QA/Tpc/TpcRawHitQA.cc
offline/QA/Tpc/TpcRawHitQA.h

Adding plots for sector/region separated hit time sample distribution and adc distribution, and xy position for all hits iterated over. Note this does slow down the QA processing a little bit (we have to calculate the median and rms of each waveform), so if needed I can add in a flag to not create these histograms by default.

Adding TPC OnlMon Plots to TpcRawHitQA Module 

---

offline/packages/TrackingDiagnostics/TrackResiduals.cc

Adding the TPOT tile id to residualtree so that tracks can be easily separated by which tile they hit.

Add TPOT tile id to residualtree

---

offline/framework/fun4allraw/SingleInttPoolInput.cc
offline/framework/fun4allraw/SingleMicromegasPoolInput.cc
offline/framework/fun4allraw/SingleMvtxPoolInput.cc
offline/framework/fun4allraw/SingleMvtxPoolInput.h
offline/framework/fun4allraw/SingleStreamingInput.h
offline/framework/fun4allraw/SingleTpcPoolInput.cc

This allows us to set the raw hit node names of the poolers from the macro level, for potential highly parallelized running. The unpackers actually already have this feature available, so the poolers were the only module missing it. The node names are defaulted to their current names, so this does not change any of the current default behavior.

feat: add settable raw hit node names

---

offline/packages/trackreco/PHSimpleVertexFinder.cc

The vertexer segfaults in the seed->vertex qa because some seeds are removed. This just adds a check to skip a track in the vertexing if it was removed in the seeding procedure.

fix: qa segfault

---

offline/QA/Jet/JetKinematicCheck.cc
offline/QA/Jet/JetKinematicCheck.h
offline/QA/Jet/JetSeedCount.cc

This PR addresses three minor issues with the Jet QA:
1. It enables the user to restrict the eta range of analyzed jets by the resolution parameter in `JetKinematicCheck`;
2. It fixes the verbosity of debugging messages in `JetSeedCount`; and
3. It removes stray instances of `ABORTEVENT` and `ABORTRUN` event codes.
This PR is a small bug fix and does not introduce breaking changes.

Fix eta acceptance in `JetKinematicCheck`, adjust verbosity in `JetSeedCount`, and fix jet QA return codes.

---

offline/QA/Tracking/TpcSiliconQA.cc
offline/QA/Tracking/TpcSiliconQA.h

Will now iterate over SiliconSeedMap and TpcSeedMap directly 
Histograms will check x, y, z, eta, and phi differences between all seeds, not just track matches

TpcSiliconQA Update to Remove TrackMap Usage

---

offline/packages/CaloReco/CaloWaveformFitting.cc
offline/packages/CaloReco/CaloWaveformFitting.h

The waveform fitting never closed the files with the templates and therefore had always 3 files in cvmfs open. This PR now closes the files after copying the TProfile into memory

close TFiles from cdb after reading histo

---

offline/QA/Tracking/TpcSiliconQA.cc
offline/QA/Tracking/TpcSiliconQA.h

Adding histograms with progressive geometric cuts that the user can specify to narrow down the selection of TPC and Silicon seeds that get matched (now that we iterate over all TPC and Silicon seeds instead of only pulling from those placed together in a track)

Adding Geometric Cut Histograms to TpcSilisonQA

---

offline/packages/TrackingDiagnostics/TrackResiduals.cc
offline/packages/TrackingDiagnostics/TrackResiduals.h
offline/packages/tpccalib/PHTpcResiduals.cc
offline/packages/tpccalib/PHTpcResiduals.h
offline/packages/tpccalib/TpcSpaceChargeReconstruction.cc
offline/packages/trackreco/PHGenFitTrkFitter.cc

This pull request fixes the use of extrapolated TrackState in the TPC for GitHub and PHTpcResiduals, so that they are properly dealt with in the TrackResiduals evaluation module. 
In particular it makes use of SvtxTrackState_v2, and properly assign cluster keys to track state (needed to form residuals later on).
It also adds module_edge correction to PHTpcResiduals. There are other places where the module_edge correction is missing. It will be part of a separate commit once this one is merged. …

Tpc residuals

---

offline/packages/TrackingDiagnostics/TrackResiduals.cc
offline/packages/TrackingDiagnostics/TrackResiduals.h

Adding the number of states to the residualtree for the KF case. Shows when the track seed contains clusters but the Acts fit did not use the measurement.

Add number of states for each subsystem to residualtree

---

offline/framework/fun4allraw/SingleInttPoolInput.cc
offline/framework/fun4allraw/SingleInttPoolInput.h

The aggressive skipping of events before filling the intt_pool had an unintended side effect. It now catches up quickly with the gl1 bco but we do have rcdaq events which contain only a packet fragment where hte decoder claims zero hits and no BCO. They still need to be fed into the intt_pool which recovers those data.  …

no skipping of zero hit events after initial syncing to gl1 bco

---

calibrations/intt/inttcalib/InttCalib.cc

The BCO related output was affected when I changed the hot-channel map logic and would put the peaks at 0. It correctly gets the peaks now.

(INTT) Bug fix in calibrations module

---

calibrations/intt/inttcalib/InttCalib.cc

[comment]: <> 
BCO convention changed from
int bco_diff = ((intt_raw_hit->get_bco() & 0x7fU) - intt_raw_hit->get_FPHX_BCO() + 128) % 128;
to
 int bco_diff = (intt_raw_hit->get_FPHX_BCO() -  (intt_raw_hit->get_bco() & 0x7fU) + 128) % 128;
 

BCO convention changed

---

offline/framework/fun4allraw/Fun4AllStreamingInputManager.cc
offline/framework/fun4allraw/Fun4AllStreamingInputManager.h
offline/framework/fun4allraw/SingleStreamingInput.h
offline/framework/fun4allraw/SingleTpcPoolInput.cc

This PR adds a few changes to be able to process the packet QA on a single server/felix/ebdc basis.
It also fixes a bug in the way that the containers were cleared. Previously, the container bcos were cleared based on the first hit bco entry, similarly to all other containers in the input manager. While doing the single server/felix/ebdc development, there were cases that became more apparent where bcos were being cleared that should not have been. This is because there are instances where the lowest hit BCO is not actually the lowest valid BCO that was tagged in the container, and so BCOs that may have been associated to future GL1 BCOs were being inadvertently cleared. This fixes that problem by clearing out the BCOs from the containers that are less than `GL1BCO - 40000`, which is …

fix: Fixes to packet QA

---

offline/packages/trackreco/PHActsTrkFitter.cc
offline/packages/trackreco/PHSimpleVertexFinder.cc
offline/packages/trackreco/PHTrackCleaner.cc
offline/packages/trackreco/PHTrackCleaner.h

In pp mode, do not drop TPC tracks that are not matched to the silicon. TPC-only tracks are assigned to crossing zero, so that their nominal z position is used in tracking. They are excluded from primary vertex finding.
TPC-only tracks can be identified by checking to see if the track has a silicon seed (nmaps > 0). …

Do not drop TPC-only tracks in pp mode

---

offline/framework/fun4allraw/SingleGl1TriggerInput.cc

We had at least one run where the last GL1 event didn't have a gl1 packet and then the production crashed

fix crash for null packet from empty gl1 event

---

offline/framework/fun4allraw/SingleGl1PoolInput.cc

The gl1 streaming input manager crashes if packet 14001 is missing from the gl1 event. That shouldn't happen but I have seen this once in the triggered systems (which then means the streaming combiner will die as well). If a gl1 event without packet 14001 is encountered, this event will be skipped (and a message with the event->identify() will be printed out).
[comment]: <> ( In case this is a draft PR, e.g. for running checks using Jenkins, please make the pull request as a …

protect against missing gl1 packet

---

offline/framework/phool/onnxlib.cc
offline/framework/phool/onnxlib.h
offline/packages/CaloReco/Makefile.am
offline/packages/CaloReco/RawClusterCNNClassifier.cc
offline/packages/CaloReco/RawClusterCNNClassifier.h

I trained a toy CNN to classify EMCal photon clusters from non-photon showers.
The training sample is derived from Pythia 1M photon-jet sample and 10M Detroit jet sample. 
Cluster truth matching is done with the [g4eval](https://github.com/sPHENIX-Collaboration/coresoftware/tree/master/simulation/g4simulation/g4eval) module For clusters with ET>7GeV, I took the 5x5 tower_calib energy around the maximum energy tower. For both photon and non-photon sample I require the primary particle that matched to the cluster to contribute >99% energy in the 5x5 tower block. For truth photon sample, e+ e- converted photons are …

CNN photon classifier

---

offline/packages/CaloReco/CaloTowerStatus.cc
offline/packages/CaloReco/CaloWaveformFitting.cc

Change in waveform fitting to set ZS waveforms with post sample = 0 to have a high chi2 (1E6) and change ZS waveform time from -1 to -20 to not interact with the normal timing fit range. Change in tower status to not set ZS waveforms to isBadTime.
This PR changes the default time value for the ZS waveforms to be -20 instead of -1. This makes sure that the default ZS timing value is outside of the expected fitted time value range. A small change to the tower status is needed to not set these ZS channels to isBadTime with the new default value. 
This PR also checks to see if a ZS waveform has a non-zero ADC pre sample and …

Change to ZS waveform default time and ZS towers with post sample = 0 to have bad chi2

---

offline/packages/trackbase_historic/SvtxTrackState.h
offline/packages/trackbase_historic/configure.ac

Small fix to the SvtxTrackState::get_cluskey() to return UINT64_MAX instead of UINT32_MAX. Returning UINT32_MAX while the cluster key is a uint64_t was making the track states in the origin and calorimeters to be misidentified as MVTX states.

Changing get_cluskey() to return max 64

---

offline/packages/KFParticle_sPHENIX/KFParticle_DST.cc
offline/packages/KFParticle_sPHENIX/KFParticle_DST.h
offline/packages/KFParticle_sPHENIX/KFParticle_eventReconstruction.cc
offline/packages/KFParticle_sPHENIX/KFParticle_sPHENIX.h

Two changes in this PR
1. In KFParticle_DST, we search for SvtxTrack by using track id which is the index in that track map. We should search in the input track map, rather than "SvtxTrackMap", because we can use track map different from SvtxTrackMap from default tracking software.
2. lepton PDG ID convention is different from charged hadrons. For example, pi+ --> 211, pi- --> -211, e+ --> -11, e- --> 11. I add a if statement to time an extra minus sign for lepton including e+/-, mu+/-, tau+/-. …

change trackmap name & lepton PDGID

---

offline/packages/TrackingDiagnostics/TrackResiduals.cc
offline/packages/TrackingDiagnostics/TrackResiduals.h
offline/packages/trackreco/PHCosmicSeeder.cc
offline/packages/trackreco/PHCosmicSeeder.h

[comment]: <> (PR to enable MVTX only running with cosmic seeder, and allow output from the TrackResiduals)
[comment]: <> ( Enables setters for various functions in the cosmic seeder that allow one to set the the seeder to work for the MVTX only cosmic seeding. These are mostly in the cosmicSeeder package, with a few small additions to the TrackResiduals module to control file size (if desired) by reducing events with too few clusters and disabling the event tree. By default, the code should remain the same unless the new options are enabled in a macro. )
[comment]: <> ( In case this is a draft PR, e.g. for running …

Harmonize mvtx cosmics

---

offline/framework/fun4allraw/Fun4AllStreamingInputManager.cc
offline/framework/fun4allraw/SingleInttPoolInput.cc
offline/framework/fun4allraw/SingleTpcPoolInput.cc
offline/framework/fun4allraw/SingleTpcPoolInput.h

First attempt at skipping tpc bcos that are way behind the gl1. Needs work/additional testing @pinkenburg 

feat: skip tpc bcos way behind the gl1

---

offline/packages/intt/InttOdbcQuery.cc
offline/packages/intt/InttOdbcQuery.h
offline/packages/intt/Makefile.am

Implemented class for querying daq database to determine whether the INTT was in streaming/triggered for a given run

(INTT) Class for getting streaming/triggered through odbc query

---

offline/framework/ffarawmodules/InttBcoDump.cc
offline/framework/ffarawmodules/InttBcoDump.h
offline/framework/ffarawmodules/Makefile.am

Fast INTT bco dump module that doesn't use the event combiner and allows you to plot things like bco diff and number of fees vs bco

feat: intt bco dump

---

offline/QA/Tracking/TpcSeedsQA.cc
offline/QA/Tracking/TpcSeedsQA.h

According to feedback from tracking software meeting, I make some updates on TpcSeedsQA
1.  Separate DCA_xy w.r.t. origin plot into north and south track (dca_z > 0 or dca_z < 0)
2. Enlarge DCA_xy w.r.t. origin 2D plot y-aixs region [-3,3] -> [10,-10]
3. For number of tpc clusters per track plot, require track within eta acceptance which considers z-vertex position
Example plots can be found in [QAhtmltest](https://sphenix-intra.sdcc.bnl.gov/WWW/subsystem/QAHtmlTest/mon.cgi?runnumber=51619&runtype=physics)
[comment]: <> ( In case this …

TpcSeedsQA update

---

offline/packages/KFParticle_sPHENIX/KFParticle_Tools.cc
offline/packages/KFParticle_sPHENIX/KFParticle_Tools.h
offline/packages/KFParticle_sPHENIX/KFParticle_eventReconstruction.cc
offline/packages/KFParticle_sPHENIX/KFParticle_eventReconstruction.h
offline/packages/KFParticle_sPHENIX/KFParticle_nTuple.cc
offline/packages/KFParticle_sPHENIX/KFParticle_nTuple.h
offline/packages/KFParticle_sPHENIX/KFParticle_sPHENIX.cc
offline/packages/KFParticle_sPHENIX/KFParticle_sPHENIX.h

…cut options
I added the ability to run reconstruction using 2D DCAs instead of 3D DCAs (this is a flag)
I also added a new secondary vertex radial cut option (useful for K-shorts/lambdas/conversions) for decays that have no associated PV
I also removed macro function calls that required the user to set them to true or false. All variables default to false so the functions now set them to true without specifying. Note, this will break old macros which have a true/false in the function call.
[comment]: <> ( In case this is a draft PR, …

KFParticle updates

---

offline/framework/fun4allraw/SingleTpcPoolInput.cc

This should address @pinkenburg concern, this change now only affects the qa histogram filling with the endat instead of the possibility of actually starting the whole show with the endat bco

fix: only fill offline qa with endat

---

offline/QA/Tracking/MicromegasClusterQA.cc
offline/QA/Tracking/MicromegasClusterQA.h
offline/framework/fun4allraw/MicromegasBcoMatchingInformation.cc
offline/framework/fun4allraw/SingleMicromegasPoolInput.cc
offline/framework/fun4allraw/SingleMicromegasPoolInput.h
offline/packages/micromegas/MicromegasDefs.h

This PR modifies the Micromegas cluster QA module to add histograms needed for a crude, standalone detection efficiency estimate, on a per run basis. More details in a coming tracking meeting.

Tpot standalone efficiency qa

---

offline/QA/Tpc/TpcRawHitQA.cc
offline/QA/Tpc/TpcRawHitQA.h
offline/QA/Tracking/TpcSiliconQA.cc
offline/QA/Tracking/TpcSiliconQA.h

Adding new North/South separated plots to TpcSiliconQA module
Also separating the laser pulse hits from other hits in the TpcRawHitQA module, as well as improving that module to more accurately determine the pedestal and std value for a given channel (was calculating on a channel-by-channel basis before incorrectly because we no longer have a resample)
[comment]: <> ( In case this is a draft PR, e.g. for running checks using Jenkins, please make the pull request as a draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/ …

TPC Offline QA Improvements

---

offline/framework/fun4allraw/SingleMicromegasPoolInput.cc
offline/framework/fun4allraw/SingleMicromegasPoolInput.h

Added offline QA histograms to keep track of how many waveforms are dropped per packet because of not being able to associate their BCO to any GL1 BCO.
Also changed TH1I into TH1F, they are easier to manipulate and normalize.

Added offline QA histograms to keep track of how dropped waveforms

---

offline/framework/ffarawmodules/InttBcoDump.cc

Fixes memory growth of this module

fix: intt bco dump memory  growth

---

offline/packages/tpc/TpcDistortionCorrection.cc
offline/packages/tpc/TpcDistortionCorrectionContainer.h
offline/packages/tpc/TpcLoadDistortionCorrection.cc
offline/packages/tpc/TpcLoadDistortionCorrection.h

This allows you to scale a correction by a scalefactor set during the initial loading of the file.  A separate pull req to the macros directory will be needed to access this.  By default, for all corrections, the scale factor is set to one, and the 'using scalefactor' flag is set to false, so the actual stored values in the histograms are used.
tbd.

Distortion scalefactors

---

offline/packages/CaloBase/RawCluster.h
offline/packages/CaloBase/RawClusterv1.cc
offline/packages/CaloBase/RawClusterv1.h

This PR introduce a method to RawClusterv1 that calculate the shower shape variables which are used to calculate the cluster chi2 using the saved tower map within the object, without changing the memory layout of the RawCluster object(so no issue with DST read back). 
The method returns a vector of float contains:
```e1t, e2t, e3t, e4t, center_of_gravity_eta, center_of_gravity_phi, variance_eta, variance_phi, e1, e2, e3, e4, totalE```
This will give us an easy access to the shower shape vars for study like tunning the cluster prob calculation :)
[comment]: <> ( What does this PR do? Linking to talk in software meeting …

RawCluster Shower Shape getter

---

offline/packages/trackreco/ALICEKF.cc
offline/packages/trackreco/ALICEKF.h
offline/packages/trackreco/PHSimpleKFProp.cc
offline/packages/trackreco/PHSimpleKFProp.h

Changes to the propagator recently introduced some cuts on clusters inside the physical volume of the TPC. This means we don't reconstruct any seeds outside of the physical volume which is where the seeds exist in streaming data before they are matched to the silicon. This PR fixes that. Note that most of the line changes in this PR are from the clang-format commit to make the code more readable - the actual code changes are very minimal. …

fix: reconstruct tpc seeds outside physical z volume

---

offline/packages/TrackingDiagnostics/TrackResiduals.cc
offline/packages/TrackingDiagnostics/TrackResiduals.h

Laser event rejection flag is added. By default, flag is set to true, so it will require node tree existing and reject laser event. For specific laser study, need to set flag to false.

add laser rejection flag

---

offline/packages/trackreco/PHSiliconTpcTrackMatching.cc

Fixes the filling of the silicon-tpc track matching tuple filling

fix: matching tuple filling

---

offline/framework/fun4allraw/Fun4AllStreamingInputManager.cc

Switches the bco check range to the 120 bco count that the INTT strobes 

fix: streaming bco range check

---

offline/packages/TrackingDiagnostics/TrackResiduals.cc
offline/packages/TrackingDiagnostics/TrackResiduals.h
offline/packages/tpc/LaserEventIdentifier.cc
offline/packages/tpc/LaserEventIdentifier.h

This moves the reject event into the laser identifier itself, so that we avoid reconstructing full events with the laser pulse in it if chosen to do so.

fix: make laser event identifier skip rest of event

---

offline/database/rundb/Makefile.am
offline/database/rundb/testODBC.cc
offline/framework/fun4all/Fun4AllReturnCodes.h
offline/framework/fun4all/Fun4AllServer.cc
offline/packages/PHGenFitPkg/Example/minimumTestPHGenFit.cc
offline/packages/PHGenFitPkg/Example/testPHGenFit.cc
offline/packages/PHGenFitPkg/GenFitExp/Makefile.am
offline/packages/PHGenFitPkg/GenFitExp/configure.ac
offline/packages/PHGenFitPkg/PHGenFit/Fitter.cc
offline/packages/PHGenFitPkg/PHGenFit/Fitter.h
offline/packages/PHGenFitPkg/PHGenFit/Makefile.am
offline/packages/PHGenFitPkg/PHGenFit/Measurement.h
offline/packages/PHGenFitPkg/PHGenFit/PlanarMeasurement.cc
offline/packages/PHGenFitPkg/PHGenFit/PlanarMeasurement.h
offline/packages/PHGenFitPkg/PHGenFit/SpacepointMeasurement.cc
offline/packages/PHGenFitPkg/PHGenFit/SpacepointMeasurement.h
offline/packages/PHGenFitPkg/PHGenFit/Tools.cc
offline/packages/PHGenFitPkg/PHGenFit/Tools.h
offline/packages/PHGenFitPkg/PHGenFit/Track.cc
offline/packages/PHGenFitPkg/PHGenFit/Track.h

We will need a new return code to be able to abort the processing gracefully (close and save the output files). The current ABORTRUN is a hard exit which does not close the output files properly. This is meant to be used in a fatal condition which invalidates a run and better a corrupt file than a "good" file with wrong data
clang-tidy fixed for genfit implementation (which is likely not being used anymore anyway) to reduce the jenkins noise …

Ffa return abortprocessing

---

offline/packages/trackreco/PHActsTrkFitter.cc
offline/packages/trackreco/PHActsTrkFitter.h
offline/packages/trackreco/PHSiliconTpcTrackMatching.cc

Modifies the handling of matched silicon-TPC tracks in PHActsTrkFitter. Turns off by default the attempts to do geometric matching when no INTT crossing is available. Now, only matched tracks with INTT crossings are considered.

Changes to handling of silicon-TPC matching for pp

---

offline/framework/fun4allraw/SingleMicromegasPoolInput.cc
offline/framework/fun4allraw/SingleMicromegasPoolInput.h

@pinkenburg When processing the extended readout TPOT data it was found that a significant fraction (20%) of the FEE data is dropped because of being received _after_ a given BCO has already been processed by Fun4All. This is because the Fun4All pooling strategy in this configuration does not work for TPOT, in turn because FEE can send data for a given BCO in a locally unordered fashion.
This is addressed by also requiring that a large enough number of BCO's in in the pool stack before alowing to process a given BCO. 
For now the default pool size is set to 1, correspondign to no change in the current strategy. 
This will be adjusted to a working value on the macro side. 
[comment]: <> ( What types of changes does your code …

Added minumum pool size in terms of number of stored BCO

---

offline/packages/mbd/MbdCalib.cc
offline/packages/mbd/MbdCalib.h
offline/packages/mbd/MbdDefs.h
offline/packages/mbd/MbdEvent.cc

[comment]: Added more fields in the t0corr.  This is the calibration that corrects the time-zero peak to be centered at 0 ns.
[comment]: I added the fit values from the calibration, which are useful for debugging.

modified t0corr calibrations format

---

offline/packages/TrackingDiagnostics/TrackSeedTrackMapConverter.cc

Assign the seed->track crossing to be 0 if it is not determined, similar to the track fitter

fix: assign seed crossing to 0

---

offline/packages/tpc/TpcDistortionCorrection.cc

previously, the corrections are instantiated as dz=z, dr=r, dphi=phi in order to let 'auto' give the new objects the same type as the original.  I added lines to set these to zero, so that when the histogram interpolation fails, it returns zero rather than corrections exactly equal to the original position.
fixes a bug in how distortions are calculated for coordinates that are outside the TPC volume (though we should talk about why we pass real z coordinates as the argument in this case...)

Fix distortion corrections for regions outside of the real TPC volume

---

offline/packages/trackbase/ActsGsfTrackFittingAlgorithm.h
offline/packages/trackbase/ActsTrackFittingAlgorithm.h

If Acts is compiled locally, other packages fail to compile because some acts includes create warnings. This PR re-introduces pragmas to ignore the compiler warnings for those includes

fix compilation failure for local acts build

---

offline/packages/mbd/MbdEvent.cc

[comment]: When writing out the calibration files during calpass 1, we append the run number to the CBD files to make them unique before uploading into CDB.
[comment]: Will work without macro changes.

added runnumber to CDB files after calibration pass0

---

offline/packages/trackreco/PHMicromegasTpcTrackMatching.cc

New TPC-TPOT matching algorithm makes sure that at most one TPOT cluster per layer is matched to a given TPC seed. 
The cluster closest to the TPC seed extrapolated to a given TPOT layer, in the direction perpendicular to the strips, is kept, provided that the distance between the two is smaller than specified cut.

Fix tpc micromegas matching

---

offline/framework/fun4all/Fun4AllBase.h
offline/framework/fun4all/Fun4AllServer.cc
offline/framework/fun4allraw/Fun4AllEventOutputManager.cc
offline/framework/fun4allraw/Fun4AllEventOutputManager.h
offline/packages/trackreco/MakeActsGeometry.cc

This PR adds a downscale to the verbosity. It's first implementation is the event wise printout (it's just a eventcount%scaledown) but it can be used in all modules which inherit from Fun4AllBase

add downscale for event printouts

---

offline/packages/trackreco/PHTrackCleaner.cc

Fixes the identification of TPC-only tracks in pp mode following the change where unmatched TPC tracks are arbitrarily assigned to crossing zero.

Fix track cleaner handling of TPC only tracks in pp mode.

---

offline/packages/trackreco/PHMicromegasTpcTrackMatching.cc

Due to a recentrly introduced flaw in the TPC to TPOT matching algorithm, in some rare cases a cluster of key == 0 could be added to a track, resulting in possible crashes downstream. 
Should now be fixed. 

Fix possibly invalid cluster added to track in TPC-TPOT matching code

---

offline/framework/fun4allraw/Fun4AllStreamingInputManager.cc
offline/framework/fun4allraw/Fun4AllStreamingInputManager.h
offline/packages/mvtx/MvtxCombinedRawDataDecoder.cc
offline/packages/mvtx/MvtxCombinedRawDataDecoder.h

These changes allow the MVTX to run in triggered mode. In this mode, the strobe arrives after the GL1 and is offset by two BCOs.
Changes needed in an analysis macro are:
```c++
bool mvtxTriggered = true;
Fun4AllStreamingInputManager *in = new Fun4AllStreamingInputManager("Comb");
in->runMvtxTriggered(mvtxTriggered);
auto mvtxunpacker = new MvtxCombinedRawDataDecoder;
mvtxunpacker->Verbosity(0);
mvtxunpacker->runMvtxTriggered(mvtxTriggered);
```
You can set the BCO range to 2 with
```c++
for (auto& infile : infiles)
{
auto* sngl= new SingleMvtxPoolInput("MVTX_FLX" + to_string(i));
int bcoRange = mvtxTriggered ? 2 : 10; …
```

CD: Added code to run MVTX in triggered mode

---

offline/packages/trackbase/Makefile.am
offline/packages/trackbase/alignmentTransformationContainer.h
offline/packages/trackbase/alignmentTransformationContainerLinkDef.h
offline/packages/trackbase_historic/Makefile.am

This PR splits libtrack_io.so and libtrackbase_historic_io into two libraries (libxxx_io.so and libxxx.so) to separate the io classes from reco classes so we don't load the PHENIX code universe just to read the DST content. This is just another step in this process - tackbase_historic contains i/o classes which call reco code internally which just breaks this concept …

Disentangle libs

---

offline/packages/epd/EpdGeom.h
offline/packages/epd/EpdGeomV1.cc
offline/packages/epd/EpdGeomV1.h
offline/packages/epd/EpdGeomV2.cc
offline/packages/epd/EpdGeomV2.h
offline/packages/epd/EpdGeomV2LinkDef.h
offline/packages/epd/EpdReco.cc
offline/packages/epd/EpdReco.h
offline/packages/epd/Makefile.am

I believe
```cpp
float EpdReco::GetTilePhi(int thisphi) {
static const float tilephi[24] = {
0.13089969, 0.39269908, 0.65449847, 0.91629786, 1.17809725, 1.43989663,
1.70169602, 1.96349541, 2.2252948,  2.48709418, 2.74889357, 3.01069296,
3.27249235, 3.53429174, 3.79609112, 4.05789051, 4.3196899,  4.58148929,
4.84328867, 5.10508806, 5.36688745, 5.62868684, 5.89048623, 6.15228561};
return tilephi[thisphi];
}
```
is (almost)equivalent to:
```cpp
float EpdReco::GetTilePhi(int thisphi) {
return ((2 * thisphi + 1) * M_PI) / 24;
}
```
The later also doesn't segfault if you give some index out of range...
I think this could be a …

EPD reco update: replace the hardcoded equal distance phi value arrays with human readable calculation

---

offline/QA/Jet/JetSeedCount.cc
offline/QA/Jet/JetSeedCount.h

This PR resolves the excessive memory usage of the `jetqa/JetSeedCount` module which was causing AuAu Jet QA production jobs to fail.
This resolves a serious bug: as written, during `process_event()` the module would fill several `std::vector`s of the values to be filled into histograms during `End()`. For sparse events (such as in pp) where the numbers of seed jets per event is small, this wasn't an issue. However, the number of seed jets per event increases dramatically in AuAu.
This PR rewrites the module so that the histograms are filled in place rather than during `End()`.

Fix memory usage in JetSeedCount

---

offline/packages/uspin/SpinDBContent.cc
offline/packages/uspin/SpinDBContent.h
offline/packages/uspin/SpinDBInput.cc
offline/packages/uspin/SpinDBOutput.cc

[comment]: Added crossing angle statistics to uspin package.
[comment]: Added crossing angle statistics for each run of pp24. Mean, standard deviation, minimum and maximum relative crossing angle over the run is now stored in databased and can be accessed by uspin package.
[comment]: Adds crossing angle statistics to uspin package

Spindb xingangle

---

offline/packages/CaloReco/CaloTowerCalib.cc
offline/packages/CaloReco/CaloTowerCalib.h

Adds method to CaloTowerCalib to get ZS cross calibration factors from cdb and apply them to towers with flag is_ZS() during the calibration step from raw towers to calib towers. These cross calibration factors will need to be applied via run by run cdb trees created from the CaloFittingQA module. 
Also adds option to not apply these factors directly from CaloTowerCalib call.  …

Add cross calibration for ZS towers in CaloTowerCalib

---

offline/packages/trackreco/PHTrackCleaner.cc

Noticed while testing some unhidden print statement

fix: hide verbosity

---

offline/QA/Tracking/TpcSeedsQA.cc
offline/QA/Tracking/TpcSeedsQA.h

Add dE/dx vs Z QA plots to TpcSeedsQA module

TpcSeedsQA add dEdx vs Z plots

---

offline/packages/CaloBase/TowerInfov4.h
offline/packages/CaloReco/CaloTowerBuilder.cc
offline/packages/CaloReco/CaloTowerBuilder.h
offline/packages/CaloReco/CaloWaveformFitting.cc

Currently if we are doing the uniform software ZS, the suppression is done in *CaloWaveformFitting* and after suppression the time of the tower will be set to -20 without setting the ZS status. However, the calotower status will check the timing for non-ZS tower.
This PR change the calotowerbuilder and waveformfitting, so the hardware and software ZS towers are set with time and chi2 equals to qnan. Also let calotowerbuilder to check for if the timing and chi2 is qnan(for SZS) to set the ZS status for software zero suppressed towers.
This PR also add case handling for Towerinfov4 where the chi2 is set into log scale, for …

set ZS status for uniform software ZS tower, no magic number for timing and chi2

---

offline/framework/fun4all/InputFileHandler.h
offline/framework/fun4allraw/Makefile.am
offline/framework/fun4allraw/SingleMvtxPoolInput.cc
offline/framework/fun4allraw/mvtx_decoder/mvtx_utils.cc
offline/framework/fun4allraw/mvtx_decoder/mvtx_utils.h
offline/packages/mvtx/Makefile.am
offline/packages/mvtx/MvtxCombinedRawDataDecoder.cc
offline/packages/mvtx/MvtxCombinedRawDataDecoder.h

This PR generalizes the daq db strobe lookup to a helper class in the mvtx decoder such that both the SinglePoolInput and unpacker can call it. This way the strobe width can be accessed from the daqdb (as is already done in the unpacker) in the pooling, and the bco ranges can be set accordingly. This should completely automate the production of the MVTX data in any mode that currently exists - 89 or 10 mus streaming strobe, or in triggered mode. …

feat: automate mvtx pooling bco range based on strobe length

---

simulation/g4simulation/g4tpc/PHG4TpcDirectLaser.cc

**Files Affected:**
- simulation/g4simulation/g4tpc/PHG4TpcDirectLaser.cc
**Changes:**
- L419, 425 - adjusting the sign of the angle so that it rotates the laser locations to proper angles
**TODO:**
- check with Ross that SS is right
- rebuild macros and confirm that its right

Changing location of line lasers to match reality

---

offline/packages/KFParticle_sPHENIX/KFParticle_truthAndDetTools.cc

There are some ghost tracks (I assume they're ghosts) that have no matching truth particles in the truth/reco map. When you try to associate them you access an array of size zero then KFParticle crashes

CD: KFP truth matching bug patch

---

offline/QA/Global/GlobalQA.cc

[comment]: <> (There was an extra space in the h_GlobalQA_mbd_charge_sum histogram string, which caused the histogram not to be found when testing the QAhtml.This issue has now been fixed in this PR  )

Updating the MBD histogram.

---

offline/packages/TrackerMillepedeAlignment/HelicalFitter.cc
offline/packages/trackbase/TrackFitUtils.cc

The direction of the tangent line was arbitrary. This uses the cluster phi to get the direction right.

Fix tangent direction in get_helix_tangent

---

offline/framework/fun4allraw/SingleGl1PoolInput.cc
offline/framework/fun4allraw/SingleGl1PoolInput.h

This cleans up the GL1 pool vectors/maps better than before, and appears to lead to more stable CPU processing time as reported in today's tracking meeting.
https://indico.bnl.gov/event/25251/
Marking draft as I don't totally understand *why* this makes the speed more stable...
@hupereir 

fix: clean up gl1 pool vectors

---

offline/packages/TrackingDiagnostics/TrackSeedTrackMapConverter.cc
offline/packages/trackbase/TrackFitUtils.cc
offline/packages/trackbase/TrackFitUtils.h

Fixes several issues with TrackSeedTrackMapConverter:
- SvtxTrackState objects are now inserted into the output SvtxTrack for all surfaces on which the track has an associated cluster.
- Silicon seeds in particular will now no longer be assigned a crossing of 0 when their associated seed crossing is SHRT_MAX.
- The residuals (for chi2/ndf calculation) now use the intersection between the fit helix and the surface, rather than the PCA of the helix to the cluster.
- The cluster errors (for chi2/ndf calculation) are now sourced from a …

TrackSeedTrackMapConverter fixes

---

offline/packages/QAUtils/QAHistManagerDef.cc
offline/packages/QAUtils/QAHistManagerDef.h

This adds a histogram containing the build and dbtag information to every qa file produced. We can add more information if it is useful

feat: build/dbtag QA histogram

---

offline/QA/Calorimeters/CaloFittingQA.cc
offline/QA/Calorimeters/CaloFittingQA.h

This PR adds separate setter functions for the EMCal and HCals for the ADC thresholds used to calculate ZS cross calibrations factors. This is necessary to account for different levels of noise between calorimeters and determining any other kind of energy dependence in the cross calibration factors. 

Add setter functions for emcal/hcal thresholds for ZS cross calib factors and histogram for packet event number check in CaloFittingQA module

---

offline/packages/trackreco/PHSimpleKFProp.cc
offline/packages/trackreco/PHSimpleKFProp.h

[comment]: <I implemented the set_max_seeds function that aborts events with more than 100k TPC seeds.> (Please tell us something about this pull request)
[comment]: <If you call the function cprop->set_max_seeds(true); in the Fun4All_FieldOnAllTrackers.C macro, it aborts events that have more than 100k TPC seeds coming from the seeder process. Discussion in: https://indico.bnl.gov/event/25255/> ( What does this PR do? Linking to talk in software meeting encouraged )

Added Function to skip events with > 100k TPCseeds

---

offline/framework/fun4allraw/Fun4AllStreamingInputManager.cc
offline/framework/fun4allraw/SingleInttPoolInput.cc
offline/framework/fun4allraw/SingleMvtxPoolInput.cc
offline/framework/fun4allraw/SingleStreamingInput.h
offline/framework/fun4allraw/SingleTpcPoolInput.cc

This PR fixes the intt and tpc slowdown in the poolers. There was a map that was being cleared in the wrong place, so it was growing faster than it was being cleared. It also changes the creation of the hits to use smart pointers instead of raw pointers, which are in general easier/safer. The linear slowdown in the mvtx still remains a mystery but it is not as egregious as these cases.

fix: intt and tpc slowdown

---

offline/framework/ffarawobjects/Makefile.am
offline/framework/ffarawobjects/TpcRawHitContainerv3.cc
offline/framework/ffarawobjects/TpcRawHitContainerv3.h
offline/framework/ffarawobjects/TpcRawHitContainerv3LinkDef.h
offline/framework/ffarawobjects/TpcRawHitv3.cc
offline/framework/ffarawobjects/TpcRawHitv3.h
offline/framework/ffarawobjects/TpcRawHitv3LinkDef.h
offline/framework/fun4allraw/SingleTpcTimeFrameInput.cc
offline/framework/fun4allraw/TpcTimeFrameBuilder.cc
offline/framework/fun4allraw/TpcTimeFrameBuilder.h

As mentioned in #3238, the v2 TPC raw hit filling was dominating the CPU usage. It copies ADC value around a few times, and uses map indexing 
This PR introduce v3 TPC Rawhit, which uses move constructor to avoid ADC data copying after decoding stage. It also maintain the SAMPA sparse encoding and uses `std::vector` instead of `map`. This is introduced in parallel to the current processing chain.
This improve DST hit processing by about two orders of magnitude, from 4x decoding time to negligible (3% of decoding time).  
New callgrind …

Step 2: fast storage for TPC time frame building and fast decoding #3238

---

offline/packages/jetbase/TowerJetInput.cc

There was a small bug where the IHCal tower's Z and r are used for calculating the vertex corrected eta phi position for retowered EMCal, this PR fixed that in the towerinput file. 
I think an alternative approach is to create a geom node for retowered CEMC in the retower module, which could make our code loop prettier, but the currently implemented fix is the most simple fix.

fix vertex correction for retowered CEMC case

---

offline/packages/jetbase/Jet.h
simulation/g4simulation/g4jets/TruthJetInput.cc

This PR adds charged particles as a potential jet source.
This PR adds `CHARGED_PARTICLE` to the list of possible jet sources, and updates `TruthJetInput` to filter out neutral `PHG4Particle`s if this input is specified. This is the 1st step towards centralizing track jet reconstruction in the same way that tower jet reconstruction is, and in turn will allow for running Jet QA on reconstructed jets.
Required for [macros#992](https://github.com/sPHENIX-Collaboration/macros/pull/992).

Add charged particles as a jet source

---

offline/framework/fun4allraw/SingleMvtxPoolInput.cc
offline/framework/fun4allraw/SingleMvtxPoolInput.h
offline/packages/mvtx/MvtxCombinedRawDataDecoder.cc
offline/packages/mvtx/MvtxCombinedRawDataDecoder.h

This PR added flags to force the MVTX strobe width setting in the (SingleMvtxPoolInput) and the unpacking modules (MvtxCombinedRawDataDecoder). We found that for some unknown reason, the information on the DB is not accurate and it mismatches with the real readout mode observed in the raw data.
However, since in most of the cases, the information read from the DB is correct, the automatic read from the DB was left as default. 
[comment]: <> ( In case this is a draft PR, …

ycm - add flag to manually force strobewidth settings

---

offline/QA/Tpc/TpcRawHitQA.cc
offline/QA/Tpc/TpcRawHitQA.h
offline/framework/ffarawobjects/TpcRawHit.h
offline/framework/ffarawobjects/TpcRawHitv1.h
offline/framework/ffarawobjects/TpcRawHitv2.h
offline/framework/ffarawobjects/TpcRawHitv3.h
offline/packages/tpc/TpcCombinedRawDataUnpacker.cc

Downstream plumbing to #3242 : use fast iterator for TPC hit access. This applies to **both** new and older version of `TpcRawHit`. Besides allowing unpacker & TPC QA to use `TpcRawHitv3`, we should see an immediate speed up of the unpacking of current DSTs of `TpcRawHitv2`
Thanks to help from Joe, who tested current RawHit DST readback. Furthermore, let's watch out for other unintended consequences. …

Downstream plumbing to #3242 : use fast iterator for TPC ADC access

---

offline/QA/Calorimeters/CaloFittingQA.cc
offline/QA/Calorimeters/CaloFittingQA.h

This PR moves the call to the CDB for the emcal adc skip mask to the init function from the process event function so that the CDB call happens only once. The PR also adds new QA histograms to monitor the calorimeter single sample pedestal. 

Move cdb call to initrun function of CaloFittingQA. Add QA histograms for calorimeter single sample pedestal.

---

offline/packages/tpc/TpcGlobalPositionWrapper.cc
offline/packages/tpc/TpcGlobalPositionWrapper.h

By default, this removes anoying per event output message about which distortion correction maps are found on the node tree. 

added verbosity flag.

---

offline/QA/Tpc/TpcRawHitQA.cc
offline/framework/fun4allraw/SingleTpcTimeFrameInput.cc
offline/framework/fun4allraw/SingleTpcTimeFrameInput.h
offline/framework/fun4allraw/TpcTimeFrameBuilder.cc
offline/framework/fun4allraw/TpcTimeFrameBuilder.h

* Improve QA of dropped TPC hits
* Add QA of time consumption of each step of TPC input
* Allow for more than Raw Hit on `DST/TPC` node
Current `callgrind` time consumption stat., which is about half-half split of CPU usage of TPC timeframe buidling and ROOT DST output: 
Test production, -> debug -> test more
- #3248
- #3242 
- #3238

Minor feature additions for TPC time frame building

---

offline/framework/ffarawobjects/TpcRawHit.h
offline/framework/ffarawobjects/TpcRawHitv3.cc
offline/framework/ffarawobjects/TpcRawHitv3.h
offline/framework/fun4allraw/SingleTpcTimeFrameInput.cc
offline/framework/fun4allraw/SingleTpcTimeFrameInput.h
offline/framework/fun4allraw/TpcTimeFrameBuilder.cc
offline/framework/fun4allraw/TpcTimeFrameBuilder.h

More performance tuning for TPC Time Frame building: 
* Faster CRC calculation based on iterator access. This seems drop CRC time cost from 14% of run time to 10% of run time.
* Add parity calculation along with CRC 
* Allow process a subset of packets 
* Iterator based adc decoding for a faster buffer access
* bug fixes 
Updated callgrind 
- #3254 …

Performance tuning for TPC Time Frame building

---

offline/framework/fun4allraw/SingleTpcTimeFrameInput.cc
offline/framework/fun4allraw/TpcTimeFrameBuilder.cc

Thanks to the work from Joe, who run a test production with Chris' build on #3255. The three run test production revealed three failure modes that is related to rare data behaviors. These are fixed in this PR: 
* Fix memory usage when handling large multi-event packets as result of DAQ slow down. 
* Disable a strong check which can fail assert under particular case of mismatch between FELIX GL1 Tagger BCO and GL1 BCO in raw data
* Avoid making RawHit for unmatched hit, to help reduce memory load when handling stuck FEEs …

Fix three low occurrence issues found in last night's test production

---

offline/framework/fun4allraw/SingleInttPoolInput.cc
offline/framework/fun4allraw/SingleMvtxPoolInput.cc

There are cases where BCOs are added to the stack that have no hits, and thus they don't get cleared out properly leading to a memory blow up. This PR fixes the container cleanup to be more succinct and erase all BCOs less than the reference BCO

fix: clear all bcos

---

offline/packages/intt/CylinderGeomIntt.cc

Currently, in `CylinderGeomIntt::find_strip_index_values`, local position on an INTT sensor surface is converted into strip indices by casting the ratio (distance along surface / strip length) to an int. This cast truncates the number, which in particular converts values like -0.1 (corresponding to a position that's not actually on the surface at all) to 0 (which is a valid strip index value). This means that positions not corresponding to any valid sensor for that surface are assigned valid strip indices.
This PR changes that int cast …

Fix out-of-bounds values being assigned valid strip indices in CylinderGeomIntt::find_strip_index_values

---

offline/framework/ffarawobjects/TpcRawHitContainerv3.cc
offline/framework/fun4allraw/SingleTpcTimeFrameInput.cc

Somehow the raw data file `TPC_ebdc02_physics-00051740-0013.evt` fetched a different run number of 11140 very late into the raw data file. This is the last raw data segment and likely corrupted at the end. This lead to a run number mismatch and crashed production for this run. 
This PR make a work around by fetching run number from first event in a segment 
@hupereir pointed out the `dynamic_cast` is slow and the `TpcRawHit *TpcRawHitContainerv3::AddHit(TpcRawHit *tpchit)` now use ROOT TClass to determine the RawHit class match. 
This …

Fix rare issue found in last night's test production and minor speed improvement 

---

offline/packages/trackreco/PHTrackSeeding.h

When running over cluster DSTs, this lack of the clusterhit association node prints out an error message. This suppresses that, as the node is not used in our default track seeding

fix: turn off hit assoc

---

offline/framework/fun4all/Fun4AllDstOutputManager.h
offline/framework/fun4all/Fun4AllOutputManager.h

This PR adds the compression level setting to the Fun4AllOutputManager base class. It's just implemented for DSTs but maybe one day we'll compress other output as well

add CompressionSetting() to Fun4AllOutputManager base class

---

offline/framework/fun4allraw/SingleInttPoolInput.cc
offline/framework/fun4allraw/SingleMvtxPoolInput.cc

I introduced a memory leak into the pool inputs that evaded Jenkins. It turns out that the default valgrind job on the streaming input is not actually running properly. See for example a log from a recent PR [here](https://web.sdcc.bnl.gov/jenkins-sphenix/job/sPHENIX/job/test-default-valgrind-StreamingProduction/1159/artifact/macros/StreamingProduction/Fun4All_Stream_Combiner.C.log/*view*/). Interestingly Jenkins marks it as successful even the job doesn't run properly. @blackcathj is there an easy way to fix this? …

fix: memory leak

---

offline/packages/tpc/Makefile.am
offline/packages/tpc/TpcCombinedRawDataUnpacker.cc
offline/packages/tpc/TpcCombinedRawDataUnpacker.h
offline/packages/tpc/TpcCombinedRawDataUnpackerDebug.cc
offline/packages/tpc/TpcCombinedRawDataUnpackerDebug.h

Add local baseline subtraction to TpcUnpacker. 
This option removes the module wise common mode noise in certain sectors and reduces the trackign time for these events from a few hours to the usual avrg. time. Baseline restoration is currently turned off by default, has to be enabled by setting:
tpcunpacker->doBaselineCorr(true);
Move NZS debugging options to separate Debug class containing all belles and whistles …

add local baseline subtraction to TpcUnpacker. 

---

offline/packages/trackreco/MakeActsGeometry.h

the new root version with gcc 14 chokes on boost/program_options.hpp, hiding it from cling makes this work

hide boost include from cling

---

offline/packages/trackreco/PHGhostRejection.h
offline/packages/trackreco/PHSimpleKFProp.cc
offline/packages/trackreco/PHSimpleKFProp.h

These changes aim to improve the ghost tracks removal.
- Setting the track ghost selection to the highest values in order to bypass it and go directly to track cluster keys comparisons.
- Setter functions where added to PHGhostRejection and PHSimpleKFProp in order to allow changes in the cuts at macro level.

Setting ghost selection to highest values as default

---

offline/framework/fun4allraw/SingleMicromegasPoolInput_v1.cc
offline/framework/fun4allraw/SingleMicromegasPoolInput_v2.cc

This will prevent saturating when processing large runs.
Incrementing TH1F histogram 1 by 1, ends up with a maximum per/bin value of 2^24 = 16777216, due to internal representaition (see https://stackoverflow.com/questions/12596695/why-does-a-float-variable-stop-incrementing-at-16777216-in-c)
Using TH1I allows to reach INT_MAX, or 2.1 10^9
This might still be too small for long runs. Ultimately will use TH1L when we run a modern enough root version. …

use TH1I for storing waveform and BCO counts. 

---

offline/framework/fun4allraw/SingleInttPoolInput.cc

At least one instance of the INTT decoder memory spiking is from cases where suddenly there are many BCOs put into one of the QA maps that are way less than the reference BCO. It is unclear why this happens at all, but this PR adds a protection for this situation.

fix: minimum bco check

---

offline/packages/TrackingDiagnostics/Makefile.am
offline/packages/TrackingDiagnostics/TrackResiduals.cc
offline/packages/intt/CylinderGeomIntt.cc
offline/packages/intt/CylinderGeomIntt.h
offline/packages/intt/CylinderGeomInttHelper.cc
offline/packages/intt/CylinderGeomInttHelper.h
offline/packages/intt/Makefile.am
offline/packages/trackreco/Makefile.am
offline/packages/trackreco/PHActsKDTreeSeeding.cc
offline/packages/trackreco/PHGenFitTrkFitter.cc
offline/packages/trackreco/PHTruthClustering.cc
simulation/g4simulation/g4eval/Makefile.am
simulation/g4simulation/g4eval/SvtxTruthEval.cc

Split CylinderGeomIntt functionality to a helper class to reduce intt_io dependencies

Split CylinderGeomIntt functionality to a helper class

---

offline/QA/Calorimeters/caloTreeGen/caloTreeGen.cc

Change caloTreeGen module ZDC tower node finder to not abort event if node is not found for use in simulation. Small bug fixes to cout statements to return the correct node names associated with calorimeter dst nodes. 

Change caloTreeGen module ZDC tower node finder to not abort event if node is not found 

---

offline/packages/TrackingDiagnostics/Makefile.am
offline/packages/TrackingDiagnostics/TrackResiduals.cc
offline/packages/mvtx/CylinderGeom_Mvtx.cc
offline/packages/mvtx/CylinderGeom_Mvtx.h
offline/packages/mvtx/CylinderGeom_MvtxHelper.cc
offline/packages/mvtx/CylinderGeom_MvtxHelper.h
offline/packages/mvtx/Makefile.am
offline/packages/trackreco/Makefile.am
offline/packages/trackreco/PHGenFitTrkFitter.cc
offline/packages/trackreco/PHTruthClustering.cc
simulation/g4simulation/g4eval/Makefile.am
simulation/g4simulation/g4eval/SvtxTruthEval.cc
simulation/g4simulation/g4eval/TrkrClusterIsMatcher.cc
simulation/g4simulation/g4eval/g4evaltools.cc
simulation/g4simulation/g4mvtx/PHG4MvtxHitReco.cc

Split CylinderGeom_Mvtx functionality to helper class to avoid linking Acts in io library
Alphabetized some of the relevant makefiles

Split CylinderGeom_Mvtx functionality to helper class

---

offline/QA/Intt/InttRawHitQA.cc
offline/QA/Intt/InttRawHitQA.h
offline/QA/Intt/InttStreamQA.cc
offline/QA/Intt/InttStreamQA.h
offline/QA/Mvtx/MvtxRawHitQA.cc
offline/QA/Mvtx/MvtxRawHitQA.h

This expands the silicon raw hit QA to be able to read multiple raw hit nodes in preparation for the single streaming jobs to properly produce qa output

feat: Multiple nodes in raw hit qa

---

offline/framework/ffarawobjects/TpcRawHitv3.cc
offline/framework/ffarawobjects/TpcRawHitv3.h

@osbornjd and @bogui56 found in the production readback test that the ADC iterator would stuck in an infinity loop when encountered a rare broken TPC waveform that contains an ADC data segment of zero length. 
This PR update the ADC iterator handle such case. It should be invisible to the downstream RawHit user code, which always get the next valid non-zerosuppressed ADC bin.  …

Handle read back of broken TPC RawHit waveform with zero length

---

offline/framework/ffamodules/CDBInterface.cc
offline/framework/ffamodules/CDBInterface.h

This PR adds a flag to disable cdb accesses centrally. We do have some production passes which do not need the cdb (e.g. the calo event combining) and we plan to run those without a cdb tag to avoid confusion/non existing dependencies. For those passes we need to be able to turn the cdb access off so user modules cannot circumvent this. By default cdb access is enabled …

add disable flag, to turn off cdb centrally

---

offline/framework/fun4allraw/MvtxRawDefs.cc

ycm - Add method to read MVTX strobe/readout mode from ocdb

---

calibrations/calorimeter/calo_tower_slope/LiteCaloEval.cc
calibrations/calorimeter/calo_tower_slope/LiteCaloEval.h

Needed to fix bug that was causing a segfault when trying to fit histograms. Added update to draw_spectra() and fit_info()

fixed segfault, updates to draw_spectra and fit_info fns

---

offline/packages/trackbase/TrackFitUtils.cc
offline/packages/trackbase/TrackFitUtils.h
offline/packages/trackreco/PHMicromegasTpcTrackMatching.cc
offline/packages/trackreco/PHMicromegasTpcTrackMatching.h

[comment]: <Straight-line fit instead of a helical fit for TPC tracks, which simplifies the projection and reduces errors. Added a zeroField flag in the PHMicromegasTpcTrackMatching.> (Please tell us something about this pull request)

Zero field implementation for TPOT-TPC tracking matching

---

offline/packages/jetbackground/RetowerCEMC.cc

[comment]: <Added a verbosity flag to the createnode which suppresses a warning> (Please tell us something about this pull request)

Updated retowerCEMC to suppress the warning from trying to re-retower

---

offline/packages/trackreco/PHMicromegasTpcTrackMatching.cc

Corrected a Verbosity for a cout after a _zero_field bool flag.
[comment]: <Just implemented a Verbosity> (Please tell us something about this pull request)

Added a Verbosity after the _zero_field bool

---

.clang-tidy
offline/QA/SimulationModules/QAG4Decayer.cc
offline/QA/SimulationModules/QAG4SimulationCalorimeter.cc
offline/QA/SimulationModules/QAG4SimulationCalorimeterSum.cc
offline/QA/SimulationModules/QAG4SimulationDistortions.cc
offline/QA/SimulationModules/QAG4SimulationIntt.cc
offline/QA/SimulationModules/QAG4SimulationJet.cc
offline/QA/SimulationModules/QAG4SimulationKFParticle.cc
offline/QA/SimulationModules/QAG4SimulationMicromegas.cc
offline/QA/SimulationModules/QAG4SimulationMvtx.cc
offline/QA/SimulationModules/QAG4SimulationTpc.cc
offline/QA/SimulationModules/QAG4SimulationTracking.cc
offline/QA/SimulationModules/QAG4SimulationTruthDecay.cc
offline/QA/SimulationModules/QAG4SimulationUpsilon.cc
offline/QA/SimulationModules/QAG4SimulationVertex.cc

Adds an ignore to the `.clang-tidy` file to ignore the `std::endl` warnings, and applies clang-tidy to the simulation qa package

fix: clang tidy simulation qa package

---

offline/packages/TrackingDiagnostics/TrackResiduals.cc

TrackResidual tree size blows up after running over many events. The diagnostic result shows that one cluster vector is not cleared at the end of process_event.

fix clear vector

---

offline/packages/CaloReco/CaloTowerStatus.cc
offline/packages/CaloReco/CaloTowerStatus.h

`TowerInfov4` saturate chi2 around 3e8, so some towers with very large energy(1E6) won't get flagged by the status setter, this PR adds an maximum chi2 threshold(1E8 by default).

Max chi2 threshold for tower status setter

---

offline/QA/Calorimeters/CaloValid.cc
offline/QA/Calorimeters/CaloValid.h
offline/QA/Calorimeters/Makefile.am

Added TH3 h_pi0_trigIB_mass to hold pi0 mass for each IB board, for triggers 10, and 28-31 (photon triggers). Updated necessary code to use decodeTriggers for this triggered data going into TH3, included header file definition, and inclusion of line in Makefile. Updated a couple of bugs causing memory issues when testing histogram generation.
[comment]: <> ( In case this is a draft PR, e.g. for running checks …

CaloValid TH3 histogram addition and trigger software inclusion

---

offline/packages/jetbase/ClusterJetInput.cc
offline/packages/jetbase/ClusterJetInput.h
offline/packages/jetbase/TowerJetInput.cc
offline/packages/jetbase/TowerJetInput.h

Allows user to select the type of global vertex used for jet reconstruction with either calorimeter towers or calorimeter clusters. Uses the GlobalVertex enum types to determine which global vertex to use. When global vertex type not specified, default behavior is still to use the "best" vertex from GlobalVertex. 
PR in macros repo to implement …

Add setter function to TowerJetInput and ClusterJetInput to allow for user-specified z vertex type 

---

offline/database/sphenixnpc/CDBUtils.cc
offline/database/sphenixnpc/SphenixClient.cc

This PR fixes a long standing issue where using -O2 or no optimizer leads to unresolved externals. The underlying problem is a bad template definition in the NPPS client:
template<typename T>
json NoPayloadClient::makeResp(T msg) {
return {{"code", 0}, {"msg", msg}};
}
using this in our code to return the payload url will lead to an unresolved json external. Contructing this ourselves without going through this template finally fixes this weird problem
[comment]: <> ( In case …

Fix nopayloadclient

---

offline/packages/CaloReco/CaloTowerCalib.h

Setter functions set_dotimecalib and set_doCalibOnly are implemented to allow for user to set member variables dotimecalib and doZScrosscalib from the module level.

Add setter functions to CaloTowerCalib for mean time calibration and to only do calorimeter energy calibration

---

generators/hijing/Makefile.am
offline/framework/fun4allraw/Makefile.am

This cosmetic PR adds subdir-objects to the automake options to get rid of the warning that we use sources from subdirs 

add subdir-objects to AUTOMAKE_OPTIONS

---

offline/packages/trackbase/TrkrClusterv5.cc

CopyFrom Function in TrkrClusterv5 used getPhiError when the name of the function is getRPhiError. This only fixes the names used in CopyFrom but it could be worth looking into why the get and set functions have different naming schemes

Fixed an error in the CopyFrom Function in TrkrClusterv5 

---

offline/packages/jetbackground/BeamBackgroundFilterAndQADefs.h
offline/packages/jetbackground/StreakSidebandFilter.cc
offline/packages/jetbackground/StreakSidebandFilter.h

Changes the status that the streak filter checks to determine if a tower is good or bad. Previously, checked for 1 to determine goodness (wrong), now checks for 0 (good) or 32 (zero suppressed and good).
This is a bug fix. As above, I have changed which statuses indicate that a tower is good to match the definitions currently in core software. Previously this file checked that the status was NOT 1 in order to determine that the tower was bad. It should check for NOT 0 and NOT 32, as these two statuses are good towers. …

Change Status Check for StreakSidebandFilter

---

offline/packages/tpc/TpcCombinedRawDataUnpacker.cc
offline/packages/tpc/TpcCombinedRawDataUnpacker.h

Found another memory leak while digging for other deeper memory issues in the production jobs

fix: another memory leak

---

calibrations/calorimeter/calo_emc_pi0_tbt/pi0EtaByEta.cc
calibrations/calorimeter/calo_emc_pi0_tbt/pi0EtaByEta.h

This PR adds function set_requireVertex which allows the user to require that every event used in pi0 mass finding have a z vertex (previous/default behavior sets vtx_z = 0 in the case that a vertex is not found from the GlobalVertex Container). This PR also adds function set_GlobalVertexType which allows the user to choose the vertex type from the GlobalVertex Container to use allowing for direct comparison between calorimeter data in data and MC using the MBD vertex. 
[comment]: <> ( In case this is a draft PR, e.g. for running …

Add functions to pi0EtaByEta to require a z vertex and to set the vertex type used for cluster location.

---

offline/QA/SimulationModules/Makefile.am
offline/QA/SimulationModules/QAG4SimulationDistortions.cc
offline/QA/SimulationModules/QAG4SimulationDistortions.h

Load and apply distortion corrections when forming unbiased residuals in the TPC.
This should address why Xudong sees no effect on applying distortion corrections in https://indico.bnl.gov/event/26185/contributions/101494/attachments/59434/102129/20250114_yuxd_TPC_distortion.pdf

Apply distortion corrections in distortion QA evaluation module

---

offline/packages/CaloReco/RawClusterBuilderTopo.cc

Splitting part goes in infinite loop when pseudocluster contains large negative values. This PR change the initial energy smaller to guarantee the finding of neighbor clusters to split the tower energy. 

Topo cluster change the initial sub_cluster E for fitting

---

offline/packages/tpc/TpcCombinedRawDataUnpacker.cc

The tpc unpacker has some weird behavior sometimes with memory consumption. Valgrind reported some invalid reads and this PR fixes those. I also clang-formatted the file to make it more readable

fix: tpc unpacker invalid reads

---

offline/framework/fun4allraw/SingleInttPoolInput.h

This adds a triggered mode setter that sets the BCO ranges appropriately based on whether or not the INTT was in triggered or streaming mode. It can be set from the macro level with a db query similar to the hit unpacker.

feat: triggered mode setter

---

offline/packages/CaloReco/RawClusterBuilderTemplate.cc
offline/packages/CaloReco/RawClusterBuilderTemplate.h

Functionality in RawClusterBuilder to set peak threshold for local maxima finder in EMCal sub-clustering. 

Functionality in RawClusterBuilder to set peak threshold

---

offline/packages/CaloBase/TowerInfo.h
offline/packages/CaloBase/TowerInfov2.h
offline/packages/CaloBase/TowerInfov4.h
offline/packages/CaloReco/CaloTowerBuilder.cc
offline/packages/CaloReco/CaloTowerBuilder.h
simulation/g4simulation/g4waveformsim/CaloWaveformSim.cc
simulation/g4simulation/g4waveformsim/CaloWaveformSim.h

Add saturation status bit for both data and sim.

Saturation status bit for calo towers

---

offline/framework/fun4allraw/SingleMvtxPoolInput.cc

This fixes the time bucket range of the MVTX to include hits of up to 5 strobes in either direction of the GL1 to be included into a streamed event processing. This should resolve the issue Tony brought up this weekend.

fix: mvtx time bucket range

---

offline/packages/trackreco/PHMicromegasTpcTrackMatching.cc
offline/packages/trackreco/PHMicromegasTpcTrackMatching.h

This PR builds on the code changes from @pedroanietom to 
- simplify/streamline the straight line fit
- add a flag to extrapolate from the silicons (MVTX and INTT in r,phi; MVTX only in r,z) instead of the TPC
- add the possibility to select both lower and upper limits for the TPC layers used for the fit.
It was checked that with identical parameters the fit results are identical to before the change.
@pedroanietom: feel free to have a look, double check.
The changes might conflict with local changes that you have. I can help resolve if this is a problem. 
[comment]: <> ( What does this PR do? Linking to talk in software …

Tpc micromegas matching

---

offline/packages/mbd/MbdCalib.cc
offline/packages/mbd/MbdCalib.h

[comment]: Names in t0corr were incorrect, resulting in failure retrieving from CDB
[comment]: Names of t0corr variables were fixed.  Previously, it tried to find the calibrations and failed.

Fixed Incorrect Names in t0corr calibrations

---

offline/packages/uspin/SpinDBOutput.cc
offline/packages/uspin/SpinDBOutput.h

This PR adds verbosity to SpinDBOutput error messages about empty arrays.

Add verbosity to uspin

---

offline/packages/CaloReco/CaloWaveformFitting.cc

When the waveform is saturated we are not including the sample(and one sample after saturation) for the least square fit.
Revert the change for default setting of the timing position, not the initial peak time is at the peak sample.
Some examples shown below, from EMCal beam data:
From waveform simulation:

Fit Saturated towers

---

offline/framework/fun4allraw/Fun4AllStreamingInputManager.cc
offline/packages/mvtx/MvtxCombinedRawDataDecoder.cc

We found that the MVTX hits in the track reconstruction dropped off after around 100 BCOs. Upon investigation, it looks like the MVTX pool was filled in reverse so there were no hits after the first strobe but several strobes filled from before GL1. There was also a bug in the unpacker that flipped the sign of the strobe index and then sent these hits from before the GL1 into INTT and TPC hits from after the GL1 by giving them a positive time sign. 
@jdosbo @pinkenburg @adfrawley @ycorrales we should probably check this PR against a test track reconstruction to ensure this actually fixes things before merging. There were …

CD: MVTX event combining patch

---

simulation/g4simulation/g4main/Makefile.am
simulation/g4simulation/g4main/PHG4MCProcessDefs.h
simulation/g4simulation/g4main/PHG4ProcessMap.cc
simulation/g4simulation/g4main/PHG4ProcessMap.h
simulation/g4simulation/g4main/PHG4ProcessMapPhysics.cc
simulation/g4simulation/g4main/PHG4ProcessMapPhysics.h
simulation/g4simulation/g4main/PHG4TruthTrackingAction.cc
simulation/g4simulation/g4main/PHG4VtxPointv2.cc
simulation/g4simulation/g4main/PHG4VtxPointv2.h
simulation/g4simulation/g4main/PHG4VtxPointv2LinkDef.h

- **ycm - Add G4 process information:**
- **ycm - create PHG4VtxPointv2**
- **ycm - fill PHG4VtxPointv2 with G4track process**
WIP, This is a first attempt to include G4 creator process to secondaries particles.
New feature to MC simulation
It get the G4Track creator process and propagate it to the PHG4VtxPointv2 

WIP add creator G4 process to particle vertex point

---

offline/packages/trackbase/AlignmentTransformation.cc
offline/packages/trackbase/AlignmentTransformation.h

This restores the option in AlignmentTransformation to apply a rotation of the surface in global coordinates after the Acts transformation. It allows the surface to be rotated around the x, y or z axis.
The code will now read files containing alignment parameters:
"hitsetkey  alpha, beta, gamma, dx, dy, dz, dgrx, dgry, dgrz"
Or, files containing only:
"hitsetkey  alpha, beta, gamma, dx, dy, dz"
In the latter case, it sets dgrx, dgry, dgrz to zero.
It should be kept in …

Add back global alignment rotation option

---

offline/packages/trackreco/PHSiliconTpcTrackMatching.cc
offline/packages/trackreco/PHSiliconTpcTrackMatching.h

These include a constant (w.r.t. pT) window for x, y A Q and pT dependent window for Z, and eta
A offcentered-window for phi

Update matching windows to reflect study on current ranges

---

offline/framework/fun4all/Fun4AllHistoManager.cc

Fixes the filename assignment for the closeout script, which wasn't apparent until testing in the production

fix: filename in closeout script

---

offline/packages/jetbase/JetReco.cc

Make sure the node is empty before filling in jets so you don't get duplicate jets

JetReco: reset node before filling

---

offline/QA/EventDisplay/TrackerEventDisplay.cc
offline/QA/EventDisplay/TrackerEventDisplay.h
offline/packages/TrackingDiagnostics/TrkrNtuplizer.cc
offline/packages/tpc/LaserClusterizer.cc
offline/packages/tpc/Tpc3DClusterizer.cc
offline/packages/tpc/TpcClusterizer.cc
offline/packages/tpccalib/TpcDirectLaserReconstruction.cc
simulation/g4simulation/g4tpc/PHG4TpcElectronDrift.cc
simulation/g4simulation/g4tpc/PHG4TpcPadBaselineShift.cc
simulation/g4simulation/g4tpc/PHG4TpcPadPlaneReadout.cc
simulation/g4simulation/g4tpc/PHG4TpcSubsystem.cc
simulation/g4simulation/g4tpc/TpcClusterBuilder.cc

This PR fixes the various places in the code that hardcode the TPC ADC clock to 53 ns to use the geometry objects definition of the ADC clock. This is in preparation for a new geometry file which uses the 50 ns clock that was actually used in run 24. The default value is left as 53ns as this was the design expectation and is what is expected to be the case in run 25. I will create a new geometry CDB file with the updated TPC geometry to be applicable for run 24. …

refactor: standardize use of TPC ADC clock

---

offline/packages/centrality/CentralityReco.cc
offline/packages/centrality/CentralityReco.h

Initialize m_mbd_total_charge to 0 instead of NaN to prevent the first event processed by Fun4All from having m_mbd_total_charge=nan and CentBin=0 (since adding a float to nan results in nan.)
This minor bug does not affect subsequent events, as ResetEvent sets m_mbd_total_charge = 0.

Minor bug fix for CentralityReco

---

offline/packages/KFParticle_sPHENIX/KFParticle_Tools.cc

Track pair DCA value is not updated in before, always zero. In this PR, DCA will be updated in reconstruction.

KFP: update dca

---

simulation/g4simulation/g4waveformsim/CaloWaveformSim.cc
simulation/g4simulation/g4waveformsim/CaloWaveformSim.h

This PR introduce the pedestal scaling by set_pedestal_scale method(set to a smaller number for smaller noise scale).
This PR is for fine tuning or noise level to better match data. Currently since the pedestal file we used in our sim is taken after the pp running, therefore the pedestal is the worst case estimation, this PR make it possible to scale down the pedestal fluctuation to achieve better data/MC agreement :)  

waveform sim pedestal scaling

---

offline/QA/Calorimeters/CaloValid.cc
offline/QA/Calorimeters/CaloValid.h

It just adds additional QA histograms to the class CaloValid. Previously it only had the narrow range histogram for the tower energy spectra, this will add wider range -10,40 Gev with 100 bins for all the calorimeters

add 5 more histogram with wide range and narrow range for energy for the tower QA for cemc ihcal ohcal

---

offline/packages/KFParticle_sPHENIX/KFParticle_Tools.cc

This PR fixes a bug in KFParticle_Tools where a track missing a silicon seed entirely would never fail the minimum MVTX hits cut, and would be included in the daughter particles list. (It also fixes an analogous issue for silicon-only tracks and the minimum TPC hits cut.)

Resolved KFParticle issue where TPC-only tracks pass nmvtx cut

---

offline/packages/trackreco/PHActsSiliconSeeding.cc
offline/packages/trackreco/PHActsSiliconSeeding.h

This adds hooks to the silicon seeder to run the Acts seeding algorithm on a strobe by strobe basis. It can be improved with the helper object in https://github.com/sPHENIX-Collaboration/coresoftware/pull/3404, as currently all the hitsetkeys are looped over to obtain clusters and only those belonging to a certain strobe are added to the seeding algorithm. Witih the helper object, we can just look up all hitsetkeys associated to a particular strobe ID. This improves the silicon seeding as will be discussed in the tracking meeting today
https://indico.bnl.gov/event/26226/
[comment]: <> ( In case this …

feat: Option to seed by strobe

---

offline/packages/KFParticle_sPHENIX/KFParticle_sPHENIX.cc
offline/packages/KFParticle_sPHENIX/KFParticle_sPHENIX.h

[comment]: <Fixed an error where KFParticle wouldn't be able to have multiple instances in one macro due to a variable not being private
> (Please tell us something about this pull request)
[comment]: <This makes candidateCounter private and introduces functions to utilize it properly> ( What does this PR do? Linking to talk in software meeting encouraged )

KFParticle candidateCounter fix

---

offline/packages/KFParticle_sPHENIX/KFParticle_Tools.cc

Removes debug print statement accidentally left in KFParticle_Tools.cc.

Remove debug print statement from KFParticle_Tools

---

offline/packages/mvtx/Makefile.am
offline/packages/mvtx/configure.ac

This PR updates the compiler flags for the mvtx package. The standard -Wshadow which prevents shadowed variable use was missing. Also use -isystem for OFFLINE_MAIN/include to get rid of warnings from 3rd party includes. No need to run jenkins [skip-ci]

update compiler flags for mvtx

---

offline/packages/intt/InttBadChannelMap.cc
offline/packages/intt/InttBadChannelMap.h
simulation/g4simulation/g4intt/PHG4InttDigitizer.cc
simulation/g4simulation/g4intt/PHG4InttDigitizer.h

(INTT) Updated PHG4InttDigitizer to use CDB calibration

---

offline/packages/trackreco/ActsEvaluator.cc
offline/packages/trackreco/ActsEvaluator.h
offline/packages/trackreco/PHActsTrkFitter.cc
offline/packages/trackreco/PHActsTrkFitter.h

This fixes up the Acts evaluator to work with raw data and not just simulation files, for evaluating what the Kalman Filter is actually doing.

fix: Acts evaluator with data

---

offline/packages/trackreco/PHCASeeding.cc

The calculation of dphi from point A to point B was atan2(By,Bx) - atan2(Ay,By). This fails for values at -Ax and -Bx, where Ay and By change sign (the periodic boundary). This is now fixed.

Fig but in PHCASeeding

---

offline/packages/tpc/TpcClusterizer.cc
offline/packages/tpc/TpcClusterizer.h

This reverts the commits that broke the tpc clusterizer

fix: revert tpc clusterizer threading changes

---

offline/packages/jetbase/JetCalib.cc
offline/packages/jetbase/JetCalib.h

Update JetCalib for first JES calibration.

---

offline/packages/trackbase/AlignmentTransformation.cc
offline/packages/trackbase/AlignmentTransformation.h

The introduction of the transient transform container meant that the misalignment factors applied to Acts were not properly propagated. This PR fixes this problem such that the measurement uncertainties are properly blown up based on some macro setting

fix: misalignment factor setting

---

offline/packages/jetbackground/BeamBackgroundFilterAndQA.cc
offline/packages/jetbackground/BeamBackgroundFilterAndQA.h
offline/packages/jetbackground/Makefile.am

This PR updates the `BeamBackgroundFilterAndQA` module to use `PHParameters` instead of `recoConsts`, and ensures that flags are updated _and_ reset event-to-event.
This resolves a bug where the flags generated by the module were never updated, so once an event was found with beam background, the corresponding flag is set to true but never _reset_. Thanks to @jnclement for catching this!
Furthermore, since `recoConsts` is intended for reconstruction parameters which change more on the scale of a run, `PHParameters` is the more appropriate tool.
Note that the example macro and reader module have been updated in [analysis](https://github.com/sPHENIX-Collaboration/analysis/tree/master/JS- …

Use PHParameters instead of recoConsts in Beam-Background Filter module

---

offline/packages/ClusterIso/ClusterIso.cc

be consistent with good tower description in cluster builder. (Also since the timing calib is not working currently some good tower can be tag as bad time therefore get excluded from the iso calculation leading to abnormal negative iso ET).
I thought I changed that long time ago :(

ClusterIso: use isgood for tower selection

---

offline/QA/Calorimeters/CaloValid.cc
offline/QA/Calorimeters/CaloValid.h

Add a new tower histogram for all the calorimeters to check its tower energy if it is saturated

Add histogram to check for a tower energy, if it is saturated

---

offline/packages/jetbackground/DetermineEventRho.cc
offline/packages/jetbackground/DetermineTowerRho.cc

Removed fasjet::JetMedianBackgroundEstimator and replaced with a custom function to calculate area rho. Similar to multiplicity-based rho. Handles negative E towers correctly now
Fixed the way DetermineTowerRho/DetermineEventRho calculates area-based rho:
https://indico.bnl.gov/event/26524/#sc-87-6-ppg-04-ue-in-auau …

update to area rho method

---

offline/packages/trackreco/PHSiliconTpcTrackMatching.cc
offline/packages/trackreco/PHSiliconTpcTrackMatching.h

Re-enabled the check in the silicon-TPC matcher that the crossing z correction provides a good match to the silicon z. Changed to using the TpcClusterZCrossingCorrection class for the z correction, for consistency with the rest of the reconstruction code.

Re-enable check that crossing z correction gives sensible result

---

offline/packages/trackbase/ActsGeometry.h
offline/packages/trackbase/AlignmentTransformation.cc
offline/packages/trackreco/MakeActsGeometry.cc
offline/packages/trackreco/MakeActsGeometry.h

This adds the TPC time zero correction as an additional z-offset in the alignment transformations for the TPC. This retains the as-recorded value of the TPC cluster time, and guarantees that TPC clusters get the correction in all circumstances when the position is transformed to global coordinates. The time zero correction is stored in the Acts geometry object alongside the TPC drift velocity, and is used only in AlignmentTransformation during TPC transform creation. …

Apply TPC tzero offset in alignment transforms for TPC.

---

offline/packages/CaloBase/RawCluster.cc
offline/packages/CaloBase/RawCluster.h
offline/packages/CaloBase/RawClusterv1.h
offline/packages/CaloBase/TowerInfoContainerSimv2.cc
offline/packages/CaloBase/TowerInfov1.cc
offline/packages/CaloReco/BEmcCluster.h
offline/packages/CaloReco/CaloGeomMapping.cc
offline/packages/CaloReco/CaloGeomMapping.h
offline/packages/CaloReco/CaloWaveformFitting.cc
offline/packages/CaloReco/CaloWaveformFitting.h
offline/packages/CaloReco/CaloWaveformProcessing.cc
offline/packages/CaloReco/CaloWaveformProcessing.h
offline/packages/CaloReco/ClusterCDFCalculator.cc
offline/packages/CaloReco/ClusterCDFCalculator.h
offline/packages/CaloReco/RawClusterBuilderTopo.cc
offline/packages/CaloReco/RawClusterBuilderTopo.h
offline/packages/CaloReco/RawClusterLikelihoodProfile.cc
offline/packages/CaloReco/RawClusterLikelihoodProfile.h
offline/packages/CaloReco/RawTowerCalibration.h
offline/packages/CaloReco/RawTowerCombiner.cc
offline/packages/CaloReco/RawTowerCombiner.h

Updated profile LUT and call for merged cluster prob. variable + usage of vertex (if exist) for cluster position correction in the profile module

Updated profile LUT and call for merged cluster prob.

---

calibrations/tpc/fillDigitalCurrentMaps/readDigitalCurrents.cc
calibrations/tpc/fillSpaceChargeMaps/fillSpaceChargeMaps.cc
generators/phhepmc/Fun4AllHepMCPileupInputManager.h
offline/framework/fun4allraw/SingleMvtxPoolInput.cc
offline/framework/phool/Makefile.am
offline/framework/phool/sphenix_constants.h
offline/packages/TrackerMillepedeAlignment/HelicalFitter.cc
offline/packages/TrackerMillepedeAlignment/HelicalFitter.h
offline/packages/TrackingDiagnostics/KshortReconstruction.h
offline/packages/mvtx/MvtxCombinedRawDataDecoder.cc
offline/packages/tpc/TpcClusterZCrossingCorrection.cc
offline/packages/tpc/TpcClusterZCrossingCorrection.h
offline/packages/tpc/TpcGlobalPositionWrapper.cc
offline/packages/tpc/TpcGlobalPositionWrapper.h
offline/packages/trackbase/ActsGeometry.cc
offline/packages/trackbase/ActsGeometry.h
offline/packages/trackbase/ActsTrackingGeometry.h
offline/packages/trackreco/ActsAlignmentStates.h
offline/packages/trackreco/PHSiliconTpcTrackMatching.cc
offline/packages/trackreco/PHSiliconTpcTrackMatching.h
offline/packages/trackreco/SecondaryVertexFinder.h
simulation/g4simulation/g4bbc/MbdDigitization.cc
simulation/g4simulation/g4intt/PHG4InttHitReco.cc
simulation/g4simulation/g4main/Fun4AllDstPileupInputManager.h
simulation/g4simulation/g4main/Fun4AllSingleDstPileupInputManager.h
simulation/g4simulation/g4main/PHG4PileupGenerator.h
simulation/g4simulation/g4mvtx/PHG4MvtxHitReco.h
simulation/g4simulation/g4tracking/TrkrTruthTrackContainer.cc
simulation/g4simulation/g4tracking/TrkrTruthTrackContainer.h
simulation/g4simulation/g4tracking/TrkrTruthTrackContainerv1.h

We use time_between_crossings = 106ns in many places in our code. Discussing with Jin, this value is not quite correct, and impacts our ability to match TPC tracks to silicons (and TPOT) in extended readout mode. Jin quoted a more accurate value of 106.65237. This PR changes the value to everywhere relevant. 
Ultimately we would rather use a centraly defined value (using e.g some static constexpre float in a global header), to be agreed upon with @pinkenburg. 
For now, lets see if this compiles and if not everything is broken. 
Improvement to TPC-TPOT matching:  …

Fix time between crossings

---

offline/framework/ffarawobjects/MvtxFeeIdInfo.h
offline/framework/ffarawobjects/MvtxFeeIdInfov1.h
offline/framework/ffarawobjects/MvtxRawEvtHeader.h
offline/framework/ffarawobjects/MvtxRawEvtHeaderv1.h
offline/framework/ffarawobjects/MvtxRawEvtHeaderv2.h
offline/packages/mvtx/MvtxCombinedRawDataDecoder.cc
offline/packages/mvtx/MvtxCombinedRawDataDecoder.h
offline/packages/trackbase/Makefile.am
offline/packages/trackbase/MvtxEventInfo.h
offline/packages/trackbase/MvtxEventInfov3.cc
offline/packages/trackbase/MvtxEventInfov3.h
offline/packages/trackbase/MvtxEventInfov3LinkDef.h
offline/packages/trackbase/TrkrHitSetContMvtxHelper.cc
offline/packages/trackbase/TrkrHitSetContMvtxHelper.h
offline/packages/trackbase/TrkrHitSetContMvtxHelperLinkDef.h
offline/packages/trackbase/TrkrHitSetContMvtxHelperv1.cc
offline/packages/trackbase/TrkrHitSetContMvtxHelperv1.h
offline/packages/trackbase/TrkrHitSetContMvtxHelperv1LinkDef.h

- **ycm - clean and merge MVTX event header**
- **ycm - add new Mvtx trkr hitset helper to map hitsetkey with strobe id**
- **ycm - add default ctors/assigment**
- **ycm - changes to add new mvtx hit set helper**
This PR add a map of hitsekey per strobe during the MVTX unpacking, this will allow to
run the clustering process for single strobe and Si seeding for a given range of strobes. …

Add Mvtx hit set helper

---

offline/packages/mvtx/MvtxCombinedRawDataDecoder.cc

This PR try to abort/unregister MVTX unpacker reco system if we use old DST with obsolete MVTXRawEvtHeaderv1.

ycm - change to check mvtx raw event header

---

offline/packages/mvtx/MvtxCombinedRawDataDecoder.cc

While producing some cluster DSTs for tpc calibration runs, we found that the mvtx unpacker exits if the nodes are not found. This shouldn't happen and this PR instead reverts the behavior back to just unregistering the module so that the job can proceed even in the absence of the proper node.

fix: do not exit mvtx unpacker

---

offline/packages/micromegas/CylinderGeomMicromegas.cc
offline/packages/micromegas/CylinderGeomMicromegas.h
offline/packages/tpccalib/TpcSpaceChargeReconstructionHelper.cc
offline/packages/tpccalib/TpcSpaceChargeReconstructionHelper.h

This adds some helper methods to facilitate the distortion extrapolation from TPOT acceptance to the full TPC acceptance 
1/ two new methods to calculate the phi and theta range of a given TPOT detector, using latest geometry+alignment correction
2/ the possibility to set the relevant theta and phi ranges (previously hard coded) to the TpcSpaceChargeReconstructionHelper class
@yudPKU (Xudong) I'll send you a separate email on how to use those. …

Distortion extrapolation update

---

offline/packages/jetbackground/JetBackgroundCut.cc

The jet background tagging is determined via: isDijet, frcem, frcoh, maxJetET, and dPhi so passing these variables to the user allows for verification of the thresholds used that tag the event as containing background.

Added Background Determination flags to User

---

offline/QA/Intt/InttRawHitQA.cc
offline/QA/Mvtx/MvtxRawHitQA.cc
offline/QA/Tpc/TpcRawHitQA.cc

In the QA we should not abort run when a particular node is not found - rather we should just unregister the module. This allows the production to run more flexibly

fix: don't abort in qa when node not found

---

offline/packages/trackreco/PHCosmicSeeder.cc
offline/packages/trackreco/PHCosmicSeeder.h

Adds an option to only use clusters meeting a minimum ADC max cut to limit the number of clusters the seeder has to deal with. Set to 0 by default so nothing changes.

feat: add optional cluster adc cut to cosmic seeder

---

offline/packages/mbd/MbdCalib.cc
offline/packages/mbd/MbdCalib.h
offline/packages/mbd/MbdEvent.cc
offline/packages/mbd/MbdPmtHitV1.cc
offline/packages/mbd/MbdPmtHitV1.h
offline/packages/mbd/MbdReco.cc
offline/packages/mbd/MbdSig.cc
offline/packages/mbd/MbdSig.h

[comment]: When there's an event from a previous crossing, the waveform from that crossing is now corrected out before fits to the waveform.  Occurred in only 1 in every ~10^4 events, depending on collision rate.  A new calibration is needed, mbd_pileup.

corrections to pileup from waveforms in prev crossing polluting current one

---

simulation/g4simulation/g4main/HepMCNodeReader.cc
simulation/g4simulation/g4main/HepMCNodeReader.h

This PR introduces kinematic selections for sampling strange particles within sPHENIX acceptance ($|\eta|\leq1$)
The default selections: $|\eta|\leq1$, $0\leq p_{T}\leq$ std::numeric_limits<float>::max() 
The current method of counting strangeness in the HepMC record does not apply any kinematic selection for sPHENIX acceptance (e.g., $|\eta|\leq1$). The number of added strange particles is calculated based on the total count, regardless of their kinematics. However, the added strange particles are sampled only within $|\eta|\leq1$. The consequence is that one ends up oversampling strange particles within the sPHENIX …

Kinematic selections for adding strange particles

---

offline/packages/TrackingDiagnostics/TrackResiduals.cc

Fixes dca calculation from wrt to origin to vertex position since we can now really try to do this

fix: calc dca wrt vertex

---

offline/packages/CaloReco/CaloWaveformFitting.cc
offline/packages/CaloReco/CaloWaveformFitting.h
offline/packages/CaloReco/CaloWaveformProcessing.cc
offline/packages/CaloReco/CaloWaveformProcessing.h

TEMPLATE_NOSAT processing option fit the saturation waveform as is.
Just in case that we need to run the MC with the old waveform processing method...hope this flag is never used:)

new processing option to turn of the saturation handling

---

offline/packages/KFParticle_sPHENIX/KFParticle_Tools.cc
offline/packages/KFParticle_sPHENIX/KFParticle_Tools.h
offline/packages/KFParticle_sPHENIX/KFParticle_nTuple.cc
offline/packages/KFParticle_sPHENIX/KFParticle_nTuple.h

[comment]: <This adds dEdx for daughter branches to KFParticle's output> ( What does this PR do? Linking to talk in software meeting encouraged )
This adds dEdx for daughter branches to KFParticle's output
Implementing dEdx selection in KFParticle's candidate selection could be useful in future for background reduction. Currently this just saves it to output to allow for selection in plotting

KFParticle dEdx

---

offline/packages/trackreco/PHActsTrackProjection.cc
offline/packages/trackreco/PHActsTrackProjection.h

This PR cleans-up track extrapolation to calorimeter
- unused methods are removed
- only TowerGeomertry objects are needed to determine calorimeters radii to which extrapolate and are only used once
- streamline calorimeter name to surface associations. 

Extrapolation to calorimeters

---

offline/QA/Calorimeters/CaloValid.cc

Fixing IB numbering in TH3 histogram

Use *32 instead of *12 in IB_num calculation for CaloValid

---

offline/packages/KFParticle_sPHENIX/KFParticle_triggerInfo.cc
offline/packages/KFParticle_sPHENIX/KFParticle_truthAndDetTools.cc
offline/packages/trigger/TriggerAnalyzer.cc

I noticed our trigger analyser module isn't compatible with the tracker GL1 packets. Theyre named differently to avoid conflicts with calo DSTs. Chris is aware of this. @danjlis does this look ok to you as a fix?
I also accidentally submitted some test code for debugging truth matching in KFParticle. The bug only affects simulated data that requests truth matching …

Trigger analyser compatible with track DSTs. KFP bug fix

---

offline/packages/trackbase_historic/TrackSeedContainer_v1.h
offline/packages/trackreco/PHActsSiliconSeeding.cc
offline/packages/trackreco/PHActsSiliconSeeding.h
offline/packages/trackreco/PHSiliconSeedMerger.cc

This PR fixes a few memory leaks that were introduced into the silicon seeding when we moved to strobe by strobe reconstruction. Thanks to @hupereir for helping me spot the actual leak. The resolution is to move all the seeding code into the strobe loop so that the seeds and their corresponding space points are destroyed on a strobe by strobe basis

fix: memory leak in silicon seeding

---

offline/framework/phool/PHNodeIOManager.cc
offline/packages/mbd/MbdReco.cc
offline/packages/mbd/MbdReco.h

There was a subtle issue caused by using a dynamic cast instead of a static cast brought to light by the mbd. The mbd created its nodes in Init() and when a file containing those nodes was opened, they did not overwrite them if the type doesn't match (the mbd has a separate sim object for the pmts which takes the place of the real data object, this is working - only the node creation tickled the problem in our PHNodeIOManager).
This PR restores the previous behavior of the PHNodeIOManager (overwriting existing nodes which have a different content) and moves the …

Restore readback from file

---

offline/QA/Jet/RhosinEvent.cc

This PR extends the axes of the histograms of the `RhosInEvent` Jet QA module.
This addresses a bug noticed in Run24 Au+Au, namely that the axes of these histograms were optimized for p+p collisions.

Extend rho axes

---

offline/packages/tpc/TpcCombinedRawDataUnpacker.cc
offline/packages/tpc/TpcCombinedRawDataUnpacker.h

[comment]: <Adds flag to raw hit unpacker that places cut on number of hits allowed in FEE channels> (Please tell us something about this pull request)
[comment]: <This PR adds a flag to the raw hit unpacker that, when called, places a cut on the number of hits allowed in the TPC channels. If a channel has more hits than the threshold value set in TpcCombinedRawDataUnpacker then those hits are rejected. The purpose of this is to address noisy channels in the TPC that are always firing. When the writeTree flag is called, this new flag will also add a histogram to the output file that shows the distribution of hits in all channels.> ( What does this PR do? Linking to talk in software …

Add flag to raw hit unpacker

---

offline/packages/KFParticle_sPHENIX/KFParticle_Tools.cc
offline/packages/KFParticle_sPHENIX/KFParticle_Tools.h
offline/packages/KFParticle_sPHENIX/KFParticle_eventReconstruction.cc
offline/packages/KFParticle_sPHENIX/KFParticle_nTuple.cc
offline/packages/KFParticle_sPHENIX/KFParticle_nTuple.h
offline/packages/KFParticle_sPHENIX/KFParticle_sPHENIX.h
offline/packages/KFParticle_sPHENIX/KFParticle_truthAndDetTools.cc
offline/packages/KFParticle_sPHENIX/KFParticle_truthAndDetTools.h

Added two new features:
1. A flag to use the SvtxVertexMap instead of the GlobalVertexMap
2. A flag to require that the daughter tracks calculate variables wrt their assigned PV, rather than all PVs

KFP: Can now switch to use SvtxVertexMap over GlobalVertexMap.

---

offline/packages/trackreco/MakeActsGeometry.cc
offline/packages/trackreco/MakeActsGeometry.h

This PR modifies the making of the MVTX hitsetkey-surface association map to use only information from the detector element associated with the surface. It no longer makes assumptions about the MVTX geometry.

Construct hitsetkey-surface map without making geometry assumptions

---

offline/QA/Calorimeters/CaloFittingQA.cc

This fixes a bug in the calo fitting QA which occurs when a subsystem isn't in, so the waveform vector size is 0. Should allow us to test QA infrastructure now with ongoing cosmics

fix: zero size vector crash

---

simulation/g4simulation/g4mvtx/PHG4MvtxDetector.cc
simulation/g4simulation/g4mvtx/PHG4MvtxDetector.h
simulation/g4simulation/g4mvtx/PHG4MvtxMisalignment.cc
simulation/g4simulation/g4mvtx/PHG4MvtxMisalignment.h
simulation/g4simulation/g4mvtx/PHG4MvtxSubsystem.cc
simulation/g4simulation/g4mvtx/PHG4MvtxSubsystem.h

This enables the mvtx large scale geometry shift to be read in from the survey file from the CDB that @hrjheng put together.

feat: read MVTX survey shift from cdb

---

simulation/g4simulation/g4tpc/PHG4TpcCentralMembrane.cc
simulation/g4simulation/g4tpc/configure.ac

variable arrays are not part of the C++ standard and result in a warning. This PR replaces the last two cases of this in our code and re-enables the warning/Werror to prevent future re-introduction

replace illegal variable array by vector

---

offline/packages/jetbackground/FastJetAlgoSub.cc
offline/packages/jetbackground/FastJetAlgoSub.h

This PR extends the use of `FastJetOpts` to `FastJetAlgoSub`, following [coresoftware#2143](https://github.com/sPHENIX-Collaboration/coresoftware/pull/2143). Now both are symmetric in their handling of FastJet options.
This PR is required to complete [macros#992](https://github.com/sPHENIX-Collaboration/macros/pull/992) which utilizes `FastJetOpts` to allow for greater flexibility to running jet reconstruction.

Enable use of `FastJetOpts` in FastJetAlgoSub

---

offline/packages/TrackingDiagnostics/KshortReconstruction.cc
offline/packages/TrackingDiagnostics/KshortReconstruction.h

Adds the number of track states for the MVTX and INTT to tracks in the KshortReconstruction output tree. 

Add silicon track states to KshortReconstruction

---

generators/sphstarlight/StarLight_To_HepMc.cc
offline/packages/mbd/MbdEvent.cc
offline/packages/mbd/MbdEvent.h
offline/packages/mbd/MbdOutV2.h
offline/packages/mbd/MbdSig.cc
offline/packages/mbd/MbdSig.h

[comment]: Fixed bug where sometimes the time from the timing channel would be nan, ie, there was no hit that triggered the threshold in the time channel, but the charge was still reconstructed (from the noise samples).
[comment]: 

Fixed bug where tt sometimes had q, when it should be 0.

---

offline/packages/KFParticle_sPHENIX/KFParticle_Tools.cc
offline/packages/KFParticle_sPHENIX/KFParticle_Tools.h
offline/packages/KFParticle_sPHENIX/KFParticle_eventReconstruction.cc
offline/packages/KFParticle_sPHENIX/KFParticle_eventReconstruction.h
offline/packages/KFParticle_sPHENIX/KFParticle_nTuple.cc
offline/packages/KFParticle_sPHENIX/KFParticle_nTuple.h
offline/packages/KFParticle_sPHENIX/KFParticle_sPHENIX.cc
offline/packages/KFParticle_sPHENIX/KFParticle_sPHENIX.h
offline/packages/KFParticle_sPHENIX/KFParticle_truthAndDetTools.cc
offline/packages/KFParticle_sPHENIX/KFParticle_truthAndDetTools.h

Several new KFParticle features:
1.     User can require the primary vertex used in the reconstruction has a bunch crossing that matches the candidate daughter tracks (reduced background)
2.     User can require PID of kaons, pions and protons using dE/dx information. Uses Michaels parameterization of dE/dx bands as requires a match in a user defined fraction (default is 20%).
3.     Number of track states from each tracking subsystem saved in nTuple
4.     Some bug fixes for saving nDoF branches
5.     New branch that saves tracks full BCO for duplicate rejection
6.     Updates branch to save number of PVs in a bunch …

KFP: Updates for QM25

---

offline/framework/fun4allraw/Makefile.am
offline/framework/fun4allraw/MicromegasBcoMatchingInformation.h
offline/framework/fun4allraw/MicromegasBcoMatchingInformation_v1.cc
offline/framework/fun4allraw/MicromegasBcoMatchingInformation_v1.h
offline/framework/fun4allraw/MicromegasBcoMatchingInformation_v2.cc
offline/framework/fun4allraw/MicromegasBcoMatchingInformation_v2.h
offline/framework/fun4allraw/SingleMicromegasPoolInput_v1.h
offline/framework/fun4allraw/SingleMicromegasPoolInput_v2.cc
offline/framework/fun4allraw/SingleMicromegasPoolInput_v2.h

This is the TPOT pendant to https://github.com/sPHENIX-Collaboration/coresoftware/pull/3502
Kept the possibility to manually adjust the clock multiplier from upstream steering macro
Also (re-added) some ntuple-based evaluation of the clock synchronization, on top of existing QA histograms, disabled by default, and cleaned-up multiple version of the MicromegasBcoMatchingInformation class …

Tpot new hit format

---

offline/QA/Calorimeters/CaloFittingQA.cc
offline/QA/Calorimeters/CaloFittingQA.h

Added QA plot for ZS fraction for each calorimeter as a function of event multiplicity. Added protection for waveform vectors in simulation. Changed process_data function to extract full waveform for non ZS calorimeter channels.

Updated to CaloFittingQA to add new QA plots and vector protections

---

offline/QA/Jet/StructureinJets.cc
offline/QA/Jet/StructureinJets.h

This PR fixes a few bugs in the `StructureinJets` QA module.
Changes made:
- QA histogram manager is initialized before use
- `process_event` now returns `Fun4AllReturnCodes::EVENT_OK` instead of `exit(-1)` on errors
- Centrality calculation is now wrapped in the `isAA` flag
- All debugging statements are wrapped in verbosity checks
- All parameters (e.g. jet and track cuts) are now configurable, and several missing ones have been added
- An additional track cut on no. of tpc clusters in seed has been added
- 1D histograms for ptTrkSum and ptTrkSum/ptJet have now been added, histogram names are more reflective of content
- Projected ptTrkSum vs. ptJet vs. centrality histograms now …

Miscellaneous fixes to Structure in Jets QA

---

offline/packages/KFParticle_sPHENIX/KFParticle_nTuple.cc

If both useFakePrimaryVertex and constrainToPrimaryVertex are enabled in KFParticle_sPHENIX, the KFParticle_nTuple module tries to retrieve information from the vertex map about a vertex that might not exist, which causes a crash in any event with no primary vertex id 0 (the fake PV isn't added to the vertex map, and has an id of 0). This PR introduces safeguards that prevent this crash: the bunch crossing for a fake vertex is set to the typical error value of -100, and the track multiplicity is retrieved from the bunch crossing, not …

Fix KFParticle crash involving useFakePrimaryVertex and constrainToPrimaryVertex

---

offline/packages/trackbase/ResidualOutlierFinder.h
offline/packages/trackreco/PHActsTrkFitter.cc
offline/packages/trackreco/PHActsTrkFitter.h

@adfrawley 
This PR adds a diagnostic tool to the outlier finder for trying to help understand what the KF is actually doing and/or seeing. You can enable it by setting 
```
actsFit->useOutlierFinder(true);
```
in your macro. Right now it just puts the predicted local/global state position, local/global cluster position, chi2, and residual distance into an ntuple. We can always add more branches.

feat: outlier finder diagnostic ntuple

---

offline/packages/KFParticle_sPHENIX/KFParticle_DST.cc
offline/packages/KFParticle_sPHENIX/KFParticle_DST.h
offline/packages/KFParticle_sPHENIX/KFParticle_Tools.cc
offline/packages/KFParticle_sPHENIX/KFParticle_eventReconstruction.cc
offline/packages/KFParticle_sPHENIX/KFParticle_nTuple.cc
offline/packages/KFParticle_sPHENIX/KFParticle_nTuple.h
offline/packages/KFParticle_sPHENIX/KFParticle_sPHENIX.cc

Reverted code that chose mothers based on best fit to IP rather than lowest mass error. Caused loss in statistics due increased mis ID (I assume).
Also added new output branches for decay length in x/y plane, and predicted dE/dx values for different PID hypotheses

KFP: Reverted candidate selection and added new output branches

---

offline/packages/trackbase/ResidualOutlierFinder.h
offline/packages/trackreco/PHActsTrkFitter.cc

The predicted state has to be transformed to get the free parameters, evidently, instead of the usual enum lookup.

fix: acts free params in outlier finder

---

offline/framework/fun4allraw/Fun4AllStreamingInputManager.cc

This changes the exit strategy of the event combiner for each subsystem to only exit if the subsystem raw hit map is empty AND the gl1 raw hit map is empty. This mimics the current behavior in the TPC. The rationale for this change is that there are cases where the ROC by ROC processing exits early because a particular ROC has no data in it. This means there are incomplete runs produced as there are more GL1s to process but the ROC has no more hits for the time being. The most frequent example seems to be when the MVTX has a mixed state, so a FELIX stops sending data for a short period of time before the mixed state is recovered.
The current change should still allow for processing without the GL1 because, in the event of processing a subsystem alone, the GL1 raw hit map will necessarily …

fix: streaming event combining exit strategy

---

offline/packages/trackbase/ResidualOutlierFinder.h

The measurement parameters vector also doesn't work with the usual enums... unfortunately we can't get the distortion corrections into this but the surface transform will have to be sufficient.

fix: global cluster position

---

offline/packages/tpccalib/TpcSpaceChargeMatrixInversion.cc

gracefully exit, rather than crash, when no distortion matrices are loaded

fix_distortion_extrapolation_crash

---

offline/packages/particleflow/ParticleFlowReco.cc
offline/packages/particleflow/ParticleFlowReco.h

Since particle flow requires matching tracks to calorimeter clusters, only crossing zero tracks should be used.
Added a function to set on/off the crossing zero requirement, but only crossing zero is the default.

Added function to use only crossing zero tracks

---

offline/packages/TrackingDiagnostics/TrackResiduals.cc
offline/packages/trackreco/PHSimpleVertexFinder.cc
offline/packages/trackreco/PHSimpleVertexFinder.h

1. TrackResiduals module: fix the variable type specifier of the vertex id (which should be unsigned int) of tracks in residualtree 
2. Add a method in PHSimpleVertexFinder to set pp mode

Variable type in TTree branch in TrackResiduals & method to set pp mode in PHSimpleVertexFinder

---

offline/packages/tpccalib/TpcLaminationFitting.cc
offline/packages/tpccalib/TpcLaminationFitting.h

Added toggle to switch between seed functions for pp and AuAu. Will use different parameters in function for AuAu collisions vs pp collisions.
https://github.com/sPHENIX-Collaboration/macros/pull/1098

Lamination AuAu Toggle

---

offline/framework/fun4all/Fun4AllDstOutputManager.cc
offline/framework/fun4all/Fun4AllDstOutputManager.h
offline/framework/fun4all/Fun4AllOutputManager.h
offline/framework/fun4allraw/SingleTriggeredInput.cc

This PR adds the capability to remove phcompositenodes (and their subnodes) from saving in the dst output manager. Now that each packet is saved in its own node, stripping them by name would result in really longs lists. Now using out->StripCompositeNode("Packets") will strip all of them with a single line …

Strip composite node

---

offline/packages/intt/InttClusterizer.cc
offline/packages/micromegas/MicromegasDefs.cc
offline/packages/micromegas/MicromegasDefs.h
offline/packages/trackbase/ActsSurfaceMaps.cc
offline/packages/trackbase/InttDefs.cc
offline/packages/trackbase/InttDefs.h
offline/packages/trackbase/MvtxDefs.cc
offline/packages/trackbase/MvtxDefs.h
offline/packages/trackbase/TpcDefs.cc
offline/packages/trackbase/TpcDefs.h
offline/packages/trackbase/TrkrDefs.cc
offline/packages/trackbase/TrkrDefs.h

This PR
- cleans up cluster to crossing association in InttClusterizer: now that crossing is in the hitset key,  the association can be done once per cluster rather than per-link as before. This is more efficient. In fact the whole table has now become obsolete, for the same reason, and could be removed altogether (to be discussed with other tracking experts)
- it also adds a MvtxDefs::resetStrobe for cluster key, in preparation for additional cleanup in the Silicon seeder. 
- some cleanup in the various XXXDefs classes to better compartimentalize.
I'd like to commit these changes early before testing more significant changes in the Silicon Seeded/Clearner, to make sure that nothing is broken in the process. …

Cluster crossing association

---

offline/framework/fun4allraw/MvtxRawDefs.cc
offline/framework/fun4allraw/MvtxRawDefs.h

This PR will fix the method to read MVTX RO modes.
The current approach is to read the MVTX RO method from OCDB first and in case the
value is not found try with DAQ DB. the latest is never reached becasue the outcome of the
comparison was always true.
MVTX Offline recosntruction for Run25 must be redone after this PR implementation.

yc - fix reading MVTX RO mode. using isnan function for nan comparison

---

simulation/g4simulation/g4eval/SvtxEvaluator.cc

This PR adds the local x,y position of an svtxhit to the SvtxEvaluator ntuple output.

SvtxEvaluator - add svtxhit x,y info to ntuple 

---

offline/framework/fun4allraw/Fun4AllStreamingInputManager.cc
offline/framework/fun4allraw/Fun4AllStreamingInputManager.h
offline/framework/fun4allraw/SingleInttPoolInput.cc
offline/framework/fun4allraw/SingleInttPoolInput.h
offline/framework/fun4allraw/SingleMvtxPoolInput.cc

Apparently there was a gtm firmware update in late March that resulted in the clock difference between the GL1 and GTM delivered to the INTT being offset by an additional tick. This means that there were no raw hits created because the BCO matching range was too small. This PR fixes this with a hacked update based on the runnumber - we should think about whether or not this should go in the CDB longer term

fix: INTT/MVTX BCO range needs updating 

---

offline/packages/KFParticle_sPHENIX/KFParticle_DST.cc
offline/packages/KFParticle_sPHENIX/KFParticle_Tools.cc
offline/packages/KFParticle_sPHENIX/KFParticle_Tools.h
offline/packages/KFParticle_sPHENIX/KFParticle_eventReconstruction.cc
offline/packages/KFParticle_sPHENIX/KFParticle_sPHENIX.h

Various KFParticle updates:
1. KFParticle SvtxTrack container now retains track IDs for real tracks, while resonances are given IDs counting back from FLT_MAX to avoid accidentally using an ID that could already exist
2. Added electron ID using dE/dx. It's the same as the pion ID as the bands are basically on top of each other
3. Added more selections to match what was used in the offline QM D0 analysis. Testing on K-short reconstruction shows a few percent increase in yield with the same cuts after switching from accepting tracks by clusters on seeds to the number of states for ach subsystem. Run 53877 yield with …

KFP updates

---

offline/framework/fun4allraw/SingleMvtxPoolInput.cc

This PR remove rely on default 89us strobe width when the strobe information is not found
neither in the OCDB nor DAQ DB and exit SingleMvtxPool instead.

yc - exit in case strobe information is not found in the DB

---

offline/framework/fun4all/Fun4AllDstOutputManager.cc
offline/framework/fun4all/Fun4AllHistoManager.cc
offline/framework/fun4all/Fun4AllServer.cc
offline/framework/fun4all/TDirectoryHelper.cc

When saving DSTs every n Events (like our single stream processing) and the total number of events is a multiple of n, the Fun4AllServer::End() method which saves the Run Node to the last output file created a separate output file (if the files was moved). That's very unlikely to have ever happened. …

fix rare duplicate runnode saving at End(), clang-tidy fixes

---

offline/packages/trigger/MinimumBiasClassifier.cc
offline/packages/trigger/TriggerAnalyzer.cc

This moves the emulator work to the front of the decode triggers function (which will fail for simulation).
These also keeps the GL1RAWHIT changes that Cameron made
Also, I added an initialization other than the MBClassifier so there is no crashing

djl moved emulator code before the gl1 code

---

offline/packages/trackreco/PrelimDistortionCorrection.cc

An ALICEKalmanFilter refit of the TPC seeds is called in PrelimDistortionCorrection. This occasionally results in clusters being dropped from the seeds. It happens only for very low pT seeds ( < 100 MeV/c). If the number of clusters drops below 3 the seed cannot be fitted with a circle, and this results in nan values for some seed parameters further down the line.
This PR drops those non-viable seeds.
[comment]: <> ( In case this is a draft PR, e.g. for running checks using …

Add check in PrelimDistortionCorrection to remove seeds with < 3 clusters

---

offline/packages/tpc/TpcClusterMover.cc
offline/packages/tpc/TpcClusterMover.h

While tracking the origin of the recent nan messages from MakeSourceLinks, found two small optimizations of TpcClusterMover:
- avoid vector copy in ::processTrack by passing argument by reference rather than value
- proper use of emplace_back
Shoud have no impact on the result (but speed-up)

TpcClusterMover speedup

---

offline/packages/mvtx/Makefile.am
offline/packages/mvtx/MvtxClusterPruner.cc
offline/packages/mvtx/MvtxClusterPruner.h
offline/packages/mvtx/MvtxClusterizer.cc
offline/packages/mvtx/MvtxHitPruner.cc
offline/packages/mvtx/MvtxHitPruner.h

This PR
- cleans up MvtxHitPruner and MvtxClusterizer by removing "using namespace ..." directives
- introduces a new module to "prune" MVTX cluster, by remove identical clusters copied accross strobes, due to single hit single waveform overlaping with two strobes. 
Ultimately this should remove a significant number of duplicated seeds upstream, otherwise matched to the TPC and fitted by acts, then removed by the PHTrackCleaner module
The impact of this module on tracking efficiency and speed is still being evaluated.  …

Mvtx cluster pruner

---

offline/QA/Jet/DijetQA.cc

Does what it says on the tin.
Previously, the `DijetQA` module would emit warnings about the `GlobalVertexMap` node being missing if the node actually was missing OR if the node was empty. The severity of these two errors are different, and so the verbosity should reflect this. Also the error message should indicate if it's the node missing or if just empty.
This PR addresses these points.

Add clarity and fix verbosity of dijet warning about vertex node

---

offline/packages/trackreco/MakeSourceLinks.cc
offline/packages/trackreco/PHTpcDeltaZCorrection.cc
offline/packages/trackreco/PHTpcDeltaZCorrection.h

A lot of messages of type " ckey moved 156511082167402502 and global moved -nan -nan -nan" has appeared in reconstruction log files recently. This originates from track seed parameters being invalid (nan) when applying delta z corrections to clusters in PHTpcDeltaZCorrection.cc. With this PR, cluster delta_z correction is not calculated nor applied if the seed parameters used to calculate the track path length are invalid, thus 'fixing' the error message. The reason for the track seed parameters being invalid is being investigated independently.
Also improved MakeSourceLinks debug messages clarity. …

Fix deltaz correction

---

offline/QA/Jet/StructureinJets.cc
offline/QA/Jet/TrksInJetQA.cc
offline/QA/Jet/TrksInJetQABaseManager.cc
offline/QA/Jet/TrksInJetQAClustManager.cc
offline/QA/Jet/TrksInJetQAClustManager.h
offline/QA/Jet/TrksInJetQAConfig.h
offline/QA/Jet/TrksInJetQAHitManager.cc
offline/QA/Jet/TrksInJetQAHitManager.h

This PR fixes a number of small bugs in track-jet QA modules.
Changes:
Necessary for [macros#1096](https://github.com/sPHENIX-Collaboration/macros/pull/1096)

Miscellaneous track-jet QA fixes

---

offline/packages/mvtx/MvtxClusterizer.cc
offline/packages/mvtx/MvtxClusterizer.h

the clang build crashes since the removal of using namespace std in the MvtxClusterizer which uses a hokey fabs of a diff of unsigned ints to check for them being withing +-1. This PR replaces this with a more decent (and maybe faster) implementation which passes clang

fix clang build - replace adjacent check with correct use of abs

---

offline/packages/TrackingDiagnostics/TrackResiduals.cc
offline/packages/tpc/TpcGlobalPositionWrapper.cc
offline/packages/tpc/TpcGlobalPositionWrapper.h

This suppresses the warning for undefined crossing when we convert the seeds to tracks, for which we in general don't need/look at the crossing anyway. It is quite cumbersome in the cosmic analysis.

feat: suppress crossing warning for convert seeds

---

offline/packages/mvtx/MvtxClusterizer.cc

Fix is_adjacent checks in case ZClustering is not requested (was eron…ously removed during the last edit)
Also rewrote conditions to avoid static_cast and fabs entirely. This should be faster and still clang compliant.

Another fix to MVTXClusterizer is_adjacent code.

---

offline/framework/fun4allraw/SingleTriggeredInput.cc

Minor bugfix - the single input manager printed out a bogus misalignment message when the input was exhausted but some strange last event in the gl1 remains. That doesn't happen for all runs - it seems to happen only for earlier runs.

end gracefully without bogus misalignment message

---

offline/packages/mvtx/MvtxClusterizer.cc
offline/packages/trackbase/TrkrClusterContainer.h
offline/packages/trackbase/TrkrClusterContainerv4.cc
offline/packages/trackbase/TrkrClusterContainerv4.h
offline/packages/trackbase/TrkrClusterHitAssoc.h
offline/packages/trackbase/TrkrClusterHitAssocv3.cc
offline/packages/trackbase/TrkrClusterHitAssocv3.h
offline/packages/trackreco/PHActsSiliconSeeding.cc
offline/packages/trackreco/PHActsSiliconSeeding.h

This Pull Request allows to reset clusters and cluster-to-hit associations for a given subsystem from existing cluster container. (and cluster-hit association container)
Using this, MVTX clusters are first removed from the container before running the MVTX clusterizer. 
Similarily, silicon seeds are removed (deleted) from the silicon seed container, before running the silicon seeder. 
The immediate use case if for @xyu3 (Xu-Dong) to be able to re-run the MVTX clustering, silicon seeding, matching and track fitting, starting from raw hits for the MVTX but using existing clusters and TPC seeds from existing DSTs. 
This is much faster than having to re-run the full reconstruction, and allows to benefit from recent improvements …

Cluster reset

---

generators/PHPythia8/PHPythia8.cc
generators/PHPythia8/PHPythia8.h

Some harmless cleanup to PHPYthia8 class: 
- use std::unique_ptr to Pythia8 and hepMC objects so that they are automatically deleted
- initialize members are declaration rather than in constructor
- destructor is now default. 
Also added full event printout, for debugging, if PHPythia8 verbosity is high enough.

Phpythia8 cleanup

---

offline/packages/mvtx/MvtxHitPruner.cc
offline/packages/trackbase/TrkrHit.h
offline/packages/trackbase/TrkrHitv1.cc
offline/packages/trackbase/TrkrHitv1.h
offline/packages/trackbase/TrkrHitv2.cc
offline/packages/trackbase/TrkrHitv2.h

This PR: 
- adds const to TrkrHit accessors, as should be
- adds a CopyFrom method (similar to that of TrkrCluster), to hide implementation details in e.g. MvtxClustercleaner when cloning hits
- cleans up/speeds up MvtxHitPruner 

Trkr hit cleanup

---

offline/framework/fun4allraw/SingleMvtxPoolInput.cc
offline/framework/fun4allraw/SingleMvtxPoolInput.h

There is an overwrite in our pooling that means a user cant set the BCO ranges for filling the MVTX pool. This is intended for collision data but in standalone streaming mode for the MVTX we are filling each Fun4All with several strobes. This causes issues in making a hot pixel map so I added a flag to ignore this overwrite if we run standalone

CD: MVTX pooling update for standalone mode

---

offline/packages/tpc/TpcCombinedRawDataUnpacker.h

While digging into memory issues in the tpc unpacker and raw hit file readback, I learned that the baseline correction is turned on by default in the data reconstruction. According to @bogui56 this should not be the case, so this turns the flag off when the read zero suppressed data flag is turned on

fix: turn baseline correction off

---

offline/packages/tpc/TpcGlobalPositionWrapper.cc
offline/packages/tpc/TpcGlobalPositionWrapper.h
offline/packages/trackreco/PHActsTrkFitter.cc
offline/packages/trackreco/PHActsTrkFitter.h

1. Add setter of SvtxTrackSeedContainer name in PHActsTrkFitter
2. Add some options to disable distortion correction so that we can decide to disable some of the distortion corrections in downstream evaluation module
Both two changes should be transparent to users and have no impact on normal tracking

add some setters for PHActsTrkFitter and TpcGlobalPositionWrapper

---

offline/framework/frog/FROG.cc
offline/framework/frog/FROG.h
offline/framework/phool/PHNodeIOManager.cc

The way the split level and buffersize setting was implemented lead to the first node setting the default for all subsequent nodes. It doesn't affect the default setting but if we want to set levels on a node by node basis we need this patch

Fix splitlevel handling

---

offline/packages/mbd/MbdEvent.cc
offline/packages/mbd/MbdOut.cc
offline/packages/mbd/MbdOut.h
offline/packages/mbd/MbdPmtContainer.cc
offline/packages/mbd/MbdPmtContainer.h

[comment]: Added Print() method to containers. Also, now saving all CDB calib root files with mbd_<calibname>-<run>.root.

added Print() to containers, make uniform the CDB calib names

---

offline/packages/trackreco/PHSiliconTpcTrackMatching.cc
offline/packages/trackreco/PHSiliconTpcTrackMatching.h

Update PHSiliconTpcTrackMatching Module as discussed in tracking software meeting on May 13th.
Modification on matching window will be another PR to macro repo
1. In ``findEtaPhiMatches`` function, only do Eta/Phi/x/y matching, remove z matching
2. Change ``checkCrossingMatches`` function to ``checkZMatches`` function
If ``_pp_mode=true``, do crossing correction on z position of TPC seed, then match TPC seed corrected z and Silicon seed z using function as well as a threshold cut (|dz|<10 cm by default)
If ``_pp_mode=false``, assume …

update PHSiliconTpcTrackMatching module

---

offline/framework/ffamodules/CDBInterface.cc
offline/framework/ffamodules/CDBInterface.h

This PR adds a search for <domain>_default so we can have default calibrations which do not interfere with runwise calibrations (where a missing calibration tells us that run is not calibrated). The cdb instance has a flag
CDBInterface::instance()->Disable_default()
which disables the loading of default calibrations so we can enforce that every processed run has all calibrations …

add automatic default for payloads

---

offline/packages/tpccalib/PHTpcResiduals.cc
offline/packages/tpccalib/TpcSpaceChargeReconstruction.cc

A bug was introduce in the distortion matrices calculation when switching from using rdelta_phi as a parameter to delta_phi.
This resulted in the matrix not being symetric (though still invertible).
Now fixed.
@xyu3
Unfortunately it means that you would need to regenerate such matrices and the corresponding inversion. 
Hopefully this should stabilize somewhat the calculation of delta_r. …

Fixed filling thedistortion matrices.

---

offline/packages/jetbackground/JetBackgroundCut.cc
offline/packages/jetbase/ClusterJetInput.cc
offline/packages/jetbase/TowerJetInput.cc

As discussed in the sim and software meeting on 2025/06/03, this PR modifies JetInput derived classes to treat events with no z vertex as having a z vertex at 0.

Change JetInput derived classes to treat events without zvtx as 0 zvtx

---

offline/packages/TrackingDiagnostics/TrackResiduals.cc
offline/packages/TrackingDiagnostics/TrackResiduals.h

This removes some branches from the TrackResiduals trees, and hides some others behind additional flags for expert use. It reduces the size of the residualtree by about 50%. Unfortunately the cluster tree is still large, which I think is just a result of there being so many clusters

fix: remove some weight from TrackResiduals

---

offline/packages/KFParticle_sPHENIX/KFParticle_truthAndDetTools.cc

@pinkenburg @jdosbo there was an extra print statement left in some KFP code that Alex found this morning. I've removed it. This is a minimal change so feel free to merge if we want to keep Jenkins available for people. I tested it compiled with gcc but not clang

Removed extraneous print statements

---

offline/framework/fun4allraw/Fun4AllStreamingInputManager.cc
offline/framework/fun4allraw/SingleInttPoolInput.cc
offline/framework/fun4allraw/SingleInttPoolInput.h
offline/framework/fun4allraw/SingleStreamingInput.h

Adding feature to turn ON/OFF big BCO skip based on GL1 BCO value. This is necessary for INTT local run without GL1 combiner. It will not harm any current combiner since standalone flag is false by default ; bool m_StandaloneMode{false}

Ignore BCO skip in INTT standalone mode

---

offline/packages/trackreco/PHActsTrkFitter.h

This change makes direct navigation the default for the Acts track fitter. Changing back to default navigation can be done from the macro. 

PHActsTrkFitter now uses direct navigation by default.

---

offline/framework/fun4allraw/TpcTimeFrameBuilder.cc

Support TPC hit format `IDTPCFEEV6` in offline event building in preparation for the digital current firmware that is similar to the online decoder https://github.com/sPHENIX-Collaboration/online_distribution/pull/199 
@osbornjd 
Currently digital current data are not yet enabled. But this is needed to process cosmic run 67442+ starting 2025-06-13 23:04:00  …

Support IDTPCFEEV6 with TPC digital current firmware

---

offline/framework/fun4allraw/SingleTriggeredInput.cc

Found and fixed the reason for the upper 32 bit set in the clock diff. The effect was already handled before, so this won't result in more events from the event combining. But one less warning in the log. I left the warning for this case in (the clock diff exceeding 32 bits) - if it still shows up we have another problem …

Fix rollover

---

offline/packages/TrackingDiagnostics/TrackSeedTrackMapConverter.cc

Allows multiple track maps to be created in the converter for QA purposes

fix: multiple track maps in converter

---

offline/QA/Calorimeters/CaloValid.cc
offline/QA/Calorimeters/CaloValid.h

Add code to: check runnumber and update m_species flag in CaloValid, set verbosity for CaloValid.
Add code that gets the runnumber during CaloValid::InitRun.
The runnumber is compared to run ranges defined in RunnumberRange.h 
This sets the m_species (pp, AuAu) flag so the correct charge scaledowns are applied for correlation QA plots.
Additionally added verbosity method to CaloValid.h
Currently the only couts it applies to are ones that announce the species, lack of a RunHeader node, or if the runnumber is outside of the range defined in RunnumberRange.h.
These are shown if verbosity>0

Add code to: check runnumber and update m_species flag in CaloValid, set verbosity for CaloValid.

---

offline/packages/CaloReco/CaloTowerBuilder.cc

Add the SEPD template CDB payload name. this doesn't change the default production yet(a change to the [Calo_Fitting.C](https://github.com/sPHENIX-Collaboration/macros/blob/master/common/Calo_Fitting.C) would be needed for changing the production). 
change the default method for SEPD fitting to be template.

sEPD template fit as default

---

offline/packages/trackreco/PHActsTrkFitter.cc

This got deprecated at one point, this PR fixes the ability to ignore a layer in the fit

fix: ignoring layer in track fitting

---

offline/framework/fun4allraw/SingleMicromegasPoolInput_v2.cc

When using TH1I, for long runs it can happen that more than MAX_INT (2147483647) waveforms are recorded, and saturate the histogram, rendeing the offline QA ratio plots incorrect. 
TH1L should fix that for the time being.

use TH1L histograms, in order not to reach max_int when counting wavefirns

---

offline/packages/KFParticle_sPHENIX/KFParticle_Container.cc
offline/packages/KFParticle_sPHENIX/KFParticle_sPHENIX.h
offline/packages/KFParticle_sPHENIX/KFParticle_truthAndDetTools.cc
offline/packages/KFParticle_sPHENIX/KFParticle_truthAndDetTools.h

Updated bunch crossing return for the vertex to be able to use the global vertex. This had been forgotten before and causes a crash currently when using the global vertex
Updated the KFParticle copy container to use the iterator rather than track ID as we can have candidates that share the same track and hence cant be added 

CD: KFP updates to vtx and container

---

offline/packages/trackreco/Makefile.am
offline/packages/trackreco/PHGenFitTrkFitter.cc
offline/packages/trackreco/PHGenFitTrkFitter.h
offline/packages/trackreco/PHTrackPruner.cc
offline/packages/trackreco/PHTrackPruner.h

Add a new module ``PHTrackPruner`` which aims to be applied after Acts track fit and track cleaner. We can use this module to apply some selections on tracks and further select good tracks. Put the associated SvtxTrackSeed of good tracks into a new SvtxTrackSeedMap container which can be used for silicon only track fit/ silicon-tpc track fit etc.

Add a new module for pruning SvtxSeedMap and track refit

---

calibrations/tpc/generator/AnnularFieldSim.cc

declaring arrays with variable size is illegal under C++ (sadly g++ allows it but clang does not)

compile with clang

---

offline/packages/TrackingDiagnostics/TrackResiduals.cc

This PR fixes a bug that used the live trigger vector instead of the scaled trigger vector in the filling of the fired trigger bits of the tracking diagnostic workflow

fix: use scaled instead of live trigger vector

---

offline/framework/ffarawmodules/ClockDiffCheck.cc
offline/framework/ffarawobjects/OfflinePacket.h
offline/framework/ffarawobjects/OfflinePacketv1.cc
offline/framework/fun4allraw/SingleTriggeredInput.cc

This should prevent quite a few of these seb dropouts. The decoder cannot deal with corrupt events and hands back an invalid (random?) clock. One has to check the packet status after an ivalue call to check for corrupt packets. The drooping of those packets (marked with status OFFline_paket::PACKET_CORRUPT) works but the clock diff check chokes a bit and drops the same packet two events later. That needs to be looked at but this PR should remedy a lot of those dropped …

Seb clock skip fix

---

offline/packages/mbd/MbdEvent.cc
offline/packages/mbd/MbdReco.cc

The new offline packets are nodes, so they will always exist, even if they are empty. This PR adds a check that packets 1001,1002 actually have content before proceeding. That should take care of the multi GB logs for the early run2pp runs where we have yet another problem with the gl1 (though it does not fix the gl1 issue) …

check for offline packets

---

offline/framework/fun4allraw/TpcTimeFrameBuilder.cc
offline/framework/fun4allraw/TpcTimeFrameBuilder.h

Two changes in the TPC Event Builder: 
1. Reinterpret GTM mode bits to mode numbers as used in v46+ firmware. Previous and new definition are documented in the header file. Nonetheless, it is expected to be back compatible with how we run in the past. But it is needed change so new digital current mode numbers are not misinterpreted as heartbeats
2. Make the code more robust to junk data arriving BEFORE the start of run sequence in GTM, e.g. due to lingering data in the DMA buffer  …

Two changes in the TPC Event Builder

---

simulation/g4simulation/g4jets/TruthJetInput.cc

Updates the truth jet reconstruction to use GetSPHENIXPrimaryParticleRange() instead of GetPrimaryParticleRange(). This will no longer work on simulations produced before the new sPHENIX primary particle definition was implemented 

updating truth jet reco for new sphenix primary particles

---

offline/packages/trackreco/PHSiliconSeedMerger.cc
offline/packages/trackreco/PHSiliconSeedMerger.h

This PR clang-formats the silicon seed merger and checks that the two seeds being merged have the same strobe ID. Interestingly over 100 events this does not change the number of seeds at all - but for completeness it should be there.

fix: check strobe in silicon seed merger

---

calibrations/calorimeter/calo_tower_slope/HCalCosmics.cc
calibrations/calorimeter/calo_tower_slope/HCalCosmics.h

Added histograms of peak time distributions per tower for cosmic muons [name of the histogram: h_towertime_hist] that pass the topological selection cuts. These histograms are included as part of the cosmic production outputs and are useful for time-based calibration.

Added tower time histograms of cosmic muons

---

offline/packages/tpccalib/TpcSpaceChargeMatrixInversion.cc

This fixes the reduced (2x2) distortion matrix inversion, for more detailed comparisons to direct fits performed by Xudong and to full matrix inversion. 
- use TpcSpaceChargeMatrixContainerv2
- set n_coord = 2 for the reduced matrix inversions.

Reduced matrix inversion fixes

---

offline/packages/PHField/PHField2D.cc
offline/packages/PHField/PHField2D.h
offline/packages/PHField/PHField3DCartesian.cc
offline/packages/PHField/PHField3DCartesian.h

This PR adds a std::mutex lock to PHField3DCartesian::GetFieldValue() and PHField2D::GetFieldValue(), to prevent data race when accessing the internal (mutable) cache from multiple thread. 
This is part of an ongoing effort initiated by @KvapilJ (Jakub) to parallelize the time consuming parts of PHSimpleKFProp
(to be discussed separately with @pinkenburg and others)
Since the current code uses PHField only inside one single thread, this should be transparent to all. 
I have tested it on a local paralellized version of the reconstruction loop.
[comment]: <> ( What does this PR do? Linking to talk in software meeting …

Phfield mutex

---

offline/packages/CaloReco/CaloTowerStatus.cc
offline/packages/CaloReco/CaloTowerStatus.h

This PR fixes a breakage that occurs when cdb attempts to access the `sigma` field for a simulation run.
- Added a flag `isSim` that uses the z_score information only if run is from data (not sim). 
- For the simulation runs, the default approach of checking the `hotMap_val` is used. 
Related PR in macros: https://github.com/sPHENIX-Collaboration/macros/pull/1161

Fix - CaloTowerStatus Sim

---

calibrations/calorimeter/calo_tower_slope/HCalCosmics.cc
calibrations/calorimeter/calo_tower_slope/HCalCosmics.h

- Added per-tower histograms of raw ADC values for cosmic muons and included average ADC distributions across all towers
- Introduced topological cuts based on neighboring tower ADC values to select vertical muons.
- Made slight modifications to improve readability of the code.

Added MIP raw ADC histograms per tower

---

offline/packages/trackreco/PHSimpleKFProp.cc
offline/packages/trackreco/PHSimpleKFProp.h

This PR includes some small optimizations to KFProp. 
The most significant change is to remove duplicates from the cluster key chains using std::unique, which is more efficient than the later ghost rejection. 
This is part of an ongoing effort initiated by @KvapilJ (Jakub) to parallelize the time consuming parts of PHSimpleKFProp
(to be discussed separately with @pinkenburg and others) …

Kfprop optimization

---

offline/QA/KFParticle/QAKFParticle.cc
offline/QA/KFParticle/QAKFParticle.h

Adds mass histograms for crossing = 0, crossing != 0, and 3 different trigger conditions to be able to view how each of those affect a given decay. Should work for any KFP reconstruction (e.g. K_S0, D0, etc.) so long as the KFParticle_Container and SvtxTrackMap are saved to the node tree. Ability to select different trigger conditions than these 3 coming soon

Adding Trigger and Crossing Inv Mass Histograms to KFPQA

---

offline/packages/jetbackground/TowerBackground.h
offline/packages/jetbackground/TowerBackgroundv1.h

This PR adds some forgotten methods to TowerBackgroundv1

add forgotten flow methods, remove get_nTowersUsedForFlow()

---

offline/framework/fun4allraw/SingleTpcTimeFrameInput.cc
offline/framework/fun4allraw/SingleTpcTimeFrameInput.h
offline/framework/fun4allraw/TpcTimeFrameBuilder.cc
offline/framework/fun4allraw/TpcTimeFrameBuilder.h

Decoding the digital current data in offline TPC event builder, which prints DC packets like the following when Verbosity is enabled, and add decoding statistics to the event builder QA histograms. 
```
void TpcTimeFrameBuilder::process_fee_data_digital_current(const unsigned int&, std::deque<short unsigned int>&)	- : received digital current packet 	- from FEE 8
- pkt_length = 39
- sampa_address = 3
- channel = 103
- bx_timestamp = 0x1b9cb
- current:	[0] = 4804	[1] = 5380	[2] = 4612	[3] = 4534	[4] = 12389	[5] = 5585	[6] = 4824	[7] = …
```

Processing TPC digital current data in offline event builder

---

offline/packages/CaloReco/CaloTowerBuilder.cc
offline/packages/CaloReco/CaloTowerBuilder.h
offline/packages/CaloReco/CaloWaveformProcessing.cc
offline/packages/CaloReco/CaloWaveformProcessing.h

The returned vector from the onnx was not compatible with the vector from the template fit (3dim instead of 5dim). This PR patches the onnx return so it can be used without special treatment by the calo tower builder, it's values are fine for processing via Calo_Calib

make onnx return vector compatible with template fit return

---

offline/packages/PHField/PHField.h
offline/packages/PHField/PHField2D.cc
offline/packages/PHField/PHField2D.h
offline/packages/PHField/PHField3DCartesian.cc
offline/packages/PHField/PHField3DCartesian.h
offline/packages/trackreco/ALICEKF.cc
offline/packages/trackreco/PHSimpleKFProp.cc

This PR removes the use of a mutex of relevant PHField classes, needed for thread safety, due to significant overhead when the number of threads is large.
Instead add a GetFieldValue_nocache() method, that is thread safe (reentrant), and is the one to be used in multithreaded enviroment. 
In PHSimpleKFProp and ALICEKF, the cached version of GetFieldValue is used for thread number 0; and the uncached version is used for any other thread >0. In any case the cache was always missed in such cases. …

Phfield optimization

---

simulation/g4simulation/g4waveformsim/CaloWaveformSim.cc
simulation/g4simulation/g4waveformsim/CaloWaveformSim.h

1.  This PR refactor the MC calibration that used to applied in the process calo_calib stage to the waveform simulation step.
2. Waveform sim with the time decalibration option now reads the MC_meantime and the the G4Hit_time = 0 puts the peak at Data_meantime - MC_meantime.

Waveformsim: refactor the MC calibration, update time de-calibration

---

calibrations/calorimeter/calo_cdb/filter-datasets.cc

Bug fix:
- Delimiter between dataset and run should be "_", not "-" to be consistent with the output from the genStatus.cc module.
- Now the same runs aren't flagged again if they already have a latest CDB map.

Bug Fix: CaloCDB Filter-Datasets Delimiter

---

offline/packages/PHField/PHField3DCartesian.cc
offline/packages/PHField/PHFieldConfig.h
offline/packages/PHField/PHFieldConfigv1.cc
offline/packages/PHField/PHFieldConfigv1.h
offline/packages/PHField/PHFieldConfigv2.cc
offline/packages/PHField/PHFieldConfigv2.h
offline/packages/trackreco/PHCASeeding.cc
offline/packages/trackreco/PHCASeeding.h
offline/packages/trackreco/PHSimpleKFProp.cc
offline/packages/trackreco/PHSimpleKFProp.h
offline/packages/trackreco/PrelimDistortionCorrection.cc
offline/packages/trackreco/PrelimDistortionCorrection.h
offline/packages/trackreco/PrelimDistortionCorrectionAuAu.cc
offline/packages/trackreco/PrelimDistortionCorrectionAuAu.h

This pull request is a first step towards having only one field map loaded at the seeding stage (right now we have 2, even 3 for a short time).
1/ in PHCASeeder, the loaded field map (as well as the ALICEKF fitter) are actually not used, and deleted immediately after being created. All of this is now removed. 
2/ in PHSimpleKFProp, and PrelimDistortionCorrection, the modules now try to load the field map stored on the node tree first, provided that it is found and that the field map configuration matches what is requested. 
if no field map is found, the module will create one and store it, together with the configuration, on the node tree.
if the field map is found but the configuration differ, the module will use an …

More phfield optimization

---

offline/packages/jetbackground/RetowerCEMC.cc

The JetReco module currently crashes without a clear warning when input calorimeter nodes (e.g., from calo DSTs) are unavailable. This issue tends to arise when working with global-only DSTs—particularly in simulation—where the calo DSTs may not be included initially. It’s easy to overlook this when migrating to jet reconstruction. Adding an explicit check with a warning message helps clarify the source of the crash.

add warning when required calorimeter nodes are missing

---

generators/phhepmc/Fun4AllHepMCInputManager.cc

Cleanup - there was a duplicate setting of the embedding id in the Fun4AllHepMCInputManager ctor and the PHHepMCGenHelper initializer to the same value (0). This should not change any behavior

embedding id is set in PHHepMCGenHelper

---

offline/packages/KFParticle_sPHENIX/KFParticle_Tools.h
offline/packages/KFParticle_sPHENIX/KFParticle_truthAndDetTools.cc

If KFParticle is run with m_dont_use_global_vertex set to true, filling primary vertex info in KFParticle_Ntuple will break if a GlobalVertexMap is not provided. This happens because a new KFParticle_Tools object is instantiated in allPVInfo that defaults to expecting a GlobalVertexMap.

KFP - fix in allPvInfo

---

offline/packages/tpc/LaserClusterizer.cc
offline/packages/tpc/LaserClusterizer.h
offline/packages/tpc/LaserEventIdentifier.cc
offline/packages/tpc/LaserEventIdentifier.h
offline/packages/tpccalib/TpcCentralMembraneMatching.cc
offline/packages/tpccalib/TpcCentralMembraneMatching.h
offline/packages/trackbase/LaserCluster.h
offline/packages/trackbase/LaserClusterv2.cc
offline/packages/trackbase/LaserClusterv2.h
offline/packages/trackbase/LaserClusterv2LinkDef.h
offline/packages/trackbase/Makefile.am

New code to fit laser clusters. This does a better job of obtaining the parameter centroids and than the previous weighted average, which can be toggled on/off with an included function, which has a toggle in Trkr_GlobalVariables.C. Also, added protection for laser event identifying with new GL1 bit so that it's only used in runs after the bit was added.
[comment]: <> ( In case this is a draft PR, e.g. for running checks using Jenkins, please make the pull request as a draft: https://github.blog/2019-02-14-introducing-draft-pull-request …

Laser cluster fitting

---

offline/packages/KFParticle_sPHENIX/KFParticle_DST.cc
offline/packages/KFParticle_sPHENIX/KFParticle_Tools.cc
offline/packages/KFParticle_sPHENIX/KFParticle_Tools.h
offline/packages/KFParticle_sPHENIX/KFParticle_nTuple.cc
offline/packages/KFParticle_sPHENIX/KFParticle_nTuple.h
offline/packages/KFParticle_sPHENIX/KFParticle_sPHENIX.h
offline/packages/KFParticle_sPHENIX/KFParticle_truthAndDetTools.cc
offline/packages/KFParticle_sPHENIX/KFParticle_truthAndDetTools.h

Several changes on KFParticle 
1. In the previous KFParticle, if multiple mother/intermediate particle is reconstructed in an event, trackmap need to be inserted multiple times. Due to duplicate keys, there are lots of warnings. In the current update, I add a check before ``insertWithKey`` to avoid warnings.
2. In track-calo matching study, track states at calo radius will be created, which do not have trkr cluster associated with. Therefore, if we call ``getGlobalPosition`` function, there will have many warnings, like surface not …

KFP updates: DST, vertex, track-calo matching

---

offline/packages/CaloBase/TowerInfoDefs.cc
offline/packages/CaloBase/TowerInfoDefs.h

- Add getEMCalSectorIB: EMCal Mapping from tower index to (sector, interface board)
This PR adds the functionality to map the EMCal tower index to its respective sector and interface board number. Below is a verification plot that shows the result of the mapping.

Add EMCal Mapping: towerIndex -> (sector, ib)

---

offline/packages/tpc/TpcCombinedRawDataUnpacker.cc
offline/packages/tpc/TpcCombinedRawDataUnpacker.h

This adds the zero suppression threshold as a cdb object to be read in at the hit unpacker level, and applied on a region by region basis. To be tested with the actually cdb files, starting this PR now to get jenkins goign

feat: tpc variable zs thresholds

---

calibrations/tpc/fillDigitalCurrentMaps/readDigitalCurrents.cc
offline/QA/EventDisplay/TrackerEventDisplay.cc
offline/QA/Tracking/TpcClusterQA.cc
offline/packages/TrackingDiagnostics/TrackResiduals.cc
offline/packages/TrackingDiagnostics/TrkrNtuplizer.cc
offline/packages/tpc/LaserClusterizer.cc
offline/packages/tpc/Tpc3DClusterizer.cc
offline/packages/tpc/TpcClusterizer.cc
offline/packages/tpc/TpcCombinedRawDataUnpacker.cc
offline/packages/tpc/TpcCombinedRawDataUnpackerDebug.cc
offline/packages/tpc/TpcSimpleClusterizer.cc
offline/packages/tpccalib/TpcDirectLaserReconstruction.cc
simulation/g4simulation/g4detectors/PHG4TpcCylinderGeom.cc
simulation/g4simulation/g4detectors/PHG4TpcCylinderGeom.h
simulation/g4simulation/g4eval/SvtxEvaluator.cc
simulation/g4simulation/g4eval/SvtxTruthEval.cc
simulation/g4simulation/g4tpc/Makefile.am
simulation/g4simulation/g4tpc/PHG4TpcDetector.cc
simulation/g4simulation/g4tpc/PHG4TpcDetector.h
simulation/g4simulation/g4tpc/PHG4TpcPadBaselineShift.cc
simulation/g4simulation/g4tpc/PHG4TpcPadPlaneReadout.cc
simulation/g4simulation/g4tpc/PHG4TpcPadPlaneReadout.h
simulation/g4simulation/g4tpc/TpcClusterBuilder.cc

This reverts the tpc fee map coresoftware changes, and adjusts modules that have since been modified to call the old `get_phi` function from the reconstruction. Need to do ample testing and cdb file orchestration still, but jenkins can get going on this

fix: tpc fee map rollback

---

offline/packages/TrackingDiagnostics/TrkrNtuplizer.cc

The build failed because I merged Christof's dE/dx changes without pulling them and retesting the channel map revert. This fixes the TrackingDiagnostics build

fix: switch to old channel map

---

offline/packages/trackreco/ALICEKF.cc
offline/packages/trackreco/ALICEKF.h
offline/packages/trackreco/MakeActsGeometry.cc
offline/packages/trackreco/PHCosmicsFilter.h
offline/packages/trackreco/PHGenFitTrkFitter.cc
offline/packages/trackreco/PHLineLaserReco.h
offline/packages/trackreco/PHRaveVertexing.cc
offline/packages/trackreco/PHSimpleKFProp.cc
offline/packages/trackreco/PHSimpleKFProp.h
offline/packages/trackreco/PHStreakFinder.h
offline/packages/trackreco/PrelimDistortionCorrection.cc
offline/packages/trackreco/PrelimDistortionCorrection.h
offline/packages/trackreco/PrelimDistortionCorrectionAuAu.cc
offline/packages/trackreco/PrelimDistortionCorrectionAuAu.h

As discussed on Monday, this cleans up loading PHField from our various subsysreco.
- MakeActsGeometry is now responsible for building the magnetic field with the proper configuration as either setup in the macro or found on the node tree (for instance when runing simulations). 
- PHSimpleKFProp, PrelimDistortionCorrection, PHGenfitTrkFitter now gets whatever is on the node tree
- all the subsysreco specific flags to set the map name, or implement constant magnetic field are now Noop. They will be removed once the corresponding macros are updated. 
- it is still possible to centraly use a constant magnetic field, by setting G4MAGNET::magfield and G4MAGNET::magfield_tracking to e.g. "1.4" in the calling macro. …

Phfield cleanup

---

offline/packages/KFParticle_sPHENIX/KFParticle_nTuple.h
offline/packages/KFParticle_sPHENIX/KFParticle_truthAndDetTools.cc
offline/packages/KFParticle_sPHENIX/KFParticle_truthAndDetTools.h

In this PR:
- Renamed  `get_detailed_tracking()` to `GetDetailedTracking()` to be more consistent with other public functions. This function is now defined in `KFParticle_nTuple.h` so that it can also update `m_detector_info`. 
- Implemented Cameron's comments on previous PR; users will now automatically get all detector info when `GetDetailedTracking()` is used to set `m_get_detailed_tracking` to `true`. 
This PR will allow the user to specify what detector info they would like KFP to store.
[comment]: <> ( In case this is a draft PR, …

Improved--flexibility in KFP for detector info

---

offline/QA/Tracking/TpcSeedsQA.cc

Finally managed to clear my eyes and find this hidden single letter typo in the qa histogram name that was causing the tpc seeds qa to not properly draw

fix:histoname typo

---

offline/packages/PHField/PHFieldConfig.cc
offline/packages/PHField/PHFieldConfig.h
offline/packages/PHField/PHFieldInterpolated.cc
offline/packages/PHField/PHFieldInterpolated.h
offline/packages/PHField/PHFieldUtility.cc

* modified aditional classes to load Interpolated fieldmap
* interpolated fieldmap gets grid information on load
* fixed hashing computation when number of gridpoints is even
* per-thread, thread-safe caching for multithreaded access

Interpolated fieldmap relevant changes

---

offline/QA/Global/GlobalQA.cc
offline/QA/Global/GlobalQA.h

The global QA was not filling histograms because some trigger decision code was added that prevents anything from being filled. This PR removes those trigger decision ifs so that the histograms are filled again.

fix: trigger decision bug in global qa

---

offline/packages/Skimmers/CaloPacket/CaloPacketSkimmer.cc
offline/packages/Skimmers/CaloPacket/CaloPacketSkimmer.h
offline/packages/Skimmers/CaloPacket/Makefile.am

add two histogram counting for kept events and skipped events

Calo packet skimmer histogram counting

---

offline/packages/trackbase_historic/TrackAnalysisUtils.cc
offline/packages/trackbase_historic/TrackAnalysisUtils.h

Something about the new dedx function without the calibration has changed the behavior significantly. This changes the consolidated function to use the old version until we get the calibrations into the cdb, after which we can easily switch.

fix: use uncalib dedx

---

offline/framework/ffaobjects/EventHeaderv1.cc
offline/framework/ffaobjects/RunHeaderv1.cc
offline/framework/ffaobjects/RunHeaderv1.h
offline/framework/ffaobjects/SyncObject.h
offline/framework/ffaobjects/SyncObjectv1.cc
offline/framework/ffaobjects/SyncObjectv1.h

This PR makes the SyncObject::EventNUmber() method public. It can be used to extract the event number from our DSTs to set the first and last event in our datasets table

make SyncObject::EventNumber() public

---

offline/packages/NodeDump/DumpEpdGeom.cc
offline/packages/NodeDump/DumpMbdVertexMap.h
offline/packages/NodeDump/DumpTowerInfoContainer.cc
offline/packages/NodeDump/DumpTruthVertexMap.cc
offline/packages/NodeDump/DumpTruthVertexMap.h
offline/packages/NodeDump/Makefile.am
offline/packages/NodeDump/PHNodeDump.cc
simulation/g4simulation/g4epd/PHG4EPDModuleReco.cc
simulation/g4simulation/g4epd/PHG4EPDModuleReco.h

This PR copies the phi and phi0 initialization used in the sepdreco code (which just derives them from dividing 4pi into phi slices instead of using long magic floats). When running the diff, some phi angles show a deviation of 10^-8 which is irrelevant and does not affect the results for the significant digits. …

Fix sepd simgeo

---

offline/packages/trackbase_historic/Makefile.am
offline/packages/trackbase_historic/TrackAnalysisUtils.cc
offline/packages/trackbase_historic/TrackAnalysisUtils.h

Adds the crossing correction to the z position in the calibrated dedx function

feat: add crossing correction to z

---

offline/packages/trackreco/PHActsSiliconSeeding.cc
offline/packages/trackreco/PHActsSiliconSeeding.h

This PR improves the matching of the INTT to the MVTX triplet by
1. Doing a "pre-projection" to the layer radius to determine an approximate phi for which to look up surface candidates
2. Refitting the track if a cluster is added to the track prior to doing the next projection
See these slides for more info
https://indico.bnl.gov/event/29457/contributions/113608/attachments/64738/111228/silicon_seeding.pdf

feat: improve intt matching in silicon seeding

---

calibrations/calorimeter/calo_emc_pi0_tbt/pi0EtaByEta.cc

Previously, the `ptClusMax` cut was only applied to the first cluster (`clus_pt`) in the pair selection logic, while the second cluster (`clus2_pt`) only had a lower cut (`pt2ClusCut`) applied. This fix ensures both clusters are subject to the upper `ptClusMax` cut, improving selection consistency.
Updated the condition:
`if (clus2_pt < pt2ClusCut || clus2_pt > ptClusMax)`
This removes a redundant check on `clus_pt` and properly applies the upper cut to `clus2_pt` as intended. …

pi0EtaByEta.cc: Apply ptClusMax cut, both clusters

---

offline/packages/jetbackground/JetBackgroundCut.cc
offline/packages/jetbackground/JetBackgroundCut.h

This commit refactors the `JetBackgroundCut` module to enhance its flexibility and code clarity without altering the default behavior.
Key changes include:
- Configurable Inputs: Introduced setter methods (`set_input_cemc_tower_node` and `set_input_ohcal_tower_node`) to allow users to specify the input tower node names. The module now retrieves tower containers using these configurable names instead of hardcoded strings. The default node names remain the same, ensuring backward compatibility.
- Improved Readability: Replaced hardcoded integer values for jet component sources with their respective `Jet::SRC` enum members (e.g., `Jet::CEMC_TOWERINFO_RETOWER`, `Jet::HCALOUT_TOWERINFO`). …

Feat(JetBackgroundCut): Improve input flexibility and readability

---

offline/packages/trackreco/PHActsTrkFitter.cc
offline/packages/trackreco/PHActsTrkFitter.h
offline/packages/trackreco/PHActsVertexPropagator.cc
offline/packages/trackreco/PHActsVertexPropagator.h

The Acts fitter puts an SvtxTrackMap and a map containing Acts trajectories on the nodetree. This was historical before we had simple conversion code, which we do now. Having two output objects from a single reconstruction module is bad practice and makes the downstream reconstruction cumbersome - this PR removes the trajectory object from use and should simplify the downstream EDM handling. I checked that the constructed object in the vertex propagation is identical to that output from the track fitting, so this should result in no change to any performance …

refactor: remove extra acts edm object from node tree

---

offline/framework/phool/RunnumberRange.h
simulation/g4simulation/g4tpc/PHG4TpcSubsystem.cc

This PR sets the TPC ADC clock value to be the correct value by default based on the runnumber range being processed. This way the correct sample bin width is obtained automatically based on the runnumber in `recoConsts`

fix: set adc clock automatically based on runnumber

---

simulation/g4simulation/g4eval/SvtxTruthEval.cc
simulation/g4simulation/g4eval/SvtxTruthEval.h

This alters a hard coded drift velocity in the truth eval to read from the tpc geometry object, which is where the simulated drift velocity is actually set in simulation jobs. Local test showed it improved the cluster residuals dependence on radius slightly, curious to see the jenkins report and in any case this is now more robust.

fix: remove hard coded dv

---

offline/packages/trackbase/ActsGeometry.cc
simulation/g4simulation/g4detectors/PHG4TpcCylinderGeom.h
simulation/g4simulation/g4eval/SvtxTruthEval.cc
simulation/g4simulation/g4tpc/PHG4TpcDetector.cc
simulation/g4simulation/g4tpc/PHG4TpcDigitizer.cc
simulation/g4simulation/g4tpc/PHG4TpcDigitizer.h
simulation/g4simulation/g4tpc/PHG4TpcElectronDrift.cc
simulation/g4simulation/g4tpc/PHG4TpcElectronDrift.h
simulation/g4simulation/g4tpc/PHG4TpcPadBaselineShift.cc
simulation/g4simulation/g4tpc/PHG4TpcPadBaselineShift.h
simulation/g4simulation/g4tpc/PHG4TpcPadPlaneReadout.cc
simulation/g4simulation/g4tpc/PHG4TpcPadPlaneReadout.h
simulation/g4simulation/g4tpc/PHG4TpcSubsystem.cc

- [ x] Requiring change in macros repository (Please provide links to the macros pull request in the last section)
Adds the simulation drift velocity to PHG4TpcCylinderGeom, making it accessible throughout the simulation process. The value is set only once, in PHG4TpcSubsystem, now.
This requires some changes to macros because the setters for drift_velocity_sim have been removed from some modules.
Needs a corresponding macros update. …

Add drift_velocity_sim to TPC layergeom

---

offline/packages/CaloReco/CaloGeomMapping.cc

This change fixes a mismatch in CaloGeomMapping. Before that change, CaloGeomMapping reproduces the HCALIN/HCALOUT geometry at the inner radius, whereas it is given at the middle radius under `calo_geo`.

Original calo geom

---

simulation/g4simulation/g4detectors/PHG4TpcCylinderGeom.h

This PR rolls back the data members of PHG4TpcCylinderGeom.h which broke the readback. The accessors for the removed data members were replaced by returning hardcoded values which should keep our new reconstruction somewhat functional (those values need to be checked)

return hardcoded vars and remove new data members

---

offline/framework/ffamodules/CDBInterface.cc
offline/framework/ffamodules/CDBInterface.h
offline/framework/ffamodules/FlagHandler.cc
offline/framework/ffamodules/FlagHandler.h
offline/framework/fun4all/Fun4AllOutputManager.cc
offline/framework/fun4all/Fun4AllOutputManager.h
offline/framework/fun4all/Fun4AllServer.cc
offline/framework/fun4all/Fun4AllServer.h

For rollover outputs the flags and cdb content was only saved in the last DST since the update of the RUN node was called in the End() method. This PR adds an UpdateRunNode() method which can be implemented by the subsysreco modules which gets called whenever a rollover DST is closed. So far only the flags were affected in the event combining step which is the only place we use those rollovers so far. And in this case only the 64 bit timestamp was not saved. Once this is …

Implement update runnode
