- offline/framework/ffarawobjects/TpcRawHit.h
- offline/framework/ffarawobjects/TpcRawHitv1.cc
- offline/framework/ffarawobjects/TpcRawHitv1.h
- offline/framework/fun4allraw/SingleTpcInput.cc
- offline/framework/fun4allraw/SingleTpcInput.h
This updates the TPC BCO alignment code from chris to 
- include gtm_bco (64bits) and per-sample adc values in the TpcRawHit object
- implement a simple BCO alignment, based on SingleMicromegasInput:
This assumes that there is at most 1 level1 tagger per RCDAQ event, and that all the waveform's are either associated to the current lvl1_tagger gtm_bco, or the last recoded one (in past event), for a given packet
This breaks as soon as there is more than one level1 tagger in a given RCDaq event.
A more robust implementation exists in SingleMicromegasInput, but it is still being worked on.
**Todo**
@blackcathj this code is largely untested beyond the fact that it compiles. The main reason is that we are missing proper evaluation …
> Tpc bco alignment

- offline/framework/ffarawobjects/MvtxRawHit.h
- offline/framework/ffarawobjects/MvtxRawHitv1.h
- offline/packages/mvtx/Makefile.am
- offline/packages/mvtx/MvtxCombinedRawDataDecoder.cc
- offline/packages/mvtx/MvtxCombinedRawDataDecoder.h
- offline/packages/trackbase/MvtxEventInfov1.h
Updated Jakub's class to use the new MvtxRawHitContainer to pass the raw hits to the TRKR_HITSET
> Updated MvtxCombinedRawDataDecoder to use MvtxRawHitContainer

- offline/framework/fun4all/CreateSubsysRecoModule.pl
This PR replaces -I$(ROOTSYS) by -isystem$(ROOTSYS) so -Wshadow doesn't throw warnings in CreateSubsysRecoModule.pl. jenksins does not check this [skip-ci]
> use isystem for root includes

- offline/database/sphenixnpc/SphenixClient.cc
- offline/database/sphenixnpc/SphenixClient.h
This PR updates the cdb client. We can now delete entries - the client implements those methods. Still for testing.
> update cdb client with delete methods

- offline/framework/fun4allraw/Fun4AllEvtInputPoolManager.cc
- offline/framework/fun4allraw/Fun4AllEvtInputPoolManager.h
- offline/framework/fun4allraw/Makefile.am
- offline/framework/fun4allraw/SingleMvtxInput.cc
- offline/framework/fun4allraw/SingleMvtxInput.h
This PR implement a first version of the SingleMVTXInput module and the change int he input manager
> ycm First commit with SingleMvtxInput

- offline/packages/trackreco/PHActsGSF.cc
- offline/packages/trackreco/PHCosmicsTrkFitter.cc
- offline/packages/trackreco/PHCosmicsTrkFitter.h
Fix scan build errors from Acts update.
@pinkenburg we'll need to add this one from our Acts repo to the suppression file
https://web.sdcc.bnl.gov/jenkins-sphenix/job/sPHENIX/job/Build-ScanBuild-gcc12/1421//clang-analyzer/new/folder.1184863068/
> fix: scan build errors

- offline/framework/ffarawmodules/InttCheck.cc
- offline/framework/ffarawmodules/InttCheck.h
- offline/framework/fun4allraw/Makefile.am
- offline/framework/fun4allraw/SingleInttPoolInput.cc
- offline/framework/fun4allraw/SingleInttPoolInput.h
- offline/framework/fun4allraw/intt_pool.cc
- offline/framework/fun4allraw/intt_pool.h
This PR adds a pool based input manager for the intt.  To ease development it lives in parallel with the previous installation, so we can easily compare
> add the single intt pool input

- offline/packages/TrackingDiagnostics/KshortReconstruction.cc
This fixes a cm/mm confusion bug that crept into KshortReconstruction.
> Fix bug in Kshort diagnostic module

- offline/packages/bbc/BbcCalib.cc
- offline/packages/bbc/BbcEvent.cc
- offline/packages/bbc/BbcEvent.h
[comment]: some minor changes to reco to match some optimizations (eg to channel threshold) during checking of output.  Added ability to read calibration constants from text files for easier testing.
- [ x ] New feature (non-breaking change which adds functionality)
[comment]: reads in calibration constants that are in text format
> added text read for calibs, updated reco

- offline/packages/TrackerMillepedeAlignment/HelicalFitter.cc
- offline/packages/TrackerMillepedeAlignment/MakeMilleFiles.cc
- offline/packages/TrackingDiagnostics/TrackResiduals.cc
- offline/packages/tpccalib/PHTpcResiduals.cc
- offline/packages/trackbase/ActsGsfTrackFittingAlgorithm.h
- offline/packages/trackbase/ActsSourceLink.h
- offline/packages/trackbase/ActsTrackFittingAlgorithm.h
- offline/packages/trackbase/Calibrator.cc
- offline/packages/trackbase/Calibrator.h
- offline/packages/trackbase/Makefile.am
- offline/packages/trackbase/TrackFittingAlgorithmFunctionsGsf.cc
- offline/packages/trackbase/TrackFittingAlgorithmFunctionsKalman.cc
- offline/packages/trackbase_historic/ActsTransformations.cc
- offline/packages/trackbase_historic/ActsTransformations.h
- offline/packages/trackbase_historic/TrackAnalysisUtils.cc
- offline/packages/trackreco/ActsAlignmentStates.cc
- offline/packages/trackreco/ActsPropagator.cc
- offline/packages/trackreco/ActsPropagator.h
- offline/packages/trackreco/MakeActsGeometry.cc
- offline/packages/trackreco/PHActsGSF.cc
- offline/packages/trackreco/PHActsGSF.h
- offline/packages/trackreco/PHActsKDTreeSeeding.cc
- offline/packages/trackreco/PHActsKDTreeSeeding.h
- offline/packages/trackreco/PHActsSiliconSeeding.cc
- offline/packages/trackreco/PHActsTrkFitter.cc
- offline/packages/trackreco/PHActsTrkFitter.h
- offline/packages/trackreco/PHActsVertexPropagator.cc
- offline/packages/trackreco/PHCosmicsTrkFitter.cc
- offline/packages/trackreco/PHCosmicsTrkFitter.h
- offline/packages/trackreco/SecondaryVertexFinder.cc
This updates us from Acts v24.0.0 to Acts v30.0.0, which was surprisingly easier than going from v21->v24. Requires Acts repo merge as well, opening now to test CI while final MB validation tests are running. Gets us some needed bug fixes and new features (e.g. GSF is supposedly ready for production, which we can test)
https://github.com/sPHENIX-Collaboration/acts/pull/38
> update: Actsv30.0.0

- offline/packages/tpc/Makefile.am
- offline/packages/tpc/TpcRawDataTree.cc
- offline/packages/tpc/TpcRawDataTree.h
updating TpcRawDataTree with current TPCRawDataTree in analysis directory
checksumerror plots
> Checksumerror

- offline/packages/CaloBase/TowerInfoDefs.cc
remove obsolete decoding and add zdc arm decoding
> Clean up TowerInfoDefs.cc for ZDC, add arm mapping

- offline/packages/bbc/Makefile.am
- offline/packages/bbc/MbdPmtHit.cc
- offline/packages/bbc/MbdPmtHit.h
- offline/packages/bbc/MbdPmtHitLinkDef.h
- offline/packages/bbc/MbdReturnCodes.h
[comment]: Added the MbdPmtHits.
> Added MbdPmtHits

- offline/framework/fun4allraw/Fun4AllEventOutputManager.cc
- offline/framework/fun4allraw/Fun4AllEventOutputManager.h
This PR adds a prinout of the prdf output file if output manager verbosity is enabled for debugging PanDA
> print out prdf output filename when opened

- offline/packages/CaloBase/TowerInfoDefs.cc
> add missing "TowerInfoDefs" in method

- offline/packages/TrackerMillepedeAlignment/MakeMilleFiles.cc
- offline/packages/TrackingDiagnostics/KshortReconstruction.cc
- offline/packages/trackreco/ActsPropagator.cc
- offline/packages/trackreco/ActsPropagator.h
- offline/packages/trackreco/PHActsTrackProjection.cc
- offline/packages/trackreco/PHActsTrackProjection.h
- offline/packages/trackreco/PHActsTrackPropagator.cc
- offline/packages/trackreco/PHActsTrackPropagator.h
- offline/packages/trackreco/PHActsVertexPropagator.cc
- offline/packages/trackreco/PHActsVertexPropagator.h
- offline/packages/trackreco/SecondaryVertexFinder.cc
- offline/packages/trackreco/SecondaryVertexFinder.h
Fixes some fall out of Acts error handling in the new v30 with propagation results. Should make our nightly builds stable now
> fix: propagation result

- offline/framework/ffarawobjects/TpcRawHitContainerv1.cc
- offline/framework/ffarawobjects/TpcRawHitv1.cc
- offline/framework/ffarawobjects/TpcRawHitv1.h
- offline/framework/fun4allraw/Fun4AllStreamingInputManager.cc
- offline/framework/fun4allraw/SingleTpcInput.cc
- offline/packages/NodeDump/DumpInttRawHitContainer.cc
- offline/packages/NodeDump/DumpInttRawHitContainer.h
- offline/packages/NodeDump/DumpTowerInfoContainer.cc
- offline/packages/NodeDump/DumpTpcRawHitContainer.cc
- offline/packages/NodeDump/DumpTpcRawHitContainer.h
- offline/packages/NodeDump/Makefile.am
- offline/packages/NodeDump/PHNodeDump.cc
This PR cleans a few memory leaks in the tpc combining
> clean up TPC in dtor of Fun4AllStreamingInputManager.cc

- offline/packages/globalvertex/Makefile.am
- offline/packages/globalvertex/Vertex.cc
- offline/packages/globalvertex/Vertex.h
- offline/packages/globalvertex/VertexLinkDef.h
This PR introduces the virtual Vertex base class which will eventually be used as a base for all other vertex types.
Eventually redo inheritance s.t. all vertex classes inherit from this one, and set up vertexmap s.t. all vertices can be accessed from it.
> Added Vertex.h to globalvertex package

- offline/framework/ffamodules/CDBInterface.cc
This PR adds the printout of the parameters (global tag, domain and timestamp) for each cdb request if verbosity is enabled for debugging
> print selection info for each db lookup if verbosity enabled

- offline/framework/fun4allraw/Makefile.am
- offline/framework/fun4allraw/tpc_pool.cc
- offline/framework/fun4allraw/tpc_pool.h
[comment]: <I added the pool class for the TPC> ( What does this PR do? Linking to talk in software meeting encouraged )
> mlp - added the tpc pool class

- offline/packages/CaloReco/CaloGeomMapping.cc
- offline/packages/CaloReco/CaloTowerBuilder.cc
- offline/packages/CaloReco/RawClusterPositionCorrection.cc
- offline/packages/CaloReco/RawClusterPositionCorrection.h
waveform templates are now read from the CDB
> Templates from cdb

- offline/packages/CaloReco/CaloTowerCalib.cc
> put calib_towers under detector node, add verbosity

- offline/packages/CaloBase/TowerInfo.h
- offline/packages/CaloBase/TowerInfoContainer.cc
- offline/packages/CaloBase/TowerInfoContainer.h
- offline/packages/CaloBase/TowerInfoContainerv1.cc
- offline/packages/CaloBase/TowerInfoContainerv1.h
- offline/packages/CaloBase/TowerInfoContainerv2.cc
- offline/packages/CaloBase/TowerInfoContainerv2.h
- offline/packages/CaloBase/TowerInfoContainerv3.cc
- offline/packages/CaloBase/TowerInfoContainerv3.h
- offline/packages/CaloBase/TowerInfov3.h
- offline/packages/NodeDump/DumpTowerInfoContainer.cc
- offline/packages/bbc/BbcPmtInfoContainerV1.h
This PR makes the size() method const. Currently it throws a monkey wrench into const methods which check the size of the container
> Fix towerinfo

- offline/packages/CaloReco/CaloWaveformProcessing.cc
- offline/packages/CaloReco/CaloWaveformProcessing.h
- offline/packages/CaloReco/RawClusterPositionCorrection.cc
Fix two memory leaks, valgrind report is now clean for Fun4All_Year1.C. One leak in the root threading cannot be fixed in code - this is now added to the valgrind suppression file
> fix small static memory leaks found by valgrind

- offline/framework/fun4allraw/Fun4AllStreamingInputManager.cc
- offline/framework/fun4allraw/Fun4AllStreamingInputManager.h
- offline/framework/fun4allraw/Makefile.am
- offline/framework/fun4allraw/SingleMicromegasPoolInput.cc
- offline/framework/fun4allraw/SingleMicromegasPoolInput.h
- offline/packages/micromegas/MicromegasCombinedDataDecoder.cc
- offline/packages/micromegas/MicromegasCombinedDataEvaluation.cc
- offline/packages/micromegas/MicromegasRawDataDecoder.cc
This PR implements SingleMicromegasPoolEvent and the necessary changes in Fun4AllStreamingInputManager
> Micromegas event combiner

- offline/packages/tpc/Makefile.am
- offline/packages/tpc/TpcClusterQA.cc
- offline/packages/tpc/TpcClusterQA.h
This introduces an example QA module that can be run on TPC clusters created by data. Meant as an example module for future unit test type modules to be created, and can certainly be expanded on as we develop the production.
> feat: Example data based cluster QA module

- offline/packages/CaloReco/CaloTowerCalib.cc
> Adding default EMCal calib to CaloTowerCalib

- offline/framework/ffarawobjects/Gl1RawHit.h
- offline/framework/ffarawobjects/Gl1RawHitLinkDef.h
- offline/framework/ffarawobjects/Gl1RawHitv1.cc
- offline/framework/ffarawobjects/Gl1RawHitv1.h
- offline/framework/ffarawobjects/Gl1RawHitv1LinkDef.h
- offline/framework/ffarawobjects/Makefile.am
- offline/framework/fun4allraw/Fun4AllStreamingInputManager.cc
- offline/framework/fun4allraw/Fun4AllStreamingInputManager.h
- offline/framework/fun4allraw/Makefile.am
- offline/framework/fun4allraw/SingleGl1PoolInput.cc
- offline/framework/fun4allraw/SingleGl1PoolInput.h
This PR adds the GL1 and starts to line other system up with its beam clock. Moved to separate vectors for the input manager types which removes a ton of if's
> Add streaming gl1

- offline/framework/fun4allraw/SingleEvtInput.cc
- offline/framework/fun4allraw/SingleGl1PoolInput.cc
- offline/framework/fun4allraw/SingleInttInput.cc
- offline/framework/fun4allraw/SingleInttPoolInput.cc
- offline/framework/fun4allraw/SingleMicromegasInput.cc
- offline/framework/fun4allraw/SingleMicromegasPoolInput.cc
- offline/framework/fun4allraw/SingleMvtxInput.cc
- offline/framework/fun4allraw/SinglePrdfInput.cc
- offline/framework/fun4allraw/SingleTpcInput.cc
- offline/framework/fun4allraw/SingleTpcPoolInput.cc
This PR fixes the hang when an input file list is empty or does not exist. It looped in the attempt to open a new file but the return code wasn't checked in one place
> fix hangs if empty or non existing filelist is used

- offline/packages/trackbase/TrackFittingAlgorithmFunctionsGsf.cc
Another (very small, comparatively) Acts update that will get us some needed bug fixes that were introduced in v27. Everything is the same in single particles, AuAu validation running but starting this now to check the CI
> update: Actsv30.3.0

- offline/framework/ffarawmodules/Makefile.am
- offline/framework/ffarawmodules/StreamingCheck.cc
- offline/framework/ffarawmodules/StreamingCheck.h
- offline/framework/fun4allraw/Fun4AllStreamingInputManager.cc
- offline/framework/fun4allraw/Fun4AllStreamingInputManager.h
- offline/framework/fun4allraw/SingleMicromegasPoolInput.cc
- offline/framework/fun4allraw/SingleMicromegasPoolInput.h
- offline/framework/fun4allraw/SingleTpcPoolInput.cc
This PR adds the Micromegas to the functioning streaming readout combiner
> Add micromegas

- offline/framework/fun4allraw/Fun4AllStreamingInputManager.cc
- offline/framework/fun4allraw/SingleMicromegasInput.cc
- offline/framework/fun4allraw/SingleTpcInput.cc
The possible +1 bco for the micromegas was applied in the wrong place, fixed now. Also incorporated PR 2327 from Hugo here
> applying +1 bco for micromegas correctly

- offline/packages/jetbase/FastJetAlgo.cc
- offline/packages/jetbase/Jet.h
- offline/packages/jetbase/JetContainer.h
- offline/packages/jetbase/JetContainerv1.cc
- offline/packages/jetbase/JetContainerv1.h
- offline/packages/jetbase/JetReco.cc
- offline/packages/jetbase/Jetv2.cc
- offline/packages/jetbase/Jetv2.h
Just ran some checks to make sure that the constituents in the JetContainer match those in the JetMap; there is a minor bug fix in JetReco to that end. 
We will want to make a strategy to convert from JetMap to JetContainer now that the last PR (with this small addendum) is finally in.
> Bug fix for constituents in JetContainer

- offline/framework/fun4allraw/Fun4AllStreamingInputManager.cc
- offline/framework/fun4allraw/Fun4AllStreamingInputManager.h
- offline/framework/fun4allraw/Makefile.am
- offline/framework/fun4allraw/SingleInttPoolInput.cc
- offline/framework/fun4allraw/SingleMvtxInput.cc
- offline/framework/fun4allraw/SingleMvtxInput.h
- offline/framework/fun4allraw/SingleMvtxPoolInput.cc
- offline/framework/fun4allraw/SingleMvtxPoolInput.h
- offline/framework/fun4allraw/SingleTpcPoolInput.h
This PR adds the mvtx to the streaming event combining. Technically it is functional but I have my doubts about the mvtx bco. It's not really correlated with the GL1 in my test run 26065
> Add mvtx stream

- generators/HIJINGFlipAfterburner/HIJINGFlipAfterburner.cc
- generators/HIJINGFlipAfterburner/HIJINGFlipAfterburner.h
- generators/HIJINGFlipAfterburner/Makefile.am
This PR just triggers jenkins for the new hijing flip afterburner
> clang-tidy

- offline/packages/CaloReco/RawClusterPositionCorrection.cc
Bunch of cluster center of mass coordinates were coming up as nans. Adding this in will allow the production to continue so we can actually look at the data and resolve this. 
> Add nan gaurd

- offline/packages/CaloReco/CaloWaveformFitting.cc
- offline/packages/CaloReco/CaloWaveformFitting.h
> forcing peak to be within sample range and dividing chi2 by DOF

- offline/packages/CaloReco/CaloWaveformFitting.cc
> initialize histo after possible software zero sup to improve speed

- offline/packages/eventplaneinfo/EventPlaneReco.cc
- offline/packages/eventplaneinfo/EventPlaneReco.h
- offline/packages/eventplaneinfo/Eventplaneinfo.cc
- offline/packages/eventplaneinfo/Eventplaneinfo.h
- offline/packages/eventplaneinfo/EventplaneinfoLinkDef.h
- offline/packages/eventplaneinfo/EventplaneinfoMap.cc
- offline/packages/eventplaneinfo/EventplaneinfoMap.h
- offline/packages/eventplaneinfo/EventplaneinfoMapLinkDef.h
- offline/packages/eventplaneinfo/EventplaneinfoMapv1.cc
- offline/packages/eventplaneinfo/EventplaneinfoMapv1.h
- offline/packages/eventplaneinfo/EventplaneinfoMapv1LinkDef.h
- offline/packages/eventplaneinfo/Eventplaneinfov1.cc
- offline/packages/eventplaneinfo/Eventplaneinfov1.h
- offline/packages/eventplaneinfo/Eventplaneinfov1LinkDef.h
- offline/packages/eventplaneinfo/Makefile.am
- offline/packages/eventplaneinfo/autogen.sh
- offline/packages/eventplaneinfo/configure.ac
gets Q vectors, Psi_n for MBD and sEPD
> Add new changes to ep reco

- offline/packages/NodeDump/Makefile.am
- simulation/g4simulation/g4dst/Makefile.am
This PR removes linking against the obsolete libeventplane
> Remove eventplane

- offline/packages/TrackingDiagnostics/TrackResiduals.cc
- offline/packages/TrackingDiagnostics/TrackResiduals.h
- offline/packages/TrackingDiagnostics/TrkrNtuplizer.cc
- offline/packages/TrackingDiagnostics/TrkrNtuplizer.h
- offline/packages/trackreco/PHCosmicSeedCombiner.cc
- offline/packages/trackreco/PHCosmicSeedCombiner.h
Updates some of the diagnostic tools to look at the cosmics 
> fix: cosmic development

- offline/framework/frog/CreateDstList.pl
This PR adds a new script which create file lists for DSTs so we can finally make use of "good run" lists
> add CreateDstList.pl to create lists of data dsts

- offline/packages/mbd/MbdCalib.cc
- offline/packages/mbd/MbdEvent.cc
- offline/packages/mbd/MbdPmtHitV1.h
- offline/packages/mbd/MbdReco.cc
- offline/packages/mbd/MbdReco.h
- offline/packages/mbd/MbdSig.cc
[comment]: memory from one module wasn't cleaned up, and an occasional access out of array bounds.
> mem leak and array index bug fixes

- offline/framework/fun4allraw/Fun4AllStreamingInputManager.cc
> ycm check m_MvtxRawHitMap.empty(), this fix the issue of crashing before last event.

- offline/framework/frog/CreateDstList.pl
- offline/framework/frog/Makefile.am
This PR adds the use of a text file containing run numbers to get a filelist for every run
> Use runlist

- offline/framework/frog/CreateDstList.pl
This PR adds an option for printing of runs (to create run lists) and existing tags which enables users to figure this out without reading wiki pages, jenkins does not check this anyway [skip-ci]
> add print run and tag option

- offline/framework/ffamodules/HeadReco.cc
- offline/framework/ffamodules/SyncReco.h
- offline/packages/NodeDump/DumpGl1RawHit.cc
- offline/packages/NodeDump/DumpGl1RawHit.h
- offline/packages/NodeDump/DumpMbdGeom.cc
- offline/packages/NodeDump/DumpMbdGeom.h
- offline/packages/NodeDump/DumpMicromegasRawHitContainer.cc
- offline/packages/NodeDump/DumpMicromegasRawHitContainer.h
- offline/packages/NodeDump/DumpMvtxRawEvtHeader.cc
- offline/packages/NodeDump/DumpMvtxRawEvtHeader.h
- offline/packages/NodeDump/DumpMvtxRawHitContainer.cc
- offline/packages/NodeDump/DumpMvtxRawHitContainer.h
- offline/packages/NodeDump/Makefile.am
- offline/packages/NodeDump/PHNodeDump.cc
The header reco now saves the event type when running over data, add missing ascii dumps
> Fix headreco

- offline/framework/fun4all/Fun4AllOutputManager.cc
- offline/framework/fun4all/Fun4AllOutputManager.h
- offline/framework/fun4allraw/Fun4AllRolloverFileOutStream.cc
- offline/framework/fun4allraw/Fun4AllStreamingInputManager.cc
- offline/framework/fun4allraw/Fun4AllStreamingInputManager.h
- offline/framework/fun4allraw/SingleGl1PoolInput.cc
- offline/framework/fun4allraw/SingleGl1PoolInput.h
Preparation for at scale production, call script when output file is closed so it can be shipped out and registered while the combining is working on the next file
> Close file script

- offline/packages/CaloBase/TowerInfo.h
> switching default behavior for easier non-towerinfov2 use like in MC

- offline/database/sphenixnpc/SphenixClient.cc
the json object which is returned on failure does not contain a message nad parsing this fails. This PR does a cout << json << endl, to see what this failure is about, get this into todays buid: [skip-ci]
> print raw json return for geturl failure

- calibrations/tpc/generator/generate_distortion_map.C
This PR just suppresses a cppcheck warning when using R__LOAD_LIBRARY
> suppress cppcheck error for R__LOAD_LIBRARY

- calibrations/calorimeter/calo_tower_slope/LiteCaloEval.cc
- calibrations/calorimeter/calo_tower_slope/LiteCaloEval.h
minor updates to acommodate new November 23 production for calorimeter calibrations
minor updates to acommodate new November 23 production for calorimeter calibrations
macros/calibration/calo/calib_nov23
> updates to go along with first tower slope macros PR

- simulation/g4simulation/g4intt/PHG4InttHitReco.cc
The Innt has a bad bug in the z coordinate assignment in PHG4HitReco.cc, it accidentally assigns the y position. Let's see what jenkins says
> fix bad local z coordinate

- calibrations/calorimeter/calo_emc_pi0_tbt/CaloCalibEmc_Pi0.cc
- calibrations/calorimeter/calo_emc_pi0_tbt/CaloCalibEmc_Pi0.h
- calibrations/calorimeter/calo_emc_pi0_tbt/Makefile.am
- calibrations/calorimeter/calo_emc_pi0_tbt/configure.ac
- offline/packages/CaloReco/RawClusterBuilderTemplate.cc
- offline/packages/CaloReco/RawClusterBuilderTemplate.h
changes for doing pi0 part of calib on Fall 23 production  -- for running macro changes given below
macros/calibration/calo/calib_nov23
> Frantz nov23 2

- offline/packages/TrackerMillepedeAlignment/HelicalFitter.cc
- offline/packages/trackbase/TrackFitUtils.cc
- offline/packages/trackbase/TrackFitUtils.h
- offline/packages/trackreco/PHCosmicSiliconPropagator.cc
- offline/packages/trackreco/PHCosmicSiliconPropagator.h
- offline/packages/trackreco/PHSiliconHelicalPropagator.cc
This PR 
1. Generalizes the `addSiliconClusters` function in `TrackFitUtils` by checking an arbitrary set of layers.
2. Adds a line fit function to add the best cluster in a given layer to a track seed.
3. Generalizes the cosmic propagator module to use the line fit case in a zero field environment or the helix fit case in a nonzero field environment.
The function is still only able to add the best cluster on a given layer to the track seed, so it still operates under the assumption of approximately radial tracks. To improve the clusters on tracks in cosmics we will have to improve the tpc seeder efficiency.
[comment]: …
> feat: propagate cosmic track to all layers

- generators/hijing/src/hijfst.cc
- generators/phhepmc/Fun4AllHepMCInputManager.h
- generators/phhepmc/Fun4AllOscarInputManager.h
- generators/phhepmc/PHHepMCGenEventMap.h
- offline/framework/ffaobjects/SyncObjectv1.h
- offline/packages/CaloBase/RawTowerGeomContainer_Cylinderv1.h
- offline/packages/CaloBase/RawTowerGeomContainerv1.h
- offline/packages/CaloBase/RawTowerv2.h
- offline/packages/CaloReco/CaloTowerCalib.h
- offline/packages/globalvertex/GlobalVertexMapv1.h
- offline/packages/globalvertex/SvtxVertexMap_v1.h
- offline/packages/micromegas/MicromegasMapping.h
- offline/packages/vararray/VariableArray.h
- simulation/g4simulation/g4detectors/PHG4BlockCellReco.h
- simulation/g4simulation/g4detectors/PHG4CylinderCellReco.h
- simulation/g4simulation/g4detectors/PHG4CylinderGeom_Spacalv1.h
- simulation/g4simulation/g4detectors/PHG4CylinderGeom_Spacalv2.h
- simulation/g4simulation/g4detectors/PHG4CylinderGeom_Spacalv3.h
- simulation/g4simulation/g4mvtx/PHG4MvtxDigitizer.cc
- simulation/g4simulation/g4mvtx/PHG4MvtxSupport.cc
- simulation/g4simulation/g4mvtx/PHG4MvtxSupport.h
- simulation/g4simulation/g4tpc/PHG4TpcDigitizer.cc
This PR takes care of some benign cppcheck warnings (suppress or fix)
> Cppcheck fix

- offline/framework/frog/CreateFileList.pl
This PR adds the new cosmic sims the CreateFileList.pl as type 22 (magnet on) and type 23 (magnet off). no point running jenkins [skip-ci]
> add the new cosmic sims as type 22/23 for magnet on/off

- calibrations/calorimeter/calo_emc_pi0_tbt/Makefile.am
- calibrations/calorimeter/calo_emc_pi0_tbt/pi0EtaByEta.cc
- calibrations/calorimeter/calo_emc_pi0_tbt/pi0EtaByEta.h
> adding light weight pi0 calib code. 

- offline/framework/fun4all/Fun4AllServer.h
- offline/framework/phool/PHNodeIOManager.h
- offline/framework/phoolraw/PHRawOManager.h
- offline/packages/KFParticle_sPHENIX/KFParticle_Container.h
- offline/packages/PHGenFitPkg/PHGenFit/Fitter.h
- offline/packages/PHGenFitPkg/PHGenFit/Track.cc
- offline/packages/PHGenFitPkg/PHGenFit/Track.h
- offline/packages/eventplaneinfo/EventplaneinfoMapv1.h
- offline/packages/tpcdaq/TPCDaqDefs.h
- offline/packages/tpcdaq/TPCDataStreamEmulator.cc
- offline/packages/trackbase/TrkrClusterv1.h
- simulation/g4simulation/g4decayer/Pythia6.hh
- simulation/g4simulation/g4histos/G4SnglTree.h
- simulation/g4simulation/g4main/EcoMug.h
- simulation/g4simulation/g4main/PHG4TruthInfoContainer.h
- simulation/g4simulation/g4trackfastsim/PHG4TrackFastSim.cc
This PR should take care of the leftover cppcheck warnings.
> Fix cppcheck 1

- offline/framework/ffarawmodules/EventNumberCheck.cc
- offline/framework/ffarawmodules/EventNumberCheck.h
- offline/framework/fun4allraw/SinglePrdfInput.cc
- offline/framework/fun4allraw/SinglePrdfInput.h
- offline/framework/fun4allraw/SingleZdcInput.cc
- offline/framework/fun4allraw/SingleZdcInput.h
This PR now corrects the FEM event number for the calo electronics, if they were out of sync, a rollover lead to huge offsets which then scrambled the alignment.
> 16bit evt rollover

- offline/packages/jetbackground/FastJetAlgoSub.cc
> Remove a cout statement that snuck through in last PR. [skip-ci]

- offline/packages/CaloReco/CaloTowerStatus.cc
- offline/packages/CaloReco/CaloTowerStatus.h
> adding hot maps to calotowerstatus

- offline/packages/CaloReco/CaloTowerStatus.cc
> removing hcal hot maps because of channel vs key mapping and lack of update

- offline/packages/CaloReco/RawClusterPositionCorrection.cc
> Fixing node name in find node which seemed to cause memory leak in PDC

- offline/packages/trackreco/PHActsGSF.cc
- offline/packages/trackreco/PHActsGSF.h
Fixes a run time error in the GSF that Tony found, likely leftover from the Acts update.
> fix: gsf run time error

- offline/packages/TrackingDiagnostics/Makefile.am
- offline/packages/TrackingDiagnostics/TrackContainerCombiner.cc
- offline/packages/TrackingDiagnostics/TrackContainerCombiner.h
- offline/packages/trackbase/TrkrClusterIterationMapv1.cc
- offline/packages/trackreco/PHActsSiliconSeeding.cc
- offline/packages/trackreco/PHActsSiliconSeeding.h
- offline/packages/trackreco/PHSiliconSeedMerger.cc
- offline/packages/trackreco/PHSiliconSeedMerger.h
- offline/packages/trackreco/TrackingIterationCounter.cc
- simulation/g4simulation/g4eval/TrackSeedTrackMapConverter.cc
This PR introduces a second pass of the silicon seeder with an expansion of the search volume to include clusters in the INTT. It picks up additional seeds that were missed in the first pass due to (in the case of perfect simulation) tracks that left less than 3 measurements in the MVTX. In real data this should help us combat dead areas in the MVTX. Examples showing the efficiency and purity changes in 2 pion events are shown below. Tests in 50kHz MB are ongoing, but this at least gives some improvement with a minimal loss in purity from duplicates introduced by including the INTT measurements. Further tuning can occur …
> feat: iterative silicon seeding

- calibrations/calorimeter/calo_emc_pi0_tbt/pi0EtaByEta.cc
- calibrations/calorimeter/calo_emc_pi0_tbt/pi0EtaByEta.h
> pi0 calib: increasing saved output and stringent fit parameter limits

- offline/packages/CaloReco/RawClusterPositionCorrection.cc
- offline/packages/CaloReco/RawClusterPositionCorrection.h
> adding eta dependence to PDC in the residual correction 

- offline/framework/fun4all/Fun4AllReturnCodes.h
- offline/framework/fun4allraw/SinglePrdfInput.cc
This PR just adds the new general packet checksum check (rather than the odd/even check) and add some long overdue documentation for the fun4all return codes
> Minor fixes

- offline/packages/particleflow/ParticleFlowJetInput.cc
the code was too much chatty by default, I think Chris will not appreciate TB big logs from jobs :)
> hiding cout behing verbosity

- calibrations/calorimeter/calo_tower_slope/LiteCaloEval.cc
> adding tower QM to hist maker for tower slope

- offline/packages/centrality/CentralityReco.cc
- offline/packages/trigger/MinimumBiasClassifier.cc
- offline/packages/trigger/MinimumBiasClassifier.h
This fixes a crash on the MinimumBiasClassifier that occurs when the GlobalVertexMap is empty, but exists
> Trigger centrality

- generators/ReactionPlaneAfterburner/Makefile.am
- generators/ReactionPlaneAfterburner/ReactionPlaneAfterburner.cc
- generators/ReactionPlaneAfterburner/ReactionPlaneAfterburner.h
- generators/ReactionPlaneAfterburner/autogen.sh
- generators/ReactionPlaneAfterburner/configure.ac
Afterburner to randomize the reaction plane angle for HEPMC files for AMPT and EPOS4
> Reaction Plane Afterburner

- simulation/g4simulation/g4waveformsim/CaloWaveformSim.cc
- simulation/g4simulation/g4waveformsim/CaloWaveformSim.h
> add setter for the peak position and timing width

- offline/packages/tpc/TpcClusterizer.cc
- offline/packages/tpc/TpcClusterizer.h
> pedestal subtraction fix

- offline/database/cdbobjects/CDBTTree.cc
- offline/database/cdbobjects/Makefile.am
- simulation/g4simulation/g4waveformsim/CaloWaveformSim.cc
- simulation/g4simulation/g4waveformsim/CaloWaveformSim.h
- simulation/g4simulation/g4waveformsim/Makefile.am
- simulation/g4simulation/g4waveformsim/configure.ac
This PR adds the g4waveform package to the build with new compiler flags
> update for new compiler flags

- offline/packages/jetbase/FastJetAlgo.cc
- offline/packages/jetbase/FastJetAlgo.h
- offline/packages/jetbase/FastJetOptions.cc
- offline/packages/jetbase/FastJetOptions.h
- offline/packages/jetbase/Makefile.am
Reverts sPHENIX-Collaboration/coresoftware#2414
> Revert "Add fastjet::contrib::ConstituentSubtractor to FastJetAlgo"

- offline/packages/tpc/TpcClusterQA.cc
- offline/packages/tpc/TpcClusterQA.h
Add some features to the offline TPC QA module to try to get it into functional shape with the cosmic data.
> feat: Offline tpc QA

- generators/FermiMotionAfterburner/FermiMotion.cc
Fix the crashes while running this afterburner on AMPT file.
> only apply Fermi Motion for final state particles

- offline/framework/frog/CreateFileList.pl
This PR adds the new AMPT and EPOS files to CreateFileList.pl, not checked by jenkins [skip-ci]
> Add AMPT and EPOS to CreateFileList.pl

- offline/QA/EventDisplay/Makefile.am
- offline/QA/EventDisplay/TrackerEventDisplay.cc
- offline/QA/EventDisplay/TrackerEventDisplay.h
- offline/QA/EventDisplay/autogen.sh
- offline/QA/EventDisplay/configure.ac
Can take hits and clusters directly from containers and make event display json
> New TrackerEventDisplay Module Initialization

- .clang-tidy
- simulation/g4simulation/g4main/HepMCCompress.cc
- simulation/g4simulation/g4main/HepMCNodeReader.cc
This PR disables the clang-tidy check for subsequent same type argument. We cannot avoid this. Adds the id of the particle which is dropped bc it is outside of our world volume
> Fix printout

- simulation/g4simulation/g4micromegas/PHG4MicromegasDetector.cc
- simulation/g4simulation/g4micromegas/PHG4MicromegasDetector.h
- simulation/g4simulation/g4micromegas/PHG4MicromegasDigitizer.cc
- simulation/g4simulation/g4micromegas/PHG4MicromegasDigitizer.h
- simulation/g4simulation/g4micromegas/PHG4MicromegasDisplayAction.cc
- simulation/g4simulation/g4micromegas/PHG4MicromegasDisplayAction.h
- simulation/g4simulation/g4micromegas/PHG4MicromegasHitReco.cc
- simulation/g4simulation/g4micromegas/PHG4MicromegasHitReco.h
- simulation/g4simulation/g4micromegas/PHG4MicromegasSteppingAction.cc
- simulation/g4simulation/g4micromegas/PHG4MicromegasSteppingAction.h
- simulation/g4simulation/g4micromegas/PHG4MicromegasSubsystem.cc
- simulation/g4simulation/g4micromegas/PHG4MicromegasSubsystem.h
- simulation/g4simulation/g4micromegas/PHG4MicromegasSurvey.cc
- simulation/g4simulation/g4micromegas/PHG4MicromegasSurvey.h
This PR enables saving hits in the micromegas support structures for geantino scans, clang-tidy, clang-format
> Micromegas support

- simulation/g4simulation/g4mvtx/PHG4MvtxSteppingAction.cc
> rm duplicated code

- offline/framework/fun4allraw/intt_pool.cc
- offline/packages/intt/InttMapping.cc
…v. 2023.
intt_pool.cc is updated to handle pool_overflow which was reported Nov. 2023
InttMapping is updated to fix the channel conversion issue.
> intt_pool.cc and InttMapping are updated to fix issues

- simulation/g4simulation/g4waveformsim/CaloWaveformSim.cc
- simulation/g4simulation/g4waveformsim/CaloWaveformSim.h
read in DST for the pedestal noise instead of using TTrees...
> read in DST for pedestal in calowaveformsim

- offline/packages/CaloBase/TowerInfo.h
- offline/packages/CaloBase/TowerInfov2.h
- offline/packages/CaloReco/CaloTowerCalib.cc
- offline/packages/CaloReco/CaloTowerStatus.h
> change default badChi2 fraction cut to 1 percent

- validation/CaloValid/CaloValid.cc
- validation/CaloValid/CaloValid.h
> CaloValidation: adding tower status hists and other small changes

- offline/packages/intt/CylinderGeomIntt.cc
- offline/packages/intt/CylinderGeomIntt.h
- offline/packages/intt/InttCombinedRawDataDecoder.cc
- offline/packages/intt/InttRawDataConverter.cc
- offline/packages/intt/InttSurveyMapv1.cc
- offline/packages/intt/InttVertexFinder.cc
This PR fixes the remaining clang-tidy issues. The warning about a typo in find_strip_center_localcoords is now suppressed but we will stumble over this one whenever somebody sees this. That method should be renamed (together with its use)
> Clang tidy intt

- offline/packages/TrackingDiagnostics/TrkrNtuplizer.cc
- offline/packages/TrackingDiagnostics/TrkrNtuplizer.h
- simulation/g4simulation/g4eval/SvtxEvaluator.h
> Ntuplizer Refactor

- offline/database/PHParameter/PHParameterContainerInterface.cc
- simulation/g4simulation/g4ihcal/PHG4IHCalDetector.cc
- simulation/g4simulation/g4ihcal/PHG4IHCalDetector.h
- simulation/g4simulation/g4ihcal/PHG4IHCalSteppingAction.cc
- simulation/g4simulation/g4ihcal/PHG4IHCalSubsystem.cc
- simulation/g4simulation/g4ohcal/PHG4OHCalDetector.cc
- simulation/g4simulation/g4ohcal/PHG4OHCalDetector.h
- simulation/g4simulation/g4ohcal/PHG4OHCalSteppingAction.cc
- simulation/g4simulation/g4ohcal/PHG4OHCalSteppingAction.h
- simulation/g4simulation/g4ohcal/PHG4OHCalSubsystem.cc
This PR fixes the clang-tidy issues in g4ohcal and g4ihcal
> Clang tidy g4hcals

- offline/packages/tpc/TpcClusterCleaner.cc
- offline/packages/tpc/TpcClusterCleaner.h
- offline/packages/tpc/TpcClusterMover.cc
- offline/packages/tpc/TpcClusterMover.h
- offline/packages/tpc/TpcClusterQA.cc
- offline/packages/tpc/TpcClusterZCrossingCorrection.cc
- offline/packages/tpc/TpcClusterZCrossingCorrection.h
- offline/packages/tpc/TpcClusterizer.cc
- offline/packages/tpc/TpcClusterizer.h
- offline/packages/tpc/TpcCombinedRawDataUnpacker.cc
- offline/packages/tpc/TpcDistortionCorrection.cc
- offline/packages/tpc/TpcDistortionCorrection.h
- offline/packages/tpc/TpcDistortionCorrectionContainer.h
- offline/packages/tpc/TpcLoadDistortionCorrection.cc
- offline/packages/tpc/TpcLoadDistortionCorrection.h
- offline/packages/tpc/TpcMap.cc
- offline/packages/tpc/TpcRawDataDecoder.cc
- offline/packages/tpc/TpcRawDataDecoder.h
- offline/packages/tpc/TpcRawDataTree.cc
- offline/packages/tpc/TpcRawDataTree.h
- offline/packages/tpc/TpcRawWriter.cc
- offline/packages/tpc/TpcRawWriter.h
- offline/packages/tpc/TpcSimpleClusterizer.cc
- offline/packages/tpc/TpcSimpleClusterizer.h
- offline/packages/tpc/TrainingHits.h
- offline/packages/tpc/TrainingHitsContainer.h
- offline/packages/tpc/TrainingHitsContainerLinkDef.h
- offline/packages/tpc/TrainingHitsLinkDef.h
Applies clang-tidy and clang-format on the `tpc` package
> fix: clang-tidy and format on tpc

- offline/packages/trackreco/MakeSourceLinks.cc
This one doesn't break the build and just suppresses the verbosity
> suppress verbosity

- offline/packages/trackreco/Makefile.am
- offline/packages/trackreco/PHCosmicsFilter.cc
- offline/packages/trackreco/PHCosmicsFilter.h
> First implementation of the rtree based cosmics filter

- calibrations/framework/oncal/OnCalServer.cc
- simulation/g4simulation/g4intt/PHG4InttDigitizer.cc
corrected ADC
- because all ADC value was 0 before.
> corrected ADC

- offline/packages/CaloEmbedding/HepMCCollisionVertex.cc
- offline/packages/CaloEmbedding/HepMCCollisionVertex.h
- offline/packages/CaloEmbedding/Makefile.am
- offline/packages/CaloEmbedding/caloTowerEmbed.cc
- offline/packages/CaloEmbedding/caloTowerEmbed.h
This PR adds a module which can set the collision vertex which is used by our HepMC based event generators for embedding (currently pythia8 into 2023 data)
> add setting of collision vertex

- offline/packages/mbd/MbdPmtContainerV1.h
Discussed with Mickey about updating the code so that the simulation sees the right number of PMTs--> this is not set anywhere in the code for the simulations. Mickey gave the OK.
> Make MBD see the right number of PMTs

- offline/packages/trackreco/PrelimDistortionCorrection.cc
- simulation/g4simulation/g4tpc/PHG4TpcPadPlaneReadout.cc
When distortions are turned on, the simulation causes electrons to occasionally arrive early in the TPC. The warning message for that is now inside a verbosity check.
> Suppress noisy warning message

- offline/packages/TrackingDiagnostics/TrackResiduals.cc
- offline/packages/trackbase/TrackFitUtils.cc
- offline/packages/trackreco/PHCosmicTrackMerger.cc
- offline/packages/trackreco/PHCosmicTrackMerger.h
- offline/packages/trackreco/TrackQA.cc
Improves the cosmic seeding with tighter windows now that we can actually get things to line up
> fix: improve cosmics seeding

- offline/packages/trackreco/PHActsTrkFitter.h
> use cluster mover by default

- calibrations/calorimeter/calo_emc_pi0_tbt/CaloCalibEmc_Pi0.cc
- calibrations/calorimeter/calo_emc_pi0_tbt/pi0EtaByEta.cc
- calibrations/framework/oncal/OnCalServer.cc
- calibrations/framework/oncal/OnCalServer.h
This PR fixes clang tidy errors in some calibration packages
> Clang tidy 2

- calibrations/tpc/generator/AnalyticFieldModel.cc
- calibrations/tpc/generator/AnalyticFieldModel.h
- calibrations/tpc/generator/AnnularFieldSim.cc
- calibrations/tpc/generator/AnnularFieldSim.h
- calibrations/tpc/generator/ChargeMapReader.cc
- calibrations/tpc/generator/ChargeMapReader.h
- calibrations/tpc/generator/Makefile.am
- calibrations/tpc/generator/Rossegger.cc
- calibrations/tpc/generator/Rossegger.h
- calibrations/tpc/generator/configure.ac
- generators/FermiMotionAfterburner/FermiMotion.cc
- generators/FermiMotionAfterburner/FermimotionAfterburner.cc
- generators/FermiMotionAfterburner/FermimotionAfterburner.h
- generators/FermiMotionAfterburner/configure.ac
More clang-tidy fixes, using doubles consistently in fermi motion afterburner
> Clang tidy 4

- offline/packages/KFParticle_sPHENIX/KFParticle_Container.h
- offline/packages/KFParticle_sPHENIX/KFParticle_MVA.cc
- offline/packages/KFParticle_sPHENIX/KFParticle_Tools.cc
- offline/packages/KFParticle_sPHENIX/KFParticle_Tools.h
- offline/packages/KFParticle_sPHENIX/KFParticle_eventReconstruction.cc
- offline/packages/KFParticle_sPHENIX/KFParticle_nTuple.cc
We found that the flag to search for a charge conjugate decay was always true so it wasn't possible to search for the separated decay
> KFP: CC bug fix

- offline/packages/trackreco/PHSimpleKFProp.cc
- offline/packages/trackreco/PHSimpleKFProp.h
This makes sure that KFProp can handle all three kind of distortions when available (static, beam induced and fluctuations), rather than static only.
> Kf prop distortions

- offline/database/sphenixnpc/CDBUtils.cc
- offline/packages/mbd/MbdEvent.cc
This PR sorts the cdb listings (global tags, payload types and iov's) alphabetically. Makes it easier to locate what one is looking for
> Cdb listing

- calibrations/localpol/monitoring/LocalPolOffMon.cc
- calibrations/localpol/monitoring/LocalPolOffMon.h
- calibrations/localpol/monitoring/Makefile.am
- calibrations/localpol/monitoring/autogen.sh
- calibrations/localpol/monitoring/configure.ac
- calibrations/xingshift/Makefile.am
- calibrations/xingshift/XingShiftCal.cc
- calibrations/xingshift/XingShiftCal.h
- calibrations/xingshift/autogen.sh
- calibrations/xingshift/configure.ac
- calibrations/xingshift/macros/Fun4All_xingshift.C
- Creates a class XingShiftCal that reads in spin patterns and gl1p data from the gl1 packets, calculates the crossing shift and saves the crossing shift and spin patterns to the db
- Creates a class LocalPolOffMon that will be used for the offline monitoring of the local polarimetry directly following a run
XingShiftCal needs to implement the code to write to the database
LocalPolOffMon needs to be developed  …
> XingShiftCal and LocalPolOffMon classes

- simulation/g4simulation/g4ohcal/PHG4OHCalDetector.cc
> Change to inner hcal support ring call

- offline/packages/micromegas/MicromegasCombinedDataEvaluation.cc
- offline/packages/micromegas/MicromegasRawDataEvaluation.cc
> fix max number of samples

- offline/packages/micromegas/MicromegasHotChannelMapData.h
- offline/packages/micromegas/MicromegasMapping.cc
- offline/packages/micromegas/MicromegasMapping.h
> Micromegas hot channels

- calibrations/calorimeter/calo_emc_noisy_tower/Makefile.am
- calibrations/calorimeter/calo_emc_noisy_tower/emcNoisyTowerFinder.cc
- calibrations/calorimeter/calo_emc_noisy_tower/emcNoisyTowerFinder.h
Added normalization switch to recover nominal functionality (set in macro) also made fix to inconsequential bug fix (so the code makes sense to the reader)
> Adding normalization switch to bad tower mapper

- offline/framework/ffarawobjects/CaloPacket.h
- offline/framework/ffarawobjects/CaloPacketContainer.h
- offline/framework/ffarawobjects/CaloPacketContainerv1.cc
- offline/framework/ffarawobjects/CaloPacketContainerv1.h
- offline/framework/ffarawobjects/CaloPacketv1.cc
- offline/framework/ffarawobjects/CaloPacketv1.h
- offline/framework/fun4allraw/Fun4AllPrdfInputTriggerManager.h
- offline/framework/fun4allraw/SingleHcalTriggerInput.cc
- offline/packages/CaloReco/CaloTowerBuilder.cc
- offline/packages/CaloReco/CaloTowerBuilder.h
- offline/packages/CaloReco/CaloTowerCalib.cc
- offline/packages/CaloReco/CaloTowerCalib.h
- offline/packages/CaloReco/CaloTowerStatus.cc
- offline/packages/CaloReco/CaloTowerStatus.h
- offline/packages/CaloReco/Makefile.am
- offline/packages/CaloReco/RawTowerCalibration.cc
- offline/packages/CaloReco/RawTowerCalibration.h
The calotower builder can now use offline packets (verified only for the hcal so far)
> Prdf combiner 6

- offline/packages/intt/InttBCOMap.cc
- offline/packages/intt/InttBCOMap.h
- offline/packages/intt/InttCombinedRawDataConverter.cc
- offline/packages/intt/InttCombinedRawDataConverter.h
- offline/packages/intt/InttCombinedRawDataDecoder.cc
- offline/packages/intt/InttMaskedChannelSetv1.cc
- offline/packages/intt/InttRawDataConverter.h
- offline/packages/intt/Makefile.am
[comment]: < The module to handle the INTT BCO calibration parameter is added> (Please tell us something about this pull request)
> BCO calibration parameter added

- offline/framework/ffarawmodules/Makefile.am
- offline/framework/ffarawmodules/ZdcCheck.cc
- offline/framework/ffarawmodules/ZdcCheck.h
- offline/framework/ffarawobjects/Gl1RawHit.cc
- offline/framework/ffarawobjects/Gl1RawHit.h
- offline/framework/ffarawobjects/Gl1RawHitv1.h
- offline/framework/ffarawobjects/Gl1RawHitv2.cc
- offline/framework/ffarawobjects/Gl1RawHitv2.h
- offline/framework/ffarawobjects/Gl1RawHitv2LinkDef.h
- offline/framework/ffarawobjects/Makefile.am
- offline/framework/fun4allraw/Fun4AllPrdfInputTriggerManager.cc
- offline/framework/fun4allraw/Fun4AllPrdfInputTriggerManager.h
- offline/framework/fun4allraw/Fun4AllStreamingInputManager.cc
- offline/framework/fun4allraw/InputManagerType.h
- offline/framework/fun4allraw/Makefile.am
- offline/framework/fun4allraw/SingleGl1PoolInput.cc
- offline/framework/fun4allraw/SingleHcalTriggerInput.cc
- offline/framework/fun4allraw/SingleMbdTriggerInput.cc
- offline/framework/fun4allraw/SingleZdcTriggerInput.cc
- offline/framework/fun4allraw/SingleZdcTriggerInput.h
This should be sufficient to run the calorimeters with event and runheader and sync object. zdc is added but only for an old hitformat
> Prdf combiner 7

- offline/framework/fun4allraw/SingleTpcPoolInput.cc
This PR addresses a reason for memory overflow - in this case a FEE stopped to take data, so its BCO did not increase anymore and the reader kept reading events in the hope to find more data from this FEE until it ran out of memory. The fix is a bit of a kludge - if the current BCO is 10^6 larger than the BCO of the FEE, no further reading of data is done …
> handle stuck FEE (no response within 10M BCOs)

- calibrations/framework/oncal/OnCalServer.cc
- offline/framework/ffarawobjects/Gl1RawHitv2.h
- offline/framework/ffarawobjects/MicromegasRawHitContainerv1.cc
- offline/framework/ffarawobjects/MicromegasRawHitv1.cc
- offline/framework/ffarawobjects/MicromegasRawHitv1.h
- offline/framework/ffarawobjects/OfflinePacket.h
- offline/framework/ffarawobjects/OfflinePacketv1.h
- offline/framework/ffarawobjects/TpcRawHitContainerv1.cc
- offline/framework/fun4all/Fun4AllOutputManager.cc
- offline/framework/fun4all/Fun4AllOutputManager.h
- offline/framework/fun4allraw/Fun4AllStreamingInputManager.cc
- offline/framework/fun4allraw/SingleCemcTriggerInput.cc
- offline/framework/fun4allraw/SingleGl1TriggerInput.cc
- offline/framework/fun4allraw/SingleHcalTriggerInput.cc
- offline/framework/fun4allraw/SingleMbdTriggerInput.cc
- offline/framework/fun4allraw/SingleTpcPoolInput.cc
- offline/framework/fun4allraw/SingleZdcTriggerInput.cc
- simulation/g4simulation/g4ohcal/PHG4OHCalDetector.cc
This PR fixes a memory leak in the micromegas hits (the TC Array allocates memory via a vector which needs explicit handling), stuck FEE's are now removed from the list of BCOs, if another hit is found, they will be added again.
Fixes an issue Jason found in the output manager. If the number of events which it saved coincides with the number of events which are analyzed (or are in the file), the optional script is called twice. It now checks if another file has been opened in …
> Prdf combiner 9

- offline/packages/intt/InttBCOMap.cc
- offline/packages/intt/InttBCOMap.h
- offline/packages/intt/InttCombinedRawDataDecoder.cc
- offline/packages/intt/InttCombinedRawDataDecoder.h
- offline/packages/intt/InttDacMap.cc
- offline/packages/intt/InttDacMap.h
InttBCOmap is added to InttCombinedRawdataDecoder to mask bad BCO hit
> InttBCOmap is added to InttCombinedRawdataDecoder to mask bad BCO hit

- offline/framework/ffarawmodules/DumpPacket.cc
- offline/framework/ffarawmodules/DumpPacket.h
- offline/framework/ffarawobjects/CaloPacket.h
- offline/framework/ffarawobjects/CaloPacketv1.cc
- offline/framework/ffarawobjects/CaloPacketv1.h
- offline/framework/fun4allraw/SingleZdcTriggerInput.cc
This PR enables reading of zero suppressed zdc/smd packets as well as unsuppressed packets
> Prdf combiner 10

- offline/framework/fun4allraw/Fun4AllPrdfInputTriggerManager.cc
- offline/framework/fun4allraw/Fun4AllStreamingInputManager.cc
- offline/packages/NodeDump/DumpCaloPacketContainer.cc
- offline/packages/NodeDump/DumpCaloPacketContainer.h
- offline/packages/NodeDump/DumpGl1Packet.cc
- offline/packages/NodeDump/DumpGl1Packet.h
- offline/packages/NodeDump/DumpGl1RawHit.cc
- offline/packages/NodeDump/DumpJetContainer.cc
- offline/packages/NodeDump/DumpMbdGeom.cc
- offline/packages/NodeDump/DumpMicromegasRawHitContainer.cc
- offline/packages/NodeDump/DumpMvtxRawEvtHeader.cc
- offline/packages/NodeDump/DumpPHHepMCGenEventMap.cc
- offline/packages/NodeDump/DumpTpcRawHitContainer.cc
- offline/packages/NodeDump/Makefile.am
- offline/packages/NodeDump/PHNodeDump.cc
This PR adds protection against running over input files from different runs, it now checks for identical runs and bails if run numbers of the single input managers differ. Added the trigger packets to the dumping
> Prdf combiner 11

- offline/packages/trackreco/PHGenFitTrkFitter.cc
Use the new get_px() and get_py() from SvtxSeedv2, to avoid warning. 
> Genfit fix

- calibrations/calorimeter/calo_emc_pi0_tbt/pi0EtaByEta.cc
- calibrations/calorimeter/calo_emc_pi0_tbt/pi0EtaByEta.h
> ading finished checker for pi0 calib loop termination

- simulation/g4simulation/g4intt/InttDeadMap.cc
- simulation/g4simulation/g4intt/InttDeadMap.h
- simulation/g4simulation/g4intt/InttDeadMapv1.cc
- simulation/g4simulation/g4intt/PHG4InttDeadMapLoader.cc
- simulation/g4simulation/g4intt/PHG4InttDeadMapLoader.h
- simulation/g4simulation/g4intt/PHG4InttDetector.cc
- simulation/g4simulation/g4intt/PHG4InttDigitizer.cc
- simulation/g4simulation/g4intt/PHG4InttDigitizer.h
- simulation/g4simulation/g4intt/PHG4InttDisplayAction.cc
- simulation/g4simulation/g4intt/PHG4InttFPHXParameterisation.cc
- simulation/g4simulation/g4intt/PHG4InttFPHXParameterisation.h
- simulation/g4simulation/g4intt/PHG4InttHitReco.cc
- simulation/g4simulation/g4intt/PHG4InttHitReco.h
- simulation/g4simulation/g4intt/PHG4InttSteppingAction.cc
- simulation/g4simulation/g4intt/PHG4InttSubsystem.cc
- simulation/g4simulation/g4intt/PHG4InttSubsystem.h
- simulation/g4simulation/g4intt/configure.ac
This PR takes care of the clang-tidy issues in g4intt - for bit operations/masks/field, please use unsigned ints in the future
> G4intt clang tidy

- offline/packages/intt/InttArborist.cc
- offline/packages/intt/InttArborist.h
- offline/packages/intt/InttDacMap.cc
- offline/packages/intt/Makefile.am
- offline/packages/tpc/Makefile.am
- offline/packages/tpc/TpcClusterZCrossingCorrection.cc
- offline/packages/tpc/TpcCombinedRawDataUnpacker.cc
- offline/packages/tpc/TpcCombinedRawDataUnpacker.h
- offline/packages/tpc/TpcMap.cc
- offline/packages/tpc/TpcRawDataTree.cc
- offline/packages/tpc/TpcRawDataTree.h
- offline/packages/tpc/configure.ac
- offline/packages/trackreco/PHTruthSiliconAssociation.cc
- offline/packages/trackreco/PHTruthSiliconAssociation.h
- offline/packages/trackreco/PHTruthTrackSeeding.cc
- offline/packages/trackreco/PHTruthTrackSeeding.h
- simulation/g4simulation/g4intt/Makefile.am
This PR fixes the clang-tidy and cppcheck warnings which have crept into the recent PRs
> Clang tidy fixes 7

- offline/packages/mbd/MbdCalib.h
- offline/packages/mbd/MbdEvent.cc
- offline/packages/mbd/MbdSig.cc
- offline/packages/mbd/MbdSig.h
[comment]: mods to handle variable number of samples (eg 12, 16, or 31)
[comment]: reads num samples from prdf and fills containers according to this
> mods to handle variable number of samples

- offline/packages/trackreco/PHCASeeding.cc
- offline/packages/trackreco/PHCASeeding.h
- offline/packages/trackreco/PHSimpleKFProp.cc
- offline/packages/trackreco/PHSimpleKFProp.h
Adds flag options to the tpc seeding for setting the field map to test the new map added by Jin and Chris
> feat: add field map options

- offline/packages/trackreco/PHTruthSiliconAssociation.cc
Somehow this slipped through Jenkins - should fix the build
> fix: px/py call

- offline/packages/trackbase_historic/TrackSeed_FastSim_v2.h
> fix: clang build

- offline/packages/TrackingDiagnostics/TrkrNtuplizer.cc
> adc and residual analysis tool update

- offline/framework/fun4all/Fun4AllServer.cc
- offline/packages/KFParticle_sPHENIX/KFParticle_sPHENIX.cc
- offline/packages/KFParticle_sPHENIX/KFParticle_sPHENIX.h
- offline/packages/KFParticle_sPHENIX/Makefile.am
- offline/packages/trackreco/MakeActsGeometry.cc
- offline/packages/trackreco/MakeActsGeometry.h
- offline/packages/trackreco/PHActsSiliconSeeding.cc
- offline/packages/trackreco/PHActsSiliconSeeding.h
- offline/packages/trackreco/PHActsTrkFitter.cc
- offline/packages/trackreco/PHActsTrkFitter.h
- offline/packages/trackreco/PHActsVertexPropagator.cc
- offline/packages/trackreco/PHActsVertexPropagator.h
- offline/packages/trackreco/PHCASeeding.cc
- offline/packages/trackreco/PHCASeeding.h
- offline/packages/trackreco/PHCosmicSiliconPropagator.cc
- offline/packages/trackreco/PHSiliconHelicalPropagator.cc
- offline/packages/trackreco/PHSimpleKFProp.cc
- offline/packages/trackreco/PHSimpleKFProp.h
This PR prepares for the consistent implementation of the tracking fieldmap. The updated macros will work with this one which is then followed by another commit where hardcoded fieldmaps are replaced by macro settings
> Tracking fieldmap

- offline/packages/TrackingDiagnostics/KshortReconstruction.cc
- offline/packages/TrackingDiagnostics/KshortReconstruction.h
- offline/packages/TrackingDiagnostics/TrackContainerCombiner.cc
- offline/packages/TrackingDiagnostics/TrackContainerCombiner.h
- offline/packages/TrackingDiagnostics/TrackResiduals.cc
- offline/packages/TrackingDiagnostics/TrackResiduals.h
- offline/packages/TrackingDiagnostics/TrackSeedTrackMapConverter.cc
- offline/packages/TrackingDiagnostics/TrkrNtuplizer.cc
- offline/packages/TrackingDiagnostics/TrkrNtuplizer.h
- offline/packages/trackreco/PHActsTrkFitter.cc
- offline/packages/trackreco/PHCASeeding.h
- offline/packages/trackreco/PHSimpleKFProp.h
This PR finalizes the single place setting of the tracking fieldmap, fixed clang-tidy complaints in TrackingDiagnostics
> Finalize fieldmap

- offline/packages/mbd/Makefile.am
- simulation/g4simulation/g4bbc/MbdDigitization.h
[comment]: Added code to be compiled under USE_ONLINE, which lets me reuse code in the online monitoring
[comment]: Just allows more code to be re-used in the MBD/BBC online monitoring.  This mod does not affect the offline at all, so it should pass Jenkins (famous last words).
> Added code for USE_ONLINE

- offline/framework/fun4allraw/Fun4AllPrdfInputTriggerManager.cc
This is a one line fix for the crash of the event combiner at the last event
> fix crash after last event is read

- offline/packages/trigger/CaloTriggerEmulator.cc
- offline/packages/trigger/CaloTriggerEmulator.h
- offline/packages/trigger/CaloTriggerEmulatorLinkDef.h
- offline/packages/trigger/CaloTriggerInfo.h
- offline/packages/trigger/LL1Defs.h
- offline/packages/trigger/LL1Out.cc
- offline/packages/trigger/LL1Out.h
- offline/packages/trigger/LL1Outv1.cc
- offline/packages/trigger/LL1Outv1.h
- offline/packages/trigger/LL1PacketGetter.cc
- offline/packages/trigger/LL1PacketGetter.h
- offline/packages/trigger/LL1PacketGetterLinkDef.h
- offline/packages/trigger/MinimumBiasClassifier.cc
- offline/packages/trigger/MinimumBiasClassifier.h
- offline/packages/trigger/MinimumBiasInfov1.h
- offline/packages/trigger/TriggerDefs.cc
- offline/packages/trigger/TriggerDefs.h
- offline/packages/trigger/TriggerPrimitive.cc
- offline/packages/trigger/TriggerPrimitive.h
- offline/packages/trigger/TriggerPrimitiveContainer.cc
- offline/packages/trigger/TriggerPrimitiveContainer.h
- offline/packages/trigger/TriggerPrimitiveContainerv1.cc
- offline/packages/trigger/TriggerPrimitiveContainerv1.h
- offline/packages/trigger/TriggerPrimitivev1.cc
- offline/packages/trigger/TriggerPrimitivev1.h
Added ability to load a custom file of LUTs as well as use CDB files (to be added to CDB ) or default identity LUTs
macros and analysis repo to be updated
> CaloTriggerEmulator

- offline/framework/ffarawmodules/ClockDiffCheck.cc
- offline/framework/fun4allraw/Fun4AllPrdfInputTriggerManager.cc
- offline/packages/TrackingDiagnostics/TrkrNtuplizer.cc
This PR fixes the cppcheck warning and fixes a long standing clang-tidy warning in the TrkrNtupler
> Fix prdf combiner

- offline/packages/tpccalib/Makefile.am
- offline/packages/tpccalib/PHTpcCentralMembraneClusterizer.cc
- offline/packages/tpccalib/PHTpcCentralMembraneClusterizer.h
- offline/packages/tpccalib/PHTpcCentralMembraneMatcher.cc
- offline/packages/tpccalib/PHTpcCentralMembraneMatcher.h
- offline/packages/tpccalib/TpcSpaceChargeReconstructionHelper.cc
- offline/packages/tpccalib/TpcSpaceChargeReconstructionHelper.h
- offline/packages/tpccalib/configure.ac
The updated compiler flags showed shadowed variables - fixed (and compiler flags updated to include -Wshadow)
fix clang-tidy errors which show up in other PR's
> Clang tidy 11

- calibrations/calorimeter/calo_tower_slope/HCalCosmics.cc
- calibrations/calorimeter/calo_tower_slope/HCalCosmics.h
- calibrations/calorimeter/calo_tower_slope/Makefile.am
> adding Cosmic histMaker

- offline/packages/trackreco/ActsAlignmentStates.cc
- offline/packages/trackreco/MakeActsGeometry.cc
- offline/packages/trackreco/PHActsTrkFitter.cc
- offline/packages/trackreco/PHActsTrkFitter.h
- offline/packages/trackreco/PHCosmicsTrkFitter.cc
- offline/packages/trackreco/PHCosmicsTrkFitter.h
- offline/packages/trackreco/PHSiliconTpcTrackMatching.cc
- offline/packages/trackreco/PHSiliconTpcTrackMatching.h
This PR should make running with a constant field possible. There were a few places left where the filename was checked for 3d or .root.  
> this should now work for constant fields as well

- offline/framework/fun4allraw/mvtx_decoder/GBTLink.h
> ycm - fix bug in MVTX decoder

- calibrations/calorimeter/calo_tower_slope/HCalCosmics.cc
- calibrations/calorimeter/calo_tower_slope/HCalCosmics.h
- calibrations/calorimeter/calo_tower_slope/Makefile.am
> adding cosmic histo maker

- offline/packages/TrackingDiagnostics/TrackSeedTrackMapConverter.cc
- offline/packages/TrackingDiagnostics/TrackSeedTrackMapConverter.h
This PR fixes another fallout from the fieldmap change. 
> fix fieldmap handling

- offline/packages/mbd/MbdCalib.cc
This PR is a minor mode to the mbd code, the compilers in 1008 want std::isnan instead of isnan.
> 1008 compilers want std::isnan

- simulation/g4simulation/g4intt/Makefile.am
- simulation/g4simulation/g4intt/PHG4InttHitReco.cc
- simulation/g4simulation/g4intt/PHG4InttHitReco.h
Added a hot strip mask ability for INTT simulations
> CD: INTT simulation hot strip masking

- simulation/g4simulation/g4mvtx/PHG4MvtxHitReco.cc
fixes recent clangtidy error that crept into build
> fix: clang-tidy clang-format mvtx hitreco

- calibrations/calorimeter/calo_tower_slope/HCalCosmics.cc
- calibrations/calorimeter/calo_tower_slope/HCalCosmics.h
> bug fix in End and removing hist manager

- offline/framework/ffaobjects/EventHeader.h
- offline/framework/ffaobjects/EventHeaderv1.cc
- offline/framework/ffaobjects/EventHeaderv1.h
- offline/framework/ffaobjects/EventHeaderv2.cc
- offline/framework/ffaobjects/EventHeaderv2.h
- offline/framework/ffaobjects/RunHeader.cc
- offline/framework/ffaobjects/RunHeader.h
- offline/framework/ffaobjects/RunHeaderv1.h
- offline/packages/CaloEmbedding/CopyIODataNodes.cc
- offline/packages/CaloEmbedding/CopyIODataNodes.h
- offline/packages/CaloEmbedding/Makefile.am
- offline/packages/centrality/CentralityInfo.h
- offline/packages/centrality/CentralityInfov1.cc
- offline/packages/centrality/CentralityInfov1.h
- offline/packages/centrality/CentralityInfov2.cc
- offline/packages/centrality/CentralityInfov2.h
- offline/packages/globalvertex/GlobalVertexMap.h
- offline/packages/globalvertex/GlobalVertexMapv1.cc
- offline/packages/globalvertex/GlobalVertexMapv1.h
- offline/packages/trigger/MinimumBiasInfo.h
- offline/packages/trigger/MinimumBiasInfov1.cc
- offline/packages/trigger/MinimumBiasInfov1.h
This PR adds the CopyIODataNodes reco module which copies a bunch of nodes from one node tree to another (needed for embedding)
> Copy nodes

- simulation/g4simulation/g4mvtx/PHG4MvtxHitReco.cc
- simulation/g4simulation/g4mvtx/PHG4MvtxHitReco.h
Expanding on Pedro's addition of the dead pixel mask to the MVTX simulations. I've also added the hot pixel map.
> MVTX hot pixel mask in simulation

- offline/framework/ffarawobjects/InttRawHit.h
- offline/framework/ffarawobjects/InttRawHitContainerv2.cc
- offline/framework/ffarawobjects/InttRawHitContainerv2.h
- offline/framework/ffarawobjects/InttRawHitContainerv2LinkDef.h
- offline/framework/ffarawobjects/InttRawHitv2.cc
- offline/framework/ffarawobjects/InttRawHitv2.h
- offline/framework/ffarawobjects/InttRawHitv2LinkDef.h
- offline/framework/ffarawobjects/Makefile.am
- offline/framework/fun4allraw/SingleInttPoolInput.cc
- offline/framework/fun4allraw/intt_pool.cc
- offline/framework/fun4allraw/intt_pool.h
pool is updated to decode the event counter from binary data and InttRawhitv2 is added to save the event counter
> pool is updated and InttRawhitv2 is added to save the event counter

- offline/packages/mbd/MbdCalib.cc
- offline/packages/mbd/MbdCalib.h
- offline/packages/mbd/MbdEvent.cc
- offline/packages/mbd/MbdEvent.h
- offline/packages/mbd/MbdRunningStats.cc
- offline/packages/mbd/MbdRunningStats.h
- offline/packages/mbd/MbdSig.cc
- offline/packages/mbd/MbdSig.h
[comment]: Adds a pedestal calibration.  Not used except as backup for evt-by-evt ped in 1st few events, and for Q/A checks.
[comment]: Requires new MBD_PED calibration in CDB.
> added ped calibration

- offline/packages/mbd/BbcVertexv1.cc
- offline/packages/mbd/BbcVertexv2.cc
- offline/packages/mbd/MbdCalib.cc
- offline/packages/mbd/MbdEvent.cc
- offline/packages/mbd/MbdSig.cc
isnan does not compile under Debian in 1008, replace all occurrences by std::isnan
> use std::isnan to compile under Debian in 1008

- offline/framework/fun4allraw/Fun4AllPrdfInputTriggerManager.cc
- offline/framework/fun4allraw/Fun4AllPrdfInputTriggerManager.h
- offline/framework/fun4allraw/SingleZdcTriggerInput.cc
- offline/framework/fun4allraw/intt_pool.cc
- offline/framework/fun4allraw/intt_pool.h
This PR puts the sepd offline packets under its own node. They are in the same file as the zdc and were so far copied under the zdc node which is kinda confusing. The CaloTowerBuilder needs to be looked at for the sepd (and likely the zdc)
> Sepd packet node

- offline/packages/trackreco/PHSimpleKFProp.cc
Fixes running with constant field in the simple kfprop module
> fix: const field in kfprop

- offline/packages/trackreco/PHSiliconCosmicSeeding.cc
This fixes memory mismanagement and improves the speed of the silicon cosmic seeder
> fix: silicon cosmic seeder memory/cpu

- calibrations/calorimeter/calo_tower_slope/HCalCosmics.cc
- calibrations/calorimeter/calo_tower_slope/HCalCosmics.h
- offline/packages/KFParticle_sPHENIX/KFParticle_nTuple.cc
- offline/packages/KFParticle_sPHENIX/KFParticle_sPHENIX.cc
- offline/packages/KFParticle_sPHENIX/KFParticle_truthAndDetTools.cc
- offline/packages/KFParticle_sPHENIX/configure.ac
- offline/packages/tpccalib/TpcCentralMembraneMatching.cc
- offline/packages/tpccalib/TpcCentralMembraneMatching.h
- simulation/g4simulation/g4mvtx/Makefile.am
- simulation/g4simulation/g4mvtx/PHG4MvtxHitReco.cc
- simulation/g4simulation/g4mvtx/PHG4MvtxHitReco.h
This PR just catches up with the accumulated clang-tidy errors
> Clang tidy 12

- offline/packages/tpc/LaserClusterizer.cc
- offline/packages/tpc/LaserClusterizer.h
Added new histograms for time of hits that are put into debug file. These are necessary for calibration of laser T0 that goes into CDB
> Laser Clustering Calibration

- offline/packages/CaloEmbedding/CopyIODataNodes.cc
- offline/packages/CaloEmbedding/CopyIODataNodes.h
- offline/packages/mbd/MbdOut.h
- offline/packages/mbd/MbdOutV1.cc
- offline/packages/mbd/MbdOutV1.h
- offline/packages/mbd/MbdOutV2.cc
- offline/packages/mbd/MbdOutV2.h
Setup ability to copy MbdOut nodes for embedding purposes
> Copy nodes mbd

- offline/packages/mbd/Makefile.am
- offline/packages/mbd/MbdEvent.cc
- offline/packages/mbd/MbdEvent.h
- offline/packages/mbd/MbdReco.cc
- offline/packages/mbd/MbdReco.h
[comment]: Now can get MBD data from event combined DST
[comment]: MBD: added calopacket to be able to read from event combined dst
> MBD: added calopacket to be able to read from event combined dst

- offline/framework/fun4allraw/SingleCemcTriggerInput.cc
- offline/framework/fun4allraw/SingleHcalTriggerInput.cc
- offline/framework/fun4allraw/SingleMbdTriggerInput.cc
- offline/framework/fun4allraw/SinglePrdfInput.cc
- offline/framework/fun4allraw/SingleZdcInput.cc
- offline/framework/fun4allraw/SingleZdcTriggerInput.cc
the clock counter has changed from iValue to lValue in online. This PR adapts offline to it
> use lValue for CLOCK

- calibrations/calorimeter/calo_emc_noisy_tower/emcNoisyTowerFinder.cc
- calibrations/calorimeter/calo_emc_noisy_tower/emcNoisyTowerFinder.h
> streamlining emcal hot tower finder

- calibrations/intt/InttHitMap/InttHitMap.cc
- calibrations/intt/InttHitMap/InttHitMap.h
[comment]: <HitMap geneator is updated. The hitmap will be used to classified hot bad channels.> 
> InttHitMap.cc/h updated;  event counter and runnumber TTree added

- offline/packages/tpc/LaserClusterizer.cc
- offline/packages/tpc/LaserClusterizer.h
Addition of flag for laser clusterizer debug mode so that debug file is only generated when requested.
> Laser clusterizer debug

- calibrations/intt/InttHitMap/InttHitMap.cc
- calibrations/intt/InttHitMap/InttHitMap.h
- offline/QA/Tpc/Makefile.am
- offline/QA/Tpc/TpcChanQA.cc
- offline/QA/Tpc/TpcChanQA.h
- offline/QA/Tpc/configure.ac
- offline/packages/CaloReco/CaloTowerStatus.cc
- offline/packages/mbd/MbdEvent.h
- offline/packages/micromegas/MicromegasCombinedDataDecoder.cc
- offline/packages/micromegas/MicromegasCombinedDataDecoder.h
- offline/packages/micromegas/MicromegasRawDataDecoder.cc
- offline/packages/micromegas/MicromegasRawDataDecoder.h
- offline/packages/micromegas/MicromegasRawDataEvaluation.cc
- offline/packages/micromegas/MicromegasRawDataEvaluation.h
- offline/packages/tpc/LaserClusterizer.cc
- offline/packages/tpc/LaserClusterizer.h
- offline/packages/tpc/LaserClusterizerLinkDef.h
clang-tidy and memory leak fixes
> Jenkins fixes 2

- offline/framework/fun4allraw/SingleTpcPoolInput.cc
Fixed the production crash issue. There was one error that I missed. I also included checksumError check
for better data.
> Fixed the production crash issue

- calibrations/xingshift/Makefile.am
- calibrations/xingshift/XingShiftCal.cc
- calibrations/xingshift/XingShiftCal.h
- calibrations/xingshift/macros/Fun4All_xingshift.C
This PR adds the capability to write crossing shifts, spin patterns, polarizations, and fill numbers to the spinDB and the crossing shifts to a CDBTTree.
> spinDB and CDB write functionality

- simulation/g4simulation/g4mvtx/PHG4MvtxHitReco.cc
The sim logs are filled with messages which were put behind a verbosity flag for real data. Same is done now for the sims
> turn off annoying message which fills the simulation logs

- calibrations/calorimeter/calo_tower_slope/HCalCosmics.cc
- calibrations/calorimeter/calo_tower_slope/HCalCosmics.h
> cosmics analysis: adding small useful output to analysis

- offline/framework/ffarawmodules/ClockDiffCheck.cc
- offline/framework/fun4allraw/Fun4AllPrdfInputTriggerManager.cc
- offline/framework/fun4allraw/SingleMbdTriggerInput.cc
This PR puts the printouts for the triggered event combiner behind a verbosity setting
> Clock diff

- offline/QA/Jet/JetSeedCount.cc
- offline/QA/Jet/JetSeedCount.h
- offline/QA/Jet/Makefile.am
Adding code to QA/Jets used to monitor the jet seeds used in the iterative underlying event subtraction.
Adding the src code JetSeedCount.cc and JetSeedCount.h to jet QA module. This code is used to study various properties of the jet seeds used in underlying event subtraction in jet reconstruction. These plots study the jet seed at the level of the seeds themselves, both at the raw and subtracted level.
> Adding Code for Jet Seed QA into QA/Jet. 

- simulation/g4simulation/g4main/PHG4Reco.cc
- simulation/g4simulation/g4main/PHG4Reco.h
We lost the capability to run with constant field. This PR restores this for G4. Draft until I tested if this doesn't change the results of running with field
> restore constant field G4 running

- offline/QA/Jet/Makefile.am
- offline/QA/Jet/StructureinJets.cc
- offline/QA/Jet/StructureinJets.h
Orginallly was TracksInJets.cc/.h from /analysis/JS-Jet/TracksInJets/ but name was changed to avoid conflicts in coresoftware
This PR has two functions based on if you are doing AA or pp analyses. For AA, it produces histograms of the summed track pT, jet pT, and projects onto centrality {0,100,10} resulting 10 histos. If the flag is set to false, then a single pp histogram is produced (a TH2F) of only summed track pT and jet pT.  …
> New QA of tracks in jets StructureinJets.cc/.h

- offline/packages/TrackingDiagnostics/TrackResiduals.cc
- offline/packages/TrackingDiagnostics/TrackResiduals.h
- offline/packages/trackreco/PHActsTrkFitter.cc
- offline/packages/trackreco/PHSiliconHelicalPropagator.cc
- offline/packages/trackreco/PHSiliconHelicalPropagator.h
Adds code to run the Acts track fitting on the zero field data. Modifies the silicon propagator to have an optional line fit extender into the silicon. Adds a bunch of diagnostic tools to `TrackResiduals`.
https://github.com/sPHENIX-Collaboration/macros/pull/838
> feat: adapt for full zero field tracking

- calibrations/xingshift/XingShiftCal.cc
- calibrations/xingshift/macros/Fun4All_xingshift.C
This PR fixes a bug in the calculation of the crossing shift from the gl1p scalers. 
> Fix xingshift calculation

- offline/packages/TrackingDiagnostics/BeamCrossingAnalysis.cc
- offline/packages/TrackingDiagnostics/BeamCrossingAnalysis.h
Adds some quick look histograms to the BeamCrossingAnalysis module.
> Add some 1D histograms to BeamCrossingAnalysis

- calibrations/calorimeter/calo_emc_noisy_tower/emcNoisyTowerFinder.cc
- calibrations/calorimeter/calo_tower_slope/LiteCaloEval.cc
- calibrations/calorimeter/calo_tower_slope/LiteCaloEval.h
- offline/QA/Calorimeters/CaloValid.cc
- offline/packages/CaloReco/CaloTowerStatus.cc
- offline/packages/CaloReco/CaloTowerStatus.h
> a few small calo updates

- calibrations/calorimeter/calo_emc_noisy_tower/emcNoisyTowerFinder.h
> Adding hcal hot tower finder functionality 

- offline/packages/mbd/MbdReco.cc
[comment]: Moved MbdVertexMap to GLOBAL node from MBD node to make it more obvious where to find it.
> moved MbdVertexMap to GLOBAL node

- offline/packages/TrackingDiagnostics/TrackResiduals.cc
Fixes a seg fault for producing trees of silicon only track seeds
> fix: seg fault for silicon track analysis

- offline/packages/CaloReco/CaloWaveformFitting.cc
- offline/packages/CaloReco/CaloWaveformFitting.h
> ZS handling for FAST processing

- offline/packages/TrackingDiagnostics/TrackResiduals.cc
- offline/packages/trackbase/TrackFitUtils.cc
- offline/packages/trackbase/TrackFitUtils.h
- offline/packages/trackreco/PHActsSiliconSeeding.cc
- offline/packages/trackreco/PHActsSiliconSeeding.h
This makes the silicon seeder work better at connecting mvtx and intt clusters in real data, overcoming the real misalignment present. Opening a PR now to check if it breaks the production workflow...
https://github.com/sPHENIX-Collaboration/macros/pull/854
> feat: silicon seeding that works

- calibrations/calorimeter/calo_emc_pi0_tbt/pi0EtaByEta.cc
- calibrations/calorimeter/calo_emc_pi0_tbt/pi0EtaByEta.h
> updates phi/eta fit

- offline/packages/tpc/TpcClusterizer.cc
- offline/packages/tpc/TpcClusterizer.h
> add fixed window option and make it default

- offline/QA/Calorimeters/CaloValid.cc
- offline/QA/Calorimeters/CaloValid.h
It creates a QA histogram named `h_CaloValid_nodes_exists` that checks if the nodes exists for each nodes. Currently checking 11 nodes for its existence. Each bin of this histogram is assigned to each nodes.
Maybe need to look for standard way of naming histograms and where it should sit in. …
> QA histogram to check the nodes existence

- calibrations/calorimeter/calo_emc_pi0_tbt/pi0EtaByEta.cc
> fixing node name

- offline/framework/frog/CreateFileList.pl
This PR adds Detroit, PhotonJet5, PhotonJet10 and PhotonJet20 to the types, jenkins does not check this - so skipping jenkins [skip-ci]
> Add photnjets and detroit tune to CreateFileList.pl

- offline/packages/TrackingDiagnostics/TrackSeedTrackMapConverter.cc
> fix: assign pT for converted SvtxSeeds

- offline/packages/CaloReco/CaloTowerBuilder.cc
- offline/packages/CaloReco/CaloTowerBuilder.h
This PR is mostly for reduce the length of the towerbuilder code. Also a small fix for the memory leak for the PRDF case(hope this work).
> Make CaloTowerBuilder shorter, fix leak

- offline/framework/fun4allraw/SingleMicromegasPoolInput.cc
- offline/framework/fun4allraw/SingleMicromegasPoolInput.h
- offline/packages/micromegas/Makefile.am
- offline/packages/micromegas/MicromegasCombinedDataDecoder.cc
- offline/packages/micromegas/MicromegasCombinedDataEvaluation.cc
- offline/packages/micromegas/MicromegasMapping.cc
- offline/packages/micromegas/MicromegasMapping.h
- offline/packages/micromegas/MicromegasRawDataDecoder.cc
- offline/packages/micromegas/MicromegasRawDataEvaluation.cc
- offline/packages/micromegas/MicromegasRawDataEvaluation.h
- offline/packages/micromegas/MicromegasRawDataTimingEvaluation.cc
- offline/packages/micromegas/MicromegasRawDataTimingEvaluation.h
- offline/packages/micromegas/MicromegasRawDataTimingEvaluationLinkDef.h
- This make the necessary change to handle recent fiber swap in the IR in a backward compatible way
- some improvements on the Micromegas sub-event building, although still not there yet.
- add a dedicated module to evaluate GTM to FEE clock matching 
- 
> Micromegas decoding

- offline/packages/CaloReco/CaloTowerStatus.cc
> only reset bit that will be set in CaloTowerStatus

- offline/packages/trackreco/PHCASeeding.cc
- offline/packages/trackreco/PHCASeeding.h
> Scale the delta Z and delta phi windows in the clusterizer with the delta R between layers

- offline/packages/micromegas/MicromegasRawDataTimingEvaluation.cc
> Re-added fee_bco_predicted.

- offline/QA/Tracking/InttClusterQA.cc
- offline/QA/Tracking/InttClusterQA.h
- offline/QA/Tracking/MvtxClusterQA.cc
- offline/QA/Tracking/MvtxClusterQA.h
[comment]: <Cluster size and TrkrHitSet object (chip or half ladder) occupancy histograms for each of the silicon detectors. Also set the overly verbose histograms for each of the chips/sensors in each QA module to not be created by default> (Please tell us something about this pull request)
> New QA Plots for MVTX and INTT 

- offline/framework/ffarawmodules/LL1Check.cc
- offline/framework/ffarawobjects/LL1Packet.h
- offline/framework/ffarawobjects/LL1Packetv1.cc
- offline/framework/ffarawobjects/LL1Packetv1.h
- offline/framework/fun4allraw/SingleGl1TriggerInput.cc
- offline/framework/fun4allraw/SingleLL1TriggerInput.cc
- offline/framework/fun4allraw/mvtx_decoder/PayLoadCont.cc
- offline/packages/trackbase_historic/SvtxTrackInfo_v1.h
- offline/packages/trigger/LL1Outv1.cc
This PR finalizes the LL1 offline packet, dumps come out identical between online and offline LL1 packets
> Finalize ll1packet

- offline/packages/tpc/Makefile.am
- offline/packages/tpc/Tpc3DClusterizer.cc
- offline/packages/tpc/Tpc3DClusterizer.h
> first atempt at 3D clustering

- offline/packages/TrackingDiagnostics/TrackResiduals.cc
- offline/packages/TrackingDiagnostics/TrackResiduals.h
- offline/packages/tpc/TpcGlobalPositionWrapper.cc
- offline/packages/tpc/TpcGlobalPositionWrapper.h
Adds the beam crossing to TrackResiduals. Adds an option to TrackResiduals to skip clusters for which there is no matching state. 
> Data branch

- offline/QA/Calorimeters/CaloValid.cc
- offline/QA/Calorimeters/CaloValid.h
Added pedestal RMS and zero-suppressed RMS histograms in iphi and ieta.
> Added pedestal RMS and ZS RMS histograms

- offline/framework/fun4allraw/Fun4AllStreamingInputManager.cc
- offline/framework/fun4allraw/Makefile.am
- offline/framework/fun4allraw/SingleMicromegasPoolInput.cc
- offline/framework/fun4allraw/SingleMicromegasPoolInput.h
Modified Hugo's TPOT BCO cluster and waveform histograms to work with the QAHistogram Manager 
> Modify TPOT BCO QA information to work with existing infrastructure

- offline/framework/fun4allraw/Fun4AllStreamingInputManager.cc
- offline/packages/trigger/MinimumBiasClassifier.h
This PR patches the MinimumBiasClassifier so it doesn't crash with the current number of zdc channels. The zdc energy sum coming out of it is wrong, this just prevents our year1 (and year2 if this is added) macros from segfaulting 
> Fix minbias classifier

- offline/packages/CaloReco/CaloWaveformFitting.cc
- offline/packages/CaloReco/CaloWaveformFitting.h
- offline/packages/CaloReco/CaloWaveformProcessing.cc
- offline/packages/CaloReco/CaloWaveformProcessing.h
A new processing method using Nyquist interpolation to find the peak. 
This PR won't change any default processing. 
> Nyquist interpolation waveform processing method

- offline/framework/fun4allraw/Fun4AllStreamingInputManager.cc
This PR fixes a memory leak in the TPOT qa, it's a typo - no jenkins check needed [skip-ci]
> fix memory leak from tpot qa

- offline/framework/fun4allraw/Fun4AllStreamingInputManager.cc
Reverts sPHENIX-Collaboration/coresoftware#2842 [skip-ci]
> Revert "fix memory leak from tpot qa"

- offline/packages/CaloReco/CaloWaveformFitting.h
That one slipped by, merged this even though jenkins failed in clang. This PR fixes the clang complaint, not running jenkins [skip-ci]
> comment out unused variable

- offline/packages/trackreco/PHCASeeding.cc
- offline/packages/trackreco/PHCASeeding.h
[comment]:  Add an option to grow seeds while skipping split clusters (and just use the median cluster location in growth). It helps reduce prohibitive combinatorics.
> Nosplitseeds

- offline/packages/tpc/Tpc3DClusterizer.cc
- offline/packages/trackreco/Makefile.am
- offline/packages/trackreco/PHStreakFinder.cc
- offline/packages/trackreco/PHStreakFinder.h
> PHstreakFinder first working version

- offline/packages/CaloBase/Makefile.am
- offline/packages/CaloBase/TowerInfoContainerv4.cc
- offline/packages/CaloBase/TowerInfoContainerv4.h
- offline/packages/CaloBase/TowerInfoContainerv4LinkDef.h
- offline/packages/CaloBase/TowerInfov4.cc
- offline/packages/CaloBase/TowerInfov4.h
- offline/packages/CaloBase/TowerInfov4LinkDef.h
- offline/packages/CaloReco/CaloTowerBuilder.cc
- offline/packages/CaloReco/CaloTowerDefs.h
> Towerinfov4 slimmed down tower objects for high lumi running 

- offline/packages/CaloBase/TowerInfoDefs.cc
- offline/packages/CaloBase/TowerInfoDefs.h
- offline/packages/CaloReco/CaloTowerBuilder.cc
Expand calotowerbuilder to 128 channels. Packet remains 1. Mask all but 52 channels.
> Update CaloTowerBuilder.cc for zdc/smd/vetoc towers

- offline/packages/TrackingDiagnostics/TrkrNtuplizer.cc
> fix crashes due to new way of accessing vexmap

- offline/framework/fun4allraw/MicromegasBcoMatchingInformation.cc
- offline/framework/fun4allraw/SingleMicromegasPoolInput.cc
- offline/framework/fun4allraw/SingleMicromegasPoolInput.h
- offline/packages/micromegas/MicromegasRawDataEvaluation.cc
- offline/packages/micromegas/MicromegasRawDataEvaluation.h
- offline/packages/micromegas/MicromegasRawDataTimingEvaluation.cc
- offline/packages/micromegas/MicromegasRawDataTimingEvaluation.h
- Store list of dropped waveforms (that is: not associated to a proper GTM BCO) in per-packet lists. 
- implemented JN QA histogram
- 
> Micromegas qa

- offline/packages/TrackingDiagnostics/TrackResiduals.cc
Try again with correct commit history - fixes a seg fault in the cosmics workflow in prep for the TPC nitrogen test analysis
> fix: cosmics seg fault

- offline/packages/CaloReco/CaloTowerBuilder.cc
- offline/packages/CaloReco/CaloTowerBuilder.h
- offline/packages/CaloReco/CaloWaveformFitting.cc
- offline/packages/CaloReco/CaloWaveformFitting.h
- offline/packages/CaloReco/CaloWaveformProcessing.cc
- offline/packages/CaloReco/CaloWaveformProcessing.h
> Adjustable template fit limits

- calibrations/calorimeter/calo_emc_noisy_tower/emcNoisyTowerFinder.cc
> adding cdb output and bug fix

- offline/QA/Calorimeters/CaloValid.cc
- offline/QA/Calorimeters/Makefile.am
> adding trigger vector hist to CaloValid

- offline/packages/tpc/LaserClusterizer.cc
- offline/packages/tpc/LaserClusterizer.h
- offline/packages/tpccalib/TpcCentralMembraneMatching.cc
- offline/packages/tpccalib/TpcCentralMembraneMatching.h
- offline/packages/trackbase/LaserCluster.h
- offline/packages/trackbase/LaserClusterContainer.h
- offline/packages/trackbase/LaserClusterv1.cc
- offline/packages/trackbase/LaserClusterv1.h
Changed radial matching scheme for CM distortions to include linear radial dependence.
Added various QA variables to the LaserClusters and modified code to fill these.
Matching debug tree now contains unmatched clusters (these have truthIndex==-1) and a bunch of new QA variables
> Radial dependence for CM distortions

- offline/framework/fun4allraw/SingleMicromegasPoolInput.cc
> Check RCDAQ event type before updating the runnumber.

- offline/framework/ffarawobjects/Makefile.am
- offline/framework/ffarawobjects/MvtxFeeIdInfo.h
- offline/framework/ffarawobjects/MvtxFeeIdInfoLinkDef.h
- offline/framework/ffarawobjects/MvtxFeeIdInfov1.cc
- offline/framework/ffarawobjects/MvtxFeeIdInfov1.h
- offline/framework/ffarawobjects/MvtxFeeIdInfov1LinkDef.h
- offline/framework/ffarawobjects/MvtxRawEvtHeader.h
- offline/framework/ffarawobjects/MvtxRawEvtHeaderv1.h
- offline/framework/ffarawobjects/MvtxRawEvtHeaderv2.cc
- offline/framework/ffarawobjects/MvtxRawEvtHeaderv2.h
- offline/framework/ffarawobjects/MvtxRawEvtHeaderv2LinkDef.h
- offline/framework/fun4allraw/Fun4AllStreamingInputManager.cc
- offline/framework/fun4allraw/Fun4AllStreamingInputManager.h
- offline/framework/fun4allraw/SingleMvtxPoolInput.cc
- offline/framework/fun4allraw/mvtx_decoder/GBTLink.h
- offline/framework/fun4allraw/mvtx_pool.cc
- offline/packages/mvtx/Makefile.am
- offline/packages/mvtx/MvtxNoiseMap.cc
- offline/packages/mvtx/MvtxNoiseMap.h
- offline/packages/mvtx/MvtxNoiseMapLinkDef.h
This PR adds a new version for the MVTX raw event header, including FeeId and strobe BCO information independent of the event containing hit.
> Create a new Raw Event header with feeid information and strobe bco per events. 

- offline/QA/Tracking/Makefile.am
- offline/QA/Tracking/SiliconSeedsQA.cc
- offline/QA/Tracking/SiliconSeedsQA.h
QA checks for quick silicon-only tracking (MVTX+INTT)
> Silicon tracklets QA module

- offline/packages/CaloReco/CaloTowerStatus.cc
- offline/packages/CaloReco/CaloTowerStatus.h
New Chi2 cut for bad waveform template fit status. This prevent us from cutting out good high energy towers.
> new chi2 cut

- offline/QA/Tracking/MvtxClusterQA.cc
- offline/QA/Tracking/TpcClusterQA.cc
> New MVTX Strobe histogram and update to TPC phisize histograms

- generators/PHPythia6/Makefile.am
- generators/PHPythia6/PHPy6ForwardElectronTrig.cc
- generators/PHPythia6/PHPy6ForwardElectronTrig.h
- generators/PHPythia6/PHPy6GenTrigger.cc
- generators/PHPythia6/PHPy6GenTrigger.h
- generators/PHPythia6/PHPy6JetTrigger.cc
- generators/PHPythia6/PHPy6JetTrigger.h
- generators/PHPythia6/PHPy6ParticleTrigger.cc
- generators/PHPythia6/PHPy6ParticleTrigger.h
- generators/PHPythia6/PHPythia6.cc
- offline/framework/fun4allraw/SingleMvtxPoolInput.cc
- offline/packages/intt/INTTXYvtx.cc
- offline/packages/intt/INTTXYvtx.h
- offline/packages/intt/INTTZvtx.cc
- simulation/g4simulation/g4tpc/PHG4TpcPadPlaneReadout.h
This PR applies fixes for clang-tidy and cppcheck, the one for the mvtx pool inpit manager might actually speed this up a tiny bit
> Cppcheck fixes

- offline/QA/Tracking/SiliconSeedsQA.h
> [Fix] define guard of SiliconSeedsQA

- offline/QA/Tracking/Makefile.am
- offline/QA/Tracking/TpcSeedsQA.cc
- offline/QA/Tracking/TpcSeedsQA.h
> yuxd: add QA module TpcSeedsQA

- offline/framework/ffarawmodules/ClockDiffCheck.cc
- offline/framework/ffarawmodules/ZdcCheck.cc
- offline/framework/fun4allraw/Fun4AllPrdfInputTriggerManager.cc
- offline/framework/fun4allraw/Fun4AllPrdfInputTriggerManager.h
- offline/framework/fun4allraw/SingleZdcTriggerInput.cc
This PR had a functional resyncing for the zdc (event missing at the first event)- the rest of the packets will come with the next PRl
> Resync triggered

- generators/sHijing/xml_test.cc
This PR fixes the last clang-tidy error. It is from unused test code, but hey - it's good practice to figure these out. Since it is unused - no jenkins running needed [skip-ci]
> fix final clang-tidy error

- offline/framework/fun4allraw/Fun4AllPrdfInputTriggerManager.cc
- offline/framework/fun4allraw/Fun4AllPrdfInputTriggerManager.h
- offline/framework/fun4allraw/SingleCemcTriggerInput.cc
- offline/framework/fun4allraw/SingleCemcTriggerInput.h
- offline/framework/fun4allraw/SingleGl1TriggerInput.cc
- offline/framework/fun4allraw/SingleGl1TriggerInput.h
- offline/framework/fun4allraw/SingleHcalTriggerInput.cc
- offline/framework/fun4allraw/SingleHcalTriggerInput.h
- offline/framework/fun4allraw/SingleLL1TriggerInput.cc
- offline/framework/fun4allraw/SingleLL1TriggerInput.h
- offline/framework/fun4allraw/SingleMbdTriggerInput.cc
- offline/framework/fun4allraw/SingleMbdTriggerInput.h
- offline/framework/fun4allraw/SingleTriggerInput.cc
- offline/framework/fun4allraw/SingleTriggerInput.h
- offline/framework/fun4allraw/SingleZdcTriggerInput.cc
- offline/framework/fun4allraw/SingleZdcTriggerInput.h
This PR introduces the first functional event combiner for our triggered system  (if the first event is out of sync for some subsystems) which should take care of a major fraction of our problems
> Resync singleinputs

- offline/framework/fun4allraw/Fun4AllStreamingInputManager.cc
- offline/framework/fun4allraw/Fun4AllStreamingInputManager.h
- offline/framework/fun4allraw/SingleGl1PoolInput.cc
- offline/framework/fun4allraw/SingleGl1PoolInput.h
This PR finally creates the GL1 offline packets instead of the reduced Gl1Rawhit for streaming so we can finally access the trigger info in the streaming output
> move from Gl1RawHit to Gl1Packet for streaming

- offline/packages/CaloReco/CaloTowerBuilder.cc
> allow for backward compatibility  in zdc tower building  for runs with 64 channels/packet

- offline/QA/Tracking/SiliconSeedsQA.cc
- offline/QA/Tracking/SiliconSeedsQA.h
- offline/QA/Tracking/TpcSeedsQA.h
- offline/packages/trackreco/PHSimpleVertexFinder.cc
- offline/packages/trackreco/PHSimpleVertexFinder.h
Adds map name setters to the various modules so that these QA modules can be properly integrated into production
> feat: add map name setters

- offline/packages/tpc/TpcCombinedRawDataUnpacker.cc
- offline/packages/tpc/TpcCombinedRawDataUnpacker.h
> add feewise baseline subtraction

- offline/packages/intt/InttCombinedRawDataDecoder.cc
- offline/packages/mvtx/MvtxCombinedRawDataDecoder.cc
Use Gl1Packet instead of Gl1RawHit according to [the merged PR](https://github.com/sPHENIX-Collaboration/coresoftware/pull/2898)
> Change to Gl1Packet

- offline/QA/Calorimeters/CaloValid.cc
> adding mbd hits  hist

- offline/packages/tpc/TpcClusterizer.cc
- offline/packages/tpc/TpcClusterizer.h
> add option to drop single pixel hits

- offline/QA/Mvtx/Makefile.am
- offline/QA/Mvtx/MvtxRawHitQA.cc
- offline/QA/Mvtx/MvtxRawHitQA.h
- offline/QA/Mvtx/autogen.sh
- offline/QA/Mvtx/configure.ac
> yuxd: Add MvtxRawHitQA module

- generators/sphstarlight/Makefile.am
- generators/sphstarlight/StarLight_To_HepMc.cc
- generators/sphstarlight/autogen.sh
- generators/sphstarlight/configure.ac
Convert starlight output to HepMC
> Convert starlight output to HepMC

- offline/QA/Intt/InttQaCommon.h
- offline/QA/Intt/InttRawHitQA.cc
- offline/QA/Intt/InttRawHitQA.h
- offline/QA/Intt/Makefile.am
- offline/QA/Intt/TH2INTT.cc
- offline/QA/Intt/TH2INTT.h
- offline/QA/Intt/autogen.sh
- offline/QA/Intt/configure.ac
Add INTT raw hit QA module
Add INTT raw hit QA module, referring to https://github.com/sPHENIX-Collaboration/INTT/blob/main/QA_codes/InttQA/InttRawHitQA.cc
> yuxd: Add InttRawHitQA module

- offline/QA/Tracking/TpcSeedsQA.cc
- offline/QA/Tracking/TpcSeedsQA.h
Update TpcSeedsQA module
1. add pT>1GeV cut for most hists
2. add track pT distribution
3. delete TPC-only beam crossing hists
> yuxd: update TpcSeedsQA

- simulation/g4simulation/g4tpc/PHG4TpcPadPlaneReadout.cc
- simulation/g4simulation/g4tpc/PHG4TpcPadPlaneReadout.h
This PR adds the functionality to G4TPC for sampling GEM gains from a Polya distribution.
> sample GEM gains from Polya distribution

- offline/QA/Intt/InttRawHitQA.cc
- offline/QA/Intt/InttRawHitQA.h
In previous PR, some histograms are Scale/Fill/SetBinContent in EndRun function. However, the changes are not updated in output QA root file. In this PR, we move all the command in process_event fucntion.
> yuxd: fix bugs in InttRawHitQA

- offline/QA/Intt/InttQaCommon.h
- offline/QA/Intt/InttRawHitQA.cc
- offline/QA/Intt/InttRawHitQA.h
- offline/QA/Intt/TH2INTT.cc
- offline/QA/Intt/TH2INTT.h
- offline/QA/Intt/configure.ac
- offline/packages/tpc/TpcCombinedRawDataUnpacker.cc
- offline/packages/tpc/TpcCombinedRawDataUnpacker.h
Playing catchup again with accumulated cppcheck errors
> Fix ccpcheck 2

- simulation/g4simulation/g4tpc/PHG4TpcPadPlaneReadout.cc
This PR speeds up the sampling of the polya distribution for G4TPC GEM gains.
> dal - speed up Polya sampling for G4TPC 

- calibrations/calorimeter/calo_emc_pi0_tbt/Makefile.am
- calibrations/calorimeter/calo_emc_pi0_tbt/pi0EtaByEta.cc
- calibrations/calorimeter/calo_emc_pi0_tbt/pi0EtaByEta.h
> pi0 calib: adding minbias req

- offline/framework/fun4allraw/SingleInttPoolInput.cc
- offline/framework/fun4allraw/SingleMicromegasPoolInput.cc
- offline/framework/fun4allraw/SingleMvtxPoolInput.cc
- offline/framework/fun4allraw/SingleTpcPoolInput.cc
This PR fixes invalid reads in the streaming poolers.
> fix: pooling invalid reads

- offline/QA/Jet/ConstituentsinJets.cc
- offline/QA/Jet/ConstituentsinJets.h
- offline/QA/Jet/JetKinematicCheck.cc
- offline/QA/Jet/JetKinematicCheck.h
- offline/QA/Jet/JetQADefs.h
- offline/QA/Jet/JetSeedCount.cc
- offline/QA/Jet/JetSeedCount.h
- offline/QA/Jet/RhosinEvent.cc
- offline/QA/Jet/RhosinEvent.h
- offline/QA/Jet/StructureinJets.cc
- offline/QA/Jet/TrksInJetQA.cc
- offline/QA/Jet/TrksInJetQABaseManager.cc
- offline/packages/particleflow/Makefile.am
- offline/packages/particleflow/ParticleFlowElement.h
- offline/packages/particleflow/ParticleFlowElementContainer.cc
- offline/packages/particleflow/ParticleFlowElementContainer.h
- offline/packages/particleflow/ParticleFlowElementv1.cc
- offline/packages/particleflow/ParticleFlowElementv1.h
- offline/packages/particleflow/ParticleFlowJetInput.cc
- offline/packages/particleflow/ParticleFlowJetInput.h
- offline/packages/particleflow/ParticleFlowReco.cc
- offline/packages/particleflow/ParticleFlowReco.h
- offline/packages/particleflow/configure.ac
This PR gets the cppcheck warnings back to zero
> Fix cppcheck 2

- offline/QA/SimulationModules/QAG4SimulationTracking.cc
- offline/QA/SimulationModules/QAG4SimulationTruthDecay.cc
- offline/QA/SimulationModules/QAG4SimulationTruthDecay.h
- offline/QA/SimulationModules/QAG4SimulationUpsilon.cc
- offline/framework/ffarawmodules/ClockDiffCheck.cc
- offline/framework/ffarawmodules/ClockDiffCheck.h
- offline/framework/fun4allraw/SingleCemcTriggerInput.cc
- offline/framework/fun4allraw/SingleCemcTriggerInput.h
- offline/framework/fun4allraw/SingleGl1TriggerInput.cc
- offline/framework/fun4allraw/SingleGl1TriggerInput.h
- offline/framework/fun4allraw/SingleHcalTriggerInput.cc
- offline/framework/fun4allraw/SingleHcalTriggerInput.h
- offline/framework/fun4allraw/SingleLL1TriggerInput.cc
- offline/framework/fun4allraw/SingleLL1TriggerInput.h
- offline/framework/fun4allraw/SingleMbdTriggerInput.cc
- offline/framework/fun4allraw/SingleMbdTriggerInput.h
- offline/framework/fun4allraw/SingleTriggerInput.cc
- offline/framework/fun4allraw/SingleTriggerInput.h
- offline/framework/fun4allraw/SingleZdcTriggerInput.cc
- offline/framework/fun4allraw/SingleZdcTriggerInput.h
The content of the needle array was duplicated, this doesn't affect the matching for the first event but needs to be fixed for the next steps.
> Fix size of needle array

- offline/packages/CaloReco/CaloTowerStatus.cc
> adding output to alert a hot map exists

- calibrations/calorimeter/calo_tower_slope/LiteCaloEval.cc
- calibrations/calorimeter/calo_tower_slope/LiteCaloEval.h
- calibrations/calorimeter/calo_tower_slope/Makefile.am
> TSC: adding minbias requirement 

- offline/framework/fun4allraw/Fun4AllStreamingInputManager.cc
- offline/framework/fun4allraw/Makefile.am
- offline/framework/fun4allraw/MvtxRawDefs.cc
- offline/framework/fun4allraw/MvtxRawDefs.h
- offline/framework/fun4allraw/SingleMvtxPoolInput.cc
- offline/framework/fun4allraw/SingleMvtxPoolInput.h
This PR adds a header with MVTX definitions and mapping.
> ycm - Add header with MVTX defs auxiliar arrays and functions

- offline/framework/fun4allraw/Fun4AllStreamingInputManager.cc
- offline/framework/fun4allraw/MvtxRawDefs.cc
- offline/framework/fun4allraw/MvtxRawDefs.h
- offline/packages/tpccalib/PHTpcResiduals.cc
- offline/packages/tpccalib/PHTpcResiduals.h
- offline/packages/tpccalib/TpcCentralMembraneMatching.cc
- offline/packages/tpccalib/TpcCentralMembraneMatching.h
- offline/packages/tpccalib/TpcDirectLaserReconstruction.cc
- offline/packages/tpccalib/TpcDirectLaserReconstruction.h
- offline/packages/tpccalib/TpcSpaceChargeMatrixContainerv1.cc
- offline/packages/tpccalib/TpcSpaceChargeMatrixContainerv1.h
- offline/packages/tpccalib/TpcSpaceChargeReconstruction.cc
- offline/packages/tpccalib/TpcSpaceChargeReconstruction.h
- simulation/g4simulation/g4trackfastsim/Makefile.am
- simulation/g4simulation/g4trackfastsim/PHG4TrackFastSim.cc
- simulation/g4simulation/g4trackfastsim/PHG4TrackFastSim.h
- simulation/g4simulation/g4trackfastsim/PHG4TrackFastSimEval.cc
- simulation/g4simulation/g4trackfastsim/PHG4TrackFastSimEval.h
fixing the most recent clang-tidy newcomers plus old ones.
> Fix clang tidy 15

- calibrations/tpc/fillSpaceChargeMaps/Shifter.cc
- calibrations/tpc/fillSpaceChargeMaps/Shifter.h
- calibrations/tpc/fillSpaceChargeMaps/fillSpaceChargeMaps.cc
- calibrations/tpc/fillSpaceChargeMaps/fillSpaceChargeMaps.h
- offline/packages/zdcinfo/Makefile.am
- offline/packages/zdcinfo/ZdcReco.cc
- offline/packages/zdcinfo/ZdcReco.h
- offline/packages/zdcinfo/Zdcinfo.h
- offline/packages/zdcinfo/Zdcinfov1.cc
- offline/packages/zdcinfo/Zdcinfov1.h
> Fix clang tidy 16

- offline/packages/TrackingDiagnostics/TrackResiduals.cc
- offline/packages/TrackingDiagnostics/TrkrNtuplizer.cc
> adding track angle correction to dedx calc

- offline/QA/Global/GlobalQA.cc
- offline/QA/Global/GlobalQA.h
- offline/QA/Global/Makefile.am
- offline/QA/Global/autogen.sh
- offline/QA/Global/configure.ac
> sfl - added MBD and ZDC QA plots

- offline/QA/Mvtx/MvtxRawHitQA.cc
- offline/QA/Mvtx/MvtxRawHitQA.h
Add Hitmap for layer 0,1,2 in MvtxRawHitQA module
> Add hitmap in MvtxRawHitQA module

- calibrations/tpc/TPCPedestalCalibration/TPCPedestalCalibration.cc
- calibrations/tpc/TPCPedestalCalibration/TPCPedestalCalibration.h
- offline/framework/ffarawmodules/ClockDiffCheck.cc
- offline/framework/phoolraw/PHRawDataNode.cc
- offline/framework/phoolraw/PHRawOManager.cc
- offline/framework/phoolraw/PHRawOManager.h
- offline/packages/jetbase/TowerJetInput.cc
- offline/packages/jetbase/TowerJetInput.h
> Clang tidy 17

- offline/packages/mbd/MbdEvent.cc
- offline/packages/mbd/MbdEvent.h
- offline/packages/mbd/MbdReco.cc
- offline/packages/mbd/MbdReco.h
- offline/packages/mbd/MbdSig.cc
[comment]: Since the gaussian fit to the hit time distribution in an arm could fail drastically if the calibrations were bad (giving wild results), we switched to a truncated mean to get the arm hit time.
> switched algorithm for arm time from gaussian fit to truncated mean

- calibrations/calorimeter/calo_emc_noisy_tower/emcNoisyTowerFinder.cc
- calibrations/calorimeter/calo_emc_noisy_tower/emcNoisyTowerFinder.h
> Hot tower finder: bug fix and better outlier detection

- offline/QA/Calorimeters/CaloValid.cc
- offline/QA/Calorimeters/Makefile.am
- offline/packages/zdcinfo/ZdcReco.cc
- offline/packages/zdcinfo/ZdcReco.h
- offline/packages/zdcinfo/Zdcinfo.h
- offline/packages/zdcinfo/Zdcinfov1.cc
- offline/packages/zdcinfo/Zdcinfov1.h
add get radius functionality to zdc reco for use outside of module
> add get radius functionality for zdc reco

- offline/framework/fun4allraw/SingleTpcPoolInput.cc
- offline/packages/tpc/LaserClusterizer.cc
Changed number of samples in TPC pooling to 425. Made changes in Lase…r clusterizer to propage change to number of samples throughout code
> TPC Pooling Samples

- offline/framework/fun4allraw/mvtx_decoder/GBTLink.h
- offline/framework/fun4allraw/mvtx_decoder/mvtx_utils.h
- offline/framework/fun4allraw/mvtx_pool.cc
This PR adds a sanity check for testing Raw Data header.
> ycm - add more sanity checks for RDH

- offline/QA/Global/GlobalQA.cc
- offline/QA/Global/GlobalQA.h
> adding GL1 - EMCal alignment check to GlobalQA

- offline/QA/Global/GlobalQA.cc
- offline/QA/Global/GlobalQA.h
- offline/QA/Global/Makefile.am
- plots from  [PR#2971](https://github.com/sPHENIX-Collaboration/coresoftware/pull/2971) added here after discussion with Blair and Sam. Do not merge PR 2971 (potential merge conflict)
- update with new zdc object
> update GlobalQA-- re-add mbd null vertex count plot, update zdc plots

- simulation/g4simulation/g4dst/Makefile.am
- simulation/g4simulation/g4eval/Makefile.am
This PR adds a few io libraries to our g4dst convenience lib so it stays the only library which needs loading when reading any of our DSTs
> Add iolibs g4dst

- offline/QA/Jet/ConstituentsinJets.cc
- offline/QA/Jet/JetKinematicCheck.cc
- offline/QA/Jet/JetSeedCount.cc
- offline/QA/Jet/JetSeedCount.h
- offline/QA/Jet/RhosinEvent.cc
- offline/QA/Jet/StructureinJets.cc
some new clang-tidy warnings made it through 
> clang-tidy for QA/Jet

- offline/QA/Global/GlobalQA.cc
> adding event number for gl1-emcal alignment tracking

- offline/QA/Global/GlobalQA.cc
> GQA: bug fix

- offline/packages/CaloReco/RawClusterBuilderTopo.cc
- offline/packages/CaloReco/RawClusterBuilderTopo.h
- Adding bad towers rejection by checking isGood flag of TowerInfo objects
> Adding bad towers rejection

- simulation/g4simulation/g4eval/CaloTruthEval.cc
- simulation/g4simulation/g4eval/CaloTruthEval.h
- simulation/g4simulation/g4eval/DSTTrackInfoWriter.cc
- simulation/g4simulation/g4eval/DSTTrackInfoWriter.h
- simulation/g4simulation/g4eval/FillClusMatchTree.cc
- simulation/g4simulation/g4eval/FillClusMatchTree.h
- simulation/g4simulation/g4eval/FillTruthRecoMatchMap.cc
- simulation/g4simulation/g4eval/FillTruthRecoMatchMap.h
- simulation/g4simulation/g4eval/TrackClusEvaluator.cc
- simulation/g4simulation/g4eval/TrackClusEvaluator.h
- simulation/g4simulation/g4eval/TruthRecoTrackMatching.cc
> Clang tidy 19

- offline/framework/fun4allraw/SingleTpcPoolInput.cc
- offline/framework/fun4allraw/SingleTpcPoolInput.h
> add setters for tpc readout range

- offline/packages/TrackingDiagnostics/TrackResiduals.cc
- offline/packages/TrackingDiagnostics/TrackResiduals.h
Adds the gl1packet info to track residuals to access trigger information
> feat: add trigger info to track residuals

- generators/PHPythia6/PHPythia6.cc
- offline/packages/CaloReco/RawClusterBuilderTopo.cc
- offline/packages/CaloReco/RawClusterBuilderTopo.h
[comment]: Small fix to our wrapper around Pythia6 - discussed here in the ColdQCD MatterMost: https://chat.sdcc.bnl.gov/sphenix/pl/f4nhuy5tct8umc6hg5ybjmbkdr
> Fix PHPythia6 to save Q, rather than Q^2, in the HepMC::PdfInfo

- offline/framework/fun4allraw/Fun4AllStreamingInputManager.cc
Hides print statement behind verbosity that clogs up log files
> fix: hide verbosity

- offline/framework/fun4allraw/Fun4AllPrdfInputTriggerManager.cc
- offline/framework/fun4allraw/SingleGl1TriggerInput.cc
This PR limits the number of printouts for duplicate GL1 packets to 1k which should reduce our logs drastically
> print 1k message with gl1 duplicate packet id

- offline/QA/Tpc/Makefile.am
- offline/QA/Tpc/TpcRawHitQA.cc
- offline/QA/Tpc/TpcRawHitQA.h
Modeled after the MVTX and INTT's similar modules, histogram ranges may need to be adjusted in the future but seems to look good for now, new plots for this coming soon as well
> New TpcRawHitQA module

- calibrations/calorimeter/calo_emc_noisy_tower/emcNoisyTowerFinder.cc
> hotTowerFinder: HCal bug fix

- calibrations/xingshift/XingShiftCal.cc
- calibrations/xingshift/XingShiftCal.h
This PR provides functionality in xingshift to perform preliminary quality assurance on the spin database and write to the badrun column. 
> xingshift - Spin DB Quality Assurance 

- offline/packages/TrackerMillepedeAlignment/HelicalFitter.cc
- offline/packages/TrackingDiagnostics/TrackResiduals.cc
Modify HelicalFitter to add INTT z position to mille file, and require a minimum of 5 silicon clusters per track. Modify Trackresiduals to not drop clusters without a matching state, just set the state variables to NaNs.
> Mods to TrackResiduals and HelicalFitter

- offline/packages/particleflow/ParticleFlowReco.cc
- offline/packages/particleflow/ParticleFlowReco.h
This module is not creating its node since last update. I included InitRun function back with the CreateNode() function so that the ParticleFlowElements container is added to the node.
> Fixing CreateNode not being called

- offline/QA/Global/GlobalQA.cc
> Dev global qa

- offline/packages/CaloBase/TowerInfoDefs.cc
updating towerinfo defs for the EPD to match the data, e.g. see (fig 2) https://sphenix-invenio.sdcc.bnl.gov/uploads/0m29t-1v983
> update epd channels to match the data

- offline/packages/TrackingDiagnostics/TrackResiduals.cc
- offline/packages/TrackingDiagnostics/TrackResiduals.h
- offline/packages/trackreco/PHCosmicSiliconPropagator.cc
- offline/packages/trackreco/PHCosmicTrackMerger.cc
- offline/packages/trackreco/PHCosmicTrackMerger.h
This fixes up and improves the cosmic reconstruction with field on in prep for the isobutane data coming soon.
[ex_track.pdf](https://github.com/user-attachments/files/16363393/ex_track.pdf)
[ex_trackyz.pdf](https://github.com/user-attachments/files/16363394/ex_trackyz.pdf)
> feat: cosmic field on reconstruction

- offline/QA/Global/GlobalQA.cc
- offline/QA/Global/GlobalQA.h
added cuts to clusters and use correct zdc towers
> added cuts to clusters

- generators/sHijing/xml_test.cc
This PR applies a minor fix to sHijing (for a source which isn't even compiled)
> clang-tidy for sHijing

- simulation/g4simulation/g4mvtx/PHG4MvtxDefs.h
This PR fixes the initial MVTX phi rotation to match with final mechanic design values.
> ycm - change mvtx layer phi0 rotation

- offline/framework/fun4all/Fun4AllDstOutputManager.cc
- offline/framework/fun4all/Fun4AllOutputManager.h
This sets the number of digits for the segment when using a file rule to 5, provision to make this configurable but this will come later when I can actually test this. It needs to go into todays build
> 5digit segment

- offline/framework/ffarawmodules/ClockDiffCheck.cc
- offline/framework/fun4allraw/Fun4AllPrdfInputTriggerManager.cc
- offline/framework/fun4allraw/Fun4AllPrdfInputTriggerManager.h
- offline/framework/fun4allraw/SingleCemcTriggerInput.cc
- offline/framework/fun4allraw/SingleCemcTriggerInput.h
- offline/framework/fun4allraw/SingleHcalTriggerInput.cc
- offline/framework/fun4allraw/SingleHcalTriggerInput.h
- offline/framework/fun4allraw/SingleTriggerInput.cc
- offline/framework/fun4allraw/SingleTriggerInput.h
This PR adds the recovery from FEM clock counter mismatches for the cemc and the hcals. It works for run 45711 where packet 6001 as this issue. Still need to work on flagging the first event for missing data. The sepd is not handled yet (since its data is combined with the zdc it's not a simple cut and paste job …
> Fem clock fix

- offline/framework/ffarawmodules/ClockDiffCheck.cc
- offline/framework/fun4allraw/Fun4AllPrdfInputTriggerManager.cc
- offline/framework/fun4allraw/SingleCemcTriggerInput.cc
- offline/framework/fun4allraw/SingleCemcTriggerInput.h
- offline/framework/fun4allraw/SingleHcalTriggerInput.cc
- offline/framework/fun4allraw/SingleHcalTriggerInput.h
- offline/framework/fun4allraw/SingleZdcTriggerInput.cc
- offline/framework/fun4allraw/SingleZdcTriggerInput.h
This adds the sepd to the fem clock check/recovery. Also for the Cemc sets the packet fem clocks and event numbers to the majority (packet 6057 has fem clock issues in one channel, 6024 has an event number offset in on channel)
> Sepd fem clock

- offline/packages/CaloReco/BEmcCluster.cc
- offline/packages/CaloReco/BEmcProfile.cc
- offline/packages/CaloReco/BEmcRec.cc
- offline/packages/CaloReco/BEmcRecCEMC.cc
- offline/packages/CaloReco/BEmcRecCEMC.h
- offline/packages/CaloReco/Makefile.am
- offline/packages/CaloReco/RawClusterBuilderGraph.cc
- offline/packages/CaloReco/RawClusterPositionCorrection.cc
- offline/packages/CaloReco/RawTowerDeadTowerInterp.cc
- simulation/g4simulation/g4jets/JetHepMCLoader.cc
- simulation/g4simulation/g4jets/JetHepMCLoader.h
- simulation/g4simulation/g4jets/Makefile.am
- simulation/g4simulation/g4jets/TruthJetInput.cc
- simulation/g4simulation/g4jets/TruthJetInput.h
More clang-tidy fixes, CaloReco and g4jets are clean now
> Clang tidy 20

- offline/packages/trackbase/TrkrDefs.h
We don't have a ttl, and this causes confusion
> fix: remove ttl

- offline/framework/fun4allraw/Fun4AllStreamingInputManager.cc
- offline/framework/fun4allraw/SingleMvtxPoolInput.h
- offline/framework/fun4allraw/SingleStreamingInput.h
- offline/packages/intt/InttCombinedRawDataDecoder.h
- offline/packages/tpc/TpcCombinedRawDataUnpacker.h
This enables parallelized event combining and hit unpacking. It dramatically speeds up the entire process to be able to process each PRDF separately. The default behavior remains the same as this will wreak havoc on the production without further changes in the production scripts first.
> feat: Parallelize event combining

- offline/packages/trackreco/PHSiliconTpcTrackMatching.h
Adds getters so that the qa module can grab the cut values and make some sequential histograms that show the effects of the cuts
> feat: phtpcsilicon matching window getters

- offline/QA/Intt/InttStreamQA.cc
- offline/QA/Intt/InttStreamQA.h
- offline/QA/Intt/Makefile.am
> InttStreamQA is added

- offline/packages/TrackingDiagnostics/TrackResiduals.cc
- offline/packages/TrackingDiagnostics/TrackResiduals.h
> feat: add TPC cluster locations for easy drawing

- offline/packages/CaloReco/CaloTowerCalib.cc
- offline/packages/CaloReco/CaloTowerCalib.h
Calibrated the tower time to the difference from the mean time per tower for individual run.
> time calibration

- simulation/g4simulation/g4calo/HcalRawTowerBuilder.cc
- simulation/g4simulation/g4calo/HcalRawTowerBuilder.h
- simulation/g4simulation/g4calo/Makefile.am
- simulation/g4simulation/g4calo/RawTowerBuilder.h
- simulation/g4simulation/g4calo/RawTowerBuilderByHitIndex.cc
- simulation/g4simulation/g4calo/RawTowerDigitizer.cc
- simulation/g4simulation/g4calo/RawTowerDigitizer.h
- simulation/g4simulation/g4centrality/Makefile.am
- simulation/g4simulation/g4centrality/PHG4CentralityReco.cc
- simulation/g4simulation/g4centrality/PHG4CentralityReco.h
More catching up with clang-tidy
> Clang tidy 21

- calibrations/calorimeter/calo_emc_noisy_tower/emcNoisyTowerFinder.cc
> hot tower finder: making optional file list input

- calibrations/calorimeter/calo_emc_pi0_tbt/pi0EtaByEta.cc
- calibrations/calorimeter/calo_emc_pi0_tbt/pi0EtaByEta.h
> pi0 calib: trig bug fix and other small updates

- offline/packages/CaloReco/CaloTowerStatus.cc
- offline/packages/CaloReco/CaloTowerStatus.h
> CaloTowerStatus: adding abort option for no hot map

- offline/framework/fun4allraw/intt_pool.cc
The intt pool code had a leftover printout, commented it out
> comment out printout

- offline/framework/fun4allraw/Fun4AllStreamingInputManager.cc
- offline/framework/fun4allraw/Makefile.am
- offline/framework/fun4allraw/SingleInttEventInput.cc
- offline/framework/fun4allraw/SingleInttEventInput.h
- offline/framework/fun4allraw/SingleInttPoolInput.cc
- offline/framework/fun4allraw/SingleInttPoolInput.h
This PR adds the skipping of early BCOs in the intt pool input manager. This is glacially slow (at ~1evt/sec it takes a day to skip 100k events). This PR adds an event based intt input manager which has acceptable speed. It doesn't recover all hits (where you need the pooling) but this will get us going with the streaming intt. …
> Skip low bco intt

- offline/framework/fun4allraw/SingleInttPoolInput.cc
This PR moves a printout to a verbosity flag, need to merge this now so we don't get too many printouts in the production [skip-ci]
> move printout behind verbosity flag

- offline/framework/fun4allraw/intt_pool.cc
- offline/framework/fun4allraw/intt_pool.h
Can now access the list of BCOs a FEE sees, and the list of FEEs a BCO sees
> Added new APIs

- offline/QA/Calorimeters/CaloValid.cc
- offline/QA/Calorimeters/CaloValid.h
[comment]: <Added New 3D Histograms and Removed 2 Unimportant Lines> (Please tell us something about this pull request)
> CaloValid2

- offline/packages/zdcinfo/ZdcReco.cc
- offline/packages/zdcinfo/ZdcReco.h
Changes to SMD ADC threshold in radius determination
> updates to ZDC reconstruction

- offline/framework/fun4allraw/Fun4AllStreamingInputManager.cc
- offline/framework/fun4allraw/Fun4AllStreamingInputManager.h
- offline/framework/fun4allraw/SingleInttPoolInput.cc
- offline/framework/fun4allraw/SingleInttPoolInput.h
- offline/framework/fun4allraw/SingleMvtxPoolInput.cc
- offline/framework/fun4allraw/SingleMvtxPoolInput.h
- offline/framework/fun4allraw/SingleStreamingInput.h
This replaces https://github.com/sPHENIX-Collaboration/coresoftware/pull/3050 after merging in Chris' changes and fixing some code that git merge inadvertently removed
> feat: Add INTT packet QA on FEE by FEE basis

- offline/QA/Global/GlobalQA.cc
> update zdc hist range

- offline/packages/TrackingDiagnostics/TrackResiduals.cc
- offline/packages/TrackingDiagnostics/TrackResiduals.h
- offline/packages/tpc/TpcCombinedRawDataUnpacker.cc
- offline/packages/tpc/TpcCombinedRawDataUnpacker.h
> zero suppression emulation and fixed pedestal subtraction in TPc Unpacker and Event tree in TrackResiduals

- calibrations/intt/inttcalib/InttCalib.cc
- calibrations/intt/inttcalib/InttCalib.h
[comment]: <New feature added. BCO Calibration CDB can be created between processes depending on number of events required> ( What does this PR do? Linking to talk in software meeting encouraged )
> Add new feature to create BCO Calib between processes

- offline/framework/fun4allraw/Fun4AllStreamingInputManager.cc
Thanks to Jaebeom for pointing out, doesn't affect anything because we only grab the nentries from the histo but it is better to be clear
> fix: stupid typo

- calibrations/tpc/TPCPedestalCalibration/Makefile.am
- calibrations/tpc/TpcDVCalib/Makefile.am
- calibrations/tpc/TpcDVCalib/README.md
- calibrations/tpc/TpcDVCalib/TrackToCalo.cc
- calibrations/tpc/TpcDVCalib/TrackToCalo.h
- calibrations/tpc/TpcDVCalib/autogen.sh
- calibrations/tpc/TpcDVCalib/configure.ac
- calibrations/tpc/TpcDVCalib/macro/Fun4All_FieldOnAllTrackersCalos.C
- calibrations/tpc/TpcDVCalib/macro/condorJob/condor-data.job
- calibrations/tpc/TpcDVCalib/macro/fit.C
- calibrations/tpc/TpcDVCalib/macro/offline_dv_calib.sh
- calibrations/tpc/TpcDVCalib/macro/run_data.sh
- calibrations/tpc/TpcDVCalib/macro/saveroot.C
- calibrations/tpc/fillDigitalCurrentMaps/Makefile.am
- calibrations/tpc/fillSpaceChargeMaps/Makefile.am
- calibrations/tpc/generator/Makefile.am
New TPC drift velocity monitoring module which will be used in run-by-run calibration
> yuxd: add new TPC drift velocity monitoring module

- offline/framework/fun4allraw/intt_pool.cc
- offline/framework/fun4allraw/intt_pool.h
improvements in INTT hit decoding 
https://indico.bnl.gov/event/24546/contributions/95493/attachments/56585/96943/intt_update_2024_08_15.pptx
> mlp - new version of the intt_pool

- calibrations/tpc/TpcDVCalib/TrackToCalo.cc
- calibrations/tpc/TpcDVCalib/macro/Fun4All_FieldOnAllTrackersCalos.C
Delete some output lines for debugging
> suppress output

- offline/packages/mbd/MbdCalib.cc
- offline/packages/mbd/MbdCalib.h
- offline/packages/mbd/MbdEvent.cc
[comment]: added calibrations for the global t0, so that we set the main timing peak to have a mean of 0.
> added overall t0 correction

- offline/packages/intt/InttCombinedRawDataDecoder.cc
- offline/packages/intt/InttCombinedRawDataDecoder.h
- offline/packages/trackbase/InttEventInfov1.cc
This PR modifies InttCombinedRawDataDecoder to implement the bunch crossing in tracking. It:
1) Adds a flag to process INTT data recorded in triggered mode or streaming mode. 
2) In triggered mode, calculates the crossing number relative to the triggered BCO as a number from 0-120.
3) In streamed mode, calculates the crossing number relative to the triggered BCO as a number from -120 to infinity.
The default setting is to process data in streamed mode, with a FEE offset …
> Prelim alignment

- offline/packages/tpc/LaserClusterizer.cc
- offline/packages/tpc/LaserClusterizer.h
- offline/packages/tpccalib/Makefile.am
- offline/packages/tpccalib/TpcCentralMembraneMatching.cc
- offline/packages/tpccalib/TpcCentralMembraneMatching.h
Fixed numbering scheme and orientation of CM stripe pattern so that it now matches what is seen in data.
Made new matching method that just finds nearest neighbor (requires static correction to be applied to work properly) along with bool to toggle between two methods.
Modified laser clustering parameters to search in a slightly narrower window (may need more tuning) …
> CM Laser Distortions

- offline/framework/ffarawmodules/BcoRangeCheck.cc
- offline/framework/ffarawmodules/BcoRangeCheck.h
- offline/framework/ffarawmodules/InttGl1Check.cc
- offline/framework/ffarawmodules/InttGl1Check.h
- offline/framework/ffarawmodules/Makefile.am
- offline/framework/ffarawobjects/Makefile.am
- offline/framework/fun4allraw/Fun4AllStreamingInputManager.cc
- offline/framework/fun4allraw/Fun4AllStreamingInputManager.h
- offline/framework/fun4allraw/SingleGl1PoolInput.cc
The PR adds a flag to the Fun4AllStreamingInputManager which uses the first event from the gl1 to set the initial reference bco to efficiently remove the initial data from the streaming systems which are taken before our daq started all components
> Streaming gl1ref

- offline/packages/tpc/LaserClusterizer.cc
Added a	verbosity requirement for cout statement in laser clustering
> Laser Clustering verbosity

- offline/packages/TrackingDiagnostics/TrackResiduals.cc
If you run without hits, some new code segfaults. This adds the flag around the offending code
> fix: seg fault when running without hits

- offline/QA/Tracking/TpcSeedsQA.cc
- offline/QA/Tracking/TpcSeedsQA.h
> add dedx gains and OPF to TPC seed QA

- calibrations/intt/inttcalib/InttCalib.cc
- calibrations/intt/inttcalib/InttCalib.h
> InttCalib module update

- offline/framework/ffarawmodules/Makefile.am
- offline/framework/ffarawmodules/TpcBcoDump.cc
- offline/framework/ffarawmodules/TpcBcoDump.h
- offline/framework/fun4allraw/SingleStreamingInput.h
- offline/packages/TrackingDiagnostics/TrkrNtuplizer.cc
- offline/packages/tpc/LaserClusterizer.cc
- offline/packages/tpc/TpcClusterizer.cc
- offline/packages/tpc/TpcSimpleClusterizer.cc
This adds the fast tpc bco ntupling code - nothing sophisticated yet, but it needs only 2:30m to run over a 20GB data file
> Tpc bco qa

- offline/framework/ffarawmodules/Gl1BcoDump.cc
- offline/framework/ffarawmodules/Gl1BcoDump.h
- offline/framework/ffarawmodules/Makefile.am
This PR adds a fast dump of the gl1 bco into an ntuple
> Add ffarawmodules/Gl1BcoDump

- offline/framework/ffarawmodules/Gl1BcoDump.cc
- offline/framework/ffarawmodules/Gl1BcoDump.h
- offline/framework/ffarawmodules/TpcBcoDump.cc
- offline/framework/ffarawmodules/TpcBcoDump.h
TpcBcoDump.cc now uses TTree instead of TNtuple
> TpcBcoDump.cc now uses TTree instead of TNtuple

- offline/framework/fun4allraw/Makefile.am
Added intt_pool.h to fun4allraw/Makefile.am, whitespace fixes in same file
> (INTT) Added intt_pool.h to fun4allraw/Makefile.am

- offline/packages/trackreco/Makefile.am
I went to test the TpcSeedFilter this morning and found that it was not in the the include files. I just
tested the code out, and it works as expected.
> Update trackreco/Makefile.am to include TpcSeedFilter

- offline/packages/zdcinfo/Makefile.am
The ZdcInfov2 file was omitted in the pcm file list. No need to run jenkins [skip-ci]
> fix forgotten pcm file

- offline/framework/fun4allraw/Fun4AllStreamingInputManager.cc
- offline/framework/fun4allraw/SingleTpcPoolInput.cc
Adds endat tagger check in the tpc bco qa
> fix: add endat tagger

- offline/QA/Tracking/TpcSeedsQA.cc
- offline/packages/KFParticle_sPHENIX/KFParticle_Container.cc
- offline/packages/KFParticle_sPHENIX/KFParticle_eventReconstruction.cc
- offline/packages/KFParticle_sPHENIX/KFParticle_nTuple.cc
- offline/packages/KFParticle_sPHENIX/KFParticle_nTuple.h
This PR just fixes the newly created clang-tidy and cppcheck warnings which managed to sneak in in the last couple of days
> Clang tidy 23

- offline/QA/Tracking/TpcSeedsQA.cc
- offline/QA/Tracking/TpcSeedsQA.h
> add sector event summary ntuple

- offline/packages/tpc/LaserClusterizer.cc
Changed abort event to event ok if laser peak not found and replaced adc pedestal subtraction with just a threshold check
> Laser cluster return code fix

- offline/QA/Tracking/TpcSeedsQA.cc
> URGENT bugfix

- offline/packages/ClusterIso/ClusterIso.cc
- offline/packages/ClusterIso/ClusterIso.h
check the tower status before including in iso ET claculation
> check tower status for iso ET

- offline/QA/Global/GlobalQA.cc
- offline/QA/Global/GlobalQA.h
- offline/QA/Global/Makefile.am
PR adds sEPD QA, streamlines ZDC QA (replaces with ZDC vertex in zdcinfo class)
> Add sEPD QA to Global

- offline/packages/CaloReco/RawClusterBuilderTemplate.cc
- offline/packages/CaloReco/RawClusterBuilderTemplate.h
- offline/packages/CaloReco/RawClusterBuilderTopo.cc
- offline/packages/CaloReco/RawClusterBuilderTopo.h
Have a setter to set the min cluster energy threshold to be saved in the raw cluster container. 
> add min energy threshold to save clusters

- offline/packages/CaloReco/RawClusterCNNClassifier.cc
- offline/packages/CaloReco/RawClusterCNNClassifier.h
This PR makes the RawClusterCNNClassifier more user friendly. 
Right now it has option creates a new cluster container node with clusters(above certain energy threshold) which their prob is set to the new CNN prob. Some setters to the input cluster name, model file path etc. are added as well.
> cluster classifier updates

- offline/QA/Global/GlobalQA.cc
- offline/QA/Global/GlobalQA.h
PR includes additional  sEPD tile-by-tile QA to global
> add sEPD tower QA

- offline/packages/tpc/LaserEventIdentifier.cc
There was incorrect logic of the laser event identifier that is now fixed. Additionally, the logic was modified to search for the presence of laser signatures rather than the absence of them.
> Fixed logic of laser event identifier

- offline/QA/Tracking/TpcSeedsQA.cc
- offline/packages/TrackingDiagnostics/TrackResiduals.cc
> fixed GL1 extraction

- offline/framework/fun4allraw/Fun4AllStreamingInputManager.cc
- offline/framework/fun4allraw/MicromegasBcoMatchingInformation.cc
- offline/framework/fun4allraw/MicromegasBcoMatchingInformation.h
- offline/framework/fun4allraw/SingleMicromegasPoolInput.cc
Take two. Improve micromegas pooling and cleanup.
> Fix micromegas pooling

- offline/framework/frog/CreateFileList.pl
The pileup will from now on be given in kHz to accommodate multiple different pileup scenarios. The old pileup where a parameter set a hardcoded scenario is still here but will be phased out. This is not checked by jenkins, no need to run it [skip-ci]
> new pileup handling

- offline/packages/epd/EpdReco.cc
- offline/packages/epd/EpdReco.h
- offline/packages/eventplaneinfo/EventPlaneReco.cc
- offline/packages/eventplaneinfo/EventPlaneReco.h
- offline/packages/eventplaneinfo/Eventplaneinfo.h
- offline/packages/eventplaneinfo/Eventplaneinfov1.cc
- offline/packages/eventplaneinfo/Eventplaneinfov1.h
PR updates sEPD for new calibration file
Updates the event plane code for sEPD phi mapping
Makes event plane code light weight (only produces raw Q vectors for production), corrections and histograms filling are decoupled.
> sEPD reco updates and event plane updates for sEPD

- calibrations/intt/inttcalib/InttCalib.cc
- calibrations/intt/inttcalib/InttCalib.h
> Inttcalib clang tidy fix

- calibrations/intt/inttcalib/InttCalib.cc
- calibrations/intt/inttcalib/InttCalib.h
Streaming BCO offset calculation is added.
> (calibrations/intt) Streaming BCO Offset calib added

- offline/packages/intt/InttOdbcQuery.cc
- offline/packages/intt/InttOdbcQuery.h
Additional functionality to query class; it now also obtains run type and file locations per query
> (offlline/packages/intt) Additional functionality to query class

- offline/packages/micromegas/MicromegasCombinedDataDecoder.cc
- offline/packages/micromegas/MicromegasRawDataDecoder.cc
> permanently masks part of the SCOZ detector that is disconnected.

- offline/framework/frog/FROG.cc
- offline/framework/frog/FROG.h
This PR switches the filecatalog db from the master to the replica. Added random sleeps (Thanks Joseph) between retries.
> use catalog replica, random sleep between retries

- offline/framework/fun4allraw/MicromegasBcoMatchingInformation.cc
- offline/framework/fun4allraw/MicromegasBcoMatchingInformation.h
- offline/framework/fun4allraw/SingleMicromegasPoolInput.cc
- offline/framework/fun4allraw/SingleMicromegasPoolInput.h
> Micromegas event assembly

- offline/packages/CaloReco/CaloTowerBuilder.cc
- offline/packages/CaloReco/CaloTowerBuilder.h
This PR introduce option to apply tower by tower software level zero suppression for **waveform simulation**, which takes us able to emulate the exact hardware ZS and apply to simulation.
> CaloTowerBuilder update: tower by tower level software zero-suppression 

- offline/packages/CaloBase/RawCluster.h
- offline/packages/CaloBase/RawClusterv1.cc
- offline/packages/CaloBase/RawClusterv1.h
> adding get_lead_tower to raw cluster

- offline/packages/Skimmers/Jets/JetDSTSkimmer.h
- offline/packages/Skimmers/Jets/configure.ac
> Skimmer update: update config file, add node name setter

- offline/packages/trigger/TriggerAnalyzer.cc
- offline/packages/trigger/TriggerAnalyzer.h
- offline/packages/trigger/TriggerRunInfo.h
- offline/packages/trigger/TriggerRunInfoReco.cc
- offline/packages/trigger/TriggerRunInfoReco.h
- offline/packages/trigger/TriggerRunInfov1.cc
- offline/packages/trigger/TriggerRunInfov1.h
This PR adds the scalers to the TriggerRunInfo node. Also adds the ability of the TriggerAnalyzer as a helper class to interpret the gl1 data.
> added scalers to triggerruninfo node

- offline/packages/TrackingDiagnostics/TrackSeedTrackMapConverter.cc
Fixes the determination of the track parameters for cosmic tracks
> fix: cosmic track params

- offline/packages/tpc/LaserEventIdentifier.cc
- offline/packages/tpc/LaserEventIdentifier.h
- offline/packages/tpc/LaserEventRejecter.cc
- offline/packages/tpc/LaserEventRejecter.h
- offline/packages/tpc/Makefile.am
- offline/packages/tpc/TpcClusterizer.cc
- offline/packages/tpc/TpcClusterizer.h
Moved laser event rejection into new module, with an additional rejection in the tpc clusterizer since that takes a long time
https://github.com/sPHENIX-Collaboration/macros/pull/983
> Laser Event Rejection

- calibrations/calorimeter/calo_tower_slope/HCalCosmics.cc
> Change the binwidth for template fitting. Remove cout.

- offline/framework/ffamodules/Makefile.am
- offline/framework/ffamodules/Timing.cc
- offline/framework/ffamodules/Timing.h
- offline/packages/NodeDump/DumpZdcinfo.cc
- offline/packages/NodeDump/DumpZdcinfo.h
- offline/packages/NodeDump/Makefile.am
- offline/packages/NodeDump/PHNodeDump.cc
- offline/packages/zdcinfo/Zdcinfov1.cc
- offline/packages/zdcinfo/Zdcinfov1.h
- offline/packages/zdcinfo/Zdcinfov2.cc
- offline/packages/zdcinfo/Zdcinfov2.h
This PR adds a very simple module which prints out the time it takes to process a given number of events, useful to see if this time increases as function of the number of processed events (something our mean values won't catch).
Unrelated - adds the zdcinfo to the ascii dump and implements the isValid() method for the Zdcinfo classes. The zdcinfo classes don't have a bounds check - that needs to be implemented (use std::arrays in v3) …
> Simple timing check

- offline/packages/caloTreeGen/Makefile.am
- offline/packages/caloTreeGen/autogen.sh
- offline/packages/caloTreeGen/caloTreeGen.cc
- offline/packages/caloTreeGen/caloTreeGen.h
- offline/packages/caloTreeGen/configure.ac
This PR moves caloTreeGen from QA to packages. It's the more logical place and there was a typo in the package list, so this was never build. Let's see if jenkins likes it
> move caloTreeGen to offline/packages

- offline/QA/SimulationModules/QAG4SimulationCalorimeter.cc
- offline/QA/SimulationModules/QAG4SimulationCalorimeter.h
- simulation/g4simulation/g4eval/CaloEvaluator.cc
- simulation/g4simulation/g4eval/CaloEvaluator.h
Following up [PR 3178](https://github.com/sPHENIX-Collaboration/coresoftware/pull/3178)
This PR introduce the option of doing truth matching with the new TowerInfoSim objects.
Need to test it and update macro.
> Towerinfosim propagation to eval and QA module

- calibrations/calorimeter/calo_emc_pi0_tbt/pi0EtaByEta.cc
- calibrations/calorimeter/calo_emc_pi0_tbt/pi0EtaByEta.h
> piEtabyEta clean up: vtx cut, triggers, clean up, ifdef

- offline/packages/micromegas/CylinderGeomMicromegas.cc
- offline/packages/micromegas/MicromegasCalibrationData.cc
- offline/packages/micromegas/MicromegasClusterizer.cc
- offline/packages/micromegas/MicromegasHotChannelMapData.cc
Just taking care of newly cropped up clang-tidy warnings
> accumulated clang-tidy warning fixes

- offline/packages/mbd/MbdSig.cc
[comment]: Improved method for waveform fits that had occasionally failed on channels with saturated ADCs.
> Improved fitting of saturated ADCs

- offline/packages/CaloReco/RawClusterBuilderTemplate.cc
> Change the good tower selection for rawtowerbuilder to isGood

- calibrations/intt/inttcalib/InttCalib.cc
- calibrations/intt/inttcalib/InttCalib.h
New module calculates stddev of BCO offsets without masked ladder. Histogram range of hitrate distribution for bad channel determination is shared through all FELIX server.
> Few updates on calibration module

- offline/packages/TrackingDiagnostics/TrackResiduals.cc
- offline/packages/TrackingDiagnostics/TrackResiduals.h
- offline/packages/TrackingDiagnostics/TrkrNtuplizer.cc
- offline/packages/TrackingDiagnostics/TrkrNtuplizer.h
Fixes bug of cluster side and sector insertion and missing cluster variable reset in case cluster tree is not enabled in TrackResiduals module
Adds run and segment info TrkrNtuplizer
> analyzer tool bugfix and update

- offline/framework/fun4allraw/SingleMicromegasPoolInput_v2.cc
Another hotfix to micromegas decoding. 
It got broken while introducing casts, in the previous pull request, to make clang-tidy happy. (interesting ...)
> Micromegas hot fix

- offline/packages/tpc/TpcCombinedRawDataUnpacker.h
> change default zero suppression threshold from 10 to 20

- offline/framework/ffarawobjects/Makefile.am
- offline/framework/ffarawobjects/MicromegasRawHitContainerv2.h
- offline/framework/ffarawobjects/MicromegasRawHitContainerv3.cc
- offline/framework/ffarawobjects/MicromegasRawHitContainerv3.h
- offline/framework/ffarawobjects/MicromegasRawHitContainerv3LinkDef.h
- offline/framework/ffarawobjects/MicromegasRawHitv3.cc
- offline/framework/ffarawobjects/MicromegasRawHitv3.h
- offline/framework/ffarawobjects/MicromegasRawHitv3LinkDef.h
- offline/framework/fun4allraw/MicromegasBcoMatchingInformation_v2.h
- offline/framework/fun4allraw/SingleMicromegasPoolInput_v1.cc
- offline/framework/fun4allraw/SingleMicromegasPoolInput_v2.cc
New MicromegasRawHitv3, inspired by TpcRawHitv3. 
> Micromegas rawhit v3

- offline/packages/uspin/SpinDBInput.cc
- offline/packages/uspin/SpinDBInput.h
- offline/packages/uspin/SpinDBOutput.cc
- offline/packages/uspin/SpinDBOutput.h
This PR adds the capability for users to pull from the spinDB using a default qa level. It also allows experts to update the default qa value.
> Added default qa level to spinDB

- calibrations/framework/oncal/OnCalServer.cc
- generators/FermiMotionAfterburner/Makefile.am
- generators/HIJINGFlipAfterburner/Makefile.am
- generators/ReactionPlaneAfterburner/Makefile.am
- generators/phhepmc/Makefile.am
- offline/database/sphenixnpc/Makefile.am
- offline/framework/fun4all/Fun4AllBase.h
- offline/framework/fun4allraw/mvtx_decoder/DecodingStat.h
- offline/framework/phool/PHFlag.h
- offline/framework/phool/PHNodeIOManager.h
First batch of small changes to compile with gcc 14
> compile with gcc 14

- offline/packages/uspin/SpinDBContent.cc
- offline/packages/uspin/SpinDBContent.h
- offline/packages/uspin/SpinDBInput.cc
- offline/packages/uspin/SpinDBInput.h
- offline/packages/uspin/SpinDBOutput.cc
- offline/packages/uspin/SpinDBOutput.h
This PR introduces the functionality for users to access local polarimetry information (neutron asymmetry magnitudes and phase offsets) from the spin db.
> Add localpol information to spinDB

- offline/packages/trackbase/TrackFitUtils.cc
- offline/packages/trackbase/TrackFitUtils.h
- offline/packages/trackreco/PHSiliconTpcTrackMatching.cc
- offline/packages/trackreco/PHSiliconTpcTrackMatching.h
> Updates to add zero_field utility to the track matching

- offline/packages/centrality/CentralityReco.cc
- offline/packages/trigger/MinimumBiasClassifier.cc
This PR fixes an error in the loading of the vertex centrality scale factors
> Centralityreco

- simulation/g4simulation/g4detectors/PHG4CEmcTestBeamSteppingAction.cc
- simulation/g4simulation/g4detectors/PHG4CEmcTestBeamSubsystem.h
- simulation/g4simulation/g4detectors/PHG4ConeSteppingAction.cc
- simulation/g4simulation/g4detectors/PHG4ConeSubsystem.h
- simulation/g4simulation/g4detectors/PHG4EnvelopeSteppingAction.cc
- simulation/g4simulation/g4detectors/PHG4FullProjSpacalCellReco.cc
- simulation/g4simulation/g4detectors/PHG4GDMLDetector.cc
- simulation/g4simulation/g4detectors/PHG4HcalSteppingAction.cc
- simulation/g4simulation/g4detectors/PHG4InnerHcalDetector.cc
- simulation/g4simulation/g4detectors/PHG4InnerHcalSteppingAction.cc
- simulation/g4simulation/g4detectors/PHG4OuterHcalDetector.cc
- simulation/g4simulation/g4detectors/PHG4OuterHcalSteppingAction.cc
- simulation/g4simulation/g4detectors/PHG4ScintillatorSlatContainer.cc
- simulation/g4simulation/g4detectors/PHG4ScintillatorSlatDefs.cc
- simulation/g4simulation/g4detectors/PHG4ScintillatorSlatv1.cc
- simulation/g4simulation/g4detectors/PHG4SectorSteppingAction.cc
- simulation/g4simulation/g4detectors/PHG4SpacalDetector.cc
- simulation/g4simulation/g4detectors/PHG4SpacalSteppingAction.cc
This PR adds the CGAL API change to the geometric hcals. They now compile under gcc 12 and gcc 14
> compile with old and new CGAL versions

- simulation/g4simulation/g4eval/CaloRawClusterEval.cc
> CaloRawClusterEval correct node name

- offline/packages/trackbase/TrackFitUtils.cc
- offline/packages/trackreco/PHSiliconTpcTrackMatching.cc
> Update ZeroField tracks "pt" to 500 MeV

- offline/framework/fun4all/Fun4AllDstOutputManager.cc
- offline/framework/fun4all/Fun4AllOutputManager.h
- offline/framework/fun4all/Fun4AllServer.h
- offline/framework/phool/PHIODataNode.h
- offline/framework/phool/PHNodeIOManager.cc
- offline/framework/phool/PHNodeIOManager.h
This PR allows to set the split level and buffer size of TBranches from the macro
> Adjust splitlevel

- offline/packages/TrackingDiagnostics/TrkrNtuplizer.cc
> memory leak fix

- offline/framework/phool/PHNodeIOManager.cc
I had forgotten to remove the printout for the split levels and buffer sizes, merging this right away to update todays ana build [skip-ci]
> remove forgotten printout

- calibrations/calorimeter/calo_tower_slope/LiteCaloEval.cc
> TSC fitting bug fix

- offline/packages/tpc/TpcCombinedRawDataUnpacker.cc
- offline/packages/tpc/TpcCombinedRawDataUnpacker.h
Adds a hook for t0 calibration into the tpc unpacker
> feat: add t0 hook

- offline/packages/tpc/TpcClusterizer.cc
- offline/packages/tpc/TpcRawWriter.cc
- offline/packages/trackbase/RawHitSet.cc
- offline/packages/trackbase/RawHitSet.h
- offline/packages/trackbase/RawHitSetv1.h
This removes the public member variable from the RawHitSet object and adds appropriate accessors to the base/derived classes
> fix: RawHitSet public member variable

- offline/framework/fun4allraw/Makefile.am
- offline/framework/fun4allraw/SingleMvtxPoolInput.cc
- offline/framework/fun4allraw/mvtx_decoder/DecodingStat.cc
- offline/framework/fun4allraw/mvtx_decoder/GBTLink.cc
- offline/framework/fun4allraw/mvtx_decoder/GBTLink.h
- offline/framework/fun4allraw/mvtx_decoder/GBTWord.cc
- offline/framework/fun4allraw/mvtx_decoder/InteractionRecord.cc
- offline/framework/fun4allraw/mvtx_decoder/PayLoadCont.h
- offline/framework/fun4allraw/mvtx_decoder/PayLoadSG.h
- offline/framework/fun4allraw/mvtx_decoder/PixelData.cc
- offline/framework/fun4allraw/mvtx_decoder/PixelData.h
- offline/framework/fun4allraw/mvtx_decoder/RDH.cc
- offline/framework/fun4allraw/mvtx_decoder/RDH.h
- offline/framework/fun4allraw/mvtx_decoder/StrobeData.cc
- offline/framework/fun4allraw/mvtx_decoder/StrobeData.h
- offline/framework/fun4allraw/mvtx_decoder/mvtx_utils.h
- offline/framework/fun4allraw/mvtx_pool.cc
- offline/framework/fun4allraw/mvtx_pool.h
This PR add changes in the MVTX decoding to handling with decoding error from corrupt data. It also introduce a new way to directly access RDH data.
> Add new RDH decoding and handling decoding errors

- generators/PHPythia8/PHPythia8.cc
- generators/hijing/Makefile.am
- generators/hijing/dummy/forcecxx.cc
- generators/sHijing/Makefile.am
- generators/sphstarlight/StarLight_To_HepMc.cc
- offline/framework/fun4allraw/Fun4AllStreamingInputManager.cc
- offline/framework/fun4allraw/Makefile.am
- offline/framework/fun4allraw/TpcTimeFrameBuilder.cc
- offline/framework/fun4allraw/intt_pool.cc
- offline/framework/phool/PHNodeIterator.cc
- offline/packages/intt/INTTXYvtx.cc
- offline/packages/intt/InttClusterizer.cc
- offline/packages/mvtx/MvtxClusterizer.cc
- offline/packages/uspin/SpinDBInput.cc
- offline/packages/uspin/SpinDBOutput.cc
This PR fixes compilation issues when using clang 19.1.5. It is stricter than gcc 14 but so far the changes are minor
> Clang 19.1.5 fix

- offline/packages/trackreco/PHCASeeding.cc
- offline/packages/trackreco/PHCASeeding.h
> add option to reject zsize == 1 clusters

- calibrations/calorimeter/calo_tower_slope/LiteCaloEval.cc
- calibrations/calorimeter/calo_tower_slope/LiteCaloEval.h
- calibrations/calorimeter/calo_tower_slope/Makefile.am
removed the minbias requirement, added trigger analyzer module
> added trigger analyzer

- calibrations/calorimeter/calo_tower_slope/LiteCaloEval.cc
small fix for clang compilation
> fix clang compilation

- offline/packages/KFParticle_sPHENIX/KFParticle_eventReconstruction.cc
This PR fixes a double delete I introduced when replacing the c++ illegal variable size arrays by new []. scan buils still claims there is a memory leak which needs to be investigated. 
> fix double delete

- offline/packages/trigger/TriggerAnalyzer.cc
[comment]: <The TriggerAnalyzer needed the triggerruninfo object if the emulator was being used> (Please tell us something about this pull request)
[comment]: <Bug fix> ( What does this PR do? Linking to talk in software meeting encouraged )
> fix: triggerruninfo branch included with emulator

- offline/packages/TrackingDiagnostics/TrackResiduals.cc
- offline/packages/TrackingDiagnostics/TrackResiduals.h
- offline/packages/trackreco/DSTClusterPruning.cc
- offline/packages/trackreco/DSTClusterPruning.h
- offline/packages/trackreco/Makefile.am
- offline/packages/trackreco/PHActsTrkFitter.cc
- offline/packages/trackreco/PHActsTrkFitter.h
- offline/packages/trackreco/PHSimpleVertexFinder.cc
- offline/packages/trackreco/PHSimpleVertexFinder.h
- offline/packages/trackreco/PHTpcDeltaZCorrection.cc
- offline/packages/trackreco/PHTpcDeltaZCorrection.h
Add module DSTClusterPruning to create a Cluster map of only clusters on tracks
> Added module to make pruned cluster container

- offline/framework/frog/CreateFileList.pl
Add Herwig as type 30 (MB), 31 (10 GeV Jets), 32 (30 GeV Jets), jenkins does not test this [skip-ci]
> add Herwig to CreateFileList.pl

- offline/packages/tpc/LaserEventIdentifier.cc
Fixes a memory leak in the laser identifier
> fix: memory leak

- offline/packages/TrackingDiagnostics/TrackResiduals.cc
The ideal surface is included to calculate the ideal track cluster positions independently from the distortion corrections.
> Include ideal surface unchanged by dist corr

- offline/QA/SimulationModules/QAG4SimulationDistortions.cc
Bug fix
Fix the inconsistency between variable type which are float and branch type which are double
> fix inconsistency between variable and branch type

- offline/framework/fun4allraw/SingleTpcTimeFrameInput.cc
Valgrind finding more memory leaks while I'm trying to debug other memory issues 
> fix: more mem leaks

- offline/packages/CaloReco/BEmcCluster.cc
- offline/packages/CaloReco/BEmcCluster.h
- offline/packages/CaloReco/RawClusterBuilderTemplate.cc
- offline/packages/CaloReco/RawClusterBuilderTemplate.h
> functionality to turn off cluster splitting

- offline/framework/frog/FROG.cc
- offline/framework/frog/FROG.h
- offline/framework/frog/Makefile.am
- offline/framework/frog/configure.ac
This PR adds searching for raw data files in the RawdataCatalog. It needs RAWDATA and HPSSRAW in the GSEARCHPATH which is not the default setting, so nobody should notice.
> Rawdata frog

- offline/QA/Calorimeters/CaloFittingQA.cc
- offline/QA/Calorimeters/CaloFittingQA.h
This PR fixes a leak in the calo qa, also replaces the duplicate m_debug flag by Verbosity() which will likely crash the Fun4All_Year2.C macro
> fix memory leak

- offline/packages/jetbackground/RetowerCEMC.cc
- offline/packages/jetbackground/RetowerCEMC.h
> Add tower time into Retower

- simulation/g4simulation/g4waveformsim/CaloWaveformSim.cc
(otherwise it overflows for large pT photons :()
> Max out the simulated sample ADC at 2^14

- offline/packages/epd/EpdReco.cc
- offline/packages/epd/EpdReco.h
> fix leak, clang-format for epdreco

- offline/framework/fun4all/Fun4AllDstOutputManager.h
- offline/framework/fun4all/Fun4AllHistoManager.cc
- offline/framework/fun4all/Fun4AllHistoManager.h
- offline/framework/fun4all/Fun4AllOutputManager.h
- offline/framework/fun4all/Fun4AllServer.cc
Hugo said this one worked for him without an issue, let's see what Jenkins says...
> feat: segmentized qa files attempt 2

- offline/packages/CaloReco/BEmcCluster.cc
- offline/packages/CaloReco/BEmcCluster.h
> EmcModule initialization updated to avoid seg fault

- offline/packages/eventplaneinfo/EventPlaneReco.cc
- offline/packages/eventplaneinfo/EventPlaneReco.h
cuts were based on simulation, update now for data.
> update cuts based on data

- offline/packages/trackbase/AlignmentTransformation.cc
Now allows commented out lines, as well as empty lines More checks on ill-formed lines
Do not require a total fixed number of lines.
parameters for hitsetkeys not found in the file are left to zero (=default alignment)
> improve robustness of alignment parameter file parsing.

- offline/packages/Skimmers/Trigger/Makefile.am
- offline/packages/Skimmers/Trigger/TriggerDSTSkimmer.cc
- offline/packages/Skimmers/Trigger/TriggerDSTSkimmer.h
- offline/packages/Skimmers/Trigger/autogen.sh
- offline/packages/Skimmers/Trigger/configure.ac
> A skimmer to select trigger

- offline/packages/jetbackground/Makefile.am
- offline/packages/jetbackground/TowerRho.h
- offline/packages/jetbackground/TowerRhoLinkDef.h
- offline/packages/jetbackground/TowerRhov1.cc
- offline/packages/jetbackground/TowerRhov1.h
- offline/packages/jetbackground/TowerRhov1LinkDef.h
Those classes were stored on DST's - we cannot just remove them or replace them by something else. Putting them back to make our DSTs readable again
> put TowerRho classes back

- offline/packages/jetbackground/DetermineTowerRho.cc
- offline/packages/jetbackground/DetermineTowerRho.h
- offline/packages/jetbackground/Makefile.am
- offline/packages/jetbackground/TowerRho.h
- offline/packages/jetbackground/TowerRhov1.cc
- offline/packages/jetbackground/TowerRhov1.h
> making EventRho and TowerRho two seperate classes with no alias

- offline/packages/CaloReco/BEmcCluster.cc
- offline/packages/CaloReco/ClusterCDFCalculator.cc
- offline/packages/CaloReco/ClusterCDFCalculator.h
- offline/packages/CaloReco/Makefile.am
- offline/packages/CaloReco/RawClusterLikelihoodProfile.cc
- offline/packages/CaloReco/RawClusterLikelihoodProfile.h
First commit for users to test the new profile likelihood CDF calculator module. 
> First iteration for profile likelihood CDF calculator module

- offline/packages/trackreco/PHMicromegasTpcTrackMatching.cc
title says it all. Thanks  @pedroanietom and sorry for the trouble
> fix crash when extrapolating from silicon only.

- offline/packages/tpc/LaserClusterizer.cc
- offline/packages/tpc/LaserClusterizer.h
Multi-threading of laser clustering
Multi-threading of laser clustering. Toggles implemented to swap between running all threads in parallel vs in series. Additional toggle to swap between laser clustering and lamination clustering
https://github.com/sPHENIX-Collaboration/macros/pull/1048
> Laser clustering multi thread

- offline/framework/fun4all/Fun4AllHistoManager.cc
Production testing revealed another bug
> fix: closing script application

- offline/packages/tpc/TpcClusterizer.cc
- offline/packages/tpc/TpcClusterizer.h
> make number of threads configurable in TpcClusterizer

- offline/packages/tpccalib/TpcLaminationFitting.cc
- offline/packages/tpccalib/TpcLaminationFitting.h
Removed runnumber and segment from QA tree since not useful
> Tpc Lamination Fitting QA fix

- offline/packages/tpc/TpcClusterizer.cc
> remove print statement

- offline/QA/Intt/InttRawHitQA.cc
> 2D HitMap Chip labeling bug fixed

- offline/packages/tpc/TpcClusterizer.cc
An unused variable crashes the clang 19 build, this PR comments it out
> fix clang-19 compilation

- offline/packages/TrackingDiagnostics/KshortReconstruction.cc
- offline/packages/TrackingDiagnostics/KshortReconstruction.h
Added a flag to write the selected tracks from KshortReconstruction to a new map, @adfrawley 
> Added toggle to let KshortReconstruction save its tracks

- offline/packages/TrackingDiagnostics/KshortReconstruction.cc
- offline/packages/TrackingDiagnostics/KshortReconstruction.h
This PR adds more branches for the KshortReconstruction module -- track ID, event number, run number
> add more branches for KshortReconstruction

- .clang-tidy
This PR is an update for the clang-tidy configuration, let's see what jenkins says
> add some more useful checks

- offline/packages/TrackingDiagnostics/KshortReconstruction.cc
- offline/packages/TrackingDiagnostics/KshortReconstruction.h
Add track pt cut function, add nmvtx and nintt branches in Ntuple
> KshortReconstruction update: track pt cut, nmvtx, nintt branches

- offline/packages/trackreco/PHActsTrkFitter.h
clang stumbles over an unused variable. Commented it out. No need to run jenkins [skip-ci]
> comment out unused var

- calibrations/tpc/generator/generate_distortion_map.C
> Fixed string conversions in generate_distortion_maps.C

- offline/packages/trackbase/ActsGeometry.cc
There are some clusters that aren't attached to a surface in the TPC because the proper surface isn't found. I imagine this is because of the alignment constants shifting things around. This PR adds a "catch" that if a surface is not found, to check the adjacent two surfaces to see if the cluster should fit on there.
> fix: buffer for tpc cluster surface assignment

- offline/packages/CaloEmbedding/CopyIODataNodes.cc
- offline/packages/globalvertex/GlobalVertexMapv1.cc
Fixes to global vertex cloning and copying for embedding.
New global vertex map made rather than cloning. Map filled by looping over all vertexes in original map and clone_insert_vtx used to manage pointer issue previously resolved elsewhere.
> Global Vertex Copying

- offline/packages/mbd/MbdCalib.h
[comment]: Fixed issue compiling offline code in online environment
[comment]: Didn't find <mbd/MbdGeom.h>, but this should have been looking for "MbdGeom.h"
> changed include of MbdGeom.h to pick up local version

- offline/framework/phool/sphenix_constants.h
- simulation/g4simulation/g4main/PHG4Reco.cc
- simulation/g4simulation/g4main/PHG4StackingAction.h
- simulation/g4simulation/g4main/PHG4SteppingAction.cc
- simulation/g4simulation/g4main/PHG4SteppingAction.h
- simulation/g4simulation/g4tpc/PHG4TpcDetector.cc
- simulation/g4simulation/g4tpc/PHG4TpcDetector.h
- simulation/g4simulation/g4tpc/PHG4TpcElectronDrift.h
- simulation/g4simulation/g4tpc/PHG4TpcEndCapDetector.cc
- simulation/g4simulation/g4tpc/PHG4TpcEndCapDetector.h
Use common CF4 density (small change in value from 3.78 to 3.86 g/cm^3 compared to before)
> Common cf4 density

- offline/packages/CaloReco/CaloTowerCalib.cc
> Switch to new OHCal calibration payload name and adding default calib

- calibrations/calorimeter/calo_tower_slope/LiteCaloEval.cc
- calibrations/calorimeter/calo_tower_slope/LiteCaloEval.h
Added second fit_info function with different parameters for increased user functionality
> add second fit_info function

- calibrations/tpc/generator/AnnularFieldSim.cc
- calibrations/tpc/generator/AnnularFieldSim.h
- calibrations/tpc/generator/bash_for_condor_submission.sh
- calibrations/tpc/generator/bash_for_z_tests.sh
- calibrations/tpc/generator/generate_distortion_map.C
This allows a user to adjust the z position of the TPC with respect to the center of the magnetic field, and provides a demo macro showing how this can be used.
> Shift B field for distortion simulation.

- offline/packages/KFParticle_sPHENIX/KFParticle_nTuple.cc
- offline/packages/KFParticle_sPHENIX/KFParticle_nTuple.h
- offline/packages/KFParticle_sPHENIX/KFParticle_sPHENIX.cc
- offline/packages/KFParticle_sPHENIX/KFParticle_sPHENIX.h
- offline/packages/KFParticle_sPHENIX/KFParticle_triggerInfo.cc
- offline/packages/KFParticle_sPHENIX/KFParticle_triggerInfo.h
- offline/packages/KFParticle_sPHENIX/KFParticle_truthAndDetTools.cc
- offline/packages/KFParticle_sPHENIX/Makefile.am
I used Dan's trigger module to add the trigger decisions to the KFParticle output nTuple
> KFP: Added new trigger module

- offline/QA/Global/GlobalQA.cc
- offline/QA/Global/GlobalQA.h
- offline/QA/Global/Makefile.am
- offline/framework/ffaobjects/CdbUrlSave.cc
- offline/framework/ffaobjects/CdbUrlSave.h
- offline/framework/ffaobjects/CdbUrlSavev1.cc
- offline/framework/ffaobjects/CdbUrlSavev1.h
- offline/framework/ffaobjects/EventHeader.h
- offline/framework/ffaobjects/EventHeaderv1.cc
- offline/framework/ffaobjects/EventHeaderv1.h
- offline/framework/ffaobjects/EventHeaderv2.cc
- offline/framework/ffaobjects/EventHeaderv2.h
- offline/framework/ffaobjects/FlagSave.h
- offline/framework/ffaobjects/FlagSavev1.h
- offline/framework/ffaobjects/Makefile.am
- offline/framework/ffaobjects/RunHeader.cc
- offline/framework/ffaobjects/RunHeader.h
- offline/framework/ffaobjects/RunHeaderv1.h
- offline/framework/ffaobjects/SyncObject.h
- offline/framework/ffaobjects/SyncObjectv1.h
- offline/framework/phool/PHIOManager.h
- offline/framework/phool/PHNode.h
- offline/framework/phool/PHNodeIOManager.cc
- offline/framework/phool/PHNodeIntegrate.cc
- offline/framework/phool/PHNodeIterator.cc
- offline/framework/phool/PHNodeReset.cc
- offline/framework/phool/PHTimer.h
- offline/framework/phool/sphenix_constants.h
> Fix clang tidy 10

- offline/packages/CaloReco/CaloWaveformProcessing.cc
> Bug fix for no saturation handling

- offline/QA/Jet/DijetQA.cc
- offline/QA/Jet/DijetQA.h
- offline/QA/Jet/Makefile.am
This PR fixes a few bugs that slipped past the initial review of the Dijet QA module.
Changes made:
- Dijet QA now included in `Makefile.am`
- Setters added for jet pt, eta, and trigger to select
- Jets are now cut on the specified eta range
- Headers, source code now alphabetized in `Makefile.am`
These changes set up a PR in preparation to integrate this module into the `Jet_QA.C`
> Miscellaneous fixes to Dijet QA

- calibrations/calorimeter/calo_emc_noisy_tower/Makefile.am
- calibrations/calorimeter/calo_emc_noisy_tower/configure.ac
- calibrations/calorimeter/calo_emc_noisy_tower/emcNoisyTowerFinder.cc
- calibrations/calorimeter/calo_emc_noisy_tower/emcNoisyTowerFinder.h
- calibrations/calorimeter/calo_emc_pi0_tbt/CaloCalibEmc_Pi0.cc
- calibrations/calorimeter/calo_emc_pi0_tbt/CaloCalibEmc_Pi0.h
- calibrations/calorimeter/calo_emc_pi0_tbt/Makefile.am
- calibrations/calorimeter/calo_emc_pi0_tbt/pi0EtaByEta.cc
- calibrations/calorimeter/calo_emc_pi0_tbt/pi0EtaByEta.h
- calibrations/calorimeter/calo_tower_slope/HCalCosmics.cc
- calibrations/calorimeter/calo_tower_slope/HCalCosmics.h
- calibrations/calorimeter/calo_tower_slope/LiteCaloEval.cc
- calibrations/calorimeter/calo_tower_slope/LiteCaloEval.h
- calibrations/calorimeter/calo_tower_slope/Makefile.am
- calibrations/framework/oncal/Makefile.am
- calibrations/framework/oncal/OnCal.cc
- calibrations/framework/oncal/OnCal.h
- calibrations/framework/oncal/OnCalServer.cc
- calibrations/framework/oncal/OnCalServer.h
Catching up with clang-tidy warnings, clean up includes and lib dependencies, remove root'isms
> Clang tidy fix 20

- offline/packages/trigger/CaloTriggerEmulator.h
An unused variable chokes the clang compiler, commented it out, do without jenkins [skip-ci]
> comment out unused var for clang compiler

- offline/QA/Calorimeters/CaloValid.cc
- offline/QA/Calorimeters/CaloValid.h
Adding SetSpecies flag to switch between calo thresholds for pp and auau
> Calo q ahist added and calibrating hist axis final

- calibrations/calorimeter/calo_tower_slope/LiteCaloEval.cc
- calibrations/calorimeter/calo_tower_slope/LiteCaloEval.h
Add second draw function for tower spectra
> added second draw f'n, fixed drawing scale for spectra

- offline/framework/fun4allraw/MicromegasBcoMatchingInformation_v2.cc
- offline/framework/fun4allraw/MicromegasBcoMatchingInformation_v2.h
- offline/framework/fun4allraw/SingleMicromegasPoolInput_v2.cc
- offline/framework/fun4allraw/SingleMicromegasPoolInput_v2.h
Added heartbeat dedicated printout about event assembly QA
Added more variable to evaluation ntuple
> Tpot event assembly

- offline/packages/trackreco/ActsEvaluator.cc
- offline/packages/trackreco/ActsEvaluator.h
@gregottino this adds the sphenix layer to the evaluator tool
> fix: add sphenix layer to acts evaluator

- offline/framework/fun4allraw/Fun4AllTriggeredInputManager.cc
- offline/framework/fun4allraw/Fun4AllTriggeredInputManager.h
- offline/framework/fun4allraw/Makefile.am
- offline/framework/fun4allraw/SingleGl1TriggeredInput.cc
- offline/framework/fun4allraw/SingleGl1TriggeredInput.h
- offline/framework/fun4allraw/SingleTriggeredInput.cc
- offline/framework/fun4allraw/SingleTriggeredInput.h
- offline/framework/fun4allraw/SingleZdcTriggeredInput.cc
- offline/framework/fun4allraw/SingleZdcTriggeredInput.h
This PR is the nucleus of the new calo combiner
> New triggered eventcombiner

- offline/framework/ffarawmodules/ClockDiffCheck.cc
- offline/framework/fun4allraw/SingleTriggeredInput.cc
fixed off by one error when handling last events 
> Fix new eventcombiner

- offline/packages/TrackerMillepedeAlignment/MakeMilleFiles.cc
- offline/packages/TrackerMillepedeAlignment/MakeMilleFiles.h
> (TrackerMillepedeAlignment) NTuple output for MakeMilleFiles

- offline/packages/mbd/MbdEvent.cc
- offline/packages/mbd/MbdEvent.h
- offline/packages/mbd/MbdReco.cc
- offline/packages/mbd/MbdReco.h
[comment]: Added more debug info to track down any problems.  The reconstruction was not changed at all.
> added debug info

- offline/packages/trackbase/ResidualOutlierFinder.h
Acts already broke the builds, lets see if this fixes it
> fix: acts build

- offline/framework/ffarawmodules/ClockDiffCheck.cc
- offline/framework/ffarawmodules/ClockDiffCheck.h
- offline/framework/phool/PHPointerListIterator.h
- offline/framework/phool/PHTypedNodeIterator.h
ClockDiffCheck now works with old and new event combiner
> Fix clock diff

- offline/packages/trackreco/PHGenFitTrkFitter.cc
This PR modifies the GenFit track fitter to properly account for alignment parameters, as loaded in ACTS. 
In details, ACTS surfaces and transformations are used to calculate the two vectors (u and v) along which the MVTX, INTT and TPOT measurements are. 
> Genfit fit update

- offline/packages/ResonanceJetTagging/ResonanceJetTagging.cc
- offline/packages/ResonanceJetTagging/ResonanceJetTagging.h
Due to changes in KFParticle, the way the daughters from the tag decay are removed had to be modified
> Improving daughter removal from particle list

- offline/packages/ResonanceJetTagging/ResonanceJetTagging.cc
- offline/packages/ResonanceJetTagging/ResonanceJetTagging.h
Adding the possibility of reconstructing jets tagged by J/Psi.
> Adding JPSI as tag option

- offline/framework/fun4allraw/Fun4AllStreamingInputManager.cc
- offline/framework/fun4allraw/Fun4AllStreamingInputManager.h
This PR adds some bco qa histograms for the silicon into the event combiner
> feat: add silicon bco qa histograms

- offline/packages/intt/InttOdbcQuery.cc
- offline/packages/intt/InttOdbcQuery.h
The query to look up files was outdated and basically failed all the time. This PR just removed this query - it really should not be necessary,
> emergency fix - remove bad lookup of files from daq DB

- offline/QA/Jet/TrksInJetQAInclusiveFiller.cc
> Using clustMap instead of hitMap for clustQA

- offline/packages/tpccalib/TpcCentralMembraneMatching.cc
Changes to CMMatching to not reset distortion map if no laser event is found. Also sets up distortion correction container with proper settings (probably will add setter functions later) since it is not loaded in the same way as other distortion corrections which have properties set when they are loaded
> Fluctuation Distortions

- offline/packages/ResonanceJetTagging/ResonanceJetTagging.cc
Change to the correct JPSI PDG code (443)
> Fix to JPSI PDG code

- simulation/g4simulation/g4tpc/PHG4TpcDigitizer.cc
Fixes g4tpc digitization so hit adc is not erroneously truncated
> minor bug fix in g4tpc digitization

- offline/framework/frog/CreateFileList.pl
This PR adds the 15 and 50 GeV jets as types 33 and 34 to CreateFileLIst.pl. jenkins does not test this [skip-ci]
> add new 15 and 50 GeV jets

- offline/QA/Jet/CaloStatusMapper.cc
- offline/QA/Jet/ConstituentsinJets.cc
- offline/QA/Jet/DijetQA.cc
- offline/QA/Jet/JetKinematicCheck.cc
- offline/QA/Jet/JetSeedCount.cc
- offline/QA/Jet/RhosinEvent.cc
- offline/QA/Jet/StructureinJets.cc
- offline/QA/Jet/TrksInJetQABaseFiller.cc
- offline/QA/Jet/TrksInJetQABaseManager.cc
- offline/QA/Jet/TrksInJetQABaseManager.h
- offline/QA/Jet/TrksInJetQAClustManager.cc
- offline/QA/Jet/TrksInJetQAHitManager.cc
- offline/QA/Jet/TrksInJetQAInJetFiller.h
- offline/QA/Jet/TrksInJetQAInclusiveFiller.cc
- offline/QA/Jet/TrksInJetQAJetManager.cc
- offline/QA/Jet/TrksInJetQATrkManager.cc
> Add getting eventrho

- generators/sphstarlight/StarLight_To_HepMc.cc
- offline/packages/mbd/MbdCalib.cc
- offline/packages/mbd/MbdCalib.h
[comment]: Added a new calibration type, mbd_thresholds.  Not used in reconstruction, but is useful for analyzers.
> Added mbd_thresholds

- offline/framework/fun4allraw/SingleInttPoolInput.cc
Skipping abnormal BCO which causes to stop reading the pool
Skipping abnormal BCO which causes to stop reading the pool within cosmics.
Wil check more runs with this change for previous cosmics runs and also for last year pp and AuAu to ensure this change does not harm the production of previous good runs.
> skip too large BCO

- offline/framework/frog/CreateFileList.pl
This PR speeds up the writing of list files by quite a bit (<1min instead of 10min). jenkins does not check this [skip-ci]
> write listfiles in one shot from cached filenames

- offline/QA/Tpc/TpcLaserQA.cc
- offline/QA/Tpc/TpcLaserQA.h
Added new histograms of laser QA
> Additional Tpc Laser QA

- offline/packages/mbd/MbdEvent.cc
- offline/packages/mbd/MbdEvent.h
- offline/packages/mbd/MbdReco.cc
- offline/packages/mbd/MbdReco.h
[comment]: Added option to process all charge channels, no matter the status of the time channel.  This is needed to process the thresholds.
> added option to process all charge channels

- offline/packages/trackreco/PHActsVertexPropagator.cc
- offline/packages/trackreco/PHActsVertexPropagator.h
> (trackreco) Added handle to set track map name in propagator

- offline/packages/CaloReco/CaloTowerCalib.cc
- offline/packages/CaloReco/CaloTowerCalib.h
> update to calotowercalib, name convention

- simulation/g4simulation/g4detectors/Makefile.am
- simulation/g4simulation/g4detectors/PHG4sPHENIXMagnetDetector.cc
- simulation/g4simulation/g4detectors/PHG4sPHENIXMagnetDetector.h
- simulation/g4simulation/g4detectors/PHG4sPHENIXMagnetDisplayAction.cc
- simulation/g4simulation/g4detectors/PHG4sPHENIXMagnetDisplayAction.h
- simulation/g4simulation/g4detectors/PHG4sPHENIXMagnetSteppingAction.cc
- simulation/g4simulation/g4detectors/PHG4sPHENIXMagnetSteppingAction.h
- simulation/g4simulation/g4detectors/PHG4sPHENIXMagnetSubsystem.cc
- simulation/g4simulation/g4detectors/PHG4sPHENIXMagnetSubsystem.h
looks okay roughly, still need validations, I will keep this PR draft for now
- material scan(done)
- overlap check(done)
- look at MC dET/dEta
more results at(
https://indico.bnl.gov/event/28019/contributions/107024/attachments/61584/105990/babar_magnet_implementation.pdf )
> magnet G4 implementation based on BaBar's code

- generators/Herwig/HepMCTrigger/HepMCJetTrigger.cc
- generators/Herwig/HepMCTrigger/HepMCJetTrigger.h
- generators/Herwig/HepMCTrigger/Makefile.am
- generators/Herwig/HepMCTrigger/autogen.sh
- generators/Herwig/HepMCTrigger/configure.ac
This is a jet trigger for HepMC files in the same theme as the one for Pythia. This is needed for users to be able to generate Herwig files via [this macro set](https://github.com/sPHENIX-Collaboration/analysis/tree/master/HerwigToHepMCProduction)
This macro adds a new feature that allows for the user to both apply a filter on lead jet pt and an optional maximum number of events in the output HepMC file  …
> HepMCJetTrigger with event filter

- calibrations/calorimeter/calo_emc_pi0_tbt/pi0EtaByEta.cc
- calibrations/calorimeter/calo_emc_pi0_tbt/pi0EtaByEta.h
> pi0 calib: fieldname change

- offline/packages/NodeDump/DumpGlobalVertexMap.cc
This PR adds the dumping of the full vertex list in our GlobalVertex node
> print out v2 vertex lists

- offline/framework/ffarawmodules/ClockDiffCheck.cc
- offline/framework/ffarawmodules/ClockDiffCheck.h
- offline/framework/ffarawobjects/CaloPacket.h
- offline/framework/ffarawobjects/CaloPacketv1.cc
- offline/framework/ffarawobjects/CaloPacketv1.h
- offline/framework/ffarawobjects/OfflinePacket.h
- offline/framework/ffarawobjects/OfflinePacketv1.cc
- offline/framework/ffarawobjects/OfflinePacketv1.h
- offline/framework/fun4allraw/SingleTriggeredInput.cc
- offline/framework/fun4allraw/SingleTriggeredInput.h
Next version of the new event combiner, removed bogus error, treats fem event number errors (packet 6024 has a stuck bit). Adds status words to the offline packets and fem status words to the calo packets
> Better femclock check

- generators/FermiMotionAfterburner/FermiMotion.cc
- generators/FermiMotionAfterburner/FermimotionAfterburner.cc
- generators/ReactionPlaneAfterburner/ReactionPlaneAfterburner.cc
- generators/ReactionPlaneAfterburner/ReactionPlaneAfterburner.h
- generators/flowAfterburner/flowAfterburner.cc
- generators/flowAfterburner/main.cc
- generators/flowAfterburner/test.cc
- offline/packages/centrality/CentralityInfov1.cc
- offline/packages/centrality/CentralityInfov2.cc
catching up with clang-tidy of rarely changed packages
> Fix clang tidy 18

- offline/packages/mbd/MbdEvent.cc
The online version does not build with the current MbdEvent.cc. This PR patches this just enough to make it compile again
> comment out GetPrimaryVtx(topNode)

- offline/packages/TrackingDiagnostics/TrkrNtuplizer.cc
> fix initialization

- offline/packages/TpcLineLaserDiode/DiodeReco.cc
- offline/packages/TpcLineLaserDiode/DiodeReco.h
- offline/packages/TpcLineLaserDiode/Makefile.am
[comment]: <Updates DiodeReco module to use cdb instead of /sphenix/user/> (Please tell us something about this pull request)
[comment]: <Pull Request Updates the DiodeReco module to pull caen module waveform corrections from the cdb rather an /sphenix/user/ directory.> ( What does this PR do? Linking to talk in software meeting encouraged )
> Update to DiodeReco to use CDB

- offline/framework/fun4allraw/Fun4AllStreamingInputManager.cc
- offline/packages/KFParticle_sPHENIX/KFParticle_DST.cc
MVTX combiner doesnt work in standalone mode as the reference BCO defaults to 0. In standalone mode, the MVTX cant set a reference as the BCO search range is subtracted from 0, overflows and is always larger than the strobe BCO
> MVTX standalone bug fix

- simulation/g4simulation/g4waveformsim/CaloWaveformSim.cc
> CaloWaveformSim use the new calib names

- calibrations/calorimeter/calo_emc_pi0_tbt/pi0EtaByEta.cc
- [ x] Breaking change (fix or feature that would cause existing functionality to not work for users)
> err fix in "fitEtaPhiTowers" function

- offline/packages/CaloReco/CaloTowerBuilder.cc
> remove debug line

- simulation/g4simulation/g4detectors/PHG4sPHENIXMagnetSubsystem.cc
I forgot to initialize the used default parameter...
> G4Magnet: set default parameter used in stepping action

- offline/packages/TrackingDiagnostics/TrackResiduals.cc
- offline/packages/TrackingDiagnostics/TrackResiduals.h
- offline/packages/trackreco/PHActsTrkFitter.cc
- offline/packages/trackreco/PHActsTrkFitter.h
[comment]: <Update to direct navigation in ACTS track fit> (Please tell us something about this pull request)
[comment]: <Introduces approach surfaces to ACTS direct navigator by interleafing them with the source links. Also adds a branch of ntracks/vertex to the residual tree output to simplify plotting differentially wrt this quantity> ( What does this PR do? Linking to talk in software meeting encouraged )
> Directed nav update

- offline/packages/jetbackground/DetermineTowerBackground.cc
- offline/packages/jetbackground/Makefile.am
PR adds sEPD combined arms second order event plane angle to jet background subtraction.
> add sEPD psi_2 to jet background 

- offline/packages/KFParticle_sPHENIX/KFParticle_truthAndDetTools.cc
- offline/packages/KFParticle_sPHENIX/KFParticle_truthAndDetTools.h
I have added track to EMCal cluster matching functionality in KFParticle. I don't anticipate this breaking anything or requiring any other code to need to change in response.
This pull request will add a feature. My code updates KFParticle_truthAndDetTools.cc and KFParticle_truthAndDetTools.h to add track-calo matching. It also adds one new branch in the TTree KFP produces.  …
> Track-EMC clus matching added to KFP.

- offline/packages/tpc/Tpc3DClusterizer.cc
- offline/packages/trackreco/Makefile.am
- offline/packages/trackreco/PHLineLaserReco.cc
- offline/packages/trackreco/PHLineLaserReco.h
> version 0 of line laser reco

- offline/packages/tpccalib/Makefile.am
- offline/packages/tpccalib/TpcLaminationFitting.cc
- offline/packages/tpccalib/TpcLaminationFitting.h
Changed lamination fitting to get ZDC coincidence (required for seeding fit parameters) from database using same method as in TriggerRunInfoReco module and removes the std::maps that were previously hard-coded in.
> Lamination Fitting ZDC Coincidence

- offline/framework/fun4allraw/SingleTriggeredInput.cc
left an accidental event wise printout if the events cannot be aligned
> move printout to once per job

- offline/packages/tpccalib/TpcLaminationFitting.cc
- offline/packages/tpccalib/TpcLaminationFitting.h
Change setter function name and associated member variable name to make it more clear that they are regarding a QA file that is generated
https://github.com/sPHENIX-Collaboration/macros/pull/1142
> Lamination Fitting QA

- calibrations/calorimeter/calo_tower_slope/LiteCaloEval.cc
- offline/QA/Calorimeters/CaloFittingQA.cc
- offline/packages/CaloReco/CaloTowerBuilder.cc
> Bug fix: properly handle emcal empty packet in CaloTowerBuilder and QA

- offline/QA/Global/GlobalQA.cc
trigger bit convention in flux, remove trigger selections for now to avoid empty histograms.
> remove trig selections

- offline/packages/trigger/TriggerAnalyzer.cc
> update trigger analyzer to use triggerruninfo when emulator is called

- offline/framework/ffarawobjects/Gl1Packet.cc
- offline/framework/ffarawobjects/Gl1Packet.h
- offline/framework/ffarawobjects/Gl1Packetv2.cc
- offline/framework/ffarawobjects/Gl1Packetv2.h
- offline/framework/ffarawobjects/Gl1Packetv3.cc
- offline/framework/ffarawobjects/Gl1Packetv3.h
- offline/framework/ffarawobjects/Makefile.am
The gl1 packets had too many code duplications which makes the maintenance problematic.I pulled the iValue and lValue methods into the base class and removed superfluous methods from v3. Also made data members of v2 and v3 private so they can't be directly accessed downstream anymore.
[comment]: <> ( In case this is a draft PR, e.g. for running checks using Jenkins, please make the pull request as a draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/ …
> Simplify gl1packet

- offline/packages/trackreco/PHLineLaserReco.cc
> cluster z coordinate fix

- offline/framework/phool/RunnumberRange.h
typo fix - jenkins does not check this anyway [skip-ci]
> add forgotten endif

- offline/packages/jetbase/FastJetAlgo.cc
- offline/packages/jetbase/FastJetAlgo.h
- offline/packages/jetbase/FastJetOptions.cc
- offline/packages/jetbase/FastJetOptions.h
- offline/packages/jetbase/Jet.cc
- offline/packages/jetbase/Jet.h
- offline/packages/jetbase/JetAlgo.h
- offline/packages/jetbase/JetCalib.cc
- offline/packages/jetbase/JetCalib.h
- offline/packages/jetbase/JetContainer.cc
- offline/packages/jetbase/JetContainer.h
- offline/packages/jetbase/JetContainerv1.cc
- offline/packages/jetbase/JetContainerv1.h
- offline/packages/jetbase/JetMap.h
- offline/packages/jetbase/JetMapv1.cc
- offline/packages/jetbase/JetMapv1.h
- offline/packages/jetbase/JetProbeMaker.cc
- offline/packages/jetbase/JetReco.cc
- offline/packages/jetbase/JetReco.h
- offline/packages/jetbase/Jetv1.cc
- offline/packages/jetbase/Jetv1.h
- offline/packages/jetbase/Jetv2.cc
- offline/packages/jetbase/Jetv2.h
- offline/packages/jetbase/Makefile.am
- offline/packages/jetbase/SubjetIndicesv1.cc
> Update JetCalib to handle new calibration

- offline/QA/Calorimeters/CaloFittingQA.cc
- offline/QA/Calorimeters/CaloFittingQA.h
> CaloFit QA: missing packets hist

- offline/QA/Calorimeters/CaloFittingQA.cc
- offline/QA/Calorimeters/CaloFittingQA.h
- offline/QA/Calorimeters/CaloValid.cc
- offline/QA/Calorimeters/CaloValid.h
the calo qa package crashed the clang build. This PR fixed this
> fix clang build, clang-tidy, iwyu

- offline/framework/frog/CreateDstList.pl
The CreateDstList.pl script was pretty useless and clunky to use. In the meantime we restructured the columns of the datasets table - the replacement script makes use of them and just uses the user provided (build_cdb_version) tag instead of trying to assemble one. Jenkins does not test this [skip-ci] …
> use new datasets table columns for faster lookup

- offline/framework/fun4allraw/SingleTriggeredInput.cc
- offline/framework/fun4allraw/SingleTriggeredInput.h
The special handling for problems in the first event was also triggered for subsequent events (especially for those skipped gl1 events). This PR applies the first event fixes only for the first event 
> run first event fixes only for first event

- offline/QA/Calorimeters/CaloFittingQA.cc
> Change error option in pedestal histograms to RMS with option s.

- calibrations/tpc/generator/AnnularFieldSim.cc
- calibrations/tpc/generator/AnnularFieldSim.h
- calibrations/tpc/generator/generate_distortion_map.C
[comment]: This allows the user to move the TPC relative to the magnetic field, for purposes of generating the distortions.  at x=y=z=0 it produces distortions consistent with previous versions from 2024.
> Distortion adjust tpc pos

- offline/QA/Tracking/Makefile.am
- offline/QA/Tracking/TrackFittingQA.cc
- offline/QA/Tracking/TrackFittingQA.h
Includes per-charge histograms of kinematic variables available from the SvtxTrack class
Currently compiles and works
May need additional histograms in the future
> Added a QA module for fitted tracks

- offline/packages/tpccalib/TpcCentralMembraneMatching.cc
- offline/packages/tpccalib/TpcCentralMembraneMatching.h
New toggle to swap between only calculating residual correction (to be used for fluctuations) and total correction after static is applied (for average in order to include lamination correction in distortion map to provide a single map)
> CM Matching Toggles

- offline/QA/Tracking/TrackFittingQA.h
The build crashes with an undeclared variable - this will be merged right away but jenkins will run over this
> add missing m_state_map_node_name

- offline/framework/fun4allraw/SingleMicromegasPoolInput_v2.cc
Another attempt at fixing Micromegas offline BCO QA for large runs
> TH1L -> TH1D

- offline/QA/Tracking/CosmicTrackQA.cc
- offline/QA/Tracking/CosmicTrackQA.h
- offline/QA/Tracking/InttClusterQA.cc
- offline/QA/Tracking/MicromegasClusterQA.cc
- offline/QA/Tracking/MicromegasClusterQA.h
- offline/QA/Tracking/MvtxClusterQA.cc
- offline/QA/Tracking/SiliconSeedsQA.cc
- offline/QA/Tracking/SiliconSeedsQA.h
- offline/QA/Tracking/TpcClusterQA.cc
- offline/QA/Tracking/TpcSeedsQA.cc
- offline/QA/Tracking/TpcSeedsQA.h
- offline/QA/Tracking/TpcSiliconQA.cc
- offline/QA/Tracking/TpcSiliconQA.h
- offline/QA/Tracking/TrackFittingQA.cc
- offline/QA/Tracking/TrackFittingQA.h
- offline/QA/Tracking/VertexQA.cc
Start to move from boost::format to std::format, clang-tidy found a bunch of things which should not propagate (e.g. using .c_str() if not needed).
> Std format

- offline/QA/Jet/JetQADefs.h
Adding options for new triggers to jet QA for run 2025 Au+Au
> adding additional triggers to jet QA for 2025 Au+Au

- offline/packages/trackreco/DSTClusterPruning.cc
- offline/packages/trackreco/DSTClusterPruning.h
> Cluster pruning update

- offline/QA/Global/GlobalQA.cc
[comment]: Changed the histogram ranges for auau
> Mods to mbd histograms in globalQA for AuAu

- offline/framework/fun4allraw/MicromegasBcoMatchingInformation_v2.cc
This is a port of https://github.com/sPHENIX-Collaboration/coresoftware/pull/3724
> updated modebits to use equal operator rather than bitwise and.

- offline/packages/jetbackground/BaseBeamBackgroundFilter.h
- offline/packages/jetbackground/BeamBackgroundFilterAndQA.cc
- offline/packages/jetbackground/BeamBackgroundFilterAndQA.h
- offline/packages/jetbackground/CopyAndSubtractJets.cc
- offline/packages/jetbackground/DetermineEventRho.cc
- offline/packages/jetbackground/DetermineEventRho.h
- offline/packages/jetbackground/DetermineTowerBackground.cc
- offline/packages/jetbackground/DetermineTowerRho.cc
- offline/packages/jetbackground/DetermineTowerRho.h
- offline/packages/jetbackground/EventRho.h
- offline/packages/jetbackground/EventRhov1.cc
- offline/packages/jetbackground/EventRhov1.h
- offline/packages/jetbackground/FastJetAlgoSub.cc
- offline/packages/jetbackground/FastJetAlgoSub.h
- offline/packages/jetbackground/JetBackgroundCut.cc
- offline/packages/jetbackground/JetBackgroundCut.h
- offline/packages/jetbackground/NullFilter.cc
- offline/packages/jetbackground/NullFilter.h
- offline/packages/jetbackground/RetowerCEMC.cc
- offline/packages/jetbackground/StreakSidebandFilter.cc
- offline/packages/jetbackground/StreakSidebandFilter.h
- offline/packages/jetbackground/SubtractTowersCS.cc
- offline/packages/jetbackground/TowerBackground.h
- offline/packages/jetbackground/TowerBackgroundv1.cc
- offline/packages/jetbackground/TowerRho.h
- offline/packages/jetbackground/TowerRhov1.cc
- offline/packages/jetbackground/TowerRhov1.h
clang-tidy fixes and removal of unused include files for jetbackground package
> clang tools for jetbackground, iwyu

- offline/QA/Tracking/TrackFittingQA.cc
- offline/QA/Tracking/TrackFittingQA.h
* still need to investigate an off-by-one state counting in MVTX
> Added handles for track cuts

- offline/packages/CaloReco/CaloTowerBuilder.cc
- offline/packages/CaloReco/CaloTowerBuilder.h
- offline/packages/CaloReco/CaloWaveformProcessing.cc
- offline/packages/CaloReco/CaloWaveformProcessing.h
This PR is an update for the ONNX processing. We now have 12 samples instead of 31. Onnx still returns 3 parameters (energy,time,pedestal) while the template fit returns 5, so it needs some special handling for the returned vector
> Onnx fix 1

- offline/framework/fun4allraw/SingleMicromegasPoolInput_v2.cc
- offline/framework/fun4allraw/SingleMicromegasPoolInput_v2.h
Title says it all. This will provide more detail information to offline QA
> added per fee dropped waveforms histograms

- offline/packages/trackreco/ALICEKF.h
- offline/packages/trackreco/Makefile.am
- offline/packages/trackreco/PHSimpleKFProp.cc
- offline/packages/trackreco/PHSimpleKFProp.h
This PR implement Open MP to parallelize the main seed loop in PHSimpleKFProp
The default number of threads is set to 2. 
It is configurable at run time.
See presentation at https://indico.bnl.gov/event/28561/contributions/110334/attachments/63485/108957/talk.pdf
> Simple kfprop parallelization

- offline/framework/fun4allraw/TpcTimeFrameBuilder.cc
- offline/framework/fun4allraw/TpcTimeFrameBuilder.h
Following https://github.com/sPHENIX-Collaboration/coresoftware/pull/3757 , adding the last digital current (DC) readout tagger's GL1 BCO to the digital current debug TTree, so 
1. readings from various channels could be grouped together to make a DC frame
2. DC reading can be synced with sequence of events via GL1 BCO
Example output looks like: 
```
root data/tpc-00069260-05_1.list_DigitalCurrentDebugTTree.root
root [0] 
Attaching file data/tpc-00069260-05_1.list_DigitalCurrentDebugTTree.root as _file0...
(TFile *) 0x4678dc0
root [1] …
```
> Adding GL1 BCO to TPC digital current debug TTree

- calibrations/intt/inttcalib/InttCalib.h
- calibrations/tpc/TpcDVCalib/configure.ac
- offline/QA/EventDisplay/configure.ac
- offline/QA/Intt/configure.ac
- offline/QA/Mvtx/configure.ac
- offline/QA/Tpc/configure.ac
- offline/QA/Tracking/configure.ac
- offline/packages/TrackerMillepedeAlignment/configure.ac
- offline/packages/TrackingDiagnostics/configure.ac
- offline/packages/tpccalib/configure.ac
- offline/packages/trackreco/configure.ac
This PR compiles our code with clang 20 and openmp. There is still a problem with Units.hpp from Acts - so jenkins will fail in the clang compiler (and nobody will notice...)
> build with clang 20 and openmp

- offline/QA/Tracking/TrackFittingQA.cc
- offline/QA/Tracking/TrackFittingQA.h
- offline/packages/intt/InttMapping.cc
Added crossing cuts and additional quality cut
* including trivial fix an intt printout statement
> Added crossing cuts and additional quality cut

- calibrations/calorimeter/calo_tower_slope/HCalCosmics.h
last problem before clang build works again
> fix last clang problem

- offline/packages/trackreco/Makefile.am
- offline/packages/trackreco/PHCASiliconSeeding.cc
- offline/packages/trackreco/PHCASiliconSeeding.h
Introduces a new module, PHCASiliconSeeding, which provides an alternative silicon track seeding algorithm to PHActsSiliconSeeding for diagnosis of seeding issues. This module uses a CA seeding approach similar to the TPC, which relies entirely on the cluster global positions and avoids using most of the ACTS components involved in the default seeding algorithm. …
> New module PHCASiliconSeeding

- offline/QA/Global/GlobalQA.cc
- offline/QA/Global/GlobalQA.h
- Updated sEPD Offline QA histogram ranges for AuAu data
- Updated trigger selection for sEPD QA plots
> sEPD Offline QA Plot Updatees

- offline/QA/Tpc/TpcLaserQA.cc
- offline/QA/Tpc/TpcLaserQA.h
New plots of diffuse laser peak in TPC for offline QA monitoring
> TPCLaserQA Timing Plots

- offline/framework/fun4allraw/SingleGl1TriggeredInput.h
- offline/framework/fun4allraw/SingleTriggeredInput.cc
- offline/framework/fun4allraw/SingleTriggeredInput.h
> update bug in triggered event combiner + dealing GL1 first

- offline/packages/TrackingDiagnostics/TrkrNtuplizer.cc
- offline/packages/TrackingDiagnostics/TrkrNtuplizer.h
> add driftlength correction for dedx

- offline/framework/frog/CreateDstList.pl
This PR makes the CreateDstList.pl script more user friendly and faster (the db was timing out with the old sql queries). Jenkins does not check this [skip-ci]
> Fix getdsts

- offline/QA/KFParticle/QAKFParticle.cc
Reduced QA pT range from 10 to 5 GeV
> CD: Reduced pT range from 10 to 5 GeV

- offline/packages/trackreco/ALICEKF.cc
- offline/packages/trackreco/ALICEKF.h
- offline/packages/trackreco/MakeActsGeometry.cc
- offline/packages/trackreco/PHCosmicsFilter.h
- offline/packages/trackreco/PHGenFitTrkFitter.cc
- offline/packages/trackreco/PHLineLaserReco.h
- offline/packages/trackreco/PHRaveVertexing.cc
- offline/packages/trackreco/PHSimpleKFProp.cc
- offline/packages/trackreco/PHSimpleKFProp.h
- offline/packages/trackreco/PHStreakFinder.h
- offline/packages/trackreco/PrelimDistortionCorrection.cc
- offline/packages/trackreco/PrelimDistortionCorrection.h
- offline/packages/trackreco/PrelimDistortionCorrectionAuAu.cc
- offline/packages/trackreco/PrelimDistortionCorrectionAuAu.h
Reverts sPHENIX-Collaboration/coresoftware#3821
> Revert "Phfield cleanup"

- generators/phhepmc/HepMCFlowAfterBurner.cc
> added print statement for flow modifications

- offline/packages/CaloReco/CaloWaveformFitting.cc
> calo fitting saturation handle bug fix

- offline/packages/trackreco/ALICEKF.cc
- offline/packages/trackreco/ALICEKF.h
- offline/packages/trackreco/MakeActsGeometry.cc
- offline/packages/trackreco/PHCosmicsFilter.h
- offline/packages/trackreco/PHGenFitTrkFitter.cc
- offline/packages/trackreco/PHLineLaserReco.h
- offline/packages/trackreco/PHRaveVertexing.cc
- offline/packages/trackreco/PHSimpleKFProp.cc
- offline/packages/trackreco/PHSimpleKFProp.h
- offline/packages/trackreco/PHStreakFinder.h
- offline/packages/trackreco/PrelimDistortionCorrection.cc
- offline/packages/trackreco/PrelimDistortionCorrection.h
- offline/packages/trackreco/PrelimDistortionCorrectionAuAu.cc
- offline/packages/trackreco/PrelimDistortionCorrectionAuAu.h
This is a new take on https://github.com/sPHENIX-Collaboration/coresoftware/pull/3821 that addresses the bug found by Xudong on real data. 
TODO: 
- still need to verify that field-off workflow is still working 
- this PR not being urgent, can wait for having real-data Jenkins QA in place, (the missing of which this PR was pushed in the first place despite the introduced bug in proton-proton reconstruction …
> Phfield cleanup (take 2)

- offline/packages/TrackerMillepedeAlignment/HelicalFitter.cc
- offline/packages/trackreco/Makefile.am
- offline/packages/trackreco/WeightedFitter.cc
- offline/packages/trackreco/WeightedFitter.h
* Tested global derivatives against HelicalFitter (looks good)
* Can be used with MakeMilleFiles in alignment workflow
* Still need to apply TPC distortions to cluster positions--currently only drift velocity is used
> Added class to perform weighted linear fits

- offline/packages/eventplaneinfo/EventPlaneCalibration.cc
- offline/packages/eventplaneinfo/EventPlaneCalibration.h
- offline/packages/eventplaneinfo/Makefile.am
This PR adds Ejiros event plane calibration module to the event plane packages
> add event plane calibration

- offline/packages/KFParticle_sPHENIX/KFParticle_truthAndDetTools.cc
Fix a bug when calculating phi value of emcal phi value.
> KFP: emcal phi bug fix

- offline/QA/Jet/ConstituentsinJets.cc
- offline/QA/Jet/ConstituentsinJets.h
- offline/QA/Jet/JetSeedCount.h
> Changed pt ranges and improved x-axis dexterity 

- .clang-tidy
- offline/packages/CaloReco/CaloGeomMapping.cc
- offline/packages/CaloReco/CaloGeomMapping.h
- offline/packages/CaloReco/CaloRecoUtility.cc
- offline/packages/CaloReco/CaloRecoUtility.h
- offline/packages/CaloReco/PhotonClusterBuilder.cc
- offline/packages/CaloReco/PhotonClusterBuilder.h
- offline/packages/CaloReco/RawClusterBuilderTemplate.cc
- offline/packages/trackreco/PHRaveVertexing.cc
- offline/packages/trackreco/PHRaveVertexing.h
trying to get rid of specific errors which affect the performance.
> Clang tidy 25

- calibrations/calorimeter/calo_tower_slope/HCalCosmics.cc
- calibrations/calorimeter/calo_tower_slope/HCalCosmics.h
- calibrations/calorimeter/calo_tower_slope/LiteCaloEval.cc
- calibrations/calorimeter/calo_tower_slope/LiteCaloEval.h
- calibrations/tpc/fillDigitalCurrentMaps/readDigitalCurrents.cc
- generators/phhepmc/Fun4AllOscarInputManager.cc
- generators/phhepmc/Fun4AllOscarInputManager.h
- generators/phhepmc/PHGenIntegral.cc
- generators/phhepmc/PHHepMCGenEvent.cc
- generators/phhepmc/PHHepMCGenEvent.h
- generators/phhepmc/PHHepMCGenEventv1.cc
- generators/phhepmc/PHHepMCGenEventv1.h
- generators/sphstarlight/StarLight_To_HepMc.cc
- offline/framework/ffamodules/CDBInterface.cc
- offline/framework/ffamodules/Timing.cc
- offline/framework/ffamodules/Timing.h
get some more packages off the clang-tidy complaint list
> Clang tidy 26

- offline/packages/Skimmers/CaloPacket/CaloPacketSkimmer.cc
- offline/packages/Skimmers/CaloPacket/CaloPacketSkimmer.h
now we print out the all of the missing packet at the end of the run so we can pipe those info to the condor log file
> Calo packet skimmer update

- offline/QA/Global/GlobalQA.cc
- offline/QA/Global/GlobalQA.h
[comment]: prior fixes to mbd histograms got overwritten, I put the fixes back.  I also put all the mbd code in a process_mbd() method to help organize and prevent any inadvertent changes.
> restored mbd histogram fixes, added process_mbd()

- offline/packages/TrackerMillepedeAlignment/HelicalFitter.cc
- offline/packages/trackreco/WeightedFitter.cc
- offline/packages/trackreco/WeightedFitter.h
* now correctly modifies TPC cluster errors using utility class
* fixed track seed parameters supplied to the TrackSeed_v2 instance
* fixed misleading typo in HelicalFitter printout
> WeightedFitter fixes

- offline/QA/Tracking/TrackFittingQA.cc
- offline/QA/Tracking/TrackFittingQA.h
- offline/packages/PHField/PHFieldConfig.cc
- offline/packages/PHField/PHFieldInterpolated.cc
- offline/packages/PHField/PHFieldInterpolated.h
* InterpolatedFieldmap now finished and tested (working)
* New trackfitting qa feature (pt error vs pt histogram)
> Fieldmap and trackfittingqa changes

- calibrations/tpc/fillDigitalCurrentMaps/readDigitalCurrents.cc
- offline/QA/EventDisplay/TrackerEventDisplay.cc
- offline/QA/Tracking/TpcClusterQA.cc
- offline/packages/TrackingDiagnostics/TrackResiduals.cc
- offline/packages/TrackingDiagnostics/TrkrNtuplizer.cc
- offline/packages/tpc/LaserClusterizer.cc
- offline/packages/tpc/Tpc3DClusterizer.cc
- offline/packages/tpc/TpcClusterizer.cc
- offline/packages/tpc/TpcCombinedRawDataUnpacker.cc
- offline/packages/tpc/TpcCombinedRawDataUnpackerDebug.cc
- offline/packages/tpc/TpcSimpleClusterizer.cc
- offline/packages/tpccalib/TpcDirectLaserReconstruction.cc
- simulation/g4simulation/g4detectors/PHG4TpcCylinderGeom.cc
- simulation/g4simulation/g4detectors/PHG4TpcCylinderGeom.h
- simulation/g4simulation/g4eval/SvtxEvaluator.cc
- simulation/g4simulation/g4eval/SvtxTruthEval.cc
- simulation/g4simulation/g4tpc/PHG4TpcDetector.cc
- simulation/g4simulation/g4tpc/PHG4TpcDetector.h
- simulation/g4simulation/g4tpc/PHG4TpcPadBaselineShift.cc
- simulation/g4simulation/g4tpc/PHG4TpcPadPlaneReadout.cc
- simulation/g4simulation/g4tpc/PHG4TpcPadPlaneReadout.h
- simulation/g4simulation/g4tpc/TpcClusterBuilder.cc
This PR goes back to the v4 fee map after we have convinced ourselves it is correct. Starting this now to test in jenkins, the CDB will also need an update
> feat: tpc fee map v4

- offline/framework/frog/CreateFileList.pl
This adds the 5GeV jet selection to CreateFileList.pl, jenkins does not test this [skip-ci]
> add 5GeV Jets to CreateFileList.pl

- offline/packages/CaloReco/Makefile.am
> include photon cluster builder in the makefile

- calibrations/framework/oncal/OnCalServer.cc
- offline/QA/EventDisplay/TrackerEventDisplay.cc
- offline/packages/trackreco/PHActsVertexPropagator.cc
- offline/packages/trackreco/WeightedFitter.cc
- offline/packages/trackreco/WeightedFitter.h
- simulation/g4simulation/g4tpc/PHG4TpcCentralMembrane.h
- simulation/g4simulation/g4tpc/PHG4TpcDetector.cc
- simulation/g4simulation/g4tpc/PHG4TpcDetector.h
- simulation/g4simulation/g4tpc/PHG4TpcDigitizer.cc
- simulation/g4simulation/g4tpc/PHG4TpcDirectLaser.cc
- simulation/g4simulation/g4tpc/PHG4TpcDirectLaser.h
- simulation/g4simulation/g4tpc/PHG4TpcElectronDrift.cc
- simulation/g4simulation/g4tpc/PHG4TpcElectronDrift.h
- simulation/g4simulation/g4tpc/PHG4TpcEndCapDetector.cc
- simulation/g4simulation/g4tpc/PHG4TpcEndCapDetector.h
- simulation/g4simulation/g4tpc/PHG4TpcPadBaselineShift.h
- simulation/g4simulation/g4tpc/PHG4TpcPadPlaneReadout.cc
- simulation/g4simulation/g4tpc/PHG4TpcPadPlaneReadout.h
- simulation/g4simulation/g4tpc/PHG4TpcSubsystem.h
- simulation/g4simulation/g4tpc/TpcClusterBuilder.cc
This fixes the clang-tidy warnings which have crept in over the last couple of days
> Clang tidy 27

- simulation/g4simulation/g4ohcal/PHG4OHCalDetector.cc
- simulation/g4simulation/g4ohcal/PHG4OHCalDetector.h
- simulation/g4simulation/g4ohcal/PHG4OHCalDisplayAction.cc
- simulation/g4simulation/g4ohcal/PHG4OHCalSteppingAction.cc
- simulation/g4simulation/g4ohcal/PHG4OHCalSubsystem.h
- simulation/g4simulation/g4waveformsim/CaloWaveformSim.cc
- simulation/g4simulation/g4waveformsim/CaloWaveformSim.h
going down the list of packages - g4ohcal and g4waveformsim pass now
> Clang tidy 28

- calibrations/calorimeter/calo_emc_pi0_tbt/pi0EtaByEta.cc
- calibrations/calorimeter/calo_emc_pi0_tbt/pi0EtaByEta.h
> pi0 calib: adding a few hists

- offline/packages/trackreco/PHCASiliconSeeding.cc
- offline/packages/trackreco/PHCASiliconSeeding.h
> fix: remove extraneous setter

- offline/database/rundb/CaloTemp.cc
- offline/database/rundb/CaloTemp.h
- offline/database/rundb/Makefile.am
- offline/database/rundb/testODBC.cc
Start using common DBInterface to connect to odbc DBs instead of local implementations
> use new DBInterface to connect to odbc DBs
