simulation/g4simulation/g4detectors/PHG4HcalSteppingAction.cc, simulation/g4simulation/g4detectors/PHG4HcalSteppingAction.h, simulation/g4simulation/g4detectors/PHG4HcalSubsystem.cc, simulation/g4simulation/g4detectors/PHG4HcalSubsystem.h, simulation/g4simulation/g4detectors/PHG4OuterHcalSteppingAction.cc, simulation/g4simulation/g4detectors/PHG4OuterHcalSteppingAction.h, simulation/g4simulation/g4detectors/PHG4OuterHcalSubsystem.cc, simulation/g4simulation/g4detectors/PHG4OuterHcalSubsystem.h, simulation/g4simulation/g4detectors/PHG4SpacalSteppingAction.cc
To get the branch: 
https://github.com/sPHENIX-Collaboration/coresoftware/tree/HCalWithCorrection 
To check the proposed update:
https://github.com/sPHENIX-Collaboration/coresoftware/compare/HCalWithCorrection 
To try it out in compiled binary:
You can use my local build at /phenix/u/jinhuang/work/sPHENIX/simulation//install/lib
To try it out with a DST reader:
Run /direct/phenix+sim02/phnxreco/ePHENIX/jinhuang/simulation/test/SPACAL_test/Fun4All_G4_sPHENIX.C
One example output file in ROOT readable format:
/direct/phenix+sim02/phnxreco/ePHENIX/jinhuang/simulation/test/SPACAL_test/G4sPHENIXCells.root_DSTReader.root
The changes are:
Change 1: Besides saving raw Geant4 energy deposition in the original edep variable, now we also save another variable proportional to the visible energy …
=> Add Birk's law and update light collection model

simulation/g4simulation/g4main/PHG4SimpleEventGenerator.cc, simulation/g4simulation/g4main/PHG4SimpleEventGenerator.h
Simple changes to add the ability to generate particles of fixed momentum.  Calling set_p_fixed() with a positive values will generate particles of fixed momentum rather than pT between a min and max range.  Default value for _p_fixed is -1.0 so default behavior will be as before.
=> added method to generate particles of fixed total momentum

offline/packages/NodeDump/DumpPHG4HitContainer.cc, simulation/g4simulation/g4detectors/PHG4CEmcTestBeamSteppingAction.cc, simulation/g4simulation/g4detectors/PHG4CrystalCalorimeterSteppingAction.cc, simulation/g4simulation/g4detectors/PHG4EnvelopeSteppingAction.cc, simulation/g4simulation/g4detectors/PHG4ForwardHcalSteppingAction.cc, simulation/g4simulation/g4detectors/PHG4HcalPrototypeSteppingAction.cc, simulation/g4simulation/g4detectors/PHG4HcalSteppingAction.cc, simulation/g4simulation/g4detectors/PHG4InnerHcalSteppingAction.cc, simulation/g4simulation/g4detectors/PHG4OuterHcalSteppingAction.cc, simulation/g4simulation/g4detectors/PHG4SpacalSteppingAction.cc, simulation/g4simulation/g4main/PHG4Hit.cc, simulation/g4simulation/g4main/PHG4Hit.h, simulation/g4simulation/g4main/PHG4HitContainer.cc, simulation/g4simulation/g4main/PHG4HitContainer.h, simulation/g4simulation/g4main/PHG4HitDefs.h, simulation/g4simulation/g4main/PHG4Hitv1.cc, simulation/g4simulation/g4main/PHG4Hitv1.h
The 64 bit keys were only partially implemented - The PHG4HitContainer used them but the G4Hits used 32 bit ids. Adding to this was a mixture of implicit conversions of unsigned int -> unsigned long long and vice versa which resulted in rather strange 32 bit keys which we would have noticed in hijing events. Now all is tested and functional (includign the generic G4Hit copy ctor) and the g4 sim results themselves did not change.
Somehow the old distinction between px/py/pz at the entry and exit point got lost - both ended up in the same property and the exit hit always won that. This is important for the tracking evaluation, for non cylinder shaped calorimeters keeping this info does not make sense and it was removed. Updating the properties to include px/py/pz at the exit point made a …
=> consistent 64 bit keys and hit ids, fixed hit properties

offline/packages/NodeDump/DumpPHG4CylinderCellContainer.cc, simulation/g4simulation/g4detectors/PHG4BlockCellGeom.cc, simulation/g4simulation/g4detectors/PHG4BlockCellReco.cc, simulation/g4simulation/g4detectors/PHG4CylinderCell.h, simulation/g4simulation/g4detectors/PHG4CylinderCellContainer.cc, simulation/g4simulation/g4detectors/PHG4CylinderCellContainer.h, simulation/g4simulation/g4detectors/PHG4CylinderCellDefs.h, simulation/g4simulation/g4detectors/PHG4CylinderCellGeom.cc, simulation/g4simulation/g4detectors/PHG4CylinderCellReco.cc, simulation/g4simulation/g4detectors/PHG4CylinderCellv1.cc, simulation/g4simulation/g4detectors/PHG4CylinderCellv1.h, simulation/g4simulation/g4detectors/PHG4CylinderCellv2.h, simulation/g4simulation/g4detectors/PHG4HcalCellReco.cc, simulation/g4simulation/g4detectors/PHG4SlatCellReco.cc, simulation/g4simulation/g4eval/PHG4CalEvaluator.C, simulation/g4simulation/g4eval/PHG4CalEvaluator.h, simulation/g4simulation/g4eval/PHG4Evaluator.C, simulation/g4simulation/g4eval/PHG4Evaluator.h, simulation/g4simulation/g4hough/PHG4SvtxAddConnectedCells.C, simulation/g4simulation/g4main/PHG4Hit.h, simulation/g4simulation/g4main/PHG4HitContainer.cc, simulation/g4simulation/g4main/PHG4HitContainer.h, simulation/g4simulation/g4main/PHG4HitDefs.h, simulation/g4simulation/g4main/PHG4Hitv1.cc, simulation/g4simulation/g4main/PHG4Hitv1.h
Fixed all hitid issues I could find - the eval links in the evaluator might still not be happy but the code passes valgrind
=> fixes for 32-64 bit g4hit id, use typedefs for key types

simulation/g4simulation/g4hough/PHG4HoughTransform.C, simulation/g4simulation/g4hough/PHG4SvtxAddConnectedCells.C, simulation/g4simulation/g4hough/PHG4SvtxAddConnectedCells.h, simulation/g4simulation/g4hough/PHG4SvtxBeamSpotReco.C, simulation/g4simulation/g4hough/PHG4SvtxBeamSpotReco.h, simulation/g4simulation/g4hough/PHG4SvtxClusterizer.C, simulation/g4simulation/g4hough/PHG4SvtxClusterizer.h, simulation/g4simulation/g4hough/PHG4SvtxDeadArea.C, simulation/g4simulation/g4hough/PHG4SvtxDeadArea.h, simulation/g4simulation/g4hough/PHG4SvtxDigitizer.C, simulation/g4simulation/g4hough/PHG4SvtxDigitizer.h, simulation/g4simulation/g4hough/PHG4SvtxThresholds.C, simulation/g4simulation/g4hough/PHG4SvtxThresholds.h, simulation/g4simulation/g4hough/PHG4SvtxTrackProjection.C, simulation/g4simulation/g4hough/PHG4SvtxTrackProjection.h, simulation/g4simulation/g4hough/PHG4TrackGhostRejection.C, simulation/g4simulation/g4hough/PHG4TrackGhostRejection.h
A lot of reco modules still used the PHTypedNodeIterator which was replaced by getClass<> about 10 years ago. I really do not want this to propagate again from here. Insure claimed a string problem in a dictionary which might be caused by using const chars as module name (replaced by strings many years ago), so I replaced const chars by std::strings in the ctors of the classes I looked at. Also a lot of arguments were not const even if they could be and using maps like return map[...] is not const while map.find(...)->second is.
=> cleanup of g4hough code

simulation/g4simulation/g4main/PHG4Hitv1.cc
Avoid using NAN and integer value in the same c?a:b expression. Otherwise, a wrong value may be returned by the following functions:
* PHG4Hitv1::get_property_uint(const PROPERTY prop_id)
* PHG4Hitv1::get_property_int(const PROPERTY prop_id)
which propagate the wrong result to many int/uint get functions of PHG4Hit.
=> Fixing a bug in reading of PHG4Hit property tags

simulation/g4simulation/g4cemc/Makefile.am, simulation/g4simulation/g4cemc/RawCluster.h, simulation/g4simulation/g4cemc/RawClusterBuilder.cc, simulation/g4simulation/g4cemc/RawClusterBuilderv1.cc, simulation/g4simulation/g4cemc/RawClusterBuilderv1.h, simulation/g4simulation/g4cemc/RawClusterContainer.h, simulation/g4simulation/g4cemc/RawClusterDefs.h, simulation/g4simulation/g4cemc/RawClusterv1.cc, simulation/g4simulation/g4cemc/RawClusterv1.h, simulation/g4simulation/g4cemc/RawClusterv1LinkDef.h, simulation/g4simulation/g4eval/CaloRawClusterEval.C
Now the clusters follow the same scheme as our hits, cells and towers. No change in the clusters themselves. This made a small change in the evaluator necessary.
=> replace eta/phi bin based tower key in cluster by towerid from towers, store tower energy for easier access

simulation/g4simulation/g4eval/JetRecoEval.C, simulation/g4simulation/g4eval/SvtxEvaluator.C, simulation/g4simulation/g4eval/SvtxTrackEval.C, simulation/g4simulation/g4eval/SvtxTruthEval.C, simulation/g4simulation/g4hough/PHG4HoughTransform.C, simulation/g4simulation/g4hough/PHG4HoughTransform.h, simulation/g4simulation/g4hough/PHG4HoughTransformTPC.C, simulation/g4simulation/g4hough/PHG4HoughTransformTPC.h, simulation/g4simulation/g4hough/PHG4SvtxTrackProjection.C, simulation/g4simulation/g4hough/PHG4SvtxTrackProjection.h, simulation/g4simulation/g4hough/PHG4TrackGhostRejection.C, simulation/g4simulation/g4hough/SvtxTrack.C, simulation/g4simulation/g4hough/SvtxTrack.h, simulation/g4simulation/g4jets/TrackJetInput.C
This merge will rework the SvtxTrack object so that it is suitable for additional modularization of the tracking reconstruction. The track object can now store a projection of the track fit at multiple locations along the path. The default state vector (at the point of closest approach) is exposed through svtxtrack->get_??() methods. Some analysis modules will need minor updates to follow the new interface. I also fix some minor inconsistencies in some method definitions and a bug that swapped the x and y PCA values.
In reworking the object's internal storage I have recovered 2 kilobytes per track for silicon-only tracking. So central event storage is down over 1 MB per event. There is also space savings for the TPC tracks, but not as large a change.
The g4hough's i/o objects will still …
=> SvtxTrack storage and interface revision

simulation/g4simulation/g4main/PHG4Reco.cc, simulation/g4simulation/g4main/PHG4Reco.h
CLHEP complains when it gets a negative seed:
Seed for HepJamesRandom must be non-negative
Seed value supplied was -541589200
Using its absolute value instead
Even though PHRandomSeed generates a uint the G4Seed interface casts it into an int so overflows can go negative. So I modified G4Seed to pass an uint instead. I thought I had caught this problem on a previous commit but missed this aspect. The logic remains the same, but CLHEP is now quiet. Enjoy.
=> rollover on G4Seed was still passing a negative seed to CLHEP

simulation/g4simulation/g4detectors/PHG4InnerHcalDetector.cc, simulation/g4simulation/g4detectors/PHG4InnerHcalDetector.h, simulation/g4simulation/g4detectors/PHG4InnerHcalParameters.cc
I changed the default number of scintilator tiles from 22 to 24 (to match it to the electronics channels which go in groups of 8).
I went over the geometry again. In the old version you can see gaps between the left inner hcal envelope and the beginning of the scintilators (red):
In the new version those are gone:
There is still a minute issue at low tilt angles (where the scintilator face touches the envelope instead of the corner) which requires subtracting 0.1mm from the scintilator length to avoid overlaps with the envelope. Given the precision of cutting scintillators I don't think I'll go through that math.
=> New version for the inner hcal - the scintillators were too short in the previous version

simulation/g4simulation/g4hough/SvtxTrackLinkDef.h
This should fix issue #47. Since this are inner objects I wasn't reminded by the compilation to do this.
=> add dictionaries for inner svtx objects

generators/PHPythia8/Makefile.am, generators/PHPythia8/PHPythia8.C, generators/PHPythia8/PHPythia8.h, generators/PHPythia8/README, generators/PHPythia8/phpythia8.cfg, simulation/g4simulation/g4eval/CaloEvaluator.C, simulation/g4simulation/g4eval/CaloRawTowerEval.C, simulation/g4simulation/g4eval/CaloTruthEval.C, simulation/g4simulation/g4eval/JetRecoEval.C, simulation/g4simulation/g4eval/SvtxClusterEval.h, simulation/g4simulation/g4eval/SvtxEvalStack.C, simulation/g4simulation/g4eval/SvtxEvalStack.h, simulation/g4simulation/g4eval/SvtxHitEval.C, simulation/g4simulation/g4eval/SvtxHitEval.h, simulation/g4simulation/g4eval/SvtxTrackEval.h, simulation/g4simulation/g4eval/SvtxTruthEval.C, simulation/g4simulation/g4eval/SvtxVertexEval.C, simulation/g4simulation/g4eval/SvtxVertexEval.h, simulation/g4simulation/g4main/PHG4TruthInfoContainer.cc
This merge will bring in the modifications to PHPythia8 to get it read for use (random number seeding mostly). In testing PHPythia8, I discovered all the ways the copied primaries & primary vertexes are not equivalent to the input primary storage and modified the eval to route around this issues. I also solved the problem in issue #44 where the truth eval expected a truth particle to always be in a truth jet, but this won't always be the case given eta acceptance and jet definitions.
Jin I'm assigning this to you. I think having a second runtime check would be helpful. I did see some reco jets being traced back to similar kinematic truth jets in the eval ntuple---that's an encouraging sign.
=> Eval modifications + new random numbers for PHPythia8

simulation/g4simulation/g4detectors/PHG4CylinderGeom_Spacalv3.cc
As the next round of production is coming, add two more rows of fibers to 2D Spacal towers (46->48) and bring the sampling fraction to be comparable value as the 1D Spacal. Otherwise, they differ by 5% relatively and complicates the comparisons. 
For 2D projective SPACAL, the new sampling fraction for 24GeV photon in the mid rapidity is ~ 2.36%. 
Just for the record, here the OLD sampling fraction before this commit:
=> Increase sampling fraction for 2D projective SPACAL

simulation/g4simulation/g4detectors/PHG4BlockCellReco.cc, simulation/g4simulation/g4detectors/PHG4CylinderCellReco.cc, simulation/g4simulation/g4detectors/PHG4SlatCellReco.cc
PHG4CylinderCell is capable of storing visible energy sum from PHG4Hit. However, this has not yet propagated to all Cell reco code. This pull request is intended to do so. 
BTW, also fix a bug in z-bin cell builder, that a zero-pathlength hit would induce a divide-zero error.
=> Enable saving visible energy in more cell builders

simulation/g4simulation/g4eval/CaloEvaluator.C, simulation/g4simulation/g4eval/CaloEvaluator.h, simulation/g4simulation/g4eval/CaloRawClusterEval.C, simulation/g4simulation/g4eval/CaloRawTowerEval.C, simulation/g4simulation/g4eval/CaloTruthEval.C, simulation/g4simulation/g4eval/CaloTruthEval.h, simulation/g4simulation/g4main/PHG4TruthInfoContainer.cc, simulation/g4simulation/g4main/PHG4TruthInfoContainer.h
This merge will bring in a couple of things. Most importantly it improves the correctness of the energy contribution calculations. I found these by embedding 40 GeV electrons in central events and watching that the evaluator was not getting confused by the additional trace possibilities.
It also mitigates the speed issues by improving the merging of sets. Full eval of the CEMC in a central event should run 10 minutes or so. For single particle traces within central events these commits resulted in a ~x10 improvement. I've added methods to reduce the forward tracing to particular embed flags and reverse tracing only above some energy threshold. This will buy us some time in many circumstances. 
I need to do more profiling to guide further optimization. One possibility is I might have to …
=> Calorimeter evaluator modifications

generators/PHPythia8/PHPythia8.C, generators/PHPythia8/PHPythia8.h
Info List print in Init() was called before event variables (x1,x2,QQ,etc) were filled. Pythia8 produces an error message that will confuse users, so I'm removing this print.
=> Remove error message from Pythia8

simulation/g4simulation/g4eval/CaloEvaluator.C, simulation/g4simulation/g4eval/CaloEvaluator.h, simulation/g4simulation/g4eval/CaloRawClusterEval.C, simulation/g4simulation/g4eval/CaloRawTowerEval.C, simulation/g4simulation/g4eval/CaloTruthEval.C, simulation/g4simulation/g4eval/CaloTruthEval.h
I've leaned a bit more on the caching for an additional minor speed improvement. I also provide an energy cutoff for the truth eval tracing. I suggest setting both truth and reco tracing to >2.0 GeV/c for the calorimeter macros. That should run at about half time of a full event.
Most of the time now is spent tracing the between g4hits and g4particles with lots of calls going to the truthinfocontainer. Short of storing the primary truth id on the g4hit id itself (which would explode memory) it is pretty tough to go faster than this now.
=> Additional CaloEvalStack Optimization

simulation/g4simulation/g4hough/PHG4TPCClusterizer.C
Clusters should store SvtxHit reco ids not cylinder cell truth ids. This was interfering with the evaluator tracing on the TPC configuration. There could be other problems, but I suspect this was the key barrier to getting the new eval working on the TPC.
=> TPC branch was storing truth cell ids on clusters not reco hit ids.

simulation/g4simulation/g4main/PHG4SimpleEventGenerator.cc, simulation/g4simulation/g4main/PHG4SimpleEventGenerator.h
Flat pT tossing has always been available. JL added an option for fixed momentum running, I'm expanding that to allow a range of momentum values.
=> Add option for flat momentum spectrum tossing on simple event generator

simulation/g4simulation/g4hough/SvtxVertex.h, simulation/g4simulation/g4hough/SvtxVertex_v1.C, simulation/g4simulation/g4hough/SvtxVertex_v1.h, simulation/g4simulation/g4vertex/GlobalVertex.h, simulation/g4simulation/g4vertex/GlobalVertex_v1.C, simulation/g4simulation/g4vertex/GlobalVertex_v1.h
Borrow the implementation for space efficient packed storage for the covariance as was done in g4hough.
=> Use packed storage for Global Vertex

simulation/g4simulation/g4eval/CaloTruthEval.C, simulation/g4simulation/g4eval/JetRecoEval.C, simulation/g4simulation/g4eval/JetTruthEval.C, simulation/g4simulation/g4eval/SvtxClusterEval.C, simulation/g4simulation/g4eval/SvtxTrackEval.C, simulation/g4simulation/g4eval/SvtxTruthEval.C
Remove some of the poor occupancy scaling calls from the other evals. Just in case these get worse under occupancy load some day. SVTX performance:
=> Copy Performance Mods from CaloEval to SvtxEval and JetEval

simulation/g4simulation/g4detectors/PHG4InnerHcalSubsystem.cc, simulation/g4simulation/g4detectors/PHG4InnerHcalSubsystem.h, simulation/g4simulation/g4detectors/PHG4OuterHcalSubsystem.cc, simulation/g4simulation/g4detectors/PHG4OuterHcalSubsystem.h, simulation/g4simulation/g4eval/CaloTruthEval.C, simulation/g4simulation/g4eval/PHG4DSTReader.cc, simulation/g4simulation/g4main/PHG4Reco.cc, simulation/g4simulation/g4main/PHG4Reco.h, simulation/g4simulation/g4main/PHG4SimpleEventGenerator.cc, simulation/g4simulation/g4main/PHG4TruthEventAction.cc, simulation/g4simulation/g4main/PHG4TruthEventAction.h, simulation/g4simulation/g4main/PHG4TruthInfoContainer.cc, simulation/g4simulation/g4main/PHG4TruthInfoContainer.h, simulation/g4simulation/g4main/PHG4TruthSubsystem.cc
It turns out some efforts are required to allow Geant4 events to get embedded to an existing DST stream. This procedure is used to reuse the Hijing production DST and embed more single particles into it via a new Geant4 cycle. 
Example Fun4All_sPHENIX.C macro to drive the embedding production is proposed to a fork of the macro repository:
https://github.com/blackcathj/macros/blob/SinglePart_master_embed_prod/macros/g4simulations/Fun4All_G4_sPHENIX.C
Major changes in coresoftware to allow G4->DST embedding are discussed in this pull request. It will be great if @pinkenburg and @mccumbermike can cross check these updates.  And the proposed changes are open for discussion.
The most significant change would be in initialization order for PHG4Reco. Previously both InitRun and Init part of the …
=> Allow Geant4 Embedding into existing DSTs (e.g. Hijing)

simulation/g4simulation/g4eval/CaloRawClusterEval.C, simulation/g4simulation/g4eval/CaloRawTowerEval.C, simulation/g4simulation/g4eval/CaloTruthEval.C, simulation/g4simulation/g4eval/JetTruthEval.C, simulation/g4simulation/g4eval/SvtxClusterEval.C, simulation/g4simulation/g4eval/SvtxEvaluator.C, simulation/g4simulation/g4eval/SvtxTruthEval.C, simulation/g4simulation/g4eval/SvtxVertexEval.C, simulation/g4simulation/g4main/PHG4TruthSubsystem.cc, simulation/g4simulation/g4main/PHG4TruthSubsystem.h
As advertised in pull request #65 , one remaining problem to kick off the embedding production is that the output DST file size is large, even after excluding the absorber G4Hits (~250MB/event). 
One solution to this problem is proposed in this pull request: an option (PHG4TruthSubsystem::SetSaveOnlyEmbeded() ) to drop off the truth G4 particle and vertex which is not associated with embedded particle. This option is by-default off, and can be activated via macro during the embedding production. This is driven by the analysis need for embedding production, for which hijing background are noise-like hits and the only embedded particle need to be traced via truth table. Meanwhile, the evaluator was updated in order to handle the missing truth info for the higjing particles. 
An example …
=> Option to remove non-embedded particle and vertex from the truth table

simulation/g4simulation/g4cemc/RawTowerGeomv1.cc, simulation/g4simulation/g4cemc/RawTowerGeomv2.cc
As titled, otherwise it can produce a phi bin number larger than number of bins. Also simplify the calculation by doing the round about in the phi bin space rather than angular space.
=> Fixing Phi Round About that phibin should be be above number of bins

simulation/g4simulation/g4detectors/PHG4CylinderSteppingAction.cc, simulation/g4simulation/g4detectors/PHG4InnerHcalParameters.cc, simulation/g4simulation/g4detectors/PHG4InnerHcalParameters.h, simulation/g4simulation/g4detectors/PHG4InnerHcalSteppingAction.cc, simulation/g4simulation/g4detectors/PHG4InnerHcalSteppingAction.h, simulation/g4simulation/g4detectors/PHG4InnerHcalSubsystem.cc, simulation/g4simulation/g4detectors/PHG4OuterHcalParameters.cc, simulation/g4simulation/g4detectors/PHG4OuterHcalParameters.h, simulation/g4simulation/g4detectors/PHG4OuterHcalSteppingAction.cc, simulation/g4simulation/g4detectors/PHG4OuterHcalSubsystem.cc
To save space by default absorber hits are not added to particles which are added to the truth table. Minor change: default is now 4 crossings for inner and -4 for outer hcal like what is in the preCDR. One does not need to set any options in the macro to get the correct default
=> add option to save hcal absorber hits in truth info

simulation/g4simulation/g4eval/CaloEvalStack.h, simulation/g4simulation/g4eval/CaloEvaluator.C, simulation/g4simulation/g4eval/CaloEvaluator.h, simulation/g4simulation/g4eval/CaloRawClusterEval.C, simulation/g4simulation/g4eval/CaloRawClusterEval.h, simulation/g4simulation/g4eval/CaloRawTowerEval.C, simulation/g4simulation/g4eval/CaloRawTowerEval.h, simulation/g4simulation/g4eval/CaloTruthEval.C, simulation/g4simulation/g4eval/CaloTruthEval.h, simulation/g4simulation/g4eval/JetEvalStack.h, simulation/g4simulation/g4eval/JetEvaluator.C, simulation/g4simulation/g4eval/JetEvaluator.h, simulation/g4simulation/g4eval/JetRecoEval.C, simulation/g4simulation/g4eval/JetRecoEval.h, simulation/g4simulation/g4eval/JetTruthEval.C, simulation/g4simulation/g4eval/JetTruthEval.h, simulation/g4simulation/g4eval/SvtxClusterEval.C, simulation/g4simulation/g4eval/SvtxClusterEval.h, simulation/g4simulation/g4eval/SvtxEvalStack.h, simulation/g4simulation/g4eval/SvtxEvaluator.C, simulation/g4simulation/g4eval/SvtxEvaluator.h, simulation/g4simulation/g4eval/SvtxHitEval.C, simulation/g4simulation/g4eval/SvtxHitEval.h, simulation/g4simulation/g4eval/SvtxTrackEval.C, simulation/g4simulation/g4eval/SvtxTrackEval.h, simulation/g4simulation/g4eval/SvtxTruthEval.C, simulation/g4simulation/g4eval/SvtxTruthEval.h, simulation/g4simulation/g4eval/SvtxVertexEval.C, simulation/g4simulation/g4eval/SvtxVertexEval.h
@blackcathj Here is the option for adding defensive depth to the evaluation. Can you try this on the gutted embedding macro? You will need to call eval->set_strict(false) in the detector macros. It adds lookup protection pretty much everywhere and specifically in the spots you were modifying previously, but it is possible I let something slip through.
=> Evaluator set_strict(true/false) option

simulation/g4simulation/g4main/PHG4ParticleGenerator.cc, simulation/g4simulation/g4main/PHG4ParticleGeneratorBase.cc, simulation/g4simulation/g4main/PHG4ParticleGeneratorBase.h, simulation/g4simulation/g4main/PHG4ParticleGeneratorD0.cc, simulation/g4simulation/g4main/PHG4ParticleGeneratorVectorMeson.cc, simulation/g4simulation/g4main/PHG4ParticleGun.cc, simulation/g4simulation/g4main/PHG4SimpleEventGenerator.cc, simulation/g4simulation/g4main/PHG4SimpleEventGenerator.h
I moved that code from the simple event generator into the PHG4ParticleGeneratorBase class and added a call to it to the other single particle generators. It works as before - please in the future put common functionality like this into the base class. Less work for everyone else
=> move use of existing vertex into generator base class

simulation/g4simulation/g4eval/BaseTruthEval.C, simulation/g4simulation/g4eval/BaseTruthEval.h, simulation/g4simulation/g4eval/BaseTruthEvalLinkDef.C, simulation/g4simulation/g4eval/CaloRawClusterEval.C, simulation/g4simulation/g4eval/CaloRawTowerEval.C, simulation/g4simulation/g4eval/CaloTruthEval.C, simulation/g4simulation/g4eval/CaloTruthEval.h, simulation/g4simulation/g4eval/JetTruthEval.C, simulation/g4simulation/g4eval/Makefile.am, simulation/g4simulation/g4eval/SvtxClusterEval.C, simulation/g4simulation/g4eval/SvtxHitEval.C, simulation/g4simulation/g4eval/SvtxTrackEval.C, simulation/g4simulation/g4eval/SvtxTruthEval.C, simulation/g4simulation/g4eval/SvtxTruthEval.h, simulation/g4simulation/g4eval/SvtxVertexEval.C
Okay @blackcathj , I believe I've done it now. I wrote a new class BaseTruthEval to handle common tasks between the SvtxTruthEval and CaloTruthEval. This reduces the duplication of code between the two modules and ensures those portions are always doing the same things. Inside that new class, I have changed the truth id matching criteria to this: 
```
if ((p1->get_primary_id() == -1) &&
(p2->get_primary_id() == -1)) {
// both particles are from the primary truth map, use track ids
if (p1->get_track_id() == p2->get_track_id()) {
are_same_particle = true;
}
} else if ((p1->get_primary_id() != -1) &&
(p2->get_primary_id() != -1)) {
// both particles are from the total truth map, use track ids
if (p1->get_track_id() == p2->get_track_id()) {
are_same_particle = true;
}
} else if …
```
=> New truth matching conditions to handle truth table copies during embedding

simulation/g4simulation/g4detectors/PHG4BlockCellGeomContainer.cc, simulation/g4simulation/g4detectors/PHG4BlockGeomContainer.cc, simulation/g4simulation/g4detectors/PHG4CylinderCellContainer.cc, simulation/g4simulation/g4detectors/PHG4CylinderCellContainer.h, simulation/g4simulation/g4detectors/PHG4CylinderCellGeomContainer.cc, simulation/g4simulation/g4detectors/PHG4CylinderCellReco.cc, simulation/g4simulation/g4detectors/PHG4CylinderCellTPCReco.cc, simulation/g4simulation/g4detectors/PHG4FCalDetector.cc, simulation/g4simulation/g4detectors/PHG4FPbScDetector.cc, simulation/g4simulation/g4detectors/PHG4InnerHcalParameters.cc, simulation/g4simulation/g4detectors/PHG4InnerHcalParameters.h, simulation/g4simulation/g4detectors/PHG4InnerHcalSteppingAction.cc, simulation/g4simulation/g4detectors/PHG4InnerHcalSteppingAction.h, simulation/g4simulation/g4detectors/PHG4InnerHcalSubsystem.cc, simulation/g4simulation/g4detectors/PHG4InnerHcalSubsystem.h, simulation/g4simulation/g4detectors/PHG4OuterHcalSteppingAction.cc, simulation/g4simulation/g4detectors/PHG4OuterHcalSteppingAction.h, simulation/g4simulation/g4detectors/PHG4SectorConstructor.cc, simulation/g4simulation/g4detectors/PHG4SectorConstructor.h, simulation/g4simulation/g4detectors/PHG4SectorDetector.cc
The light correction was only implemented for the outer hcal. This pull request adds it to the inner hcal. While at it I ran cppcheck and fixed all those performance warnings. We should make running cppcheck mandatory before code is being checked in.
=> add light correction to inner hcal stepping action, remove track pathlength from hcal hits, fix cppcheck performance warnings

simulation/g4simulation/g4eval/Makefile.am, simulation/g4simulation/g4eval/MomentumEvaluator.C, simulation/g4simulation/g4eval/MomentumEvaluator.h, simulation/g4simulation/g4eval/MomentumEvaluatorLinkDef.h
The TPC tracking is in need of a different evaluator for 2 reasons :
1) comparison of reconstructed tracks and true tracks should be done in momentum-space instead of by comparing clusters
2) the current svtx evaluator is prohibitively slow for the TPC in hijing
This evaluator is an entirely independent class from the rest of the g4eval directory, and won't impact any other code.  It could also be used with the Svtx if desired : it ignores clusters but runs in far under a second per event in central hijing.
=> adding an evaluator based only on 3-momentum

simulation/g4simulation/g4eval/CaloTruthEval.C
When I rewrote the CaloTruthEval object to account for the id mismatches in the truth tables, I inserted are_same_particle(p1,p2) in many places. In this particular spot I reverse the logic by accident by not typing a '!'. Apologies for not seeing this sooner.
=> CaloTruthEval::get_shower_from_primary() logic was backward

simulation/g4simulation/g4detectors/PHG4BlockCellReco.cc, simulation/g4simulation/g4detectors/PHG4BlockCellReco.h, simulation/g4simulation/g4detectors/PHG4CylinderCellReco.cc, simulation/g4simulation/g4detectors/PHG4CylinderCellReco.h, simulation/g4simulation/g4detectors/PHG4FullProjSpacalCellReco.cc, simulation/g4simulation/g4detectors/PHG4FullProjSpacalCellReco.h, simulation/g4simulation/g4detectors/PHG4HcalCellReco.cc, simulation/g4simulation/g4detectors/PHG4HcalCellReco.h, simulation/g4simulation/g4detectors/PHG4SlatCellReco.cc, simulation/g4simulation/g4detectors/PHG4SlatCellReco.h
As an action item from the last simulation meeting, this pull request introduces a timing cut in the cell reco to the mimic the effective ADC integration window for sPHENIX calorimeters.  
The idea is to apply this cut after PHG4Hit stage, since the timing span for each hit is small and it would allow us to tune the timing window post Geant production of hits. Also only a simple max-timing cut was applied, since at length scale of 100ns the start time variation is effectively negligible. The cut value can be changed via macro inputs. However, in near future, we plan to read it via the parameter node, after Chris finish building the parameter database infrastructure.
The default timing window is 0 to infinity, i.e. consistent with no timing cut as used in previous analysis. The timing cut …
=> Support timing cut in Cell reco

simulation/g4simulation/g4eval/SvtxClusterEval.C, simulation/g4simulation/g4eval/SvtxHitEval.C
Before the track evaluator was looping over all clusters and checking the g4hits for a match based on input id, now it bails immediately if the cluster is from the wrong layer which greatly limits the downward search. Look for the change to SvtxClusterEval::all_clusters_from(g4hit) function in the before/after for 4-7 fm impact parameter (for finite callgrind testing) below. The eval is below G4 in these events and comparable to the track finding CPU.
Before:
After:
=> Additional Evaluator Optimization

simulation/g4simulation/g4hough/PHG4SvtxThresholds.C, simulation/g4simulation/g4hough/PHG4SvtxThresholds.h
The old threshold module used a single value for all layers which will clobber the TPC since it is inside the same cylinder cell container. So I changed the default to 0.0 and require individual setting of each layer threshold. I've updated the SVTX macros and will generate a separate pull request on that side. The old interface will work with a warning message to update the macros from GitHub.
I'm pretty sure this is the last change needed to make the behavior of the silicon the same in the silicon+tpc and silicon-only macros.
=> New SVTX tracking layer energy threshold defaults

simulation/g4simulation/g4eval/BaseTruthEval.C, simulation/g4simulation/g4eval/BaseTruthEval.h, simulation/g4simulation/g4eval/CaloRawClusterEval.C, simulation/g4simulation/g4eval/CaloRawClusterEval.h, simulation/g4simulation/g4eval/CaloRawTowerEval.C, simulation/g4simulation/g4eval/CaloRawTowerEval.h, simulation/g4simulation/g4eval/CaloTruthEval.C, simulation/g4simulation/g4eval/CaloTruthEval.h, simulation/g4simulation/g4eval/SvtxClusterEval.C, simulation/g4simulation/g4eval/SvtxClusterEval.h, simulation/g4simulation/g4eval/SvtxHitEval.C, simulation/g4simulation/g4eval/SvtxHitEval.h, simulation/g4simulation/g4eval/SvtxTrackEval.C, simulation/g4simulation/g4eval/SvtxTrackEval.h, simulation/g4simulation/g4eval/SvtxTruthEval.C, simulation/g4simulation/g4eval/SvtxTruthEval.h, simulation/g4simulation/g4eval/SvtxVertexEval.C, simulation/g4simulation/g4eval/SvtxVertexEval.h
The evaluator hierarchy has the jet truth evaluation owning evaluator stacks for each detector subsystem. Previously when a subsystem was missing the detector evaluator stack would notice the missing node and throw an error. However, with the jet evaluator we'd like it to not care if say, the forward calorimeters were not run and those nodes are not missing, so long as we never ask for information from those nodes.
So I've moved the crash stop error into the public methods so that the missing nodes are only queried on usage and not at setup. I've also changed this check from a crash stop error into the standard error handling of the evaluation that does best it can during processing and reports errors at the end.
This should allow @johnlajoie to keep making good progress on forward jets …
=> Modify Evaluator Error Handling for Missing Nodes

generators/flowAfterburner/Makefile.am, generators/sHijing/Makefile.am, offline/framework/fun4all/Fun4AllEventOutStream.h, offline/packages/HelixHough/helix_hough/HelixHough.h, offline/packages/HelixHough/helix_hough/sPHENIX/sPHENIXTracker.h, simulation/g4simulation/g4cemc/BEmcCluster.cc, simulation/g4simulation/g4cemc/PHMakeGroups.h, simulation/g4simulation/g4cemc/RawClusterBuilderv1.cc, simulation/g4simulation/g4detectors/PHG4CEmcTestBeamSteppingAction.cc, simulation/g4simulation/g4detectors/PHG4CrystalCalorimeterSteppingAction.cc, simulation/g4simulation/g4detectors/PHG4CylinderCellTPCReco.cc, simulation/g4simulation/g4detectors/PHG4CylinderGeom_Spacalv3.h, simulation/g4simulation/g4detectors/PHG4EnvelopeSteppingAction.cc, simulation/g4simulation/g4detectors/PHG4ForwardEcalSteppingAction.cc, simulation/g4simulation/g4detectors/PHG4ForwardHcalSteppingAction.cc, simulation/g4simulation/g4detectors/PHG4HcalPrototypeSteppingAction.cc, simulation/g4simulation/g4detectors/PHG4InnerHcalSteppingAction.cc, simulation/g4simulation/g4detectors/PHG4OuterHcalDetector.cc, simulation/g4simulation/g4detectors/PHG4OuterHcalSteppingAction.cc, simulation/g4simulation/g4detectors/PHG4ProjCrystalCalorimeterDetector.cc, simulation/g4simulation/g4detectors/PHG4SiliconTrackerSteppingAction.cc, simulation/g4simulation/g4eval/CaloEvaluator.C, simulation/g4simulation/g4eval/CaloEvaluator.h, simulation/g4simulation/g4eval/CaloRawClusterEval.C, simulation/g4simulation/g4eval/JetEvaluator.C, simulation/g4simulation/g4eval/MomentumEvaluator.C, simulation/g4simulation/g4eval/SvtxEvaluator.C, simulation/g4simulation/g4hough/SvtxTrack.h, simulation/g4simulation/g4main/PHG4InEvent.cc
We need to upgrade our compiler ASAP since G4 does not compile anymore with the our installed  4.4.7. We have gcc 4.8.2 as alternative under /opt/gcc, it is set up in a way that the binaries also work on a normal SL6 box. No major changes but the new compiler traces unused variables more aggressively. It also does not accept NULL as numerical int/float value (that shouldn't have been used like this in the first place) and pushing unsigned ints into a float. The changes should be backward compatible, the code should still compile under gcc 4.4.7
=> port to gcc 4.8.2

offline/QA/macros/QA_Draw_CEMC_G4Hit.C, offline/QA/macros/QA_Draw_CEMC_TowerCluster.C, offline/QA/macros/QA_Draw_HCALIN_G4Hit.C, offline/QA/macros/QA_Draw_HCALIN_TowerCluster.C, offline/QA/macros/QA_Draw_HCALOUT_G4Hit.C, offline/QA/macros/QA_Draw_HCALOUT_TowerCluster.C, offline/QA/macros/SaveCanvas.C, offline/QA/macros/SetOKStyle.C, offline/QA/modules/Makefile.am, offline/QA/modules/QAG4SimulationCalorimeter.C, offline/QA/modules/QAG4SimulationCalorimeter.h, offline/QA/modules/QAG4SimulationCalorimeterLinkDef.h, offline/QA/modules/QAHistManagerDef.C, offline/QA/modules/QAHistManagerDef.h, offline/QA/modules/QAHistManagerDefLinkDef.h, offline/QA/modules/autogen.sh, offline/QA/modules/configure.in, simulation/g4simulation/g4detectors/PHG4BlockCellReco.cc, simulation/g4simulation/g4detectors/PHG4ForwardCalCellReco.cc, simulation/g4simulation/g4detectors/PHG4FullProjSpacalCellReco.cc, simulation/g4simulation/g4detectors/PHG4HcalCellReco.cc, simulation/g4simulation/g4detectors/PHG4SlatCellReco.cc
Implemented first of three planned QA modules. More to be discussed in simulation meeting today. 
Example macros to run: 
https://github.com/blackcathj/macros/tree/SinglePart_master_readhit_calo_eval/macros/g4simulations
Few screen shots, which compare 24GeV pi- shower VS 24GeV e- shower:
* At geant4 production level:
* At post-production reconstruction level:
=> Standardized Calorimetry QA - part 1/3

simulation/g4simulation/g4main/HepMCNodeReader.cc, simulation/g4simulation/g4main/HepMCNodeReader.h
Previously only a Gaussian smearing could be applied. I overloaded negative values of smearing into access to a uniform distribution. This is a simple one, but Chris should approve that I have selected the appropriate GSL implementations.
=> Uniform HepMC Vertex Smearing

offline/framework/fun4all/Fun4AllBase.cc, offline/framework/fun4all/Fun4AllBase.h, offline/framework/fun4all/Fun4AllServer.cc, simulation/g4simulation/g4eval/PHG4DSTReader.cc
Two light touches on the framework code, which should not change be default behavior: 
1. Introduce an enum name for each level of verbosity for ```Fun4AllBase::verbosity``` (without breaking compatibility of using it as integer). 
Therefore, instead of writing 
```c++
if (verbosity > 1) cout <"some debug message"; 
```
one can choose to write as 
```
if (verbosity >= VERBOSITY_SOME) cout <"some debug message"; 
```
Similar user can choose verbosity levels in macro with enum tags instead of number now. More in ```Fun4AllBase::enu_Verbosity```, which will be compiled to searchable documentation in doxygen once merged.
2. Sort out levels of verbosity messages in ```Fun4AllServer```. Default is still quiet mode (suitable for batch condor jobs), although I advertise for verbosity level …
=> Verbosity tune for fun4all server

online_distribution/newbasic/configure.in
at long last, I was able to nail down the difference between a standard and the nightly rebuild. It activates a switch that effectively adds -fkeep-inline-functions to the link flags. Google finds a reference to thsi as the culprit that results in a failure to instantiate a number of STL and boost classes. We'll see what this gives.
=> mlp -- based on some googling, remove -fkeep-inline to see if this

simulation/g4simulation/g4detectors/Makefile.am, simulation/g4simulation/g4detectors/PHG4EICForwardEcalDetector.cc, simulation/g4simulation/g4detectors/PHG4EICForwardEcalDetector.h, simulation/g4simulation/g4detectors/PHG4ForwardEcalDetector.cc, simulation/g4simulation/g4detectors/PHG4ForwardEcalDetector.h, simulation/g4simulation/g4detectors/PHG4ForwardEcalSubsystem.cc, simulation/g4simulation/g4detectors/PHG4ForwardEcalSubsystem.h
This commit implements the fsPHENIX dual EMCal, comprised of re-used elements of the PHENIX PbGl and MPC. This can be easily switched between the EIC EMCal and the fsPHENIX EMCal at the macro level; PHG4ForwardEcalSubsystem can use different detector classes (derived from a base class), selectable at the macro level.  This allow fsPHENIX to move forward with the new implementation without breaking compatibility with the EIC detector simulations.  
Some pretty plots - the EIC EMCal (Pb/Sc sandwich): 
and the brand new fsPHENIX dual EMCal:
=> Implementation of fsPHENIX Dual EMCal (reuse PbGL and MPC)

simulation/g4simulation/g4detectors/PHG4Prototype2InnerHcalDetector.cc, simulation/g4simulation/g4detectors/PHG4Prototype2InnerHcalDetector.h, simulation/g4simulation/g4detectors/PHG4Prototype2OuterHcalDetector.cc, simulation/g4simulation/g4detectors/PHG4Prototype2OuterHcalDetector.h
Small bugfix. The plots how well the bottom/top coordinates (green triangles) from the drawing match are here, only the bottom coordinates are being used in the construction of the hcals:
=> fix distance between scinti slats in inner hcal, use parameter for scintillator front face length

simulation/g4simulation/g4detectors/Makefile.am, simulation/g4simulation/g4detectors/PHG4Prototype2CryostatDetector.cc, simulation/g4simulation/g4detectors/PHG4Prototype2CryostatDetector.h, simulation/g4simulation/g4detectors/PHG4Prototype2CryostatSteppingAction.cc, simulation/g4simulation/g4detectors/PHG4Prototype2CryostatSteppingAction.h, simulation/g4simulation/g4detectors/PHG4Prototype2CryostatSubsystem.cc, simulation/g4simulation/g4detectors/PHG4Prototype2CryostatSubsystem.h, simulation/g4simulation/g4detectors/PHG4Prototype2CryostatSubsystemLinkDef.h
A quick implementation of the cryostat mockup of the prototype. It uses extruded volumes right from the corner points from the engineering drawings. The plot shows a geantino scan with the coordinates from the drawings overlaid. The hits visible in the rigth two volumes are from geantinos leaving the sides of the cryostat.
=> Prototype cryostat added

online_distribution/newbasic/rcdaqEventiterator.cc, online_distribution/newbasic/rcdaqEventiterator.h
If the env. variable $RCDAQHOST - the same you define to interact with a remote rcdaq_server - is defined, it will default to that host. The assumption is that if you want to control that remote server, you will also want to get your monitoring data from there.
If that is not defined, you get "localhost" as the default.
=> mlp -- changed behavior of the "empty" rcdaqEveniterator constructor

online_distribution/newbasic/ddump.cc, online_distribution/newbasic/dlist.cc
Some changes to make dlist and ddump honor a $RCDAQHOST env. variable definitions if one just says "dlist -r". The idea is that in that case it defaults to "localhost" in the absence of variable, or its value else.
The RCDAQHOST env. variable is set if one controls a remote rcdaq_server, and it is a reasonable assumption that one will also get monitoring data from there.
=> Some changes to make dlist and ddump honor a $RCDAQHOST env. variable

simulation/g4simulation/g4jets/TruthJetInput.C, simulation/g4simulation/g4jets/TruthJetInput.h
This modification adds support for restricting truth jet reconstruction to only run over particles with an embedded id given by user. This is needed for studies of jet performance after embedding into HIJING. We tested this code at the sPHENIX MAPS workfest: it correctly recovers the "PYTHIA only" truth jet kinematics for PYTHIA events embedded into HIJING events. 
For example, if the embedded event is being read in with a HepMCNodeReader and assigned a given embedded ID:
```c++
HepMCNodeReader *hr = new HepMCNodeReader();
hr->Embed( 17 );
se->registerSubsystem(hr);
```
Truth jet reconstruction can be specified to run only over particles with that embedded ID:
```c++
TruthJetInput *tji = new TruthJetInput(Jet::PARTICLE);
tji->add_embedding_flag( 17 );
JetReco *truthjetreco = new …
```
=> add option to run truth jet reco only over embedded particles

online_distribution/newbasic/packet_hbd_fpga.cc, online_distribution/newbasic/packet_hbd_fpgashort.cc
The HBD packet is the only one that needs some external information to decode properly, as the number of samples it was configured for is not part of the packet payload - a stupid oversight. 
The default for the HBD was 12, while in sPHENIX, where the old HBD electronics is used extensively, we virtually always write 24 samples. This is not an optimal situation, as our packets are normally required to be autonomously decodable. But in the sPHENIX context, this is better than each user having to manually set the number of samples, and always get it right.
=> mlp -- changed the default for the number of samples in teh HBD packets from 12 to 24.

simulation/g4simulation/g4main/HepMCNodeReader.cc
I realize now that most people would expect this to be a half width function not full width. Adding a factor two to switch to the half width definition.
=> Change Flat Smearing from Full Width to Half Width in HepMCNodeReader

simulation/g4simulation/g4hough/PHG4HoughTransform.C
As previously promised this pull request will fix a problem wherein the DCA on the track was computed against the null beam location (0,0) and not the reconstructed vertex. I've also encountered an issue where the vertex guessing is failing ~20% for smeared truth vertexes---I have a plan for correcting that issue in a future follow-up pull request.
=> Incorporate Reconstructed Vertex into Tracking DCA Calculation

simulation/g4simulation/g4cemc/Prototype2RawTowerBuilder.cc, simulation/g4simulation/g4detectors/PHG4Prototype2HcalCellReco.cc, simulation/g4simulation/g4detectors/PHG4Prototype2InnerHcalSteppingAction.cc, simulation/g4simulation/g4detectors/PHG4Prototype2OuterHcalSteppingAction.cc, simulation/g4simulation/g4main/PHG4Hit.cc, simulation/g4simulation/g4main/PHG4Hit.h, simulation/g4simulation/g4main/PHG4Hitv1.h
The columns are now mapped more intuitively onto eta bins, the rows onto phi bins. Add new property prop_row so we don't have to hijack the layers anymore which really have a different meaning
=> Sort out row/column business for prototype

simulation/g4simulation/g4cemc/Prototype2RawTowerBuilder.cc, simulation/g4simulation/g4cemc/RawTowerBuilder.cc, simulation/g4simulation/g4cemc/RawTowerDigitizer.cc, simulation/g4simulation/g4cemc/RawTowerGeomContainer.h, simulation/g4simulation/g4detectors/PHG4CEmcTestBeamSteppingAction.cc, simulation/g4simulation/g4detectors/PHG4ForwardEcalSteppingAction.cc, simulation/g4simulation/g4detectors/PHG4HcalPrototypeSteppingAction.cc, simulation/g4simulation/g4detectors/PHG4OuterHcalDetector.cc, simulation/g4simulation/g4detectors/PHG4Prototype2OuterHcalSteppingAction.cc, simulation/g4simulation/g4eval/SvtxEvaluator.C, simulation/g4simulation/g4hough/PHG4TPCClusterizer.C
Using the empty geometry object (which basically only contains the number of towers) the output of the prototype tower builder can now be fed into the digitizer. Coverity found issues in many stepping actions where the new shower objects wasn't filled properly for absorber hits (cut and paste error). Fixed some other benign warnings (like possible use of negative indices) which probably never happened.
=> Add preliminary geometry object to prototype towers for digitizer, fix coverity problems

online_distribution/newbasic/CpacketV1.h
We rarely saw this because the DCMs tend to give 32bit-based data, which works ok.
The padding is in units of the packet data size. So if that size is 1
(byte-based), and we store just one character, the padding will
be 7 so that we fill up to the next 64bit boundary. (Note that the
ONCS format is 128bit-aligned). Similarly, if the data size is 2, and we store
one value, we get a padding value of 3.
The routine here simply subtracted paddingsize 32bit-values, which was wrong.
=> mlp - the padding in prdf was never properly implemented. 

offline/packages/Prototype2/Makefile.am, offline/packages/Prototype2/RawTower_Temperature.cc, offline/packages/Prototype2/RawTower_Temperature.h, offline/packages/Prototype2/RawTower_TemperatureLinkDef.h
This is a class to store the temperature readings for the SiPMs on a tower by tower basis. This allows to structure the container in the same coordinate space as the real SiPM signals, and get the right temperature.
Since we are reading the temperature only every minute or so, we interpolate between readings for event times in between two measurements linearly in time.
One can also ask for the reading from a given entry if one wants to make more sophisticated interpolations.
=> mlp - added the class to maintain the temperatures for a given module.

simulation/g4simulation/g4cemc/Makefile.am, simulation/g4simulation/g4cemc/RawTowerCalibration.cc, simulation/g4simulation/g4cemc/RawTowerCombiner.cc, simulation/g4simulation/g4cemc/RawTowerCombiner.h, simulation/g4simulation/g4cemc/RawTowerCombinerLinkDef.h, simulation/g4simulation/g4cemc/RawTowerDigitizer.cc, simulation/g4simulation/g4cemc/RawTowerGeomContainer.h, simulation/g4simulation/g4cemc/RawTowerGeomContainer_Cylinderv1.cc, simulation/g4simulation/g4cemc/RawTowerGeomContainer_Cylinderv1.h, simulation/g4simulation/g4cemc/RawTowerGeomContainerv1.cc, simulation/g4simulation/g4cemc/RawTowerGeomContainerv1.h
Adding a new tower analysis module to enable analysis of sPHENIX simulation to use multi-tower ganging of EMCal readout. For example 2x2-ganging as proposed for some CEMC de-scoping options. 
Technically, a new module ```RawTowerCombiner``` is introduced to combine MxN towers into one readout channel on an eta-phi tower grid exiting on the DST tree. Therefore, it needs to be called after ```RawTowerBuilder``` and before ```RawTowerDigitizer```. During the merging, truth structure (Cells and showers) is maintained. In the default mode, both RawTower and RawTowerGeometry are edited on the DST tree, rather than introducing a new node for combined towers. I found this is least intrusive to our analysis code base. 
If one need to use this module for ALD charge (e.g. photon position resolution, …
=> Module to support ganging EMCal readout

simulation/g4simulation/g4jets/TowerJetInput.C, simulation/g4simulation/g4vertex/GlobalVertexReco.C
In the past few days the jet finding with calorimeter always crashes within FastJet (for both v3.1 and v3.2).  @pinkenburg , @dvperepelitsa and I traced down the problem to NAN momentum vector passed to FastJet, which stems from an NAN vertex z in the global vertex map. 
Therefore, as a temp fix, all vertex with NAN in z is rejected from filling into the global vertex map. Mike might have a permanent fix later by further trace to its source within the SVX vertex finder or upper stream. 
Checking reconstructing 250 events of 25GeV p+p jets. Blue curves is FastJet 3.2 + this fix. Green reference is FastJet 3.1 as produced on Feb 17.
Calorimeter Tower R=0.7 jet spectrum, which has been stable:
Calorimeter Tower R=0.7 jet truth matching, shows the reconstructed efficiency is slightly lower in …
=> Fast jet crash fix by avoiding NAN vertex propagation to global vertex

offline/packages/Prototype2/RawTower_Temperature.h
When you want to use it in a non-production environment, it fails since
we are not installing this header.
This will not affect the existing DSTs. After the next rebuild all will be fine.
=> mlp -- removed the "PROTOTYPE2_FEM.h" include from the header. 

simulation/g4simulation/g4detectors/Makefile.am, simulation/g4simulation/g4detectors/PHG4CylinderCellTPCReco.cc, simulation/g4simulation/g4detectors/PHG4CylinderCellTPCReco.h, simulation/g4simulation/g4detectors/PHG4TPCDistortion.cc, simulation/g4simulation/g4detectors/PHG4TPCDistortion.h, simulation/g4simulation/g4detectors/PHG4TPCDistortionLinkDef.h, simulation/g4simulation/g4detectors/PHG4TPCSpaceChargeDistortion.cc, simulation/g4simulation/g4detectors/PHG4TPCSpaceChargeDistortion.h, simulation/g4simulation/g4detectors/PHG4TPCSpaceChargeDistortionLinkDef.h
Tom and Carlos modeled the residual TPC space charge distortion based on the space charge simulation and estimation on the correction residual. This residual distortion is introduced to TPC simulation. 
A distortion virtual interface class was introduced to apply any distortion to a primary ionization: ```PHG4TPCDistortion```. Later it can be used to apply various full distortion to the primary ionization. But in this pull request, we only apply the residual space charge distortion via prametrization of ```PHG4TPCSpaceChargeDistortion``` (a variation of Tom's code).
The distortion is applied which primary charge drift to the pad in ```PHG4CylinderCellTPCReco```.  At this moment, only r*phi distortion is applied, which is the sensitive direction to a most radial track. Proper application …
=> Apply residual space charge distortion in TPC

simulation/g4simulation/g4eval/SvtxEvaluator.C, simulation/g4simulation/g4eval/SvtxTrackEval.C, simulation/g4simulation/g4eval/SvtxTrackEval.h
I'm adding an entry to the track and gtrack ntuple to record which of the first 30 layers had clusters from the max truth contributor. This will help examine the matching correctness between the MAPS inner tracking and the TPC outer tracking.
=> Add Truth Layer Record to Eval

simulation/g4simulation/g4bbc/BbcVertexFastSimReco.C, simulation/g4simulation/g4bbc/BbcVertex_v1.C, simulation/g4simulation/g4bbc/BbcVertex_v1.h, simulation/g4simulation/g4eval/SvtxEvaluator.C, simulation/g4simulation/g4hough/PHG4HoughTransform.C, simulation/g4simulation/g4hough/SvtxVertex.h, simulation/g4simulation/g4hough/SvtxVertex_v1.h, simulation/g4simulation/g4vertex/GlobalVertex.h, simulation/g4simulation/g4vertex/GlobalVertexMap_v1.C, simulation/g4simulation/g4vertex/GlobalVertexReco.C, simulation/g4simulation/g4vertex/GlobalVertex_v1.C, simulation/g4simulation/g4vertex/GlobalVertex_v1.h
Some clean up on the vertexing side. Removed empty vertex bug, also hardened against null inputs. Before/After:
Probably won't solve #155.
=> Vertex Cleanup

simulation/g4simulation/g4detectors/PHG4BlockCellReco.cc, simulation/g4simulation/g4detectors/PHG4BlockCellReco.h, simulation/g4simulation/g4detectors/PHG4CylinderCellReco.cc, simulation/g4simulation/g4detectors/PHG4CylinderCellReco.h, simulation/g4simulation/g4detectors/PHG4CylinderCellTPCReco.cc, simulation/g4simulation/g4detectors/PHG4CylinderCellTPCReco.h, simulation/g4simulation/g4detectors/PHG4ForwardCalCellReco.cc, simulation/g4simulation/g4detectors/PHG4ForwardCalCellReco.h, simulation/g4simulation/g4detectors/PHG4FullProjSpacalCellReco.cc, simulation/g4simulation/g4detectors/PHG4FullProjSpacalCellReco.h, simulation/g4simulation/g4detectors/PHG4HcalCellReco.cc, simulation/g4simulation/g4detectors/PHG4HcalCellReco.h, simulation/g4simulation/g4detectors/PHG4Prototype2HcalCellReco.cc, simulation/g4simulation/g4detectors/PHG4Prototype2HcalCellReco.h, simulation/g4simulation/g4detectors/PHG4SiliconTrackerCellReco.cc, simulation/g4simulation/g4detectors/PHG4SiliconTrackerCellReco.h, simulation/g4simulation/g4detectors/PHG4SlatCellReco.cc, simulation/g4simulation/g4detectors/PHG4SlatCellReco.h, simulation/g4simulation/g4eval/SvtxEvaluator.C, simulation/g4simulation/g4main/HepMCNodeReader.cc, simulation/g4simulation/g4main/HepMCNodeReader.h, simulation/g4simulation/g4main/PHG4PrimaryGeneratorAction.cc, simulation/g4simulation/g4main/PHG4SimpleEventGenerator.cc, simulation/g4simulation/g4main/PHG4SimpleEventGenerator.h
I'd like to merge some initial changes for treating pileup in G4. I've added a new function to the event generators to place additional events backward in time, lower time limits on the cell reco to add a sense of the integration times (defaults unchanged), a patch for a unit convention bug (sec vs nanosec), and some additional evaluator lines for the g4hit and g4point time to see that everything is exercising correctly. 
EDIT: Here is a look at some g4hit pileup from the new branch.
=> Some Initial Pileup Capabilities

generators/PHPythia6/Makefile.am, generators/PHPythia6/PHPy6ForwardElectronTrig.C, generators/PHPythia6/PHPy6ForwardElectronTrig.h, generators/PHPythia6/PHPy6GenTrigger.C, generators/PHPythia6/PHPy6GenTrigger.h, generators/PHPythia6/PHPythia6.C, generators/PHPythia6/PHPythia6.h, generators/PHPythia6/PHPythia6LinkDef.h
This branch updates the PHPythia6 package by @nfeege with the following:
-> Added the ability to handle "mdme" settings in the config file (set particle decays)
-> Added triggers and the ability to handle a list of triggers in the event generation
-> Fixed passing the process ID to HepMC event record
All these are needed for the planned fsPHENIX DY simulations. This is an initial package to allow @nfeege and others to have a look and comment. 
As a check, setting the MDME flags in the config file as: 
mdme	174 1 0
mdme	175 1 0
mdme	176 1 0
mdme	177 1 0
mdme	178 1 0
mdme	179 1 0
mdme	180 1 0
mdme	181 1 0
mdme	182 1 1
mdme	183 1 0
mdme	184 1 0
mdme	185 1 0
mdme	186 1 0
mdme	187 1 0
mdme	188 1 0
mdme	189 1 0
results in the following output from a pylist(12):
23     23    Z0 …
=> Ph pythia6 update

offline/packages/HelixHough/helix_hough/sPHENIX/sPHENIXTrackerTPC_findTracksBySegments.cpp, simulation/g4simulation/g4hough/PHG4SvtxClusterizer.C, simulation/g4simulation/g4hough/PHG4SvtxClusterizer.h, simulation/g4simulation/g4hough/PHG4TPCClusterizer.C, simulation/g4simulation/g4hough/PHG4TPCClusterizer.h
The TPC was using fixed size arrays to cluster both the MAPS and the TPC layers. In the MAPS layers, due to the fine pitch pixels, this is a particularly wasteful approach. So I've rewritten both the MAPS and the TPC clusterizer to work over just those subsystems individually. The peak memory footprint is now 1.2 GB smaller and things will run on the normal condor queue for the TPC simulations.
I will need to push changes to the MAPS+TPC macro as well with this merge.
Here is the full MAPS performance cross check:
And here is the MAPS+TPC performance cross check:
Some small changes in this one since the MAPS clusters are now made differently.
=> TPC Memory Reduction

simulation/g4simulation/g4hough/SvtxCluster_v1.C
Veronica found a cut and paste bug in the get_error() method on the SvtxCluster object. I fix the bug and check the resulting tracking performance delta for a MAPS tracker:
and for the MAPS+TPC tracker:
This will get us started on simplifying the cluster error handling. I'll go ahead and merge this right away since it is tested.
=> Patch for Cut and Paste Bug in Cluster v1

simulation/g4simulation/g4detectors/PHG4CylinderGeom_Spacalv3.cc, simulation/g4simulation/g4detectors/PHG4CylinderGeom_Spacalv3.h, simulation/g4simulation/g4detectors/PHG4FullProjSpacalCellReco.cc, simulation/g4simulation/g4detectors/PHG4FullProjSpacalCellReco.h, simulation/g4simulation/g4detectors/PHG4FullProjSpacalCellRecoLinkDef.h, simulation/g4simulation/g4detectors/PHG4SpacalPrototypeSteppingAction.cc, simulation/g4simulation/g4main/PHG4Hit.cc, simulation/g4simulation/g4main/PHG4Hit.h, simulation/g4simulation/g4main/PHG4Hitv1.cc, simulation/g4simulation/g4main/PHG4Hitv1.h, simulation/g4simulation/g4main/PHG4SteppingAction.cc, simulation/g4simulation/g4main/PHG4SteppingAction.h
As preparation to the coming test beam workfest, this pull request puts SPACAL simulation to a near final shape by introducing scintillation light collection model that handles both fiber attenuation and light guide position dependent efficiency.
Also as a general service, this pull request introduce calculation and storage of local coordinates via commit ac9ae806aaa29d3c774830a16dfd4b0c3e694a91, which would be useful for light collection efficiency calculation for HCal and Digitization for MAPS tracker. 
Sean Stoll (BNL) extracted effective light attenuation for SCSF-78 scintillation fiber from manufacture spec curves to be 105 cm. To be confirmed with our measurements. The reflection at the non-readout end is ~30%. Together, the relative light collection efficiency along length position …
=> scintillation light collection in SPACAL

generators/PHPythia6/PHPythia6.C
Added support for the pmas setting; we use this to set the charm and bottom quark mass when it's important to match to data....
=>  add support for pmas setting

offline/packages/Prototype2/EventHeader_Prototype2.C, offline/packages/Prototype2/EventHeader_Prototype2.h, offline/packages/Prototype2/EventHeader_Prototype2LinkDef.h, offline/packages/Prototype2/Makefile.am, offline/packages/Prototype2/RawTower_Prototype2.h, offline/packages/Prototype2/RunInfoUnpackPRDF.C, offline/packages/Prototype2/configure.in
From Test Beam workfest, adding event header to DST which store event number, type and timestampe. The immediate goals is to allow analysis code etrieve event time for use in temperature correction. 
Also the header installation location is updated to prototype2, e.g. inclusion of the EventHeader uses #include <prototype2/EventHeader_Prototype2.h>
An example DST production from PRDF can be run using the default macro on RCF: 
https://github.com/sPHENIX-Collaboration/macros/blob/master/macros/prototype2/Fun4All_TestBeam.C 
From the DST output (./data/beam_00002609.root), the event header could be interactively printed via 
```
[jinhuang@rcas2073 macros]$ root
root [0]   gSystem->Load("libPrototype2.so");
root [2] TFile *_file0 = TFile::Open("data/beam_00002609.root")
root [3] …
```
=> Add event header for test beam analysis produciton

simulation/g4simulation/g4main/PHG4SteppingAction.cc
This pull request introduce a bug fix for local coordinate calculation utility.
Local coordinate calculation was introduced in #173 to the base class of ```PHG4SteppingAction```. Tony @adfrawley  reported the exit point calculation is wrong for the on-going MAPS detector development. This problem was traced down to the translation matrix for the exit point of PHG4Hit used the next logical volume passing the sensitive volume. Fix was straight forward: use the pre-step's translation matrix for glocal-to-local transformation of both pre- and post-points. 
Currently two subsystem uses this local coordinates translation. Both are checked:
Local x-y coordinate of exit point is plotted here for PHG4Hits in SPACAL fibers in one electron shower. It shows a nice circular shell for at the radius of …
=> Bug fix on local coordinate calculation

online_distribution/newbasic/oncsBuffer.cc
that ended the buffer processing prematurely. Don't know why the bug persisted here.
It manifests itself by missing event numbers when one writes "oncs-format" data. The bug had already been fixed in April while we were at Fermilab. It is only at the decoding stage so so data are affected.
=> back-ported a long-standing fix from the PHENIX side

simulation/g4simulation/g4detectors/PHG4SectorConstructor.cc, simulation/g4simulation/g4detectors/PHG4SectorConstructor.h, simulation/g4simulation/g4detectors/PHG4SectorDetector.cc, simulation/g4simulation/g4detectors/PHG4SectorDetector.h
Match methods to pass 'overlapcheck' in Sector and RICH
=> Match overlapcheck passing in Sector and RICH

simulation/g4simulation/g4detectors/PHG4CylinderGeom_Spacalv1.cc, simulation/g4simulation/g4detectors/PHG4CylinderGeom_Spacalv2.cc, simulation/g4simulation/g4detectors/PHG4CylinderGeom_Spacalv3.cc, simulation/g4simulation/g4detectors/PHG4SpacalDetector.cc
In https://github.com/sPHENIX-Collaboration/macros/pull/34, @nfeege reported an overlap error in central EMCal. That trace to an overlap problem introduce to 1-D projective SPACAL  ( ~30um overlap between sectors) in a past commit (cfb339e64a3fcfbdf0df35ed0b10a75a8a52ac76). 2-D projective SPACAL is NOT affected. 
This pull request carries the patch fixing this problem.
Both 1-D and 2-D projective SPACAL do not has overlap after this fix. Nevertheless, I also invite @nfeege to check again in the full macro. 
For 1-D projective SPACAL, this bug lead to ~30um overlap between sectors. Fixing this problem slightly changed the visible sampling fraction from 2.33% in the nightly-build to 2.28% with this patch. The full comparison is checked with calorimeter QA using 24 GeV electrons: 
The 2-D …
=> Overlap in 1-D projective SPACAL

offline/packages/PHGenFitPkg/PHGenFit/Fitter.cc, offline/packages/PHGenFitPkg/PHGenFit/Fitter.h, offline/packages/PHGenFitPkg/PHGenFit/SpacepointMeasurement.cc, offline/packages/PHGenFitPkg/PHGenFit/SpacepointMeasurement.h, offline/packages/PHGenFitPkg/PHGenFit/Track.h, simulation/g4simulation/g4hough/Makefile.am, simulation/g4simulation/g4hough/PHG4TrackFastSim.C, simulation/g4simulation/g4hough/PHG4TrackFastSim.h, simulation/g4simulation/g4hough/PHG4TrackFastSimLinkDef.h, simulation/g4simulation/g4hough/SvtxTrack.h, simulation/g4simulation/g4hough/SvtxTrack_FastSim.C, simulation/g4simulation/g4hough/SvtxTrack_FastSim.h, simulation/g4simulation/g4hough/SvtxTrack_FastSimLinkDef.h
Introducing a Truth Tracking module into g4hough.
Smearing PHG4Hits form G4 simulations to mimic measurements.
Use truth information to do a pseudo pattern recognition.
Originally designed for the forward tracking. Now generalized to any cylindrical or vertical plane detector setup. Also this module utilized [Jin's PHGeometry offline package](https://github.com/sPHENIX-Collaboration/coresoftware/tree/master/offline/packages/PHGeometry) to handle the G4 => G3 on-the-fly translation, so no need of external G3 root file input. Example event display for FGEM and Maps+TPC:
Affected code:
- Add a new SvtxTrack derived class SvtxTrack_FastSim:SvtxTrack_v1 and modified the SvtxTrack base class for truth g4particle and phg4hits association.
- PHGenFit package. Compatible with Jin's PHGeometry; …
=> Truth tracking2

offline/database/pdbcal/base/Makefile.am, offline/database/pdbcal/base/PdbParameterMapContainer.cc, offline/database/pdbcal/base/PdbParameterMapContainer.h, offline/database/pdbcal/pg/Makefile.am, offline/database/pdbcal/pg/PgPostApplication.cc, offline/database/pdbcal/pg/RunToTimePg.cc, offline/packages/NodeDump/DumpPdbParameterMap.cc, offline/packages/NodeDump/DumpPdbParameterMapContainer.cc, offline/packages/NodeDump/DumpPdbParameterMapContainer.h, offline/packages/NodeDump/Makefile.am, offline/packages/NodeDump/PHNodeDump.cc, simulation/g4simulation/g4detectors/Makefile.am, simulation/g4simulation/g4detectors/PHG4BlockDetector.cc, simulation/g4simulation/g4detectors/PHG4CylinderGeomv4.cc, simulation/g4simulation/g4detectors/PHG4CylinderSubsystem.cc, simulation/g4simulation/g4detectors/PHG4CylinderSubsystem.h, simulation/g4simulation/g4detectors/PHG4DetectorSubsystem.cc, simulation/g4simulation/g4detectors/PHG4DetectorSubsystem.h, simulation/g4simulation/g4detectors/PHG4EICForwardEcalDetector.cc, simulation/g4simulation/g4detectors/PHG4Parameters.cc, simulation/g4simulation/g4detectors/PHG4Parameters.h, simulation/g4simulation/g4detectors/PHG4ParametersContainer.cc, simulation/g4simulation/g4detectors/PHG4ParametersContainer.h, simulation/g4simulation/g4detectors/PHG4ParametersContainerLinkDef.h, simulation/g4simulation/g4detectors/PHG4Prototype2InnerHcalSubsystem.cc, simulation/g4simulation/g4detectors/PHG4Prototype2OuterHcalSubsystem.cc, simulation/g4simulation/g4detectors/PHG4SpacalPrototypeDetector.cc, simulation/g4simulation/g4detectors/PHG4SpacalPrototypeDetector.h, simulation/g4simulation/g4detectors/PHG4SpacalPrototypeSubsystem.cc, simulation/g4simulation/g4detectors/PHG4SpacalPrototypeSubsystem.h
The tracker needs parameters on a layer by layer basis. Previously this was done by giving each layer its own parameter class instance leading to a large number of nodes (also DB table and/or calibration files). This pull request introduces a container where multiple parameter instances can be handled as a single entity. Those parameters do not have to describe the same detector type, it is possible to merge e.g. a tilted plate hcal with a surrounding cylinder for the electronics into one calibration object. The previous standalone parameter class is still available (for e.g. single layer cylinders).
Since this change only deals with the handling of parameters but not their value, it doesn't change the simulations results (which was verified). This only affects subsystems inheriting from …
=> Extend parameter class to handle multiple layers

offline/packages/Prototype2/CaloCalibration.C, offline/packages/Prototype2/CaloUnpackPRDF.C, offline/packages/Prototype2/GenericUnpackPRDF.C, offline/packages/Prototype2/Prototype2DSTReader.h, offline/packages/Prototype2/RunInfoUnpackPRDF.C, offline/packages/Prototype2/TempInfoUnpackPRDF.C, offline/packages/Prototype2/TempInfoUnpackPRDF.h, simulation/g4simulation/g4detectors/PHG4Prototype2InnerHcalDetector.cc, simulation/g4simulation/g4detectors/PHG4Prototype2InnerHcalDetector.h, simulation/g4simulation/g4detectors/PHG4Prototype2InnerHcalSubsystem.cc, simulation/g4simulation/g4detectors/PHG4Prototype2InnerHcalSubsystem.h, simulation/g4simulation/g4detectors/PHG4Prototype2OuterHcalDetector.cc, simulation/g4simulation/g4detectors/PHG4Prototype2OuterHcalDetector.h, simulation/g4simulation/g4detectors/PHG4Prototype2OuterHcalSubsystem.cc, simulation/g4simulation/g4detectors/PHG4Prototype2OuterHcalSubsystem.h
The inner/outer hcal prototypes now inherit from PHG4DetectorSubsystem which simplifies the code tremendously. The high rapidity test setup only differs in the shape of the scintillators, an option (hi_eta) can be used to switch between them. The placement on the platform also differs but that can be accomplished by changing the placement of the hcals in the macro. The code was verified for midrapidity, the hits are identical compared to the previous implementation.
Some cosmetic change for the beam prototype code: We should really watch out that includes using quotes are before include using brackets. Mixing this can lead to really strange behaviour since includes can be picked up from the wrong place on a case by case basis.
=> add forward rapidity test setup to hcal prototypes

simulation/g4simulation/g4detectors/PHG4Prototype2InnerHcalDetector.cc, simulation/g4simulation/g4detectors/PHG4Prototype2OuterHcalDetector.cc, simulation/g4simulation/g4detectors/PHG4Prototype2OuterHcalDetector.h
The most recent design change was to move the scintillator tiles to the front of the steel plates. Also some code cleanup (use of CGAL was not needed), code now very similar to inner hcal prototype but given that the sizes are very different merging them would result in very confusing setups.
=> move the hi eta scintillator tiles of the outer hcal to the front edge of the steel plates

simulation/g4simulation/g4detectors/PHG4Prototype2InnerHcalSteppingAction.cc, simulation/g4simulation/g4detectors/PHG4Prototype2OuterHcalSteppingAction.cc, simulation/g4simulation/g4main/PHG4Hit.cc, simulation/g4simulation/g4main/PHG4Hit.h, simulation/g4simulation/g4main/PHG4Hitv1.h
This patch adds a hit_type property to PHG4Hit and makes use of it in the inner and outer HCAL prototype stepping actions. This allows one to flag hits that have an EM (e+/e-) or hadronic (all others) origin very easily at the hist stage to facilitate studies of the HCAL signal shapes and the correlations with fluctuations in the EM fraction of the showers.
=> add hit flag for shower studies in prototype

simulation/g4simulation/g4detectors/PHG4OuterHcalSubsystem.cc, simulation/g4simulation/g4detectors/PHG4Prototype2InnerHcalDetector.cc, simulation/g4simulation/g4detectors/PHG4Prototype2OuterHcalDetector.cc, simulation/g4simulation/g4main/PHG4Reco.cc
Up to now we used SS310 for the hcal prototype steel and G4_Fe for the outer hcal. The prototypes are made of a36 and the outer hcal will use 1006. Those materials were added (from the compositions as listed in http://www.matweb.com) and are now the defaults for the prototypes and outer hcal
=> Add a36 and 1006 steel and use for prototype (a36) and outer hcal (1006)

offline/packages/PHGenFitPkg/PHGenFit/Track.cc, offline/packages/PHGenFitPkg/PHGenFit/Track.h, simulation/g4simulation/g4hough/PHG4TrackFastSim.C, simulation/g4simulation/g4hough/PHG4TrackFastSim.h, simulation/g4simulation/g4hough/SvtxTrackState.h, simulation/g4simulation/g4hough/SvtxTrackState_v1.C, simulation/g4simulation/g4hough/SvtxTrackState_v1.h
This patch utilizes the ability of SvtxTrack to save track states to hold projections of track to different detectors - currently the barrel or forward calorimeters.  These projections can then be used in analysis code, etc., to attach calorimeter clusters to the track, etc. 
For the forward calorimeters I have checked this with the FEMC and FHCAL using 30GeV e-/pi- and the projections to attach the closest FEMC and FHCAL clusters.  The E/p for each is plotted below: 
Electrons: 
Negative Pions: 
There are still a few things I might like to add/fix before merging: 
- The constructor for SvtxTrackState takes the pathlength as the argument, but for now this is either the z-location (for the forward calorimeters) or radial position (for the barrel).  The pathlength must come from the fitted …
=> Add SvtxTrackState to SvtxTrack for requested detector projections to SvtxTrack_FastSim

offline/packages/Prototype2/PROTOTYPE2_FEM.C
Saturation correction to the ADC timing samples. After discussing in the HCAL workfest we decided to redo the signal fits without the saturation points. This would potentially improve nonlinearity observed in HCAL test beam performance. Below is an example:
Fit with saturated points:
Fit without saturation points:
=> Saturation Correction

offline/packages/HelixHough/helix_hough/HelixHough.h, offline/packages/HelixHough/helix_hough/HelixHough_findHelices.cpp, offline/packages/HelixHough/helix_hough/HelixHough_init.cpp, offline/packages/HelixHough/helix_hough/sPHENIX/sPHENIXTrackerTPC.cpp, offline/packages/HelixHough/helix_hough/sPHENIX/sPHENIXTrackerTPC.h, simulation/g4simulation/g4hough/PHG4HoughTransformTPC.C, simulation/g4simulation/g4hough/PHG4HoughTransformTPC.h
This pull request is to replace the current initial z-vertexing (from BBC with no smearing) with the realistic initial z-vertexing with MAPS+TPC.
The changes made:
offline/package/HelixHough/helix_hough/* 
: add a switch to use selective range of layers. 
: revive findTrackBySegments for initial z-vertexing. 
simulation/g4simulation/g4hough/PHG4HoughTransformTPC.*
: general makeover (modularization) 
: add seeded-tracking steps for initial z-vertexing
Here is an example of performance plot. 
(the std of z-vertex offset ~10um.)
[maps+tpc_L4_chisq2_3.pdf](https://github.com/sPHENIX-Collaboration/coresoftware/files/397612/maps.tpc_L4_chisq2_3.pdf)
=> Initial z-vtxing for MAPS+TPC configuration

offline/packages/Prototype2/PROTOTYPE2_FEM.C
Following #204 , in which @sen1 suggest ignore saturated ADC sample in prototype2 signal fit, we found the fit result in tower energy still suffers from saturation. The problem trace to the choice of fit parameter that is output as energy in ```PROTOTYPE2_FEM.C```. In the current version, the scale constant in front of the signal shape function is returned as tower energy. However, as signal saturates, the shape changes and the scale constant does not represents the energy anymore. 
Therefore, this pull request change the fit to return true ADC-VS-time peak height as energy in a tower, which is calculated analytically in 	3126ef5 . Test production show improved HCal linearity and slightly improved EMCal resolution after this change. 
See Hcal test in Abhisek's talk in HCal meeting …
=> Signal peak fit for calorimeter prototype2 analysis

simulation/g4simulation/g4eval/SvtxEvaluator.C
Fix a typo(?) of the SvtxEvaluator:
Instead of using the incoming Geant hit position, use the average position for the PHG4Hits related evaluations.
=> Svtx evaluator

simulation/g4simulation/g4hough/PHG4TrackFastSim.C, simulation/g4simulation/g4hough/PHG4TrackFastSim.h
Submitted for consideration, although I am sure this is not the last word.  Currently PHG4TrackFastSim only checks primary tracks for fast tracking. This modification leaves primary tracks as the default, but enables a switch to search all tracks  (set in G4_FGEM_fsPHENIX.C:FGEM_FastSim_Reco): 
kalman->set_primary_tracking(0); // 0=all tracks, >0 = primaries only
I could use some advice here - it seems that PHG4TruthInfoContainer makes some distinction between tracks and showers, so this isn't horribly inefficient in the sense that it searches over all tracks in an EM shower, but I am uncertain how the truth tracking is done so this interpretation may not be correct. Another way to do this would be to just combine hits in the FGEM's from the same tracks, but that is more complicated and …
=> Enable tracking for all tracks, not just primaries

simulation/g4simulation/g4detectors/PHG4ConeSteppingAction.cc, simulation/g4simulation/g4detectors/PHG4ConeSteppingAction.h, simulation/g4simulation/g4detectors/PHG4ForwardEcalSteppingAction.cc, simulation/g4simulation/g4detectors/PHG4ForwardEcalSteppingAction.h, simulation/g4simulation/g4detectors/PHG4ForwardHcalSteppingAction.cc, simulation/g4simulation/g4detectors/PHG4ForwardHcalSteppingAction.h, simulation/g4simulation/g4detectors/PHG4SectorSteppingAction.cc, simulation/g4simulation/g4detectors/PHG4SectorSteppingAction.h
I propagated the new handling of zero energy deposition hits to the fsPHENIX detectors (cone, sector, femc, fhcal). This results in a memory reduction of 25% (16GB -> 12GB) in processing hijing events with those detectors. The resulting hits did not change (except no more gaps in the hit id because zero edep hits are not removed in a later stage leaving gaps in those ids).
valgrind indicates a use of uninitialized variables and writing uninitialized vars in the output but this seems to come from the saving of the G4 geometry on the DST
=> zero energy deposition hits not saved for fsPHENIX detectors

generators/PHPythia6/PHPy6ForwardElectronTrig.C, generators/PHPythia6/PHPy6ForwardElectronTrig.h, generators/PHPythia6/PHPythia6.C, generators/PHPythia6/PHPythia6.h
PHPYthia6 in the sPHENIX repositories was configured to use a hard-coded random seed. Guess how I found this. Guess how much time it wasted. 
This commit modifies PHPythia6 to use the same method to set the random see used in the PHENIX version of PHPythia6, and adds a function to allow the user to set the seed manually. 
This commit also changes the example electron trigger to use PT instead of ptot - this just makes more sense for forward physics.
=> Fix PHPythia6 random seed, set electron trigger to use pT (not ptot)

generators/PHPythia8/PHPy8GenTrigger.C, generators/PHPythia8/PHPy8JetTrigger.C, generators/PHPythia8/PHPy8ParticleTrigger.C, generators/PHPythia8/PHPythia8.C, generators/PHPythia8/PHPythia8.h, simulation/g4simulation/g4detectors/PHG4CylinderCellTPCReco.cc, simulation/g4simulation/g4detectors/PHG4CylinderCellTPCReco.h, simulation/g4simulation/g4detectors/PHG4CylinderDetector.cc, simulation/g4simulation/g4detectors/PHG4CylinderDetector.h, simulation/g4simulation/g4detectors/PHG4InnerHcalDetector.cc, simulation/g4simulation/g4detectors/PHG4OuterHcalDetector.cc, simulation/g4simulation/g4detectors/PHG4RICHDetector.cc, simulation/g4simulation/g4detectors/PHG4RICHDetector.h, simulation/g4simulation/g4detectors/ePHENIXRICHConstruction.cc, simulation/g4simulation/g4detectors/ePHENIXRICHConstruction.h
The offset of the front (positive tilt) or back (negative tilt) corners of the first tile respect to phi=0 is calculated and used to align the towers independent of the tilt angle or the number of tiles. This still needs to be propagated to the cell/tower geometry but at least we do not need tilt angle dependent calibrations in the analysis anymore.
PHPythia8 now uses PHRandomSeed() as sole source for random seed (the recoConsts was removed, this is handled inside PHRandomSeed()).
A handful of cppcheck warnings and the usual mixup of includes with quotes vs includes with <> were fixed
=> shift hcal tiles so their phi coverage does not change with tilt angle or number of tiles

generators/PHPythia6/PHPy6ForwardElectronTrig.C, generators/PHPythia6/PHPy6ForwardElectronTrig.h, generators/PHPythia6/PHPythia6.C, generators/PHPythia6/PHPythia6.h, simulation/g4simulation/g4hough/PHG4TrackFastSim.C, simulation/g4simulation/g4hough/PHG4TrackFastSim.h, simulation/g4simulation/g4hough/SvtxTrack_FastSim.C, simulation/g4simulation/g4hough/SvtxTrack_FastSim.h
Submitted for your consideration - it would be very useful to keep track of *at least* the number of hits on a FastSim track, especially when looking at all tracks and not just primary tracks.  The evaluation software from Haiwang uses the "size_clusters()" method to extract the number of hits on the track, but in SvtxTrack this is meant to keep track of the number of calorimeter clusters attached to the track, and in any case PHG4TrackFastSim does nothing to fill it. 
The attached patch just adds the ability to store the number of measurements along the track in SvtxTrack_FastSim and adds the code to PHG4TrackFastSim to initialize it.  
It might be nice to store an id/pointer to the detector-specific hits instead, but this should be done in a more general way that will ultimately …
=> Keep track of number of hits for fast sim track

simulation/g4simulation/g4detectors/PHG4CylinderCellTPCReco.cc, simulation/g4simulation/g4hough/PHG4TPCClusterizer.C
Changes made to PHG4CylinderCellTPCReco and PHG4TPCClusterizer.
With this change, also when the space charge distortion in PHG4CylinderCellTPCReco turned off.
The TPC cluster pulldistribution w.r.t PHG4Hit looks almost perfect:
Related to [this talk](https://indico.bnl.gov/getFile.py/access?contribId=2&resId=0&materialId=slides&confId=1935)
=> Shift TPC cluster centers to the corresponding PHG4Hit center

simulation/g4simulation/g4main/HepMCNodeReader.cc, simulation/g4simulation/g4main/PHG4Particle.h, simulation/g4simulation/g4main/PHG4Particlev1.cc, simulation/g4simulation/g4main/PHG4Particlev1.h, simulation/g4simulation/g4main/PHG4Particlev2.cc, simulation/g4simulation/g4main/PHG4Particlev2.h, simulation/g4simulation/g4main/PHG4PrimaryGeneratorAction.cc, simulation/g4simulation/g4main/PHG4TruthTrackingAction.cc, simulation/g4simulation/g4main/PHG4UserPrimaryParticleInformation.h
This set of modifications will carry the HepMC barcode through to the truth information for primary particles, allowing you to connect a PHG4Particle from PHG4TruthInfoContainer back to the HepMC event record, which then allows you to track back the true origin of a primary in the HepMC event record. For example: 
`         PHHepMCGenEvent *genevent = findNode::getClass<PHHepMCGenEvent>(topNode,"PHHepMCGenEvent");
HepMC::GenEvent *evt = genevent->getEvent();
PHG4TruthInfoContainer::ConstRange range =
_truth_container->GetParticleRange();
for (PHG4TruthInfoContainer::ConstIterator truth_itr = range.first;
truth_itr != range.second; ++truth_itr) {
PHG4Particle* g4particle = truth_itr->second;
if(_truth_container->is_primary(g4particle)){
HepMC::GenParticle *ptcle = …
=> carry HepMC barcode information through truth tracking

simulation/g4simulation/g4cemc/HcalRawTowerBuilder.cc, simulation/g4simulation/g4detectors/PHG4HcalDefs.h, simulation/g4simulation/g4detectors/PHG4InnerHcalSubsystem.cc
This is a quick patch which fills the tower geometry object from what is in the detector parameters. Things like the eta binning have changed so I assume the cluster building which used this never really worked in the last months
=> fix problems in clustering caused by unfilled raw tower geometry object

simulation/g4simulation/g4hough/PHG4HoughTransform.C, simulation/g4simulation/g4hough/PHG4HoughTransformTPC.C, simulation/g4simulation/g4hough/PHG4SvtxClusterizer.C, simulation/g4simulation/g4hough/PHG4SvtxDigitizer.C, simulation/g4simulation/g4hough/PHG4TPCClusterizer.C, simulation/g4simulation/g4hough/PHG4TrackFastSim.C, simulation/g4simulation/g4hough/PHG4TrackKalmanFitter.C
Thanks for @SashaLebedev for reporting a crash for TPC simulation after a few recent software changes. The problem trace to multiple tracking subsystem code built IO nodes onto the RUN node instead of the DST node, which is not reset after each event and not written to DST files. This problem only acted now as the geometry parameter are now saved to a composite SVTX node on the RUN node. 
This problem should be fixed after nightly build.
=> Fix various tracking code so that tracking IO object always use the DST node

simulation/g4simulation/g4detectors/Makefile.am, simulation/g4simulation/g4detectors/PHG4BlockSteppingAction.cc, simulation/g4simulation/g4detectors/PHG4ConeDetector.cc, simulation/g4simulation/g4detectors/PHG4ConeRegionSteppingAction.cc, simulation/g4simulation/g4detectors/PHG4CrystalCalorimeterSteppingAction.cc, simulation/g4simulation/g4detectors/PHG4EnvelopeDetector.cc, simulation/g4simulation/g4detectors/PHG4FCalDetector.cc, simulation/g4simulation/g4detectors/PHG4FCalSteppingAction.cc, simulation/g4simulation/g4detectors/PHG4FPbScDetector.cc, simulation/g4simulation/g4detectors/PHG4FPbScRegionSteppingAction.cc, simulation/g4simulation/g4detectors/PHG4FPbScSteppingAction.cc, simulation/g4simulation/g4detectors/PHG4FPbScSubsystem.cc, simulation/g4simulation/g4detectors/PHG4ForwardEcalSteppingAction.cc, simulation/g4simulation/g4detectors/PHG4ForwardHcalSteppingAction.cc, simulation/g4simulation/g4detectors/PHG4MapsDetector.cc, simulation/g4simulation/g4eval/SvtxEvaluator.C, simulation/g4simulation/g4main/PHG4Particlev2.cc, simulation/g4simulation/g4main/PHG4Particlev2.h
During cross check of #218 and #219, valgrind and cppcheck tests were run on the tracker simulation which revealed a few historical problems. This pull request try to fix some of them:
1. duplicated ```PHG4Particlev2::barcode``` and its interface functions that shadow that of  PHG4Particlev1
2. inconsistent NTuple data length in ```SvtxEvaluator.C```
3. uninitialized variables in variable code
4. unchecked iterator in various code 
Propose to merge after merging #218 and #219
=> Cumulative memory bug fixes

simulation/g4simulation/g4cemc/HcalRawTowerBuilder.cc, simulation/g4simulation/g4cemc/RawTowerContainer.h, simulation/g4simulation/g4detectors/PHG4BlockDetector.cc, simulation/g4simulation/g4detectors/PHG4BlockDetector.h, simulation/g4simulation/g4detectors/PHG4BlockSubsystem.cc, simulation/g4simulation/g4detectors/PHG4CylinderCellGeom_Spacalv1.cc, simulation/g4simulation/g4detectors/PHG4EnvelopeDetector.cc, simulation/g4simulation/g4detectors/PHG4EnvelopeDetector.h, simulation/g4simulation/g4detectors/PHG4ScintillatorSlat.h, simulation/g4simulation/g4detectors/PHG4ScintillatorSlatv1.h
The raw tower geometry was set during Init() while the parameters were only read from the node tree during the InitRun(), that lead to invalid radii and thickness's. Also missing was the loop which sets the eta/phi ranges. They are now filled generically from info added by the g4 detector implementation
Also some cleanup of include files and forward declaration
=> fill the raw tower geom properly - second attempt

generators/sHijing/Hijing.cxx, generators/sHijing/Makefile.am, generators/sHijing/configure.ac, generators/sHijing/sHijing.xml
The config file can now be given as cmd line argument (clunky - should be replaced by boost program_options) so we can use this in batch. Default is now a random random seed, rather than hardcoded 11793. Can still be overridden by setting in config file. Some cleanups (cppcheck) took care of warnings, now -Werror enabled
=> some improvements of sHijing

offline/QA/modules/QAG4SimulationCalorimeter.C, offline/database/pdbcal/base/Makefile.am, offline/database/pdbcal/base/PdbParameterMap.cc, offline/database/pdbcal/base/PdbParameterMap.h, offline/database/pdbcal/base/PdbParameterMapContainer.cc, offline/database/pdbcal/base/PdbParameterMapContainer.h, simulation/g4simulation/g4detectors/PHG4CylinderGeom_Spacalv3.h, simulation/g4simulation/g4detectors/PHG4Parameters.cc, simulation/g4simulation/g4detectors/PHG4Parameters.h, simulation/g4simulation/g4detectors/PHG4SpacalPrototypeDetector.cc, simulation/g4simulation/g4detectors/PHG4SpacalPrototypeSubsystem.cc
A few update on the core software to support the prototype3 EMCal simulation: 
- Support save PdbParameterMapContainer to files
- To address #199, add hash check to PdbParameterMap and expanded the XML output decimal precision from ```%15e``` to ```%18g``` (required precision for loss-less save of IEEE 754 double). Confirmed the read back reproduce the initial binary hash
- Update SPACAL 32-bit scintillator ID assignment to support higher fiber count in 2x2 blocks. This will **break the backward compatibility with previously simulated EMCal DSTs in both sPHENIX and prototypes.** 
- Minor: allow user to set the rotation of EMCal around the (sphenix) z axis 
- Minor: add G4hit->G4particle consistency check on the truth container in the calorimetry QA module. 
32 GeV pion in prototype3 …
=> Add support of prototype3 EMCal

simulation/g4simulation/g4main/HepMCNodeReader.cc, simulation/g4simulation/g4main/PHG4ParticleGeneratorBase.cc, simulation/g4simulation/g4main/PHG4ParticleGeneratorD0.cc, simulation/g4simulation/g4main/PHG4ParticleGeneratorVectorMeson.cc, simulation/g4simulation/g4main/PHG4Reco.cc
When running hijing simulations we have very rare crashes which are not reproducible when just rerunning with a different seed. Now the seed is printed out so those crashes can be reproduced
=> print out random number seeds for debugging

simulation/g4simulation/g4cemc/RawClusterContainer.cc, simulation/g4simulation/g4cemc/RawClusterv1.cc, simulation/g4simulation/g4cemc/RawTowerContainer.cc, simulation/g4simulation/g4cemc/RawTowerDigitizer.cc, simulation/g4simulation/g4cemc/RawTowerDigitizer.h, simulation/g4simulation/g4cemc/RawTowerGeom.cc, simulation/g4simulation/g4cemc/RawTowerGeomContainer.cc, simulation/g4simulation/g4cemc/RawTowerGeomContainer_Cylinderv1.cc, simulation/g4simulation/g4cemc/RawTowerGeomContainerv1.cc, simulation/g4simulation/g4cemc/RawTowerGeomv1.cc, simulation/g4simulation/g4cemc/RawTowerGeomv1.h, simulation/g4simulation/g4cemc/RawTowerGeomv2.cc, simulation/g4simulation/g4cemc/RawTowerGeomv2.h, simulation/g4simulation/g4cemc/RawTowerGeomv3.cc, simulation/g4simulation/g4cemc/RawTowerGeomv3.h, simulation/g4simulation/g4cemc/RawTowerv1.cc, simulation/g4simulation/g4cemc/RawTowerv1.h
I accidentally killed the tower digitization for empty towers, removing pedestals. That's back in with a comment to explain what is being done.
All obsolete ClassImp macros were removed (they are needed for the obsolete THtml machinery in root used for documentation, now superseded by doxygen). unused include files were removed.
=> fix tower digitization (put old scheme to loop over all possible towers back in)

simulation/g4simulation/g4detectors/Makefile.am, simulation/g4simulation/g4detectors/PHG4CylinderGeom_MAPS.h
Two fixes in silicon simulation code
1. As raised by @pinkenburg and @mccumbermike in #232 , ```PHG4CylinderGeom_MAPS``` does not have a public accessible default constructor, which is required for ROOT file IO via the streamer utilities. Adding it. 
Note if the default constructor is put under ```protected``` flag, ROOT still complains on the missing default constructor.  
2. @HaiwangYu raised an issue that the INTT ladder header file ```PHG4CylinderGeom_Siladders.h``` , which is required for downstream analysis. Adding it.
=> Two fixes in silicon simulation code

generators/PHPythia6/Makefile.am, generators/PHPythia6/PHPy6GenTrigger.C, generators/PHPythia6/PHPy6ParticleTrigger.C, generators/PHPythia6/PHPy6ParticleTrigger.h, generators/PHPythia6/PHPythia6LinkDef.h
Copied the PHPythia8/PHPy8ParticleTrigger module to PHPythia6/PHPy6ParticleTrigger and made changes to make it work with Pythia6-HepMC events. The trigger uses the Pythia6 event and particle information stored in HepMC format.
Here's a screenshot that shows it does what it is supposed to, i.e. reject Pythia6 events that do not match the particle trigger requirement:
=> Add Pythia6 particle trigger

simulation/g4simulation/g4detectors/PHG4CylinderGeom_Siladders.cc, simulation/g4simulation/g4detectors/PHG4SiliconTrackerCellReco.cc, simulation/g4simulation/g4detectors/PHG4SiliconTrackerDetector.cc, simulation/g4simulation/g4hough/PHG4SiliconTrackerDigitizer.C, simulation/g4simulation/g4hough/PHG4SvtxClusterizer.C
MAPS ladders + INTT ladders code working now, after fixing a few bugs in INTT ladder code. The changes were to:
g4detectors/PHG4SiliconTrackerDetector 
-- initialization of geometry object uses cm now, puts layers at correct radius etc.
-- fixed material bug - copper changed to G4_C
g4hough/PHG4SiliconTrackerCellReco  
-- fixed hard coding of layer numbers when defining timing cuts, was killing layer 6 hits
Here is a plot of the cluster distribution in the MAPS + INTT ladders:
[maps+intt_clusters_x_vs_y_all_ladders.pdf](https://github.com/sPHENIX-Collaboration/coresoftware/files/703445/maps.intt_clusters_x_vs_y_all_ladders.pdf)
Here is a plot of the number of hit layers per track in the MAPS and INTT. Where the number of hits is greater than the number of layers, it means more than one …
=> All ladders

simulation/g4simulation/g4detectors/Makefile.am, simulation/g4simulation/g4detectors/PHG4BeamlineMagnetDetector.cc, simulation/g4simulation/g4detectors/PHG4BeamlineMagnetDetector.h, simulation/g4simulation/g4detectors/PHG4BeamlineMagnetSubsystem.cc, simulation/g4simulation/g4detectors/PHG4BeamlineMagnetSubsystem.h, simulation/g4simulation/g4detectors/PHG4BeamlineMagnetSubsystemLinkDef.h
Adding a new class g4detectors/PHG4BeamlineMagnetSubsystem. This class represents beam line magnet for studies that need to consider the extended interaction region, for example exclusive processes in ep and eA collisions. The magnets are represented as cylinders with constant dipole or constant gradient quadrupole field within the cylinder volume. The magnet field, field type, position, aperture, outer radius, as well as position and rotation w.r.t. the nominal beam axis can be set via parameters.
This is a screenshot of five magnets in Fun4All (together with the BaBar coil from the default Fun4All macros):
A rough crosscheck of the deflection of particles in 'x'-direction at z=30 m caused by these magnets agrees reasonably well with calculations by CAD/MagnetDivision for the same …
=> Add PHG4BeamlineMagnetSubsystem

offline/packages/Prototype3/EventInfoSummary.C, offline/packages/Prototype3/EventInfoSummary.h, offline/packages/Prototype3/EventInfoSummaryLinkDef.h, offline/packages/Prototype3/Makefile.am, offline/packages/Prototype3/PROTOTYPE3_FEM.C, offline/packages/Prototype3/Prototype3DSTReader.cc, offline/packages/Prototype3/Prototype3DSTReader.h
Prototype3 production code update:
1. This year, the calorimeter signals are positive pulses. Adjust the ADC-time fitting code to allow overflow-ADC samples in the positive directions. 
2. Thanks for Martin pointing out a new signal this year encode the spill indicator. Added a module to interpret the spill indicator and place results in a new event information ''DST/EVENT_INFO'' node, as well as in the DST-reader TTrees as variable ''beam_Is_In_Spill''. 
Will start a new series of data production and update on wiki: https://wiki.bnl.gov/sPHENIX/index.php/2017_calorimeter_beam_test/Data_Production_and_Analysis#Production_output
=> Prototype3 production code update

generators/PHPythia6/PHPythia6.C
Adds a PdfInfo structure to the HEPMC GenEvent so the x1, x2, Q2 and parton id's for the event are saved.
=> add PDF info to to HepMC::GenEvent

simulation/g4simulation/g4hough/PHG4TrackFastSim.C
Fix memory leak by cleaning up new'd tracks before clearing list.
=> clean up memory before deleting track vector in PHG4TrackFastSim

simulation/g4simulation/g4hough/PHG4TrackFastSim.C
Minor changes to allow PHG4TrackFastSim to work properly with an event vertex other than the origin.
=> PHG4TrackFastSim: add in the use of the event vertex, not 0.0,0.0,0.0

simulation/g4simulation/g4hough/PHG4TrackFastSim.C
Clean up the gf_state allocation when done creating the SVXTrack.
=> A few more memory leak fixes for PHG4TrackFastSim

simulation/g4simulation/g4hough/PHG4TrackFastSim.C, simulation/g4simulation/g4hough/PHG4TrackFastSim.h
These changes allow for the vertex to be treated properly in the track fitting. The vertex is smeared *once* for a given even, and the projections have been modified so they are to the vertex and not (0,0,0) so that the DCA's are calculated correctly. 
Here's the 2D DCA as a function of vertex, not showing NO vertex dependence
=> proper use of vertex for z!=0 in PHG4TrackFastSim

offline/packages/PHGenFitPkg/Example/Makefile, offline/packages/PHGenFitPkg/Example/minimumTestPHGenFit.cc, offline/packages/PHGenFitPkg/PHGenFit/Fitter.cc, offline/packages/PHGenFitPkg/PHGenFit/Fitter.h, offline/packages/PHGenFitPkg/PHGenFit/Measurement.cc, offline/packages/PHGenFitPkg/PHGenFit/Track.cc, offline/packages/PHGenFitPkg/PHGenFit/Track.h, simulation/g4simulation/g4hough/PHG4TrackKalmanFitter.C, simulation/g4simulation/g4hough/PHG4TrackKalmanFitter.h
Fix memory leaks related to PHGenFit and PHG4TrackKalmanFitter.
After this fixing, with DST output turned off, there will be no memory leaks in `PHG4TrackKalmanFitter::process_event`
valgrind log file for one full pp event refitting with DST output turned off; cppcheck log file for PHGenFit and g4hough could be find here:
https://www.phenix.bnl.gov/WWW/p/draft/yuhw/PullRequest/2017-02-27/0/
There are still some one time memory leaks related with TGeo and loading RAVE libraries. But as they are one time leaks, we should be fine for now.
=> Memory leak fix for PHGenFit and PHG4TrackKalmanFitter

simulation/g4simulation/g4hough/Makefile.am, simulation/g4simulation/g4hough/PHG4TrackKalmanFitter.C, simulation/g4simulation/g4hough/PHG4TruthPatRec.C, simulation/g4simulation/g4hough/PHG4TruthPatRec.h, simulation/g4simulation/g4hough/PHG4TruthPatRecLinkDef.h
Tracking pattern recognition by grouping clusters associated with a truth `PHG4Particle`.
Introduction:
[2017-02-28 talk](https://indico.bnl.gov/getFile.py/access?contribId=1&resId=0&materialId=slides&confId=2682)
[2017-03-07 talk](https://indico.bnl.gov/conferenceDisplay.py?confId=2683)
Example macro:
[line 376, 377 of G4_Svtx_maps_ladders+intt_ladders+tpc_TruthPatRec.C ](https://github.com/HaiwangYu/macros/blob/TruthPatRec/macros/g4simulations/G4_Svtx_maps_ladders%2Bintt_ladders%2Btpc_TruthPatRec.C#L376)
As this module only do the pattern recognition, a kalman filter is needed to fit the track.
=> Truth Pattern Recognition for Tracking

simulation/g4simulation/g4hough/PHG4SvtxThresholds.C, simulation/g4simulation/g4hough/PHG4SvtxThresholds.h
this code will bite us again, it loops over the cylindergeom container for one detector, over cylindercellgeoms in others, extracting pitch,length,thickness via different methods but then calling the same cut and pasted code
=> okay - put the old PHG4SvtxThresholds back

simulation/g4simulation/g4hough/PHG4TrackKalmanFitter.C, simulation/g4simulation/g4hough/PHG4TrackKalmanFitter.h, simulation/g4simulation/g4hough/PHG4TruthPatRec.C, simulation/g4simulation/g4hough/SvtxTrackState.h, simulation/g4simulation/g4hough/SvtxTrackState_v1.h
Updated both GenFit( [`PHG4TrackKalmanFitter `](https://github.com/HaiwangYu/coresoftware/blob/master/simulation/g4simulation/g4hough/PHG4TrackKalmanFitter.C) ) and ideal pattern recognition ( [`PHG4TruthPatRec `](https://github.com/HaiwangYu/coresoftware/blob/master/simulation/g4simulation/g4hough/PHG4TruthPatRec.C) )modules.
Basically made them more automatic and woking with different Fun4All steering macro options.
Also some bugs were fixed for the ideal pattern recognition module.
I also made some example macros:
https://github.com/HaiwangYu/macros/tree/MakeRefitFormal
Now there are two easy-to-use switches:
- [use_truth_pat_rec](https://github.com/HaiwangYu/macros/blob/MakeRefitFormal/macros/g4simulations/Fun4All_single_particle.C#L50) : use ideal pattern recgnition instead of Hough …
=> Make refitting an official option

.clang-format, simulation/g4simulation/g4detectors/PHG4CylinderDetector.cc, simulation/g4simulation/g4detectors/PHG4CylinderDetector.h, simulation/g4simulation/g4detectors/PHG4CylinderSteppingAction.cc, simulation/g4simulation/g4detectors/PHG4CylinderSteppingAction.h, simulation/g4simulation/g4detectors/PHG4CylinderSubsystem.cc, simulation/g4simulation/g4detectors/PHG4CylinderSubsystem.h, simulation/g4simulation/g4detectors/PHG4CylinderSubsystemLinkDef.h, simulation/g4simulation/g4detectors/PHG4InnerHcalSteppingAction.cc, simulation/g4simulation/g4detectors/PHG4InnerHcalSteppingAction.h, simulation/g4simulation/g4detectors/PHG4InnerHcalSubsystem.cc, simulation/g4simulation/g4detectors/PHG4MapsSteppingAction.cc, simulation/g4simulation/g4detectors/PHG4OuterHcalSteppingAction.cc, simulation/g4simulation/g4detectors/PHG4OuterHcalSteppingAction.h, simulation/g4simulation/g4detectors/PHG4SpacalPrototypeSteppingAction.cc, simulation/g4simulation/g4detectors/PHG4SpacalSteppingAction.cc, simulation/g4simulation/g4detectors/PHG4SpacalSteppingAction.h, simulation/g4simulation/g4detectors/PHG4SpacalSubsystem.cc, simulation/g4simulation/g4detectors/PHG4SpacalSubsystem.h, simulation/g4simulation/g4main/PHG4Reco.cc, simulation/g4simulation/g4main/PHG4SteppingAction.cc, simulation/g4simulation/g4main/PHG4SteppingAction.h
This should not make a difference, the track status seems to be stopandkill which is another condition for saving a hit. Add some sanity checks if the hits are not scrambled (track id does not change, hit is initialized when it is updated). Try new formatting using clang-format, added .clang-format in top dir so 
clang-format -style=file -i <file>
reformats the file using our style conventions
Now for cylinders the deposited ionization energy is also stored (and optional with flag the light yield). For the hcals the deposited ionization is not saved anymore for the absorber which should lead to some space saving
=> add at rest condition to saving hits

generators/PHPythia6/Makefile.am, generators/PHPythia6/PHPy6JetTrigger.C, generators/PHPythia6/PHPy6JetTrigger.h, generators/PHPythia6/PHPythia6.C, generators/PHPythia6/PHPythia6LinkDef.h
Added the ability to use the "pytune" card in the pythia6 configuration file.  This allows use to run TuneA, which is a fair match at RHIC kinematics. 
Added a jet trigger which is the same functionality at the jet trigger in the PhPythia8 repository.  This will allow Pythia8 and Pythia6 comparisons on an equal footing.
=> Added ability to use Pythia6 Tunes, Jet trigger for comparison with Pythia8

simulation/g4simulation/g4eval/SvtxEvaluator.C, simulation/g4simulation/g4hough/PHG4TPCClusterizer.C, simulation/g4simulation/g4hough/PHG4TrackKalmanFitter.C, simulation/g4simulation/g4hough/SvtxCluster.h, simulation/g4simulation/g4hough/SvtxCluster_v1.C, simulation/g4simulation/g4hough/SvtxCluster_v1.h
Creating new function get_rphi_error() to return error in rphi measurement.
Changing get_phi_error() to get_rphi_error() for evaluator and kalmanFitter, since the intention in that code is to use the error of rphi and not the error of phi.
TPCClusterer now returns rphi as element of covariance (previously was phi).
=> patch to solve ambiguity in error_rphi for cluster

simulation/g4simulation/g4detectors/Makefile.am, simulation/g4simulation/g4detectors/PHG4DetectorGroupSubsystem.cc, simulation/g4simulation/g4detectors/PHG4DetectorGroupSubsystem.h, simulation/g4simulation/g4detectors/PHG4DetectorGroupSubsystemLinkDef.h, simulation/g4simulation/g4detectors/PHG4SiliconTrackerDetector.cc, simulation/g4simulation/g4detectors/PHG4SiliconTrackerDetector.h, simulation/g4simulation/g4detectors/PHG4SiliconTrackerSteppingAction.cc, simulation/g4simulation/g4detectors/PHG4SiliconTrackerSteppingAction.h, simulation/g4simulation/g4detectors/PHG4SiliconTrackerSubsystem.cc, simulation/g4simulation/g4detectors/PHG4SiliconTrackerSubsystem.h
use copy number to decode unproblematic strips rather than the complicated and cpu intensive check for the y/z range.Also start with the PHG4DetectorGroupSubsystem base class for subsystems containing multiple layers/detector ids
=> push temporary fix to get correct strip y indices

simulation/g4simulation/g4detectors/PHG4SiliconTrackerDetector.cc, simulation/g4simulation/g4detectors/PHG4SiliconTrackerSteppingAction.cc
It turns out that reducing the strip sizes by 1/10000th of their size takes care of the overlaps. I guess the approach to increase the size of the mother volume and adjusting the parametrization wasn't consistent. The code needed an additional check besides the copy number which can be identical for different logical volumes (copy = 0 is all over the place)
=> better fix for parametrized volume overlaps

offline/packages/trigger/CaloTriggerInfo.C, offline/packages/trigger/CaloTriggerInfo.h, offline/packages/trigger/CaloTriggerInfoLinkDef.h, offline/packages/trigger/CaloTriggerSim.C, offline/packages/trigger/CaloTriggerSim.h, offline/packages/trigger/CaloTriggerSimLinkDef.h, offline/packages/trigger/Makefile.am, offline/packages/trigger/autogen.sh, offline/packages/trigger/configure.in
Initial commit of calo trigger related code. 
There are two major components: (1) a calo trigger simulator module meant to emulate the performance of the Level-1 trigger to be used in sPHENIX data-taking, and (2) a lightweight node which stores calo-trigger information and is to be written to the node tree in simulations.
At the moment, only a photon trigger (or single-electron trigger for Upsilon triggering) is implemented which consists of a 4x4 sliding window (composed of four 2x2 windows) algorithm on the EMCal towers. The simulator is agnostic as to the EMCal geometry (e.g. 1D- or 2D-projective, which differ in their eta structure) and will set up the internal tower map according to what the geometry container object tells it.
This is intended to be the first commit just to get some …
=> Initial commit of calo trigger emulator and info node.

simulation/g4simulation/g4detectors/PHG4MapsDetector.cc, simulation/g4simulation/g4detectors/PHG4Prototype2InnerHcalSteppingAction.cc, simulation/g4simulation/g4detectors/PHG4Prototype2InnerHcalSteppingAction.h, simulation/g4simulation/g4detectors/PHG4Prototype2InnerHcalSubsystem.cc, simulation/g4simulation/g4detectors/PHG4Prototype2InnerHcalSubsystem.h, simulation/g4simulation/g4detectors/PHG4Prototype2OuterHcalSteppingAction.cc, simulation/g4simulation/g4detectors/PHG4Prototype2OuterHcalSteppingAction.h, simulation/g4simulation/g4detectors/PHG4Prototype2OuterHcalSubsystem.cc, simulation/g4simulation/g4detectors/PHG4Prototype2OuterHcalSubsystem.h
Just bringing the prototype2 hcals to the same level as other detectors. The resulting hits did not change (except the ionization energy is now also saved for the scintillators)
=> replace zero energy hit removal in afterburner by properly saving hits which contain energy

offline/packages/trigger/CaloTriggerInfo.h, offline/packages/trigger/CaloTriggerInfo_v1.C, offline/packages/trigger/CaloTriggerInfo_v1.h, offline/packages/trigger/CaloTriggerSim.C, offline/packages/trigger/CaloTriggerSim.h
CaloTriggerSim: A simulation of a"FullCalo" (jet patch) trigger is implemented. The trigger uses both EMCal and HCal tower energies, allowing for experimental triggering on jets of varying sizes and, potentially, on high-pT hadrons. The algorithm first creates a 0.1x0.1 grid in eta and phi as defined by the OHCal geometry. It then fills 0.1x0.1 grid blocks according to the energy in EMCal, IHCal and OHCal towers (for the EMCal, the geometric center of the small towers are used to assign them to the corresponding larger 0.1x0.1 blocks). The 0.1x0.1 blocks are regrouped into 0.2x0.2-sized blocks. Then, sliding windows over these 0.2x0.2 blocks are constructed with total sizes in eta by phi of 0.4x0.4, 0.6x0.6, 0.8x0.8 and 1.0x1.0. The highest-energy windows for each size are calculated, …
=> Adding FullCalo (jet patch) trigger simulator capability

simulation/g4simulation/g4detectors/Makefile.am, simulation/g4simulation/g4detectors/PHG4CylinderDetector.cc, simulation/g4simulation/g4detectors/PHG4CylinderSteppingAction.cc, simulation/g4simulation/g4detectors/PHG4CylinderSteppingAction.h, simulation/g4simulation/g4detectors/PHG4CylinderSubsystem.cc, simulation/g4simulation/g4main/HepMCCompress.cc, simulation/g4simulation/g4main/PHG4HitContainer.cc, simulation/g4simulation/g4main/PHG4HitContainer.h, simulation/g4simulation/g4main/PHG4Reco.cc, simulation/g4simulation/g4main/PHG4TruthTrackingAction.cc
The Cylinders can now save hits after each step with adjustable step size (that did not work before - Thanks Carlos for figuring this out). FR4 was added - found in ncc code by Andrey Sukhanov and the sPHENIX tpc gas (90% Ne, 10%CF4). Fixed some cppcheck warnings on the way
=> Modify PHG4Cylinder to accomodate TPC, add step size limit, add FR4 and sPHENIX tpc gas

offline/packages/NodeDump/DumpPHG4CylinderGeomContainer.cc, simulation/g4simulation/g4detectors/PHG4DetectorGroupSubsystem.cc, simulation/g4simulation/g4detectors/PHG4SiliconTrackerDetector.cc, simulation/g4simulation/g4detectors/PHG4SiliconTrackerDetector.h, simulation/g4simulation/g4detectors/PHG4SiliconTrackerSteppingAction.cc, simulation/g4simulation/g4detectors/PHG4SiliconTrackerSteppingAction.h, simulation/g4simulation/g4detectors/PHG4SiliconTrackerSubsystem.cc, simulation/g4simulation/g4detectors/PHG4SiliconTrackerSubsystem.h
Now all parameters are on the node tree. Writing out absorber hits works, the volume is encoded into the ladderz (hokey but this is anyway for testing only). We still have those hits with pre=post step status=fGeomBoundary and pre/post step in the same volume but they result in the same strip index. I assume it's when the stepping length by the physics process and the stepping length to the next geometrical are very close and then the physics process length is chosen. The code will print out a warning if the strip index turns out to be wrong.
=> Use PHG4Parameters to store/retrieve all the hardcoded silicon tracker numbers

simulation/g4simulation/g4detectors/PHG4MapsCellReco.cc, simulation/g4simulation/g4detectors/PHG4MapsCellReco.h
I modified PHG4MapsCellReco to add a timing cut on the hits. This was requested by Yorito Yamaguchi, who is doing event pileup studies for the INTT. Timing cuts are already implemented for the INTT ladders and for the cylinder cells.
The timing cut for the maps is set at a default value of +/- 2000 ns. The values can be over-written from the macro using the "set_timing_window" method. I checked that the timing cuts are set correctly.
=> Maps time window

simulation/g4simulation/g4detectors/PHG4SiliconTrackerDetector.cc
For some reason the intt geo object wants the strip_x, strip_y and strip_z in length/2. This patch is to restore the previous behavior and get Haiwang going again
=> quick patch to get strips geo back

simulation/g4simulation/g4detectors/PHG4CylinderGeom_Siladders.cc, simulation/g4simulation/g4detectors/PHG4SiliconTrackerDetector.cc, simulation/g4simulation/g4hough/PHG4SiliconTrackerDigitizer.C
Initially the strip dimensions were stored as length/2. just what G4 expects for boxes. But looking at the subsequent code it seems that this fact got lost and so in the tracking/clustering everything is off by a factor of 2 (the only method which treated this correctly was the return of the local coordinates). Affected is everything which uses geo->get_thickness(), geo->get_strip_y_spacing() and geo->get_strip_z_spacing(). It doesn't have a big effect but the results after this change are not identical anymore.
=> Changes to the silicon tracker geometry object

simulation/g4simulation/g4detectors/PHG4CylinderCellTPCReco.cc, simulation/g4simulation/g4detectors/PHG4CylinderCellTPCReco.h
Adding possibility to smear cloud center in TPC simulation as discussed in the previous software meeting: 
https://indico.bnl.gov/getFile.py/access?contribId=3&resId=0&materialId=slides&confId=2693
The code was tested by Tony already.
We added back the time correction for Z displacement as suggested by Jin.
=> Adding cloud center smearing

simulation/g4simulation/g4detectors/PHG4CylinderCellTPCReco.cc, simulation/g4simulation/g4detectors/PHG4CylinderCellTPCReco.h
it was still using the root random number generators, replaced by gsl. Removed TMath::Abs(), use defines from cmath (M_PI instead of acos(0) and SQRT2 instead of sqrt(2)). Replaced bad unsigned long key by the previous unsigned long long. Nota bene on 64 bits long is 64 bits like long long but on 32 bit architectures long is 32 bits (long long is 64 bits on 32 bit archs)- which is why the long type should never be used.
I am puzzled about the 60ns time window which looks like a leftover from the calorimeters.
=> fixed up PHG4CylinderCellTPCReco

offline/packages/trigger/CaloTriggerSim.C
Small bug in 1.0x1.0 FullCalo window energy calculation (simulator was incompletely calculating only the "upper left" 0.8x0.8 subset of each possible window).
=> fixing bug in 1.0x1.0 full calo window energy determination

simulation/g4simulation/g4hough/PHG4KalmanPatRec.C, simulation/g4simulation/g4hough/PHG4KalmanPatRec.h
Previously didn't rotate the norm vector when track propagated to silicon detectors.
This reduced the hit finding eff. in the silicon layers.
Fixed it in this patch.
Quickly tested with 5GeV and 30GeV pions embedded into central Hijing events.
Resolution for pT and DCA improved significantly:
5GeV:
30GeV:
=> KalmanPatRec - day one patch

offline/packages/trigger/CaloTriggerInfo.C, offline/packages/trigger/CaloTriggerInfo_v1.C, offline/packages/trigger/Makefile.am, simulation/g4simulation/g4detectors/PHG4CylinderCellTPCReco.cc, simulation/g4simulation/g4main/PHG4Hitv1.h
While compiling with root6 I came across a missing std:: in the PHG4Hitv1.h and a missing using namespace std in CaloTriggerInfo_v1.C for ostream which were probably resolved by root5. Coverity complained about inconsistent handling of int vs long long when generating the long long key.
ClassImps are obsolete (that macro was needed to generate the THtml documentation which has been phased out a long time ago in favour of doxygen)
=> small fixes to compile under root 6

offline/database/pdbcal/base/PdbParameterMapContainer.cc, offline/database/pdbcal/base/PdbParameterMapContainer.h, offline/framework/fun4all/Fun4AllServer.cc, offline/framework/fun4all/Fun4AllServer.h, offline/framework/phool/PHNodeOperation.h, offline/framework/phool/PHNodeReset.cc, offline/framework/phool/PHNodeReset.h, offline/framework/phool/PHObject.cc, offline/framework/phool/PHObject.h
The handling of the parametermap in the PHG4DetectorGroup base class isn't finished yet - the readback from the node tree still needs implementing so the parameters used for generating the background file is being used (right now we rely that the default settings are correct). During this the Reset() of the PdbParameterMapContainer class was called which wasn't implemented and lead to an Exit() during the embedding. Also the class name is now printed out in this error message to diagnose which class lacks the Reset() (will probably give PHObject if a class wasn't loaded when reading the DST which was the original intent of this). Also added verbosity flag to the PHNodeOperation class so we can put debug messages into its daughter classes
=> Fix for embedding

simulation/g4simulation/g4hough/PHG4KalmanPatRec.C, simulation/g4simulation/g4hough/PHG4KalmanPatRec.h
This is a temporary fix.
Reads in truth vertex and smear it with 100 micro to mimic a reconstructed vertex.
This enables tracking for events from vertex off (0,0,0) for now.
=> Tracking with vertex off (0,0,0)

simulation/g4simulation/g4detectors/PHG4DetectorGroupSubsystem.cc, simulation/g4simulation/g4detectors/PHG4ParametersContainer.cc, simulation/g4simulation/g4detectors/PHG4ParametersContainer.h, simulation/g4simulation/g4detectors/PHG4SiliconTrackerSubsystem.cc
This just follows the scheme of the parametermap handling. During sim step of the embedding we want to use the same parameters as during the production of the input DST. This is normally the case - as long as the default setting ins the code are not changed (and recompiled) so this is just a safeguard. I verified that the parameters used by the embedding don't change and are now stable even if the default parameters are changed in the code. The parameters can still be overridden in the macro or via reading from a DB or file (actually useful if you want to change the active setting)
=> read back parametermapcontainer from dst to restore setting used during production

offline/packages/jetbackground/RetowerCEMC.C, offline/packages/jetbackground/RetowerCEMC.h, offline/packages/jetbackground/SubtractTowers.C, offline/packages/jetbackground/SubtractTowers.h
The previous version of the RetowerCEMC and SubtractTowers modules attempted to create a new data node (for the retowerized-CEMC and subtracted CEMC/HCALIN/HCALOUT tower containers, respectively) for every event. Now this takes place only during InitRun(), and the containers are accessed from the node tree during process_event(). My initial test did not catch this because I was testing on a single dijet + Hijing background event. The DetermineBackground module has the correct Create/Fill model and does not need a fix.
=> Bugfix in treatment of new tower container nodes

offline/packages/PHGeometry/Makefile.am, offline/packages/PHGeometry/PHGeomIOTGeo.cc, simulation/g4simulation/g4dst/Makefile.am, simulation/g4simulation/g4dst/g4dst.C
This is a meta library which depends on all our io libraries. Loading it resolves all classes stored on our DSTs, so users do not have to figure out what libraries need loading to read in DSTs. Our PHGeometry library was split into an io lib for the dst content and a reco lib. I removed unneeded library dependencies which caused dependencies on e.g. odbc
=> convenience library to load all classes stored on our dsts

simulation/g4simulation/g4detectors/PHG4RICHSteppingAction.cc
As Chris pointed out in today's software meetings, G4Hits with exactly '0' energy may get discarded by following modules. Therefore, the energies of hits from optical Cerenkov photons are now set to the energy that these photons deposit according to Geant4 (which is a few eV per photon).
=> Set deposited energy for RICH photon hits to energy deposit from G4 step

simulation/g4simulation/g4detectors/PHG4InnerHcalSteppingAction.cc, simulation/g4simulation/g4detectors/PHG4InnerHcalSteppingAction.h, simulation/g4simulation/g4detectors/PHG4OuterHcalSteppingAction.cc, simulation/g4simulation/g4detectors/PHG4OuterHcalSteppingAction.h
It's something which shouldn't happen - after a post step status of fGeomboundary one would expect a pre step status of fGeomboundary which starts a new hit. Instead the next pre step status is fPostStepDoItProc and it's back in the previous pre step volume. This fix catches this condition and will create a new hit in this case. The printouts in case the hit is a null ptr (which means the previous hit was saved and deleted but no new hit was created in this step) contain a lot more info now to track these cases down
=> fix crashed caused by a rare combination of step status's

offline/framework/fun4all/Fun4AllInputManager.cc, offline/framework/fun4all/Fun4AllInputManager.h, offline/framework/fun4all/Makefile.am
Someone accidentally added a root file as list file with AddListFile(). The code interprets this as an ascii list and started filling the characters into an stl vector until the memory blew apart with 50GB. This change adds a check for the size. If it exceeds 1MB (which is a pretty large list) it returns with an error. It can be overridden if needed. Even if a binary file is used now it won't overflow the memory making this easier for the user to recognize - nice crash when running the job
=> check input manager list file for size and being a regular file

generators/PHSartre/Makefile.am, generators/PHSartre/PHSartre.C, generators/PHSartre/PHSartre.h, generators/PHSartre/PHSartreGenTrigger.C, generators/PHSartre/PHSartreGenTrigger.h, generators/PHSartre/PHSartreLinkDef.h, generators/PHSartre/PHSartreParticleTrigger.C, generators/PHSartre/PHSartreParticleTrigger.h, generators/PHSartre/README, generators/PHSartre/autogen.sh, generators/PHSartre/configure.ac, generators/PHSartre/sartre.cfg, generators/PHSartre/sartreRuncard_pAu_Au_emits.txt, generators/PHSartre/sartreRuncard_pAu_p_emits.txt
PHSartre is a wrapper for the Sartre 1.20 event generator for diffractive and UPC events. It works in much the same way as the PHPythia event generators, and the event output is in HepMC format, suitable for the sPHENIX G4 simulations. The event generator includes a generator level trigger interface and a simple particle trigger. 
(Sartre itself and the root upgrades required have been previously installed by @pinkenburg  - thanks Chris!)
=> Add PHSartre Diffractive/UPC Event Generator

simulation/g4simulation/g4hough/PHG4KalmanPatRec.C
This is a quick fix for high eta tracks. Some high eta tracks used more than 11 bits in current grid bin size, so make the bins coarser.
=> Change default search grid bin size for high eta tracks

simulation/g4simulation/g4cemc/RawTowerCalibration.cc, simulation/g4simulation/g4cemc/RawTowerCalibration.h
In the 2017 SPACAL design (https://github.com/sPHENIX-Collaboration/coresoftware/pull/300), the fiber density various slightly from block to block, with an up to 10% relative variation. 
To get energy scale consistent between all blocks, a tower-by-tower calibration is introduced, similar to that used in the test beam reconstruction. 
The tower by tower calibration constant is the inverse of the average sampling fraction for 4-GeV photons in the corresponding SPACAL 2x2 block:
- Calibration file: https://github.com/sPHENIX-Collaboration/calibrations/pull/25 
- Macros: https://github.com/sPHENIX-Collaboration/macros/pull/69 
Check cluster energy response of 4-GeV photon in the EMCal is studied in two case as following. Note the lower energy response around eta=0 is related to the assembly …
=> add tower by tower calibration for EMCal

simulation/g4simulation/g4eval/SvtxClusterEval.C, simulation/g4simulation/g4eval/SvtxClusterEval.h, simulation/g4simulation/g4eval/SvtxEvaluator.C, simulation/g4simulation/g4eval/SvtxEvaluator.h, simulation/g4simulation/g4eval/SvtxTrackEval.C, simulation/g4simulation/g4eval/SvtxTrackEval.h, simulation/g4simulation/g4eval/SvtxTruthEval.C
Full matching (not just embedded) now works in central Hijing events.
g4hit + Cluster + track matching executes in 1200 seconds
including the hit matching (not optimized yet) increases the budget to 3800seconds.
In semi central events the CPU usage decreased from 2700sec to 465sec.
Most performance inceases were obtained by presorting the clustermap
in layer and z to reduce the search range and by caching matching results.
A lot of time is spent accessing the clustermap. Access to clusters in the large 
clustermap is apparently quite inefficient.
=> Evaluator CPU Performance Optimization

offline/framework/fun4all/Makefile.am, simulation/g4simulation/g4main/Makefile.am, simulation/g4simulation/g4main/PHG4HitLinkDef.h, simulation/g4simulation/g4main/PHG4LinkDef.h, simulation/g4simulation/g4main/PHG4Reco.cc, simulation/g4simulation/g4main/configure.ac
The mRICH had renamed G4_Pyrex_Glass which broke the ePHENIXRICH. Now the mRICH uses a copy of the G4_Pyrex_Glass for its purpose (it adds some properties so it cannot use the original G4_Pyrex_Glass). There might be an issue with the material copying - that still needs to be looked at but this put the ePHENIXRICH back into business.
=> fixing the ePHENIXRICH

simulation/g4simulation/g4detectors/PHG4CylinderCellTPCReco.cc
just a dumb check on the total number of cells in a given layer. The current default (0.12/0.17) results in 5+M cells in the outer layer, the limit is set to 5.1M
=> limit cellsize in TPC to prevent excessive memory usage

simulation/g4simulation/g4detectors/PHG4BlockSteppingAction.cc, simulation/g4simulation/g4detectors/PHG4BlockSteppingAction.h, simulation/g4simulation/g4detectors/PHG4CylinderSteppingAction.cc, simulation/g4simulation/g4detectors/PHG4CylinderSteppingAction.h, simulation/g4simulation/g4detectors/PHG4InnerHcalSteppingAction.cc, simulation/g4simulation/g4detectors/PHG4OuterHcalSteppingAction.cc
The last round of hijing sims showed that those impossible step status combinations also occur in the cylinder. This pull request adds those protections. It also gives now a printout if an impossible (but handled) stepping action is seen to get an idea how frequent they are and that we can reproduce them to show this at some time to the G4 developers
=> propagate stepping action fixes from the hcal to the cylinder and block stepping action

simulation/g4simulation/g4detectors/PHG4SiliconTrackerCellReco.cc, simulation/g4simulation/g4detectors/PHG4SiliconTrackerSteppingAction.cc, simulation/g4simulation/g4hough/PHG4SvtxClusterizer.C
Fixed a bug in PHG4SiliconTrackerCellReco due to the celllist key not being unique between layers. G4 hits from different layers would be added together in one cell in high multiplicity events. Added the layer number to the key.
In PHG4SiliconTrackerSteppingAction, if the prePoint step status is "fUndefined" sometimes G4 returns the copy number for the strip volume from the last call to the stepping action. That is generally an unrelated strip, and so the strip address is recorded in the hit incorrectly, leading to the cluster being in the wrong place. Added a check for this and a calculation of the strip address from the entry position in the sensor.
Added a lot of diagnostic output that can be turned on by verbosity settings, allowing a fairly complete sanity check of the whole chain …
=> Intt stepping bug fix

offline/packages/PHGeometry/macros/PHGeom_DSTInspection.C, simulation/g4simulation/g4detectors/PHG4FullProjSpacalDetector.cc, simulation/g4simulation/g4detectors/PHG4FullProjTiltedSpacalDetector.cc, simulation/g4simulation/g4detectors/PHG4SpacalDetector.cc
Following discussion of today's simulation meeting on #341, disabling the geometry export for EMCal blocks and wall volumes. In the current Geant4->GDML->ROOT TGeo export/import chain, the SPACAL blocks was not properly translated and is placed overlapping active volumes of tracking detectors. 
@HaiwangYu : please cross check
=> Disable geometry export for EMCal blocks and wall volumes

simulation/g4simulation/g4main/PHG4Reco.cc
When using a material copy one has to initialize the state (solid, liquid, gas) - the default used in the G4Material ctor (kStateUndefined) leads to the use of uninitialized vars in some initialisation calculation (not sure what else an undefined state does).  Now all parameters are taken from the original material. Filed a bug report with G4 about this behavior
=> fix use of uninitialized variable in density calculation for new material

simulation/g4simulation/g4hough/PHG4GenFitTrackProjection.C
Thanks for the feedback from Sasha L. and John. L.
Found a major bug in the projection module.
The `genfit::StateOnPlane` for the projection was initialized with wrong pz = 0 GeV
Fixed it in this pull request.
Tested with e-, pT = 1 GeV/c, |vtx_z| < 5cm, eta = 0.8.
matching deta:
matching dphi:
electron EMCal3X3/pT
=> Bug fix for PHG4GenFitTrackProjection

offline/packages/PHField/PHFieldConfig_v1.h, offline/packages/PHField/PHFieldConfig_v2.h
Thanks to @dvperepelitsa for the check, the DST object for field map is missing the default constructor, which is necessary for ROOT file read back. Added into this pull request.
=> Hot-fix on field setting storage objects

offline/packages/PHGenFitPkg/GenFitExp/Field.cc
Thanks @adfrawley for cross check the result of #349 , in which he found worse Upsilon resolution over full acceptance. This problem was traced to worsening resolution in the higher psuedorapidity regions. And it was finally traced to units consistency issue of field map wrapper for GenFit. GenFit used cm-kG units, while ```PHField``` used ```CLHEP``` units to max Geant4-use speed. The length unit translation at this stage was missed in #349 
This was fixed in this pull request. Tested with muons in |eta|<1 and the overall resolution is slightly improved when compared to before #349 and slightly more tracks were found. 
Request @adfrawley to test this setup again after today's build around 1PM.
=> Hot-Fix 2: fix the unit in field wrapper for GenFit

offline/packages/PHGenFitPkg/PHGenFit/Track.cc
During HIJING-embedded tracking production, Chris found GenFit fitter generates uncatched errors, which would force Fun4AllServer to quit. This is one attempt to catch these kind of errors: when Kalman fitter could not find a valid charge, set the track charge to NAN.
=> Catch possible throws that could force reconstruction to abort

simulation/g4simulation/g4hough/PHG4HoughTransform.C
Another quick fix to avoid crashes from the old version of track propagation toolset.
=> Fix crash if no valid state was found

offline/QA/modules/QAG4SimulationJet.C, simulation/g4simulation/g4detectors/PHG4ForwardEcalSteppingAction.cc, simulation/g4simulation/g4detectors/PHG4ForwardHcalSteppingAction.cc, simulation/g4simulation/g4detectors/PHG4InnerHcalSteppingAction.cc, simulation/g4simulation/g4detectors/PHG4OuterHcalSteppingAction.cc, simulation/g4simulation/g4detectors/PHG4PSTOFSteppingAction.cc, simulation/g4simulation/g4detectors/PHG4Prototype2InnerHcalSteppingAction.cc, simulation/g4simulation/g4detectors/PHG4Prototype2OuterHcalSteppingAction.cc, simulation/g4simulation/g4detectors/PHG4SiliconTrackerSteppingAction.cc, simulation/g4simulation/g4detectors/PHG4SpacalPrototypeSteppingAction.cc, simulation/g4simulation/g4detectors/PHG4SpacalSteppingAction.cc
From QAing of the last jet production, we found the absorber truth energy contribution is missing during the simulation truth tracing. This problem was traced to multiple mismatch between ```hitcontainer->AddHit()``` and ```PHG4Shower::add_g4hit_id()```. They are corrected in this pull request.
=> Fix shower hit index in stepping actions

simulation/g4simulation/g4cemc/RawTowerBuilder.cc, simulation/g4simulation/g4detectors/PHG4FullProjSpacalCellReco.cc
During pi0/photon analysis, Alexander Bazilevsky found unexpected variation in SPACAL tower-to-tower spacing as reported by geometry node ```RUN/TOWERGEOM_CEMC```
This problem was traced to the calculation error in the tower position reporting, which is corrected in this pull request. 
The corrected tower size and spacing in psudorapidity is checked here. Note the non-zero spacing between towers when they are not belong to the same 2x2 block, and the larger spacing between two EMCal half sectors at the center.
=> Correct SPACAL tower eta position reporting

simulation/g4simulation/g4jets/TowerJetInput.C
During a jet reco test with Raghav Elayavalli, we noticed the jet finder will discard tower input silently if missing the necessary global vertex node. Vertex is used to convert tower coordinate into eta for FastJet. The default behavior of discarding tower silently prevents users from identifying the source of the problem. 
This pull request is a quick update that make the global vertex node a requirement for TowerJets to be processed. Otherwise, the reconstruction aborts with an error message about how to recover the vertex node.
=> Abort reconstruction is missing vertex during tower-jet reco

simulation/g4simulation/g4detectors/Makefile.am, simulation/g4simulation/g4detectors/PHG4InnerHcalDetector.cc, simulation/g4simulation/g4detectors/PHG4InnerHcalDetector.h, simulation/g4simulation/g4detectors/PHG4InnerHcalSteppingAction.cc, simulation/g4simulation/g4detectors/PHG4InnerHcalSubsystem.cc, simulation/g4simulation/g4detectors/PHG4InnerHcalSubsystem.h, simulation/g4simulation/g4detectors/PHG4OuterHcalDetector.cc, simulation/g4simulation/g4detectors/PHG4OuterHcalDetector.h, simulation/g4simulation/g4detectors/PHG4OuterHcalSteppingAction.cc, simulation/g4simulation/g4detectors/PHG4OuterHcalSubsystem.cc, simulation/g4simulation/g4detectors/PHG4OuterHcalSubsystem.h
The hcal implementation used the envelope as inner/outer radius rather than the actual radii from the engineering drawings. The defaults were adjusted to reflect the radii from the drawings. The scintillators are also shorter which is now properly implemented. Material scan for the old inner hcal:
new inner hcal:
shows a reduction of the interaction length by about 20%. The material scan for the old outer hcal
and the new outer hcal:
shows negligent differences
=> Hcal size changes

simulation/g4simulation/g4detectors/PHG4InnerHcalDetector.cc, simulation/g4simulation/g4detectors/PHG4InnerHcalSubsystem.cc, simulation/g4simulation/g4detectors/PHG4OuterHcalDetector.cc, simulation/g4simulation/g4detectors/PHG4OuterHcalSubsystem.cc
I switched the default from 4 crossings (not 5 for the outer hcal - sorry about that) to the tilt angle from the engineering drawings. The differences are minute (the vertical line is a geantino, the yellow dots show the points where it enters a new volume):
outer hcal with 4 crossings (-11.7826 deg):
outer hcal using -11.23 deg from drawings:
inner hcal with 4 crossings (35.5497 deg):
inner hcal using 36.15 deg from drawings:
=> Hcal tilt angle default set to engineering drawings

simulation/g4simulation/g4detectors/PHG4CylinderGeom_Spacalv3.cc, simulation/g4simulation/g4detectors/PHG4CylinderGeom_Spacalv3.h, simulation/g4simulation/g4detectors/PHG4FullProjTiltedSpacalDetector.cc, simulation/g4simulation/g4detectors/PHG4SpacalSubsystem.cc
During the EMCal meeting ( https://indico.bnl.gov/conferenceDisplay.py?confId=3577 ) , we need to answer a design decision regarding whether to place block dividers in EMCal active volume to assist assembly. If so, what would be the optimal material: Stainless steel or carbon/glass fiber type of materials. 
This pull request allow us to perform simulation to reach a conclusion quantitatively.  The default behavior is no block divider which is the setting for the current reference design. 
Similar to the engineering design, 15 mil divider space is inserted into between EMCal block rows: 
* User can turn ON/OFF via macro by setting parameter ```divider_width``` to a positive value. Suggested width is 14.5 cm. Default is OFF with width of 0 cm, until the EMCal group finalize the decision on …
=> Allow inserting block dividers in EMCal active volume

generators/PHPythia8/PHPy8JetTrigger.C, generators/PHPythia8/PHPy8JetTrigger.h
Add the ability to select the minimum Z of the leading particle in a jet. Very useful for generating an enhanced sample of high-Z jets for study.
=> Add minimum leading particle z to trigger

simulation/g4simulation/g4eval/SvtxEvaluator.C, simulation/g4simulation/g4hough/PHG4TrackKalmanFitter.C, simulation/g4simulation/g4hough/PHG4TrackKalmanFitter.h
Add dca3dz, dca3dzsigma to the `SvtxEvaluator` for convenience.
dca3d is calculated using PCA with regarding to the reconstructed vertex.
So this is related to pull request [356](https://github.com/sPHENIX-Collaboration/coresoftware/pull/356)
dca2d is calculated using PCA with regarding to a line parallel to beam pipe and through the reconstructed vertex. (line x=vx, y=vy)
=> Add dca3dz, dca3dzsigma

simulation/g4simulation/g4detectors/PHG4InnerHcalSubsystem.cc, simulation/g4simulation/g4detectors/PHG4OuterHcalSubsystem.cc, simulation/g4simulation/g4tpc/PHG4TPCDetector.cc, simulation/g4simulation/g4tpc/PHG4TPCDetector.h, simulation/g4simulation/g4tpc/PHG4TPCSteppingAction.cc, simulation/g4simulation/g4tpc/PHG4TPCSubsystem.cc, simulation/g4simulation/g4tpc/PHG4TPCSubsystem.h
A scan with geantinos showed that the scintillator for the inner hcal is too short (typo in scintillator radius). But even after fixing this it is too short by by 0.4mm. For the outer hcal it is 0.1mm. It doesn't really matter but while I was at it I might as well fix this by tweaking the scintillator radius. There must be somewhere a small math issue in the geometry code. Here are the entry and exit hit distributions for scintillators and absorbers. Inner hcal before this patch:
after:
Outer hcal before:
after:
=> Hcal scintillator size fine adjustment

generators/phhepmc/Makefile.am
not sure why this worked under SL6
=> fix typo which prevents compilation under SL7

simulation/g4simulation/g4main/PHG4TruthInfoContainer.cc, simulation/g4simulation/g4main/PHG4TruthInfoContainer.h
Thanks @adfrawley for checking #364 , which showed low overall tracking efficiency for the pile up simulations. This problem was traced to a pile up vertex would be used as the primary vertex in the truth container, and thereafter used as source of the vertex seed during the pattern recognition stage. 
In the current code base, ```PHG4TruthInfoContainer::GetPrimaryVertexIndex()``` depends on the order of tracks simulated by Geant4. This pull request introduce an explicit definition that ```PHG4TruthInfoContainer::GetPrimaryVertexIndex()``` return the primary vertex with highest embedding ID which is usually used for the signal sub-event. 
Small scale test showed reasonable tracking efficiency with multiple Au+Au pile up simulations. Further test welcomed.
=> Use an explicit definition of primary in the truth information

simulation/g4simulation/g4detectors/PHG4FullProjTiltedSpacalDetector.cc, simulation/g4simulation/g4detectors/PHG4SpacalSteppingAction.cc
Thanks @jdosbo for studying the effect of SPACAL block divider  with https://github.com/sPHENIX-Collaboration/coresoftware/pull/365 . During this process, we found it necessary to explicitly check the shower energy deposition in the divider to ensure the simulation is properly setup. This pull request would allow us to do it. 
For hits on the dividers, the divider ID is encoded in the  ```scint_id``` variable of the result ```PHG4Hit``` on the ```DST/G4HIT_ABSORBER_CEMC``` node. Here is how to read it out interactively:
1. enable ```do_DSTReader = true``` in ```Fun4All_G4_sPHENIX.C```
2. open the result DST reader TTree: ```root G4sPHENIX.root_DSTReader.root```
3. Then interactively on ROOT command line, we can check the hits on the divider: 
```c++
// whether a hit is on the divider …
```
=> Tag hits in SPACAL support structure for debug purpose

generators/phhepmc/Fun4AllHepMCOutputManager.cc, generators/phhepmc/Fun4AllHepMCOutputManager.h
This is another follow up to https://github.com/sPHENIX-Collaboration/coresoftware/pull/364 to revive ```Fun4AllHepMCOutputManager```.
@sookhyun and Sanghoon have been testing p+p embedding and need a hepMC p+p pythia event for embedding stream input. This pull request revive the ```Fun4AllHepMCOutputManager```, which can be used in another Fun4All cycle to save PHPythia output to HepMC file for later use in embedding. 
* Example macro to generate MB hepMC file: https://github.com/blackcathj/macros/blob/pythia_MB_HepMC_Output/macros/g4simulations/Fun4All_PythiaHepMC.C
* Example macro to do p+p pile up simulation: https://github.com/blackcathj/macros/blob/pythia_MB_HepMC_Output/macros/g4simulations/Fun4All_G4_sPHENIX.C
=> Revive Fun4AllHepMCOutputManager

simulation/g4simulation/g4eval/SvtxClusterEval.C
Thanks @jdosbo for the cross check, who found https://github.com/sPHENIX-Collaboration/coresoftware/pull/373 leads to crashes in events of low multiplicity in the trackers. That is related to a missing of member existence check in a buffer map. This pull request fixes this problem. Welcome further checks.
=> Tracking evaluator bug fix

simulation/g4simulation/g4detectors/PHG4MapsDetector.cc
Fix a concern raised by @pinkenburg and @adfrawley . Connection to CERN server, required by MAPS GDML schema validation, sometimes leads to job fails. Disabling it.
=> Disable validation for GDML schema, which require remote connection to CERN server

offline/framework/fun4all/Fun4AllServer.cc, simulation/g4simulation/g4main/Makefile.am, simulation/g4simulation/g4main/PHG4LinkDef.h, simulation/g4simulation/g4main/PHG4Reco.cc, simulation/g4simulation/g4main/PHG4Reco.h, simulation/g4simulation/g4tpc/PHG4TPCDetector.cc
According to Alice test beam results the PAI model gives a better description of the ionization than the standard Urban model. 
What is more important for us is that the dEdx from PAI is less dependent on the Geant4 Step Size:
(yes these plots also show that we have to be careful not to use too small steps). The PAI model is activated for a G4Region (REGION_TPCGAS) which is used by the tpc gas volume. The code is only active for the new G4 version 10.03.p03, there are no changes affecting our current version PAI has changed, backporting this to G4 10.02 would require some validation). 
While at it I changed the default physics list to FTFP_BERT for the new G4 version.
Some minor bugfixes (spawning the g4 menu in a separate window works again, and one can actually issue commands from it) …
=> use of PAI (PhotoAbsorption Ionization) model for tpc gas, use FTFP_BERT for G4 10.03.p03

offline/framework/fun4all/Fun4AllServer.cc, simulation/g4simulation/g4main/Makefile.am, simulation/g4simulation/g4main/PHG4LinkDef.h, simulation/g4simulation/g4main/PHG4Reco.cc, simulation/g4simulation/g4main/PHG4Reco.h, simulation/g4simulation/g4tpc/PHG4TPCDetector.cc
Previously the EmSaturation was created on the fly by a call from the stepping action which probably wreaked havoc when running multi threaded. The initialization has now occur before putting G4 into running mode. A simple call to EmSaturation still does the job but it has to be done at startup
=> EmSaturation needs to be initialized at startup

simulation/g4simulation/g4detectors/Makefile.am, simulation/g4simulation/g4detectors/PHG4Cell.h, simulation/g4simulation/g4detectors/PHG4Cellv1.cc, simulation/g4simulation/g4detectors/PHG4Cellv1.h, simulation/g4simulation/g4detectors/PHG4Cellv2.cc, simulation/g4simulation/g4detectors/PHG4Cellv2.h, simulation/g4simulation/g4detectors/PHG4Cellv2LinkDef.h, simulation/g4simulation/g4detectors/PHG4CylinderCellTPCReco.cc, simulation/g4simulation/g4hough/SvtxHit.h, simulation/g4simulation/g4hough/SvtxHit_v1.h
@adfrawley pointed out the full pile up simulation pushed our memory usage to the 22 GB condor limit, which significantly limited our capability to evaluate the performance dependency on the event occupancy. 
This pull request represent an effort to reduce the memory usage. A memory profiling showed the majority memory is used by the TPC hits and cells. These objects represent non-zero ADC bins in the TPC, which are 10x-100x the number of PHG4Hits (ionizing hit per layer) in the TPC. Therefore, this pull request focuses on strip down the Hits/cells, in particular for those used by TPC: 
* Reduce the base class for ```PHG4Cell``` and ```SvtxHit``` from ```PHObject``` to ```TObject```. They do not have to be on the Node Tree directly, therefore, not needing the 2x4 B data members in …
=> Memory saver for TPC cells by more than half

simulation/g4simulation/g4main/PHG4TruthInfoContainer.cc
Primary vertex in the truth information is used for the fast simulation of BBC and the current place-holder for the vertex seeding. After the implementation of the pile up tool chain, the primary vertex is defined as the first vertex with highest embedding ID as in #372. 
However, as Sanghoon find out, in the Pythia-8 event simulations, the collision vertex is saved to the last vertex in the truth container, and the first vertex is usually a decay vertex which leads to low track seeding efficiency. Therefore, this pull request change the primary vertex definition to the last vertex with the highest embedding ID. 
Tested with few Pythia-8 B-jet events. Looks working fine.
=> Update the definition of primary vertex in the truth information

offline/framework/fun4all/Fun4AllDstInputManager.cc, offline/framework/fun4all/Fun4AllDstInputManager.h, offline/framework/fun4all/Fun4AllDstOutputManager.cc, offline/framework/fun4all/Fun4AllDstOutputManager.h, offline/framework/fun4all/Fun4AllOutputManager.cc, offline/framework/fun4all/Fun4AllOutputManager.h, offline/framework/phool/Makefile.am, offline/framework/phool/PHNodeIOManager.cc, offline/framework/phool/PHNodeIOManager.h, offline/framework/phool/PHNodeIntegrate.cc, offline/framework/phool/PHNodeIntegrate.h, offline/framework/phool/PHNodeReset.cc, offline/framework/phool/PHObject.cc, offline/framework/phool/PHObject.h
This pull request adds the capability to integrate objects which are stored under the Run Node when reading multiple input files. These objects have to implement the following methods:
int Integrate() const {return 1;} // just a flag that this object wants to take part in this
int Integrate(PHObject *obj); 
void CopyContent(PHObject *obj);
The Integrate(PHObject *) method does the actual summing - it is called by the summed object, the result is stored locally in the respective DstInputManager. The CopyContent() method is needed to copy the content of the local summed object to the object under the node tree. This approach should give us the most flexibility when it comes to reading multiple input files in parallel while also dealing with changing versions of the stored objects (the worst …
=> support of summing objects from multiple input files under the Run Node

offline/framework/phool/PHRandomSeed.cc, offline/framework/phool/PHRandomSeed.h, simulation/g4simulation/g4main/PHG4ParticleGeneratorBase.cc, simulation/g4simulation/g4main/PHG4Reco.cc
This PR maximizes entropy by always returning a value from rdev rather than a uniform distribution initialized by a single seed. With PHRandomSeed::LoadSeed(unsigned int) seeds can be preloaded to reproduce any sequence. If the RANDOMSEED flag is set, it still uses this seed to initialize a uniform random number distribution.
It prints out the random seeds so a script can pull the seeds from a log file to recover the sequence. It is not necessary anymore for consumers to print out the seed themselves
=> Random generator cleanup

generators/PHPythia8/PHPythia8.C, generators/PHPythia8/PHPythia8.h, generators/phhepmc/Makefile.am, generators/phhepmc/PHGenIntegral.cc, generators/phhepmc/PHGenIntegral.h, generators/phhepmc/PHGenIntegralLinkDef.h, generators/phhepmc/PHGenIntegralv1.cc, generators/phhepmc/PHGenIntegralv1.h, generators/phhepmc/PHGenIntegralv1LinkDef.h, offline/framework/fun4all/Fun4AllDstInputManager.cc, offline/framework/fun4all/Fun4AllDstOutputManager.cc, offline/framework/phool/PHNodeIntegrate.h
Following framework update in #387 , revive PR #378 to store integrated quantities from Pythia8 event generator, including integrated luminosity and events. The integrated luminosity will be summed automatically when multiple DST files are analyzed. 
Pythia8 simulation will produce the following nodes on the node tree:
```
List of Nodes in Fun4AllServer:
Node Tree under TopNode TOP
TOP (PHCompositeNode)/
DST (PHCompositeNode)/
.....
RUN (PHCompositeNode)/
PHGenIntegral (IO,PHGenIntegralv1)    <- the new node
....
```
And at the end of processing, print out the content in this node, e.g.:
```
*-------  PYTHIA Event and Cross Section Statistics  -------------------------------------------------------------*
| …
```
=> Try2: Integrated luminosity for normalization

simulation/g4simulation/g4detectors/PHG4CylinderCellTPCReco.cc, simulation/g4simulation/g4detectors/PHG4CylinderCellTPCReco.h
The version defaults to the prior version of the avalanche-induced charge spread, but adds the capability to change this parameter at the macro level.  This change may be implemented without effect to users code.
=> Allow the avalanche smear to be externally changed.

offline/packages/trigger/CaloTriggerInfo.h, offline/packages/trigger/CaloTriggerInfo_v1.C, offline/packages/trigger/CaloTriggerInfo_v1.h, offline/packages/trigger/CaloTriggerSim.C, offline/packages/trigger/CaloTriggerSim.h
Determine and save the second-highest-energy EM 4x4 window for Upsilon di-electron trigger studies. Also add option to implement 8-bit ADC truncation of EM 2x2 window energies.
=> Additional functionality for trigger simulation studies

offline/packages/jetbackground/CopyAndSubtractJets.C, offline/packages/jetbackground/CopyAndSubtractJets.h, offline/packages/jetbackground/CopyAndSubtractJetsLinkDef.h, offline/packages/jetbackground/DetermineTowerBackground.C, offline/packages/jetbackground/Makefile.am, offline/packages/jetbackground/SubtractTowers.C, simulation/g4simulation/g4jets/Jet.h, simulation/g4simulation/g4jets/TowerJetInput.C
These changes implement the second iterative step (really the first of the two steps in the sequence) in the UE background determination as described in nucl-ex/1203.1353 . (Note that the commensurate reconstruction macro will be updated separately in the macros repository.)
Summary of major changes: 
* The DetermineBackground module now implements an additional possible seed definition, which is based on the discriminant D (max tower ET / mean tower ET) > 3 within R=0.2 jets initially reconstructed without any subtraction. I've also lowered the minimum pT cut (from 25 GeV to 15 GeV) on jets entering as seeds in the second iteration, since their kinematics will now reflect the first UE subtraction iteration.
*  The core TowerJet reconstruction code now needs another possible tower input …
=> Implementation of second iterative step for UE background determination.

simulation/g4simulation/g4cemc/BEmcCluster.cc, simulation/g4simulation/g4cemc/BEmcCluster.h, simulation/g4simulation/g4cemc/BEmcRec.cc, simulation/g4simulation/g4cemc/RawCluster.h, simulation/g4simulation/g4cemc/RawClusterBuilderv1.cc, simulation/g4simulation/g4cemc/RawClusterv1.cc, simulation/g4simulation/g4cemc/RawClusterv1.h
* RawCluster.h,cc:
New filed "ecore" and corresponding get and set functions
* BEmcRec.cc:
New shower profile parameters and other minor modifications (more clear error message if cluster is too large ... I'll remove this limitation later)
* BEmcCluster.h,cc:
Change output data format in GetPeaks(): from fixed size array to vector
Introduce GetECoreCorrected()
Increase parameter fgMaxNofPeaks to make sure clustering will go on even for very large clusters
Tune ECore for sPHENIX
Other minor modifications
RawClusterBuilder.cc
AbortEvent on clustering error with proper message
Set default tower threshold of 20MeV - looks safe even for central HI collisions
Some more modification related to changes in BEmcCluster.h(cc), RawCluster.h(cc)
=> Modifications in PHENIX-style Clustering

simulation/g4simulation/g4eval/SvtxEvaluator.C
- Introduce new variables to analyze multiple vertices from out-of-time events
- gembed (embedding ID), gnembed (number of embedded events), gntracksmaps (number of tracks within MAPS acceptance and pT > 0.5)
=> ntp_vertex update to analyze multiple vertices from pile-up events

offline/database/PHParameter/PHParameters.cc, simulation/g4simulation/g4detectors/PHG4Parameters.cc
coverity flagged this as an error. The code does what it is supposed to but the construct is a bit misleading. This makes it more explicit that we are checking if the substring starts at position 0
=> fix coverity complaint (the code is valid but unclear what it is up to)

offline/packages/CaloReco/BEmcCluster.cc, offline/packages/CaloReco/BEmcCluster.h, offline/packages/CaloReco/BEmcRec.cc, offline/packages/CaloReco/BEmcRec.h
Modifications to address two goals: 
1. Introduce bCYL flag in BEmcRec to switch between cylindrical and planar geometries (needed e.g. for forward calorimeter). The default value is true (for cylindrical geometry); the switch to planar geometry use BEmcRec::SetPlaneGeometry()
2. Remove the maximal cluster size limitation (now it can deal with any cluster size); despite that is was large anyway (half of the calorimeter size in phi), I removed this limitation properly correcting the code
The modifications should not affect any existing codes in any way.
=> Calorimeter Clustering: switch between cylindrical and plane geometries; remove the cluster size limitation

simulation/g4simulation/g4detectors/PHG4CylinderCellTPCReco.cc, simulation/g4simulation/g4detectors/PHG4CylinderCellTPCReco.h, simulation/g4simulation/g4hough/PHG4TPCClusterizer.C
New version of PHG4CylinderCellTPCReco that provides a zigzag pad readout for the TPC as the default. Optionally, rectangular pads can be used instead by putting in the tracking macro:
(PHG4CylinderCellTPCReco* svtx_cells = .........)
bool use_zigzag_pads = false;
svtx_cells->setZigzags(use_zigzag_pads);  
I will make a presentation at the February 27 simulations meeting showing some test results.
=> New zigzag pads

offline/packages/Prototype4/CaloCalibration.C, offline/packages/Prototype4/CaloCalibration.h, offline/packages/Prototype4/PROTOTYPE4_FEM.C, offline/packages/Prototype4/PROTOTYPE4_FEM.h, offline/packages/Prototype4/RawTower_Prototype4.cc, offline/packages/Prototype4/RawTower_Prototype4.h
Accumulated update on 2018 test beam analysis:
* Introduce global ADC-time-series fit constraints following suggestions from Edward Kistenev 
* Further ADC-time-series fit tunings
* Introducing simple peak finding as energy for non-shaped signals (VETO, Cherenkovs)
Getting ready to migrate from test productions to official productions. 
Also building analysis modules and macros under https://github.com/sPHENIX-Collaboration/analysis/tree/master/Prototype4/  . Tutorials and examples to come soon too.
=> Accumulated update on 2018 test beam analysis

simulation/g4simulation/g4hough/PHG4KalmanPatRec.C, simulation/g4simulation/g4hough/PHG4KalmanPatRec.h
Previously a bug in the initialization of the seeding geometry caused the iterative approach to detonate when taking out some of the detector layers in front of the TPC. Fixed now.
=> Fix to enable iterative tracking without maps or intt

offline/packages/CaloReco/BEmcCluster.cc, offline/packages/CaloReco/BEmcCluster.h, offline/packages/CaloReco/BEmcRec.cc, offline/packages/CaloReco/BEmcRec.h, offline/packages/CaloReco/BEmcRecCEMC.cc, offline/packages/CaloReco/BEmcRecCEMC.h, offline/packages/CaloReco/BEmcRecFEMC.cc, offline/packages/CaloReco/BEmcRecFEMC.h, offline/packages/CaloReco/Makefile.am, offline/packages/CaloReco/RawClusterBuilderTemplate.cc, offline/packages/CaloReco/RawClusterBuilderTemplate.h, offline/packages/CaloReco/RawClusterBuilderTemplateFEMC.cc, offline/packages/CaloReco/RawClusterBuilderTemplateFEMC.h, offline/packages/CaloReco/RawClusterBuilderTemplateFEMCLinkDef.h
Modification made to allow PHENIX-style clustering for FEMC
1. RawClusterBuilderTemplateFEMC is introduced, which should be called from G4_FEMC.C::FEMC_Clusters() instead of RawClusterBuilderFwd: 
RawClusterBuilderTemplateFEMC *ClusterBuilder = new RawClusterBuilderTemplateFEMC("EmcRawClusterBuilderTemplateFEMC");
ClusterBuilder->Detector("FEMC");
ClusterBuilder->Verbosity(verbosity);
se->registerSubsystem(ClusterBuilder);
2. BEmcRec is now a base class, from which BEmcRecCEMC and BEmcRecFEMC inherit base functionality and contains EMCal specific descriptions; RawClusterBuilderTemplate is now for CEMC, therefore it calls BEmcRecCEMC (while RawClusterBuilderTemplateFEMC calls BEmcRecFEMC)
3. Some minor (mainly stylish) modifications in BEmcCluster
4. FEMC clustering outputs a fully …
=> Clusterizer

simulation/g4simulation/g4hough/PHG4KalmanPatRec.C, simulation/g4simulation/g4hough/PHG4KalmanPatRec.h
New seeding scheme and fitter change for KalmanPatRec speed up the track reconstruction time by a big factor. 
For a detailed description of the effect of the changes check the CPU performance presentation in the Tracking meeting: https://indico.bnl.gov/event/4518/
=> New seeding scheme and fitter change for KalmanPatRec

simulation/g4simulation/g4eval/CaloEvaluator.C
Thanks to Jinlong Zhang for pointing out a warning message from the evaluation module of the forward caloriemters, which can not access the tower eta/phi row centers as they are only meaningful for the cylindrical calorimeters. 
Fixed this error for forward calorimeter by using more generic tower-by-tower geometry objects to access the tower eta and phi coordinates.
=> Tower-by-tower geometry for forward calorimeter evaluation

generators/flowAfterburner/main.cc, generators/flowAfterburner/test.cc
boost/property_tree/ptree.hpp still shadows variable, and new - an unused parameter warning
backward compatible
=> suppress warnings for new boost version

simulation/g4simulation/g4detectors/PHG4InnerHcalDetector.cc, simulation/g4simulation/g4detectors/PHG4InnerHcalDetector.h, simulation/g4simulation/g4detectors/PHG4InnerHcalSteppingAction.cc, simulation/g4simulation/g4detectors/PHG4InnerHcalSteppingAction.h, simulation/g4simulation/g4detectors/PHG4InnerHcalSubsystem.cc, simulation/g4simulation/g4detectors/PHG4InnerHcalSubsystem.h, simulation/g4simulation/g4detectors/PHG4Prototype3InnerHcalSteppingAction.cc, simulation/g4simulation/g4detectors/PHG4Prototype3InnerHcalSteppingAction.h, simulation/g4simulation/g4tpc/PHG4TPCElectronDrift.h
small speedup by not decoding volume name in stepping action (now a map filled in PHG4InnerHcalDetector provides a lookup for the layer/tower id). Apply coding convention, clean up code - use light correction from base class
=> Inner Hcal speedup

offline/packages/mvtx/Makefile.am
the dependency on libg4detectors crashed the build (in the build order this package came before g4detectors). This dependency is not needed (as are most of the others). The only one needed is the dependency on libtrack_io from trackbase for this to build and link
=> clean up lib dependencies in offline/packages/mvtx/MakeFile.am

simulation/g4simulation/g4detectors/PHG4ProjCrystalCalorimeterDetector.h
Previously the projective EEMC crashed the default Fun4All_G4_EICDetector.C because a calibration file could not be properly read in. This PR just adds this function and sets a global variable so that the calibration file can be properly read in.
=> Added function to fix projectivity problem

offline/database/pdbcal/base/PdbBankListIterator.h, offline/framework/phool/PHPointerListIterator.h, simulation/g4simulation/g4hough/PHG4TPCClusterizer.C, simulation/g4simulation/g4hough/PHG4TPCClusterizer.h
The interface of a method in TSpectrum has changed (double instead of float which makes sense - we should get away from using floats, there is no advantage to that except in i/o objects to reduce output file size). rootcling does not understand C++11 == delete, going back to previous use of protecte/private ctors. Changes do not affect results
=> compile with root6 while keeping backward compatibility with root5

simulation/g4simulation/g4hough/PHG4TrackFastSim.C, simulation/g4simulation/g4hough/PHG4TrackFastSim.h
fasttrack can work at unison with vertical/cylindrical detectors using different resolutions and efficiencies. Mod was needed to do tracking with EIC detectors at forward-central rapidities.
macros will be uploaded too
[res.pdf](https://github.com/sPHENIX-Collaboration/coresoftware/files/2128100/res.pdf)
[eff.pdf](https://github.com/sPHENIX-Collaboration/coresoftware/files/2128098/eff.pdf)
=> adding support for fast tracking EIC using different detector responses at forward+central stations

simulation/g4simulation/g4main/Makefile.am, simulation/g4simulation/g4main/PHG4LinkDef.h, simulation/g4simulation/g4main/PHG4Reco.cc, simulation/g4simulation/g4main/PHG4Reco.h, simulation/g4simulation/g4main/PHG4ScoringManager.cc, simulation/g4simulation/g4main/PHG4ScoringManager.h
`Geant4` tool kit has a built in tool, `G4ScoringManager`, to record radiation dose and fluence by analyzing passage and interaction of particle tracks with user defined x-y-z or cylindrical meshed volumes. 
This pull request introduce interface to `G4ScoringManager`, configuring it to run with full sPHENIX/EIC simulation and record the result for further analysis. 
In addition, related updates include:
* Added a switch to disable stepping actions with `PHG4Reco::setDisableSteppingActions()`. Stepping action produce the `PHG4Hits` which interface to the rest of Fun4All based analysis. Disabling it make dose focused simulation run much faster and use smaller memory foot print. 
* Example macro to drive the dose simulation: https://github.com/blackcathj/macros/blob/dose_tests/macros/g4simula …
=> Introducing radiation dose / fluence recording

simulation/g4simulation/g4detectors/PHG4CylinderGeom_Siladders.cc, simulation/g4simulation/g4detectors/PHG4CylinderGeom_Siladders.h, simulation/g4simulation/g4detectors/PHG4SiliconTrackerCellReco.cc, simulation/g4simulation/g4detectors/PHG4SiliconTrackerDetector.cc, simulation/g4simulation/g4detectors/PHG4SiliconTrackerDetector.h, simulation/g4simulation/g4detectors/PHG4SiliconTrackerParameterisation.cc, simulation/g4simulation/g4detectors/PHG4SiliconTrackerSteppingAction.cc, simulation/g4simulation/g4detectors/PHG4SiliconTrackerSteppingAction.h, simulation/g4simulation/g4detectors/PHG4SiliconTrackerSubsystem.cc, simulation/g4simulation/g4detectors/PHG4SiliconTrackerSubsystem.h, simulation/g4simulation/g4hough/PHG4KalmanPatRec.C, simulation/g4simulation/g4hough/PHG4KalmanPatRec.h
Installed the current design for the INTT in G4. The changes have been tested with 100 pion + Upsilon events, and show little difference in performance from the previous configuration aside from the effect of an additional mass of 4% X_0 in the INTT layers. See the plots below.
No changes to the tracking macro are needed to get the new default configuration (vertical strips in layer 0, horizontal strips in layers 1-3). Once this pull request is merged, I will commit changes to the tracking macro that show how to modify the INTT configuration. 
[ups1s_100pions_newINTT.pdf](https://github.com/sPHENIX-Collaboration/coresoftware/files/2272788/ups1s_100pions_newINTT.pdf)
[eff_newINTT.pdf](https://github.com/sPHENIX-Collaboration/coresoftware/files/2272789/eff_newINTT.pdf) …
=> New intt configuration

simulation/g4simulation/g4detectors/PHG4CylinderGeom_Siladders.cc, simulation/g4simulation/g4detectors/PHG4CylinderGeom_Siladders.h, simulation/g4simulation/g4detectors/PHG4SiliconTrackerCellReco.cc, simulation/g4simulation/g4detectors/PHG4SiliconTrackerDetector.cc, simulation/g4simulation/g4detectors/PHG4SiliconTrackerDetector.h, simulation/g4simulation/g4detectors/PHG4SiliconTrackerParameterisation.cc, simulation/g4simulation/g4detectors/PHG4SiliconTrackerSteppingAction.cc, simulation/g4simulation/g4detectors/PHG4SiliconTrackerSteppingAction.h, simulation/g4simulation/g4detectors/PHG4SiliconTrackerSubsystem.cc, simulation/g4simulation/g4detectors/PHG4SiliconTrackerSubsystem.h, simulation/g4simulation/g4hough/PHG4KalmanPatRec.C, simulation/g4simulation/g4hough/PHG4KalmanPatRec.h, simulation/g4simulation/g4main/PHG4Reco.cc
Built on top of PR #466 (new INTT configuration. Added support structure material inside the acceptance for the INTT and also the MVTX outer shell. All support material description is from discussions with MIckey Chiu/Dan Cacace/Walt Sondheim.
Material included is:
INTT support rails (CFRP)
INTT outer shell (CFRP)
INTT inner shell (CFRP)
MVTX outer shell (Rohacell foam/CFRP)
Note: The MVTX outer shell is built in the INTT detector module for now. Once things are merged, I will move it to the MVTX module.
=> Si support material

simulation/g4simulation/g4detectors/PHG4CylinderGeom_MAPS.cc, simulation/g4simulation/g4detectors/PHG4MapsDetector.cc, simulation/g4simulation/g4detectors/PHG4MapsDetector.h, simulation/g4simulation/g4detectors/PHG4MapsSteppingAction.cc
This pull request updates the stave (or ladder) geometry of the inner MAPS to better conform to the current MVTX proposed geometry.
The bulk of the changes occur in a modified gdml file from which the geometry is read. The updated gdml file is currently located here:
/phenix/hhj3/dcm07e/sPHENIX/macros/macros/g4simulations/mvtx_stave_v01.gdml
The major changes to the gdml file are:
- Renaming volumes to use MVTX rather than ITSU
- File now contains only the geometry for a single stave & support, rather than the full ITS
- Sensor size has been reduced to the correct active area and shifted to the correct position within the chip
- Silicon chip size updated
- Include space between chips
This pull request mainly deals with updating hard-coded values in the various MAPS construction, stepping …
=> Update MVTX Stave Geometry

simulation/g4simulation/g4detectors/PHG4SiliconTrackerDetector.h, simulation/g4simulation/g4hough/Makefile.am, simulation/g4simulation/g4hough/PHG4SiliconTrackerDigitizer.C, simulation/g4simulation/g4hough/PHG4SiliconTrackerDigitizer.h, simulation/g4simulation/g4hough/PHG4SvtxDeadMapLoader.C, simulation/g4simulation/g4hough/PHG4SvtxDeadMapLoader.h, simulation/g4simulation/g4hough/PHG4SvtxDeadMapLoaderLinkDef.h, simulation/g4simulation/g4hough/PHG4SvtxDigitizer.C, simulation/g4simulation/g4hough/PHG4SvtxDigitizer.h, simulation/g4simulation/g4hough/SvtxDeadMap.C, simulation/g4simulation/g4hough/SvtxDeadMap.h, simulation/g4simulation/g4hough/SvtxDeadMapLinkDef.h, simulation/g4simulation/g4hough/SvtxDeadMapv1.C, simulation/g4simulation/g4hough/SvtxDeadMapv1.h, simulation/g4simulation/g4hough/SvtxDeadMapv1LinkDef.h
From Inner detector task force, working on simulating INTT under realistic dead area distributions, which including dead parts and hot channels which is then masked away online or offline.  The dead map is inspired by the experience of forward silicon tracker (FVTX) at PHENIX, whose DAQ is reused for INTT. 
The dead map are defined in calibration repository, read into the DST `RUN` node, applied at the digitization stage of INTT. The same map can also be used in the reconstruction stage for dead-recon and apply to real data. 
Similar approach can be expanded to MAPS and TPC too. 
The predefined dead map for INTT including random dead areas of three categories: 
* dead/masked sensors, e.g. caused by loss of HV/LV, loss of downstream DAQ cables. Later stage of FVTX operation, this was …
=> Introduce pre-defined deadmap for INTT

simulation/g4simulation/g4detectors/Makefile.am, simulation/g4simulation/g4detectors/PHG4DetectorGroupSubsystem.cc, simulation/g4simulation/g4detectors/PHG4DetectorGroupSubsystem.h, simulation/g4simulation/g4detectors/PHG4SiliconTrackerDefs.h, simulation/g4simulation/g4detectors/PHG4SiliconTrackerDetector.cc, simulation/g4simulation/g4detectors/PHG4SiliconTrackerDetector.h, simulation/g4simulation/g4detectors/PHG4SiliconTrackerSteppingAction.cc, simulation/g4simulation/g4detectors/PHG4SiliconTrackerSteppingAction.h, simulation/g4simulation/g4detectors/PHG4SiliconTrackerSubsystem.cc, simulation/g4simulation/g4detectors/PHG4SiliconTrackerSubsystem.h
This pull request implements the capability to change the number of layers consistently (previous version only worked with default 4 layers). It is possible to change the parameters but this version still contains all the problems of the original implementation (one has to use mm when changing double params due to inconsistent application of the units). This pull request reproduces the results from the previous version identically, any bugfixes in the next pull request won't do this. Also changing the internal unit used by the parameters from mm to cm will result in small changes due to different conversions of the input value. Hits from active absorber volumes should also work now (they sort of didn't in the original version)
=> Fix up the Intt

simulation/g4simulation/g4detectors/Makefile.am, simulation/g4simulation/g4detectors/PHG4GDMLDetector.cc, simulation/g4simulation/g4detectors/PHG4GDMLDetector.h, simulation/g4simulation/g4detectors/PHG4GDMLSubsystem.cc, simulation/g4simulation/g4detectors/PHG4GDMLSubsystem.h, simulation/g4simulation/g4detectors/PHG4GDMLSubsystemLinkDef.h, simulation/g4simulation/g4detectors/PHG4HcalDetector.h
Adding a generic detector in Geant4 simulation, which are defined in external GDML files. This module can be used to import mechanical drawing or externally defined detector geometry to be used as part of the Geant4 simulation. Currently, the imported detectors are not active, but it is possible to define an associated stepping action to enable recording the hits. 
Example macros is: https://github.com/blackcathj/macros/blob/dose_PHENIX/macros/g4simulations/Fun4All_G4_sPHENIX.C , which import the whole PHENIX detector into the simulation: 
Top view of a few 10+ GeV pions in the full PHENIX detector:
=> Generic detector from external GDML files

simulation/g4simulation/g4main/PHG4ScoringManager.cc
Just added #if G4VERSION_NUMBER >= 1040 in a few places where the API has changed. The new version actually makes the mean and the rms accessible while the current version only returns a double (mean?). Needs to be tested with Geant4 10.4.p02 where the mean is used in the PHG4ScoringManager
=> Geant4 10.4.p02 changed the API for results from G4ScoringManager

simulation/g4simulation/g4detectors/PHG4RICHSteppingAction.cc, simulation/g4simulation/g4main/PHG4Reco.cc
The Cherenkov  physics list which is used in gas and Aerogel RICH detector simulation was configured to track the Cherenkov photon before completing track the charged track within Geant4. This conflicts the assumption within `PHG4TruthTrackingAction` which split a charged track into multiple duplicates. This significant disrupts truth tracking and truth tracking on EIC detector simulations. 
This pull request should fix that. In addition, it fixes a missing variable init for `PHG4RICHSteppingAction`
=> Fixes on Cherenkov simulation

simulation/g4simulation/g4detectors/PHG4CylinderGeom.h, simulation/g4simulation/g4detectors/PHG4CylinderGeom_Siladders.cc, simulation/g4simulation/g4detectors/PHG4CylinderGeom_Siladders.h, simulation/g4simulation/g4detectors/PHG4SiliconTrackerCellReco.cc, simulation/g4simulation/g4detectors/PHG4SiliconTrackerCellReco.h, simulation/g4simulation/g4detectors/PHG4SiliconTrackerDefs.h, simulation/g4simulation/g4detectors/PHG4SiliconTrackerDetector.cc, simulation/g4simulation/g4detectors/PHG4SiliconTrackerSteppingAction.cc, simulation/g4simulation/g4detectors/PHG4SiliconTrackerSteppingAction.h
GEANT suffers failures at the 5% level in identifying the INTT strip volume that is associated with a G4 hit. I have made many attempts to repair this, but without complete success. I have given up, and now the simulation contains only the sensor volume as the active volume. The hit strips are assigned now in PHG4SiliconTrackerCellReco, using the G4 hit entry and exit points in the sensor and the INTT geometry object (similar to how the pixels are assigned for the MVTX).
The algorithm that assigns strips to the G4 hits is similar to the one used for the MVTX pixels, and it allows charge diffusion to be added in a convenient way. Currently I have added a small charge diffusion - it can be tweaked later when we have measurements.
These changes have been merged with the recent ones from …
=> Intt strips pacement

simulation/g4simulation/g4detectors/PHG4HcalSubsystem.cc, simulation/g4simulation/g4detectors/PHG4SiliconTrackerCellReco.cc, simulation/g4simulation/g4detectors/PHG4SiliconTrackerCellReco.h, simulation/g4simulation/g4detectors/PHG4SiliconTrackerDetector.cc, simulation/g4simulation/g4detectors/PHG4SiliconTrackerDetector.h, simulation/g4simulation/g4detectors/PHG4SiliconTrackerParameterisation.cc, simulation/g4simulation/g4detectors/PHG4SiliconTrackerParameterisation.h, simulation/g4simulation/g4detectors/PHG4SiliconTrackerSteppingAction.cc
Removal of 3 unused variables. The layer id is coded into the hit id, the access is way faster than going via the property map, the method is set/get_detid() to get rid of this layer number since it can be used for subdetectors as well. Replace TVectors by gsl vectors (TVectors should not be used since they use TMath internally which involves the pathetic TMath suppression of invalid values). Use PHParameter interface to store/retrieve/set tmin/tmax, fix memory leaks by use of new G4Visattribute and new G4RotationMatrix (the logical volumes copy this, which leaves the memory dangling).
No changes for the resulting Cells
=> Fix intt part 4

offline/packages/PHField/PHField3DCylindrical.cc
Fixing the z-boundary limit and adding additional phi- and r- boundary checks in the 3-D field map module `PHField3DCylindrical`. Current code segfaults at z=field map boundary.
=> Boundary condition checks on 3-D field map module

simulation/g4simulation/g4main/PHG4Reco.cc, simulation/g4simulation/g4main/PHG4Reco.h
Quick update to #472: allow disable all user action to Geant4 in order to speed up special studies that does not require downstream digitized analysis, such as the dose/fluence simulation.
=> Option to disable all user action to Geant4

simulation/g4simulation/g4detectors/PHG4DetectorGroupSubsystem.cc
the copying of the double params which were set in the macro wasn't done correctly (for the detector groups where so far the intt is the only customer). This is fixed now, strings might still have an issue - I just want to get this bugfix out so the Intt development can continue
=> double params from macro were not propagated

offline/packages/Prototype2/Prototype2DSTReader.cc, offline/packages/Prototype2/Prototype2DSTReader.h, offline/packages/Prototype3/Prototype3DSTReader.cc, offline/packages/Prototype3/Prototype3DSTReader.h, offline/packages/Prototype4/Prototype4DSTReader.cc, offline/packages/Prototype4/Prototype4DSTReader.h
This is just a cleanup, not sure why those two were included in the first place:
#include <HepMC/GenEvent.h>
#include <HepMC/SimpleVector.h>
while at it, replaced
boost:shared_ptr by std::shared_ptr (easy since the syntax is identical) but gets rid of an #ifdef __CINT__ since <memory> can be digested by rootcint
=> Removal of unused includes which prevent easy transition to hepmc3, use C++11 shared ptr

offline/packages/PHField/PHField3DCylindrical.cc
Our code QA tool `coverity` had two complains on `PHField3DCylindrical`. This pull request should address both.
=> Quick fix on coverity complains on PHField3DCylindrical

simulation/g4simulation/g4detectors/PHG4Prototype3InnerHcalDetector.cc, simulation/g4simulation/g4histos/G4TowerNtuple.cc, simulation/g4simulation/g4histos/G4TowerNtuple.h
The eta bins started at 10 putting a monkey wrench into the analysis code. Now the g4vplacements use copy no = 0 just like for the other prototypes which makes the etabin start at 0
=> Fix prototype4

simulation/g4simulation/g4detectors/PHG4CylinderGeom_Siladders.cc, simulation/g4simulation/g4detectors/PHG4CylinderGeom_Siladders.h, simulation/g4simulation/g4detectors/PHG4SiliconTrackerDetector.cc, simulation/g4simulation/g4detectors/PHG4SiliconTrackerDetector.h, simulation/g4simulation/g4detectors/PHG4SiliconTrackerSteppingAction.cc, simulation/g4simulation/g4detectors/PHG4SiliconTrackerSubsystem.cc, simulation/g4simulation/g4eval/SvtxEvaluator.C, simulation/g4simulation/g4eval/SvtxEvaluator.h, simulation/g4simulation/g4hough/PHG4KalmanPatRec.C, simulation/g4simulation/g4hough/PHG4KalmanPatRec.h
Modified the INTT simulation code so that what was formerly up to 4 layers with 2 sub-layers each, now becomes up to 8 single layers that can be configured independently. This is intended to make the setup more flexible, and make it easier to study the performance.
I also added some checks in the stepping action for glitches in the G4 handling of the active volume. There seem to be no problems in the present code, which uses a single active sensor volume and determines the strip later in the cell reco. The only strange events observed in the INTT sensors (track does not exit volume) appear to be due to hadronic interactions that kill the track. 
I will also commit a matching tracking macro.
=> Intt sublayer to layer

simulation/g4simulation/g4detectors/PHG4BlockDetector.cc, simulation/g4simulation/g4detectors/PHG4BlockDetector.h, simulation/g4simulation/g4detectors/PHG4OuterHcalSteppingAction.cc, simulation/g4simulation/g4detectors/PHG4OuterHcalSteppingAction.h, simulation/g4simulation/g4detectors/PHG4Prototype2InnerHcalDetector.cc, simulation/g4simulation/g4detectors/PHG4Prototype2InnerHcalDetector.h, simulation/g4simulation/g4detectors/PHG4Prototype2InnerHcalSteppingAction.cc, simulation/g4simulation/g4detectors/PHG4Prototype2InnerHcalSteppingAction.h, simulation/g4simulation/g4detectors/PHG4Prototype2InnerHcalSubsystem.cc, simulation/g4simulation/g4detectors/PHG4Prototype2InnerHcalSubsystem.h, simulation/g4simulation/g4detectors/PHG4Prototype2OuterHcalDetector.cc, simulation/g4simulation/g4detectors/PHG4Prototype2OuterHcalDetector.h, simulation/g4simulation/g4detectors/PHG4Prototype2OuterHcalSteppingAction.cc, simulation/g4simulation/g4detectors/PHG4Prototype2OuterHcalSteppingAction.h, simulation/g4simulation/g4detectors/PHG4Prototype2OuterHcalSubsystem.cc, simulation/g4simulation/g4detectors/PHG4Prototype2OuterHcalSubsystem.h, simulation/g4simulation/g4detectors/PHG4Prototype3InnerHcalDetector.cc, simulation/g4simulation/g4detectors/PHG4Prototype3InnerHcalDetector.h
The numbering in terms of rows/columns of the scintillators in the hcals is inconsistent. This pull request (which is still being worked on - so do not merge) makes the numbers consistent between inner and outer hcal for the 3rd testbeam (2nd testbeam inner hcal still needs to be looked at). The rows are unchanged, the columns go from 0-3.
Sadly this is not just a number change, while the scintillators stay the same (except their column number), the resulting towers and their energies are very different. Maybe its the lookup of calibration constants which his probably keyed to the row/column numbers
=> Fix prototype2/3

generators/JETSCAPE/FinalStateHadrons.cc, generators/JETSCAPE/FinalStatePartons.cc, generators/JETSCAPE/LBT_brickTest.cc, generators/JETSCAPE/MUSICTest.cc, generators/JETSCAPE/Makefile.am, generators/JETSCAPE/PythiaBrickTest.cc, generators/JETSCAPE/SimpleValidate.cc, generators/JETSCAPE/autogen.sh, generators/JETSCAPE/brickTest.cc, generators/JETSCAPE/configure.ac, generators/JETSCAPE/freestream-milneTest.cc, generators/JETSCAPE/hydroFileTest.cc, generators/JETSCAPE/hydroJetTest.cc, generators/JETSCAPE/hydroJetTestPGun.cc, generators/JETSCAPE/readerTest.cc, generators/JETSCAPE/testJetScape.cc
Normally one has to build JETSCAPE in its full glory to compile these examples as part of it. I pulled the examples out and added a Makefile which will build them against our centrally installed jetscape version
=> Add jetscape examples

generators/hijing/src/hijfst.C, generators/sHijing/Hijing.cxx, generators/sHijing/sHijing.xml, simulation/g4simulation/g4jets/Jet.h, simulation/g4simulation/g4jets/JetHepMCLoader.C, simulation/g4simulation/g4jets/JetHepMCLoader.h, simulation/g4simulation/g4jets/JetHepMCLoaderLinkDef.h, simulation/g4simulation/g4jets/Makefile.am
In the last jet structure group meeting, we discussed running large (2M) hijing production to study the fake jet rate and rejection in Geant4 simulation of the current calorimeter stacks. Last study was published in [DOI: 10.1103/PhysRevC.86.024908](https://journals.aps.org/prc/abstract/10.1103/PhysRevC.86.024908) with fast calorimetry simulations. 
Aaron Angerami pointed out up that we need to recover the capability of reading the sHijing HIJFRG truth jets, which records hard process originated from each HIJFRG subprocess. In the discussion, it was also clear that we also need to make these truth jets in the analysis via jets objets on the DST nodes. 
This pull request implements both suggestions. 
The current sHijing hard code |eta|<2 and E_total > 5 GeV cut. This pull request make both …
=> sHijing HIJFRG truth jets config and readback in DST

offline/packages/CaloReco/Makefile.am, simulation/g4simulation/g4calo/Makefile.am, simulation/g4simulation/g4calo/configure.ac, simulation/g4simulation/g4detectors/Makefile.am, simulation/g4simulation/g4eval/Makefile.am, simulation/g4simulation/g4hough/Makefile.am, simulation/g4simulation/g4main/Makefile.am, simulation/g4simulation/g4tpc/Makefile.am, simulation/g4simulation/g4vertex/Makefile.am
root6 macros insist on having all include files available for objects one instantiates in the macros. These ones are needed to make Fun4All_G4_sPHENIX.C and the macros it loads functional
=> install include files needed for Root6 macros

simulation/g4simulation/g4tpc/PHG4TPCElectronDrift.cc
Minor change to randomize the start position of the primary ionization electrons along the g4hit track in the TPC. Previously, they were evenly spaced. Ran some checks and they look fine.
=> Tpc random electron position

generators/phhepmc/HepMCFlowAfterBurner.cc, generators/phhepmc/HepMCFlowAfterBurner.h
this was basically a cleanup. The code got its parameters from an xml file and from the macro with somewhat unclear precedence. In order to avoid confusion I removed the xml file reading. The algorithm name was set to JJNEW which wasn't implemented. By some means it defaulted back to MINBIAS which is what we probably should use anyway. I added a check that the chosen algorithm actually exists (via a list copied from the flowAfterBurner, one should change the flowAfterBurner so this list is accessible from the outside to make this foolproof). The defaults are now set to -2<eta<2, 0<pt<100, algorithm=MINBIAS
=> remove xml file reading, only parameters set in macro are used now

offline/packages/CaloBase/RawTowerDefsLinkDef.h, offline/packages/trackbase/configure.ac
The RawTowerDefs were created with streamer (which was wrong but root5 is somewhat forgiving), now run it with -! like the other namespace Defs we have. For some unknown reason  offline/packages/trackbase generates warning in rootcling (the makefile and the includes and linkdefs look like the ones from other packages). Added an option to rootcling to suppress this warning. We certainly want to look at this at some point
=> no streamer for RawTowerDefs, suppress warnings from rootcling

simulation/g4simulation/g4eval/CaloTruthEval.C, simulation/g4simulation/g4eval/CaloTruthEval.h
During production stage with DST compression enabled, the calorimeter G4hit nodes are removed. The calorimeter tower truth information are linked with the primary particles with the G4Shower objects. CaloTruthEval need this minor patch to allow it safely ignore the missing G4hit node
=> Patch CaloTruthEval to analyze stripped DST without G4hit nodes

simulation/g4simulation/g4detectors/PHG4SiliconTrackerDetector.cc, simulation/g4simulation/g4tpc/PHG4TPCElectronDrift.cc, simulation/g4simulation/g4tpc/PHG4TPCElectronDrift.h
This pull request contains two unrelated bug fixes:
1) Fix to a bug in the g4tpc code that caused the TPC valid time window check to effectively not be made in the electron drift module. 
2) Fix to a bug found by Takahito in the INTT code. The dimensioning of one of the arrays used to construct the INTT was not increased from 4 to 8 when we switched from layers to sublayers. This caused problems for setups containing more than 4 sublayers. Fixing this bug corrected a problem reported separately by Sanghoon today. He saw bad behavior in the sublayers beyond 4. 
Before the bug fix, I reproduced Sanghoon's problem using the 6 layer setup "INTTLADDER6" in G4_Tracking.C. After the bug fix, the distribution of clusters in phi-Z space looks normal. See the before and after plots below. …
=> Tpc time window fix

offline/QA/modules/Makefile.am, simulation/g4simulation/g4detectors/Makefile.am, simulation/g4simulation/g4histos/Makefile.am
Installing a few more header files which are needed for root6 macros - for Fun4AllG4_EICDetector.C and the sim macro under packages/prototype4
=> install includes needed for root6 macros

simulation/g4simulation/g4calo/HcalRawTowerBuilder.cc, simulation/g4simulation/g4calo/HcalRawTowerBuilder.h, simulation/g4simulation/g4calo/RawTowerBuilder.cc, simulation/g4simulation/g4main/PHG4Shower.h, simulation/g4simulation/g4main/PHG4Showerv1.cc, simulation/g4simulation/g4main/PHG4Showerv1.h, simulation/g4simulation/g4main/PHG4TruthEventAction.cc
Cumulative fixes for analyzing jet background production data, which is the first time we strip hits, save calorimeter towers-only then perform embedding simulation on top again. 
Specific changes are
- Allow the embedding process to append simulation tower energy rather than overwrite it
- During the embedding process, check whether tower geometry would be consistent. If pass check, avoiding the warning message of overwriting tower geometry
- In the embedding process, avoid pruning the `PHG4Shower` objects produced the previous background simulation and preserve truth tracing for the background towers and showers. 
- [clang-format the source code](https://wiki.bnl.gov/sPHENIX/index.php/Codingconventions#Style_reformatting_tools)
=> Cumulative fixes for analyzing jet background production data

simulation/g4simulation/g4hough/PHG4TrackKalmanFitter.C
In `PHG4TrackKalmanFitter`, if a track refitting failed and in `_over_write_svtxtrackmap` mode.
The pre-refitting track in the `SvtxTrackMap` needs to be erased.
This was not handled properly and cause `Invalid read` memory issue.
Fixed this bug in this pull request.
Thanks to @blackcathj  and @pinkenburg for identifying and helping fix this issue.
valgrind log with forced into 'refitting failure': https://www.phenix.bnl.gov/WWW/p/draft/yuhw/erase_iter_fix/
reference: https://stackoverflow.com/questions/8234779/how-to-remove-from-a-map-while-iterating-it
=> Fix 'erase iter' issue

simulation/g4simulation/g4main/PHG4ParticleGeneratorBase.cc
Thanks to Mickey for finding this - the get_mass() method returned internal G4 units (which is MeV), now returns the mass in GeV which is our standard
=> return mass in GeV, not internal G4 units

offline/framework/phool/PHTimeServer.h, simulation/g4simulation/g4detectors/PHG4BlockDetector.cc, simulation/g4simulation/g4detectors/PHG4BlockSubsystem.cc, simulation/g4simulation/g4detectors/PHG4CylinderDetector.cc, simulation/g4simulation/g4detectors/PHG4CylinderSubsystem.cc, simulation/g4simulation/g4detectors/PHG4DetectorSubsystem.cc, simulation/g4simulation/g4detectors/PHG4FullProjTiltedSpacalDetector.cc, simulation/g4simulation/g4detectors/PHG4MapsSubsystem.cc, simulation/g4simulation/g4detectors/PHG4SpacalDetector.cc, simulation/g4simulation/g4detectors/PHG4SpacalPrototypeDetector.cc, simulation/g4simulation/g4detectors/PHG4SpacalPrototypeSubsystem.cc, simulation/g4simulation/g4detectors/PHG4SpacalSubsystem.cc, simulation/g4simulation/g4main/PHG4Reco.cc, simulation/g4simulation/g4main/PHG4Reco.h, simulation/g4simulation/g4tpc/PHG4TPCDetector.cc
insure flags std::string.c_str() as copying an uninitialized pointer (which is strictly speaking correct, but the uninitialized parts are not used). Since our interface is std::string, not const char *, all those conversions from srting to char * are redundant. So rather than add all of those occurrences to the suppression list this PR replaces std::string.c_str() by std::string. As of now there is one last insure error in g4gdml when it deals with the parametrized volume from the intt which I am not sure if this is real or not. 2 more false positives were added to the suppression. Other than the one from g4gdml, no insure complaints when running Fun4All_G4_sPHENIX.C This should make insure usable again.
=> Fix insure complaints

simulation/g4simulation/g4eval/SvtxEvaluator.C
if for some reason the layer id stored in the G4hit is outside of the x/y/z val array (given by the sum of the numbers of layers in the mvtx, intt and tpc) this will corrupt the memory. This PR checks that the layer id is within the allowed range
=> protect against use of out of bounds layer id

simulation/g4simulation/g4detectors/PHG4ForwardEcalDetector.cc, simulation/g4simulation/g4detectors/PHG4ForwardEcalDetector.h, simulation/g4simulation/g4detectors/PHG4ForwardEcalSteppingAction.cc
This set of changes adds a new option for a forward EMCal, based in a "cut" E864 calorimeter module.  The 10x10cm^2 E864 modules is further subdivided into towers using a 6x6 non-regular array of light guides, forming 36 smaller towers.  Because the E864 towers use a 47x47 array of fibers, the light guides come in two varieties - an 8x8 fiber version and an 8x7 fiber version, allowing the construction of three different sizes of towers (an 8x8, 8x7 and 7x8 tower).  While this arrangement complicates the cluster reconstruction and fitting, it is the only way to avoid creating inefficiencies on the edges by having a light guide boundary cross fibers. 
The code adds support for towers type 3,4,5 defined as: 
1.702 x 1.702 cm^2   (type 3, 8x8 fibers)
1.702 x 1.489 cm^2   (type 4 with long …
=> Add E864 (cut) module forward EMCal

offline/packages/CaloBase/RawClusterContainer.cc, offline/packages/CaloBase/RawClusterContainer.h, offline/packages/CaloBase/RawTowerContainer.cc, offline/packages/CaloBase/RawTowerContainer.h
Adding the const access functions of `get_cluster()`/`get_tower()` on the cluster/tower containers, to allow using these containers as constant objects in the downstream analysis modules. 
Thanks @FrancescoVassalli  at UCB for pointing out these missing const getters.
=> adding const access function for cluster/tower containers.

offline/framework/phool/PHObject.cc, offline/framework/phool/PHObject.h, offline/packages/PHGeometry/PHGeomIOTGeo.cc
From the PHENIX days PHObject had two private variables to handle the split level and buffer size for each object which were not streamed out. This leads to higher memory consumption since all our I/O objects inherit from it. This PR removes those variables, since they were not streamed out this does not affect the readability of old DSTs
=> Fix PHObject

offline/database/PHParameter/Makefile.am, offline/database/PHParameter/configure.ac
this package only contained dictionaries for command line classes, no dictionaries needed for root6
=> create dictionaries only for root5

offline/packages/Prototype3/RawTower_Prototype3.cc, offline/packages/Prototype3/RawTower_Temperature.cc, offline/packages/Prototype4/RawTower_Prototype4.cc, offline/packages/Prototype4/RawTower_Temperature.cc, simulation/g4simulation/g4main/Makefile.am, simulation/g4simulation/g4main/PHG4EventHeader.cc, simulation/g4simulation/g4main/PHG4EventHeaderv1.cc, simulation/g4simulation/g4main/PHG4Hitv1.cc, simulation/g4simulation/g4main/PHG4InEvent.cc, simulation/g4simulation/g4main/PHG4Particle.cc, simulation/g4simulation/g4main/PHG4Particlev1.cc, simulation/g4simulation/g4main/PHG4Particlev2.cc, simulation/g4simulation/g4main/PHG4Shower.cc, simulation/g4simulation/g4main/PHG4Showerv1.cc, simulation/g4simulation/g4main/PHG4VtxPoint.cc, simulation/g4simulation/g4main/PHG4VtxPointv1.cc
The ClassImp macro has been obsolete for more than 10 years, removing it so it finally stops propagating
=> Remove classimp

simulation/g4simulation/g4detectors/Makefile.am
ePHENIXRICHConstruction_Dict.cc and PHG4DetectorGroupSubsystem_Dict.cc made it into the source list rather than the root5 dictionary list
=> oops, 2 dictionaries made it into the source list

simulation/g4simulation/g4hough/Makefile.am, simulation/g4simulation/g4intt/Makefile.am
two more dictionaries, now we can build with root6 without having to copy the pcm files by hand after building
=> fix forgotten dictionaries

simulation/g4simulation/g4intt/PHG4INTTDigitizer.cc, simulation/g4simulation/g4intt/PHG4INTTDigitizer.h
This is a pull request to implement the contribution from noise electrons into the determination of INTT hit ADC values. The noise electron distribution for 320um thick silicon cell was obtained using INTT prototype modules, which is shown in the right panel of the below figure. The mean(457e-) and sigma(166e-) values of the noise electron distribution are available only in this plot right now. Once we have a new INTT prototype module with 320um thick cell, we will confirm these values again. For now we want to set up an infrastructure to handle the noise contributions.
Currently the ADC value of INTT hit is determined by directly comparing the true deposited energy in a cell (cell->get_edep()) to the energy threshold (vadcrange * mip_e). 
The code change strategy here is as follows:
1. …
=> Added noise electron when determining ADC value.

simulation/g4simulation/g4calo/Makefile.am
The include needs to be installed to run the prototype(2) reconstruction macro under root6
=> need to install Prototype2RawTowerBuilder.h

simulation/g4simulation/g4detectors/PHG4ForwardEcalDetector.cc, simulation/g4simulation/g4detectors/PHG4ForwardEcalDetector.h
This pull request updates the forward EMC (based on cut down E864 modules) tower geometry to use the tower structure suggested by @blackcathj: 
// In order to keep the light guide boundaries between fibers in the E864 47x47 fiber array, 
// we need to have two types of light guides yielding three sizes of towers with different
// numbers of fibers. 
// 2.128 x 2.128 cm^2   (type 3, 10x10 fibers)
// 1.915 x 2.128 cm^2   (type 4 with short dimension horizontal (9x10), 5 with short dimension vertical (10x9))
// 1.915 x 1.915 cm^2   (type 6, 9x9 fibers)
// 3 (1:10,38:47) 4 (11:19,38:47) 4 (20:28,38:47) 4 (29:37,38:47) 3 (38:47,38:47)
// 5 (1:10,29:37) 6 (11:19,29:37) 6 (20:28,29:37) 6 (39:37,29:37) 5 (38:47,39:37)
// 5 (1:10,20:28) 6 (11:19,20:28) 6 (20:28,20:28) 6 (29:37,20:28) 5 …
=> Updated E864 fEMC tower geometry

simulation/g4simulation/g4jets/JetMapv1LinkDef.h
It's not clear to me why this works or what those additional entries in the LinkDef file were about. They are still visible to root5 CINT. Lets see how this goes
=> this change makes the cling loading complaint about JetMap.h go away

simulation/g4simulation/g4intt/PHG4INTTDetector.cc, simulation/g4simulation/g4intt/PHG4INTTSubsystem.cc, simulation/g4simulation/g4main/PHG4Reco.cc
This is a PR to implement the new INTT endcap ring geometry using Carbon-PEEK (CP) proposed by Rachid at the simulation meeting 3/12/2019. Defined the CP material in the "PHG4Reco.cc". Introduced a parameter in the "PHG4INTTSubsystem.cc" to select either the aluminum(Al) or CP endcap rings. The Al endcap ring option remains as default for now. The new geometry in "PHG4INTTDetector.cc"  successfully passed the overlap check.
=> INTT new endcap ring geometry using Carbon-PEEK

offline/framework/fun4all/Fun4AllMemoryTracker.cc, offline/framework/fun4all/Fun4AllMemoryTracker.h, offline/framework/fun4all/Fun4AllServer.cc, offline/framework/fun4all/Fun4AllServer.h, offline/framework/fun4all/Makefile.am
This PR adds a singleton which can be used to track memory. Snapshots and Start/Stop are supported, the memory tracking uses a name and a group to identify a given tracker. It has been added to monitor the memory for each module for each process_event call as well as the output managers when writing out. To print out the values use:
Fun4AllServer *se = Fun4AllServer::instance()
se->PrintMemoryTracker();
you can instrument any code by using
#include <fun4all/Fun4AllMemoryTracker.h>
ffamemtrk = Fun4AllMemoryTracker::instance();
ffamemtrk->AddSnapshot("MYmodule");
or
ffamemtrk->Start("Mymodule");
do something
ffamemtrk->Stop("Mymodule");
ffamemtrk->PrintMemoryTracker("Mymodule");
to see the memory growth
Also sorted the data members of the Fun4AllServer according to type to make their …
=> Add Memory tracking

generators/phhepmc/Fun4AllHepMCOutputManager.cc, offline/framework/fun4all/Fun4AllDstOutputManager.cc, offline/framework/fun4all/Fun4AllEventOutputManager.cc, offline/framework/fun4all/Fun4AllMemoryTracker.cc, offline/framework/fun4all/Fun4AllMemoryTracker.h, offline/framework/fun4all/Fun4AllOutputManager.cc, offline/framework/fun4all/Fun4AllOutputManager.h, offline/framework/fun4all/Fun4AllPrdfOutputManager.cc, offline/framework/fun4all/Fun4AllPrdfOutputManager.h, offline/framework/fun4all/Fun4AllServer.cc, offline/framework/fun4all/Fun4AllServer.h, offline/framework/fun4all/Makefile.am
This PR is part of a long term cleanup of fun4all. Datamembers should not be exposed to derived classes but private and access methods should be used. This PR makes the datamembers of the Fun4AllOutputManager base class private
=> Fun4AllOutputManager are private now

simulation/g4simulation/g4trackfastsim/Makefile.am
the new genfit version uses eigen - so we need to add the eigne include dir to the include search path ($OFFLINE_MAIN/include/eigen3)
=> add eigen include dir to include path

offline/framework/fun4all/Fun4AllMemoryTracker.cc, offline/framework/fun4all/Fun4AllMemoryTracker.h, simulation/g4simulation/g4histos/Makefile.am
This PR installs G4HitTTree.h which is needed by the block and cylinder tutorials. Added return of vector<int> for memory tracker to be used in plotting macros
=> Fix tutorials

simulation/g4simulation/g4intt/PHG4INTTDetector.cc, simulation/g4simulation/g4intt/PHG4INTTSubsystem.cc
This PR is to implement the follwoing changes.
- Latest INTT stave design with the water cooling presnted by Rachid.
https://indico.bnl.gov/event/5455/contributions/27179/attachments/22046/30517/INTT_Simulation_Meeting_12March2019.pdf
- Modification to ladder_volume shape (drop of two corners) to resolve the issue that 
air inside the volume overlaps with other ladder because of the small clearnace in the
latest INTT configuration.
The code keeps the previous stave design without water cooling. 
The stave with water cooling is set as default.
These changes succesfully passed the overlap check of GEANT4.
=> INTT new stave design (version Mar12)

simulation/g4simulation/g4intt/PHG4INTTDetector.cc
This PR is to fix warning messages on parameter ordering issue when using G4GenericTrap to describe the trapezoidal part of the rohacell foam in the INTT stave geometry. No change in the geometry itself. Shown below is a cut-and-paste from GEANT4 overlap check with the fixed code. 
Now the trapezoidal shapes do not show the warning messages.
++++++++++++++++++++++++++++++++++++++++++++++++++++
Checking overlaps for volume rohacell_trap_0_0_0 ... OK! 
Checking overlaps for volume rohacell_trap_ext_0_0_0 ... OK! 
Checking overlaps for volume rohacell_trap_0_0_1 ... OK! 
Checking overlaps for volume rohacell_trap_ext_0_0_1 ... OK! 
++++++++++++++++++++++++++++++++++++++++++++++++++++
=> Fix parameter ordering issue when using G4GenericTrap for INTT geometry

simulation/g4simulation/g4main/Makefile.am, simulation/g4simulation/g4main/PHG4IonGun.cc, simulation/g4simulation/g4main/PHG4IonGun.h, simulation/g4simulation/g4main/PHG4IonGunLinkDef.h, simulation/g4simulation/g4main/PHG4Reco.cc, simulation/g4simulation/g4main/PHG4Reco.h
NSRL and CAD need ions but our particle generator infra structure needs to look the particles up in pdg. This PR creates a back door to feed particles into our G4 simulations. Caveat: this cannot be used in conjunction with our particle generators. A new class PHG4IonGun is used to generate ions. So far it uses 0/0/0 as vertex - I don't think it is necessary to add vertex displacement or smearing for this
=> Add Ion gun

offline/packages/intt/CylinderGeomINTT.cc, offline/packages/intt/Makefile.am, offline/packages/jetbackground/Makefile.am, simulation/g4simulation/g4detectors/Makefile.am, simulation/g4simulation/g4dst/Makefile.am, simulation/g4simulation/g4eval/Makefile.am, simulation/g4simulation/g4hough/Makefile.am, simulation/g4simulation/g4intt/Makefile.am, simulation/g4simulation/g4jets/Makefile.am
this PR fixes up some library dependencies. The more or less random adding of libraries is hurting us in the meantime - if your DST objects need the geant4 installation you know something is not right (or for that matter your simulation libraries need the online libs). This will probably an iterative process, this is the first step
=> Fix library dependencies

offline/packages/mvtx/Makefile.am, offline/packages/tpc/Makefile.am, offline/packages/trackbase/Makefile.am, simulation/g4simulation/g4intt/Makefile.am, simulation/g4simulation/g4mvtx/Makefile.am, simulation/g4simulation/g4tpc/Makefile.am
This PR reduces the lib dependencies of the new tracking even more. This should get rid of G4 propagating into our reconstruction libraries
=> Fix lib deps

offline/framework/frog/Makefile.am, offline/framework/fun4all/Makefile.am, offline/framework/phool/Makefile.am, offline/framework/phool/PHRawDataNode.cc, offline/framework/phool/PHRawDataNode.h, offline/packages/NodeDump/Makefile.am, offline/packages/PHGeometry/Makefile.am, offline/packages/intt/Makefile.am, offline/packages/jetbackground/Makefile.am, offline/packages/mvtx/Makefile.am, offline/packages/trigger/Makefile.am
This PR cleans up our libs and Makefiles a bit more. It is rarely necessary to need libfun4all, for most subsysreco modules a dependency on libSubsysReco is enough. Started to split off event libraries, we now have a libphool_raw which contains sources dependent on event libs (we do not make use of them right now, it is the raw data write which in principal can be used to write prdf files)
=> Fix makefiles

simulation/g4simulation/g4detectors/Makefile.am, simulation/g4simulation/g4detectors/PHG4CEmcTestBeamSubsystem.cc, simulation/g4simulation/g4detectors/PHG4ConeSubsystem.cc, simulation/g4simulation/g4detectors/PHG4CrystalCalorimeterSubsystem.cc, simulation/g4simulation/g4detectors/PHG4CylinderDetector.cc, simulation/g4simulation/g4detectors/PHG4CylinderDetector.h, simulation/g4simulation/g4detectors/PHG4CylinderDisplayAction.cc, simulation/g4simulation/g4detectors/PHG4CylinderDisplayAction.h, simulation/g4simulation/g4detectors/PHG4CylinderGeom_Spacalv1.h, simulation/g4simulation/g4detectors/PHG4CylinderSteppingAction.cc, simulation/g4simulation/g4detectors/PHG4CylinderSteppingAction.h, simulation/g4simulation/g4detectors/PHG4CylinderSubsystem.cc, simulation/g4simulation/g4detectors/PHG4CylinderSubsystem.h, simulation/g4simulation/g4detectors/PHG4EnvelopeSubsystem.cc, simulation/g4simulation/g4detectors/PHG4ForwardEcalSubsystem.cc, simulation/g4simulation/g4detectors/PHG4ForwardHcalSubsystem.cc, simulation/g4simulation/g4detectors/PHG4HcalPrototypeSubsystem.cc, simulation/g4simulation/g4detectors/PHG4HcalSubsystem.cc, simulation/g4simulation/g4detectors/PHG4RICHSubsystem.cc, simulation/g4simulation/g4detectors/PHG4SectorSubsystem.cc, simulation/g4simulation/g4main/Makefile.am, simulation/g4simulation/g4main/PHG4DisplayAction.cc, simulation/g4simulation/g4main/PHG4DisplayAction.h, simulation/g4simulation/g4main/PHG4Reco.cc, simulation/g4simulation/g4main/PHG4Reco.h, simulation/g4simulation/g4main/PHG4Subsystem.h
This PR introduces the PHG4DisplayAction which sets the G4VisAttributes on demand (when the detector is displayed), thus saving the memory those attributes waste when running normally. This is the first test implementation for the PHG4CylinderSubsystem. The DisplayOn.C macro needs to be adjusted to call this. If you forget you just get a wireframe when displaying the detector (better than nothing).
Also included - making
=> New DisplayAction

simulation/g4simulation/g4main/PHG4DisplayAction.h, simulation/g4simulation/g4mvtx/Makefile.am, simulation/g4simulation/g4mvtx/PHG4MVTXDetector.cc, simulation/g4simulation/g4mvtx/PHG4MVTXDetector.h, simulation/g4simulation/g4mvtx/PHG4MVTXDisplayAction.cc, simulation/g4simulation/g4mvtx/PHG4MVTXDisplayAction.h, simulation/g4simulation/g4mvtx/PHG4MVTXSteppingAction.h, simulation/g4simulation/g4mvtx/PHG4MVTXSubsystem.cc, simulation/g4simulation/g4mvtx/PHG4MVTXSubsystem.h
This PR implements the DisplayAction for the mvtx. It mimics what was done for the mvtx in terms of color selections. This fixes also some memory leaks. The mvtx code still uses the event action to drop zero energy hits which wastes memory and cpu. That will be tackled seperately in some subsequent PR
=> Mvtx displayaction

simulation/g4simulation/g4mvtx/PHG4MVTXDetector.cc, simulation/g4simulation/g4mvtx/PHG4MVTXDetector.h, simulation/g4simulation/g4mvtx/PHG4MVTXDisplayAction.cc, simulation/g4simulation/g4mvtx/PHG4MVTXDisplayAction.h, simulation/g4simulation/g4mvtx/PHG4MVTXSteppingAction.cc, simulation/g4simulation/g4mvtx/PHG4MVTXSteppingAction.h, simulation/g4simulation/g4mvtx/PHG4MVTXSubsystem.cc, simulation/g4simulation/g4mvtx/PHG4MVTXSubsystem.h
This PR replaces the old event action which was used to remove zero energy hits. This functionality is now done in the steppingaction where we pick up the last step in a volume and add the hit only if it has some energy loss. Not sure if the entry condition is up to date (we have a few more condition to start a hit in others). Also the mvtx does not provide for the creation and saving of absorber/support structure hits
=> Mvtx Eventaction replacement

simulation/g4simulation/g4intt/Makefile.am, simulation/g4simulation/g4intt/PHG4INTTDetector.cc, simulation/g4simulation/g4intt/PHG4INTTDetector.h, simulation/g4simulation/g4intt/PHG4INTTDigitizer.cc, simulation/g4simulation/g4intt/PHG4INTTDigitizer.h, simulation/g4simulation/g4intt/PHG4INTTDigitizerLinkDef.h, simulation/g4simulation/g4intt/PHG4INTTDisplayAction.cc, simulation/g4simulation/g4intt/PHG4INTTDisplayAction.h, simulation/g4simulation/g4intt/PHG4INTTFPHXParameterisation.cc, simulation/g4simulation/g4intt/PHG4INTTFPHXParameterisation.h, simulation/g4simulation/g4intt/PHG4INTTSubsystem.cc, simulation/g4simulation/g4intt/PHG4INTTSubsystem.h, simulation/g4simulation/g4tpc/Makefile.am, simulation/g4simulation/g4tpc/PHG4TPCDigitizer.cc, simulation/g4simulation/g4tpc/PHG4TPCDigitizer.h, simulation/g4simulation/g4tpc/PHG4TPCDigitizerLinkDef.h, simulation/g4simulation/g4tpc/PHG4TPCElectronDrift.cc, simulation/g4simulation/g4tpc/PHG4TPCElectronDrift.h, simulation/g4simulation/g4tpc/PHG4TPCElectronDriftLinkDef.h
This PR moves the setting of the G4VisAttributes to the DisplayAction so we only allocate the needed memory when an event display is made. It also makes the source/class names uniform in the g4intt and g4tpc package. They are still different between the intt/tpc and g4intt/g4tpc, I guess this should be discussed so we can change it before it gets out of hand
=> Displayaction intt

simulation/g4simulation/g4intt/PHG4InttHitReco.cc, simulation/g4simulation/g4intt/PHG4InttHitReco.h
The local 12x12 arrays stripenergy and stripeion were too small, the bounds check allowed index=12 which is outside. This lead to stack corruption which then crashed the calling routine. insure would have found that but the current version doesn't work
=> fix off by one index problem

offline/framework/phool/PHIODataNode.h, offline/framework/phool/PHNodeIOManager.cc, offline/framework/phool/PHNodeIOManager.h, offline/framework/phool/PHObject.h
This PR moves the source of those parameters for the TBranch from PHObject to the PHIODataNode so it can be set separately on a node by node level
=> Buffer Size and Split Level now feature of PHIODataNode

simulation/g4simulation/g4detectors/PHG4SpacalPrototypeSteppingAction.cc, simulation/g4simulation/g4main/PHG4Reco.cc
From #633, new `PHG4SteppingAction` require string name as the 1st parameter. Many derived stepping action was updated in #633, but `PHG4SpacalPrototypeSteppingAction` was left over. This pull request fixes that. 
Thanks to @sunxuhit for pointing out this problem.
=> Fixing `PHG4SpacalPrototypeSteppingAction`

simulation/g4simulation/g4detectors/PHG4FullProjTiltedSpacalDetector.cc
For the EMCal block density studies, enabling print out of the block size and density statistics if verbosity flag is turned on. 
To enable the output, please set `construction_verbose` = 2 or higher in `G4_CEmc_Spacal.C` following this example: https://github.com/sPHENIX-Collaboration/macros/commit/33b878b30c43dbeb10569dc96bd68fa46e166403
Example print for one of the block are
`
PHG4FullProjTiltedSpacalDetector::Construct_Tower::CEMC_0 - constructed tower ID 1010 with 2668 fibers using Construc
t_Fibers_SameLengthFiberPerTower. V = 348.577cm3, m = 3525.35gram, Density = 10.1135g/cm3
`
=> Count and print EMCal block density

offline/packages/trackreco/Makefile.am, offline/packages/trackreco/PHGenFitTrackProjection.cc, offline/packages/trackreco/PHGenFitTrackProjection.h, offline/packages/trackreco/PHGenFitTrackProjectionLinkDef.h
Moved g4hough/PHG4GenFitTrackProjection to trackreco/PHGenFitTrackProjection. This removes all dependency of the track reconstruction macro on g4simulations/g4hough. 
I will make a pull request with corresponding macro changes.
=> Track projection move

offline/QA/modules/Makefile.am, offline/QA/modules/QAG4SimulationCalorimeterSum.cc, offline/packages/NodeDump/Makefile.am, simulation/g4simulation/g4dst/Makefile.am, simulation/g4simulation/g4histos/Makefile.am, simulation/g4simulation/g4jets/Makefile.am, simulation/g4simulation/g4vertex/Makefile.am
This PR removes the g4hough from the Makefiles.  The only code which used a method from g4hough is offline/QA/modules/QAG4SimulationCalorimeterSum.cc for projections to the front of the emc. I commented this code out - that needs to be reimplemented with our current versions.
=> remove g4hough remnants

offline/packages/tpc/TpcClusterizer.cc, offline/packages/trackreco/PHTruthTrackSeeding.cc, offline/packages/trackreco/PHTruthTrackSeeding.h, simulation/g4simulation/g4tpc/PHG4TpcPadPlaneReadout.cc
Few fixes to get the TPC prototype simulation going
1. Implement `TpcClusterizer::InitRun(PHCompositeNode *topNode)` to build containers in DST, which are needed to run TPC simulation alone without silicon trackers. 
2. Allow zero layers in modules for the TPC readout plane in 242942c. This is due to test beam only use module 2 with module 1 and module 3 = 0 layers. 
3. clang-format to sPHENIX code style. Adding a few more verbosity prints.
=> Accumulated fixes to get the TPC prototype simulation going

offline/packages/trackreco/PHGenFitTrackProjection.cc
This PR fixes a simple coverity complaint. Doing this to reduce the noise in coverity and before this code gets copied around more
=> make coverity happy, set verbosity after pointer was verified

generators/PHPythia8/Makefile.am, generators/PHPythia8/PHPythia8.cc
This PR fixes a small memory leak. Use fastjet-config --libs to link against fastjet. This will pull in the libraries fastjet needs (boost and CGAL) so we do not need to add them explicitely
=> Fix phpythia8

simulation/g4simulation/g4detectors/PHG4BlockDisplayAction.cc, simulation/g4simulation/g4detectors/PHG4BlockDisplayAction.h, simulation/g4simulation/g4detectors/PHG4BlockSubsystem.cc, simulation/g4simulation/g4detectors/PHG4BlockSubsystem.h, simulation/g4simulation/g4detectors/PHG4CylinderDisplayAction.cc, simulation/g4simulation/g4detectors/PHG4CylinderDisplayAction.h, simulation/g4simulation/g4detectors/PHG4CylinderSubsystem.cc, simulation/g4simulation/g4detectors/PHG4CylinderSubsystem.h
This PR makes it possible to set the color of generic blocks and cylinders in the macro. Up to now it was based on the material which is not really what we want
=> make colors for block and cylinder detectors adjustable in macro

offline/packages/trackreco/Makefile.am, offline/packages/trackreco/PHRaveVertexing.cc, simulation/g4simulation/g4trackfastsim/PHG4TrackFastSim.cc, simulation/g4simulation/g4trackfastsim/PHG4TrackFastSim.h, simulation/g4simulation/g4trackfastsim/PHG4TrackFastSimEval.cc, simulation/g4simulation/g4trackfastsim/PHG4TrackFastSimEval.h
EIC detector use fast pattern recognition + Kalman filter fit. With recent need in secondary vertex studies (https://indico.in2p3.fr/event/18281/contributions/71617/), this pull request add option to reconstruct vertexes with RAVE using the tracks after the fitting stage. Evaluation module are also modified to support the reconstructed vertexes too.
=> Add vertex reconstruction in the EIC fast tracking module

simulation/g4simulation/g4detectors/PHG4BlockCellReco.cc, simulation/g4simulation/g4detectors/PHG4BlockCellReco.h, simulation/g4simulation/g4detectors/PHG4CylinderCellReco.cc, simulation/g4simulation/g4detectors/PHG4CylinderCellReco.h, simulation/g4simulation/g4intt/PHG4InttHitReco.cc, simulation/g4simulation/g4intt/PHG4InttHitReco.h, simulation/g4simulation/g4main/PHG4Utils.cc, simulation/g4simulation/g4main/PHG4Utils.h, simulation/g4simulation/g4mvtx/PHG4MvtxHitReco.cc, simulation/g4simulation/g4mvtx/PHG4MvtxHitReco.h
we had multiple identical copies of intersection of lines with rectangles and circles floating around, they live now as static methods in PHG4Utils. Also cleanup of identical get_eta and get_etaphi methods. Removal of unused variables and empty methods. Basically some sources are now 1/2 of their original size while still doing the same
=> Move geometry methods to PHG4Utils

simulation/g4simulation/g4detectors/PHG4InnerHcalSubsystem.cc
This PR switches the default material for the inner Hcal from SS310 to Al
=> Use Al as material for Inner HCal

generators/flowAfterburner/main.cc
At the request of the JS TWG I have updated the code defaults to extend the eta range over which the flow afterburner is applied to include coverage for the forward region, allowing for studies of future forward  detectors. There was confusion after the last collaboration meeting as to how the afterburner was actually applied if run w/o a configuration file. The MINBIAS configuration has an eta-dependent model for v2, although I haven't compared it to RHIC data yet (has anyone?). 
I also explicitly updated the code to use the configuration name MINBIAS which is one of the three defined in flowAfterburner.cc rather than rely on some obscure behavior of the STL map to select the right thing. The code is less confusing this way if anyone tries to read it. 
There is a corresponding pull …
=> Update configuration defaults

generators/flowAfterburner/flowAfterburner.cc
Minor change to the rapidity dependence of the flow function to be a better match to 200 GeV AuAu at RHIC, as determined by a comparison with PHOBOS data. The PHOBOS comparison is outlined in a Jet Structure ToG talk at:
https://indico.bnl.gov/event/6764/
With this change the flowAfterburner is a fair representation of the flow measured by PHOBOS at RHIC 200 GeV AuAu, not perfect, but good enough for detector studies.
=> tune flow rapidity dependence to better match RHIC 200GeV AuAu

offline/packages/trackreco/PHGenFitTrkFitter.cc
Tweaked the diagnostic output from tracking so that you have to turn on a non-zero verbosity level to get them.
=> Fix berbosity in multiple vertexing code

simulation/g4simulation/g4main/PHG4Showerv1.cc, simulation/g4simulation/g4main/PHG4Showerv1.h
This PR reverts the use of std::array instead of float []. Don't know what I was thinking changing datamembers of an i/o class. Use fill(std::begin(pos),std::end(pos),NAN) to initialize the array in the ctor - no knowledge of array size needed, no gymnastics with sizeof variable
=> Fix PHG4Showerv1

simulation/g4simulation/g4calo/RawTowerDigitizer.cc, simulation/g4simulation/g4calo/RawTowerDigitizer.h
In the Sept 13 EMCal meeting, John Haggerty pointed out in Anabel's talk that the top energy EMCal showers are in SiPM saturation region due to limited (40k x 4) available pixels. This pull request enable this effect in the simulation with new digitizer option :
```c++
TowerDigitizer->set_digi_algorithm(RawTowerDigitizer::kSiPM_photon_digitization);
```
The default value is 40000 * 4, i.e. the sPHENIX EMCal default, 4x Hamamatsu S12572-015P MPPC [sPHENIX TDR]. 
Please note this scheme does not directly apply to the HCal, as each tiles are optically isolated from each other which require SiPM simulation for each tiles rather than each tower as in the EMCal cases.
=> Add SiPM Digitization

simulation/g4simulation/g4detectors/Makefile.am
the g4detectors needs the MT flags from G4 to build
=> add use of geant4-config --cflags to compile with MT GEANT4

generators/phhepmc/Fun4AllHepMCInputManager.h, generators/phhepmc/Fun4AllHepMCPileupInputManager.h, generators/phhepmc/PHGenEventListv1.h, generators/phhepmc/PHGenEventv1.h, generators/phhepmc/PHHepMCGenHelper.h, generators/sHEPGen/sHEPGen.h, offline/framework/phool/PHTimeServer.h, offline/framework/phool/phool.h, offline/packages/CaloBase/RawTowerDefs.h, offline/packages/intt/InttDefs.h, offline/packages/mvtx/MvtxDefs.h, offline/packages/tpc/TpcDefs.h, offline/packages/tpcdaq/TPCDataStreamEmulator.h, offline/packages/tpcdaq/TPCFEETestRecov1.h, offline/packages/tpcdaq/TPCIntegratedCharge.h, offline/packages/trackbase/TrkrDefs.h, offline/packages/trackbase/TrkrDefsLinkDef.h, offline/packages/trackreco/PHGenFitTrkProp.h, offline/packages/trackreco/PHHoughSeeding.h, offline/packages/trackreco/PHPatternReco.h
This PR makes all headers accessible to rootcling by just excluding rootcint from some parts. rootcling defines __CINT__ and __CLING__ so requiring !__CINT__ || __CLING__ lets rootcling see those. This was already done for most sources, thie PR fixes all of our headers so the old ifndef __CINT__ hopefully stops spreading from now on
=> Fix up ifndef __CINT__

offline/packages/NodeDump/DumpPHG4TruthInfoContainer.cc, simulation/g4simulation/g4main/PHG4ScoringManager.cc, simulation/g4simulation/g4main/PHG4ScoringManager.h, simulation/g4simulation/g4main/PHG4TruthEventAction.cc, simulation/g4simulation/g4main/PHG4TruthEventAction.h, simulation/g4simulation/g4main/PHG4TruthInfoContainer.cc, simulation/g4simulation/g4main/PHG4TruthInfoContainer.h
This PR fixes the order of actions in the Truth End of Event action. The showers need track information which is scrubbed during the removal of "unused" entries (unused meaning leading to saved hits). Now the showers are handled before the scrubbing so they have the full information available
=> Fix femc truth

offline/framework/phool/PHNodeIOManager.cc, offline/framework/phool/phooldefs.h
This PR exchanges the . we have used so far as branch name delimeter by \# The . was interpreted by the TTree->Draw as decimal point which made drawing from the cmd line impossible.
The change is backward compatible, branchnames are still split properly when . is used (or from the really old days /) from previous productions
=> use # as branch delimeter

generators/PHPythia6/PHPy6JetTrigger.cc, generators/PHPythia6/PHPy6JetTrigger.h, generators/PHPythia8/PHPy8JetTrigger.cc, generators/PHPythia8/PHPy8JetTrigger.h
Added simple functionality to the PYTHIA jet trigger class for users to require the jet has a minimum number of constituents. Tested by running default pythia jet macro while requiring a large number of constituents (14) at RHIC energies - each event had at least one jet with 14 or more constituents.
Useful for e.g. photon-jet events where one would like to trigger on a high pT photon and a high pT jet that isn't just composed of (for example) the prompt photon.
=> Added minimum number of constituents option to PYTHIA jet trigger

offline/packages/trackreco/PHTruthTrackSeeding.cc, offline/packages/trackreco/PHTruthTrackSeeding.h
During recent study with truth patter reco by Hugo Pereira Da Costa, rare errors are reported from GenFit fitting module on the GenFit track state's co-variant matrix, which fails the positive definite test. Further debug trace some of the error to tightly coiled delta electron in the TPC volume. They can contribute to many clusters per track but all within few layers. 
This pull request introduce a cut on the minimal layers a track is required to go through to be considered in the truth patter reco. Default cut is set to three, which is the minimal to fit a curve
Nonetheless, this PR does not completely eliminate this error message, as there are still large-radius loopers, which traverse multiple TPC layers. They could still fail in GenFit fit and this error may still be thrown from …
=> Introduce min-layer requirement for truth patter reco

offline/packages/trackreco/PHRTreeSeeding.cc, offline/packages/trackreco/configure.ac
gcc 8.3 generates a warning in a boost heard which needs suppressing,  std::accumulate needs <numeric> include
=> Fix for gcc 8.3

offline/packages/trackreco/PHGenFitTrkFitter.h
This should take care of the  weird behavior under singularity with local cvmfs copies. phgenfit::Track was forward declared but used in a shared pointer. No idea why it behaved this way but including the declaration fixed this. This include has a comment now to ignore the recommendations from include checkers to remove this
=> add include to resolve phgenfit::Track

offline/packages/trackreco/PHTruthVertexing.cc, offline/packages/trackreco/PHTruthVertexing.h
Properly set rnd seed in PHTruthVertexing: not to call `PHRandomSeed()` in `PHTruthVertexing::Process(PHCompositeNode* topNode)`
=> properly set rnd seed in PHTruthVertexing

offline/framework/phool/PHNodeIntegrate.cc, offline/framework/phool/PHObject.cc
`PHObject::clone()` has retired to use `PHObject::CloneMe()`. Updating `PHNodeIntegrate` to reflect this change. 
Thanks Yuanjing Ji for finding this problem
=> Fix clone() call

offline/packages/PHGenFitPkg/PHGenFit/Fitter.h, offline/packages/trackreco/PHGenFitTrkProp.h, simulation/g4simulation/g4trackfastsim/PHG4TrackFastSim.h
This PR fixes more of those ubuntu crashes. Now all namespace PHGenFit{class Track;} are replaced by the include file
=> replace namespace PHGenFit{class Track} by include to make ubuntu happy

simulation/g4simulation/g4mvtx/PHG4MvtxHitReco.cc
Fix an additional bug from pixel range in g4hit reconstruction. The range for the rows is 0 to 511 and for col 0 to 1023.
=> Fix pixel out of range bug

offline/packages/CaloReco/RawClusterBuilderTopo.cc, offline/packages/CaloReco/RawClusterBuilderTopo.h
3-D topoCluster building can now extend across IHCal<->EMCal boundary. Configurable user options to run topoClustering on HCal layers only, EMCal only, or all three layers.
=> Add EMCal layer in 3-D topoClustering

simulation/g4simulation/g4tpc/PHG4TpcSteppingAction.cc
Add momentum information to g4hits, similar to what is done in e.g. g4mvtx/PHG4MvtxSteppingAction.cc
This is useful for comparing truth momentum to fit for any track state.
=> added momentum information to g4hits

offline/packages/trackreco/PHActsTrkFitter.cc, offline/packages/trackreco/PHActsTrkFitter.h
the gcc 8.3 compilation crashed, this PR fixes this. It also removed all the unused includes which speeds up compilation
=> fix compilation error, exit() if layer is not found, fix up includes

offline/packages/trackreco/PHActsTrkFitter.cc, offline/packages/trackreco/PHActsTrkFitter.h
Moved TPC surface subdivisions to header file so that they are easier to find/change e.g. in constructor
=> Fixed cppcheck warnings, cleaned a few things up

offline/packages/trackbase/TrkrHitSetContainer.cc, offline/packages/trackbase/TrkrHitTruthAssoc.cc, simulation/g4simulation/g4tpc/PHG4TpcElectronDrift.cc, simulation/g4simulation/g4tpc/PHG4TpcPadPlaneReadout.cc, simulation/g4simulation/g4tpc/PHG4TpcPadPlaneReadout.h
This pull request improves the efficiency of the PHG4TPCElectronDrift subsysreco, which is the largest contributor to the time spend in digitizing and clustering G4Hits. 
Improvements in terms of cpu time vary from a factor two for high-mult events, and a factor five for low-multiplicity events.
First set of commits implement a known trick for efficiently filling maps and not do the search twice (find, then insert). This part dominates the high-multiplicity  digitization/clustering, and results in the x2 improvement above.  
Second set of commits get rid of using TF1 for calculating functions, and use direct implementation instead. It also uses a lookup table for gaussian calculation. This is what gives the x5 improvement for low multiplicity events.
All in all running digit+clustering on …
=> Master optimize tpc electron drift

simulation/g4simulation/g4detectors/PHG4Cell.h, simulation/g4simulation/g4detectors/PHG4CellDefs.cc, simulation/g4simulation/g4detectors/PHG4Cellv1.cc, simulation/g4simulation/g4detectors/PHG4Cellv1.h, simulation/g4simulation/g4detectors/PHG4CylinderCellReco.cc, simulation/g4simulation/g4histos/G4CellNtuple.cc
This PR fixes the case where the size of the cell exceeds the available range (basically giving a large value since you want only one bin). The G4CellNtuple code was updated to use the new PHG4Cells instead of the old PHG4CylinderCells.
=> Fix cellreco

offline/QA/modules/Makefile.am, offline/QA/modules/QAG4SimulationTracking.cc, offline/QA/modules/QAG4SimulationTracking.h, offline/QA/modules/QAG4SimulationUpsilon.cc, offline/QA/modules/QAG4SimulationUpsilon.h, offline/QA/modules/QAG4SimulationUpsilonLinkDef.h
Following @mitaylor ' #734, this pull request add a few more functions to tracking QA as below. 
The driving macro for plotting is here: 
* simulation: https://github.com/sPHENIX-Collaboration/macros/blob/master/macros/g4simulations/Fun4All_G4_sPHENIX.C 
* plotting: https://github.com/sPHENIX-Collaboration/macros/tree/tracking-low-occupancy-qa/macros/QA/tracking
Integration to Jenkins CI will start after merging. 
Events simulated are tracking only 40 pions 0.1-50 GeV/c with emphasize on the 0-2 GeV/c region + one Upsilon embedded.
=> Tracking QA

simulation/g4simulation/g4decayer/configure.ac, simulation/g4simulation/g4main/PHG4ParticleGeneratorVectorMeson.cc, simulation/g4simulation/g4main/PHG4ParticleGeneratorVectorMeson.h
Fix a memory leak from `PHG4ParticleGeneratorVectorMeson::trand` and trigger a newly implimented tracking QA check
=> Trigger a tracking QA check

simulation/g4simulation/g4tpc/PHG4TpcElectronDrift.cc, simulation/g4simulation/g4tpc/PHG4TpcElectronDrift.h, simulation/g4simulation/g4tpc/PHG4TpcPadPlaneReadout.cc
This is a emergency fix on the per-event-growing memory usage in the TPC digitization. 
In both recent tracking QA and jet-tracking production, the memory usage steadily grow over event number. Specifically, this is massif reported memory usage for tracking-QA macro over 100 events: 
https://github.com/sPHENIX-Collaboration/macros/blob/tracking-low-occupancy-qa/macros/g4simulations/Fun4All_G4_sPHENIX.C
This growth is not a memory leakage as valgrind test is fine. It trace to continued memory usage at this line: 
https://github.com/sPHENIX-Collaboration/coresoftware/blob/b59ecfa403d2e1e8510582ad8933f6f876f4a115/simulation/g4simulation/g4tpc/PHG4TpcPadPlaneReadout.cc#L463
It has three problems:
1. This ntuple supposedly only used in Verbosity debugging mode, but filled in nominal usage …
=> Fixing memory hosted eval NTuple in TPC digitization

offline/framework/fun4all/CreateSubsysRecoModule.pl, offline/framework/fun4all/Makefile.am
This PR add a script which creates a template for a subsysreco module - I was tired of always cutting and pasting this from somewhere. Also easier for new users. It takes the class name as argument and generates an include file and an implementation. If the --all option is used it also creates the standard autogen.sh and the appropriate configure.ac and Makefile.am
=> Create module script

offline/packages/trackreco/PHGenFitTrkFitter.cc
While tracking down a crash in trkreco (still unresolved) I stumbled across this potential one.
Without the added "else" condition, the null rf_track is inserted (unchecked) few lines below in the refit map
=> Fix certain crash if !rf_track && !_over_write_svtxtrackmap

offline/packages/trackreco/MakeActsGeometry.h, offline/packages/trackreco/Makefile.am, offline/packages/trackreco/PHActsSourceLinks.cc, offline/packages/trackreco/PHActsSourceLinks.h, offline/packages/trackreco/PHActsTracks.cc, offline/packages/trackreco/PHActsTracks.h, offline/packages/trackreco/PHActsTrkFitter.cc, offline/packages/trackreco/PHActsTrkFitter.h, offline/packages/trackreco/PHActsTrkProp.cc, offline/packages/trackreco/PHActsTrkProp.h
This PR introduces a module for Acts track propagation. Right now it does not actually do anything other than take prototracks and run the default acts track propagator on them. This will be changed once we actually have the appropriate things to put on the node tree when we have the updated acts code.
Tested with local Fun4All acts macro. Runs propagator and seems to function well. Will need to debug acts propagator once we update to acts master.
=> Acts track propagation

offline/packages/trackreco/ActsTrack.h, offline/packages/trackreco/Makefile.am, offline/packages/trackreco/PHActsTracks.h, offline/packages/trackreco/PHActsTrkFitter.cc, offline/packages/trackreco/PHActsTrkFitter.h, offline/packages/trackreco/PHActsTrkProp.cc, offline/packages/trackreco/PHActsTrkProp.h
Follow up PR to yesterday's that puts proto tracks from track propagation onto node tree. 
Also moved `struct ActsTrack` to it's own header file class, so that additional code can be added to it if needed and so that other classes which need it don't need to include an entire class (e.g. PHActsTracks) which is unnecessary extra code to include.
Will follow this PR with additional code once TPC Surfaces are added into the TGeo object and thus Acts builds them by default.
=> Track propagation

offline/QA/modules/QAG4SimulationTracking.cc, offline/QA/modules/QAG4SimulationTracking.h, offline/QA/modules/QAG4SimulationUpsilon.cc, offline/QA/modules/QAG4SimulationUpsilon.h
In high occupancy simulation, almost all g4track is matched with a reconstructed track via `track = trackeval->best_track_from(g4particle);`. However this only require the reco track used some of the hits from the g4track, and the reco track may also use many hits from other g4tracks.  This leads to arbitrarily high tracking efficiency. 
This PR change the matching to by default requiring both `track = trackeval->best_track_from(g4particle);` and `g4particle == trackeval->max_truth_particle_by_nclusters(track)`, ensuring most of the reco track's cluster comes from the g4track in study.  This requirement can also be turned off via a setter. 
This pull request will also be used in testing the new high-multiplicity tracking QA tests.
=> Default option to require unique matches for tracking efficiency QA

simulation/g4simulation/g4intt/PHG4InttDetector.cc, simulation/g4simulation/g4intt/PHG4InttSubsystem.cc
This PR removes the old INTT carbon stave design from PHG4InttDetector.cc and puts some hard coded parameters for the current stave design into PHG4InttSubsystem.cc. Parameters for the current design remain the same.  INTT G4 volumes after this change passed the overlap check.
=> INTT G4 detector clean-up

offline/packages/PHGeometry/macros/PHGeom_DSTInspection.C, offline/packages/trackreco/MakeActsGeometry.cc, offline/packages/trackreco/MakeActsGeometry.h, offline/packages/trackreco/PHActsSourceLinks.cc, offline/packages/trackreco/PHActsSourceLinks.h, offline/packages/trackreco/PHActsTrkFitter.cc, offline/packages/trackreco/PHActsTrkFitter.h, offline/packages/trackreco/PHActsTrkProp.cc, offline/packages/trackreco/PHActsTrkProp.h
This PR introduces a major change in the way the TPC is implemented in the Acts track fitting. 
Previously, the `Acts::Surfaces` for the TPC were built by us in `MakeActsGeometry`, and then clusters were connected to those surfaces via a map as with the other silicon geometries. The TPC geometry was not actually included in the Acts FW geometry building code; only the silicon was explicitly built within Acts.
This PR introduces a change to modify the `TGeoManager` to include boxes for the TPC. The `TGeoManager` is then passed to Acts (as before) to build all of the Acts tracking geometry straight from the `TGeoManager`. Now, the Acts FW code actually keeps track of the TPC boxes (rather than just us building them and passing them to Acts as plane surfaces) in the `TrackingGeometryPtr` …
=> TPC in Acts

offline/packages/trackreco/MakeActsGeometry.cc, offline/packages/trackreco/MakeActsGeometry.h
This PR adds a few lines that completely deletes the TGeoManager geometry and then recreates it from scratch, to deal with it's implementation as a singleton. In order to run the acts code in a local macro (since the main repository does not have acts macros yet), you need to add PHActsSourceLinks (which runs MakeActsGeometry) at the very beginning of the `Tracking_Reco` function stage in `G4_Tracking.C`.
=> Cleans up Geometry Creation

offline/packages/PHField/PHFieldCleo.cc
After the scrambling of the fieldmap - this PR adds a safety belt where coordinates are checked against expectations
=> check coordinates in outer loops during reading to avoid mishaps

simulation/g4simulation/g4detectors/PHG4GDMLDetector.cc, simulation/g4simulation/g4detectors/PHG4GDMLDetector.h, simulation/g4simulation/g4detectors/PHG4GDMLSubsystem.cc, simulation/g4simulation/g4detectors/ePHENIXRICHConstruction.cc, simulation/g4simulation/g4detectors/ePHENIXRICHConstruction.h, simulation/g4simulation/g4main/PHG4Utils.cc
1. Use gray color for Al material in G4 display
2. Allow GDML import detector to determine whether to include its Geant4 simulation geometry in the DST geometry for offline. The default behavior does not change (do export for offline use)
The driving factor is beam pipe extension's CAD model can not be exported to offline (tessellated object) and not useful for Kaman filter anyway. The central pipe in acceptance is exported separately. 
3. Allow gas RICH's beam pipe opening to follow the beam pipe extension's contour. 
Note this change require an update to the G4_RICH.C macro. 
See below the macros pull request for use
=> Few adjustment used in EIC beam pipe importing

offline/packages/PHGenFitPkg/GenFitExp/Makefile.am, offline/packages/PHGenFitPkg/PHGenFit/Fitter.cc, offline/packages/PHGenFitPkg/PHGenFit/Makefile.am, simulation/g4simulation/g4trackfastsim/Makefile.am
This PR adds $OFFLINE_MAIN/lib64 to the AM_LDFLAGS for packages linking against genfit. The default location of libgenfit2.so has changed from $OFFLINE_MAIN/lib to $OFFLINE_MAIN/lib64. Depending on the build type it is one or the other. With this change both locations are searched for libgenfit2.so
=> Genfit lib64

simulation/g4simulation/g4detectors/PHG4SectorConstructor.cc
@pinkenburg notice a new DST geometry translation error during the GDML to ROOT TGeo import state that is linked to the sector detectors as used in the EIC simulation. This is traced to the GDML export, where numerical value may change at the large digit and go beyond a 0 or 180 degree limit by a miniature amount. Therefore the related angle limit is recessed 0/pi by a small amount to avoid such problem
=> GDML export precision fix for sector detectors

simulation/g4simulation/g4detectors/PHG4CylinderDetector.cc, simulation/g4simulation/g4detectors/PHG4CylinderSubsystem.cc
This PR was long overdue - so far one had to set lengthviarapidity explicitly to zero if one set the length, otherwise the length was silently set to +- 1.1 rapidity coverage. That just confused everybody. Now if the length is set it is used and the lengthviarapidity flag is set to zero. If the length is not set the rapidity coverage is chosen, so the old default behavior is preserved. The length, thickness and radius are initialized to NAN, before the cylinder is created those values are checked to be finite
=> Change lengthviarapidity default

offline/packages/trackreco/PHActsTracks.cc
This PR fixes the track covariance matrix rotation to the proper basis that Acts expects. Previously we had a place holder to simply calculate the diagonal elements from the sPHENIX covariance matrix and hand them to Acts. This PR actually rotates the covariance matrix from global (sPHENIX) coordinates to local (Acts) coordinates, and in the proper basis that Acts expects.
=> Track covariance

offline/database/PHParameter/PHParameters.cc, offline/database/PHParameter/PHParameters.h, offline/database/PHParameter/PHParametersContainer.cc, offline/database/PHParameter/PHParametersContainer.h, offline/database/pdbcal/base/PdbParameterMapContainer.cc, offline/database/pdbcal/base/PdbParameterMapContainer.h, simulation/g4simulation/g4detectors/PHG4CylinderSubsystem.cc, simulation/g4simulation/g4detectors/PHG4CylinderSubsystem.h, simulation/g4simulation/g4detectors/PHG4DetectorGroupSubsystem.cc, simulation/g4simulation/g4detectors/PHG4DetectorGroupSubsystem.h, simulation/g4simulation/g4detectors/PHG4DetectorSubsystem.cc, simulation/g4simulation/g4detectors/PHG4DetectorSubsystem.h
We had a hole in the logic saving the parameters on the node tree (and subsequent DST). It is possible for a subsystem to change the parameters. E.g. the cylinders do that to pass the length calculated from the rapidity coverage or set the lengthviarapidity to 0 (defaults to 1, bad idea to begin with) if the length is set in the macro.
Now the parameters on the node tree are updated with changes done by the subsystem. This is implemented for the PHG4DetectorSubsystem as well as for the PHG4DetectorGroupSubsystem (the later one only being used by the PSTOF)
=> Update params nodetree

simulation/g4simulation/g4trackfastsim/PHG4TrackFastSim.cc, simulation/g4simulation/g4trackfastsim/PHG4TrackFastSim.h
`PHG4TrackFastSim` is used to string `PHG4Hit` from various detectors to make fast digitization and tracking pattern recognition, which is followed up with a Kalman filter fit via GenFit2. This pull request order the `PHG4Hit` by their G4 truth time order, which relax the requirement of inserting the detectors in the order of track traversing. It also allow processing multiple hits in the same layer in a proper order. 
Thanks discussion with Chris Pinkenburg and Reynier Cruz Torres
=> G4hit-based fast tracking tuning

offline/QA/modules/QAG4SimulationIntt.cc, offline/QA/modules/QAG4SimulationMvtx.cc
This PR fixes a bug introduced when defining QA histograms for INTT and MVTX.
For clarity, the detector name should be in the histogram title, not on the x axis title. Sorry.
=> Put Detector name in histogram title rather than x axis label

simulation/g4simulation/g4trackfastsim/PHG4TrackFastSim.cc
Fixed bug when smearing the hit coordinate in the case of a cylindrical detector. The z coordinate was not being smeared at all before. Discussed with Chris Pinkenburg and Jin Huang.
=> Fixed bug when smearing hit coordinate in cylinder

offline/packages/NodeDump/DumpSvtxTrackMap.cc, offline/packages/trackbase_historic/SvtxTrackState.h, offline/packages/trackbase_historic/SvtxTrackState_v1.h, simulation/g4simulation/g4trackfastsim/PHG4TrackFastSim.cc, simulation/g4simulation/g4trackfastsim/PHG4TrackFastSim.h
This PR adds the capability to add any cylinder and vertical plane as projection point to the fast tracking. The first track state (by default at the origin at pathlength=0) had the default name "UNKNOWN", that was changed to ORIGIN. Smearing with the detector resolution can be disabled for debugging purposes via a flag (default is smearing=on). sPHENIX naming conventions were applied. This needed an adjustment of the svtxtrackstate interface (set_name from string & to const string &). Remove uses of .c_str() (node methods take strings as arguments)
=> Add any projections capability to kalman

offline/packages/trackreco/MakeActsGeometry.cc, offline/packages/trackreco/PHActsSourceLinks.cc, offline/packages/trackreco/PHActsSourceLinks.h, offline/packages/trackreco/PHActsTracks.cc, offline/packages/trackreco/PHActsTracks.h, offline/packages/trackreco/PHActsTrkFitter.cc, offline/packages/trackreco/PHActsTrkFitter.h, offline/packages/trackreco/PHActsTrkProp.cc
This PR introduces the code that actually runs the Acts track fitter. It updates the `SvtxTrack` associated with the Acts track so that subsequent analysis can be performed with the `SvtxEvaluator`. 
The PR also changes the default number of z TPC surfaces from 11 to 1, which decreases the single track fit time by an order of magnitude. This is approximately what Acts has advertised for a single muon track in ATLAS.
The track fitter is still not ready for production (e.g. public macro) use as the covariance matrix rotation is still not correct. We are waiting for some guidance from Andi on what Acts expects. Nonetheless, this PR puts a functional version of the Acts track fitting into the repository.
=> Acts Track Fitter 

simulation/g4simulation/g4trackfastsim/PHG4TrackFastSim.h
This PR puts an include back which is needed to run the container. I accidentally removed this in the last cleanup
=> put include back - ubuntu container need this

offline/packages/PHTpcTracker/externals/nanoflann.hpp
This adds
// cppcheck-suppress *
before the line with the warning which suppresses all warnings (sadly I cannot find docs with the actual names of the warnings to be used for the suppression so this suppresses all
=> suppress cppcheck warnings

offline/packages/tpc/TpcClusterizer.cc, offline/packages/tpc/TpcClusterizer.h, simulation/g4simulation/g4eval/SvtxClusterEval.cc, simulation/g4simulation/g4eval/SvtxEvaluator.cc
Introduced a fiducial cut to remove clusters close to the TPC sector boundaries. The default value is +/- 0.5 cm around the boundary center. The simulation was previously unrealistic, since it did not contain the 5 mm sector boundary dead gap. There are now no clusters that cross the sector gaps. Also changed the search window in the TPC clusterizer for local maxima to +/- 2 bins in z and phi. This reduces the number of duplicate and split clusters caused by fluctuations in the adc values, which confuse the cluster seeding algorithm. 
The dominant cause of split clusters is now tracks passing through the membrane with charge deposited on both sides of the membrane. I did not address this. 
There is a slight drop in tracking efficiency, but otherwise performance is unaffected - see plots …
=> Cluster duplication

offline/packages/trackreco/ActsCovarianceRotater.cc, offline/packages/trackreco/ActsCovarianceRotater.h, offline/packages/trackreco/MakeActsGeometry.cc, offline/packages/trackreco/Makefile.am, offline/packages/trackreco/PHActsTracks.cc, offline/packages/trackreco/PHActsTracks.h, offline/packages/trackreco/PHActsTrkFitter.cc, offline/packages/trackreco/PHActsTrkFitter.h, offline/packages/trackreco/PHActsTrkProp.cc, offline/packages/trackreco/PHActsTrkProp.h
This is (yet another) PR for the Acts covariance matrix. Introducing it now because it is at least a step in the right direction, but there is still clearly something incorrect with the fitting. Many fits fail within Acts, and many return values that are not what one would expect. However, there were several changes to the covariance code design, so I thought they should be put into the repository.
These plots show a 5 pion event thrown between 1 and 6 GeV in pT within the nominal eta and phi acceptance. The plots show improvement as they are roughly centered at 1 or 0, but clearly there is still something that is not correct as the tails to these distributions are far too large. Regardless the width of the central gaussian is too large for what should be expected for the tracking. …
=> Acts covariance

offline/packages/PHTpcTracker/Makefile.am, offline/packages/PHTpcTracker/PHTpcTracker.cc, offline/packages/PHTpcTracker/PHTpcTracker.h
Turn PHTpcTracker into a seeding module to fit into the general tracking framework. 
Efficiency looks very promising, timing not so much.
=> make PHTpcTracker a seeding module

simulation/g4simulation/g4mvtx/PHG4MvtxDigitizer.cc, simulation/g4simulation/g4mvtx/PHG4MvtxDigitizer.h
Add a pixel energy threshold for each mvtx hit. 
Hits with energy under threshold will be removed.
This change is to match the cluster size distribution in simulation with those from test beam data.
=> Mvtx energy threshold

offline/packages/trackreco/ActsEvaluator.cc, offline/packages/trackreco/ActsEvaluator.h
This PR adds the global track fit results to the ActsEvaluator tree for further analysis. I also fixed the comments in the header to be doxygen style.
=> add global track fit results to tree

offline/packages/trackreco/PHActsSourceLinks.cc
@adfrawley noticed that we were still using our local calculation for the MVTX source links. The geometry has since been fixed, so we just use the Acts coordinate transformation (which yields the same result as ours, modulo units which were not taken into account here).
=> Fix mvtx source link bug

offline/packages/trackreco/ActsEvaluator.cc, offline/packages/trackreco/ActsEvaluator.h
This PR puts the proto track information that is fed into the Acts Fitter onto the ActsEvaluator output tree. This can allow for all the hit information to be analyzed after the fact, i.e. all hits/info that goes into the fitter and all hits/info that come out of the fitter.
This PR replaces [PR838](https://github.com/sPHENIX-Collaboration/coresoftware/pull/838) which failed due to me testing on an older version of `coresoftware` as there currently is an issue between the communication of `PHGenFitTrkProp` and `PHActsTrkFitter`.
=> Acts proto track eval

simulation/g4simulation/g4jets/JetInput.h, simulation/g4simulation/g4jets/TowerJetInput.cc, simulation/g4simulation/g4jets/TowerJetInput.h, simulation/g4simulation/g4jets/TrackJetInput.cc, simulation/g4simulation/g4jets/TrackJetInput.h, simulation/g4simulation/g4jets/TruthJetInput.cc, simulation/g4simulation/g4jets/TruthJetInput.h, simulation/g4simulation/g4main/PHG4TruthInfoContainer.cc
This PR replaces the hardcoded Track Node Name by an argument to the ctor of TrackJetInput. This should help getting rid of these svtxtrack maps. It defaults to SvtxTrackMap so it does not break old code/macros
=> Remove hardcoded tracknode name

offline/packages/PHGenFitPkg/PHGenFit/SpacepointMeasurement.cc, offline/packages/PHGenFitPkg/PHGenFit/SpacepointMeasurement.h, offline/packages/PHTpcTracker/PHTpcTrackFollower.cc, offline/packages/PHTpcTracker/PHTpcTracker.cc, offline/packages/trackreco/PHCASeeding.cc, offline/packages/trackreco/PHGenFitTrkFitter.cc, offline/packages/trackreco/PHGenFitTrkProp.cc, offline/packages/trackreco/PHGenFitTrkProp.h, simulation/g4simulation/g4eval/SvtxEvaluator.cc
Revert PHGenFitTrkProp to working state for ACTS tracking initialisation
Extend SpacepointMeasurement with constructor for asymmetric errors for use as 
beamsport constraint
Minor touchup of PHTpcTracker
Printout controll in PHCASeeding.cc
Fix indention in PHGenFitTrkFitter.cc for better readability
Minor fix of ntuple ordering in SvtxEvaluator. 
Ntuple definition and filling were out of sync when scan_for_embedded is set to false.
=> PHGenFitTrkProp fix

offline/framework/phool/PHLog.h
This PR changes the default priority for log4cpp messages to print on the screen from INFO (everything) to FATAL (nothing)
=> only print fatal messages

offline/packages/trackreco/ActsEvaluator.cc
Some branches were accidentally constructed as leaves, instead of branches. This PR fixes that.
=> Fix branches in Evaluator Tree

offline/packages/trackreco/ActsEvaluator.cc, offline/packages/trackreco/ActsEvaluator.h
This PR adds the 3D DCA to the acts evaluator, following a similar procedure in `PHGenFitTrkFitter`
=> Add DCA to acts eval

simulation/g4simulation/g4mvtx/PHG4MvtxDigitizer.cc
This prevents having dandling keys in the truth association map.
Similar code already exists for the TPC.
=> when removing hits because below threshold, also remove from hit truth association map

offline/packages/micromegas/Makefile.am, offline/packages/micromegas/MicromegasClusterizer.cc, offline/packages/micromegas/MicromegasClusterizer.h, offline/packages/micromegas/MicromegasTile.h, offline/packages/micromegas/MicromegasTileLinkDef.h, simulation/g4simulation/g4dst/Makefile.am, simulation/g4simulation/g4micromegas/Makefile.am, simulation/g4simulation/g4micromegas/PHG4MicromegasDetector.cc, simulation/g4simulation/g4micromegas/PHG4MicromegasDigitizer.cc, simulation/g4simulation/g4micromegas/PHG4MicromegasDigitizer.h, simulation/g4simulation/g4micromegas/PHG4MicromegasHitReco.cc, simulation/g4simulation/g4micromegas/PHG4MicromegasSteppingAction.h, simulation/g4simulation/g4micromegas/PHG4MicromegasSubsystem.h
The micromega geometry gave readback warnings since its helper class MicromegasTile did not have a Streamer. Added the micromega io lib to libg4dst, fixed includes according to include what you use. Enabling the micromegas crashes the tracking evaluator (g4hit null pointer dereference)
=> Fix micromega readback

offline/packages/PHTpcTracker/PHTpcSeedFinder.cc
This PR contains a fix from Dmitry for the leak in PHTpcSeedFinder.cc (tracks need to be deleted if removed from the candidate list)
=> delete track candidate to fix memory leak

offline/packages/trackreco/MakeActsGeometry.cc, offline/packages/trackreco/PHActsSourceLinks.cc
This PR introduces some additional verbosity checks for the TPC cluster position transforms. It also changes the default number of azimuthal TPC surfaces per sector in Acts to 12. This ensures that there is not a mismatch between the global -> local -> global position transforms for the TPC clusters that are introduced by the fact that we are approximating the TPC with flat surfaces.
=> Change TPC Azimuthal Surfaces

simulation/g4simulation/g4detectors/BeamLineMagnetDetector.cc, simulation/g4simulation/g4detectors/BeamLineMagnetSubsystem.cc, simulation/g4simulation/g4main/EicEventHeader.cc, simulation/g4simulation/g4main/PHG4ParticleGeneratorD0.cc, simulation/g4simulation/g4main/PHG4ParticleGeneratorVectorMeson.cc, simulation/g4simulation/g4main/PHG4ParticleGeneratorVectorMeson.h, simulation/g4simulation/g4main/PHG4TruthEventAction.cc, simulation/g4simulation/g4main/ReadEICFiles.cc
This PR makes some minor mods to the upsilon generator: added simplified interface to select decay (just electron or muon), checks for only valid decays (e+ & e-, mu+ & mu-), use x*x instead of pow(x,2), declare protected datamembers private, Some include what you use suggestions were added for good measure
=> Simplify vmeson gen

offline/packages/trackreco/ActsEvaluator.cc, offline/packages/trackreco/ActsEvaluator.h, offline/packages/trackreco/ActsTrack.h, offline/packages/trackreco/MakeActsGeometry.cc, offline/packages/trackreco/PHActsTracks.cc, offline/packages/trackreco/PHActsTracks.h, offline/packages/trackreco/PHActsTrkFitter.cc, offline/packages/trackreco/PHActsTrkProp.cc
This PR changes the Acts track fitting/propagation to fit with respect to the initial track vertex estimate given by the `PHInitVertexing` that is used (either `PHTruthVertexing` or `PHInitZVertexing`). Previously we were just fitting wrt to the global origin (0,0,0), which in discussion with the Acts developers is not the intended use of the fitter.
This PR also introduces a small change in commit `ee2f314` to return a `nullptr` instead of `exit` in the event an appropriate surface for a TPC cluster isn't found. This way the cluster is just skipped and not added to the fitting procedure rather than causing the whole code to exit.
=> Fit WRT Initial Vertex Estimate

offline/packages/tpc/TpcClusterizer.cc
This is the second attempt at simplifying the TPC cluster error calculatio code.
First commit is similar to the original attempt, but with better handling of size one cluster. Not identifying size-one cluster due to numerical divergences is the reason why the first attempt lead to a deterioration of the tracking efficiency. The clusters positions and errors after this first commit are identical to what they were before with simpler and more robust code
The second commit remove hits for which adc - pedestal is <0. This fixes cases for which the resulting cluster error square was negative, and the corresponding error -nan. 
This has a bigger impact on all cluster errors, hopefully for the best. This should hopefully lead to either identical or improved performances. If not, this one can …
=> Tpc cluster error v2

simulation/g4simulation/g4main/PHG4Particlev2.cc
It appears that PHG4Particlev2 constructor from pointer to base class was not propagating the track id, vertex id, primary id and energy, resulting in having the values being reset when doing a deep copy of the object. I don't think this is intentinal.
This PR fixes that.
=> Fixed copy-from-baseclass constructor

offline/packages/trackreco/ActsEvaluator.cc, simulation/g4simulation/g4eval/SvtxClusterEval.cc, simulation/g4simulation/g4eval/SvtxClusterEval.h, simulation/g4simulation/g4eval/SvtxEvaluator.cc, simulation/g4simulation/g4eval/SvtxEvaluator.h, simulation/g4simulation/g4eval/SvtxTruthEval.cc, simulation/g4simulation/g4eval/SvtxTruthEval.h
Substantially reorganized SvtxEvaluator and friends. Moved the functionality to make TPC truth clusters to SvtxTruthEval and added methods to get them and their associated truth hits. The truth clusters are now returned in a TrkrCluster map. Added some functionality to SvtxClusterEval to get the best matching reco cluster corresponding to a truth cluster, and also the best matching truth cluster corresponding to a reco cluster. Truth/reco cluster matching still uses the cluster/hit/g4hit tracing from the TrkrClusterHitAssoc and TrkrHitTruthAssoc maps, but I also added a 4-sigma cluster position cut. When matching to a reco cluster, only one truth cluster is chosen - the one with the largest truth energ
[cluster_efficiency_reorganization.pdf](https://github.com/sPHENIX-Collaboration/coresof …
=> Reorganize svtxeval

generators/phhepmc/PHHepMCGenEventMap.cc, generators/phhepmc/PHHepMCGenEventMap.h, simulation/g4simulation/g4main/PHG4HitContainer.cc
Two optimizations when inserting objects into maps, to avoid multiple unnecessary map lookups 
For PHHepMCGenEventMap, also simplified constructor, copy constructor and assignment operator.
=> Optimize map insertion

simulation/g4simulation/g4main/PHG4Hitv1.cc, simulation/g4simulation/g4main/PHG4Hitv1.h
variable showerid was never properly initialized in G4Hitv1 constructor, nor reset in the ::Reset method.
I took the opportunity of fixing this to modernize the code: 
- moved all member initialization to the header (this should help not making the same mistake again)
- marked the constructor (and the destructor) as "default" since they are both empty.
=> Fixed uninitialized variable and modernized

offline/packages/trackreco/ActsCovarianceRotater.cc, offline/packages/trackreco/ActsCovarianceRotater.h, offline/packages/trackreco/MakeActsGeometry.cc, offline/packages/trackreco/PHActsSourceLinks.cc, offline/packages/trackreco/PHActsTrkFitter.cc
This PR fixes a bug in the track seed covariance rotation. Previously rotating to q/p was causing the covariance to be too small, which is why the track fit seemed to just copy the input track seed. This fix improves the track pT resolution to something that is at least the right shape. The resolution is still on the high side, though.
=> Track Momentum Covariance Bug fix

offline/QA/modules/Makefile.am, offline/QA/modules/QAG4SimulationTpc.cc, offline/QA/modules/QAG4SimulationTpc.h
Added a TPC cluster QA module. It uses the recently added SvtxEvaluator methods for getting TPC truth clusters and matched reco clusters. It calculates cluster efficiency, as well as making histograms of cluster reconstruction performance. There will be an accompanying pull request for the associated macro changes.
=> Tpc cluster qa

generators/phhepmc/PHHepMCGenEvent.cc, offline/framework/ffaobjects/EventHeader.h, offline/framework/ffaobjects/EventHeaderv2.cc, offline/framework/ffaobjects/EventHeaderv2.h, offline/framework/ffaobjects/EventHeaderv2LinkDef.h, offline/framework/ffaobjects/Makefile.am, offline/framework/ffaobjects/SyncObject.h, simulation/g4simulation/g4main/Fun4AllDstPileupInputManager.cc, simulation/g4simulation/g4main/Fun4AllDstPileupInputManager.h, simulation/g4simulation/g4main/Fun4AllDstPileupInputManagerLinkDef.h, simulation/g4simulation/g4main/Makefile.am, simulation/g4simulation/g4main/PHG4VertexSelection.cc, simulation/g4simulation/g4main/PHG4VertexSelection.h, simulation/g4simulation/g4main/PHG4VertexSelectionLinkDef.h
This pull request implements a DST input manager that is capable of merging multiple single collision Hijing events according to a timestamp (== bunch crossing ids) sequence, to form full events (signal + pileup). The timestamp sequence must be provided externally. 
in details:
- added EventHeaderv2 class that derives from v1 and includes the bunchcrossing id
- added a subsysreco (PHG4VertexSelection) used to select HIJING events with vertex withing +/-10cm. Those events are used as "trigger" events to which pileup events are added 
- added Fun4AllDstPileupInputManager that does all the heavy lifting. 
It is duplicated from Fun4AllDstInputManager. The merging of the events is achieved using two PHNodeIOManagers, one for the signal event and one for the pile-up events that are merged to …
=> Implement input manager to merge hijing events

simulation/g4simulation/g4micromegas/PHG4MicromegasHitReco.cc, simulation/g4simulation/g4micromegas/PHG4MicromegasHitReco.h
Consistently with what is done with INTT
Needed to catch in bunch pileup hits
=> changed tmin to -20ns in order to catch inbunch pileup hits with negative time offsets.

simulation/g4simulation/g4detectors/PHG4CylinderSteppingAction.cc, simulation/g4simulation/g4detectors/PHG4CylinderSteppingAction.h, simulation/g4simulation/g4detectors/PHG4CylinderSubsystem.cc, simulation/g4simulation/g4detectors/PHG4CylinderSubsystem.h, simulation/g4simulation/g4detectors/PHG4DetectorSubsystem.h
This PR fixes a hit position check in the cylinder stepping action (the hit z-position is compared to the z-position of the cylinder). This is valid if the cylinder is put into the world volume. If the cylinder is put into a mother volume which is shifted in z this check fails since it uses the world coordinates from our g4hits.
I don't want to remove this check (you never know) so I added a bool hasMotherSubsystem() method to the stepping action (which uses the GetMotherSubsystem() method in PHG4Subsystem). This needed adding a pointer to the subsystem which creates the stepping action.
Also removed obsolete CINT checks and defines which made root5 happy
=> Fix cylinder

offline/packages/trackreco/ActsEvaluator.cc, offline/packages/trackreco/ActsEvaluator.h, offline/packages/trackreco/MakeActsGeometry.cc, offline/packages/trackreco/Makefile.am, offline/packages/trackreco/PHActsTrkFitter.cc, offline/packages/trackreco/PHActsTrkFitter.h, offline/packages/trackreco/tgeo-sphenix.response
This PR updates our Acts modules to reflect changes in our Acts builds after updating to Acts v0.30. These changes should be merged together with this [PR](https://github.com/sPHENIX-Collaboration/acts/pull/16) in our Acts fork.
One change worth noting in this PR is that the geometry options required to build the sPHENIX-Acts geometry are now contained in a response file that is read in. This keeps the options archived as a data file and no longer hard coded in `MakeActsGeometry.cc`.
=> Update to Actsv0.30

offline/packages/trackreco/Makefile.am
This PR adds the Acts TGeo response file into the Makefile so that it is installed into `$OFFLINE_MAIN/share` for access by the Fun4All macros.
=> Add Acts TGeo Response File

offline/packages/CaloReco/BEmcCluster.cc, offline/packages/CaloReco/BEmcProfile.cc, offline/packages/CaloReco/BEmcProfile.h, offline/packages/CaloReco/BEmcRec.cc, offline/packages/CaloReco/BEmcRec.h, offline/packages/CaloReco/BEmcRecCEMC.cc, offline/packages/CaloReco/BEmcRecCEMC.h, offline/packages/CaloReco/BEmcRecEEMC.cc, offline/packages/CaloReco/BEmcRecEEMC.h, offline/packages/CaloReco/BEmcRecFEMC.cc, offline/packages/CaloReco/BEmcRecFEMC.h, offline/packages/CaloReco/Makefile.am, offline/packages/CaloReco/RawClusterBuilderTemplate.cc, offline/packages/CaloReco/RawClusterBuilderTemplate.h
Modifications to RawClusterBuilderTemplate framework which should not change anything in clustering itself, and will slightly change the output value of "prob" parameter: 
1. RawClusterBuilderTemplate.h,cc: Get collision vertex from g4vertex/GlobalVertex and pass it to clustering (output cluster "prob" parameter is affected); reserve a switch to alternative way for shower profile prediction (for future use)
2. BEmcProfile.h,cc: Introduce an alternative way for shower profile prediction (for future use)
3. BEmcRec{CEMC,EEMC,FEMC}.h,cc: some restructuring between base class and inherited classes; reserve a switch to alternative way for shower profile prediction (for future use)
4. BEmcCluster.cc: Minor modification to be aligned with modifications in BEmcRec (more parameters in …
=> Em clusterizer

simulation/g4simulation/g4main/Fun4AllDstPileupInputManager.cc
argh ...
Get new embeded id from new event rather than old one. 
This ensures that the right embedding id is stored in the truth info map
=> Fix bug when propagating embed id to merged Hijing events

offline/packages/trackreco/ActsEvaluator.cc, offline/packages/trackreco/Makefile.am, offline/packages/trackreco/PHActsTrkFitter.cc, offline/packages/trackreco/PHActsVertexFitter.cc, offline/packages/trackreco/PHActsVertexFitter.h
This PR introduces a final acts vertex fitting module. Provided a list of tracks, the vertex fitter will return a single fitted vertex. No analysis has been performed to determine how good the vertex fit actually is, given the input tracks.
=> Acts vertex fitting

offline/packages/trackreco/ActsEvaluator.cc, offline/packages/trackreco/ActsEvaluator.h, offline/packages/trackreco/PHActsTrkFitter.cc, offline/packages/trackreco/PHActsTrkFitter.h
This PR improves the tracking efficiency at high pT by resetting the covariance matrix before it goes into the Acts KF. Acts (evidently) relies heavily on the covariance being something that is large enough that it has room to work within but also small enough such that it can actually find the propagation steps. 
Previously the covariance was too large and thus at high pT Acts would quit the propagation after a couple of steps as it had too much room to work within. This PR sets the covariance to almost the same value used in the Acts unit tests, and it improves the fit quality and the tracking efficiency at high pT substantially (previously the track efficiency would drop to ~70% at high pT, see here 
[ptEff.pdf](https://github.com/sPHENIX-Collaboration/coresoftware/files/5069951/ptEff.p …
=> Track efficiency

offline/packages/trackreco/ActsEvaluator.cc, offline/packages/trackreco/ActsEvaluator.h, offline/packages/trackreco/ActsTransformations.cc, offline/packages/trackreco/ActsTransformations.h, offline/packages/trackreco/PHActsTrkFitter.cc, offline/packages/trackreco/PHActsTrkFitter.h, offline/packages/trackreco/PHActsTrkProp.cc, offline/packages/trackreco/PHActsTrkProp.h
This PR updates the CKF module and ActsEvaluator for running the Acts CKF track finding + fitting and performing subsequent analysis on the results. The main updates are filling the SvtxTrack objects with the output from the CKF, and constructing a truth-reco track matching map so that the ActsEvaluator can properly evaluate the fit results.
=> CKF Updates

simulation/g4simulation/g4intt/PHG4InttDetector.cc, simulation/g4simulation/g4intt/PHG4InttSubsystem.cc, simulation/g4simulation/g4mvtx/PHG4MvtxDetector.cc, simulation/g4simulation/g4mvtx/PHG4MvtxDetector.h, simulation/g4simulation/g4mvtx/PHG4MvtxSubsystem.cc
In this PR we moved the cylinder mvtx outer shell volume implemented by the INTT's group to MVTX detector. We also introduced a beta MVTX EndWheels (an ALICE ITS like) of Carbon PEEK. EndWheel volumes are shifted by 2-3 cm to avoid overlaps. (new merge attempt after alteration in EIC MVTX model)
=> Move MVTX outer shell from INTT and include beta version for EndWheels

offline/packages/trackreco/ActsEvaluator.cc, offline/packages/trackreco/PHActsTrkProp.cc, offline/packages/trackreco/PHActsTrkProp.h, simulation/g4simulation/g4eval/SvtxEvaluator.cc
This PR modifies the source link selection criteria for the CKF. The module now has setters which can be used to test different "search windows" for the CKF. It also adds a layer modifier so that chi2 criteria can be set for a given layer in the silicon or TPC.
=> Source Link Selection

offline/framework/phool/Makefile.am, offline/framework/phool/PHFlag.h, offline/framework/phool/PHFlagLinkDef.h, offline/framework/phool/PHMessageLinkDef.h, offline/framework/phool/PHObject.h, offline/framework/phool/PHPointerListIterator.h, offline/framework/phool/PHRandomSeedLinkDef.h, offline/framework/phool/PHTimeServer.h, offline/framework/phool/PHTimeServerLinkDef.h, offline/framework/phool/configure.ac, offline/framework/phool/recoConstsLinkDef.h, simulation/g4simulation/g4trackfastsim/Makefile.am, simulation/g4simulation/g4trackfastsim/PHG4TrackFastSimEval.cc, simulation/g4simulation/g4trackfastsim/PHG4TrackFastSimEval.h, simulation/g4simulation/g4trackfastsim/PHG4TrackFastSimEvalLinkDef.h, simulation/g4simulation/g4trackfastsim/PHG4TrackFastSimLinkDef.h, simulation/g4simulation/g4trackfastsim/configure.ac
This PR removes the limit on the number of projections in the evaluator. It now uses vector<vector<float>> instead of hardcoded arrays. It also only adds existing g4 hits to the branches of the output ttree (now done in InitRun() where the g4hit nodes are settled and we know their names)
Added StringFlag methods to PHFlag to stay with more modern times. Internally they just call the old CharFlags
Removed root5 remnants from packages offline/framework/phool and simulation/g4simulation/g4trackfastsim
=> Unlimited Projections

offline/packages/PHTpcTracker/externals/kdfinder.hpp, offline/packages/trackreco/MakeActsGeometry.cc, offline/packages/trackreco/PHActsSourceLinks.cc, offline/packages/trackreco/PHActsSourceLinks.h, offline/packages/trackreco/PHActsTracks.cc, offline/packages/trackreco/PHActsTrkProp.cc, offline/packages/trackreco/PHActsTrkProp.h
This PR implements an update to the MVTX geometry unpacking when constructing the map between `TrkrDef::hitsetkey` and MVTX `TGeoNode`. The MVTX geometry was recently changed to be in a wrapper, so this PR unwraps the wrapper to grab the relevant nodes.
Note - this is branched off of [PR 901](https://github.com/sPHENIX-Collaboration/coresoftware/pull/901). So, the commits that are unrelated to this particular problem that are currently shown at the opening of the PR will go away once 901 is merged.
=> Mvtx Acts Geometry Update

offline/packages/PHTpcTracker/externals/kdfinder.hpp, offline/packages/trackreco/PHActsSourceLinks.cc, offline/packages/trackreco/PHActsSourceLinks.h, offline/packages/trackreco/PHActsTracks.cc, offline/packages/trackreco/PHActsTrkProp.cc, offline/packages/trackreco/PHActsTrkProp.h
This PR implements changes to have the Acts CKF run with the TpcTracker seeder. The fitting produces good fits in momentum but not in track position, which probably is related to the poor TpcTracker seed position. This is a problem we will have to discuss with all of the TPC seeders.
This PR also implements the option to add the event vertex as a measurement to add to the fitting procedure. The measurement is added and the CKF recognizes this; however, we will have to iterate with the ACTS developers on how to force the propagator to "see" this measurement as it is not part of the `Acts::TrackingGeometry`. Currently the CKF only visits surfaces associated to the geometry and not isolated surfaces (e.g. the one associated to the vertex measurement).
One other issue with TPC seeders that …
=> Tpc tracker interface and Vertex SL

simulation/g4simulation/g4tpc/PHG4TpcPadPlaneReadout.cc
This ensures that the average charge per particle per pad is kept unchanged.
The ratio between old and new gain correspond to the inverse ratio of the average number of primary electron per cm for a MIP
=> Update gain to match gas change from Ne/CF4 90/10 to Ne/CF4 50/50

offline/packages/trackreco/Makefile.am, offline/packages/trackreco/PHTruthSiliconAssociation.cc, offline/packages/trackreco/PHTruthSiliconAssociation.h, offline/packages/trackreco/PHTruthTrackSeeding.cc
This module uses truth information to add the silicon clusters to seed tracks from PHTpcTracker or PHCASeeding. Those two seeding modules find and fit only TPC clusters. This new module allows PHActsTrkFitter to fully fit tracks from the two CA seeders without running PHGenFitTrkProp in between. Tested and working with either PHTpcTracker of PHCASeeding as input. Performance plots and comparison to the Hough seeding + Genfit propagation and fitting are attached.
[acts_truth_silicon_genfit_comparison_eff.pdf](https://github.com/sPHENIX-Collaboration/coresoftware/files/5178430/acts_truth_silicon_genfit_comparison_eff.pdf)
[acts_truth_silicon_genfit_comparison_ptres.pdf](https://github.com/sPHENIX-Collaboration/coresoftware/files/5178432/acts_truth_silicon_genfit_comparison_ptres.pdf) …
=> Associate silicon truth clusters

offline/packages/tpc/TpcClusterizer.cc, offline/packages/tpc/TpcClusterizer.h
Eliminates duplicates and should provide better cluster splitting capability
TpcTracker tpc only reconstruction efficiency is veru high in high multiplicity qa events:
Obvious cluster splitting issues should be fixed:
Before:
=> New Clusterizer

offline/packages/trackreco/ActsEvaluator.cc, offline/packages/trackreco/ActsEvaluator.h, offline/packages/trackreco/ActsTrack.h, offline/packages/trackreco/ActsTransformations.cc, offline/packages/trackreco/ActsTransformations.h, offline/packages/trackreco/MakeActsGeometry.cc, offline/packages/trackreco/MakeActsGeometry.h, offline/packages/trackreco/Makefile.am, offline/packages/trackreco/PHActsSourceLinks.cc, offline/packages/trackreco/PHActsSourceLinks.h, offline/packages/trackreco/PHActsTracks.cc, offline/packages/trackreco/PHActsTracks.h, offline/packages/trackreco/PHActsTrkFitter.cc, offline/packages/trackreco/PHActsTrkFitter.h, offline/packages/trackreco/PHActsTrkProp.cc, offline/packages/trackreco/PHActsTrkProp.h, offline/packages/trackreco/PHActsVertexFitter.cc, offline/packages/trackreco/PHActsVertexFitter.h
This PR introduces necessary changes to run the tracking with the new version of Acts v0.32. The outward API changed significantly in the last few versions of Acts, so there are a lot of changes to our code that reflect these API changes. Some plots to demonstrate performance in 100 muon events with hough seeding + PHGenFitTrkProp + PHActsTrkFitter:
[dcarphi.pdf](https://github.com/sPHENIX-Collaboration/coresoftware/files/5195598/dcarphi.pdf)
[dcaz.pdf](https://github.com/sPHENIX-Collaboration/coresoftware/files/5195599/dcaz.pdf)
[eff.pdf](https://github.com/sPHENIX-Collaboration/coresoftware/files/5195600/eff.pdf)
[pt2d.pdf](https://github.com/sPHENIX-Collaboration/coresoftware/files/5195601/pt2d.pdf)
[ptscale.pdf](https://github.com/sPHENIX-Collaboration/coresoftware/files/5195602/ptscal …
=> Acts v0.32

simulation/g4simulation/g4eval/JetRecoEval.cc, simulation/g4simulation/g4eval/JetRecoEval.h, simulation/g4simulation/g4eval/JetTruthEval.cc, simulation/g4simulation/g4eval/JetTruthEval.h, simulation/g4simulation/g4jets/ClusterJetInput.cc, simulation/g4simulation/g4jets/Jet.h, simulation/g4simulation/g4jets/TowerJetInput.cc
Adding electron-going electromagnetic calorimeter, or "EEMC", as on option for tower and cluster jet reconstruction.
With these edits, one can now use the line: `towerjetreco->add_input(new TowerJetInput(Jet::EEMC_TOWER));` in G4_Jets.C to add the EEMC as an in put for reconstructed jets.
=> Add EEMC to jet reconstruction

generators/phhepmc/Fun4AllHepMCInputManagerLinkDef.h, generators/phhepmc/Fun4AllHepMCOutputManagerLinkDef.h, generators/phhepmc/Fun4AllHepMCPileupInputManagerLinkDef.h, generators/phhepmc/Fun4AllOscarInputManagerLinkDef.h, generators/phhepmc/HepMCFlowAfterBurnerLinkDef.h, generators/phhepmc/Makefile.am, generators/phhepmc/PHHepMCGenHelperLinkDef.h, generators/phhepmc/PHHepMCParticleSelectorDecayProductChainLinkDef.h, generators/phhepmc/PHHepMC_ioLinkDef.h, generators/phhepmc/configure.ac, offline/QA/modules/Makefile.am, offline/QA/modules/QAG4SimulationMvtx.cc, offline/QA/modules/QAG4SimulationTpc.cc, offline/QA/modules/QAG4SimulationUpsilon.cc, offline/QA/modules/QAG4SimulationVertex.cc, offline/QA/modules/QAG4SimulationVertex.h, offline/packages/CaloReco/PHMakeGroups.h, simulation/g4simulation/g4eval/CaloEvaluator.cc, simulation/g4simulation/g4eval/CaloEvaluator.h, simulation/g4simulation/g4eval/Makefile.am, simulation/g4simulation/g4eval/PHG4DSTReader.h, simulation/g4simulation/g4eval/SvtxClusterEval.h, simulation/g4simulation/g4eval/SvtxEvalStack.h, simulation/g4simulation/g4eval/SvtxEvaluator.cc, simulation/g4simulation/g4eval/SvtxEvaluator.h, simulation/g4simulation/g4eval/SvtxTrackEval.cc, simulation/g4simulation/g4eval/SvtxTrackEval.h, simulation/g4simulation/g4eval/SvtxTruthEval.cc, simulation/g4simulation/g4eval/SvtxVertexEval.cc, simulation/g4simulation/g4eval/SvtxVertexEval.h
We need to be able to set the tracknode name, svtxtrack is not really appropriate anymore and the fast truth based tracking has it now as a configurable parameter. It was still hardcoded in the svtx evaluator which crashed the eic detector qa.
Minor cleanups - please no "using namespace" in header files, this influences the behavior of any code which includes this file. Include what you use got rid of a few not needed includes
=> Set tracknode name

simulation/g4simulation/g4tpc/Makefile.am, simulation/g4simulation/g4tpc/PHG4TpcDigitizerLinkDef.h, simulation/g4simulation/g4tpc/PHG4TpcDistortionLinkDef.h, simulation/g4simulation/g4tpc/PHG4TpcElectronDriftLinkDef.h, simulation/g4simulation/g4tpc/PHG4TpcEndCapDetector.cc, simulation/g4simulation/g4tpc/PHG4TpcEndCapDetector.h, simulation/g4simulation/g4tpc/PHG4TpcEndCapDisplayAction.cc, simulation/g4simulation/g4tpc/PHG4TpcEndCapDisplayAction.h, simulation/g4simulation/g4tpc/PHG4TpcEndCapSteppingAction.cc, simulation/g4simulation/g4tpc/PHG4TpcEndCapSteppingAction.h, simulation/g4simulation/g4tpc/PHG4TpcEndCapSubsystem.cc, simulation/g4simulation/g4tpc/PHG4TpcEndCapSubsystem.h, simulation/g4simulation/g4tpc/PHG4TpcPadPlaneLinkDef.h, simulation/g4simulation/g4tpc/PHG4TpcPadPlaneReadoutLinkDef.h, simulation/g4simulation/g4tpc/PHG4TpcPadPlaneSimpleLinkDef.h, simulation/g4simulation/g4tpc/PHG4TpcSpaceChargeDistortionLinkDef.h, simulation/g4simulation/g4tpc/PHG4TpcSubsystemLinkDef.h, simulation/g4simulation/g4tpc/configure.ac
TPC endcap in the current engineering model added into in simulation, for forward detector simulations at both sPHENIX and EIC.
Direct importing the CAD model is slow to run and incompatible with the Kalman filter (TGeoGeometry). Therefore, this PR introduce a simplified model coded in Geant4.
=> Introduce TPC endcap in simulation

offline/packages/trackreco/ActsEvaluator.cc
The TPC seeders do not associate the track seed to the vertex. This causes a crash in the acts evaluator when it tries to access an unallocated vertex. For now we just set it to the 0th vertex until the track stub matchers are implemented.
=> Fix Vertex

offline/packages/trackreco/MakeActsGeometry.cc
Switch the response file grabbing to `OFFLINE_MAIN` rather than the local directory where the macro is run.
=> Correct response file

simulation/g4simulation/g4epd/PHG4EPDSubsystem.cc, simulation/g4simulation/g4epd/PHG4EPDetector.cc, simulation/g4simulation/g4epd/PHG4EPDetector.h
default position remains at +/- 300 cm.
checked that the position can be configured by `epd->set_double_param(-1, "z_position", 100.);` in `macros/common/G4_EPD.C`
=> epd: make z position of detector configurable

offline/packages/PHTpcTracker/Makefile.am, offline/packages/PHTpcTracker/PHTpcTrackFollower.cc, offline/packages/PHTpcTracker/PHTpcTracker.cc, offline/packages/PHTpcTracker/PHTpcTracker.h, offline/packages/PHTpcTracker/Track.h, offline/packages/PHTpcTracker/configure.ac
This PR fixes a memory leak in PHTpcTracker which has been bothering us for a long time. The reason was a problem in the handling of >1 matches where the genfit track was cloned each time but only deleted once at the end of the loop. This happens only very rarely for our single particle events which is why this only cropped up occasionally. Using a variable of that scope wasn't necessary, keeping everything local and deleting the cloned track right after use fixed that leak. The results did not change.
=> Fix phtpctracker memleak

offline/packages/trackreco/PHGenFitTrkFitter.cc
Check pointer returned by getPointWithMeasurementAndFitterInfo() befire moving on with the extrapolation
This is consistent with what is done elsewhere in the code and prevents crashes.
Said crash where only manifesting when 
- some layers are "disabled" from the fit
- truth track finding is used
=> Fix crash in Genfit kalman filter extrapolation

offline/packages/trackreco/Makefile.am, offline/packages/trackreco/PHSiliconTpcTrackMatching.cc, offline/packages/trackreco/PHSiliconTpcTrackMatching.h, offline/packages/trackreco/PHSiliconTpcTrackMatchingLinkDef.h, offline/packages/trackreco/PHSiliconTruthTrackSeeding.cc, offline/packages/trackreco/PHSiliconTruthTrackSeeding.h, offline/packages/trackreco/PHSiliconTruthTrackSeedingLinkDef.h, offline/packages/trackreco/PHTruthSiliconAssociation.cc, offline/packages/trackreco/PHTruthSiliconAssociation.h
Introduces two modules that are intended to replace PHGenFitTrkProp. 
**PHSiliconTruthTrackSeeding** uses truth information to assemble silicon detector clusters into track stubs, and puts them on the node tree in a separate map. It will eventually be replaced with a real silicon track stub finder.
**PHSiliconTpcTrackMatching** reads the silicon track stubs from the node tree, and the TPC track stubs from the CA TPC track seeder(s). It associates them into full tracks. No truth information is used. All associations falling within the matching windows are accepted, duplicating the TPC track stubs as needed. The search windows used for matching have been optimized to reproduce the truth silicon association results from the PHTruthSiliconAssociation module. 
The reconstruction chain used for …
=> Truth silicon track seeding and TPC-silicon track stub matching module

offline/packages/PHTpcTracker/PHTpcTracker.cc, offline/packages/trackreco/PHActsTracks.cc, offline/packages/trackreco/PHActsTrkFitter.cc, offline/packages/trackreco/PHSiliconTpcTrackMatching.cc, offline/packages/trackreco/PHSiliconTruthTrackSeeding.cc
1) PHTpcTracker did not set the charge sign for tracks. They all defaulted to -1. The Genfit chain does not care, but the Acts chain does. For now, the charge sign is set and then reversed, because Acts has a different opinion about the direction of the magnetic field (apparently). Joe is working on that. This was not apparent until now because I was testing with positive muons, which were given the wrong sign by PHTpcTracker, thus making Acts happy (!!).
2) Updated PHSiliconTpcTrackMatching to properly handle the phi bias correction from PHTpcTracker for negative tracks, which bend the other way (duh). This was also not noticed because I was testing with positive muons.
3) Modified PHSiliconTruthTrackSeeding to associate the silicon track stubs with the vertex of the truth particle. …
=> Multiple vertices, silicon-TPC track stub matching improvements, PHTpcTracker fix

simulation/g4simulation/g4trackfastsim/PHG4TrackFastSimEval.cc
In the EIC fast tracking module, add projection variable output for TOF analysis:
1. truth hit time from Geant4: `<detector>_t`
2. reconstructed path length from the vertex PCA: `<detector>_proj_path_length`
Quick test taking FST_5 as LGAD TOF: 
https://github.com/sPHENIX-Collaboration/macros/compare/master...blackcathj:EIC-TOF-Projection?expand=1 
and output looks like this:
```
root G4EICDetector_g4tracking_eval.root                                 
root [0] 
Attaching file G4EICDetector_g4tracking_eval.root as _file0...
(TFile *) 0x152cb40
root [1] tracks->Show(3)
event           = 1
gtrackID        = 4
gflavor         = -211
...
FST_5_proj_x    = 0.283821
FST_5_proj_y    = -32.3717
FST_5_proj_z    = 280
**FST_5_proj_path_length** = 282.679
...
FST_5_x         = 0.283815
FST_5_y …
```
=> Add projection variable output for TOF analysis

offline/packages/trackreco/PHActsTrkFitter.cc
Seed tracks for which the Acts track fit failed are junk, and they are now deleted instead of being marked as junk. This lowers the load on the SvtxEvaluator quite a lot for Hijing events.
=> Delete failed proto tracks

generators/phhepmc/Fun4AllHepMCInputManager.h, generators/phhepmc/Fun4AllHepMCPileupInputManager.cc, generators/phhepmc/Fun4AllHepMCPileupInputManager.h, offline/framework/fun4all/Fun4AllInputManager.h, offline/framework/fun4all/Fun4AllNoSyncDstInputManager.h, offline/framework/fun4all/Fun4AllServer.cc, offline/framework/fun4all/Fun4AllServer.h, offline/framework/fun4all/Fun4AllSyncManager.cc
This PR is a quick (but reasonable) fix to skip events in the pileup manager properly so skipping will preserve the event ordering one would see when just running. The same change was applied to the nosync manager, so it will also advance its event counter. The mechanics need some more cleanup to get event numbers right and pushing back the previous events in case of reread. This will take a bit longer and will come in a later PR.
=> implement skipping for non syncing input managers

offline/framework/fun4all/Fun4AllServer.cc
The Fun4AllServer::skip called the syncmanagers even if the number of skipped events = 0 (which is now done in the new Fun4All macros). This lead to problems in the DST input manager when using file lists. This behavior will need fixing since it will also fail if some none zero number of events is skipped in the DSTs. But that's for later
=> do not skip 0 events, just return

offline/packages/trackreco/Makefile.am, offline/packages/trackreco/PHGenFitTrkFitter.cc
This PR modifies how Micromegas 1D clusters are handled in the Genfit track fit: 
Even if the clusters are 1D one must provide an estimate of the "other" coordinate to the measurement. This is to have the planar approximation around the measurement, performed by GenFit, actually tengent to the detector. (this is not the case for z measurements, for which phi is assigned to the midle of the detector).
This estimate is based on the measurement provided by the other micromegas cluster, in the same track, if present. 
There is no double use of the said measurements because the errors are unchanged and kept very large for the direction that one given micromegas layer does not measure. 
This fixes some large biases in the z residual for tracks including Micromegas detectors.
Ultimately, …
=> Fix micromegas tracking

generators/PHPythia6/Makefile.am, generators/PHPythia6/PHPy6ForwardElectronTrig.h, generators/PHPythia6/PHPy6ForwardElectronTrigLinkDef.h, generators/PHPythia6/PHPy6GenTrigger.cc, generators/PHPythia6/PHPy6GenTrigger.h, generators/PHPythia6/PHPy6GenTriggerLinkDef.h, generators/PHPythia6/PHPy6JetTrigger.cc, generators/PHPythia6/PHPy6JetTrigger.h, generators/PHPythia6/PHPy6JetTriggerLinkDef.h, generators/PHPythia6/PHPy6ParticleTrigger.cc, generators/PHPythia6/PHPy6ParticleTrigger.h, generators/PHPythia6/PHPy6ParticleTriggerLinkDef.h, generators/PHPythia6/PHPythia6.cc, generators/PHPythia6/PHPythia6LinkDef.h, generators/PHPythia6/configure.ac, generators/PHPythia8/Makefile.am, generators/PHPythia8/PHPy8GenTriggerLinkDef.h, generators/PHPythia8/PHPy8JetTriggerLinkDef.h, generators/PHPythia8/PHPy8ParticleTriggerLinkDef.h, generators/PHPythia8/PHPythia8LinkDef.h, generators/PHPythia8/configure.ac, generators/PHSartre/Makefile.am, generators/PHSartre/PHSartreGenTriggerLinkDef.h, generators/PHSartre/PHSartreLinkDef.h, generators/PHSartre/PHSartreParticleTriggerLinkDef.h, generators/PHSartre/configure.ac, generators/phhepmc/Fun4AllHepMCInputManager.cc
This PR adds the deletion of the temporary hepmc file in the dtor. If an input manager is exhausted the others push back their latest event which in the HepMC input manager case creates those temporary files which then need to be cleaned up in the dtor.
=> Delete tmp file

offline/packages/trackreco/PHGenFitTrkFitter.cc
Because of this missing continue statement Micromegas hits were counted twice in the fit ...
=> aded missing "continue" statement

offline/packages/trackreco/ActsEvaluator.h, offline/packages/trackreco/ActsTrack.h, offline/packages/trackreco/ActsTrackingGeometry.h, offline/packages/trackreco/MakeActsGeometry.cc, offline/packages/trackreco/Makefile.am, offline/packages/trackreco/PHActsSourceLinks.h, offline/packages/trackreco/PHActsTracks.h, offline/packages/trackreco/PHActsTrkFitter.cc, offline/packages/trackreco/PHActsTrkFitter.h, offline/packages/trackreco/PHActsTrkProp.h, offline/packages/trackreco/PHActsVertexFinder.h, offline/packages/trackreco/PHActsVertexFitter.h
This PR refactors the ActsTrackingGeometry struct and puts it into it's own header file so that PHActsSourceLinks.h is not carried around in a bunch of different modules.
=> Acts Tracking Geometry

offline/packages/trackreco/ActsSurfaceMaps.h, offline/packages/trackreco/MakeActsGeometry.cc, offline/packages/trackreco/MakeActsGeometry.h, offline/packages/trackreco/Makefile.am, offline/packages/trackreco/PHActsSourceLinks.cc, offline/packages/trackreco/PHActsSourceLinks.h, offline/packages/trackreco/PHActsTrkFitter.cc, offline/packages/trackreco/PHActsTrkFitter.h
This PR makes the `MakeActsGeometry` module a standalone `SubsysReco` subclass so that it can be called on its own in the G4_Tracking macro. This way if we need to build the geometry before any other part of the reconstruction chain, it can be done.
There is a corresponding [PR](https://github.com/sPHENIX-Collaboration/macros/pull/313/) in the macros repository that should be merged with this PR to reflect the change to the acts tracking chain.
=> Standalone acts geometry

offline/database/pdbcal/pg/configure.ac, offline/framework/frog/configure.ac, simulation/g4simulation/g4tpc/PHG4TpcDigitizer.cc, simulation/g4simulation/g4tpc/PHG4TpcDigitizer.h, simulation/g4simulation/g4tpc/PHG4TpcDistortion.h, simulation/g4simulation/g4tpc/PHG4TpcElectronDrift.h, simulation/g4simulation/g4tpc/PHG4TpcPadPlane.h, simulation/g4simulation/g4tpc/PHG4TpcPadPlaneReadout.h
This PR should enable us to use ccache. The gcc 8.3 setup scripts sets CXX and CC to the respective compiler. This overrules ccache which is not called. Building without those variables set gave a few more compiler warnings which this fixes.
Also ifdef CINT removed from trackreco includes
=> Fix gcc 8.3

simulation/g4simulation/g4epd/PHG4EPSteppingAction.cc
add scintillator light yields to EPD hits, based on implementation in `PHG4InnerHcalSteppingAction.cc`. tested that it can be read out from the node tree and is very linearly correlated with the energy deposit.
=> g4epd: add scintillator light yields to epd hits

generators/FermiMotionAfterburner/FermiMotion.cc, generators/FermiMotionAfterburner/FermiMotion.h, generators/FermiMotionAfterburner/FermimotionAfterburner.cc, generators/FermiMotionAfterburner/FermimotionAfterburner.h, generators/FermiMotionAfterburner/Makefile.am, generators/FermiMotionAfterburner/autogen.sh, generators/FermiMotionAfterburner/configure.ac
Draft of Fermimotion afterburner. The Fermimotion method will take in a hepmc event, find all spectator neutrons and protons, randomly remove neutrons that bound to larger charge fragments, then apply Fermi motions to the remaining spectators. 
Only works for Au+Au so far.
=> Fermi motion afterburner

offline/packages/trackreco/PHActsTracks.cc
This PR adds a diagnostic and check for track seeds that are passed to Acts with nan entries. Christof found this error in embedded HIJING events, and we will have to understand where it is coming from in the tracking chain. This PR allows these bad track seeds to be skipped, thus Acts does not crash.
=> Add bad track seed diagnostic

simulation/g4simulation/g4jets/ClusterJetInput.cc, simulation/g4simulation/g4jets/FastJetAlgo.cc, simulation/g4simulation/g4jets/Jet.h, simulation/g4simulation/g4jets/TowerJetInput.cc, simulation/g4simulation/g4jets/TowerJetInput.h, simulation/g4simulation/g4jets/TrackJetInput.h
This PR adds ECAL_TOPO_CLUSTER as a possible input to jet finding. This input can be used in macros/g4simulations/G4_Jets.C.
=> add EMCAL_TOPO as a possible input to jet finding

offline/packages/trackreco/PHMicromegasTpcTrackMatching.cc, offline/packages/trackreco/PHMicromegasTpcTrackMatching.h, offline/packages/trackreco/PHSiliconTpcTrackMatching.cc, offline/packages/trackreco/PHSiliconTpcTrackMatching.h, offline/packages/trackreco/PHSiliconTruthTrackSeeding.cc, offline/packages/trackreco/PHTrackFitting.h, offline/packages/trackreco/PHTruthVertexing.cc
Modifies PHTruthVertexing to copy all primary truth vertices to the SvtxTrackMap, regardless of embedding ID. Modifies PHSiliconTruthTrackSeeding to more gracefully handle not finding a vertex entry in the track map for a truth particle (just skips the truth particle).
=> Fix multiple vertex handling

offline/packages/trackreco/PHSiliconTruthTrackSeeding.cc, offline/packages/trackreco/PHTruthVertexing.cc
Added some code to PHSiliconTruthTrackSeeding to associate (rare) secondary tracks in the silicon with the correct primary vertex. Combined with PR958, I think that multiple vertex events are now handled properly in the tracking chain.
=> Secondary track vertex association

offline/packages/trackreco/PHActsTrkFitter.cc
This PR adds some timing verbosity statements around the track fitting code. Times are output in milliseconds.
@bogui56
=> Add some timing verbosity statements

offline/packages/trackreco/PHTruthVertexing.cc
Yasser reported that the silicon-TPC matching was not working properly for Pythia events. It turns out that the PYTHIA simulation adds dozens of vertices to the truth container, including some for secondaries. This broke the logic in the current truth vertexing bookkeeping. This PR resolves that by unconditionally copying all truth vertices from the truth container over to the SvtxVertexMap. It has no effect for Hijing and simple generator events.
=> Fix truth vertices

simulation/g4simulation/g4eval/SvtxEvaluator.cc
verbosity ==1 now gives grepable lines with nhits, ntracks, n primary gen tracks and job number
=> evaluator verbosity update for performance checks

offline/framework/fun4all/Fun4AllDstOutputManager.cc, offline/framework/fun4all/Fun4AllDstOutputManager.h, offline/framework/fun4all/Fun4AllOutputManager.h, simulation/g4simulation/g4main/PHG4Reco.cc, simulation/g4simulation/g4main/PHG4TruthEventAction.cc
The use of the PAI model which worked in G4 10.03 crashes G4 10.06.p02 when enabling the micromega sim. Commented out for the time being - we need to verify the TPC and micromegas gas simulations. The PAI model was supposed to make the eloss more independent on the step length.
=> Remove pai

offline/packages/trackreco/ActsEvaluator.cc, offline/packages/trackreco/ActsEvaluator.h, offline/packages/trackreco/ActsTransformations.cc, offline/packages/trackreco/ActsTransformations.h, offline/packages/trackreco/PHActsSourceLinks.cc, offline/packages/trackreco/PHActsSourceLinks.h, offline/packages/trackreco/PHActsTracks.cc, offline/packages/trackreco/PHActsTracks.h, offline/packages/trackreco/PHActsTrkFitter.cc, offline/packages/trackreco/PHActsTrkFitter.h, offline/packages/trackreco/PHActsTrkProp.cc, offline/packages/trackreco/PHActsTrkProp.h
This PR changes the hit ID to cluster key map to a `boost::bimap` which is a bijective map that contains the information to go from key to value and vice versa. Since the hit ID is unique to a given clusterkey, this does not change any of the Acts `SourceLink` look up. 
Changing this to a bijective map improves the look up speed of the hit ID to cluster key by an order of magnitude when copying the Acts track state data back to the SvtxTrack object. One can now run the entire Acts track fitting module with the Svtx track update without a major order of magnitude speed loss in the module execution.
=> Cluster key look up

offline/packages/trackreco/PHActsSourceLinks.cc, offline/packages/trackreco/PHActsTracks.cc, offline/packages/trackreco/PHActsTracks.h, offline/packages/trackreco/PHActsTrkFitter.cc
This PR adds `PHTimer` timers to the various acts classes instead of using one of the `std::` available timers. It also shuffles around some verbosity statements/makes them a little easier to read.
Timing information can now be accessed for the entire acts chain on an event by event basis by switching verbosity to 1 for `PHActsSourceLinks`, `PHActsTracks`, and `PHActsTrkFitter`.
=> Add PHTimer timers

offline/packages/tpccalib/TpcSpaceChargeReconstruction.cc, offline/packages/tpccalib/TpcSpaceChargeReconstruction.h
This is an overall update of the track-base space charge distortion code
- reordered axis and change axis range to better match the format of the input distortion map.
- added checks on tracks and clusters before filling the matrices 
- save the result of the matrix inversions (namely, the space charge corrections) to 3D histograms of the same format as the input distortions rather than TGraphs. The histograms are written to a rootfile that can then be used as input for correcting the cluster positions.
=> Tpc distortion reconstruction

offline/packages/trackreco/Makefile.am, offline/packages/trackreco/PHActsTrackProjection.cc, offline/packages/trackreco/PHActsTrackProjection.h
This PR introduces a track-to-calo projecting module to replace `PHGenFitTrackkProjection` using the Acts machinery. Tracks are projected out to a cylindrical surface that is created at the radii of the EMCal and two HCals. The track projection is matched with the nearest cluster in each calo layer and some 3x3 and 5x5 tower sums are calculated. The SvtxTrack object is updated with the calculated information.
This gives us a full Acts tracking chain for the MDC, with no GenFit dependency.
=> Acts track-to-calo projection

offline/packages/PHTpcTracker/PHTpcTracker.cc, offline/packages/trackreco/Makefile.am, offline/packages/trackreco/PHActsSourceLinks.cc, offline/packages/trackreco/PHActsSourceLinks.h, offline/packages/trackreco/PHActsTracks.cc, offline/packages/trackreco/PHCASeeding.cc, offline/packages/trackreco/PHSiliconTruthTrackSeeding.cc, offline/packages/trackreco/PHTrackPropagating.cc, offline/packages/trackreco/PHTrackPropagating.h, offline/packages/trackreco/PHTrackSeeding.cc, offline/packages/trackreco/PHTrackSeeding.h, offline/packages/trackreco/PHTruthClustering.cc, offline/packages/trackreco/PHTruthClustering.h, simulation/g4simulation/g4eval/SvtxEvaluator.cc, simulation/g4simulation/g4eval/SvtxEvaluator.h, simulation/g4simulation/g4eval/SvtxTruthEval.cc, simulation/g4simulation/g4eval/SvtxTruthEval.h
Adds a module to do truth clustering and put clusters in the TRKR_CLUSTER_TRUTH node. Includes flags for downstream modules so that tracking can use truth clusters instead of reco clusters. Updates SvtxEvaluator truth clusters with an estimate of the ADC value. Everything defaults to normal tracking.
=> Truth clustering module

simulation/g4simulation/g4eval/SvtxEvaluator.cc
minor fix to number of hit printout. Avoid it to switch to back and forth to scientific notation. Makes processing the output text easier
=> fix print formatting

generators/flowAfterburner/flowAfterburner.cc, generators/flowAfterburner/main.cc
extend default eta range to cover the entire acceptance of the epd. increase width of v2 vs. eta distribution to better match data [[slides]].
[slides]: https://indico.bnl.gov/event/9997/contributions/43248/attachments/31315/49420/sphenix-js-tg-201106.pdf
=> flow afterburner: adjust parameters

simulation/g4simulation/g4main/Fun4AllDstPileupInputManager.cc
This PR ensures that raw events are not reused from one merged event (signal + pile-up) to the other.
In particular, there must be a difference of at least one full drift time between the last background (or signal) source event used in one merge event, and the signal of the next merged event.
Also prevent source events to be read multiple times by either the signal or background IO manager, by making the signal IO manager skipped as many events as there was events used for the background, before moving to the next. 
This increases the efficiency of the merging.
=> Protection against overlapping events

simulation/g4simulation/g4main/Fun4AllDstPileupInputManager.cc, simulation/g4simulation/g4main/Fun4AllDstPileupInputManager.h
This PR adds the possibility for the DSTPileupInputManager to generate its own list of bunch crossing ids, needed for merging pileup events into min bias hijing events at a given pile-up rate, rather than getting them from an external file. 
Typicall code would look like: 
// input manager
auto in = new Fun4AllDstPileupInputManager("DSTin");
in->generateBunchCrossingList( 1000, 5e4 );
in->fileopen(inputFile);
se->registerInputManager(in);
... 
se->run( 1000 );
Note that the number of events passed to generateBunchCrossingList should be at least as big as the number of events in the inputFile
=> Pileup input manager

offline/packages/CaloBase/RawTowerGeom.h, offline/packages/CaloBase/RawTowerGeomContainer.h, offline/packages/CaloBase/RawTowerGeomContainer_Cylinderv1.cc, offline/packages/CaloBase/RawTowerGeomContainer_Cylinderv1.h, offline/packages/CaloBase/RawTowerGeomv1.cc, offline/packages/CaloBase/RawTowerGeomv1.h, offline/packages/CaloBase/RawTowerGeomv3.cc, offline/packages/CaloBase/RawTowerGeomv3.h
This PR adds get_theta() methods to the calorimeter geometries we use. It's needed to create parametrizations for eic-smear which use theta, not eta
=> Return calogeo theta

offline/packages/tpccalib/TpcSpaceChargeReconstruction.cc
Title says it all.
Impact on the actual space charge reconstruction is minimal though, because extrapolation along r is essentially zero or very small for the vast majority of clusters.
=> Fix track state extrapolation along r. (dr/dt was improperly calculated)

offline/packages/trackreco/PHActsVertexFinder.cc, offline/packages/trackreco/PHActsVertexFinder.h, offline/packages/trackreco/PHActsVertexFitter.cc
This PR puts the Acts vertex finder in a usable state. The vertex finder takes a list of tracks and returns a list of vertices. A new `SvtxVertexMap` with the name `SvtxVertexMapActs` is put on the node tree, so that analyzers can use this vertex map or one created by e.g. rave. 
Only vertices that have at least 3 tracks and chi2/ndf < 100 are added to the map. These are very basic quality cuts so that users have the option to identify vertices that they may or may not want to use.
=> Acts vertexing

offline/packages/CaloReco/BEmcRec.cc, offline/packages/trackreco/MakeActsGeometry.cc, simulation/g4simulation/g4histos/G4VtxNtuple.cc, simulation/g4simulation/g4histos/G4VtxNtuple.h, simulation/g4simulation/g4histos/Makefile.am
This PR adds a few small things:
In MakeActsGeometry a string is copied by strdup(argstr[i].c_str()); the memory needs to be free'd, not deleted
Added a small ntuple to dump the vtx distribution (to verify that we use the CAD vertex distribution)
Print out the module name for the x out of bounds message in BEmcRec so we know which one throws the error
=> Small fixes

offline/packages/trackreco/PHActsVertexFinder.cc, offline/packages/trackreco/PHActsVertexFinder.h
This PR updates the svtx vertex instance with the corresponding track keys for the evaluator machinery.
=> Update SvtxVertex with track ids

offline/packages/trackreco/PHActsVertexFinder.cc, simulation/g4simulation/g4eval/SvtxEvalStack.h, simulation/g4simulation/g4eval/SvtxEvaluator.cc, simulation/g4simulation/g4eval/SvtxEvaluator.h, simulation/g4simulation/g4eval/SvtxVertexEval.cc, simulation/g4simulation/g4eval/SvtxVertexEval.h
This PR updates SvtxEvaluator to use SvtxVertexMapActs by default. This is the vertex map made from the final Acts fitted tracks by PHActsVertexing. A switch is provided to allow the use of SvtxVertexMapRefit, which is filled by Rave when Genfit tracking is run. Note that the Acts vertexing handles multiple vertices, while Rave (as now configured) only handles one vertex.
=> Add acts vertexing to SvtxEvaluator

offline/framework/frog/FROG.cc, offline/framework/frog/FROG.h
This PR adds proper handling for files in dCache. PHENIX overloaded the hpss location - we don't need to do this anymore
=> modify for sPhenix dcache

offline/packages/trackreco/PHActsTrackProjection.cc, offline/packages/trackreco/PHActsTrackProjection.h, offline/packages/trackreco/PHGenFitTrackProjection.cc, offline/packages/trackreco/PHGenFitTrackProjection.h
This PR adds a flag to the track projection modules to use the cemc position recalibrated cluster information rather than the raw cluster information. It is turned off by default to maintain the current configuration, but users can set it in their tracking macro.
=> Project tracks with CEMC position recalibrated clusters

offline/packages/NodeDump/macro/run_dump.C, simulation/g4simulation/g4detectors/PHG4CrystalCalorimeterDetector.cc, simulation/g4simulation/g4detectors/PHG4CrystalCalorimeterDetector.h, simulation/g4simulation/g4detectors/PHG4CrystalCalorimeterSteppingAction.cc, simulation/g4simulation/g4detectors/PHG4CrystalCalorimeterSubsystem.cc, simulation/g4simulation/g4detectors/PHG4CrystalCalorimeterSubsystem.h, simulation/g4simulation/g4detectors/PHG4ProjCrystalCalorimeterDetector.cc, simulation/g4simulation/g4detectors/PHG4ProjCrystalCalorimeterDetector.h
This PR modernizes the crystal calorimeter. Instead of string parsing it compares the actual volume, so volumes from other subsystems which match the string compare are not picked up anymore.
The projective calorimeter cheated - it was surrounded by vacuum. This is now replaced with the world material which leads to significantly higher number of hits in the crystals and the absorbers (if the world is filled with air). Given that it was initially air which was exchanged by vacuum later I guess someone "tuned" this
=> Crystal phparameter

simulation/g4simulation/g4tpc/PHG4TpcDistortion.h
(otherwise might break compilation on some systems)
=> Added missing include 

offline/framework/fun4all/Fun4AllDstInputManager.cc, offline/framework/fun4all/Fun4AllInputManager.h, offline/framework/phool/PHNodeIOManager.cc, offline/framework/phool/PHNodeIOManager.h, offline/framework/phool/PHTimer.cc, offline/framework/phool/PHTimer.h
I revived the selection of branches for reading so one reads only the data which is needed. This selection needs to be applied before a file is opened to have an effect. There is now a warning message saying so if the order is reversed. I did not make this fatal since the reading still works (you just read more bytes than you have to).
Also - replaced a few more const char * interfaces by const std::string &
=> Branchwarning

offline/packages/trackreco/PHActsSiliconSeeding.cc, offline/packages/trackreco/PHActsSiliconSeeding.h
This PR switches the seeding to only include the MVTX rather than the entire silicon. This reduces the number of duplicate seeds significantly. Additionally, this PR adds an option to project the circle fit that is performed on the MVTX seed to the INTT to find potential matching clusters.
The rphi projection looks as expected but the z projection is quite large, perhaps due to fitting a line to only 3 points introducing a large enough error in the slope that the z projection can be quite bad. A future PR will add a module that tries running the Acts track projection scheme over the MVTX seeds to see if it performs better.
=> Switch Seeding to MVTX

simulation/g4simulation/g4main/Fun4AllDstPileupInputManager.cc, simulation/g4simulation/g4main/Fun4AllDstPileupInputManager.h, simulation/g4simulation/g4main/Fun4AllDstPileupMerger.cc, simulation/g4simulation/g4main/Fun4AllDstPileupMerger.h, simulation/g4simulation/g4main/Fun4AllSingleDstPileupInputManager.cc, simulation/g4simulation/g4main/Fun4AllSingleDstPileupInputManager.h, simulation/g4simulation/g4main/Makefile.am
This PR:
- modifies the existing DSTPileUpInputManager so that pileup event times are generated on the fly rather than pregenerated, or read from external files. This allows to properly merge signal and pileup events with the right (flat) time distribution, while ensuring that there is no overlap between merged events. This also prevents a bias identified by Dennis (and Jin) in merging pile-up events when reading the time sequence from a predefined set and then adding cuts on event time differences to avoid overlapping merged events. The possibility to read a predefined time sequence will be re-added later.
- renames the existing DSTPileUpInputManager to SingleDSTPileUpInputManager, to indicate that both the signal and the pileup events are read from the same DST
- moves the pile-up event …
=> Pileup input managers

offline/framework/fun4all/Fun4AllDstInputManager.cc, offline/framework/fun4all/Fun4AllSyncManager.cc
Ejiro found a problem when using file lists. For file lists the first event has to be processed for the input manager to actually open the file and figure out if a sync object exists or not. Now the run(1) is called in the Fun4AllSyncManager before the sync object consistency is checked. This forces the input managers to open the first file
=> fix sync object read for filelists

offline/packages/trackreco/PHActsSiliconSeeding.cc, offline/packages/trackreco/PHActsSiliconSeeding.h
This PR changes the projection of the MVTX triplets to the INTT in a couple of ways:
1. The z matching window is changed from some arbitrary length to the INTT strip z length
2. The hits in the INTT that are potential matches are collected
3. These hits are then combinatorially combined with the MVTX triplet with the assumption of 2 INTT hits per track
Initial performance evaluation for the full Acts silicon seeder is/was shown in the December 15, 2020 sPHENIX simulations meeting.
=> Intt projection update

offline/packages/trackreco/PHActsInitialVertexFinder.cc, offline/packages/trackreco/PHActsSiliconSeeding.cc, offline/packages/trackreco/PHActsSiliconSeeding.h, offline/packages/trackreco/PHActsTrkFitter.cc
This PR changes the x-y PCA selection for the acts silicon seeds to less than 1 mm. The initial vertex finder was crashing due to the Acts stepper trying to propagate seeds that had a bad starting point - adding this criteria removes a higher fraction of bad seeds and allows the vertex finder to run without getting stuck trying to propagate something to a large x-y position.
Now, if a seed is bad, the acts track fitter just returns a bad track fit after the silicon seed is matched to the tpc seed (and then moves on to the next track).
This PR accompanies a macros [PR](https://github.com/sPHENIX-Collaboration/macros/pull/351) which provides a flag to run the acts silicon seeder. It is …
=> Fix silicon seed PCA requirement

offline/packages/trackreco/PHActsSiliconSeeding.h, offline/packages/trackreco/PHActsVertexFitter.cc, offline/packages/trackreco/PHActsVertexFitter.h
This PR updates the z vertex fitting module to work with the SvtxVertexMap and run the final vertex fitting over tracks that have already been assigned to a found vertex. In the initial vertex finding, silicon stubs are associated to a vertex so the finding does not necessarily need to be performed again. This module can then act as a final vertex fitter and could be used in place of the IVF if desired. It needed to be updated to pull from the SvtxTrackMap and to take into account the already associated vertices from the IVF.
Note that it does not need to be included in the macros since the finder+fitter tool could also be used as a final vertex finder+fitter (i.e. this is an …
=> Z vertex fitter

offline/packages/KFParticle_sPHENIX/KFParticle_DST.cc, offline/packages/KFParticle_sPHENIX/KFParticle_nTuple.cc, offline/packages/KFParticle_sPHENIX/KFParticle_particleList.cc
When testing KFParticle I noticed ROOT can't interpret branch names with parenthesis. If they appear in either the nTuple or DST output, they are now removed.
I also changed the electron mass assignment to a coded double rather than looking up the KFParticle database. It can return a low mass which confuses the daughter mass check in KFParticle_Tools
Nothing to do in KFParticle. I'm working on a Lambda_c generator for now which can be used to test KFParticle as well (and other parts of our software...)
PR in macros to run KFParticle: https://github.com/sPHENIX-Collaboration/macros/pull/353
KFParticle will still work without this macro, you just wont be able to read branches with () …
=> Minor change to KFParticle

simulation/g4simulation/g4tpc/PHG4TpcElectronDrift.cc
The observed slowness of PHG4TpcElectronDrift when running the MDC is addressed. It was due to the overhead of searching the TrkrHitsSetContainer to check if a new hitset and/or hit was already present on the node tree. The new hitsets were previously buffered in a temporary TrkrHitSetContainer for one g4hit worth of electrons. The map search time increases quadratically with the number of g4hits, and becomes unacceptable for events with several million g4hits. This PR …
=> Electron drift speedup

offline/packages/KFParticle_sPHENIX/Makefile.am
[comment]: <This PR fixes a race condition in the KFParticle_sPHENIX package. The io lib was added under LDADD which is basically reserved for library paths. Libraries are added via LIBADD. Then they are build in the proper order so dependencies among them are satisfied> ( What does this PR do? Linking to talk in software meeting encouraged )
=> need to use LIBADD when libs dependency affects build order

offline/packages/trackreco/PHActsInitialVertexFinder.cc, offline/packages/trackreco/PHActsInitialVertexFinder.h, offline/packages/trackreco/PHActsSiliconSeeding.cc, offline/packages/trackreco/PHActsSiliconSeeding.h
This PR updates the seeding code with some diagnostic verbosity statements and histograms. It also adds a second circle fit iteration after the INTT clusters are added to the track stubs to improve the momentum magnitude estimate. The efficiency and overall performance of the seeder, as it is in the state of this PR, will be discussed at the tracking meeting tomorrow, linked [here](https://indico.bnl.gov/event/10465/).
=> Acts Silicon Seeding Improvements

simulation/g4simulation/g4main/Fun4AllDstPileupInputManager.cc, simulation/g4simulation/g4main/Fun4AllSingleDstPileupInputManager.cc
I see some evidence that the chattering of the pileup manager in pp which goes into the logs impacts gpfs performance. This puts the cout's behind a verbosity check (>0)
=> reduce chatter of pileupmanager

simulation/g4simulation/g4main/PHG4Shower.h, simulation/g4simulation/g4main/PHG4Showerv1.h, simulation/g4simulation/g4main/PHG4TruthInfoContainer.cc, simulation/g4simulation/g4main/PHG4TruthInfoContainer.h
The equality operators for the truth container will help to streamline the comparison of the created output data during refactoring
=> Overload equality operators for PHG4TruthInfoContainer and PHG4Shower

offline/packages/KFParticle_sPHENIX/KFParticle_DST.cc, offline/packages/KFParticle_sPHENIX/KFParticle_sPHENIX.cc, offline/packages/KFParticle_sPHENIX/KFParticle_sPHENIX.h
I noticed when generating MDC data that when creating a track map for the loose reconstruction, the tracks used disappear from the original track map rather than being copied from them. I cloned the original track map then made the new container from there which keeps the original tracks in place. This might be related to the crash from jet truth matching which could be trying to access the missing tracks.
I also increased the verbosity level for the DST class as it mostly duplicates the basic reconstruction output and would thus be annoying for most users. …
=> Fix to KFParticle DST output

offline/packages/trackreco/PHActsInitialVertexFinder.cc, offline/packages/trackreco/PHActsInitialVertexFinder.h, offline/packages/trackreco/PHActsSiliconSeeding.cc
The Acts initial vertex finder fails when there is only a single track in the event, which is not ideal for single particle simulations. Jenkins pulled this up after making the Acts silicon seeder + IVF default. This PR creates a catch for this by creating a single vertex at (0,0,0) with a large covariance so that the rest of the track fitting can be run without seg faulting.
It remains to be investigated the performance of the IVF in low track situations, which will inevitably come up in p+p collisions. At some point we will need to understand the validity of the IVF and when it fails in low track situations, and create a more permanent solution for these cases.
Macros …
=> Fail safe for IVF in single particle sims

offline/packages/trackreco/PHSiliconTpcTrackMatching.cc
There is a newly observed, extremely rare, failure to find a valid vertex pointer in PHSiliconTpcTrackMatching. It causes a segfault. This PR traps the error and prints out some diagnostic information. The combined track vertex is then set to (0,0,0), which effectively throws the track away.
Use the diagnostic information generated to find the problem. …
=> Trap vertex error

offline/packages/trackreco/PHTruthVertexing.cc, offline/packages/trackreco/PHTruthVertexing.h
This PR adds functionality for the truth vertexing module to be run following the Acts reconstructed silicon seeder. Currently we see that the performance (DCA, efficiency, etc.) degrades considerably when using the Acts reconstructed initial vertex finder. This needs to be understood, but for the time being (to get people going on their own sims) this PR modifies the truth vertexing to be able to run with the Acts silicon seeder. This improves the performance considerably. …
=> Truth Initial Vertexing with Acts Silicon Seeding

offline/packages/KFParticle_sPHENIX/KFParticle_DST.cc, offline/packages/KFParticle_sPHENIX/KFParticle_eventReconstruction.cc, offline/packages/KFParticle_sPHENIX/KFParticle_nTuple.cc, offline/packages/KFParticle_sPHENIX/KFParticle_nTuple.h, offline/packages/KFParticle_sPHENIX/KFParticle_sPHENIX.cc, offline/packages/KFParticle_sPHENIX/KFParticle_sPHENIX.h, offline/packages/KFParticle_sPHENIX/KFParticle_truthAndDetTools.cc, offline/packages/KFParticle_sPHENIX/KFParticle_truthAndDetTools.h
A request was made to calculate the true DCA in the nTuple output. This is calculated from the true track parameters and the VtxPoint, if it exists. If the true VtxPoint does not exist then the true DCA is calculated wrt to the reconstructed vertex and a warning is given.
I also added some new DCA branches in the nTuple: DCA_xy and DCA error to aid in resolution studies. Please note that the DCA_xy error is not calculated. I also changed the units of the decay time from ctau to ps.
Lastly, the magnetic field was set to negative 1.5T. I changed this to positive 1.5T which matches our magnetic field map plot but I should check that there isn't a flip in the sign somewhere.
[comment]: <> ( What types of changes does your code …
=> Adding true DCA calculations to KFParticle output (nTuple only)

offline/packages/tpccalib/TpcSpaceChargeReconstruction.cc, offline/packages/tpccalib/TpcSpaceChargeReconstruction.h
This PR updates the space charge reconstruction code to align with latest results presented at collaboration meeting: 
- allows to configure maximum residuals and local track angles from steering macro
- properly account from track errors when forming the residual-based chisquare used for the distortion reconstruction
- when micromegas are used, extrapolate the reconstructed distortions to regions of the TPC acceptance that are not covered with Micromegas. Right now this extrapolation uses a number of hard coded numbers, from our "baseline" micromegas configuration. This will be updated and made more flexible once we converge on a setup for the Micromegas modules (both number of modules and position)
Remark: in principle …
=> Spacecharge reconstruction

simulation/g4simulation/g4eval/JetRecoEval.cc
Thanks to @cdean-github , who during the HF MDC1 test production found rare cases where 
```c++
maxtruthparticle = get_svtx_eval_stack()->get_track_eval()->max_truth_particle_by_nclusters(track);
```` 
would return `nullptr`. In extremes rare cases, noise hits in tracker could make a track and has no truth particle matching. Such case previously generates an `assert` error in the strict mode. This PR allow such case and handle it in the jeteval.   …
=> Handle in extreme rare cases, noise hits can make a track with no `maxtruthparticle` matched

simulation/g4simulation/g4eval/BaseTruthEval.cc, simulation/g4simulation/g4eval/BaseTruthEval.h, simulation/g4simulation/g4eval/JetRecoEval.cc, simulation/g4simulation/g4eval/JetRecoEval.h, simulation/g4simulation/g4eval/JetTruthEval.h, simulation/g4simulation/g4eval/SvtxTrackEval.cc, simulation/g4simulation/g4eval/SvtxTruthEval.cc, simulation/g4simulation/g4eval/SvtxTruthEval.h
Added PHG4FastSim exceptions needed in jet truth-reco matching.
Added Ability to name TrackNodeName to support changes ("SvtxTrackMap" -> "TrackMap"). Call it in jet analysis module.
=> FastSim Exception in TrackEval + Custom TrackNodeName Functions

offline/packages/trackreco/PHHybridSeeding.cc, offline/packages/trackreco/PHHybridSeeding.h
The TPC-to-silicon matching (PHSiliconTpcTrackMatching) expects momentum estimates at the vertex, while the old PHHybridSeeding was providing these estimates at the position of the innermost cluster. In this PR, PHHybridSeeding now provides these estimates at the vertex, significantly improving the ease of matching.
Other changes:
- Reverse cluster chain output from seeding core if it's arranged inside-out
- Fixed TPC tracklet charge assignment by flipping Bz when the parameter _fieldDir is negative
- Minor fixes to KF internals, improving numerical stability …
=> PHHybridSeeding silicon matching improvements

offline/packages/trackreco/PHActsTracks.cc, offline/packages/trackreco/PHActsTracks.h
I inadvertently added a bug into the vertex node accessing when trying to make the QA happy. This PR fixes that so that the second track fit pass actually access the final vertexing map `SvtxTrackMapActs` instead of the default `SvtxVertexMap`.
Macros [PR](https://github.com/sPHENIX-Collaboration/macros/pull/366)
=> fix vertex node access

offline/packages/trackreco/PHActsTracks.cc, offline/packages/trackreco/PHActsTrkFitter.cc, offline/packages/trackreco/PHActsVertexFinder.cc, offline/packages/trackreco/PHActsVertexFinder.h
This PR switches the ActsVertexFinder to use the SvtxVertexMap only, and then creates an SvtxVertexMapActs as a clone of the original vertex map. It also resets the track seed position to the vertex for the second fit pass
=> Set Acts Vertex Finder to use SvtxVertexMap

offline/packages/trackreco/PHSiliconTpcTrackMatching.cc, offline/packages/trackreco/PHTruthSiliconAssociation.cc
- [ x] Requiring change in macros repository (Please provide links to the macros pull request in the last section)
This PR significantly optimizes the search windows in PHSiliconTpcTrackMatching for high occupancy events. The MVTX matching efficiency after the optimization is ~ 93% above pT = 1 GeV/c. The matching efficiency at low pT is greatly improved over the previous tune. The new silicon matching efficiency vs pT is shown in the attached figure. …
=> Tune silicon tpc matcher

simulation/g4simulation/g4decayer/G4Pythia6Decayer.cc, simulation/g4simulation/g4decayer/P6DExtDecayerPhysics.cc, simulation/g4simulation/g4detectors/PHG4RICHSteppingAction.cc, simulation/g4simulation/g4detectors/PHG4SectorConstructor.cc, simulation/g4simulation/g4detectors/PHG4mRICHDetector.cc, simulation/g4simulation/g4detectors/ePHENIXRICHConstruction.cc, simulation/g4simulation/g4gdml/PHG4GDMLWrite.cc, simulation/g4simulation/g4gdml/PHG4GDMLWriteDefine.cc, simulation/g4simulation/g4gdml/PHG4GDMLWriteMaterials.cc, simulation/g4simulation/g4gdml/PHG4GDMLWriteSetup.cc, simulation/g4simulation/g4gdml/PHG4GDMLWriteSolids.cc, simulation/g4simulation/g4gdml/PHG4GDMLWriteStructure.cc, simulation/g4simulation/g4main/G4TBMagneticFieldSetup.cc, simulation/g4simulation/g4main/PHG4Reco.cc, simulation/g4simulation/g4main/PHG4RegionInformation.cc, simulation/g4simulation/g4main/PHG4TrackUserInfoV1.h
This PR replaces all uses of G4cout and G4endl by std::cout/std::endl. Trying to hunt down the use of an uninitialized variable in the G4 Streambuf which turns out to be likely caused by the static instantiation of this in G4ios.hh where the buffer which keeps the printout is not initialized. Anyway - we should have only one way to print stuff out. If it turns out that we need to use G4cout in multithreading we change it but having a mix is just bad
[comment]: <> ( In case this …
=> Remove g4cout

offline/packages/trackreco/PHActsInitialVertexFinder.cc, offline/packages/trackreco/PHActsInitialVertexFinder.h, simulation/g4simulation/g4eval/SvtxEvaluator.cc
This PR tunes the initial vertex finder to be used in both embedded and low occupancy events. It now works with very high efficiency for any number of track events greater than 2. I will make a macros PR to introduce it later, after the full reconstruction chain can be tested with it.
It also adds the vertex chi2 and NDF to the `ntp_vertex` tuple in the SvtxEvaluator.
=> Tune Initial Vertexing

simulation/g4simulation/g4eval/SvtxEvaluator.h
This PR finally set the use_initial_vertex to true (in the SvtxEvaluator.h which then passes this down to the SvtxVertexEval). That should make a lot of warnings go away - let's see what breaks
=> set use_initial_vertex to true

offline/packages/KFParticle_sPHENIX/KFParticle_Tools.cc, offline/packages/KFParticle_sPHENIX/KFParticle_Tools.h, offline/packages/KFParticle_sPHENIX/KFParticle_eventReconstruction.cc, offline/packages/KFParticle_sPHENIX/KFParticle_eventReconstruction.h, offline/packages/KFParticle_sPHENIX/KFParticle_particleList.cc, offline/packages/KFParticle_sPHENIX/KFParticle_sPHENIX.cc, offline/packages/KFParticle_sPHENIX/KFParticle_truthAndDetTools.cc
Occasionally we can reconstruct tracks from noise hits. When we try to truth match these tracks we get a null pointer and KFParticle crashes. I've added a check for this null pointer and set the truth variables to 0.
I found a bug in KFParticle reconstruction that affects analysis where a mother decays to a resonance and reconstructed tracks AND the resonance mass was not constrained (such as B+ -> D0 pi+ where the D0 mass was not fixed to the PDG mass). This would cause all the tracks to have no mass and no PID (see …
=> KFParticle: 2 fixes (ghosts and resonance/track bug)

offline/packages/trackreco/ActsTransformations.cc, offline/packages/trackreco/PHActsInitialVertexFinder.cc, offline/packages/trackreco/PHActsInitialVertexFinder.h
This PR adds functionality to the so-called InitialVertexFinder to run with an arbitrary trackmap and vertex map. This will allow users to run this module individually on whatever track map and vertex map that they want to. Note that the name `PHActsInitialVertexFinder` is only because the class is intended to slot in with the initial silicon seeder - all it does is take a generic `SvtxTrackMap` and convert the tracks to Acts track parameters, run the Acts vertex finder on them, then create an `SvtxVertexMap` with the output name. The module defaults to the setup for running after the silicon seeder, so users who want to …
=> Add options to run initial vertex finder by itself

generators/PHPythia6/PHPythia6.cc, generators/PHPythia6/PHPythia6.h, generators/PHPythia8/PHPythia8.cc, generators/PHPythia8/PHPythia8.h, generators/PHSartre/PHSartre.cc, generators/PHSartre/PHSartre.h, generators/phhepmc/Fun4AllHepMCInputManager.cc, generators/phhepmc/Fun4AllHepMCInputManager.h, generators/phhepmc/Fun4AllHepMCPileupInputManager.cc, generators/phhepmc/Fun4AllOscarInputManager.cc, generators/phhepmc/Fun4AllOscarInputManager.h, generators/phhepmc/Makefile.am, generators/phhepmc/PHHepMCGenEvent.cc, generators/phhepmc/PHHepMCGenEvent.h, generators/phhepmc/PHHepMCGenEventv1.cc, generators/phhepmc/PHHepMCGenEventv1.h, generators/phhepmc/PHHepMCGenEventv1LinkDef.h, generators/phhepmc/PHHepMCGenHelper.cc, generators/phhepmc/PHHepMCGenHelper.h, generators/sHEPGen/sHEPGen.C, generators/sHEPGen/sHEPGen.h, offline/packages/NodeDump/Makefile.am, simulation/g4simulation/g4main/HepMCNodeReader.cc, simulation/g4simulation/g4main/ReadEICFiles.cc, simulation/g4simulation/g4main/ReadEICFiles.h
Both sPHENIX and EIC are expected to run with a beam crossing angle, 2mrad for sPHENIX and 25mrad for EIC. This is in principal supported in our current event generator setup, as the reference frame for the event generator is detached from the lab frame which is used in the Geant4 simulation and reconstruction. This pull request further introduce the machinery to easily using the beam parameters
* Support inputs via user macro for beam angle, divergence, vertex shift in space time
* calculate the boost-rotation-shift that is used to …
=> Apply beam crossing angle to any event generator

offline/packages/trackreco/Makefile.am, offline/packages/trackreco/PHSiliconTpcTrackMatching.cc, offline/packages/trackreco/PHSiliconTpcTrackMatching.h, offline/packages/trackreco/PHTpcTrackSeedVertexAssoc.cc, offline/packages/trackreco/PHTpcTrackSeedVertexAssoc.h, offline/packages/trackreco/PHTruthSiliconAssociation.cc
This PR adds a module that runs after the TPC track seeding. The module is completely agnostic about which seeder is used, it just takes the pT estimate and the list of TPC clusters. It fits a straight line to the clusters in z vs radius and associates the track with a collision vertex, and determines eta from the fit. It fits a circle to the clusters in x vs y and assigns a phi angle at the vertex. The revised track position and track momentum components are updated in …
=> Tpc seed vtx assoc

offline/packages/trackbase/TrkrClusterContainer.cc
This speeds up FindOrAdd by a factor two when inserting clusters, by not parsing the map twice.
=> use lower_bound rather than find to check existence of cluster in map

offline/packages/micromegas/MicromegasClusterizer.cc, offline/packages/trackreco/PHTruthClustering.cc, simulation/g4simulation/g4eval/SvtxTruthEval.cc, simulation/g4simulation/g4micromegas/PHG4MicromegasHitReco.cc, simulation/g4simulation/g4micromegas/PHG4MicromegasHitReco.h
rather than adding the tiles to the existing micromegas geometry node inherited from Geant4,
- create a new node (CYLINDERGEOM_MICROMEGAS_FULL)
- copy the cylinder definition from the old, 
- and add the tiles there
this prevents having two nodes with the same name but different content when reading from multiple streams, and possibly crashing, depending on the order by which files are opened, as happened during MDC1. 
Updated the relevant modules (micromegas clustering, truthcluster module and evaluators) to use the new name.
Side note: one should be able to rebase this PR on top of master, rather than merge.
[comment]: …
=> Fix micromegas geometry nodenames

offline/packages/trackreco/PHSiliconTpcTrackMatching.cc, offline/packages/trackreco/PHTpcTrackSeedVertexAssoc.cc, offline/packages/trackreco/PHTpcTrackSeedVertexAssoc.h
Adds the option in PHTpcSeedVertexAssoc to reject outlying clusters in xy or z, using the fitted helix. They are set to false by default. Enabling the rejection in xy improves tracking efficiency in central Au+Au events with 50 kHz pileup to 71% from 66%. It also improves the pT resolution significantly. I think that both of these occur because the ACTS track fit is improved by the outlier rejection. The silicon TPC matching is not affected. 
[comment]: <> ( In case this …
=> Reject outlier clusters

offline/packages/trackreco/PHSimpleKFProp.cc, offline/packages/trackreco/PHSimpleKFProp.h
Fixing valgrind issues involving PHSimpleKFProp and SvtxTrackMap::erase. The propagator resets and rebuilds the track map rather than modifying in-place, which should be more reliable. 
=> Fixing valgrind issues

offline/packages/tpccalib/TpcSpaceChargeReconstructionHelper.cc, offline/packages/tpccalib/TpcSpaceChargeReconstructionHelper.h
- more static helper method
- fix a bug in the extrapolation procedure along phi, due to recalculating the (z-integrated) normalization factor, while filling the histogram along z.
=> fixed a bug in distortion extrapolation procedure

offline/packages/tpccalib/TpcSpaceChargeReconstructionHelper.cc
- prevent nan scale factors
- make sure bin error is always positive
This has no impact on using the reconstructed map since region of the acceptance where nan scale factors occur correspond to places where there is no measurement (typically r < 30cm), but can prevent plotting the distortion map for cross-checks (root doesn't like nans) …
=> protect against nan scale factors

generators/phhepmc/PHHepMCGenHelper.cc, generators/phhepmc/PHHepMCGenHelper.h
Following https://github.com/sPHENIX-Collaboration/coresoftware/pull/1087, this pull request implement two vertex-z dependency for any HepMC-based event generators:
* The average collision axis would be rotated from z-axis, when e.g. one beam is off z-axis in the EIC case. At approximation of the lateral beam width is the same between two beams, the collision axis is implemented in the middle between two beams. 
* The crab cavity rotate beam bunch to increase collision overlap between two bunches. It induces a bunch z dependence of the …
=> Implementing beam bunch z dependent of collision vertex and momentum tilt (Crab cavity kick)

offline/packages/KFParticle_sPHENIX/KFParticle_Tools.cc, offline/packages/KFParticle_sPHENIX/KFParticle_Tools.h, offline/packages/KFParticle_sPHENIX/KFParticle_eventReconstruction.cc, offline/packages/KFParticle_sPHENIX/KFParticle_nTuple.cc, offline/packages/KFParticle_sPHENIX/KFParticle_sPHENIX.cc, offline/packages/KFParticle_sPHENIX/KFParticle_sPHENIX.h, offline/packages/KFParticle_sPHENIX/KFParticle_truthAndDetTools.cc, offline/packages/KFParticle_sPHENIX/KFParticle_truthAndDetTools.h
A user requested the true PV info for each track which has been added to the nTuple
I improved the mother/PV selection to work on the lower IP chi2 for each mother
I fixed a bug in the DIRA. I had taken the absolute value which allowed the momentum and flight vectors to point in opposite directions. This led to strange effects in distributions such as the decay time and decay length.
Discuss with HFTG about adding calo information to selection and where this should go.
Figure out mother truth matching …
=> KFParticle: Added truth PV info and fixed DIRA bug

offline/packages/trackbase_historic/Makefile.am, offline/packages/trackbase_historic/SvtxTrack.h, offline/packages/trackbase_historic/SvtxTrack_FastSim.cc, offline/packages/trackbase_historic/SvtxTrack_FastSim_v1.cc, offline/packages/trackbase_historic/SvtxTrack_FastSim_v1.h, offline/packages/trackbase_historic/SvtxTrack_FastSim_v1LinkDef.h, offline/packages/trackbase_historic/SvtxTrack_v1.h, simulation/g4simulation/g4trackfastsim/Makefile.am, simulation/g4simulation/g4trackfastsim/PHG4TrackFastSim.cc, simulation/g4simulation/g4trackfastsim/PHG4TrackFastSim.h, simulation/g4simulation/g4trackfastsim/PHG4TrackFastSimEval.cc, simulation/g4simulation/g4trackfastsim/PHG4TrackFastSimEval.h
Following request by @FriederikeBock to introduce the constituent tracing for truth-based fast tracking tracks. 
- New version of `SvtxTrack_FastSim_v1` that associate truth-based fast tracking tracks to its constituent `PHG4Hit`s and containers. The format follow that of `PHG4Shower`
- Record the association in `PHG4TrackFastSim`
- Update the example evaluation analysis module `PHG4TrackFastSimEval` to output number of hit per PHG4HitContainer per track. Example output fast tracking ntuple from the default `Fun4All_G4_EICDetector.C` …
=> Add constituent tracing for truth-based fast tracking tracks

offline/packages/trackreco/PHTruthTrackSeeding.cc, offline/packages/trackreco/configure.ac
Using G4ParticleTable to get particle charge from pid might result in a crash of the macro, because G4ParticleTable might not be initialized at the time of the first call. This happens for instance when running reconstruction only modules on DSTs containing G4Hits.
Instead of figuring out what needs to be initialized to prevent the crash, use TDatabasePDG instead of G4ParticleTable to get charge from PID, as done in e.g. QA/modules/QAG4SimulationTracking.cc
At the same time, reverted the changes to configure.ac about warning suppression, since they have become (hopefully) unnecessary here.
[comment]: <> ( What does this …
=> use TDatabasePDG instead of G4ParticleTable to get charge from PID

offline/packages/trackreco/PHSiliconTpcTrackMatching.cc
This fixes a memory leak issue that was identified by valgrind also in PHActsSiliconSeeding. The same code is here, so we fix it to get rid of a mem leak in this module also.
=> Fix other instance of track.release memory leak

offline/packages/trackreco/ALICEKF.cc, offline/packages/trackreco/ALICEKF.h, offline/packages/trackreco/PHSimpleKFProp.cc, offline/packages/trackreco/PHSimpleKFProp.h
Fixed bug where PHSimpleKFProp uses an antiquated version of getClusters(). Also updated ALICE KF to include constant-field and fixed-cluster-error options.
=> TPC propagator cluster getter fix, and small ALICE KF update

offline/framework/fun4allraw/Fun4AllRolloverFileOutStream.cc, offline/framework/phoolraw/PHRawOManager.cc, offline/framework/phoolraw/configure.ac
This PR switches our raw data buffers from ogzBuffer to ospBuffer (in offline/framework/phoolraw and fun4allraw). That also fixes the recent crash of the builds. Right now this is not in the build, once this PR is through and we sorted out the jenkins failures those packages will go back into the build …
=> switch from ogzBuffer to opsBuffer

generators/PHSartre/PHSartreParticleTrigger.cc, offline/packages/micromegas/MicromegasClusterizer.cc, simulation/g4simulation/g4micromegas/PHG4MicromegasHitReco.cc
This fixes the micromegas toolchain after recent coresoftware changes:
- use proper version for TrkrHit in MicromegasHitReco
- make sure clusters are properly stored in cluster map at the end of MicromegasClusterizer
Note that ACTS tracking is still broken: no micromegas hits are added to tracks. But GenFit is working as before. 
Fixing ACTS will be the subject of another pull request …
=> Fix micromegas

offline/packages/trackreco/PHTruthVertexing.cc, simulation/g4simulation/g4main/PHG4Particlev2.cc
This PR fixes a bug in the silicon stub association with the truth vertex when there are multiple vertices in an event. It also adds a phi/eta printout to the G4particle class, which can be useful for debugging sometimes.
=> Silicon Stub Association

simulation/g4simulation/g4main/PHG4TruthInfoContainer.cc, simulation/g4simulation/g4main/PHG4TruthInfoContainer.h, simulation/g4simulation/g4main/PHG4TruthTrackingAction.cc, simulation/g4simulation/g4main/PHG4TruthTrackingAction.h
As discussed in my talk (see https://plexoos.github.io/pub-docs/sphenix-simu-mem/s2.html) this implements a stack of Geant4 tracks. This stack is used to remove particles from the output truth container as Geant4 provides them instead of collecting all particles and deleting selected ones at the end of event. This approach helps to reduce the maximum amount of memory allocated by simulation jobs.
Previously unsuccessful PR #1081 …
=> Reject Geant4 tracks during filling of truth container

offline/packages/NodeDump/DumpTrkrClusterHitAssoc.cc, offline/packages/NodeDump/DumpTrkrClusterHitAssoc.h, offline/packages/NodeDump/DumpTrkrHitSetContainer.cc, offline/packages/NodeDump/Makefile.am, offline/packages/NodeDump/PHNodeDump.cc, offline/packages/trackbase/TrkrClusterHitAssoc.h
This is for the preparation of the DST conversion. The pure virtual base class prevented the v1 to be instantiated. Added the printout of TrkrClusterHitAssoc for comparison if successful
=> Fix baseclass

offline/packages/trackbase_historic/SvtxTrack.h, offline/packages/trackbase_historic/SvtxTrack_FastSim.cc, offline/packages/trackbase_historic/SvtxTrack_FastSim.h, offline/packages/trackbase_historic/SvtxTrack_FastSim_v1.cc, offline/packages/trackbase_historic/SvtxTrack_FastSim_v1.h, offline/packages/trackbase_historic/SvtxTrack_v1.cc, offline/packages/trackbase_historic/SvtxTrack_v1.h, offline/packages/trackbase_historic/SvtxTrack_v2.cc, offline/packages/trackbase_historic/SvtxTrack_v2.h, offline/packages/trackreco/PHGenFitTrkFitter.cc, offline/packages/trackreco/PHTruthTrackSeeding.cc
In order to fix GenFit track fitting with both truth or full track finding, one must make it agnostic to the version of the SvtxTrk object provided by the track finding. To achieve this one introduces a CopyFrom to the lastest SvtxTrk object that takes the base class as constructor, and makes use of it inside the GenFitTrackFitter.
CopyFrom method should also be implemented for the other older SvtxTrack objects. This will be the subject for another PR. …
=> more tracking fixes

offline/packages/trackbase_historic/Makefile.am, offline/packages/trackbase_historic/SvtxTrack_FastSim.cc, offline/packages/trackbase_historic/SvtxTrack_FastSim.h, offline/packages/trackbase_historic/SvtxTrack_FastSim_v1.cc, offline/packages/trackbase_historic/SvtxTrack_FastSim_v1.h, offline/packages/trackbase_historic/SvtxTrack_FastSim_v2.cc, offline/packages/trackbase_historic/SvtxTrack_FastSim_v2.h, offline/packages/trackbase_historic/SvtxTrack_FastSim_v2LinkDef.h, offline/packages/trackbase_historic/SvtxTrack_v2.h, offline/packages/trackreco/PHSiliconTruthTrackSeeding.cc, offline/packages/trackreco/PHTruthTrackSeeding.cc
This PR creates a new SvtxTrack_FastSim_v2 class that 
- inherits from SvtxTrack_v2
- implements the additional functionalities of both SvtxTrack_FastSim and SvtxTrack_FastSim_v1
This new class is now the one constructed in trackreco/PHSiliconTruthTrackSeeding and trackreco/PHTruthTrackSeeding.
This allows to fully run ACTS on top of these modules, and in particular properly store and retrieve the newly introduced 6x6 ACTS covariance matrix. This in turn should allow to run ACTS final vertex fit. 
Classes SvtxTrack_FastSim_v1 and SvtxTrack_FastSim_v2 are marked as "final" because future versions of SvtxTrack_FastSim will have to inherit not from the previous version but from whatever latest version of FvtxTrack_vXXX there …
=> svtxtrack fastsim

offline/packages/trackreco/PHCASeeding.cc, offline/packages/trackreco/PHHybridSeeding.cc, offline/packages/trackreco/PHSiliconTruthTrackSeeding.cc, offline/packages/trackreco/PHTrackSeeding.cc, offline/packages/trackreco/PHTruthTrackSeeding.cc
This PR just removes the requirement from PHTrackSeeding (the seeding base class) that the SvtxVertexMap be present during instantiation. Now the derived classes get a pointer to SvtxVertexMap as needed. This was needed to allow the reorganization of the G4_Tracking.C macro. It should be transparent to users. …
=> Modify PHTrackSeeding

offline/QA/modules/QAG4SimulationTracking.cc, offline/QA/modules/QAG4SimulationTracking.h
In order to also get the number of micromegas clusters per layer per truth track (histogram named nClus_layerGen one must also get the micromegas G4Hit node, and look there to find G4Hits associated to tracks. 
After the patch, said histogram looks like this: 
The last two layers are the micromegas ones
=> Another fix about Micromegas in Tracking QA

offline/packages/tpc/TpcClusterizer.cc
This PR
- binds thread_p and thread_data to a small structure so that you only need one array to manipulate them
- use a std::vector to store said structures instead of a fixed size std::array. We reserve the proper vector size to the number of per-event non-empty hitsetids in order to avoid unnecessary reallocations. This should reduce the memory footprint of the method without any impact on performaces (checked the latter)
- also gotten rid of using namespace std, and changed NULL to nullptr.
There is a chance that cppcheck/clang complain about unitialized variables in the structs. We will see. …
=> tpc clusterizer

offline/QA/modules/QAG4SimulationIntt.cc, offline/QA/modules/QAG4SimulationMicromegas.cc, offline/QA/modules/QAG4SimulationMvtx.cc, offline/QA/modules/QAG4SimulationTpc.cc, offline/QA/modules/QAG4SimulationTracking.cc, offline/packages/intt/InttClusterizer.cc, offline/packages/micromegas/MicromegasClusterizer.cc, offline/packages/mvtx/MvtxClusterizer.cc, offline/packages/tpc/TpcClusterizer.cc, offline/packages/trackbase/Makefile.am, offline/packages/trackbase/TrkrClusterContainerv1.cc, offline/packages/trackbase/TrkrClusterContainerv2.cc, offline/packages/trackbase/TrkrClusterContainerv3.cc, offline/packages/trackbase/TrkrClusterContainerv3.h, offline/packages/trackbase/TrkrClusterContainerv3LinkDef.h, offline/packages/trackbase/TrkrClusterHitAssocv3.cc, offline/packages/trackbase/TrkrClusterHitAssocv3.h, offline/packages/trackbase/TrkrClusterHitAssocv3LinkDef.h, offline/packages/trackreco/PHCASeeding.cc, offline/packages/trackreco/PHSiliconTruthTrackSeeding.cc, offline/packages/trackreco/PHTrackSeeding.cc, offline/packages/trackreco/PHTruthClustering.cc, simulation/g4simulation/g4eval/SvtxClusterEval.cc, simulation/g4simulation/g4eval/SvtxEvaluator.cc
This is the second PR that addresses issues in the TrkrClusterContainer and TrkrClusterHitAssoc. 
It introduces TrkrClusterContainerv3 and TrkrClusterHitAssocv3
Both use a map, with hitsetid as a key, to store the detector specific cluster (and cluster-to-hit association) maps, instead of fixed size 3D array. This fixed the various out-of-bound isses reported with the v2. 
I have not noticed any significant slowdown when accessing these maps instead of the fix-sized arrays, mostly because the number of hitsetids (as opposed to hits or clusters) is reasonably small. 
[comment]: <> ( What does this PR do? Linking to talk …
=> Master fix clustercontainers

offline/QA/modules/QAG4SimulationMicromegas.cc, offline/QA/modules/QAG4SimulationMicromegas.h, offline/packages/micromegas/CylinderGeomMicromegas.cc, offline/packages/micromegas/CylinderGeomMicromegas.h, offline/packages/micromegas/MicromegasClusterizer.cc, offline/packages/micromegas/MicromegasTile.h, offline/packages/trackreco/PHGenFitTrkFitter.cc, simulation/g4simulation/g4micromegas/PHG4MicromegasHitReco.cc, simulation/g4simulation/g4micromegas/PHG4MicromegasHitReco.h
This is the first of two PR that implements new micromegas geometry, consisting of planar tiles located around the TPC instead of portions of cylinders. Rather than using polar coordinates to find fired strips, cluster positions etc. one now use a local reference frame for each micromegas, and convert (world_to_local, local_to_world) to and from this frame to do all the position handling.
The Geant4 micromegas implementation is unchanged: two cylinders that cover the full TPC acceptance. 
G4Hits generated with those are 'translated' to the planar implementation in G4HitReco
Genfit and QA evaluators are modified to properly handle this geometry change. 
ACTS is slightly more broken than before with this change, but was broken …
=> New micromegas geometry

offline/packages/trackreco/PHActsTrkFitter.cc, offline/packages/trackreco/PHActsTrkFitter.h, offline/packages/trackreco/PHTpcResiduals.cc
This PR creates a new `SvtxTrackMap` for the results of the silicon+MM track fitting and has the TPC residual calculation module grab that instead. This leaves the original track map alone and then allows us to work with a single silicon+MM track fit map. 
=> Directed fitter fixes

offline/packages/trackreco/PHActsInitialVertexFinder.cc, offline/packages/trackreco/PHActsInitialVertexFinder.h
Add catch for nTracks < nCentroids
This PR fixes a few issues in the Acts::IVF:
1. It adds a catch for the case where there are no silicon seeds produced. In this case, the IVF returns a dummy vertex of (0,0,0)
2.  It adds a catch for the case where the number of silicon tracks is less than the number of centroids in the initial silicon stub cleaning algorithm. In this case, the number of centroids is just set to 1. This only occurs when there are a small number of tracks (i.e. less than 5).
3. It updates the random number generator used in the centroid clustering algorithm to use that of the `RANDOMSEED` flag, so that …
=> Fix Acts Initial Vertex Finder Issues

simulation/g4simulation/g4eval/EventEvaluator.cc, simulation/g4simulation/g4eval/EventEvaluator.h
This enables storing the tracking output from multiple sources of tracks
in the event evaluator (say, running the tracking twice with different
parameters). The tracks are stored in one collection, and then
differentiated by a source ID. The user then needs to differentiate the
sources. However, if there is only one collection of tracks, then the
source can be ignored
@FriederikeBock  …
=> Add additional track sources to event evaluator

offline/packages/trackbase/TrkrCluster.h, offline/packages/trackbase/TrkrClusterContainer.h, offline/packages/trackbase/TrkrClusterHitAssoc.h, offline/packages/trackbase/TrkrHitSet.h, offline/packages/trackbase/TrkrHitSetContainer.h, offline/packages/trackbase/TrkrHitTruthAssoc.h
The TrkrHitSetContainer base class size() method was not virtual which prevented the derived classes from implementing it. There is a way to use the override keyword without triggering warnings from the ClassDef macro by using the ClassDefOverride macro instead
[https://root-forum.cern.ch/t/annoying-warnings-using-c-11-14/20891/2]. This turns the problem around since now one gets warnings from PHObject. If we ever do this it needs to be implemented all at one
[comment]: <> ( In …
=> Fix trkr hit set container

offline/packages/trackreco/MakeActsGeometry.cc, offline/packages/trackreco/MakeActsGeometry.h, offline/packages/trackreco/PHActsTrkFitter.cc
This PR enables a second pass of the tracking to be run on the output file from a first pass. Because we are not able to write out Acts surface objects, we have to make the clusterSurfaceMaps in the second pass by running MakeActsGeometry in that pass too. These changes are required so that the fake surfaces for the TPC and Micromegas are not added to the geometry a second time, before the clusterSurfaceMaps are made in the second pass. …
=> Changes to enable second pass tracking

simulation/g4simulation/g4trackfastsim/PHG4TrackFastSimEval.cc
…-Collaboration/coresoftware/pull/1115
The initialization order for `m_TracksEvalTree` was reversed during the reorganization of `PHG4TrackFastSimEval` as in #1115. This pull request correct for that.
#1115
=> Fixing a fast tracking initialization bug introduced in #1115

offline/packages/trackreco/PHActsInitialVertexFinder.cc, offline/packages/trackreco/PHActsInitialVertexFinder.h
This adds an option to remove the silicon seeds from the track map that are not used in the initial vertexing. Note that is turned off by default, and there is an accessor function to set it in the macro with e.g.
```
init_vtx->removeSiliconSeeds(true);
```
=> Add option to remove silicon seeds

offline/packages/trackreco/PHActsTrkFitter.cc, offline/packages/trackreco/PHActsTrkFitter.h
hard coded volume id for Micomegas surface was incorrect since the new micromegas geometry was implemented.
This result in all tracks to be discarded in the SCCalibMode fit (Silicium+MM track fits)
rather than hard code the new volume, store all possible volumes in a std::set when calling GetNodes, and use that to identify MM surfaces. this should be more robust to future changes …
=> Fix mm volume id detection in ActsTrkFitter

offline/packages/trackreco/PHActsInitialVertexFinder.cc
This PR adds a check to run the silicon seed selection only for the cases where the Acts iterative vertex finder is run with the silicon seeds. The HFTG uses this module for generic vertex finding, which pulled up a bug when testing with the MDC data.
=> Iterative vertex finder bug fix

offline/packages/tpccalib/PHTpcResiduals.cc, offline/packages/tpccalib/PHTpcResiduals.h
This PR fixes a couple of issues introduced when writting space charge reconstruction matrices to output file. 
The evaluation histograms and ntuples, previously written to the same file, were erased when writing the matrices.
They are now written to a different file. Additionally, there is now a flag to turn these off, since they are only meant for debugging. …
=> store evaluation histogram to separate file, add flag to disable, turn off by default

offline/packages/trackbase/ActsSurfaceMaps.cc, offline/packages/trackbase/ActsSurfaceMaps.h, offline/packages/trackbase/Makefile.am, offline/packages/trackreco/MakeActsGeometry.cc, offline/packages/trackreco/PHActsTrkFitter.cc, offline/packages/trackreco/PHActsTrkFitter.h
Since the micromegas geometry reimplementation in ACTS, the main TPC volume ID has changed from 14 to 12, likely  because of how ACTS handles Geant volumes internally when converting to ACTS geometry. 
This breaks the volume-id based identification of TPC surfaces in ActsTrkFitter.
Rather than updating the hard-coded volume id used for this identifiation, an std::set is used to store TPC relevant volume IDs. It is filled from TPC surfaces when calling GetNodes and is used for TPC surfaces identifiaction.
This is essentially the same change as in https://github.com/sPHENIX-Collaboration/coresoftware/pull/1194, but for the TPC
Following suggestion from Joe, the std::sets for Micromegas and TPC are moved to ActsSurfaceMap, and filled in MakeActsGeom.
Two convenience functions are added to …
=> Fix TPC volume id detection in ActsTrkFitter

offline/packages/trackreco/PHActsInitialVertexFinder.cc
This PR fixes the bug that was introduced by me that breaks the silicon seed sorting in the initial IVF. Vertexing and DCA QA in high occupancy should be fixed now.
=> Fix High Occupancy vertexing

offline/packages/PHGeometry/Makefile.am, offline/packages/PHGeometry/PHGeomUtility.cc, offline/packages/PHGeometry/PHGeomUtility.h
The automatic G4->Reconstruction geometry export involves a GDML file write in the `/tmp` folder by default. Sometimes the file names are duplicated between [two processes of the same PID which causes file write error](https://chat.sdcc.bnl.gov/ecce/pl/kgbamwkgr7rkffsm9mhpkxxexr). 
This pull request resolve this problem by:
1. ensuring the GDML file name is unique with a UUID, such as in the new begin run STDOUT print of `PHG4Reco::InitRun - export geometry to DST via tmp file …
=> Automatic geometry export using unique file names

simulation/g4simulation/g4main/Fun4AllDstPileupMerger.cc, simulation/g4simulation/g4main/PHG4PhenixStackingAction.h, simulation/g4simulation/g4main/PHG4Reco.cc, simulation/g4simulation/g4main/PHG4StackingAction.h
The stacking action left an annoying printout. This PR adds a hook to PrepareNewEvent() for the stacking action
=> remove printout, add PrepareNewEvent() to PHG4StackingAction, remove shadowed vars

simulation/g4simulation/g4main/PHG4PhenixStackingAction.cc, simulation/g4simulation/g4main/PHG4PhenixStackingAction.h
The PrepareNewEvent() was implemented as empty method which then did not loop over the subsystem PrepareNewEvent() methods
=> fix interface to PrepareNewEvent()

simulation/g4simulation/g4detectors/PHG4BlockDetector.cc, simulation/g4simulation/g4detectors/PHG4ConeDetector.cc, simulation/g4simulation/g4detectors/PHG4ConeSubsystem.cc, simulation/g4simulation/g4detectors/PHG4CylinderDetector.cc, simulation/g4simulation/g4detectors/PHG4CylinderSubsystem.cc
Following bug report at https://discourse.sdcc.bnl.gov/t/zdcsurrogate-rotation-in-y-not-being-performed/207 , implementing X-Y-Z rotations in simple subsystems. 
If more than one rotation is given, the input is ambiguous, and the rotation will be executed in the order of X->Y->Z with a warning message explicitly printing out the rotation matrix. 
=> X-Y-Z rotations in simple subsystems

calibrations/tpc/cm/CMDistortionAnalysis.C, calibrations/tpc/cm/CMDistortionAnalysisCart.C, calibrations/tpc/cm/CMDistortionAnalysisPhiR.C, calibrations/tpc/cm/CMDistortionReco.C, calibrations/tpc/cm/CMDistortionRecoCart.C, calibrations/tpc/cm/CMDistortionRecoPhiR.C, calibrations/tpc/generator/AnalyticFieldModel.cc, calibrations/tpc/generator/AnalyticFieldModel.h, calibrations/tpc/generator/AnnularFieldSim.cc, calibrations/tpc/generator/AnnularFieldSim.h, calibrations/tpc/generator/Rossegger.cc, calibrations/tpc/generator/Rossegger.h
Introduces code to calculate TPC distortions from Central Membrane (CM) data. Includes cartesian and r, phi binning versions and analysis. Not technically a member yet but I am working with Ross Corliss.
Macros use CM hits and interpolate a 3D distortion fluctuation. 
https://indico.bnl.gov/event/11165/contributions/50614/attachments/35073/57038/6_8%20CM.pdf …
=> Pushing in cm distortion code.

simulation/g4simulation/g4eval/EventEvaluator.cc, simulation/g4simulation/g4eval/EventEvaluator.h
[comment]: This PR adds a geometry tree that saves the eta/phi position and coordinates of the calorimeter towers. The output is not active by default and can be switched on in the EventEvaluator via GEOMETRYTREE in the special settings string.<> (Please tell us something about this pull request)
=> addition of geometry tree for calorimeters

offline/packages/trackreco/ALICEKF.cc, offline/packages/trackreco/PHCASeeding.cc, offline/packages/trackreco/PHCASeeding.h, offline/packages/trackreco/PHSimpleKFProp.cc, offline/packages/trackreco/PHSimpleKFProp.h
Introduces changes in CA seeding and propagation that significantly increase the efficiency and average length of TPC tracks.
Implements several modifications to CA seeding that improve its momentum estimates and result in cleaner cluster chains before Kalman filtering. Also implements modifications to the propagator so that its use now increases tracking efficiency and track length across the board. …
=> CA seeding and propagator overhaul

generators/PHPythia8/PHPythia8.cc, generators/PHPythia8/PHPythia8.h, simulation/g4simulation/g4eval/EventEvaluator.cc, simulation/g4simulation/g4eval/EventEvaluator.h
Add event level info to the event evaluator (xsec, event weight, etc). To do so, the Pythia8 event weight is now stored in the HepMC event. Based on how these weights are used, I don't think this is used, but to be safe, the option is off by default.
Also add some track DCA values
@FriederikeBock 
=> Add event level info to event evaluator

offline/packages/trackreco/PHSimpleKFProp.cc
Fixes issue where invalid read occurred when browsing a list of layers of a lengthened track. The list of layers was not updated at the same time as the track itself, so under certain conditions the list of layers could be read out of bounds.
Updates layer list when clusters are added to track, iterates over length of layer list when checking if layer is already occupied, and no longer removes cluster keys from the original cluster key list when a cluster is rejected as an outlier, instead simply not adding it to the propagated track. …
=> PHSimpleKFProp valgrind fix

simulation/g4simulation/g4eval/EventEvaluator.cc
[comment]: In case no vertex is found, the cluster pseudorapidity will now be determined with respect to the coordinates (0,0,0). 
=> EventEvaluator fix for missing cluster eta

simulation/g4simulation/g4calo/HcalRawTowerBuilder.cc, simulation/g4simulation/g4detectors/PHG4HcalDefs.h, simulation/g4simulation/g4detectors/PHG4InnerHcalDetector.cc, simulation/g4simulation/g4detectors/PHG4InnerHcalDetector.h, simulation/g4simulation/g4detectors/PHG4InnerHcalSubsystem.cc
This set of modifications enables asymmetric configurations of the inner HCAL both in terms of the location and length along the z-axis as well as the eta coverage and number of scintillating tiles.  In ECCE this is needed because the iHCAL frame needs to extend further on the electron going side to support the barrel EMCal. 
Conceptually there are two changes:
(1) Previously, if the module was shifted in z to account for a longer size on one side than the other, the scintillation tiles would no longer be projective with respect to the center of the experiment, but would be projective with respect to the center of the iHCAL.
(2) The new parameters n_scinti_tiles_pos, …
=> mods to allow for asymmetric iHCAL configurations (for ECCE)

simulation/g4simulation/g4eval/EventEvaluator.cc, simulation/g4simulation/g4eval/EventEvaluator.h
Resubmitting https://github.com/ECCE-EIC/coresoftware/pull/2
- [ x] Breaking change (fix or feature that would cause existing functionality to not work for users)
In the EventEvaluator, there are several variables (HEPMC pdgID, mcpart ID's) that are added to the tree as floats, as opposed to ints (their natural representation).  I have changed this, although this will require some people to redo their macros when reading back the output files. …
=> EventEvaluator: changed PDG IDs, mcpart IDs, and status variables from float to int

simulation/g4simulation/g4trackfastsim/PHG4TrackFastSimEval.cc
Bug fix for the evaluator output reset for truth tracking (used in EIC studies)
=> Bug fix on fast tracking eval's variable reset

simulation/g4simulation/g4eval/EventEvaluator.cc
[comment]: Just a small fix to obtain the correct projection layers in the EventEvaluator, since the projections are named without "_0".
=> fixed naming of projection layers in EventEvaluator

offline/packages/tpccalib/PHTpcResiduals.cc, offline/packages/trackreco/ActsTransformations.cc, offline/packages/trackreco/ActsTransformations.h, offline/packages/trackreco/PHActsTrkFitter.cc, offline/packages/trackreco/PHActsTrkFitter.h
In this PR, one uses the fit parameters position, instead of the measurement position to fill the track's Svx StateVector
This 
- is consistent with what is done in GenFit
- fixes discrepancies between GenFit and ACTS when looking at residuals (track - truth or track-clusters) as disscussed there: https://phenix-intra.sdcc.bnl.gov/WWW/p/draft/hpereira/sphenix/Tracking_meeting_2021_03_29/talk.pdf
- is needed to be able to compare track and cluster position in a given layer (whith TPC included in the fit), when running e.g. millepede to perform track-based alignment.
Also added some tiny optimizations and c++ cosmetics 
I'll prepare some slides about this for the next tracking meeting, on Monday July 19.  …
=> Acts state vectors

simulation/g4simulation/g4eval/SvtxEvaluator.cc, simulation/g4simulation/g4eval/SvtxEvaluator.h
Added switch to turn on and off scanning for only primary particles in the ntp_gtrack ntuple
scan_for_primaries(true) -> output contains only primary particles [default]
scan_for_primaries(false) -> output contains primaries and all secondaries
=> add scan for primaries

simulation/g4simulation/g4eval/EventEvaluator.cc
In the event evaluator, there was an addition of the cross section as an output branch. This is only available in certain generators such as pythia8. When the object was created it could return a null pointer which would crash Fun4All on the next access. Simple fix:
```c++
auto xsec = truthevent->cross_section();
if (xsec)
{
_cross_section = xsec->cross_section();
}
``` …
=> Patched missing null check for EventEvaluator

simulation/g4simulation/g4tpc/Makefile.am, simulation/g4simulation/g4tpc/PHG4TpcCentralMembrane.cc, simulation/g4simulation/g4tpc/PHG4TpcCentralMembrane.h, simulation/g4simulation/g4tpc/PHG4TpcDirectLaser.cc, simulation/g4simulation/g4tpc/PHG4TpcDirectLaser.h, simulation/g4simulation/g4tpc/PHG4TpcElectronDrift.cc, simulation/g4simulation/g4tpc/PHG4TpcElectronDrift.h
This PR introduces central membrane flashes and steerable directed lasers to the TPC data by generating g4hit sets representing the laser tracks and central membrane stripes and adding these into the g4hit set that is drifted in PHG4TpcElectronDrift.  These features are disabled by default.   A modified G4_TPC.C macro is needed to interact with them properly.  The associated pull request will be generated shortly.
A complete version of this ought to interact with the g4hits independently, rather than adding to the record directly in the drift code.  Methods for controlling the lasers are currently exposed by providing …
=> Tpc lasers

offline/packages/tpc/TpcClusterCleaner.cc, offline/packages/tpc/TpcClusterCleaner.h, offline/packages/trackreco/PHActsTrkFitter.cc, offline/packages/trackreco/PHTpcTrackSeedVertexAssoc.cc
This PR primarily fixes a bug in "packages/tpc/TpcClusterCleaner". The cluster cleaner previously increased the covariance on the 3D cluster position for any cluster for which the XY covariance was too small - which occurs because the cluster contains a large signal from delta electrons, and the cluster position is therefore bad. The cluster was kept with an increased error to help the track seeder connect the layers. When the cluster container was modified to store the local …
=> Fix cluster cleaner

offline/packages/trackreco/PHActsInitialVertexFinder.cc, offline/packages/trackreco/PHActsInitialVertexFinder.h, offline/packages/trackreco/PHActsSiliconSeeding.cc
This PR expands the initial silicon seed clustering algorithm to include the transverse direction. The clustering is performed based on a 3D radial distance now instead of just along the z axis, which helps remove tracks in the transverse direction that are inconsistent with the vertex cluster.
=> Vertexing Clustering Improvement

offline/packages/trackreco/PHSiliconTpcTrackMatching.cc, offline/packages/trackreco/PHTpcTrackSeedVertexAssoc.cc, offline/packages/trackreco/PHTpcTrackSeedVertexAssoc.h
Modify tracking so that the silicon and TPC seeds are always given the position of the PCA (point of closest approach) of the helical fit to the clusters, rather than the nearest vertex associated with the track. This accomodates tracks that are not from a primary vertex. Tested with MB Hijing + 50 KHz events with 100 pions embedded. No detectable effect on the tracking performance was seen. See the slides at: the tracking meeting today: …
=> Modify track seed position

offline/packages/trackreco/PHActsSiliconSeeding.cc
This PR expands the silicon seeding vertex collision region to include the nominal sPHENIX beam parameter spread for pythia events. It fixes a bug that caused ~20% of pythia events to return 0 silicon seeds.
=> Missing vertices

simulation/g4simulation/g4eval/SvtxEvaluator.cc, simulation/g4simulation/g4eval/SvtxEvaluator.h, simulation/g4simulation/g4main/HepMCNodeReader.cc, simulation/g4simulation/g4main/HepMCNodeReader.h
Add switch to HepMCNodeReader to override PYTHIA's
assignment of a single vertex to each particle
with the collision vertex
This PR adds two switches to the `SvtxEvaluator` and the `HepMCNodeReader`. Both are off by default.
For the `SvtxEvaluator`, a separate switch is added for performing the light vertex evaluation. This way one can perform the light g4hit evaluation while doing heavy g4vertex evaluation, rather than having to do light or heavy evaluation for both at the same time.
For the `HepMCNodeReader`, a switch is added that overrides PYTHIA's default assigning of a single vertex to every particle. When the …
=> Improve Vertex Evaluation

offline/packages/KFParticle_sPHENIX/KFParticle_sPHENIX.h, offline/packages/compressor/compress_clu_res_float32.cc, offline/packages/tpccalib/PHTpcResiduals.h, offline/packages/trackbase/TrkrClusterv1.cc, simulation/g4simulation/g4eval/SvtxClusterEval.cc, simulation/g4simulation/g4eval/SvtxTruthEval.cc, simulation/g4simulation/g4tpc/PHG4TpcEndCapDetector.cc, simulation/g4simulation/g4tpc/PHG4TpcEndCapDetector.h
cppcheck found a bad array initialization in TrkrClusterv1.cc which probably never affected the code. Fixed a few other benign cppcheck performance warnings
=> Fix cppcheck

simulation/g4simulation/g4detectors/PHG4ZDCDetector.cc, simulation/g4simulation/g4detectors/PHG4ZDCDetector.h, simulation/g4simulation/g4detectors/PHG4ZDCDisplayAction.cc, simulation/g4simulation/g4detectors/PHG4ZDCSteppingAction.cc, simulation/g4simulation/g4detectors/PHG4ZDCSteppingAction.h, simulation/g4simulation/g4detectors/PHG4ZDCSubsystem.cc
Added SMD(7*8 scintillator blocks) in between the first and second modules of ZDC. Modified the stepping, energy loss when particles in SMD, Cherenkov if in the PMMA fiber. idx_j from 10 to 23, idx_k from 10 to 17 are for the SMD.
Modified the ZDC subsystem, added two int parameters: fzdc, bzdc. We can now build ZDC in the forward or backward region by setting fzdc or bzdc to 1(or do both). …
=> added SDM, ZDC is now able to be built one at a time

simulation/g4simulation/g4gdml/PHG4GDMLWriteMaterials.cc
In the G4->Reconstruction geometry transporter, avoids a to-be-deprecated function call to Geant4, i.e. `ptable->GetPropertiesMap()` and `ptable->GetPropertiesCMap()`
=> avoid to-be-deprecated GetPropertiesMap() and GetPropertiesCMap() in Geant4

offline/packages/trackbase/TrkrDefs.h, simulation/g4simulation/g4main/PHG4Reco.cc
[comment]: This PR adds the TTL layers as an option in the TrkrDefs. In addition, the material for LYSO crystals is defined, which is needed for an ECCE detector system.
=> necessary changes for TTL tracking and LYSO layer implementation

offline/packages/trackreco/Makefile.am, offline/packages/trackreco/PHActsTrkFitter.cc, offline/packages/trackreco/PHGhostRejection.cc, offline/packages/trackreco/PHGhostRejection.h, offline/packages/trackreco/PHMicromegasTpcTrackMatching.cc, offline/packages/trackreco/PHSiliconTpcTrackMatching.cc, offline/packages/trackreco/PHTrackCleaner.cc, offline/packages/trackreco/PHTrackCleaner.h, offline/packages/trackreco/PHTruthSiliconAssociation.cc, simulation/g4simulation/g4eval/SvtxEvaluator.cc
This PR adds a module to reject duplicate ("ghost") tracks. It can be run on the TPC track seeds after vertex association, or on the full tracks after the first track fitter is run. Because of the way the CA seeder works, it is very efficient but produces roughly two (usually identical) seeds per truth track. This module compares (x,y,z), phi and eta for every pair of tracks. When it finds matches, it keeps the track having the best chisq/ndf and deletes the others. …
=> Ghost track rejector module

offline/packages/trackreco/PHTruthTrackSeeding.cc, offline/packages/trackreco/PHTruthTrackSeeding.h
This PR adds a circle fit option to the truth seeding algorithm. The option is off by default. When turned on, the clusters that are accumulated by the truth seeding are used for a circle fit to determine the track seed parameters. This gives a more realistic set of track seed parameters rather than the default of smearing the truth track parameters by 5%. This option can be useful for track fit debugging.
=> Circle Fit Truth Seed Option

offline/packages/trackreco/Makefile.am, offline/packages/trackreco/PHActsTrkFitter.cc, offline/packages/trackreco/PHSiliconTpcTrackMatching.cc, offline/packages/trackreco/PHSimpleVertexFinder.cc, offline/packages/trackreco/PHSimpleVertexFinder.h
This PR adds a new primary collision vertex finder. It produces about 17 micron resolution in x and y for 6 pion events, and about 2 micron resolution for 100 pion events. Tested with events containing two vertices, one at (0,0,z1), the second at (1mm,1mm,z2). For 6 pions per vertex, the module is 98% efficient at finding all vertices. The failures occur when the vertices are very close in z. It currently requires that the vertex be within 2 mm of(x,y) = (0,0).
It is not …
=> New vertex finder

offline/packages/trackreco/PHMicromegasTpcTrackMatching.cc, offline/packages/trackreco/PHSiliconTpcTrackMatching.cc, offline/packages/trackreco/PHSimpleKFProp.cc, offline/packages/trackreco/PHTruthSiliconAssociation.cc
std::prev, when used on an empty container, can return an invalid iterator. When accessing the contained object, this can result in a crash
Check on track_map content before calling std::prev(track_map->end())
=> std::prev can produce crashes when used on an empty container.

offline/packages/tpccalib/PHTpcResiduals.cc, offline/packages/tpccalib/PHTpcResiduals.h
PHTpcResiduals was still using vertex position to get the track fit seed, used for calculating residuals. Changed the code to use the first track point instead, as done in PHActsTrkFit. 
=> Do not depend on vertex to define track parameters

offline/packages/tpccalib/PHTpcResiduals.cc, offline/packages/tpccalib/PHTpcResiduals.h, offline/packages/trackreco/PHActsTrkFitter.cc, offline/packages/trackreco/PHActsTrkFitter.h
This PR allows to extrapolate tracks to the TPC using Silicon detector only, and without TPOT. 
Resulting extrapolation accuracy is similar to that achieved with GenFit: 
A PR to the macros repository will follow to enable this feature when TPOT is not enabled. 
Also fixed a couple of minor issues with evaluation histograms, and introduced two residuals vs layer number evaluation histograms. …
=> Enable extrapolation in the TPC without TPOT

offline/database/pdbcal/base/PdbParameterMap.h, offline/database/pdbcal/base/PdbParameterMapContainer.cc
The PdbParameterMap needed a copy ctor for the cloning to work when saving a parametermapcontainer in an xml file (means this wasn't done in 3 years)
=> implement missing clone

offline/packages/trackreco/PHSimpleVertexFinder.cc, offline/packages/trackreco/PHSimpleVertexFinder.h
Add code to propagate the track position covariances to the vertex covariance, and set the SvtxVertex covariance accordingly.
=> Add machinery to determine vertex covariance

offline/packages/trackreco/PHSimpleVertexFinder.cc, offline/packages/trackreco/PHSimpleVertexFinder.h
This PR adds both a track quality cut and a requirement for a match to the MVTX for tracks used in the primary vertex determination. The vertex resolution is significantly improved.
=> Quality cut and MVTX match for PHSimpleVertexFinder  

simulation/g4simulation/g4main/PHG4SimpleEventGenerator.cc, simulation/g4simulation/g4main/PHG4SimpleEventGenerator.h
This PR adds a function to set a power law n value for the simple event generator to throw particles in (transverse) momentum. Nominally not used, unless user explicitly sets it. Gives a more realistic pT distribution from the simple event generator.
=> Add simple power law generation

offline/QA/modules/QAG4SimulationMicromegas.cc, offline/packages/tpc/TpcClusterizer.cc, offline/packages/tpc/TpcClusterizer.h, offline/packages/tpccalib/PHTpcResiduals.cc, offline/packages/tpccalib/PHTpcResiduals.h, offline/packages/trackbase_historic/SvtxTrack_v2.cc, simulation/g4simulation/g4detectors/PHG4CylinderCellGeom.cc, simulation/g4simulation/g4detectors/PHG4CylinderCellGeom.h, simulation/g4simulation/g4tpc/PHG4TpcDigitizer.cc
This PR introduces the possibility to add an arbitrary scale factor to the TPC drift velocity in the TPC clusterizer. 
It also 
- simplifies passing of arguments between static functions in the multi-threaded TPC clusterizer
- saves Track state corresponding to extrapolating in the TPC in SC calibration mode (this is identical to what was used for GenFit and allows to run evaluators on the extrapolated tracks) 
- adds some minor cleanup to MicromegasQA, SvtxTrack_v2 and PHG4CylinderCellGeom
This is what is used to generate the plots discussed at https://indico.bnl.gov/event/13715/contributions/56808/attachments/38056/62709/talk.pdf
[comment]: <> ( What types of changes does your code introduce? Put an `x` in all the boxes …
=> Drift velocity

offline/packages/trackreco/PHActsSiliconSeeding.cc, offline/packages/trackreco/PHActsSiliconSeeding.h
This PR improves the time needed to match INTT clusters by only looking at INTT segments that are azimuthally within the nominal projection region from the MVTX triplet. Currently all INTT segments are iterated for each projection. Improves the speed of the code significantly.
Further improvements can be made, for example by caching the INTT geometry for quick geometric lookup based on the projection position.
=> Improve INTT Matching Time

offline/packages/trackreco/PHActsTrkFitter.cc, offline/packages/trackreco/PHMicromegasTpcTrackMatching.cc, offline/packages/trackreco/PHSiliconTpcTrackMatching.cc, offline/packages/trackreco/PHSiliconTpcTrackMatching.h, offline/packages/trackreco/PHTpcClusterMover.cc, offline/packages/trackreco/PHTpcClusterMover.h, offline/packages/trackreco/PHTpcDeltaZCorrection.cc, offline/packages/trackreco/PHTpcTrackSeedCircleFit.cc
This PR does the following:
1) Updates PHTpcClusterMover to access distortion corrections from Hugo's new class. 
2) Updates PHTpcClusterMover to read clusters associated with TPC tracks from TRKR_CLUSTER, and write the distortion corrected clusters to a new map, CORRECTED_TRKR_CLUSTER.
3) Modifies PHSiliconTpcTrackMatching so that it copies the silicon clusters for matched tracks to CORRECTED_TRKR_CLUSTER (if it exists).
4) Modifies the downstream modules so that they …
=> Update cluster mover

offline/packages/centrality/CentralityInfo.h, simulation/g4simulation/g4centrality/Makefile.am, simulation/g4simulation/g4centrality/PHG4CentralityReco.cc, simulation/g4simulation/g4centrality/PHG4CentralityReco.h
[comment]: Functionality to read in centrality calibration (cuts on centrality observables), determine the centile % of the event, and save the result
[comment]: PHG4CentralityReco will check if its parameter file (configured via macro when defining subsystem reco) contains centrality calibration information. If so, we now determine the centile % values according to the sEPD, MBD, and HIJING b impact parameter, and store the best result on the node tree.
[comment]: PRs in calibrations and macros repositories to follow
=> Read in centrality calibrations from file and determine centiles

offline/packages/intt/InttClusterizer.cc, offline/packages/mvtx/MvtxClusterizer.cc
This PR changes the silicon clustering to local coordinates instead of global coordinates. It removes the need for transforming between global/local, which is unnecessary and wastes time.
It also fixes  a bug in the silicon uncertainty calculations. Previously the silicon uncertainty was calculated in local coordinates. It was then rotated to global coordinate uncertainty via the stave/ladder azimuth. When stored in the `TrkrCluster` object, to get the local uncertainty with e.g. `getRPhiError()`, it was rotated from global to local based on the cluster azimuth and not the stave/ladder azimuth. This PR fixes this by just …
=> Cluster silicon in local coordinates

offline/packages/trackreco/PHMicromegasTpcTrackMatching.cc
It can happen that a cluster is not copied to the CORRECTED_TRKR_CLUSTER map because moving it back on surface failed. This PR yprevents a crash when this happens.
=> check cluster existence before moving forward

offline/framework/frog/FROG.cc, offline/framework/frog/FROG.h
This PR adds enables the XRootD interface of root. Basically all it needs is to add root://dcsphdoor02.rcf.bnl.gov:1095 in front of the pnfs path. It needs XROOTD in the GSEARCHPATH which will be added once this is working. DCACHE and XROOTD will be mutually exclusive, it depends on the order in the GSEARCHPATH which protocol is chosen …
=> add opening files in pnfs via xrootd

offline/packages/trackbase/TrkrCluster.h, offline/packages/trackbase/TrkrClusterContainerv3.cc, offline/packages/trackbase/TrkrClusterv1.cc, offline/packages/trackbase/TrkrClusterv1.h, offline/packages/trackbase/TrkrClusterv2.cc, offline/packages/trackbase/TrkrClusterv2.h, offline/packages/trackbase/TrkrClusterv3.cc, offline/packages/trackbase/TrkrClusterv3.h, offline/packages/trackbase_historic/SvtxTrack_FastSim_v1.cc, offline/packages/trackbase_historic/SvtxTrack_FastSim_v2.cc, offline/packages/trackbase_historic/SvtxTrack_v1.cc, offline/packages/trackbase_historic/SvtxTrack_v2.cc, offline/packages/trackreco/PHMicromegasTpcTrackMatching.cc, offline/packages/trackreco/PHMicromegasTpcTrackMatching.h, offline/packages/trackreco/PHSiliconTpcTrackMatching.cc, offline/packages/trackreco/PHTpcClusterMover.cc
This PR makes sure that clusters other than TPC are always copied, unchanged, from the full cluster map to the tpc-distortion-corrected cluster map. More explicitly
- in TPC-Micromegas matching module, make sure that the Micromegas clusters are looked after in the full map, and copied onty the corrected map when a match is found
- in case of Truth track finding, make sure that all non-TPC clusters are copied over to the corrected cluster map, when running the cluster mover.
In addition:
- To reduce code duplication, make copying clusters easier and more future proof, introduced a "CopyFrom" method to all TrkrCluster variants (similar to what is done for SvtxTrack)
- Fixed  TrkrCluster version created in …
=> Master corrected clusters

simulation/g4simulation/g4tpc/PHG4TpcDistortion.cc, simulation/g4simulation/g4tpc/PHG4TpcDistortion.h, simulation/g4simulation/g4tpc/PHG4TpcElectronDrift.cc
This changes the expected format of the input distortion maps applied in simulated data to match the format supplied in reconstructed data.  The new maps contain only cylindrical coordinate elements.  This reduces their size and makes it easier to compare same-in, same-out which previously did not read the same format.  Additionally, a temporary fix regarding how to handle positions quite close to the CM has been resolved by breaking the distortion maps up into a z>0 and z<0 histogram, which no longer attempts to interpolate between the two separate halves. …
=> updated simulation injection of distortions to cylindrical format etc.

offline/packages/PHField/PHField3DCartesian.cc
This PR prints out the stack trace if PHField3DCartesian::GetFieldValue gets called with not finite coordinates. I see nan's occasionally which seem to come from the tracking. The stacktrace print will tell us where this comes from
=> print out stacktrace for invalid field to see who did this

simulation/g4simulation/g4detectors/PHG4SpacalDetector.h, simulation/g4simulation/g4main/PHG4Detector.h, simulation/g4simulation/g4tpc/PHG4TpcDetector.cc, simulation/g4simulation/g4tpc/PHG4TpcDetector.h, simulation/g4simulation/g4tpc/PHG4TpcDisplayAction.cc
…fiber rods.
Also modified central membrane to be enig surface.
clocking of the two stainless steel rods still needs to be confirmed.
This pull request creates the two stainless steel rods that support the TPC, as well as twelve hollow carbon fiber rods that provide rigidity.  It also corrects the material on the surface of the central membrane to ENIG from the previous copper.
It changes the behavior of the TPC visualization, which previously forced exit(1) if anything other than an explicitly listed set of volume names appears.  Now …
=> TPC Supports and minor central membrane improvement.

offline/packages/tpc/TpcClusterizer.cc, offline/packages/trackbase/ActsSurfaceMaps.h, offline/packages/trackbase_historic/ActsTransformations.cc, offline/packages/trackreco/ActsEvaluator.cc, offline/packages/trackreco/MakeActsGeometry.cc, offline/packages/trackreco/MakeActsGeometry.h, offline/packages/trackreco/PHActsTrkFitter.cc, offline/packages/trackreco/PHTpcClusterMover.cc
This PR fixes issues with getting the TPC subsurface key from global cluster coordinates after distortion corrections. The subsurface is found from coordinates in PHTpcClusterizer and in PHTpcClusterMover, so both are affected by this PR.
1) The cause of the occasional failure to find a TPC surface for distortion corrected clusters is that they sometimes change hitsets. In that case,  the surface vector returned using the hitset key is the wrong one. Discussed this with Joe, and …
=> Fixing cluster mover surface finding

offline/packages/trackreco/PHCASeeding.cc, offline/packages/trackreco/PHTpcTrackSeedCircleFit.cc, offline/packages/trackreco/PHTpcTrackSeedCircleFit.h
Modified PHTpcTrackSeedCircleFit so that it uses distortion corrected clusters, whether in the pre-propagator or final instance. It now checks to see if:
a) It is using the original cluster map.
b) A distortion correction map is available.
If both are true (happens in pre-propagator case when distortion corrections are enabled only) it corrects the clusters for distortions. The circle fit after the cluster mover uses corrected clusters from the node tree, and is not affected. …
=> Use distortion corrected clusters in pre-propagator circle fitter

simulation/g4simulation/g4calo/HcalRawTowerBuilder.cc
HcalRawTowerBuilder was using hard coded pseudorapidity limits for the towers of -1.1 to 1.1.  This is fine for sPHENIX, but does not work for ECCE with the modified inner HCAL covering -1.45 to 1.15.  The towers and clusters were coming out systematically shifted to the wrong pseudorapidity. 
The code was modified to pull in the corresponding limits from the geometry parameters.  …
=> Remove hard-coded eta limits in HcalRawTowerBuilder

simulation/g4simulation/g4eval/DSTEmulator.cc, simulation/g4simulation/g4eval/SvtxClusterEval.cc, simulation/g4simulation/g4eval/SvtxEvaluator.cc, simulation/g4simulation/g4eval/SvtxHitEval.cc, simulation/g4simulation/g4eval/TrackEvaluation.cc
This PR modifies the evaluator classes to use the CORRECTED_TRKR_CLUSTER node to get clusters, if it is found. When distortions are enabled, the corrected clusters are written to that node. If that node is not found, clusters are taken from the TRKR_CLUSTER node as before. 
=> Modify evaluator classes to look for CORRECTED_TRKR_CLUSTER node first.

simulation/g4simulation/g4tpc/Makefile.am, simulation/g4simulation/g4tpc/PHG4TpcPadBaselineShift.cc, simulation/g4simulation/g4tpc/PHG4TpcPadBaselineShift.h, simulation/g4simulation/g4tpc/configure.ac
Base-line shift tool PHG4TpcPadBaselineShift is added
Base-line shift tool PHG4TpcPadBaselineShift is added to simulate charge sharing from the bottom layer of the bottom GEM [TPC general meeting talk]: <https://indico.bnl.gov/event/13864/contributions/57472/attachments/38504/63503/BLShift_eshulga_221121.pdf> 
=> Base-line shift tool PHG4TpcPadBaselineShift is added 

offline/packages/trackbase/TrkrClusterv3.h, simulation/g4simulation/g4eval/TrackEvaluation.cc, simulation/g4simulation/g4eval/TrackEvaluation.h
This PR updates the g4eval/TrackEvaluation module, dedicated to residuals and pulls to: 
- use ActsTransformation to get global from local cluster coordinates
- properly calculate residuals in Micromegas
- properly calculate residuals in TPC with proper handling of layer boundaries, similar to what is done in SvtxEval
- get the right error information along phi
Also adds an error message when trying to access TrkrClusterv3->getPhiError()
[comment]: <> ( In case this is a draft PR, e.g. for running checks using Jenkins, please make the …
=> Trackevaluation update

offline/packages/tpc/TpcClusterizer.cc
Check that cluster was properly inserted in the map before releasing the unique_ptr.
This prevents potential memory leak
Add an error message if not inserted, since duplicated cluster keys should not happen.
=> Possible memory leak fix in TPC clusterizer

offline/packages/trackbase/CMFlashCluster.h, offline/packages/trackbase/CMFlashClusterContainer.h, offline/packages/trackbase/CMFlashClusterContainerLinkDef.h, offline/packages/trackbase/CMFlashClusterContainerv1.cc, offline/packages/trackbase/CMFlashClusterContainerv1.h, offline/packages/trackbase/CMFlashClusterContainerv1LinkDef.h, offline/packages/trackbase/CMFlashClusterLinkDef.h, offline/packages/trackbase/CMFlashClusterv1.cc, offline/packages/trackbase/CMFlashClusterv1.h, offline/packages/trackbase/CMFlashClusterv1LinkDef.h, offline/packages/trackbase/Makefile.am
This PR adds classes to store reconstructed clusters from the central membrane flash on the node tree. Because these reconstructed clusters are not uniquely associated with a layer, the TrkrCluster classes are not suitable to store them. they are stored as 3D space points, with an ADC value. These storage classes will be used throughout the central membrane flash calibration procedure.
They are presently not implemented by any module in the repository.  …
=> Adding classes to store the central membrane flash clusters.

offline/packages/trackreco/MakeActsGeometry.h
Allow to set m_buildMMs externally, so that it can be conditioned to Enable::MICROMEGAS
This is the first set of commits related to updated TPOT geometry. 
This one really does nothing but is needed to then update the steering macros without crashing.
The core of the changes will be pushed once the changes G4_Tracking and G4_Micromegas are also pushed 
[comment]: <> ( In case this is a draft PR, e.g. for running checks using Jenkins, please make the pull request as a draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/ …
=> Allow to set m_buildMMs externally

simulation/g4simulation/g4tpc/PHG4TpcPadPlaneReadout.cc, simulation/g4simulation/g4tpc/PHG4TpcPadPlaneReadout.h
This PR removes unused and obsolete code from PHG4PadPlaneReadout. The code that was removed used the obsolete cell containers for hits, and the (no longer used) rectangular pads for the TPC readout. This is just cleanup before we modify the code to properly handle the gaps in the readout due to the frames between the three radial regions of the TPC readout, and the sector boundaries in phi. …
=> PHG4PadPlaneReadout remove obsolete code

simulation/g4simulation/g4main/Makefile.am, simulation/g4simulation/g4main/PHG4Reco.cc
This PR removes the use of the not working eic physics list which does not compile with G4 v11
=> remove non functional eic physics list

offline/packages/trackreco/PHTruthTrackSeeding.cc, offline/packages/trackreco/PHTruthTrackSeeding.h
Update helical track fit option to use new global cluster position API
This PR makes two changes:
1. The default truth track seeding parameters somehow were changed to not be smeared out at all and taken as the truth values. This is not representative of an actual seeding algorithm, so this was changed back to a 5% smearing.
2. The optional helical fit code had become deprecated with the new cluster global position API. This is now fixed so that there is the option to perform a helical fit on the truth seed and get a more realistic set of initial track parameters. …
=> Truth Seeding Bug Fix

offline/packages/PHGenFitPkg/PHGenFit/Makefile.am, offline/packages/PHGenFitPkg/PHGenFit/Measurement.h, offline/packages/PHGenFitPkg/PHGenFit/PlanarMeasurement.h, offline/packages/PHGenFitPkg/PHGenFit/SpacepointMeasurement.cc, offline/packages/PHGenFitPkg/PHGenFit/SpacepointMeasurement.h, offline/packages/PHGenFitPkg/PHGenFit/Track.cc, offline/packages/PHGenFitPkg/PHGenFit/configure.ac, offline/packages/PHTpcTracker/SpacepointMeasurement2.h
The measurement class did not have a virtual dtor which might be the reason for genfit leaks we see. coverity marked the dtors for the daughter classes as resource leak for that reason. This won't hurt - maybe it will do some good
=> make dtor virtual since classes inherit from it, fix shadowed variables

offline/packages/PHGeometry/PHGeomIOTGeo.cc, offline/packages/PHGeometry/PHGeomUtility.cc
ROOT has been changing default units from cm to mm in Feb 2019 ( https://github.com/root-project/root/pull/3417 ) and back to cm again in sept 2021 ( https://github.com/root-project/root/pull/8955 ). The unit interface also changed, e.g. in https://github.com/root-project/root/pull/7165 . This interferes with the stability for our reconstruction geometry, showing up in recent ACTS code updates by @jdosbo 
This pull request lock the TGeo to use the Fun4All length units to keep our geometry objects stable. 
Meanwhile, it is recommend …
=> force TGeoManager to use the Fun4All unit of cm

offline/packages/trackreco/MakeActsGeometry.cc, offline/packages/trackreco/MakeActsGeometry.h
As part of the Acts update, we found that the fake TPC surfaces overlap the end wheels. This PR fixes the overlaps so that Jenkins can now routinely check this in the CI.
=> Fix fake TPC surface overlaps

offline/packages/trackreco/PHActsTrkFitter.cc
This adds a catch for a rare crash where Acts returns that the fit was successful but the fit result has no fitted track parameters. I would consider that unsuccessful, so when this happens the track is now removed from the track map.
=> Add catch for no track parameters

simulation/g4simulation/g4mvtx/PHG4MvtxDetector.cc
TODO:
we need to move all MVTX detector geometry from TrackingService to
MVTX detector module to avoid this cases. Keep detector geometry definitions
in several places are difficult to maintain and debug.
=> YCM remove overlaps with MVTX geometry defined in TrackingService macro

offline/packages/trackreco/MakeActsGeometry.h
This PR makes the TPC fake surfaces as long as possible in z in the TPC gas volume without introducing overlaps (Jenkins should confirm).
=> Expand TPC surface length

offline/packages/tpccalib/PHTpcCentralMembraneClusterizer.cc, offline/packages/tpccalib/PHTpcCentralMembraneMatcher.cc, offline/packages/tpccalib/PHTpcCentralMembraneMatcher.h, offline/packages/trackbase/CMFlashCluster.h, offline/packages/trackbase/CMFlashClusterv1.h, offline/packages/trackbase/CMFlashDifference.h, offline/packages/trackbase/CMFlashDifferencev1.cc, offline/packages/trackbase/CMFlashDifferencev1.h
Following the discussion at the distortions meeting this morning, this pull request:
1) Adds the number of component clusters in a CM flash cluster to the CM cluster object and the difference object.
2) Stores the positions as (R, phi, Z) in the difference object, instead of (X, Y, Z).
The behavior of the code is unchanged. …
=> Update to central membrane reco and matcher

offline/packages/trackreco/PHActsTrkFitter.cc, offline/packages/trackreco/PHActsTrkFitter.h
This PR tunes the covariance matrix entry for the track seeds to be something that is not too big or too small for Acts. It improves the high pT resolution and local tests indicate it improves the low pT resolution as well for the new Actsv17
=> Expand track seed covariance

offline/packages/trackreco/PHActsTrackProjection.cc, offline/packages/trackreco/PHActsTrackProjection.h
This allows you to configure the radius you want to project tracks too in the calorimeters. Default is the nominal radius provided by the geometry container.
=> Configurable Projection Radii

offline/packages/trackreco/Makefile.am, offline/packages/trackreco/PHActsTrkFitter.cc, offline/packages/trackreco/PHActsTrkFitter.h, offline/packages/trackreco/ResidualOutlierFinder.h
This PR introduces an outlier finder into the Acts track fitter. The outlier finder will reject clusters from the track fit based on a chi2 criteria set in the track fitting module. These criteria still need to be tuned and studied in greater detail in various event topologies. The outlier finder can be turned on/off by a switch, and is by default off for now.
=> Outlier finder

calibrations/tpc/generator/AnnularFieldSim.cc
This alters the behavior of the TPC truth-distortion generator in two ways:
1) It corrects an error in the naming convention of the histograms that previously required an afterburner macro to rename them.  Distortion histograms are now named hIntDistortion%s_%s where the first argument is the component (R, P, Z, corresponding to r-hat, phi, and z-hat) and the second argument is the half of the tpc (posz or negz)
2)  It changes the behavior of the 'P' component.  Previously, this was the phi-hat direction, carrying the same units as …
=> Distortion gen namefix

offline/framework/ffamodules/FlagHandler.cc, offline/framework/ffamodules/FlagHandler.h, offline/framework/ffamodules/HeadReco.cc, offline/framework/ffamodules/HeadReco.h, offline/framework/ffamodules/Makefile.am, offline/framework/ffamodules/SyncReco.h, offline/framework/ffaobjects/FlagSave.h, offline/framework/ffaobjects/FlagSavev1.cc, offline/framework/ffaobjects/FlagSavev1.h, simulation/g4simulation/g4bbc/BbcVertexMap.cc, simulation/g4simulation/g4bbc/BbcVertexMap.h, simulation/g4simulation/g4calo/RawTowerDigitizer.cc, simulation/g4simulation/g4centrality/PHG4CentralityReco.h
This PR cleans up the flag handling (writing to DST and readback). So far flags were only written to DST by the header reconstruction for the initial pass. Any flags set for subsequent processing were not save. This PR creates a module (FlagHandler) which creates the Flags node if it doesn't exist already and then saves the content of the recoConst flags to the output. WHen run on a DST, the FlagHandler will read the flags and copy them into the recoConsts. If a flag already …
=> Proper flag save retrieve

offline/packages/trackreco/MakeActsGeometry.cc, offline/packages/trackreco/MakeActsGeometry.h
For this to work I had to move the call to setPlanarSurfaceDivisions from the constructor to ::Init method
Also changed some static const into static constexpr
Successfully tested with a twice larger number of phi subsurface on single particle simulations.
This has zero impact on the default reconstruction chain.
=> added the possibility to change the number of TPC subsurface along phi

offline/packages/trackreco/PHActsSiliconSeeding.cc, offline/packages/trackreco/PHActsSiliconSeeding.h
This PR removes the duplication of matches in the INTT with MVTX triplets. Local tests show it boosts the track seed purity in 50 kHz by ~15-20% without a loss in efficiency. Slides to show in the next tracking meeting. Curious to see if Jenkins agrees
=> Improve silicon track purity

generators/decayFinder/DecayFinder.cc, offline/packages/KFParticle_sPHENIX/KFParticle_nTuple.h
Jenkins found an issue where I compared two different iterators (one of the vectors used was just the modulus of the other so we couldn't go out of scope). Anyway, fixed this so it actually does what it should rather than do funny things with our memory
From 
```c++
//Which intermediate decay list to we need
auto it = std::find(positive_intermediates_ID.begin(), positive_intermediates_ID.end(), abs(particle->pdg_id()));
int index = it - m_intermediates_ID.begin();
```
to
```c++
//Which intermediate decay list to we need
auto it = std::find(positive_intermediates_ID.begin(), positive_intermediates_ID.end(), …
```
=> Fixed issue in decay finder where 2 iterators were compared

offline/packages/trackreco/PHActsTrkFitter.cc
Swaps the mass lookup to Root version from Geant so that the tracking macro can be run independent of Geant.
=> Swap mass to root instead of geant

offline/packages/trackreco/Makefile.am, offline/packages/trackreco/PHSiliconSeedMerger.cc, offline/packages/trackreco/PHSiliconSeedMerger.h
This PR introduces a module that merges silicon seeds based on common MVTX hits. Something like ~10% of single tracks result in duplicate silicon seeds because the track leaves 4 MVTX hits, and since the Acts seeder finds triplets it finds two seeds for a single track. This PR introduces a module that finds seeds that have at least 2 common MVTX measurements and merges them, which results in a ~10% boost in purity at no efficiency expense.
After a few more tests I will introduce a macros PR to implement this in the workflow.
=> Silicon seed merger

offline/packages/tpccalib/TpcSpaceChargeReconstructionHelper.cc
This PR adapts the TPC distortion extrapolation procedure to new TPOT geometry and makes it more robust against distortion histogram binning. 
The procedure does not yet use an external distortion map (from e.g. Central Membrane clusters) to scale the distortions copy from one sector to the other. This will be the subject of a separate PR.
=> Distortion extrapolation

offline/packages/trackreco/PHSiliconSeedMerger.cc
There were cases where a single seed was iteratively merged with many seeds depending on the cluster key content. This PR fixes that such that a seed can have at most 4 MVTX measurements.
=> Merge only two seeds

offline/packages/tpccalib/PHTpcResiduals.cc, offline/packages/tpccalib/PHTpcResiduals.h, offline/packages/trackbase_historic/ActsTransformations.cc, offline/packages/trackbase_historic/ActsTransformations.h, offline/packages/trackreco/PHActsTrkFitter.cc, offline/packages/trackreco/PHActsVertexPropagator.cc
This PR cleansup ActsTransformation::Rotate... methods to not require Acts geometry context any more, which was not used anyway. This simplifies the code.
@jdosbo: is this ok ? 
=> removed GeoContext from cov matrix transformations. (it is not used)

offline/packages/trackbase_historic/Makefile.am, offline/packages/trackbase_historic/PHG4ParticleSvtxMap.cc, offline/packages/trackbase_historic/PHG4ParticleSvtxMap.h, offline/packages/trackbase_historic/PHG4ParticleSvtxMapLinkDef.h, offline/packages/trackbase_historic/PHG4ParticleSvtxMap_v1.cc, offline/packages/trackbase_historic/PHG4ParticleSvtxMap_v1.h, offline/packages/trackbase_historic/PHG4ParticleSvtxMap_v1LinkDef.h, offline/packages/trackbase_historic/SvtxPHG4ParticleMap.cc, offline/packages/trackbase_historic/SvtxPHG4ParticleMap.h, offline/packages/trackbase_historic/SvtxPHG4ParticleMapLinkDef.h, offline/packages/trackbase_historic/SvtxPHG4ParticleMap_v1.cc, offline/packages/trackbase_historic/SvtxPHG4ParticleMap_v1.h, offline/packages/trackbase_historic/SvtxPHG4ParticleMap_v1LinkDef.h, simulation/g4simulation/g4eval/Makefile.am, simulation/g4simulation/g4eval/SvtxTruthRecoTableEval.cc, simulation/g4simulation/g4eval/SvtxTruthRecoTableEval.h
This PR adds two new objects that correlate truth to reco and reco to truth tracks. They are intended to be a fix for the current tracking truth-reco limitation of carrying around too much information and thus being too large. The maps are of form:
```
/// Map of form std::map<gtrack id, std::map<weight, std::set<reco track id>>>
std::map<int, std::map<float, std::set<unsigned int>>> TruthToRecoTrackMap
/// Map of form std::map<reco track id, std::map<weight, std::set<gtrack id>>>
std::map<unsigned int, std::map<float, std::set<int>>> RecoToTruthTrackMap
```
The tables are filled with a new module that can be added to the G4_Tracking macro.
[comment]: <> ( What does this PR do? …
=> New Truth-Reco Track Tables

simulation/g4simulation/g4gdml/PHG4GDMLWriteStructure.cc
https://github.com/sPHENIX-Collaboration/coresoftware/pull/1423 was intended to make `g4gdml` lib to compile in G4.10.6 and G4.11.0 However, it do not compile in G4.10.7 yet, which is enabled by this pull request
Downgrade G4.11 to G4.10.7 due to numerical reproducibility issue in G4.11.0.1
=> Adjust `G4VERSION_NUMBER` cuts to compile in G4.10.7 too

simulation/g4simulation/g4eval/SvtxTrackEval.cc, simulation/g4simulation/g4eval/SvtxTrackEval.h, simulation/g4simulation/g4eval/SvtxTruthRecoTableEval.h
This PR adds functionality for the `SvtxTrackEval` class to lookup the truth-reco track matching via the new objects on the node tree rather than the cached maps in the evaluator. This should allow truth-reco track matching readback with the output DSTs.
Also tested without the new table evaluator (e.g. only the `SvtxEvaluator`) and it produces identical results when either only the cached maps are used or only the objects on the node tree are used. …
=> Node Tree Truth-Reco Match Lookup

offline/packages/intt/InttClusterizer.cc, offline/packages/intt/InttDefs.cc, offline/packages/intt/InttDefs.h, offline/packages/micromegas/MicromegasClusterizer.cc, offline/packages/micromegas/MicromegasDefs.cc, offline/packages/micromegas/MicromegasDefs.h, offline/packages/mvtx/MvtxClusterizer.cc, offline/packages/mvtx/MvtxDefs.cc, offline/packages/mvtx/MvtxDefs.h, offline/packages/tpc/TpcClusterizer.cc, offline/packages/tpc/TpcDefs.cc, offline/packages/tpc/TpcDefs.h, offline/packages/tpc/TpcSimpleClusterizer.cc, offline/packages/trackbase/TrkrDefs.cc, offline/packages/trackbase/TrkrDefs.h, offline/packages/trackreco/PHTruthClustering.cc, simulation/g4simulation/g4eval/SvtxTruthEval.cc
Moved genClusKey(const TrkrDefs::hitsetkey hskey, const uint32_t clus…id) from detector specific implementation to TrkrDefs because
- all detectors had the exact same implementation
- TrkrDefs::getClusIndex assumes a given implementation, so the detectors did not have the freedom to change this anyway, without breaking things
- having a unique way to go from hitsetkey+clusId to cluskey is necessary for the coming ClusterContainer reorganization …
=> moved gencluskey from detector specific implementation to TrkrDefs

offline/packages/trackreco/MakeActsGeometry.cc, offline/packages/trackreco/MakeActsGeometry.h
This PR adds a flag for loading the magnetic field map into Acts. It is set to true by default.
This will allow us to run the clustering in a separate job without loading in the magnetic field, which should conserve memory consumption since the clustering only requires the detector geometry.
=> Add Flag for Acts Magnetic Field

offline/packages/tpc/TpcClusterizer.cc, offline/packages/tpc/TpcSimpleClusterizer.cc, offline/packages/tpc/TpcSimpleClusterizer.h, offline/packages/trackbase/TrkrClusterContainer.cc, offline/packages/trackbase/TrkrClusterContainer.h, offline/packages/trackbase/TrkrClusterContainerv1.cc, offline/packages/trackbase/TrkrClusterContainerv1.h, offline/packages/trackbase/TrkrClusterContainerv2.cc, offline/packages/trackbase/TrkrClusterContainerv2.h, offline/packages/trackbase/TrkrClusterContainerv3.cc, offline/packages/trackbase/TrkrClusterContainerv3.h, offline/packages/trackreco/PHMicromegasTpcTrackMatching.cc, offline/packages/trackreco/PHSiliconTpcTrackMatching.cc, offline/packages/trackreco/PHTpcClusterMover.cc, offline/packages/trackreco/PHTruthClustering.cc, offline/packages/trackreco/PHTruthSiliconAssociation.cc
This PR simplifies the TrkrClusterContainer public interface in preparation for the new clusterContainer to minimize the number of function calls that make explicit assumptions to the underlying structure.
In particular: 
- ::findOrAddCluster has been removed 
- ::getClusterMap has been removed
- ::addCluster now returns void rather than an interator to the underlying map.
In addition ::getClusterRange( hitsetid ) has been made non const. 
The code calling these functions has been adapted accordingly, in principle with no loss of functionality nor performance
TpcSimpleClusterizer has been updated to incorporate recent changes to TpcClusterizer.
[comment]: <> ( What types of changes does your code introduce? Put an `x` in all …
=> Cluster container

offline/packages/trackreco/PHActsVertexPropagator.cc, offline/packages/trackreco/PHActsVertexPropagator.h
The vertex chisq/ndf was previously just set to 0 because we didn't explicitly calculate it. This fixes that and assigns the vertex a proper chisq.
=> Add vertex chisq/ndf calculation

offline/packages/trackbase_historic/SvtxTrack_v3.cc, offline/packages/trackreco/PHTruthSiliconAssociation.cc, offline/packages/trackreco/PHTruthSiliconAssociation.h, offline/packages/trackreco/PHTruthTrackSeeding.cc, offline/packages/trackreco/PHTruthTrackSeeding.h
This PR fixes passing around the crossing number from INTT clusters to the SvtxTracks when running truth track seeding. 
It also simplifies how multiple/no crossings are found for a give (truth) track, by using std::set instead of std::vector
=> Track crossing

offline/QA/modules/QAG4SimulationTracking.cc, offline/packages/trackbase_historic/PHG4ParticleSvtxMap.cc, offline/packages/trackbase_historic/PHG4ParticleSvtxMap.h, offline/packages/trackbase_historic/PHG4ParticleSvtxMap_v1.cc, offline/packages/trackbase_historic/PHG4ParticleSvtxMap_v1.h, offline/packages/trackbase_historic/SvtxPHG4ParticleMap.cc, offline/packages/trackbase_historic/SvtxPHG4ParticleMap.h, offline/packages/trackbase_historic/SvtxPHG4ParticleMap_v1.cc, offline/packages/trackbase_historic/SvtxPHG4ParticleMap_v1.h, simulation/g4simulation/g4detectors/PHG4CylinderGeom_Spacalv3LinkDef.h, simulation/g4simulation/g4eval/PHG4DstCompressReco.cc, simulation/g4simulation/g4eval/PHG4DstCompressReco.h, simulation/g4simulation/g4eval/SvtxEvaluator.cc, simulation/g4simulation/g4eval/SvtxTrackEval.cc, simulation/g4simulation/g4eval/SvtxTrackEval.h, simulation/g4simulation/g4eval/SvtxTruthRecoTableEval.cc, simulation/g4simulation/g4eval/SvtxTruthRecoTableEval.h
This PR implements the truth compress for generic simulation physics analysis based on tracking and calorimetry, following these previous work: 
* For calorimeters: the shower truth compression was built in long time ago by Mike McCumber with `PHG4DstCompressReco`
* Tracker compression was introduced at https://github.com/sPHENIX-Collaboration/coresoftware/pull/1465 and evaluator by passing at https://github.com/sPHENIX-Collaboration/coresoftware/pull/1470 
Then this PR introduce changes to
* `SvtxTruthRecoTableEval` to zero suppress …
=> Truth compress for simulation physics analysis based on tracking and calorimetry

offline/database/dbtools/xclient.cc
With "-Wall" option clang issues a warning if a range loop has an implicit cast that creates a copy
For details see https://github.com/BNLNPPS/xpload/issues/32
[skip ci]
=> Prevent clang warning about a copy in range loop

simulation/g4simulation/g4centrality/PHG4CentralityReco.cc, simulation/g4simulation/g4centrality/PHG4CentralityReco.h
…ty flag
This is committing a bug fix to the PHG4CentralityReco.cc to correct for code functionality being unintentionally gated behind a verbosity requirement.
This moves a "}" from the incorrect location to the correct location around the cout statements in the code. Restoring the ability of the software to determine centrality values when verbosity is not set to 1+. …
=> corrected a bug where centrality interval readin was behind verbosity

offline/packages/tpc/TpcLoadDistortionCorrection.cc
Add a check that a correction is enabled before trying to load the correction file.
=> Add check to see if correction is in use before loading into node.

offline/packages/tpc/TpcClusterizer.cc
This PR wraps the tpc cluster surface warning into a verbosity statement.
=> wrap in verb statement

offline/packages/tpc/TpcClusterizer.cc, offline/packages/tpc/TpcClusterizer.h
Adds option to cut out the forward r-z wedge as in AuAu raw data.
Default is to not cut the wedge. 
Activate using 
TpcClusterizer->set_do_wedge_emulation(true);
=> Add option to cut out forward r-z wedge as in raw data

offline/packages/trackreco/PHTruthTrackSeeding.cc
…ber. For z, 5% of 10 cm is 5 mm!
Randomizing the track position by 5% produced up to 5 mm variation in track z, causing loss of tracking efficiency. Changed the position randomization to be an added fraction of +/- 20 microns. 
=> Truth track seeding position randomization fix

simulation/g4simulation/g4eval/SvtxTrackEval.cc, simulation/g4simulation/g4eval/SvtxTrackEval.h
Check for _recoTruthMap and TruthRecoMap every time they are used to prevent crash when not found
This can happen when running the QA (which calls the evaluator internally) without first running Tracking_Eval(), where SvtxTruthRecoTableEval is registered. 
also moved member initialization to header
=> Fix crash in QA

offline/packages/trackbase_historic/TrackSeed_FastSim_v1.cc, offline/packages/trackbase_historic/TrackSeed_FastSim_v1.h, offline/packages/trackbase_historic/TrackSeed_v1.h, offline/packages/trackreco/PHTruthTrackSeeding.cc, offline/packages/trackreco/PHTruthTrackSeeding.h
This PR fixes the truth seeding after the major track seeding changes from PR 1505.
=> Truth seeding fix

offline/QA/modules/QAG4SimulationTracking.cc, offline/QA/modules/QAG4SimulationTracking.h, offline/QA/modules/QAG4SimulationVertex.cc, offline/QA/modules/QAG4SimulationVertex.h, offline/packages/trackbase_historic/Makefile.am, offline/packages/trackbase_historic/SvtxTrack.h, offline/packages/trackbase_historic/SvtxTrack_v4.cc, offline/packages/trackbase_historic/SvtxTrack_v4.h, offline/packages/trackbase_historic/SvtxTrack_v4LinkDef.h, offline/packages/trackreco/PHActsTrackProjection.cc, offline/packages/trackreco/PHActsTrkFitter.cc, offline/packages/trackreco/PHActsTrkFitter.h, offline/packages/trackreco/PHActsVertexPropagator.cc, offline/packages/trackreco/PHActsVertexPropagator.h, offline/packages/trackreco/PHSimpleVertexFinder.cc, simulation/g4simulation/g4eval/SvtxEvaluator.cc, simulation/g4simulation/g4eval/SvtxEvaluator.h, simulation/g4simulation/g4eval/SvtxTrackEval.cc, simulation/g4simulation/g4eval/SvtxTrackEval.h, simulation/g4simulation/g4eval/SvtxTruthRecoTableEval.cc
This PR introduces a new `SvtxTrack_v4` object that is significantly more lightweight than the current version. It removes extra floats and removes the calo projection information in favor of saving the projections at state objects.  Additionally, the cluster key set is removed and instead the track carries pointers to two `TrackSeed` objects corresponding to the relevant silicon and TPC+TPOT seeds that form the track. 
This changes the outward analyzer facing API potentially significantly by:
1. Removing the floats which store the DCA. Calculation of the DCA is now up to the analyzer rather than just storing a "default" DCA
2. Removing the calo projection cluster info, e.g. the delta-phi, delta-eta, etc. Instead, a `SvtxTrackState` is added to the state list which corresponds to the …
=> New Lightweight SvtxTrack

offline/packages/trackreco/PHActsTrackProjection.cc
This fixes the path length determination from the Acts propagation which was off by a factor of mm->cm
=> Fix path length determination

offline/packages/trackbase_historic/SvtxTrack.h
This PR shuffles some functions around and adds some comments to hopefully make it more clear what is deprecated in the SvtxTrack base class since the introduction of the lighter weight track object.
=> Add deprecation comments to SvtxTrack 

offline/packages/tpccalib/PHTpcResiduals.cc, offline/packages/trackreco/PHGenFitTrkFitter.cc, simulation/g4simulation/g4eval/TrackEvaluation.cc
This PR adapts a few classes to the new track interface and how we loop over clusters.
Adapted classes are:
g4eval/TrackEvaluation
tpccalib/PHTpcResiduals
trackreco/PHGenfitTrkFitter
The later needs more modifications: right now it expects fully built tracks (as opposed to seeds) to perform the fit. 
I'll copy what's in PHActsTrkFitter in a future pull request. 
As long as we have not resolved the differences between ACTS and GENFIT concerning distortion reconstructions (the latter having significantly better differences than the former), we must keep both fits alive. 
[comment]: <> ( What does this PR do? Linking to …
=> Adapt to new track

offline/packages/trackreco/PHActsTrkFitter.cc, offline/packages/trackreco/PHActsTrkFitter.h, offline/packages/trackreco/PHSiliconTpcTrackMatching.cc, offline/packages/trackreco/PHSiliconTpcTrackMatching.h, offline/packages/trackreco/PHSimpleVertexFinder.cc, offline/packages/trackreco/PHSimpleVertexFinder.h, offline/packages/trackreco/PHTrackCleaner.cc, offline/packages/trackreco/PHTrackCleaner.h, offline/packages/trackreco/PHTrackSelector.cc, offline/packages/trackreco/PHTrackSelector.h, offline/packages/trackreco/PHTruthSiliconAssociation.cc, offline/packages/trackreco/PHTruthSiliconAssociation.h, offline/packages/trackreco/PHTruthTrackSeeding.cc, offline/packages/trackreco/PHTruthTrackSeeding.h
This PR modifies the truth track seeding, truth silicon matching, and normal track matching chains to make full use of, and fully conform to, the new track seeding scheme. The changes are:
1) PHTruthTrackSeeding makes separate seeds for the silicon and tpc clusters instead of putting them all in the tpc seed.
2) PHTruthSiliconAssociation makes a new seed for the silicon clusters, instead of adding them to the tpc seed.
3) PHSiliconTpcTrackMatching no longer duplicates …
=> Cleanup matcher

simulation/g4simulation/g4eval/SvtxEvaluator.cc
The number of hits in the ntp_track tuple didn't get updated for the new tracking scheme. This PR fixes the bug.
=> Fix nhits in ntp_track

offline/QA/modules/QAG4SimulationTracking.cc, offline/packages/trackbase_historic/SvtxTrack_v4.cc, offline/packages/trackreco/PHActsTrkFitter.cc, offline/packages/trackreco/PHActsTrkFitter.h, offline/packages/trackreco/PHGenFitTrkFitter.cc, offline/packages/trackreco/PHGenFitTrkFitter.h
This PR finishes moving genfit to the new Trackseed and track objects.
Like in PHActsTrkFitter, SvtxTrack objects are created on the fly, from Track seeds, before being fit. 
Also added some more checks in the QATracking module to prevent crashes when running genfit, and a few simplifications in the ActsTrkFitter code. 
=> Fix genfit

offline/packages/tpc/TpcClusterMover.cc, offline/packages/tpc/TpcClusterMover.h, offline/packages/trackbase/Makefile.am, offline/packages/trackbase/TrackFitUtils.cc, offline/packages/trackbase/TrackFitUtils.h, offline/packages/trackbase_historic/TrackSeed_FastSim_v1.cc, offline/packages/trackbase_historic/TrackSeed_v1.cc, offline/packages/trackbase_historic/TrackSeed_v1.h, offline/packages/trackreco/ALICEKF.cc, offline/packages/trackreco/ALICEKF.h, offline/packages/trackreco/PHCASeeding.cc, offline/packages/trackreco/PHMicromegasTpcTrackMatching.cc, offline/packages/trackreco/PHSimpleKFProp.cc, offline/packages/trackreco/PHTpcClusterMover.cc, offline/packages/trackreco/PHTpcClusterMover.h
This PR moves all the implementations of circle_fit_by_taubin, and (r,z) line_fit to a single place: trackbase/TrackFitUtils, to avoid code duplication.
Also moved is the "circle_circle_intersection" code, that was used in both the TPC Micromegas matcher and the Cluster mover code. 
The reason the utility code is in trackbase, rather than e.g. trackreco is that it can then be used internally inside trackbase_historic/TrackSeed_v1.cc
This should have no impact on the performances.  …
=> Circle fit

offline/packages/trackreco/PHSiliconTpcTrackMatching.cc, offline/packages/trackreco/PHTruthTrackSeeding.cc
This PR modifies the truth track seeding module so that for truth TPC seeding the track z position is set by running the track seed lineFit method, instead of assigning it from the truth track vertex. This is necessary for tracks that come from bunch crossings other than the triggered one. The change enables a new check in the silicon-tpc track matcher that the observed z-mismatch between the silicon and tpc track seeds is consistent with the bunch crossing obtained from …
=> Modify truth track seeding for TPC to set track z to linefit value

offline/framework/frog/CreateFileList.pl
This PR fixes the selection of hijing MB events without pileup (-nopileup option)
[skip ci]
=> fix -nopileup selection for hijing MB

offline/packages/intt/InttClusterizer.cc, offline/packages/intt/InttClusterizer.h, offline/packages/micromegas/MicromegasClusterizer.cc, offline/packages/micromegas/MicromegasClusterizer.h, offline/packages/mvtx/MvtxClusterizer.cc, offline/packages/mvtx/MvtxClusterizer.h, simulation/g4simulation/g4eval/SvtxEvaluator.cc, simulation/g4simulation/g4eval/SvtxEvaluator.h
adds option to write TrkrClusterv4 to clusterizers, controlled by setter for cluster version number.
also contains update to SvtxEvaluator to process v4 clusters.
=> add option to create v4 clusters to clusterizers and matching evaluator

offline/packages/trackreco/PHActsTrkFitter.cc, offline/packages/trackreco/PHMicromegasTpcTrackMatching.cc, offline/packages/trackreco/PHMicromegasTpcTrackMatching.h, offline/packages/trackreco/PHSiliconTpcTrackMatching.cc
…sing from silicon stub.
Micromegas-TPC matching was not properly converted to the new seed track scheme, so MM's clusters were not being attached to TPC track seeds. This PR fixes that.
=> Micromegas matching bug fix

offline/QA/modules/QAG4SimulationMicromegas.cc, offline/QA/modules/QAG4SimulationMicromegas.h, offline/packages/micromegas/CylinderGeomMicromegas.cc, offline/packages/micromegas/CylinderGeomMicromegas.h, offline/packages/micromegas/MicromegasClusterizer.cc, offline/packages/micromegas/MicromegasClusterizer.h, offline/packages/trackreco/MakeActsGeometry.cc, offline/packages/trackreco/PHGenFitTrkFitter.cc, offline/packages/trackreco/PHGenFitTrkFitter.h, offline/packages/trackreco/PHMicromegasTpcTrackMatching.cc, offline/packages/trackreco/PHMicromegasTpcTrackMatching.h, simulation/g4simulation/g4eval/TrackEvaluation.cc, simulation/g4simulation/g4eval/TrackEvaluation.h, simulation/g4simulation/g4micromegas/PHG4MicromegasDetector.h, simulation/g4simulation/g4micromegas/PHG4MicromegasHitReco.cc, simulation/g4simulation/g4micromegas/PHG4MicromegasHitReco.h
This PR modifies CylinderGeomMicromegas to use acts sufaces for all local_to_master and master_to_global transformation instead of locally stored geometry description. Ultimately this would allow to seamlessly include alignment parameters without the need to maintain to instances of the geometry in parallel. 
There is one remaining place where the internal geometry is used and not acts surfaces. It is in "find_tiles_cylindrical" 
The reason is that this is the method used to match a given Acts surface to a TPOT tile number (in MakeActsGeometry). 
It is also a quick (and coarse) way to match MM clusters to extrapolated TPC seeds. 
[comment]: <> ( What types of changes does your code introduce? Put an `x` in all the boxes that …
=> CylinderGeomMicromegas

offline/packages/tpc/TpcClusterizer.cc, offline/packages/tpc/TpcClusterizer.h, offline/packages/trackreco/PHTpcDeltaZCorrection.cc, simulation/g4simulation/g4eval/SvtxEvaluator.cc
This PR does three things:
1) It fixes the evaluator bug that caused the cluster ntuple to not be filled when the scan-for-embedded flag was set.
2) Fixes a bug in the calculation of the flight time correction in PHTpcDeltaZCorrection.
3) Changes the SAMPA shaping offset correction in TpcClusterizer to be a time in ns, and tunes it so that z values match in the TPC north and south at z = 0. …
=> Scan embed clusters bug

offline/packages/intt/CylinderGeomIntt.cc, offline/packages/intt/CylinderGeomIntt.h, offline/packages/mvtx/CylinderGeom_Mvtx.cc, offline/packages/mvtx/CylinderGeom_Mvtx.h, offline/packages/trackbase/ActsSurfaceMaps.cc, offline/packages/trackreco/MakeActsGeometry.cc, offline/packages/trackreco/Makefile.am, offline/packages/trackreco/PHActsSiliconSeeding.cc, offline/packages/trackreco/PHActsTrkFitter.cc, offline/packages/trackreco/PHGenFitTrkFitter.cc, offline/packages/trackreco/PHTruthClustering.cc, offline/packages/trackreco/PHTruthClustering.h, simulation/g4simulation/g4eval/SvtxTruthEval.cc, simulation/g4simulation/g4eval/SvtxTruthEval.h, simulation/g4simulation/g4mvtx/PHG4MvtxHitReco.cc
This PR moves the silicon cylinder geometry classes to call Acts for transformations instead of use their own defined transforms. This will be necessary for alignment as the Acts surfaces will contain the alignment info.
=> Silicon geometries to Acts

offline/packages/micromegas/CylinderGeomMicromegas.cc, offline/packages/trackbase/ActsGeometry.cc, offline/packages/trackbase/ActsGeometry.h, simulation/g4simulation/g4eval/DSTEmulator.cc
This PR fixes the track timing issue I inadvertently introduced with `const ref` accessors. This also pulled up a few other compilation issues, which required fixing (e.g. in the micromegas cylinders Eigen could apparently not deduce what `auto` was referring to at compile time and thought that the vector might go uninitialized, and declaring it explicitly as `Acts::Vector3` seems to make gcc happy).
Thanks to Jin and Jenkins for finding the issue, and to Hugo for pointing out that I made some mistake on the first attempt at using const ref accessors
[comment]: <> ( In case this is a draft PR, e.g. for running checks …
=> Track Timing Fix

offline/framework/frog/CreateFileList.pl
CreateFileList.pl did not produce a list for G4Hits for nopileup in pp (and mixed runnumbers in hijing for G4Hits). Added safety belts for invalid flag combinations (--embed and --nopileup, --embed only for pp)
[skip ci]
=> Fix createfilelist

offline/framework/fun4all/Fun4AllMonitoring.cc, simulation/g4simulation/g4detectors/PHG4ZDCSteppingAction.cc
This PR put the suppression of a known false positive for cppcheck in simulation/g4simulation/g4detectors/PHG4ZDCSteppingAction.cc back. Running jenkins to establish a new baseline for cppcheck warnings
=> put cppcheck suppression for false positive back

offline/packages/tpc/TpcClusterizer.cc, offline/packages/trackbase/ActsGeometry.cc, offline/packages/trackreco/PHActsTrkFitter.cc
Reverts sPHENIX-Collaboration/coresoftware#1572
https://nbviewer.org/github/sPHENIX-Collaboration/QA-gallery/blob/jenkins-sPHENIX-test-tracking-low-occupancy-qa-2271-test-tracking_Event1000_Sum16/QA-vertexing.ipynb
This PR somehow screwed up the number of tracks associated to vertices as in the QA. Reverting it for now and will re-check what happened.
=> Revert "TPC cluster transform simplification"

simulation/g4simulation/g4main/Fun4AllDstPileupInputManager.cc, simulation/g4simulation/g4main/Fun4AllDstPileupInputManager.h, simulation/g4simulation/g4main/Fun4AllDstPileupMerger.cc, simulation/g4simulation/g4main/Fun4AllDstPileupMerger.h
This PR adds detector specific active bunch crossings to the pileup generator. (active for one bc --> 1). This doesn't adjust the truth info, particles with hits which are rejected by the timing cut are still in the truth info
=> add detector specific bunchcrossings pileup window

simulation/g4simulation/g4main/PHG4Reco.cc
In this change, I added a line G4HadronicParameters::Instance()->SetEnableBCParticles(false) in the PHG4Reco.cc file to allow GEANT to use external decayers for heavy flavor particles by disabling the Geant4 existing decay tables. We have tested the PYTHIA 6 decayer indeed runs for heavy flavor particles with the update. 
=> Implement the fix suggested by GEANT 4 developers to allow external decayers for heavy flavor particles. 

simulation/g4simulation/g4mvtx/PHG4MvtxHitReco.cc, simulation/g4simulation/g4mvtx/PHG4MvtxHitReco.h
This PR try to implement a more realistic MVTX detector response in the hit reconstruction simulation.
A set of new features is reported below:
* Use a common readout/digitalization time window for all layers
* Add configurable strobe setting to the parameter list
* Move all MVTX configuration to PHParameter Interfaces. Remove public set member function, modification through PHParameterInterface only.
* Keep set_timing_window member for backward compatibility in the G4_MVTX macro but It DOES NOT change timing parameter values. It will …
=> [WIP] MVTX hit timing and duplication

offline/packages/eventplane/EpFinderReco.cc
cuts added to reject hits arriving from out-of-time pileup collisions
=> Add timing cut on EPD and BBC hits

calibrations/calorimeter/calo_tower_slope/LiteCaloEval.cc, offline/packages/CaloReco/RawClusterBuilderTopo.cc, offline/packages/jetbackground/DetermineTowerBackground.cc, offline/packages/particleflow/Makefile.am, offline/packages/particleflow/ParticleFlowReco.cc, offline/packages/trackbase/TrkrHitTruthClustersv1.cc, offline/packages/trackreco/MakeActsGeometry.cc
Calculate cluster eta with global vertex instead of assuming at z=0
This PR:
1. Fixes a stupid bug I introduced that rejected all tracks outside the sPHENIX acceptance
2. Calculates the cluster eta values based on the global vertex rather than assuming a z vertex of 0, if the global vertex is available.
=> Update particle flow

simulation/g4simulation/g4detectors/PHG4HcalCellReco.cc
Store the new raw light yield in cell only if it was set in the PHG4Hits, so old DSTs don't waste space by just filling cells with NAN's
=> save raw light yield in cell only if it exists in the PHG4Hit

offline/framework/ffamodules/XploadInterface.cc, offline/framework/ffamodules/XploadInterface.h
If the flags related to xpload were not set the lookup fails badly. This PR sets the flags (timestamp, config and global tag) to a working default if they are not set.
=> set XPload flags to some default if not set to prevent crashes

simulation/g4simulation/g4detectors/PHG4InnerHcalSteppingAction.cc, simulation/g4simulation/g4detectors/PHG4OuterHcalSteppingAction.cc, simulation/g4simulation/g4ihcal/PHG4IHCalSteppingAction.cc, simulation/g4simulation/g4ohcal/PHG4OHCalSteppingAction.cc
This PR fixes an issue found by coverity. The check if the histogram with the mephi maps is not a null pointer came after dereferencing the pointer (the code would have crashed here). Now the order is correct - the code will quit gracefully if the histos cannot be loaded
=> move pointer check ahead of dereferencing it

offline/packages/trackreco/PHActsTrkFitter.cc
added validity check on momentum and position to prevent acts fit crash
It can happen when running truth track seeding that either the initial track seed momentum or position contains nan values, which results in the acts fit crashing. 
This PR prevents that by explicitely checking all values and skipping the track when an invalid number is found.
One should still determine the root cause of these "nan" values from the truth track seeding. …
=> Fix Crash in ACTS fit due to invalid starting parameters

offline/packages/KFParticle_sPHENIX/KFParticle_sPHENIX.h
The reorganization of the includes broke the loading of KFParticle into root. I tracked this down to a single include which needs to be includes out of order. I didn't track down the reason for this - doesn't bode well for the future. But KFParticle_sPHENIX.h is stable against running clang-format and I put a fat comment there …
=> change include order to prevent root crash

simulation/g4simulation/g4calo/HcalRawTowerBuilder.cc, simulation/g4simulation/g4calo/HcalRawTowerBuilder.h, simulation/g4simulation/g4calo/RawTowerDigitizer.cc, simulation/g4simulation/g4jets/ClusterJetInput.cc, simulation/g4simulation/g4jets/ClusterJetInput.h, simulation/g4simulation/g4jets/FastJetAlgo.cc, simulation/g4simulation/g4jets/FastJetAlgo.h, simulation/g4simulation/g4jets/Jet.h, simulation/g4simulation/g4jets/JetAlgo.h, simulation/g4simulation/g4jets/JetHepMCLoader.cc, simulation/g4simulation/g4jets/JetHepMCLoader.h, simulation/g4simulation/g4jets/JetInput.h, simulation/g4simulation/g4jets/JetMap.cc, simulation/g4simulation/g4jets/JetMap.h, simulation/g4simulation/g4jets/JetMapv1.cc, simulation/g4simulation/g4jets/JetMapv1.h, simulation/g4simulation/g4jets/JetReco.cc, simulation/g4simulation/g4jets/JetReco.h, simulation/g4simulation/g4jets/Jetv1.cc, simulation/g4simulation/g4jets/Jetv1.h, simulation/g4simulation/g4jets/TowerJetInput.cc, simulation/g4simulation/g4jets/TrackJetInput.cc, simulation/g4simulation/g4jets/TrackJetInput.h, simulation/g4simulation/g4jets/TruthJetInput.cc, simulation/g4simulation/g4jets/TruthJetInput.h, simulation/g4simulation/g4tpc/PHG4TpcDetector.cc, simulation/g4simulation/g4tpc/PHG4TpcEndCapDetector.cc
The hcals produced NANs as phi coordinates under certain conditions. This lead to a hard to debug problem in the jet finding with fastjet (which did not take well to px/py=NAN). Now the input values are checked via isfinite() before handed down to fastjet. The hcal tower reconstruction also makes sure the phistart value is a valid number (which was the root cause of this crash)
[comment]: <> ( In case this is a draft PR, e.g. for running checks using Jenkins, please make the …
=> Protect jets

simulation/g4simulation/g4jets/Jet.h, simulation/g4simulation/g4jets/JetMap.h, simulation/g4simulation/g4jets/JetMapv1.cc, simulation/g4simulation/g4jets/JetMapv1.h
This pull request is in respond to todays Jet Substructure meeting, as a version 2. Here are the proposed slides for next weeks meeting: https://d.pr/f/k0OOcK . I wish to make this pull request as a reference point for that meeting. (In something of a chicken-and-egg situation)
=> Add code to generate a vector to access the JetMap data.

offline/QA/modules/QAG4SimulationTracking.cc, offline/QA/modules/QAG4SimulationTracking.h, offline/QA/modules/QAG4SimulationVertex.cc, offline/QA/modules/QAG4SimulationVertex.h, offline/packages/trackreco/MakeActsGeometry.h, offline/packages/trackreco/PHSiliconTpcTrackMatching.cc
This PR adds a setter for the embed id flag in the QA modules. It defaults to the current behavior, so the Jenkins QA should run normally but we want to be able to set it for the daily build Hijing and Pythia8 QA. 
It also cleans up unused code in MakeActsGeometry and hides a verbosity statement from the track matcher.
=> Add embed setter for QA modules

simulation/g4simulation/g4ihcal/PHG4IHCalDetector.cc, simulation/g4simulation/g4ihcal/PHG4IHCalDetector.h, simulation/g4simulation/g4ohcal/PHG4OHCalDetector.cc, simulation/g4simulation/g4ohcal/PHG4OHCalDetector.h
This PR disables the GDML/TGeo geometry export for new HCal, which is aimed to solve two issues since the introduction of the new HCal: 
* The exported geometry has a compatibility issue that lead to large amount of overlap errors in the exported sPHENIX geometry in TGeo: [example error message in CI geometry checks](https://web.sdcc.bnl.gov/jenkins-sphenix/job/sPHENIX/job/test-overlap-check-pipeline/1687/artifact/macros/detectors/sPHENIX/Fun4All_G4_sPHENIX.log/*view*/). This geometry copy is later used in downstream tracking …
=> Disable GDML/TGeo geometry export for new HCal

simulation/g4simulation/g4tpc/PHG4TpcDigitizer.cc
Commented out the line in the TPC digitizer that removes entries from the hit-truth association map for TPC hits that fall below ADC threshold. This speeds up the TPC digitizer by a factor of more than three for 1000 pion events, with no obvious effect on tracking. The speed up will be larger for events with more hits.
For 1000 pion events with fixed random seed:
TPC digitizer time/evt = 28.2 s  before and 8.7 s after the change
TPC clustering time/evt = 0.68 s before and 0.62 s …
=> Comment out removal of hit-truth association for TPC hits with ADC zero to speed it up

offline/packages/trackbase_historic/SvtxTrackMap_v2.cc, offline/packages/trackreco/PHActsTrkFitter.cc, offline/packages/trackreco/PHGenFitTrkFitter.cc
This PR: 
- cleans up GenFit trackfit
- fixes the sourcelink order in Acts Trackfit. This is necessary because the SVTX+MM fit check this order and arbitrarily remove surfaces if it is not met
- fix crash in SVTX+MM fit, due to incorrect insertion of the fitted track in the map. 
- improves (speed up) track insertion in the maps, print a warning (and fixes a memory leak) in case of duplicated keys. …
=> Acts fit fixes

offline/packages/trackreco/MakeActsGeometry.cc
This PR adds a warning for running a macro with TPOT in G4 but without the TPOT in the tracking. This inadvertently happens unless you set `Enable::MICROMEGAS=true` and leads to a seg fault, so this warning will hopefully make it more clear.
=> Add warning for tpot

offline/packages/tpc/TpcClusterMover.cc, offline/packages/tpc/TpcClusterMover.h, offline/packages/trackreco/MakeActsGeometry.cc, offline/packages/trackreco/MakeActsGeometry.h, offline/packages/trackreco/PHActsTrkFitter.cc, simulation/g4simulation/g4tpc/PHG4TpcPadPlaneReadout.cc
This PR fixes the TGeo TPC overlap introduced from the changes in the TPC gas volume at the G4 level. It also removes all hard coded instances of the TPC geometry from the cluster+track reconstruction and uses only the CellGeometryContainer to get the relevant pad plane readout information.
=> fix tpc overlap

offline/packages/KFParticle_sPHENIX/KFParticle_truthAndDetTools.cc
I added a new method to the truth matching in KFParticle. It now uses the new reco -> truth maps developed by the tracking team. If the maps don't exist it will revert back to the old method using association by nClusters, this will make it backwards compatible with our DSTs
=> KFP: New truth matching method using maps

simulation/g4simulation/g4ihcal/PHG4IHCalSteppingAction.cc
This PR updates the new gdml based ihcal light yield with ihcal Mephi maps. See attached pdf.
[newihcal.pdf](https://github.com/sPHENIX-Collaboration/coresoftware/files/9558470/newihcal.pdf)
=> update new gdml based ihcal light yield with maps

offline/packages/tpccalib/PHTpcResiduals.cc, offline/packages/tpccalib/TpcSpaceChargeReconstruction.cc, offline/packages/tpccalib/TpcSpaceChargeReconstruction.h
- remove use of now obsolete get_acts_covariance()
- cleanup
This fixes getting Nan for all reconstructed distortion corrections
Also adapts the Genfit version of the distortion corrections to new track interface, and make acts/genfit distortion reconstruction more consistent. 
We still need the genfit path in order to be able to compare with acts in detail. …
=> Distortion correction fixes

simulation/g4simulation/g4main/PHG4Reco.cc
After https://github.com/sPHENIX-Collaboration/coresoftware/pull/1665 a rare memory invalid read is observed at https://ecce-eic.github.io/doxygen/d8/d17/G4EmSaturation_8cc_source.html#l00132 , which appears related to the order of initialization between material table and `G4EmSaturation` that manages Birk constants. In particular, it fixes `G4EmSaturation::effCharges` array size to the number of material at its initialization. 
This pull request is a test, moving `G4EmSaturation` initialization to after the G4 subsystem geometry …
=> Initialize `G4EmSaturation` after all materials are defined

simulation/g4simulation/g4eval/SvtxEvaluator.cc, simulation/g4simulation/g4eval/TrackSeedTrackMapConverter.cc, simulation/g4simulation/g4eval/TrackSeedTrackMapConverter.h
Catch missing vertex seg fault in evaluator when running single particles
This PR updates the seed converter to use `SvtxTrack_v4`. It now works on full seeds in local tests so that the seeding quantities can be evaluated.
It should be merged with the corresponding macros PR [555](https://github.com/sPHENIX-Collaboration/macros/pull/555)
=> Update seed converter to SvtxTrack_v4

simulation/g4simulation/g4ihcal/PHG4IHCalSteppingAction.cc, simulation/g4simulation/g4ohcal/PHG4OHCalSteppingAction.cc
This PR enables keeping the light correction in G4 but disabling the application of the MEPHI maps. Set the  light_scint_model flag which defaults to 1 to larger- equal 10
e.g.
G4HCALIN::light_scint_model = 20;
G4HCALOUT::light_scint_model = 20;
does the trick
=> disable mephi maps if light_scint_model >= 10 for testing

offline/packages/trackbase_historic/SvtxTrack_v4.cc, offline/packages/trackreco/Makefile.am, offline/packages/trackreco/SvtxTrackStateRemoval.cc, offline/packages/trackreco/SvtxTrackStateRemoval.h
This PR adds a module that strips SvtxTracks of all the state information except that at the PCA and in the calorimeters. It should lead to an order of magnitude reduction in DST size when run as it takes the number of states of the average track from ~50 to ~5. It  can be run in any macro by just adding to the Fun4AllServer, e.g.
```
auto remover = new SvtxTrackStateRemoval;
se->registerSubsystem(remover);
```
=> Add track state removing module

offline/packages/trackbase/AlignmentTransformation.cc, offline/packages/trackbase/AlignmentTransformation.h, offline/packages/trackbase/alignmentTransformationContainer.cc, offline/packages/trackbase/alignmentTransformationContainer.h, offline/packages/trackbase/sPHENIXActsDetectorElement.cc
This PR converts the alignment transformation map from a map of all transformations with a key of Acts::GeometryId to a vector of vectors, where the index of the main vector is layer number and the index of the sub vectors is sensor number. The purpose is to minimize the time required to locate a local/global transformation for a given surface. After the change, the execution times for 500 pion events for modules that use Acts transformations are indistinguishable from …
=> More transform map speedup

simulation/g4simulation/g4ihcal/PHG4IHCalSteppingAction.cc
This PR is as a result of a discussion at the software meeting on 9/20- A request was made to normalize the Mephi maps on a tile by tile basis rather than as a whole map.
The idea to previously normalize a whole map, rather than on a tile by tile basis was due to the fact that the old sims tiles were smaller than the Mephi maps. This led lines between tiles (creating artificial hotspots) - see page 4 of https://indico.bnl.gov/event/13165/contributions/54359/attachments/37115/61122/EjiroU_ohcal_update_091421.pdf
Normalizing the whole map suppresses the artificial hotspots on the borders of the tiles.
The new ihcal sims however are more closely matched with the Mephi maps, hence, normalizing tile by tile is not an issue in this case and is done here-  (given the need to suppress the tile by …
=> update to use tile by tile normalized maps

simulation/g4simulation/g4ihcal/PHG4IHCalDetector.cc, simulation/g4simulation/g4main/PHG4Reco.cc, simulation/g4simulation/g4ohcal/PHG4OHCalDetector.cc
This PR defines a new material (Uniplast_scintillator)in PHG4Reco::DefineMaterials() which is G4_POLYSTYRENE with a different name. We are going to use Uniplast_scintillator for HCal in order to change the Birks' constant for HCal without interfering with other subsystems.
=> "new" scintillator material for HCal

offline/packages/trackbase_historic/SvtxTrack_v4.cc, simulation/g4simulation/g4eval/SvtxEvaluator.cc, simulation/g4simulation/g4eval/SvtxTrackEval.cc, simulation/g4simulation/g4eval/TrackSeedTrackMapConverter.cc
Enables the relevant parts of the tracking chain and vertexing to be run with only the silicon tracking detectors active. Specifically, fixes crashes in SvtxTrackv4::Identify, SvtxTrackEval, and SvtxEvaluator resulting from the absence of a TPC seed, and implements a simple chi2 and ndf calculation in TrackSeedTrackMapConverter that enables PHSimpleVertexFinder to work with silicon-only tracks. …
=> Enable silicon-only tracking and vertexing

simulation/g4simulation/g4eval/SvtxEvaluator.cc
Adds reco vertex ID and reco vertex position to ntp_track and ntp_gtrack, and adds vertex ID to ntp_vertex.
=> Adding reco track vertex association info to SvtxEvaluator ntuples

offline/packages/trackreco/ALICEKF.cc, offline/packages/trackreco/PHCASeeding.cc, offline/packages/trackreco/PHCASeeding.h, offline/packages/trackreco/PHSimpleKFProp.cc, offline/packages/trackreco/PHSimpleKFProp.h
Rewrites PHCASeeding, ALICEKF, and PHSimpleKFProp to be more efficient, especially at lower pT and in pp data.
- Switches from eta-phi search window to z-phi search window
- Builds multiple cluster chains if multiple compatible clusters are found
- Propagates and filters using energy loss corrections
- Propagates with double previous resolution
Note that the change to a z-phi window involves a significant change to the G4_Tracking.C settings for PHCASeeding: https://github.com/sPHENIX-Collaboration/macros/pull/556.
[comment]: <> ( In …
=> TPC seeding overhaul

offline/packages/tpc/TpcDistortionCorrection.cc, offline/packages/trackreco/PHGenFitTrkFitter.cc, offline/packages/trackreco/PHGenFitTrkFitter.h, offline/packages/trackreco/PHMicromegasTpcTrackMatching.cc, offline/packages/trackreco/PHMicromegasTpcTrackMatching.h, simulation/g4simulation/g4tpc/PHG4TpcDistortion.cc
Three fixes to the distortion code
- remove adding ad hoc corrections to the TPC-Micromegas matching when running in distortion calibration mode. This should be handled upstream by adding a first guess of the distortions corrections upfront. @adfrawley : this is what we discussed this morning
- make the genfit handling of the distortion calibration mode closer to that of acts, by adding a dedicated flag and skipping the tracks that don't have a Micromegas
- remove the ominous TH3::interpolate warnings by checking the cluster position against histogram's boundaries upfront. @pinkenburg : this should make JobA much less verbose.  
[comment]: <> ( What types of changes does your code introduce? Put an `x` in all the boxes that …
=> Distortion fixes

offline/packages/trackreco/ALICEKF.cc
Fixes error in ALICEKF where pathological track seeds still tried to look up the magnetic field values at NaN position values. Checking whether the current position is NaN, and terminating before calling the magnetic field lookup if so, eliminates this error.
=> Fix B field NaN lookup error

offline/packages/tpccalib/PHTpcResiduals.cc, offline/packages/tpccalib/PHTpcResiduals.h, offline/packages/tpccalib/TpcSpaceChargeReconstruction.cc, offline/packages/tpccalib/TpcSpaceChargeReconstruction.h, offline/packages/trackreco/PHGenFitTrkFitter.cc
The track-base distortion correction code needs to know and apply existing corrections before calculating residuals. This is necessary to e.g. first correct for static distortions, before calculating beam-induced distortion
=> Distortion fix

offline/packages/PHField/PHField3DCartesian.cc
This PR adds the filename to the printout when a key cannot be found to clarify which map is being looked at
[skip-ci]
=> print the filename of the fieldmap where the key lookup fails

simulation/g4simulation/g4eval/SvtxHitEval.cc, simulation/g4simulation/g4eval/SvtxHitEval.h
Add an additional argument to the methods `std::set<PHG4Hit*> SvtxHitEval::all_truth_hits` and `PHG4Hit* SvtxHitEval::max_truth_hit_by_energy` to specify the TrkrId to find the proper TrkrHitsets to perform matching. 
Added methods are `std::set<PHG4Hit*> all_truth_hits(TrkrDefs::hitkey hit_key, const TrkrDefs::TrkrId trkrid);`, `PHG4Hit* max_truth_hit_by_energy(TrkrDefs::hitkey hit_key, const TrkrDefs::TrkrId trkrid);`, `std::set<PHG4Particle*> all_truth_particles(TrkrDefs::hitkey hit_key, const TrkrDefs::TrkrId trkrid);`, and `PHG4Particle* max_truth_particle_by_energy(TrkrDefs::hitkey hit_key, const TrkrDefs::TrkrId …
=> SvtxHitEval: truth matching with trkrid as an additional argument

simulation/g4simulation/g4ohcal/PHG4OHCalDetector.cc
This PR introduces the correct 10cm safety margin for the field map cut (to account for the 2x2 grid). 
[skip-ci]
=> apply 10 cm safety margin for steel fieldmap

offline/packages/TrackerMillepedeAlignment/HelicalFitter.cc, offline/packages/TrackerMillepedeAlignment/HelicalFitter.h, offline/packages/TrackerMillepedeAlignment/MakeMilleFiles.cc, offline/packages/TrackerMillepedeAlignment/MakeMilleFiles.h
The optional grouping of hitsets into sectors during alignment is modified so that the grouping is by sector and region (inner, mid, outer) to better match how the TPC is constructed.
=> Modified TPC sector grouping to be by region and sector

simulation/g4simulation/g4tpc/PHG4TpcElectronDrift.cc, simulation/g4simulation/g4tpc/PHG4TpcPadPlaneReadout.cc, simulation/g4simulation/g4tpc/TpcClusterBuilder.cc, simulation/g4simulation/g4tpc/TpcClusterBuilder.h
While working on the TrkrCluster matching for the Embedded to Reco tracks, I found a bug in my code for the arguments of  TrkrCluster->Set{Phi,Z}Size when filling the clusters for the truth tracks. This code fixes that error.
=> Fix error in code in storing TrkrCluster sizes for phi and time

simulation/g4simulation/g4decayer/pythia6_common_address.c
This PR should fix the pythia6 decayer. THe mapping of c style arrays with fortran common blocks seems to have changed - it now needs an extern declaration. This seems to work also for gcc 8.3, we'll see what jenkins says
=> c arrays need extern declaration

offline/packages/decayfinder/DecayFinder.cc, offline/packages/decayfinder/DecayFinder.h
Zhaozhong requested an update to DecayFinder so it doesn't require the HepMC record to run. He's using particle guns which only write to the truth info container. This should allow him to run DecayFinder and use the truth info QA code
Zhaozhong should check if this works with his particle gun
=> Updated decay finder to not require the HepMC record
