sPHENIX-Collaboration/coresoftware

simulation/g4simulation/g4detectors/PHG4CrystalCalorimeterDetector.cc

Fixes issue where maximum j, k index would have to be hard coded into the software (PHG4CrystalCalorimeterDetector.cc), as well as subtracts the _place_in_x and _place_in_y (position in x and y of the mother volume) from the position of the daughter volumes instead of only the _place_in_z in previous version.

Fixes issues which were raised in the last pull request

---

simulation/g4simulation/g4field/PHG4Field2D.C
simulation/g4simulation/g4field/PHG4Field2D.h
simulation/g4simulation/g4field/PHG4Field3D.C
simulation/g4simulation/g4field/PHG4Field3D.h
simulation/g4simulation/g4field/PHG4FieldsPHENIX.cc
simulation/g4simulation/g4field/PHG4FieldsPHENIX.h
simulation/g4simulation/g4main/G4TBMagneticFieldSetup.cc
simulation/g4simulation/g4main/G4TBMagneticFieldSetup.hh
simulation/g4simulation/g4main/PHG4Reco.cc
simulation/g4simulation/g4main/PHG4Reco.h

This will add an interface for passing down a rescale factor to the magnetic field objects. Impact on g4field and g4main libraries. Default value is 1.0. I will add the macro handles after a new build. I tested that a field/2 gives a pt*2.

Rescale any magnetic field by some value

---

simulation/g4simulation/g4vertex/BbcVertex.h
simulation/g4simulation/g4vertex/BbcVertexMapLinkDef.h
simulation/g4simulation/g4vertex/BbcVertexMap_v1.h
simulation/g4simulation/g4vertex/GlobalVertex.h
simulation/g4simulation/g4vertex/GlobalVertexLinkDef.h
simulation/g4simulation/g4vertex/GlobalVertexMapLinkDef.h

Silence an error message from the g4vertex_io DST output. Thanks Jin for the help diagnosing.

Global dst fix

---

simulation/g4simulation/g4main/HepMCNodeReader.cc
simulation/g4simulation/g4main/HepMCNodeReader.h

allow Pythia (or other generators) read in off the HEPMC node to have the embed flags set to some value

Add embed flag setting to HEPMC node reader

---

offline/packages/HelixHough/helix_hough/HelixHough.h
offline/packages/HelixHough/helix_hough/HelixHough_findHelices.cpp
offline/packages/HelixHough/helix_hough/HelixHough_init.cpp
offline/packages/HelixHough/helix_hough/sPHENIX/sPHENIXTracker_findTracksBySegments.cpp
simulation/g4simulation/g4hough/PHG4TPCClusterizer.C
simulation/g4simulation/g4hough/PHG4TPCClusterizer.h

This is take two on the pull request to get the TPC merged completely into master.  In this attempt, the changes necessary for the TPC tracking to run well in central HIJING have been disabled by default, so (fingers crossed) silicon tracking shouldn't be affected.

Tpc testing2

---

online_distribution/newbasic/prdfBuffer.cc

that can create a lot of output...

mlp - had forgotten to take out a stray debug print statement. Done

---

simulation/g4simulation/g4detectors/Makefile.am
simulation/g4simulation/g4detectors/PHG4Prototype2InnerHcalDetector.cc
simulation/g4simulation/g4detectors/PHG4Prototype2InnerHcalDetector.h
simulation/g4simulation/g4detectors/PHG4Prototype2InnerHcalSteppingAction.cc
simulation/g4simulation/g4detectors/PHG4Prototype2InnerHcalSteppingAction.h
simulation/g4simulation/g4detectors/PHG4Prototype2InnerHcalSubsystem.cc
simulation/g4simulation/g4detectors/PHG4Prototype2InnerHcalSubsystem.h
simulation/g4simulation/g4detectors/PHG4Prototype2InnerHcalSubsystemLinkDef.h
simulation/g4simulation/g4detectors/PHG4Prototype2OuterHcalDetector.cc

The inner hcal prototype is ready, just like for the outer hcal needs coordinates of corners of bottom steel plate and scintillator tiles, everything else derived from that. Verified by checking the coordinates of top steel plate which are smack on the g4hits display for the inner hcal top steel plate

Inner Hcal prototype

---

online_distribution/newbasic/dlist.cc

The comment says it - I added a stray line after I had checked everything. Fixed.

mlp -- managed to commit a stray line after all the checks.. fixed.

---

simulation/g4simulation/g4cemc/Makefile.am
simulation/g4simulation/g4cemc/Prototype2RawTowerBuilder.cc
simulation/g4simulation/g4cemc/Prototype2RawTowerBuilder.h
simulation/g4simulation/g4cemc/Prototype2RawTowerBuilderLinkDef.h
simulation/g4simulation/g4detectors/Makefile.am
simulation/g4simulation/g4detectors/PHG4BlockSteppingAction.cc
simulation/g4simulation/g4detectors/PHG4Parameters.cc
simulation/g4simulation/g4detectors/PHG4Prototype2HcalCellReco.cc
simulation/g4simulation/g4detectors/PHG4Prototype2HcalCellReco.h
simulation/g4simulation/g4detectors/PHG4Prototype2HcalCellRecoLinkDef.h
simulation/g4simulation/g4detectors/PHG4ScintillatorSlat.cc
simulation/g4simulation/g4detectors/PHG4ScintillatorSlat.h
simulation/g4simulation/g4detectors/PHG4ScintillatorSlatContainer.cc
simulation/g4simulation/g4detectors/PHG4ScintillatorSlatContainer.h
simulation/g4simulation/g4detectors/PHG4ScintillatorSlatContainerLinkDef.h
simulation/g4simulation/g4detectors/PHG4ScintillatorSlatDefs.cc
simulation/g4simulation/g4detectors/PHG4ScintillatorSlatDefs.h
simulation/g4simulation/g4detectors/PHG4ScintillatorSlatDefsLinkDef.h
simulation/g4simulation/g4detectors/PHG4ScintillatorSlatLinkDef.h
simulation/g4simulation/g4detectors/PHG4ScintillatorSlatv1.cc
simulation/g4simulation/g4detectors/PHG4ScintillatorSlatv1.h
simulation/g4simulation/g4detectors/PHG4ScintillatorSlatv1LinkDef.h
simulation/g4simulation/g4histos/G4HitNtuple.cc

This adds new classes. The cell reconstruction combines G4Hits on a slat by slat level, the tower builder combines 5 slats in the same eta bin into a tower

Add slat wise cell reconstruction and tower builder for prototype

---

simulation/g4simulation/g4cemc/Prototype2RawTowerBuilder.cc
simulation/g4simulation/g4cemc/Prototype2RawTowerBuilder.h
simulation/g4simulation/g4cemc/RawTowerContainer.cc
simulation/g4simulation/g4detectors/PHG4Prototype2InnerHcalSteppingAction.cc
simulation/g4simulation/g4detectors/PHG4Prototype2OuterHcalSteppingAction.cc
simulation/g4simulation/g4detectors/PHG4ScintillatorSlatDefs.cc
simulation/g4simulation/g4histos/G4AnalysisLinkDef.h
simulation/g4simulation/g4histos/G4RootScintillatorSlat.cc
simulation/g4simulation/g4histos/G4RootScintillatorSlat.h
simulation/g4simulation/g4histos/G4RootScintillatorSlatContainer.cc
simulation/g4simulation/g4histos/G4RootScintillatorSlatContainer.h
simulation/g4simulation/g4histos/G4RootScintillatorTower.cc
simulation/g4simulation/g4histos/G4RootScintillatorTower.h
simulation/g4simulation/g4histos/G4RootScintillatorTowerContainer.cc
simulation/g4simulation/g4histos/G4RootScintillatorTowerContainer.h
simulation/g4simulation/g4histos/G4ScintillatorSlatTTree.cc
simulation/g4simulation/g4histos/G4ScintillatorSlatTTree.h
simulation/g4simulation/g4histos/G4ScintillatorTowerTTree.cc
simulation/g4simulation/g4histos/G4ScintillatorTowerTTree.h
simulation/g4simulation/g4histos/Makefile.am

120 GeV/c protons at 0/0 (100 events overlayed)
Inner Hcal Slats:
Inner Hcal Towers
Outer Hcal Slats:
Outer Hcal Towers

Add prototype tower reconstruction, bugfixes for consistent row/column handling

---

simulation/g4simulation/g4histos/G4HitNtuple.cc

This is just a one line fix but my next pull request will take a while and I want this in before it gets forgotten

put layers back, they work now after fixing stepping actions

---

simulation/g4simulation/g4detectors/Makefile.am
simulation/g4simulation/g4detectors/PHG4HcalPrototype2Detector.cc
simulation/g4simulation/g4detectors/PHG4HcalPrototype2Detector.h
simulation/g4simulation/g4detectors/PHG4HcalPrototype2DetectorMessenger.cc
simulation/g4simulation/g4detectors/PHG4HcalPrototype2DetectorMessenger.h
simulation/g4simulation/g4detectors/PHG4HcalPrototype2SteppingAction.cc
simulation/g4simulation/g4detectors/PHG4HcalPrototype2SteppingAction.h
simulation/g4simulation/g4detectors/PHG4HcalPrototype2Subsystem.cc
simulation/g4simulation/g4detectors/PHG4HcalPrototype2Subsystem.h
simulation/g4simulation/g4detectors/PHG4HcalPrototype2SubsystemLinkDef.h

HCal (inner&outer) prototype2 simulation code. It is an independent implementation comparing to Chris' Prototype2OuterHcal. And we can do cross check for each other.
An example macro to run these modules are located on RCF:
/phenix/u/sar/work/macros/Fun4All_G4_HcalPrototype2.C

Prototype2 code that supports both inner and outer HCal.

---

offline/packages/Prototype2/Makefile.am
offline/packages/Prototype2/TempInfoUnpackPRDF.C
offline/packages/Prototype2/TempInfoUnpackPRDF.h
offline/packages/Prototype2/TempInfoUnpackPRDFLinkDef.h

added the classes than stores the temperature readings on the DST.

mlp - added the temperature-storing class and subsysreco class

---

simulation/g4simulation/g4eval/SvtxEvaluator.C
simulation/g4simulation/g4hough/SvtxCluster.h
simulation/g4simulation/g4hough/SvtxCluster_v1.C
simulation/g4simulation/g4hough/SvtxCluster_v1.h

This is a simple one to add x,y,z,phi errors to the eval tables.

Eval Tools to Check Cluster Errors

---

simulation/g4simulation/g4eval/SvtxEvaluator.C
simulation/g4simulation/g4eval/SvtxTrackEval.C
simulation/g4simulation/g4eval/SvtxTrackEval.h

Add Reconstructed Track IDs to Cluster Eval

---

generators/PHPythia6/PHPythia6.C
generators/PHPythia6/PHPythia6.h
generators/PHPythia6/phpythia6_ep.cfg

Continuation of pull request #152 by adding another commit.
Histograms show comparison of jet QA plots between master branch version and this pull request. No minimum parton pT cut applied (used phpyhtia6.cfg and commented out 'ckin    3  25.0'). The histograms agree.
No errors when running phpythia6_ep.cfg configuration file.

Pythia6 ep test

---

generators/PHPythia6/PHPythia6.C
generators/PHPythia6/phpythia6_ep.cfg

Incorporates a configuration file for ep collisions. PHPythia6.C is modified so that "p1" and "p2" are used as the labels for the electron and proton momenta.

Incorporate ep Configuration File 

---

generators/PHPythia6/PHPy6ForwardElectronTrig.C

Fixed the pseudorapidity cut for the trigger (wrong method used), added 1GeV total momentum cut.

fix trigger pseudorapidity, add momentum cut

---

generators/PHPythia6/PHPythia6.C
generators/PHPythia6/PHPythia6.h

output trigger statistics (fraction passed) at the end of each run, fix memory leak.

PHPythia6 fixes

---

generators/PHPythia6/Makefile.am
generators/PHPythia6/PHPy6ForwardDiElectronTrig.C
generators/PHPythia6/PHPy6ForwardDiElectronTrig.h
generators/PHPythia6/PHPythia6LinkDef.h

Added a dielectron trigger for fsPHENIX MB studies

added dielectron troigger

---

offline/framework/ffaobjects/EventHeader.h
offline/packages/Prototype2/RunInfoUnpackPRDF.C

I don't think this merits a new version, so I left the name at v1.

Added the run number to the event header. 

---

generators/PHPythia6/Makefile.am
generators/PHPythia6/PHPy6ForwardElectronTrig.C
generators/PHPythia6/PHPy6ForwardElectronTrig.h
generators/PHPythia6/configure.in

Adding addition configuration options for the electron trigger, fixed includes issues (thansk @pinkenburg ), package fixes from @blackcathj

additional configurability for electron trigger, fixes from Jin

---

offline/packages/NodeDump/DumpSvtxClusterMap.cc
offline/packages/NodeDump/DumpSvtxClusterMap.h
offline/packages/NodeDump/DumpSvtxHitMap.cc
offline/packages/NodeDump/DumpSvtxHitMap.h
offline/packages/NodeDump/DumpSvtxTrackMap.cc
offline/packages/NodeDump/DumpSvtxTrackMap.h
offline/packages/NodeDump/DumpSvtxVertexMap.cc
offline/packages/NodeDump/DumpSvtxVertexMap.h
offline/packages/NodeDump/Makefile.am
offline/packages/NodeDump/PHNodeDump.cc

This dumps the content of the svtx nodes into ascii files for fast and easy checking if some code change affects the data

Adding dump classes for svtx objects (hit, cluster,track,vertex)

---

simulation/g4simulation/g4detectors/PHG4Parameters.cc
simulation/g4simulation/g4detectors/PHG4Parameters.h

fixes the build crash, but we should have a look at how we want to do this

add old saving of PHG4Parameters on node tree back for prototype

---

simulation/g4simulation/g4cemc/HcalRawTowerBuilder.cc
simulation/g4simulation/g4cemc/RawTowerDigitizer.cc

While this patch now creates digi towers, the truth backtracing will still not work. I need to fall back to G4Cells instead of the slats.

lets try this again. This fix for the tower geometry now fills the digi towers

---

simulation/g4simulation/g4cemc/HcalRawTowerBuilder.cc

one last time - phi mapping no from 0-2pi which is against our convention -pi to pi

---

simulation/g4simulation/g4detectors/PHG4CylinderCellReco.cc
simulation/g4simulation/g4detectors/PHG4CylinderCellReco.h
simulation/g4simulation/g4detectors/PHG4CylinderCellTPCReco.cc
simulation/g4simulation/g4detectors/PHG4CylinderCellTPCReco.h
simulation/g4simulation/g4detectors/PHG4MapsCellReco.cc
simulation/g4simulation/g4detectors/PHG4MapsCellReco.h

That gained between 30% and 50% more speed to the cell recos (cylinder, TPC and Maps). It affects the order of the stored cells but subsequent tracking is not affected (tracks stay identical, except for one small change in the 4th digit, something is not numerically stable in the tracking)

replaced expensive string keys in map by unsigned long long keys

---

simulation/g4simulation/g4detectors/PHG4Cell.cc
simulation/g4simulation/g4detectors/PHG4Cell.h
simulation/g4simulation/g4detectors/PHG4Cellv1.h
simulation/g4simulation/g4detectors/PHG4SiliconTrackerCellReco.cc
simulation/g4simulation/g4detectors/PHG4SiliconTrackerCellReco.h
simulation/g4simulation/g4hough/Makefile.am
simulation/g4simulation/g4hough/PHG4SiliconTrackerDigitizer.C
simulation/g4simulation/g4hough/PHG4SiliconTrackerDigitizer.h
simulation/g4simulation/g4hough/PHG4SiliconTrackerDigitizerLinkDef.h
simulation/g4simulation/g4hough/PHG4SvtxDeadArea.C
simulation/g4simulation/g4hough/PHG4SvtxDeadArea.h
simulation/g4simulation/g4hough/PHG4SvtxThresholds.C
simulation/g4simulation/g4hough/PHG4SvtxThresholds.h

This puts the deleted silicon tracker subsystem back. The only thing still missing is the  PHG4SvtxClusterizer which will take a bit longer. I just want to get this back out there

put SILICON_TRACKER sources back in

---

simulation/g4simulation/g4detectors/PHG4SiliconTrackerCellReco.cc
simulation/g4simulation/g4hough/PHG4SvtxClusterizer.C
simulation/g4simulation/g4hough/PHG4SvtxClusterizer.h

The PHG4SvtxClusterizer is a cut and paste nightmare and should be replaced by something more organized. It spands a lot of time uselessly sorting lists and looping over maps without doing anything

This puts the silicon tracker back - the intt shows up in the SvtxClusterMap

---

simulation/g4simulation/g4detectors/PHG4SiliconTrackerCellReco.cc
simulation/g4simulation/g4detectors/PHG4SiliconTrackerParameterisation.cc
simulation/g4simulation/g4detectors/PHG4SiliconTrackerSteppingAction.cc
simulation/g4simulation/g4hough/PHG4SvtxClusterizer.C

Modified PHG4SiliconTrackerSteppingAction to work around a bug in the reporting of the volume for the first pre-step point in a multi-strip hit.
Fixed a bug in PHG4SvtxClusterizer that was preventing clustering for the INTT strips.
Cluster errors after the fix:
[intt_cluster_errors.pdf](https://github.com/sPHENIX-Collaboration/coresoftware/files/866737/intt_cluster_errors.pdf)
More details:
[INTT_clustering_fix_march23_2017.pdf](https://github.com/sPHENIX-Collaboration/coresoftware/files/866736/INTT_clustering_fix_march23_2017.pdf)

Intt cluster fix

---

simulation/g4simulation/g4hough/PHG4TrackKalmanFitter.C
simulation/g4simulation/g4hough/PHG4TrackKalmanFitter.h
simulation/g4simulation/g4main/HepMCNodeReader.cc
simulation/g4simulation/g4main/HepMCNodeReader.h

it compiles but I cannot test it. But since the new PHG4Cells and the old PHG4CylinderCells have the same interfaces it should work
The change in the HepMCNodeReader makes the random seed accessible from the outside so crashes where the seed is known can be reproduced

change PHG4TrackKalmanFitter to use PHG4Cells

---

simulation/g4simulation/g4detectors/PHG4SpacalPrototypeSteppingAction.h
simulation/g4simulation/g4detectors/PHG4SpacalPrototypeSubsystem.cc

Removing also the deletion of zero energy hits in the cemc prototype, this is now done in the stepping action

okay - this time it is the correct include file

---

offline/packages/trigger/CaloTriggerInfo.C
offline/packages/trigger/CaloTriggerInfo.h
offline/packages/trigger/CaloTriggerInfoLinkDef.h
offline/packages/trigger/CaloTriggerInfo_v1.C
offline/packages/trigger/CaloTriggerInfo_v1.h
offline/packages/trigger/CaloTriggerInfo_v1LinkDef.h
offline/packages/trigger/CaloTriggerSim.C
offline/packages/trigger/CaloTriggerSim.h
offline/packages/trigger/CaloTriggerSimLinkDef.h
offline/packages/trigger/Makefile.am
offline/packages/trigger/autogen.sh
offline/packages/trigger/configure.in

Same request, now with virtual base class and first version of CaloTriggerInfo (which is written to node)

Adding virtual base class and v1 implementation of CaloTriggerInfo

---

simulation/g4simulation/g4detectors/PHG4DetectorGroupSubsystem.cc
simulation/g4simulation/g4detectors/PHG4DetectorGroupSubsystem.h
simulation/g4simulation/g4detectors/PHG4ParametersContainer.h
simulation/g4simulation/g4detectors/PHG4SiliconTrackerDetector.cc
simulation/g4simulation/g4detectors/PHG4SiliconTrackerDetector.h
simulation/g4simulation/g4detectors/PHG4SiliconTrackerSteppingAction.cc
simulation/g4simulation/g4detectors/PHG4SiliconTrackerSteppingAction.h
simulation/g4simulation/g4detectors/PHG4SiliconTrackerSubsystem.cc
simulation/g4simulation/g4detectors/PHG4SiliconTrackerSubsystem.h

The output did not change, this is a major cleanup and a step towards using the parameter maps to store/retrieve all those magical numbers which are hardcoded. It does need a change in the macro to actually set each strip layer active

Starting to use the parameter map, right now for the active and black hole setting

---

simulation/g4simulation/g4detectors/PHG4BlockDetector.cc
simulation/g4simulation/g4detectors/PHG4BlockSteppingAction.cc
simulation/g4simulation/g4detectors/PHG4BlockSteppingAction.h
simulation/g4simulation/g4detectors/PHG4BlockSubsystem.cc
simulation/g4simulation/g4detectors/PHG4BlockSubsystem.h
simulation/g4simulation/g4detectors/PHG4CylinderDetector.cc
simulation/g4simulation/g4main/PHG4Reco.cc
simulation/g4simulation/g4main/PHG4Reco.h

I propagated the step size setting to the block subsystem. Use the new saving of hits with eloss in stepping action by detecting last step of current hit, remove the now obsolete old afterburner to remove zero energy hits. G4 verbosity can now be set via PHG4Reco

Block detector update

---

simulation/g4simulation/g4main/PHG4ParticleGeneratorVectorMeson.cc
simulation/g4simulation/g4main/PHG4ParticleGeneratorVectorMeson.h

Allows to reuse existing vertex stored in the PHG4InEvent node.

Vector meson generator upgrade

---

offline/framework/fun4all/Fun4AllServer.cc
offline/framework/fun4all/Fun4AllServer.h

Fun4AllServer::PrintTimer() prints the stats, it is not printed out be default

Add timer to check process_event time for each subsystem

---

simulation/g4simulation/g4detectors/Makefile.am
simulation/g4simulation/g4detectors/PHG4PSTOFDetector.cc
simulation/g4simulation/g4detectors/PHG4PSTOFDetector.h
simulation/g4simulation/g4detectors/PHG4PSTOFSteppingAction.cc
simulation/g4simulation/g4detectors/PHG4PSTOFSteppingAction.h
simulation/g4simulation/g4detectors/PHG4PSTOFSubsystem.cc
simulation/g4simulation/g4detectors/PHG4PSTOFSubsystem.h
simulation/g4simulation/g4detectors/PHG4PSTOFSubsystemLinkDef.h

New mRPC psTOF at radius between 80-90 cm.  First commit.

psTOF Added

---

simulation/g4simulation/g4hough/PHG4GenFitTrackProjection.C
simulation/g4simulation/g4hough/PHG4KalmanPatRec.C
simulation/g4simulation/g4hough/PHG4TrackKalmanFitter.C

Changes for positive Bz field map

Set no field reverse by default for PatRec, Fit, Projection modules

---

simulation/g4simulation/g4decayer/P6DExtDecayerPhysics.cc
simulation/g4simulation/g4main/PHG4Reco.cc

minor changes to make this compile with G4 10.03.p03, though we should fix the decayer

changes for G4 10.03.p03

---

simulation/g4simulation/g4cemc/BEmcCluster.cc
simulation/g4simulation/g4cemc/BEmcCluster.h
simulation/g4simulation/g4cemc/BEmcRec.cc
simulation/g4simulation/g4cemc/BEmcRec.h
simulation/g4simulation/g4cemc/RawCluster.h
simulation/g4simulation/g4cemc/RawClusterBuilderv1.cc
simulation/g4simulation/g4cemc/RawClusterBuilderv1.h
simulation/g4simulation/g4cemc/RawClusterv1.cc
simulation/g4simulation/g4cemc/RawClusterv1.h

Modifications are made to
1. Make PHENIX-style clustering work (modifications in the interface RawClusterBuilderv1.cc(h))
2. Introduce shower profile evaluation (in BEmcRec.cc(h) and BEmcCluster.cc(h)) and corresponding data fields "prob" and "chi2" in RawCluster class (RawCluster.h and RawClusterv1.h)
3. Make position correction (phi and eta) for the bias due to calorimeter cell structure (sinh shape) in BEmcRec.cc

Phenix-style clusterizer for sPHENIX

---

simulation/g4simulation/g4detectors/PHG4CylinderCellTPCReco.cc
simulation/g4simulation/g4eval/SvtxEvaluator.C

Added some variables to the SvtxEvaluator.C needed for cluster shape analysis and occupancy studies.
Update of the  PHG4CylinderCellTPCReco.cc. 7 sub segments per layer cause long clusters to look like a toblerone chocolate. Made number of subsegments variable depending on predicted cluster length z cluster width.

TPC Cluster Shape analysis changes

---

simulation/g4simulation/g4tpc/PHG4TPCElectronDriftLinkDef.h

add linkdef

---

simulation/g4simulation/g4tpc/Makefile.am

Adding this to the pull request was premature, this pull request takes it out of the build

do not build PHG4TPCElectronDrift

---

simulation/g4simulation/g4eval/SvtxEvaluator.C
simulation/g4simulation/g4hough/Makefile.am
simulation/g4simulation/g4hough/PHG4KalmanPatRec.C
simulation/g4simulation/g4hough/PHG4TPCClusterizer.C
simulation/g4simulation/g4hough/PHG4TPCClusterizer.h

TPC Clusterizer code as presented at the collaboration meeting.

TPC Clusterizer Update

---

offline/packages/Prototype4/PROTOTYPE4_FEM.C

update inner hcal mapping

---

offline/packages/Prototype4/CaloUnpackPRDF.C

inner hcal mapping is off by 1, low gain and high gain of outer hcal is reversed

update mapping of inner and outer hcal

---

simulation/g4simulation/g4eval/SvtxEvaluator.C
simulation/g4simulation/g4eval/SvtxEvaluator.h

added tpc hit multiplicity information to SvtxEvaluator so we can do multiplicity dependent upsilon resolution studies.

added hit multiplicity information

---

simulation/g4simulation/g4calo/RawTowerBuilder.cc
simulation/g4simulation/g4calo/RawTowerBuilder.h
simulation/g4simulation/g4detectors/PHG4CylinderSteppingAction.cc

just restoring the state of cout using boost::io::ios_XXX_saver which is a neat one line exception safe way to get back to the default once it goes out of scope way later

Coverity fix, restoring state of cout

---

offline/packages/ClusterIso/ClusterIso.cc
offline/packages/ClusterIso/ClusterIso.h
offline/packages/ClusterIso/ClusterIsoLinkDef.h
offline/packages/ClusterIso/Makefile.am
offline/packages/ClusterIso/autogen.sh
offline/packages/ClusterIso/configure.ac

…nt, ChaseSmith added doxygen comments, code was editted to meet Jin's standard, the generators were not deleted

ClusterIso

---

offline/packages/tpcdaq/Makefile.am
offline/packages/tpcdaq/README.md
offline/packages/tpcdaq/TPCDaqDefs.cc
offline/packages/tpcdaq/TPCDaqDefs.h
offline/packages/tpcdaq/TPCDaqDefsLinkDef.h
offline/packages/tpcdaq/TPCDataStreamEmulator.cc
offline/packages/tpcdaq/TPCDataStreamEmulator.h
offline/packages/tpcdaq/TPCDataStreamEmulatorLinkDef.h
offline/packages/tpcdaq/TPCIntegratedCharge.cc
offline/packages/tpcdaq/TPCIntegratedCharge.h
offline/packages/tpcdaq/TPCIntegratedChargeLinkDef.h
offline/packages/tpcdaq/autogen.sh
offline/packages/tpcdaq/configure.ac

Introducing TPC DAQ lib to TPC FEE and DAQ simulations using the Geant4 and tracking output. More details see https://indico.bnl.gov/event/4024/ 
Plot macros: https://github.com/sPHENIX-Collaboration/analysis/tree/master/TPC/DAQ/macros

Introducing TPC DAQ lib

---

generators/PHPythia8/phpythia8_mb.cfg

Validation:
https://indico.bnl.gov/event/4027/contributions/23165/attachments/19604/25768/sPHENIX_simulation_shlim_20180807.pdf

Pythia8 configuration file of MB p+p for pileup event generation

---

simulation/g4simulation/g4detectors/PHG4SiliconTrackerDefsLinkDef.h

forgot to check in simulation/g4simulation/g4detectors/PHG4SiliconTrackerDefsLinkDef.h

oops forgot that one

---

simulation/g4simulation/g4detectors/PHG4DetectorGroupSubsystem.cc
simulation/g4simulation/g4detectors/PHG4DetectorGroupSubsystem.h

The strings were handled okay in the latest version. This pull request modernizes the code with some c++11 features (return of map.insert, auto pointers in loops) which make the code a lot more compact and readable. This class still needs a DB (and file) backend

Parameter fix

---

simulation/g4simulation/g4detectors/Makefile.am
simulation/g4simulation/g4detectors/PHG4CylinderGeomSiLadders.cc
simulation/g4simulation/g4detectors/PHG4CylinderGeomSiLadders.h
simulation/g4simulation/g4detectors/PHG4CylinderGeomSiLaddersLinkDef.h
simulation/g4simulation/g4detectors/PHG4CylinderGeom_Siladders.cc
simulation/g4simulation/g4detectors/PHG4CylinderGeom_Siladders.h
simulation/g4simulation/g4detectors/PHG4SiliconTrackerCellReco.cc
simulation/g4simulation/g4detectors/PHG4SiliconTrackerDetector.cc
simulation/g4simulation/g4detectors/PHG4SiliconTrackerDetector.h
simulation/g4simulation/g4detectors/PHG4SiliconTrackerSteppingAction.cc
simulation/g4simulation/g4detectors/PHG4SiliconTrackerSteppingAction.h
simulation/g4simulation/g4detectors/PHG4SiliconTrackerSubsystem.cc
simulation/g4simulation/g4eval/MomentumEvaluator.C
simulation/g4simulation/g4eval/SvtxClusterEval.C
simulation/g4simulation/g4eval/SvtxEvaluator.C
simulation/g4simulation/g4eval/SvtxEvaluator.h
simulation/g4simulation/g4eval/SvtxHitEval.C
simulation/g4simulation/g4hough/PHG4InitZVertexing.C
simulation/g4simulation/g4hough/PHG4KalmanPatRec.C
simulation/g4simulation/g4hough/PHG4KalmanPatRec.h
simulation/g4simulation/g4hough/PHG4PatternReco.C
simulation/g4simulation/g4hough/PHG4SvtxClusterizer.C
simulation/g4simulation/g4hough/PHG4TrackKalmanFitter.C
simulation/g4simulation/g4hough/PHRaveVertexing.C

I guess I screwed up a bit - this is Tonys pull request with some bugfixes and variable cleanup

Adfrawley intt sublayer to layer

---

generators/phhepmc/Fun4AllHepMCInputManager.cc
generators/phhepmc/PHHepMCGenHelper.cc
simulation/g4simulation/g4main/HepMCNodeReader.cc

okay - it's done. Freeze this until we either switch to hepmc3 (unlikely) or port the jetscape writer to hepmc2 (needs effort)

remove printouts

---

simulation/g4simulation/g4detectors/PHG4SiliconTrackerDetector.cc
simulation/g4simulation/g4detectors/PHG4SiliconTrackerSubsystem.cc

INTT FPHX chip position is moved by +0.05mm to match to the actual design.

INTT FPHX chip position

---

simulation/g4simulation/g4detectors/PHG4SiliconTrackerDetector.cc

Modified the ladder volume for the INTT Z-sensitive ladders so that it tightly conforms to the actual material. This should avoid overlaps for the Z-sensitive layers. Modified the ladder placement algorithm so that the sensor is centered at the requested phi angle, and its face is normal to the radial vector from the barrel center. This is just as it was before, so the geometry object did not need to be modified.
Tested with the INTTLADDER6 configuration by plotting phi vs Z for all layers, and also by looking at the cluster resolution in Z for the Z-sensitive layers, and in phi for the phi-sensitive layers. All looks as it should.

Intt zsegmentation ladder volume

---

offline/framework/fun4all/Fun4AllServer.cc
simulation/g4simulation/g4eval/SvtxEvaluator.C
simulation/g4simulation/g4hough/PHG4KalmanPatRec.C
simulation/g4simulation/g4hough/PHG4KalmanPatRec.h
simulation/g4simulation/g4hough/PHG4TruthPatRec.C

merge this branch with the recent changes to the master branch to make comparisons possible

merge with master

---

offline/packages/jetbackground/DetermineTowerBackground.C
offline/packages/jetbackground/DetermineTowerBackground.h
offline/packages/jetbackground/TowerBackground.h
offline/packages/jetbackground/TowerBackground_v1.C
offline/packages/jetbackground/TowerBackground_v1.h
simulation/g4simulation/g4jets/Jet.h

1. add option to force Psi2 from mid-rapidity Hijing truth particles
2. setting of (new) jet properties to add information about seeds used in reconstruction
3. save number of calo towers (strips) used in background determination (flow determination)

Package of updates to aspects of HI jet reconstruction:

---

simulation/g4simulation/g4calo/HcalRawTowerBuilder.cc
simulation/g4simulation/g4calo/HcalRawTowerBuilder.h
simulation/g4simulation/g4calo/HcalRawTowerBuilderLinkDef.h
simulation/g4simulation/g4calo/Makefile.am
simulation/g4simulation/g4calo/Prototype2RawTowerBuilder.cc
simulation/g4simulation/g4calo/Prototype2RawTowerBuilder.h
simulation/g4simulation/g4calo/Prototype2RawTowerBuilderLinkDef.h
simulation/g4simulation/g4calo/RawTowerBuilder.h
simulation/g4simulation/g4calo/RawTowerBuilderByHitIndex.cc
simulation/g4simulation/g4calo/RawTowerBuilderByHitIndex.h
simulation/g4simulation/g4calo/RawTowerBuilderByHitIndexLinkDef.h
simulation/g4simulation/g4calo/RawTowerBuilderLinkDef.h
simulation/g4simulation/g4calo/RawTowerDigitizer.cc
simulation/g4simulation/g4calo/RawTowerDigitizer.h
simulation/g4simulation/g4calo/RawTowerDigitizerLinkDef.h
simulation/g4simulation/g4calo/configure.ac

one more root5/6 ready package

Root6 g4calo

---

offline/framework/frog/FROG.h
offline/framework/frog/FROGLinkDef.h
offline/framework/frog/Makefile.am
offline/framework/frog/configure.ac
offline/framework/phool/Makefile.am

build cmd line dicts only for root5, no i/o classes in this package

Root6 frog

---

offline/packages/ClusterIso/ClusterIso.cc
offline/packages/ClusterIso/ClusterIso.h
offline/packages/ClusterIso/ClusterIsoLinkDef.h
offline/packages/ClusterIso/Makefile.am
offline/packages/ClusterIso/configure.ac

create dict only for root5, cleanup, reduce lib dependencies to minimum, clang-format

Root6 clusteriso

---

offline/packages/PHGeometry/Makefile.am
offline/packages/PHGeometry/PHGeomFileImport.cc
offline/packages/PHGeometry/PHGeomFileImport.h
offline/packages/PHGeometry/PHGeomFileImportLinkDef.h
offline/packages/PHGeometry/PHGeomIOTGeo.cc
offline/packages/PHGeometry/PHGeomIOTGeo.h
offline/packages/PHGeometry/PHGeomIOTGeoLinkDef.h
offline/packages/PHGeometry/PHGeomTGeo.cc
offline/packages/PHGeometry/PHGeomTGeo.h
offline/packages/PHGeometry/PHGeomTGeoLinkDef.h
offline/packages/PHGeometry/PHGeomUtility.cc
offline/packages/PHGeometry/PHGeomUtility.h
offline/packages/PHGeometry/PHGeomUtilityLinkDef.h
offline/packages/PHGeometry/configure.ac

cmd line dicts for root5 only, i/o dicts for root5/6, cleanup, clang-format

Root6 phgeometry

---

offline/packages/PHGenFitPkg/GenFitExp/Field.cc
offline/packages/PHGenFitPkg/GenFitExp/Field.h

remove unused include files, clang-format

Root6 genfitexp

---

offline/database/PHParameter/PHParameters.cc
simulation/g4simulation/g4intt/PHG4INTTDigitizer.cc
simulation/g4simulation/g4intt/PHG4INTTDigitizer.h

This is Takahitos PR for the INTT noise with some fixes to make it work

Tktdrk intt sim

---

offline/framework/fun4all/Fun4AllPrdfInputManager.cc
offline/framework/fun4all/Fun4AllPrdfInputManager.h

small change to run multiple prdf input managers putting their content under macro defined prdf nodes

enable multiple prdf input managers

---

simulation/g4simulation/EICPhysicsList/AntiBaryonPhysics.cc
simulation/g4simulation/EICPhysicsList/AntiBaryonPhysics.hh
simulation/g4simulation/EICPhysicsList/EICPhysicsList.cc
simulation/g4simulation/EICPhysicsList/EICPhysicsList.hh
simulation/g4simulation/EICPhysicsList/GammaLeptoNuclearPhysics.cc
simulation/g4simulation/EICPhysicsList/GammaLeptoNuclearPhysics.hh
simulation/g4simulation/EICPhysicsList/HyperonPhysics.cc
simulation/g4simulation/EICPhysicsList/HyperonPhysics.hh
simulation/g4simulation/EICPhysicsList/IonPhysics.cc
simulation/g4simulation/EICPhysicsList/IonPhysics.hh
simulation/g4simulation/EICPhysicsList/KaonPhysics.cc
simulation/g4simulation/EICPhysicsList/KaonPhysics.hh
simulation/g4simulation/EICPhysicsList/Makefile.am
simulation/g4simulation/EICPhysicsList/NeutronPhysics.cc
simulation/g4simulation/EICPhysicsList/NeutronPhysics.hh
simulation/g4simulation/EICPhysicsList/PionPhysics.cc
simulation/g4simulation/EICPhysicsList/PionPhysics.hh
simulation/g4simulation/EICPhysicsList/ProtonPhysics.cc
simulation/g4simulation/EICPhysicsList/ProtonPhysics.hh
simulation/g4simulation/EICPhysicsList/autogen.sh
simulation/g4simulation/EICPhysicsList/configure.ac
simulation/g4simulation/g4main/Makefile.am
simulation/g4simulation/g4main/PHG4Reco.cc

This PR adds the proposed EIC G4 physics list. It covers the same energy range interesting for sPHENIX. It is experimental but we should have a close look at it

Eic physics list

---

simulation/g4simulation/g4main/Makefile.am

libphg4hit had inbuild deps on fun4all, eicsmear and subsysreco which don't have any business there. Cleaned up the Makefile.am, removed unneeded dep on libxerces for g4testbench as well

remove unneeded lib dependencies for libphg4hit

---

offline/packages/CaloReco/BEmcCluster.h
offline/packages/intt/INTTClusterizer.cc
offline/packages/mvtx/MVTXClusterizer.cc
simulation/g4simulation/EICPhysicsList/AntiBaryonPhysics.cc
simulation/g4simulation/g4detectors/PHG4mRICHDetector.cc
simulation/g4simulation/g4detectors/ePHENIXRICHConstruction.cc
simulation/g4simulation/g4detectors/ePHENIXRICHConstruction.h
simulation/g4simulation/g4hough/CellularAutomaton_v1.C
simulation/g4simulation/g4mvtx/PHG4CylinderCell_MVTX.cc

Fix a bunch of cppcheck warnings (the cellularautomaton_v1 was actually serious. Basically this is a check to see if jenkins works now with root6

Fix cppcheck

---

offline/framework/fun4all/Fun4AllFileOutStream.cc
offline/framework/fun4all/Fun4AllFileOutStream.h
offline/framework/fun4all/Fun4AllRolloverFileOutStream.cc
offline/framework/fun4all/Fun4AllRolloverFileOutStream.h
simulation/g4simulation/g4main/PHG4SteppingAction.cc
simulation/g4simulation/g4main/PHG4SteppingAction.h
simulation/g4simulation/g4main/ReadEICFiles.cc

the PR changes the Fun4AllFileOutStream base class to use private datamembers and access methods

Private datamembers for Fun4AllFileOutStream

---

simulation/g4simulation/g4main/Makefile.am

This PR just installs ReadEICFiles.h which is needed by the eic macro

install ReadEICFiles.h

---

simulation/g4simulation/g4histos/Makefile.am
simulation/g4simulation/g4main/PHG4IonGun.cc
simulation/g4simulation/g4main/PHG4IonGun.h

install the includes of the g4histos ntuple/ttree modules

install some more includes for root6

---

offline/packages/intt/Makefile.am
offline/packages/mvtx/Makefile.am
offline/packages/tpc/Makefile.am

ROOT5_IO_DICTS duplicates ROOTDICTS, will likely fail the root5 build

remove duplicate creation of dictionaries for root5

---

offline/packages/trackbase/TrkrClusterHitAssoc.cc
simulation/g4simulation/g4eval/Makefile.am
simulation/g4simulation/g4eval/SvtxClusterEval.cc
simulation/g4simulation/g4eval/SvtxClusterEval.h
simulation/g4simulation/g4eval/SvtxEvaluator.cc
simulation/g4simulation/g4eval/SvtxHitEval.cc
simulation/g4simulation/g4eval/SvtxHitEval.h
simulation/g4simulation/g4eval/SvtxTrackEval.cc
simulation/g4simulation/g4eval/SvtxTrackEval.h

Converted the SvtxEvaluator classes in g4eval to use the new containers. Seems to be working normally. Will make a separate pull request for the accompanying G4_Tracking.C macro.

Evaluator containers

---

offline/packages/HelixHough/helix_hough/HelixHough_init.cpp
simulation/g4simulation/g4eval/SvtxEvaluator.cc
simulation/g4simulation/g4eval/SvtxEvaluator.h
simulation/g4simulation/g4intt/INTTDeadMap.cc
simulation/g4simulation/g4intt/INTTDeadMap.h
simulation/g4simulation/g4intt/PHG4INTTHitReco.cc
simulation/g4simulation/g4intt/PHG4InttDigitizer.cc
simulation/g4simulation/g4intt/PHG4InttDigitizer.h
simulation/g4simulation/g4mvtx/PHG4MVTXDigitizer.cc
simulation/g4simulation/g4mvtx/PHG4MVTXDigitizer.h
simulation/g4simulation/g4tpc/PHG4TpcDigitizer.cc
simulation/g4simulation/g4tpc/PHG4TpcDigitizer.h

Fix some leaks

---

offline/packages/trackreco/PHGenFitTrkProp.cc
offline/packages/trackreco/PHGenFitTrkProp.h
simulation/g4simulation/g4detectors/PHG4CylinderGeom_Spacalv2.h
simulation/g4simulation/g4detectors/PHG4CylinderGeom_Spacalv3.cc
simulation/g4simulation/g4detectors/PHG4CylinderGeom_Spacalv3.h
simulation/g4simulation/g4detectors/PHG4FullProjTiltedSpacalDetector.cc
simulation/g4simulation/g4detectors/PHG4OuterHcalDetector.cc
simulation/g4simulation/g4mvtx/Makefile.am
simulation/g4simulation/g4mvtx/PHG4MVTXDetector.cc
simulation/g4simulation/g4tpc/PHG4TPCPadPlaneReadout.cc
simulation/g4simulation/g4tpc/PHG4TPCPadPlaneReadout.h
simulation/g4simulation/g4tpc/PHG4TpcElectronDrift.cc

Some more memory leaks fixed. Lets see if the valgrind suppression list works for this one

More fixes

---

simulation/g4simulation/g4detectors/Makefile.am
simulation/g4simulation/g4detectors/PHG4BlockDetector.cc
simulation/g4simulation/g4detectors/PHG4BlockDetector.h
simulation/g4simulation/g4detectors/PHG4BlockDisplayAction.cc
simulation/g4simulation/g4detectors/PHG4BlockDisplayAction.h
simulation/g4simulation/g4detectors/PHG4BlockSteppingAction.cc
simulation/g4simulation/g4detectors/PHG4BlockSteppingAction.h
simulation/g4simulation/g4detectors/PHG4BlockSubsystem.cc
simulation/g4simulation/g4detectors/PHG4BlockSubsystem.h
simulation/g4simulation/g4detectors/PHG4CylinderDisplayAction.h

This PR implements the DisplayAction for the block subsystem (pretty much a copy of the cylinders)

Block display

---

simulation/g4simulation/g4intt/PHG4INTTDisplayAction.h
simulation/g4simulation/g4tpc/Makefile.am
simulation/g4simulation/g4tpc/PHG4TPCDetector.cc
simulation/g4simulation/g4tpc/PHG4TPCDetector.h
simulation/g4simulation/g4tpc/PHG4TPCDisplayAction.cc
simulation/g4simulation/g4tpc/PHG4TPCDisplayAction.h
simulation/g4simulation/g4tpc/PHG4TPCPadPlaneReadout.cc
simulation/g4simulation/g4tpc/PHG4TPCSubsystem.cc
simulation/g4simulation/g4tpc/PHG4TPCSubsystem.h

This PR implements the DisplayAction for the tpc subsystem. It fixes a few memory leaks and involves some cleanup of obsolete things.  The valgrind suppression file was updated

DisplayAction for the tpc

---

simulation/g4simulation/g4detectors/Makefile.am
simulation/g4simulation/g4detectors/PHG4CylinderGeom_Spacalv1.cc
simulation/g4simulation/g4detectors/PHG4CylinderGeom_Spacalv1.h
simulation/g4simulation/g4detectors/PHG4FullProjSpacalDetector.cc
simulation/g4simulation/g4detectors/PHG4FullProjSpacalDetector.h
simulation/g4simulation/g4detectors/PHG4FullProjTiltedSpacalDetector.cc
simulation/g4simulation/g4detectors/PHG4FullProjTiltedSpacalDetector.h
simulation/g4simulation/g4detectors/PHG4Prototype2InnerHcalDetector.cc
simulation/g4simulation/g4detectors/PHG4Prototype2InnerHcalDetector.h
simulation/g4simulation/g4detectors/PHG4SpacalDetector.cc
simulation/g4simulation/g4detectors/PHG4SpacalDetector.h
simulation/g4simulation/g4detectors/PHG4SpacalDisplayAction.cc
simulation/g4simulation/g4detectors/PHG4SpacalDisplayAction.h
simulation/g4simulation/g4detectors/PHG4SpacalPrototypeDetector.h
simulation/g4simulation/g4detectors/PHG4SpacalSubsystem.cc
simulation/g4simulation/g4detectors/PHG4SpacalSubsystem.h
simulation/g4simulation/g4tpc/PHG4TPCDisplayAction.cc

This PR finishes the implementation of the DisplayAction for the MIE detectors. Some memory leak fixing, new suppression file for valgrind

Displayaction for Spacal

---

simulation/g4simulation/g4detectors/Makefile.am
simulation/g4simulation/g4detectors/PHG4CrystalCalorimeterDetector.cc
simulation/g4simulation/g4detectors/PHG4CrystalCalorimeterDetector.h
simulation/g4simulation/g4detectors/PHG4CrystalCalorimeterDisplayAction.cc
simulation/g4simulation/g4detectors/PHG4CrystalCalorimeterDisplayAction.h
simulation/g4simulation/g4detectors/PHG4CrystalCalorimeterSteppingAction.cc
simulation/g4simulation/g4detectors/PHG4CrystalCalorimeterSteppingAction.h
simulation/g4simulation/g4detectors/PHG4CrystalCalorimeterSubsystem.cc
simulation/g4simulation/g4detectors/PHG4CrystalCalorimeterSubsystem.h
simulation/g4simulation/g4detectors/PHG4ProjCrystalCalorimeterDetector.cc
simulation/g4simulation/g4detectors/PHG4ProjCrystalCalorimeterDetector.h
simulation/g4simulation/g4detectors/PHG4RICHDetector.cc
simulation/g4simulation/g4detectors/PHG4RICHDetector.h
simulation/g4simulation/g4detectors/PHG4RICHDisplayAction.cc
simulation/g4simulation/g4detectors/PHG4RICHDisplayAction.h
simulation/g4simulation/g4detectors/PHG4RICHSteppingAction.h
simulation/g4simulation/g4detectors/PHG4RICHSubsystem.cc
simulation/g4simulation/g4detectors/PHG4RICHSubsystem.h
simulation/g4simulation/g4detectors/ePHENIXRICHConstruction.cc
simulation/g4simulation/g4detectors/ePHENIXRICHConstruction.h

This PR applies the DisplayAction for the subsystems used in the EIC macro, clang-format and cleanup of unused includes as well

Displayaction eic

---

offline/framework/fun4all/Fun4AllDummyInputManager.cc
offline/framework/fun4all/Fun4AllDummyInputManager.h
offline/framework/fun4all/Fun4AllEventOutStream.h
offline/framework/fun4all/Fun4AllPrdfInputManager.cc
offline/framework/fun4all/Fun4AllPrdfInputManager.h
offline/framework/fun4all/Fun4AllSyncManager.cc
offline/framework/fun4all/Fun4AllSyncManager.h
simulation/g4simulation/g4dst/Makefile.am

This PR is just some fun4all cleanup. Replacing ifndef __CINT__ by if !defined(__CINT__) || defined (__CLING__) so rootcling can parse the include file properly. Add libintt_io and libmvtx_io to libg4dst so we can read any DST just loading this convenience library

Tweak fun4all

---

offline/packages/CaloReco/BEmcProfile.cc
offline/packages/CaloReco/BEmcProfile.h
offline/packages/CaloReco/Makefile.am
offline/packages/CaloReco/RawClusterBuilderTemplateFEMC.cc
offline/packages/CaloReco/RawClusterBuilderTemplateFEMC.h

BEmcProfile.cc(h): Introduced new class BEmcProfile to load EM shower profile data from external file to be used for shower profile evaluation
RawClusterBuilderTemplateFEMC.cc(h): minor modifications to calculate "prob" using class BEmcProfile

Clusterizer

---

generators/PHPythia6/PHPythia6.cc
generators/PHPythia8/PHPythia8.cc

This PR adds a printout of the seeds used for pythia6 and pythia8 so results can be reproduced

Print seed for pythia6 and pythia8

---

generators/flowAfterburner/main.cc
generators/flowAfterburner/test.cc

This PR prepares our code for boost 1.70.0 (needs suppression of boost version specific benign warning to make it compile)

suppress known warning

---

offline/framework/phool/PHFlag.cc
offline/framework/phool/PHNodeIOManager.cc
offline/framework/phool/PHRawOManager.cc

This PR applies minor fixes, it's the result of getting this check into some weekly build with analysis of the build result

getting the include what you use into a regular build

---

generators/PHPythia6/PHPythia6.cc
generators/PHPythia8/PHPythia8.cc
generators/PHSartre/PHSartre.cc
generators/flowAfterburner/main.cc
offline/packages/intt/InttClusterizer.cc
offline/packages/intt/InttClusterizer.h
offline/packages/mvtx/MvtxClusterizer.cc
offline/packages/mvtx/MvtxClusterizer.h
offline/packages/tpc/TpcClusterizer.cc
simulation/g4simulation/g4mvtx/PHG4MvtxDetector.cc
simulation/g4simulation/g4mvtx/PHG4MvtxSubsystem.cc
simulation/g4simulation/g4tpc/PHG4TpcDetector.cc
simulation/g4simulation/g4tpc/PHG4TpcDigitizer.cc

This PR fixes a few more include file issues and removes the phtimer from some sources.This functionality has been moved to Fun4All a long time ago:
https://wiki.bnl.gov/sPHENIX/index.php/Tools#How_long.3F

another test for include what you use

---

offline/database/pdbcal/pg/PgPostApplication.cc
offline/database/pdbcal/pg/PgPostApplication.h
offline/database/pdbcal/pg/PgPostBankBackupLog.h
offline/database/pdbcal/pg/PgPostBankBackupManager.cc
offline/database/pdbcal/pg/PgPostBankBackupManager.h
offline/database/pdbcal/pg/PgPostBankBackupStorage.cc
offline/database/pdbcal/pg/PgPostBankBackupStorage.h
offline/database/pdbcal/pg/PgPostBankManager.cc
offline/database/pdbcal/pg/PgPostBankManager.h
offline/database/pdbcal/pg/PgPostBankWrapper.cc
offline/database/pdbcal/pg/PgPostBankWrapper.h
offline/database/pdbcal/pg/PgPostBankWrapperManager.h
offline/database/pdbcal/pg/PgPostCalBank.h
offline/database/pdbcal/pg/PgPostCalBankIterator.cc
offline/database/pdbcal/pg/PgPostCalBankIterator.h
offline/database/pdbcal/pg/RunToTimePg.cc
offline/database/pdbcal/pg/RunToTimePg.h

This PR fixed up offline/database/pdbcal/pg

replace auto_ptr by C++11 unique_ptr, fix include files, adjust include guard names

---

offline/packages/PHGenFitPkg/PHGenFit/Track.h
offline/packages/trackbase_historic/SvtxTrack.h
offline/packages/trackbase_historic/SvtxTrack_v1.cc
offline/packages/trackbase_historic/SvtxTrack_v1.h
offline/packages/trackreco/CellularAutomaton_v1.cc
offline/packages/trackreco/PHGenFitTrkFitter.cc
offline/packages/trackreco/PHGenFitTrkFitter.h
offline/packages/trackreco/PHGenFitTrkProp.cc
offline/packages/trackreco/PHGenFitTrkProp.h
offline/packages/trackreco/PHHoughSeeding.cc
offline/packages/trackreco/PHHoughSeeding.h
offline/packages/trackreco/PHInitZVertexing.cc
offline/packages/trackreco/PHInitZVertexing.h
offline/packages/trackreco/PHTruthVertexing.cc
simulation/g4simulation/g4eval/SvtxEvalStack.h
simulation/g4simulation/g4eval/SvtxEvaluator.cc
simulation/g4simulation/g4eval/SvtxEvaluator.h
simulation/g4simulation/g4eval/SvtxVertexEval.cc
simulation/g4simulation/g4eval/SvtxVertexEval.h

Changes to enable handling of multiple collision vertices per event throughout the tracking. See presentation at September 3, 2019 Simulations Meeting for details. 
Still needs a bit of tuning of parameters for the initial Z vertexing and the RAVE vertexing.

Multiple vertexing

---

simulation/g4simulation/g4main/PHG4Reco.cc

This PR adds the ALICE preferred physics list (from G4 10.05 on, do not use for our current default 10.02)

Add FTFP and QGSP + Intranuclear cascade physics lists (HP and non HP versions)

---

offline/packages/CaloReco/BEmcProfile.cc
offline/packages/CaloReco/RawClusterBuilderTemplateFEMC.cc

This PR fixes a static memory leak I came across. The dtor for array deletion was also wrong (missing [])

Fix memleak

---

simulation/g4simulation/g4main/PHG4Reco.cc
simulation/g4simulation/g4main/PHG4Utils.cc

This PR just adds the QGSP INCLXX physics lists (HP and non HP) I forgot to add last time. It removes the old LHEP physics list which was removed starting with G4 version 10

Add qgsp inclxx

---

simulation/g4simulation/g4jleic/G4JLeicBeamLineMagnetDetector.cc
simulation/g4simulation/g4jleic/G4JLeicBeamLineMagnetDetector.h
simulation/g4simulation/g4jleic/G4JLeicBeamLineMagnetDisplayAction.cc
simulation/g4simulation/g4jleic/G4JLeicBeamLineMagnetDisplayAction.h
simulation/g4simulation/g4jleic/G4JLeicBeamLineMagnetSteppingAction.cc
simulation/g4simulation/g4jleic/G4JLeicBeamLineMagnetSteppingAction.h
simulation/g4simulation/g4jleic/G4JLeicBeamLineMagnetSubsystem.cc
simulation/g4simulation/g4jleic/G4JLeicBeamLineMagnetSubsystem.h
simulation/g4simulation/g4jleic/G4JLeicBeamLineMagnetSubsystemLinkDef.h
simulation/g4simulation/g4jleic/G4JLeicDIRCDetector.h
simulation/g4simulation/g4jleic/G4JLeicVTXSubsystem.cc
simulation/g4simulation/g4jleic/Makefile.am

This PR adds the jleic beamline magnets, basically cylinders with a dipole or quad field in the inner cylinder

Add Jleic beamline magnets

---

offline/packages/PHGenFitPkg/PHGenFit/PlanarMeasurement.cc
offline/packages/PHGenFitPkg/PHGenFit/PlanarMeasurement.h
offline/packages/intt/InttClusterizer.cc
offline/packages/intt/InttHit.cc
offline/packages/jetbackground/RetowerCEMC.cc
offline/packages/jetbackground/TowerBackgroundv1.h
offline/packages/tpc/TpcHit.cc
offline/packages/trackreco/PHTruthTrackSeeding.h
offline/packages/trigger/CaloTriggerSim.cc
simulation/g4simulation/g4decayer/P6DExtDecayerPhysics.cc
simulation/g4simulation/g4decayer/P6DExtDecayerPhysics.hh
simulation/g4simulation/g4detectors/PHG4ConeDetector.cc
simulation/g4simulation/g4detectors/PHG4EICForwardEcalDetector.cc
simulation/g4simulation/g4detectors/PHG4FPbScDetector.cc
simulation/g4simulation/g4detectors/PHG4ForwardEcalDetector.cc
simulation/g4simulation/g4detectors/PHG4ForwardEcalDetector.h
simulation/g4simulation/g4detectors/PHG4ForwardEcalSubsystem.cc
simulation/g4simulation/g4main/PHG4ScoringManager.cc
simulation/g4simulation/g4mvtx/PHG4MvtxSteppingAction.cc

2 classes did not compile with G4 10.06 (P6DExtDecayerPhysics.cc and PHG4ScoringManager.cc). Both needed a check on the G4 version to make them work with our previous G4 versions.
Some minor include shuffling following recommendations from include what you use

Fix g4 10 6

---

offline/packages/trackreco/PHGenFitTrkFitter.h
offline/packages/trackreco/PHInitZVertexing.cc
offline/packages/trackreco/PHTrackFitting.cc
offline/packages/trackreco/PHTrackPropagating.cc
offline/packages/trackreco/PHTrackPropagating.h
offline/packages/trackreco/PHTrackSeeding.cc
simulation/g4simulation/g4eval/SvtxEvaluator.h

setters of SvtxTrackMap names now fully functional and tested.

next step towards iterative tracking

---

offline/packages/trackreco/PHGenFitTrkFitter.h

This PR hides phgenfit/Track.h from rootcint

root5 rootcint did not like the previous change, need to hide include

---

offline/QA/modules/Makefile.am
offline/QA/modules/QAG4SimulationTracking.cc
offline/QA/modules/QAG4SimulationTracking.h
offline/QA/modules/QAG4SimulationTrackingLinkDef.h

New modules with preliminary QA for tracking. Creates histograms with #events, #recotracks, reco/truth pt, and truth pt / #reco tracks plotted at truth pt (for efficiency plots).

QA tracking

---

offline/packages/mvtx/CylinderGeom_Mvtx.cc
offline/packages/mvtx/CylinderGeom_Mvtx.h
offline/packages/mvtx/Makefile.am
offline/packages/mvtx/MvtxClusterizer.cc
offline/packages/mvtx/SegmentationAlpide.cc
offline/packages/mvtx/SegmentationAlpide.h
offline/packages/mvtx/SegmentationAlpideLinkDef.h
simulation/g4simulation/g4mvtx/PHG4MvtxDefs.h
simulation/g4simulation/g4mvtx/PHG4MvtxDetector.cc
simulation/g4simulation/g4mvtx/PHG4MvtxDetector.h
simulation/g4simulation/g4mvtx/PHG4MvtxHitReco.cc
simulation/g4simulation/g4mvtx/PHG4MvtxSubsystem.cc
simulation/g4simulation/g4mvtx/PHG4MvtxSubsystem.h

This PR fixes the compilation crash under root5 for Yassers code

Ycorrales new mvtx sim

---

simulation/g4simulation/g4eval/CaloEvaluator.cc
simulation/g4simulation/g4eval/CaloEvaluator.h
simulation/g4simulation/g4trackfastsim/PHG4TrackFastSim.cc

Described on slides 11 and 12 here:
https://indico.bnl.gov/event/7399/contributions/34257/attachments/26399/39954/sphenix_012820.pdf

Changed track projection location for planar EM calorimeters

---

offline/packages/intt/CylinderGeomIntt.cc
offline/packages/intt/CylinderGeomIntt.h
offline/packages/intt/InttClusterizer.cc
offline/packages/mvtx/CylinderGeom_Mvtx.cc
offline/packages/mvtx/CylinderGeom_Mvtx.h
offline/packages/mvtx/MvtxClusterizer.cc
offline/packages/trackreco/Makefile.am
offline/packages/trackreco/PHActsTrkFitter.cc
offline/packages/trackreco/PHActsTrkFitter.h
offline/packages/trackreco/PHActsTrkFitterLinkDef.h
offline/packages/trackreco/PHTrackFitting.h
offline/packages/trackreco/configure.ac
simulation/g4simulation/g4intt/PHG4InttSteppingAction.cc
simulation/g4simulation/g4intt/PHG4InttSubsystem.cc
simulation/g4simulation/g4mvtx/PHG4MvtxDetector.cc
simulation/g4simulation/g4mvtx/PHG4MvtxSubsystem.cc

Adds module PHActsTrkFitter to offline/packages/trackreco. Includes accompanying changes to packages/mvtx and packages/intt. Implements Acts geometry building from within Fun4All, and creates Acts measurements for the sPHENIX MVTX, INTT and TPC. Built and tested against the new build.

Acts implementation

---

offline/packages/trackreco/PHActsTrkFitter.cc

Now aborts if layergeom not found!

Fix nullptr check

---

offline/packages/trackreco/PHActsTrkFitter.cc
offline/packages/trackreco/PHActsTrkFitter.h
offline/packages/trackreco/PHGenFitTrkProp.cc
offline/packages/trackreco/TrkrClusterSourceLink.hpp

Implement code that prepares all containers for calling the Acts track fitter. Next up: figure out how to call acts track fitting

Prepare Track Fitting

---

offline/packages/trackreco/PHActsTrkFitter.cc
offline/packages/trackreco/PHActsTrkFitter.h
offline/packages/trackreco/TrkrClusterSourceLink.hpp

Added TPC surface from 100-110 cm in Z to handle occasional clusters that have Z > 100.

Surface bug fix

---

simulation/g4simulation/g4trackfastsim/PHG4TrackFastSim.cc
simulation/g4simulation/g4trackfastsim/PHG4TrackFastSim.h

This PR just adds DisplayEvent() to PHG4TrackFastSim so it can be called from the cmd line. Currently the display is only called at the End(). The storing of tracks only works very limited - it crashes when going back more than 2 events. In general this is rather unstable

Display genfit

---

offline/packages/trackreco/ActsFittingAlgorithm.h
offline/packages/trackreco/PHActsTrkFitter.cc
offline/packages/trackreco/PHActsTrkFitter.h
offline/packages/trackreco/TrkrClusterSourceLink.hpp

This PR introduces the necessary foundation for calling the Acts track fitting using sPHENIX clusters and track seeds. There is still work to be done as the Kalman Fitter within Acts can't find the TrackingGeometry object (unsure why at the moment), but I'm pushing this code now so that there is a stable copy in the master repository that can successfully call the track fitting without any sPHENIX issues.
Still on the table is debugging the issues within Acts as to why the TrackingGeometry object can't be accessed.

Acts Track Fitting

---

offline/framework/fun4all/CreateSubsysRecoModule.pl

The previous printouts drowned in other messages in the dryrun macro. More visible and explicit now

make printouts more visible, adding method to printout

---

simulation/g4simulation/g4detectors/CreateG4Subsystem.pl

This PR just modifies the CreateG4Subsystem.pl script. I will merge this before the tests are finished

the script now adds more comments to the sources

---

offline/framework/fun4all/CreateSubsysRecoModule.pl

This should give enough info in the source file on how to use this

put more comments into source file

---

offline/packages/PHField/Makefile.am
offline/packages/PHField/PHField2D.cc
offline/packages/PHField/PHField3DCartesian.cc
offline/packages/PHField/PHField3DCylindrical.cc
offline/packages/PHField/PHFieldBeast.cc
offline/packages/PHField/PHFieldBeast.h
offline/packages/PHField/PHFieldConfig.cc
offline/packages/PHField/PHFieldConfig.h
offline/packages/PHField/PHFieldConfigv1.cc
offline/packages/PHField/PHFieldConfigv1.h
offline/packages/PHField/PHFieldConfigv2.h
offline/packages/PHField/PHFieldUniform.cc
offline/packages/PHField/PHFieldUtility.cc
simulation/g4simulation/g4gdml/Makefile.am
simulation/g4simulation/g4main/PHG4Reco.cc
simulation/g4simulation/g4main/PHG4Reco.h

This PR adds the fieldmap for the Beast magnet - not that we want to use it, it is for the eic

Beast magnet

---

simulation/g4simulation/g4detectors/BeamLineMagnetDetector.cc
simulation/g4simulation/g4detectors/BeamLineMagnetDetector.h
simulation/g4simulation/g4detectors/BeamLineMagnetDisplayAction.cc
simulation/g4simulation/g4detectors/BeamLineMagnetDisplayAction.h
simulation/g4simulation/g4detectors/BeamLineMagnetSteppingAction.cc
simulation/g4simulation/g4detectors/BeamLineMagnetSteppingAction.h
simulation/g4simulation/g4detectors/BeamLineMagnetSubsystem.cc
simulation/g4simulation/g4detectors/BeamLineMagnetSubsystem.h
simulation/g4simulation/g4detectors/BeamLineMagnetSubsystemLinkDef.h
simulation/g4simulation/g4detectors/Makefile.am

This PR adds more sophisticated beam line magnets than the PHG4BeamLineMagnet class

Add beamline magnets

---

simulation/g4simulation/g4main/PHG4HitEval.cc
simulation/g4simulation/g4main/PHG4HitEval.h
simulation/g4simulation/g4main/PHG4Reco.cc
simulation/g4simulation/g4main/PHG4Utils.cc

So far out default was a solenoidal field of 1.4T which since the arrival of a fieldmap did not make sense but confused everyone. This PR initializes our field to 0 T

Magnetic field default zero

---

offline/packages/trackreco/Makefile.am
offline/packages/trackreco/PHActsTrkFitter.cc
offline/packages/trackreco/PHActsTrkProp.h
offline/packages/trackreco/configure.ac
simulation/g4simulation/g4mvtx/PHG4MvtxHitReco.cc
simulation/g4simulation/g4mvtx/PHG4MvtxSteppingAction.cc
simulation/g4simulation/g4tpc/PHG4TpcElectronDrift.cc

This PR introduces small changes into the Acts track fitting class and the Makefile/configure files to enable building with the new Acts github repository.
This PR is expected to fail the CI by default, since the CI is not yet configured for the new acts github repo. We can address that once everything gets tested as Chris is working on getting the nightly builds setup with the acts github repo.

Changes for new Acts repository

---

simulation/g4simulation/g4main/HepMCNodeReader.cc
simulation/g4simulation/g4main/ReadEICFiles.cc

simple commit to ease future debugging

Add read eic files & hep mc verbosity

---

simulation/g4simulation/g4detectors/PHG4CrystalCalorimeterSubsystem.cc
simulation/g4simulation/g4detectors/PHG4RICHDetector.cc
simulation/g4simulation/g4detectors/PHG4SectorConstructor.cc
simulation/g4simulation/g4detectors/PHG4SectorConstructor.h
simulation/g4simulation/g4detectors/ePHENIXRICHConstruction.cc

This PR puts all those printouts of detector geometries behind a verbosity flag. The Rich now has a dedicated REGION_RICH G4Region initialized with the default cuts

Stop blabbering

---

simulation/g4simulation/g4main/EicEventHeader.cc
simulation/g4simulation/g4main/EicEventHeader.h
simulation/g4simulation/g4main/EicEventHeaderLinkDef.h
simulation/g4simulation/g4main/EicEventHeaderv1.cc
simulation/g4simulation/g4main/EicEventHeaderv1.h
simulation/g4simulation/g4main/EicEventHeaderv1LinkDef.h
simulation/g4simulation/g4main/Makefile.am
simulation/g4simulation/g4main/ReadEICFiles.cc
simulation/g4simulation/g4main/ReadEICFiles.h

This PR adds the first version of the Eic Generator event header which stored event wise information for the eic event generators (currently Milou). It uses the property map scheme from PHG4Hit to store various generator outputs in the same class

Eic event header

---

offline/packages/PHTpcTracker/externals/nanoflann.hpp
simulation/g4simulation/g4trackfastsim/PHG4TrackFastSimEval.cc
simulation/g4simulation/g4trackfastsim/PHG4TrackFastSimEval.h

This PR adds the projections and hits/momenta of reference planes/cylinders to the evaluation TTree

Add projections

---

offline/packages/mvtx/MvtxClusterizer.cc

correct local hit position inside sensor before including into cluster, to account for diffusion process.
Correction has been updated to account for thresholds added by Zhengyun at the digitizer level.
Resulting residuals.
Before: 
[DeltaRPhi_cluster_2k_realistic_full_zhengyun.pdf](https://github.com/sPHENIX-Collaboration/coresoftware/files/4703748/DeltaRPhi_cluster_2k_realistic_full_zhengyun.pdf)
[DeltaZBeta_cluster_2k_realistic_full_zhengyun.pdf](https://github.com/sPHENIX-Collaboration/coresoftware/files/4703760/DeltaZBeta_cluster_2k_realistic_full_zhengyun.pdf)
after
[DeltaRPhi_cluster_2k_realistic_full_zhengyun_fix3.pdf](https://github.com/sPHENIX-Collaboration/coresoftware/files/4703749/DeltaRPhi_cluster_2k_realistic_full_zhengyun_fix3.pdf) …

correct local hit position in mvtx for clustering

---

offline/QA/modules/QAG4SimulationIntt.cc
offline/QA/modules/QAG4SimulationIntt.h
offline/QA/modules/QAG4SimulationMvtx.cc
offline/QA/modules/QAG4SimulationMvtx.h
offline/QA/modules/QAG4SimulationTracking.cc
offline/QA/modules/QAG4SimulationTracking.h
offline/QA/modules/QAG4SimulationUpsilon.cc
offline/QA/modules/QAG4SimulationUpsilon.h
offline/QA/modules/QAHistManagerDef.cc
offline/QA/modules/QAHistManagerDef.h
offline/framework/fun4all/Fun4AllHistoManager.cc
offline/framework/fun4all/Fun4AllHistoManager.h
offline/framework/fun4all/Fun4AllServer.cc
offline/framework/fun4all/Fun4AllServer.h
offline/framework/fun4all/Fun4AllSyncManager.cc
offline/framework/fun4all/Fun4AllSyncManager.h
offline/framework/fun4all/TDirectoryHelper.cc
offline/framework/fun4all/TDirectoryHelper.h
simulation/g4simulation/g4main/EicEventHeaderv1.cc
simulation/g4simulation/g4main/EicEventHeaderv1.h
simulation/g4simulation/g4main/Fun4AllMessenger.cc

This PR replaces the last holdouts of the const char * interface by std::string &
Also fixed some sources which included larger numbers of not needed include files

Fix fun4all

---

offline/packages/trackreco/Makefile.am
offline/packages/trackreco/PHActsTrkProp.cc

Small changes to makefile to conform with latest acts version, which will be pushed into the sPHENIX-acts repo shortly.

Small changes to conform with acts latest version

---

offline/packages/trackreco/PHGenFitTrkProp.cc
offline/packages/trackreco/PHGenFitTrkProp.h

With this fix PHGenFitTrkProp has the same fit performance as PHGenFitTrkFitter.

TrackProp fix

---

generators/PHPythia8/PHPythia8.cc
generators/PHPythia8/PHPythia8.h
simulation/g4simulation/g4main/G4TBMagneticFieldSetup.cc
simulation/g4simulation/g4main/PHG4Detector.cc
simulation/g4simulation/g4main/PHG4DisplayAction.cc
simulation/g4simulation/g4main/PHG4EtaParameterization.cc
simulation/g4simulation/g4main/PHG4SimpleEventGenerator.cc
simulation/g4simulation/g4main/PHG4SimpleEventGenerator.h
simulation/g4simulation/g4main/PHG4TruthTrackingAction.cc
simulation/g4simulation/g4main/PHG4UIsession.cc

This PR replaces another const char * interface by const string &, the simple particle generator did not print out the momentum setting correctly if momentum range instead of pt range was chosen. A bunch of missing include files added

Pythia8 no const char

---

generators/PHSartre/PHSartre.h
simulation/g4simulation/g4main/PHG4ParticleGeneratorVectorMeson.cc
simulation/g4simulation/g4main/PHG4ParticleGeneratorVectorMeson.h

This PR replaces yet another const char * interface by const string &

Const char to string phsartre

---

offline/packages/PHTpcTracker/Makefile.am

The latest macro change in G4_Tracking.C needs this include

install PHTpcTracker.h

---

offline/packages/trackreco/PHGenFitTrkFitter.cc

This PR fixes rare but annoying crashes (about 1 out of 5000 single particle events) when using genfit to extrapolate tracks state vectors to disabled layers. Whenever extrapolation fails GenFit was throwing an exception, which, uncaught was resulting in fun4all termination
Added proper try/catch blocks fixes that.
This does not affects normal reconstruction, for which there is no disabled layers. 
Similar exceptions thrown elsewhere in the code (in the trackfit) are caught already using the same construct.

Fix rare crashes in PHGenFitTrkFit 

---

offline/QA/modules/QAG4SimulationTracking.cc

DCA histograms for rPhi and Z added to compiled code for SimulationTracking file

Adding DCA histograms

---

offline/packages/micromegas/MicromegasClusterizer.cc

Code inspired from TPC Gems, with extra normalization factors to have pull's width at unity

Implemented proper cluster error calculations

---

offline/packages/CaloReco/RawTowerCalibration.cc
offline/packages/CaloReco/RawTowerCalibration.h

[https://indico.bnl.gov/event/7423/](url) from zero suppression presentation.

Removed redundant zero suppression by GeV

---

offline/QA/modules/QAG4SimulationTracking.cc
offline/QA/modules/QAG4SimulationTracking.h

Histograms for tracking purity reco track truth matching ratio created

Tracking purity histograms added

---

simulation/g4simulation/g4micromegas/PHG4MicromegasHitReco.cc
simulation/g4simulation/g4micromegas/PHG4MicromegasHitReco.h

see https://indico.bnl.gov/event/8548/contributions/37753/attachments/28212/43343/2020_05_Proposal_sPhenixMonitoring_update_19052020.pptx
slide 10

added realistic timing window [0,800ns]

---

simulation/g4simulation/g4tpc/PHG4TpcElectronDrift.cc

Diffusion and drift velocity numbers from http://skipper.physics.sunysb.edu/~prakhar/tpc/HTML_Gases/split.html
(Thanks Ross !)

Change TPC gas properties to Ne/CF4 50/50

---

simulation/g4simulation/g4epd/Makefile.am
simulation/g4simulation/g4epd/PHG4EPDSubsystem.cc
simulation/g4simulation/g4epd/PHG4EPDSubsystem.h
simulation/g4simulation/g4epd/PHG4EPDetector.cc
simulation/g4simulation/g4epd/PHG4EPDetector.h
simulation/g4simulation/g4epd/PHG4EPSteppingAction.cc
simulation/g4simulation/g4epd/PHG4EPSteppingAction.h
simulation/g4simulation/g4epd/autogen.sh
simulation/g4simulation/g4epd/configure.ac

this is based on the design of the STAR EPD. the geant4 model is built using extruded solids (1 per scintillator tile), with coordinates from Prashanth, who worked on the STAR EPD.

first version of event plane detector

---

simulation/g4simulation/g4epd/PHG4EPSteppingAction.cc

always save geantino hits and set their energy deposits to -1, following examples for other detector systems..

g4epd: handle geantinos in stepping action

---

offline/packages/trackreco/PHActsTrkFitter.cc
offline/packages/trackreco/PHActsTrkFitter.h

This PR adds some histograms/analysis for doing timing analysis with the Acts KF. The behavior can be turned off at the macro level and is off by default.

Acts KF Timing Additions

---

offline/framework/fun4all/CreateSubsysRecoModule.pl
simulation/g4simulation/g4detectors/CreateG4Subsystem.pl

This PR removes the using namespace std from the templates, so new users are steered in the right direction

No std namespace create scripts

---

generators/phhepmc/Fun4AllHepMCInputManager.cc
generators/phhepmc/Fun4AllHepMCInputManager.h
generators/phhepmc/Fun4AllHepMCPileupInputManager.cc
generators/phhepmc/Fun4AllHepMCPileupInputManager.h
generators/phhepmc/PHHepMCGenHelper.cc
generators/phhepmc/PHHepMCGenHelper.h
offline/database/PHParameter/Makefile.am
offline/database/PHParameter/PHParameters.cc
offline/database/PHParameter/configure.ac

This PR adds the correct pushing back of events in case of another input manager failing. Also the skipping had a flaw and did not work.

Fix hepmc pileup sync

---

offline/framework/fun4allraw/Fun4AllEventOutStream.h
offline/framework/fun4allraw/Fun4AllPrdfInputManagerLinkDef.h
offline/framework/fun4allraw/Fun4AllPrdfOutputManagerLinkDef.h
offline/framework/fun4allraw/Makefile.am
offline/framework/fun4allraw/configure.ac
simulation/g4simulation/g4histos/G4CellNtupleLinkDef.h
simulation/g4simulation/g4histos/G4EdepNtupleLinkDef.h
simulation/g4simulation/g4histos/G4HitNtupleLinkDef.h
simulation/g4simulation/g4histos/G4HitTTreeLinkDef.h
simulation/g4simulation/g4histos/G4RawTowerTTreeLinkDef.h
simulation/g4simulation/g4histos/G4ScintillatorSlatTTreeLinkDef.h
simulation/g4simulation/g4histos/G4ScintillatorTowerTTreeLinkDef.h
simulation/g4simulation/g4histos/G4SnglNtupleLinkDef.h
simulation/g4simulation/g4histos/G4SnglTreeLinkDef.h
simulation/g4simulation/g4histos/G4TowerNtupleLinkDef.h
simulation/g4simulation/g4histos/Makefile.am

This PR should just trigger jenkins to see if the changed G4_Tracking.C macro works in the tests

Remove root5 g4histos

---

offline/framework/fun4all/Fun4AllMemoryTracker.cc
offline/framework/fun4all/Fun4AllServer.cc
offline/framework/phool/PHTimer.h
offline/packages/particleflow/Makefile.am
offline/packages/particleflow/ParticleFlowReco.cc
offline/packages/particleflow/ParticleFlowReco.h

This PR prints the timing info in a single line for easier parsing of the logs. Also removed printouts from particleflowreco and uses gsl instead of TRandom, uses seed now from PHRandomSeed to make it reproducible

Timer printout

---

offline/framework/fun4all/Fun4AllDstInputManager.cc
offline/framework/fun4all/Fun4AllDstOutputManager.cc
offline/framework/fun4all/Fun4AllDstOutputManager.h
offline/framework/fun4all/Fun4AllDummyInputManager.cc
offline/framework/fun4all/Fun4AllDummyInputManager.h
offline/framework/fun4all/Fun4AllInputManager.cc
offline/framework/fun4all/Fun4AllInputManager.h
offline/framework/fun4all/Fun4AllMemoryTracker.cc
offline/framework/fun4all/Fun4AllNoSyncDstInputManager.h
offline/framework/fun4all/Fun4AllOutputManager.h
offline/framework/fun4all/Fun4AllReturnCodes.h
offline/framework/fun4all/Fun4AllServer.cc
offline/framework/fun4all/Fun4AllSyncManager.cc
offline/framework/fun4all/Fun4AllUtils.cc
offline/framework/fun4all/Fun4AllUtils.h
offline/framework/fun4all/PHTFileServer.cc
offline/framework/phool/PHNodeIterator.cc
offline/framework/phoolraw/PHRawDataNode.cc

This PR adds the capability to select which runwise nodes should be saved. This way we don't have to save everything every time.

Add runnode select

---

offline/packages/trackreco/PHCASeeding.cc
offline/packages/trackreco/PHCASeeding.h

CA seeder now checks to see if the SvtxTrack parameters are not NaN before adding them to the track map, just in case.

CA seeding NaN checking

---

offline/packages/trackreco/PHCASeeding.cc

Re-adding Tony's fix for track seed charge after it was accidentally deleted.

Fixing track seed charge issue

---

offline/packages/trackreco/PHActsTrkFitter.cc
offline/packages/trackreco/PHActsTrkFitter.h

Somehow some timing verbosity statements escaped me previously - this adds them in.

Add finer verbosity statements

---

offline/packages/trackreco/PHCASeeding.cc

Hopefully resolves timing problems caused by file I/O issues. Also, nobody was using this Ntuple anyway.

Removed output Ntuple from CA seeding

---

offline/packages/CaloBase/RawTower.h
offline/packages/CaloBase/RawTowerGeomContainer.h
offline/packages/CaloBase/RawTowerGeomContainer_Cylinderv1.cc
offline/packages/CaloBase/RawTowerGeomContainer_Cylinderv1.h
simulation/g4simulation/g4histos/G4EdepNtuple.cc
simulation/g4simulation/g4histos/G4HitNtuple.cc
simulation/g4simulation/g4histos/G4HitTTree.cc
simulation/g4simulation/g4histos/G4RawTowerTTree.cc
simulation/g4simulation/g4histos/G4ScintillatorSlatTTree.cc
simulation/g4simulation/g4histos/G4ScintillatorTowerTTree.cc
simulation/g4simulation/g4histos/G4SnglNtuple.cc
simulation/g4simulation/g4histos/G4SnglTree.cc
simulation/g4simulation/g4histos/G4TowerNtuple.cc

Our calo geometries need to return theta in addition to eta for real lab coordinates. This PR implements that interface for our cylinder geometries

Add theta to calogeo

---

offline/packages/trackreco/PHActsTracks.cc
offline/packages/trackreco/PHActsTracks.h
offline/packages/trackreco/PHActsTrkFitter.cc
offline/packages/trackreco/PHTruthTrackSeeding.cc

This PR modifies the truth seeding module to prepare an SvtxTrack instance that is suitable for Acts to fit.

Acts truth seeding

---

offline/framework/ffamodules/SyncReco.cc
offline/framework/ffamodules/SyncReco.h
offline/framework/ffaobjects/SyncDefs.h
offline/framework/fun4all/Fun4AllDstInputManager.cc
offline/framework/fun4all/Fun4AllDummyInputManager.cc

This PR puts the syncing back together - the branch delimeter had changed, now it's all taken from include files

Fix input managers

---

offline/packages/trackreco/MakeActsGeometry.cc
offline/packages/trackreco/PHActsSourceLinks.cc
offline/packages/trackreco/PHActsSourceLinks.h
offline/packages/trackreco/PHActsTracks.cc
offline/packages/trackreco/PHActsTrkFitter.cc

This PR fixes some memory leaks as reported from valgrind and Chris in the Acts tracking chain. The definite leaks are fixed with smart pointers.

Fix memory leaks

---

generators/sHijing/Hijing.cxx

the PR adds a little parser so we can set a few things from the cmd line instead of modifying the xml file

sHijing cmdparser

---

generators/FermiMotionAfterburner/FermiMotion.cc
generators/FermiMotionAfterburner/FermimotionAfterburner.cc
generators/FermiMotionAfterburner/FermimotionAfterburner.h
generators/FermiMotionAfterburner/configure.ac
generators/flowAfterburner/flowAfterburner.cc

This PR adds a check for the heavy ion record so it does not crash on pythia. Remove printouts and install include in subdir for Fermi Motion

Fix fermi flow

---

offline/QA/modules/QAG4SimulationVertex.cc
offline/QA/modules/QAG4SimulationVertex.h
offline/packages/trackreco/PHRaveVertexing.h

Following meeting today: allowing QA module to select a vertex map

Allow QA module to select a vertex map

---

offline/QA/modules/QAG4SimulationVertex.cc
offline/QA/modules/QAG4SimulationVertex.h

Fix node handling in the QA module

Allow QA module to select a vertex map #993 try-2

---

offline/packages/particleflow/ParticleFlowReco.cc

Thanks @blackcathj for catching this!

Add missing verbosity filter

---

offline/packages/trackreco/PHCASeeding.cc
offline/packages/trackreco/PHCASeeding.h

These changes should close a few small memory leaks that valgrind found.

[CA Seeding] Removed TNtuple and converted PHTimers to smart pointers

---

offline/packages/trackreco/PHActsVertexFinder.cc
offline/packages/trackreco/PHActsVertexFinder.h
simulation/g4simulation/g4eval/SvtxEvaluator.cc

This PR cleans up memory leaks in the acts vertex finder

Acts Vertex Finder Memory

---

.github/pull_request_template.md

Introduce template for pull request descriptions, which consists of one multi-choice section on general feature and a description section. This template also encourage linking to the macro and repository pull request to help sync the updates when merging
None

Introduce the pull request template for better documentation

---

generators/PHPythia8/PHPy8ParticleTrigger.cc
generators/PHPythia8/PHPy8ParticleTrigger.h

Allow for triggering on unstable particles in Pythia8 records and cut on rapidity 
Start HF MDC1
https://github.com/sPHENIX-Collaboration/MDC1/pull/6

Pythia Trigger update in preparation for MDC HF production jobs

---

offline/packages/KFParticle_sPHENIX/Makefile.am
simulation/g4simulation/g4detectors/PHG4CrystalCalorimeterDetector.cc

I accidentally added the dictionary to both libraries which leads to a startup message about a class already being added

Fix class message

---

offline/QA/modules/QAG4SimulationCalorimeter.cc
offline/QA/modules/QAG4SimulationCalorimeter.h
offline/QA/modules/QAG4SimulationCalorimeterSum.cc
offline/QA/modules/QAG4SimulationCalorimeterSum.h
offline/QA/modules/QAG4SimulationIntt.cc
offline/QA/modules/QAG4SimulationMvtx.cc
offline/QA/modules/QAG4SimulationTpc.cc
offline/QA/modules/QAG4SimulationTpc.h

Please ignore build errors in this thread. 
The interface between the [sPHENIX Jenkins Continuous Integration](https://web.sdcc.bnl.gov/jenkins-sphenix/) and GitHub is being upgrade from a [robotic account](https://github.com/sPHENIX-bot) to a new GitHub App: https://github.com/apps/sphenix-jenkins-ci
This [app](https://github.com/apps/sphenix-jenkins-ci) will allow us to use newest CI features at GitHub, such as [Checks API](https://docs.github.com/en/free-pro-team@latest/rest/reference/checks). It also allow for better maintenance, …

Dummy pull request for Jenkins CI development as a new GitHub App

---

offline/framework/frog/CreateFileList.pl

This adds pythia8 files from the mdc to the selection of GetFIleList.pl

Add pythia8 files to selection

---

offline/database/PHParameter/PHParameters.cc
offline/framework/ffamodules/HeadReco.cc
offline/framework/ffamodules/SyncReco.cc
offline/framework/ffaobjects/EventHeader.h
offline/framework/ffaobjects/EventHeaderv1.cc
offline/framework/ffaobjects/EventHeaderv1.h
offline/framework/ffaobjects/EventHeaderv2.h
offline/framework/ffaobjects/RunHeader.h
offline/framework/ffaobjects/RunHeaderv1.cc
offline/framework/frog/CreateFileList.pl

This PR reorganizes the creating of file lists. It uses one parameter -type to select the production (hijing 0-12fm, hijing 0-4.88fm or pythia8 pp mb) rather than living with competing parameters for hijing and pythia. With -r one gets randomly selected segments (for a given number of events) so you don't have to always run the same events.
Fixed some not needed includes, added needed ones as identified by include what you use:
https://wiki.bnl.gov/sPHENIX/index.php/Tools#Include_What_You_Use …

Randomize segments

---

offline/QA/modules/QAG4SimulationJet.cc
offline/QA/modules/QAG4SimulationJet.h
offline/QA/modules/QAG4SimulationTracking.cc
offline/QA/modules/QAG4SimulationUpsilon.cc
offline/QA/modules/QAG4SimulationUpsilon.h
offline/QA/modules/QAG4SimulationVertex.cc
offline/QA/modules/QAG4Util.h
offline/packages/CaloBase/RawCluster.h
offline/packages/CaloBase/RawClusterDefs.h
offline/packages/CaloBase/RawClusterv1.cc
offline/packages/CaloBase/RawClusterv1.h
offline/packages/CaloBase/RawTowerDefs.h
offline/packages/CaloBase/RawTowerGeom.h
offline/packages/CaloBase/RawTowerGeomContainer_Cylinderv1.cc
offline/packages/CaloBase/RawTowerGeomv1.cc
offline/packages/CaloBase/RawTowerGeomv1.h
offline/packages/CaloBase/RawTowerGeomv3.cc
offline/packages/CaloBase/RawTowerGeomv3.h
offline/packages/CaloReco/RawTowerCalibration.cc
offline/packages/CaloReco/RawTowerCombiner.cc
offline/packages/CaloReco/RawTowerDeadMapLoader.cc
offline/packages/CaloReco/RawTowerDeadMapLoader.h
offline/packages/CaloReco/RawTowerDeadTowerInterp.cc
offline/packages/PHField/PHFieldCleo.cc
offline/packages/PHField/PHFieldUtility.cc

Please ignore build errors in this thread. 
QA checks has been broken since we migrated the default macro to the new setup, https://github.com/sPHENIX-Collaboration/macros/pull/262 
As QA modules was reintroduced in the new macro set ( https://github.com/sPHENIX-Collaboration/macros/pull/339 ), it is also been rebuilt on [sPHENIX Jenkins CI](https://web.sdcc.bnl.gov/jenkins-sphenix/). Besides the simulation macro moves, the plotting macros is being moved to using the [sPHENIX JupyterLab …

Dummy pull request for Jenkins CI development - Round 2 for rebuilding QA Checks

---

offline/framework/frog/CreateFileList.pl

This PR adds type 4 = hijing 0-20fm to CreateFileList.pl

add sHijing_0_20fm as type 4

---

simulation/g4simulation/g4eval/JetRecoEval.cc
simulation/g4simulation/g4eval/JetRecoEval.h
simulation/g4simulation/g4eval/PHG4DSTReader.cc
simulation/g4simulation/g4eval/SvtxEvalStack.h
simulation/g4simulation/g4eval/SvtxTrackEval.cc
simulation/g4simulation/g4eval/SvtxTrackEval.h
simulation/g4simulation/g4eval/SvtxVertexEval.cc
simulation/g4simulation/g4eval/SvtxVertexEval.h

This PR fixes the use of the jet evaluator for the eic tracking. The previous version has SvtxTrackMap hardcoded, now it also checks for the TrackMap node in case SvtxTrackMap is not found

Use eic trackmap

---

offline/packages/trackreco/GPUTPCTrackLinearisation.h
offline/packages/trackreco/Makefile.am
offline/packages/trackreco/PHCASeeding.cc
offline/packages/trackreco/PHCASeeding.h
offline/packages/trackreco/PHHybridSeeding.cc
offline/packages/trackreco/PHHybridSeeding.h

Introduces PHHybridSeeding module, which incorporates the STAR seeding core and the ALICE simplified Kalman filter.
https://github.com/sPHENIX-Collaboration/macros/pull/362

Hybrid TPC seeding module

---

offline/framework/frog/CreateFileList.pl

This PR adds the new pileup using 0-20fm background and fixes the mixing of those with 0-12fm pileup. It's just temporary until the renaming of the files is done

temporary patch till proper rename is done

---

offline/framework/frog/CreateFileList.pl

- [x ] Breaking change (fix or feature that would cause existing functionality to not work for users)
The MDC1 files needed a rename so we can distinguish different pileup rates or background centralities. The new CreateFileList.pl adheres to the new names

New mdc name scheme

---

offline/framework/frog/CreateFileList.pl

- [ x] Breaking change (fix or feature that would cause existing functionality to not work for users)
The 0-20fm files were renamed according to the new scheme. This needs an update for CreateFileList.pl. The new version is already copied to our cvmfs area, so we do not have to wait for the next build

use new naming scheme also for 0-20fm files

---

offline/packages/trackreco/PHActsTracks.cc
offline/packages/trackreco/PHActsTrkFitter.cc
offline/packages/trackreco/PHActsVertexFinder.cc

This PR enables the acts track fitting modules to be run a second time, which improves the DCA performance.

Track refit

---

simulation/g4simulation/g4detectors/PHG4ForwardEcalDetector.cc
simulation/g4simulation/g4detectors/PHG4ForwardEcalSteppingAction.cc

This PR strips a few unused variables from the FEMC hits. We do not need the ionization energy for the absorbers. The tower positions indices for the absorber were set to -1 and the scintillator id for absorber and scintillator was 0. Nothing in the downstream reconstruction code depends on these entries …

Fix forward calos

---

offline/packages/KFParticle_sPHENIX/KFParticle_DST.cc
offline/packages/KFParticle_sPHENIX/KFParticle_eventReconstruction.cc
offline/packages/KFParticle_sPHENIX/KFParticle_nTuple.cc
offline/packages/KFParticle_sPHENIX/KFParticle_nTuple.h
offline/packages/KFParticle_sPHENIX/KFParticle_sPHENIX.cc
offline/packages/KFParticle_sPHENIX/KFParticle_sPHENIX.h
offline/packages/KFParticle_sPHENIX/KFParticle_truthAndDetTools.cc
offline/packages/KFParticle_sPHENIX/KFParticle_truthAndDetTools.h

I noticed that ROOT TTrees can't handle branches with + or - symbols (you cant open them in a browser, I think macros can handle them...). To make life easier I put in some lines where these symbols will be replaced with words if they appear.
This change only affects the output options and will not change anything in the MDC production

KFParticle output name changes

---

offline/packages/trackreco/Makefile.am
offline/packages/trackreco/PHTruthTrackSeeding.cc
offline/packages/trackreco/PHTruthTrackSeeding.h
simulation/g4simulation/g4eval/SvtxClusterEval.cc
simulation/g4simulation/g4eval/SvtxClusterEval.h
simulation/g4simulation/g4eval/SvtxEvaluator.cc
simulation/g4simulation/g4eval/SvtxTrackEval.cc
simulation/g4simulation/g4eval/SvtxVertexEval.h

Cluster overlap based Truth Tracking update

---

simulation/g4simulation/g4detectors/PHG4ForwardEcalDisplayAction.cc
simulation/g4simulation/g4detectors/PHG4ForwardHcalDetector.cc
simulation/g4simulation/g4detectors/PHG4ForwardHcalDetector.h
simulation/g4simulation/g4detectors/PHG4ForwardHcalDisplayAction.cc
simulation/g4simulation/g4eval/EventEvaluator.cc
simulation/g4simulation/g4eval/EventEvaluator.h
simulation/g4simulation/g4eval/Makefile.am
simulation/g4simulation/g4eval/PHG4DSTReader.cc
simulation/g4simulation/g4jets/ClusterJetInput.cc

- Introduction of proper geometry for FHCAL according to the STAR forward upgrade design: https://drupal.star.bnl.gov/STAR/files/ForwardUpgrade.v20.pdf
- new event based tree eval 
- added forward clusters to jet class

FHCAL updates and event tree eval introduction

---

simulation/g4simulation/g4eval/EventEvaluator.cc
simulation/g4simulation/g4eval/EventEvaluator.h

Further improvements for the event based tree as output
Further improvements for the event based tree as output

Update of event based tree

---

offline/packages/trackreco/Makefile.am
offline/packages/trackreco/PHActsToSvtxTracks.cc
offline/packages/trackreco/PHActsToSvtxTracks.h

This PR makes a module that converts Acts tracks to SvtxTracks. This will allow us to keep backwards compatibility with Svtx objects once we move away from them.

Acts to svtx module

---

offline/packages/trackreco/ALICEKF.cc
offline/packages/trackreco/ALICEKF.h
offline/packages/trackreco/GPUTPCBaseTrackParam.h
offline/packages/trackreco/GPUTPCTrackLinearisation.h
offline/packages/trackreco/GPUTPCTrackParam.cxx
offline/packages/trackreco/GPUTPCTrackParam.h
offline/packages/trackreco/Makefile.am
offline/packages/trackreco/PHCASeeding.cc
offline/packages/trackreco/PHCASeeding.h
offline/packages/trackreco/PHHybridSeeding.cc
offline/packages/trackreco/PHHybridSeeding.h
offline/packages/trackreco/PHSimpleKFProp.cc
offline/packages/trackreco/PHSimpleKFProp.h
offline/packages/trackreco/nanoflann.hpp

Major changes:
- Created propagator, PHSimpleKFProp
- Separated ALICE Kalman filter wrapper into separate class (ALICEKF), used by PHCASeeding, PHHybridSeeding, and PHSimpleKFProp
- Substantial coordinate-transformation-based fixes to Kalman filter usage
- If Kalman filter produces unsatisfactory results, default to circle-fit-based pT estimate (less accurate, but possibly more numerically stable for short seeds)
- Changed ALICE KF module (GPUTPC*) internal members from float to double
- Using field map, rather than constant field, for KF and propagator
[comment]: <> ( What does this PR do? Linking to talk in software …

TPC seeding overhaul and introduction of PHSimpleKFProp

---

simulation/g4simulation/g4eval/EventEvaluator.cc
simulation/g4simulation/g4eval/EventEvaluator.h

restructuring and DRCALO preparation for EventEvaluator

---

simulation/g4simulation/g4eval/EventEvaluator.cc

added tracking layer hits to output for event tree

added hits for tracking layers for output

---

simulation/g4simulation/g4eval/EventEvaluator.cc

fix for random crashes in event evaluator

fix for EventEvaluator for calo standalone modes

---

simulation/g4simulation/g4eval/EventEvaluator.cc

- fix for random crashes due to too large hit output

reduced output size and rare crash for EventEvaluator

---

offline/packages/trackreco/PHTruthTrackSeeding.cc
offline/packages/trackreco/configure.ac

This is necessary for ACTS fit to succeed.
The charge is retrieved from the geant particle. Unfortunately the particle charge is not stored in PHG4Particle. We need to resort to G4ParticleTable to get the charge from pdg id.

assign correct charge to the truth track. 

---

generators/PHPythia8/configure.ac
generators/hijing/configure.ac
offline/QA/modules/configure.ac
offline/packages/CaloBase/configure.ac
offline/packages/CaloReco/configure.ac
offline/packages/ClusterIso/configure.ac
offline/packages/KFParticle_sPHENIX/configure.ac
offline/packages/NodeDump/configure.ac
offline/packages/PHTpcTracker/configure.ac
offline/packages/jetbackground/configure.ac
offline/packages/particleflow/configure.ac
offline/packages/trackreco/configure.ac
offline/packages/trigger/configure.ac
simulation/g4simulation/EICPhysicsList/configure.ac
simulation/g4simulation/g4bbc/configure.ac
simulation/g4simulation/g4calo/configure.ac
simulation/g4simulation/g4detectors/configure.ac
simulation/g4simulation/g4epd/configure.ac
simulation/g4simulation/g4histos/configure.ac
simulation/g4simulation/g4intt/configure.ac
simulation/g4simulation/g4jets/configure.ac
simulation/g4simulation/g4main/Makefile.am
simulation/g4simulation/g4main/PHG4Reco.cc
simulation/g4simulation/g4main/configure.ac
simulation/g4simulation/g4micromegas/configure.ac
simulation/g4simulation/g4mvtx/configure.ac
simulation/g4simulation/g4tpc/configure.ac
simulation/g4simulation/g4trackfastsim/configure.ac
simulation/g4simulation/g4vertex/configure.ac

This PR updates all the clang compiler flags in various configure.ac's to suppress new warnings from clang 11.1.0. It should not have any effect on the g++ compilation but the old clang and probably scan build based on the old calng version won't like this.

Clang c++17

---

simulation/g4simulation/g4eval/EventEvaluator.cc
simulation/g4simulation/g4eval/EventEvaluator.h

added true hit information to EventEvaluator

---

simulation/g4simulation/g4eval/SvtxEvaluator.cc

SvtxEvaluator fix

---

offline/packages/micromegas/MicromegasClusterizer.cc
offline/packages/trackreco/PHActsTrkFitter.cc
offline/packages/trackreco/PHGenFitTrkFitter.cc
offline/packages/trackreco/PHTruthTrackSeeding.cc
simulation/g4simulation/g4micromegas/PHG4MicromegasHitReco.cc

The weekly friday afternoon PR is here from the tracking side. This PR fixes several bugs from the fall out of the monday night merge which combined the Svtx and Acts objects. This PR fixes truth track seeding, GenFit track fitting, and the TPOT cluster adding to the acts track fits.

Tracking fixes

---

offline/packages/micromegas/MicromegasClusterizer.cc
offline/packages/trackreco/PHActsTrkFitter.cc
offline/packages/trackreco/PHGenFitTrkFitter.cc
offline/packages/trackreco/PHTruthTrackSeeding.cc
simulation/g4simulation/g4micromegas/PHG4MicromegasHitReco.cc

Reverts sPHENIX-Collaboration/coresoftware#1134
Sorry - I misunderstood

Revert "Tracking fixes"

---

.gitignore
offline/packages/CaloBase/Makefile.am
offline/packages/CaloBase/RawTower.cc
offline/packages/CaloBase/RawTower.h
offline/packages/CaloBase/RawTowerDefs.h
offline/packages/CaloBase/RawTowerv1.cc
offline/packages/CaloBase/RawTowerv1.h
offline/packages/CaloBase/RawTowerv2.cc
offline/packages/CaloBase/RawTowerv2.h
offline/packages/CaloBase/RawTowerv2LinkDef.h
simulation/g4simulation/g4calo/Makefile.am
simulation/g4simulation/g4calo/RawTowerBuilderDRCALO.cc
simulation/g4simulation/g4calo/RawTowerBuilderDRCALO.h
simulation/g4simulation/g4detectors/Makefile.am
simulation/g4simulation/g4detectors/PHG4BackwardHcalDetector.cc
simulation/g4simulation/g4detectors/PHG4BackwardHcalDetector.h
simulation/g4simulation/g4detectors/PHG4BackwardHcalDisplayAction.cc
simulation/g4simulation/g4detectors/PHG4BackwardHcalDisplayAction.h
simulation/g4simulation/g4detectors/PHG4BackwardHcalSteppingAction.cc
simulation/g4simulation/g4detectors/PHG4BackwardHcalSteppingAction.h
simulation/g4simulation/g4detectors/PHG4BackwardHcalSubsystem.cc
simulation/g4simulation/g4detectors/PHG4BackwardHcalSubsystem.h
simulation/g4simulation/g4eval/EventEvaluator.cc
simulation/g4simulation/g4eval/EventEvaluator.h
simulation/g4simulation/g4main/PHG4Hit.cc
simulation/g4simulation/g4main/PHG4Hit.h
simulation/g4simulation/g4main/PHG4Reco.cc

- addition of new classes for backward HadCal
- base implementations needed for DRCalo (dual readout)
- new properties in offline/packages/CaloBase/RawTowerv1.cc for scintialtion and cherenkov photons
- addition of other calorimeters to EventEvaluator

Introduction of EHCAL & base class changes needed for DR calo

---

simulation/g4simulation/g4eval/Makefile.am
simulation/g4simulation/g4eval/TrackEvaluation.cc
simulation/g4simulation/g4eval/TrackEvaluation.h
simulation/g4simulation/g4eval/TrackEvaluationContainer.cc
simulation/g4simulation/g4eval/TrackEvaluationContainer.h
simulation/g4simulation/g4eval/TrackEvaluationContainerLinkDef.h
simulation/g4simulation/g4eval/configure.ac
simulation/g4simulation/g4micromegas/PHG4MicromegasDigitizer.cc

As discussed (in particular with @bogui56) during last few tracking meetings, this PR introduces a new evaluation module, called TrackEvaluation, that fills variable size structures containing track and cluster informations hopefully suitable for studying the possibility to compress our output format. (this is also in essence the module I used to get all types of residual plots that have been circulating around for the last 6 month). Tracks and clusters are stored in a node called "TrackEvaluationContainer". The structure using only std::vectors, the node content can be drawn directly from  a root macro without the need for loading any coresoftware-specific libraries (as with a flat ntuple)
[comment]: <> ( What types of …

new evaluation module

---

simulation/g4simulation/g4eval/Makefile.am
simulation/g4simulation/g4eval/TrackEvaluation.cc
simulation/g4simulation/g4eval/TrackEvaluation.h
simulation/g4simulation/g4eval/TrackEvaluationContainer.h
simulation/g4simulation/g4eval/TrackEvaluationContainerv1.cc
simulation/g4simulation/g4eval/TrackEvaluationContainerv1.h
simulation/g4simulation/g4eval/TrackEvaluationContainerv1LinkDef.h

Following private discussion with @pinkenburg, this PR 
- moved the container class to a tiny g4eval_io library
- introduces a base class for the Container and a v1 class.
@pinkenburg Can you double-check, in case you have better ideas: the base class has an essentially empy interface. I have kept the information in the v1 class as nested structures, with no base class. This means that any modification would require to create a v2 and copy the nested classes with relevant modifications ported there. This allows to store actual classes rather than pointer to them, which in turns makes it much easier to browse the tree's content offline, in a way that is very similar to what you can do with a TNtuple.  Now this is not as …

New evaluation module (follow up)

---

simulation/g4simulation/g4eval/TrackEvaluation.cc
simulation/g4simulation/g4eval/configure.ac

This fixes an error not caught by jenkins due to https://github.com/sPHENIX-Collaboration/coresoftware/pull/1144, but that was causing nightly rebuild to fail.
Since things should be back to normal, also re-added the -Werror flag to configure.ac

fix nightly build

---

simulation/g4simulation/g4detectors/PHG4BlockSubsystem.cc

This PR initializes the color array of the block subsystem to NAN

Fix block uninit

---

offline/database/PHParameter/Makefile.am
offline/database/PHParameter/PHParameterContainerInterface.cc
offline/database/PHParameter/PHParameterContainerInterface.h
offline/database/PHParameter/PHParameterInterface.cc
offline/database/PHParameter/PHParameterInterface.h
offline/database/PHParameter/PHParameters.cc

This PR replaces boost::filesystem by std::filesystem from c++17 in the PHParameter class. It also takes care of some perennial cppcheck warnings. It turned outthat the change was not necessary but replacing boost by stl is a good thing in terms of API stability.

Package upgrades

---

simulation/g4simulation/g4detectors/BeamLineMagnetSteppingAction.cc
simulation/g4simulation/g4detectors/BeamLineMagnetSteppingAction.h

This bogus message came from the magnets being disabled but set as black hole:
BeamLineMagnetSteppingAction::SetTopNode - unable to find G4HIT_BEAMLINEMAGNET
There is nothing wrong with that - in that case the hit nodes are not created and the stepping action is aborted in the black hole before anything gets written. Now this message is suppressed if the black hole feature is set.
[comment]: <> ( In case this is a draft PR, e.g. for running checks using Jenkins, please make the …

Fix node message

---

calibrations/alignment/README.md
calibrations/calorimeter/README.md
calibrations/distortions/README.md

This PR just adds a directory structure for our calibrations

Add calibration code structure

---

offline/packages/trackreco/PHActsTrackProjection.cc
offline/packages/trackreco/PHActsTrackProjection.h

This PR updates the track projection module to work with the updated tracking object formats. Local tests work so it is unclear if the ACTS bug is solved in this - will continue to test over larger jobs to see if anything comes up.

Update track projection module

---

simulation/g4simulation/g4detectors/PHG4CylinderSteppingAction.cc
simulation/g4simulation/g4detectors/PHG4CylinderSteppingAction.h
simulation/g4simulation/g4detectors/PHG4CylinderSubsystem.cc
simulation/g4simulation/g4detectors/PHG4DetectorGroupSubsystem.cc
simulation/g4simulation/g4detectors/PHG4DetectorSubsystem.cc
simulation/g4simulation/g4detectors/PHG4DetectorSubsystem.h

This PR adds the entries needed to separate the calorimeter absorber from support structures. Based on this support structures can be added as their own entities 

prepare for separate support structure accounting

---

offline/packages/CaloReco/BEmcRec.cc

Corrected bug in geometry extraction; may affect endcap reco

---

offline/packages/tpc/TpcClusterizer.cc
offline/packages/tpc/TpcClusterizer.h

Tpc cluster z offset correction

---

offline/QA/modules/QAG4SimulationMicromegas.cc
offline/packages/micromegas/CylinderGeomMicromegas.h
offline/packages/micromegas/MicromegasClusterizer.cc
offline/packages/micromegas/MicromegasClusterizer.h
offline/packages/trackbase/ActsSurfaceMaps.h
offline/packages/trackreco/MakeActsGeometry.cc
offline/packages/trackreco/MakeActsGeometry.h
offline/packages/trackreco/PHActsTrkFitter.cc
offline/packages/trackreco/PHActsTrkFitter.h
offline/packages/trackreco/PHGenFitTrkFitter.cc
offline/packages/trackreco/PHMicromegasTpcTrackMatching.cc
offline/packages/trackreco/PHMicromegasTpcTrackMatching.h
offline/packages/trackreco/PHTpcResiduals.cc
offline/packages/trackreco/PHTpcResiduals.h
simulation/g4simulation/g4detectors/PHG4CylinderGeomContainer.h
simulation/g4simulation/g4micromegas/PHG4MicromegasHitReco.cc

This is a follow up to https://github.com/sPHENIX-Collaboration/coresoftware/pull/1166. It implements the new Micromegas geometry in ACTS. Rather than having ACTS Micromegas surfaces defined as portion of cylinders that cover the full TPC acceptance, there is now on surface per micromegas module. This makes the correspondance from hitsetid to ACTS Micromegas surface straightforward, and fixes the problem of ACTS not picking the right surface when handling 1D measurements, located at the middle of the strip, for the other coordinate.
All tracking and QA code adjusted accordingly
See https://indico.bnl.gov/event/11903/contributions/49766/attachments/34569/56076/talk.pdf for details
New geometry in ACTS:  …

New micromegas geometry acts

---

calibrations/calorimeter/calo_tower_slope/LiteCaloEval.cc
calibrations/calorimeter/calo_tower_slope/LiteCaloEval.h
calibrations/calorimeter/calo_tower_slope/README.md
calibrations/calorimeter/calo_tower_slope/autogen.sh
calibrations/calorimeter/calo_tower_slope/configure.ac
calibrations/calorimeter/calo_tower_slope/macro/Fun4All_G4_Analysis.C
calibrations/calorimeter/calo_tower_slope/macro/run_f4a.csh

initial add of tower slope calib code by Justin

---

calibrations/tpc/generator/AnnularFieldSim.cc
calibrations/tpc/generator/AnnularFieldSim.h
calibrations/tpc/generator/Makefile.am
calibrations/tpc/generator/Rossegger.h
calibrations/tpc/generator/autogen.sh
calibrations/tpc/generator/configure.ac

The tpc generator code compiles now

get tpc dist generator to compile

---

offline/framework/frog/CreateFileList.pl
offline/framework/fun4all/Fun4AllDstInputManager.cc
offline/framework/fun4all/Fun4AllUtils.cc
offline/framework/fun4all/TDirectoryHelper.cc
offline/packages/CaloBase/RawTower.cc
offline/packages/CaloBase/RawTower.h
offline/packages/CaloBase/RawTowerGeomContainer.cc
offline/packages/CaloBase/RawTowerv2.cc
offline/packages/CaloBase/RawTowerv2.h
simulation/g4simulation/g4detectors/PHG4ConeSubsystem.cc
simulation/g4simulation/g4detectors/PHG4OuterHcalField.cc
simulation/g4simulation/g4detectors/PHG4OuterHcalField.h
simulation/g4simulation/g4detectors/PHG4SpacalDetector.cc
simulation/g4simulation/g4main/PHG4Reco.cc

This PR fixes a few scan-build warnings and cleans some includes. CreateFileList.pl now prints out all dst types for a given production, not only the pre-defined ones (the additional ones are normally temporary which is useful for testing) 

Print all dsttypes

---

offline/packages/compressor/Makefile.am
offline/packages/compressor/autogen.sh
offline/packages/compressor/compress_clu_res_float32.cc
offline/packages/compressor/compressor.h
offline/packages/compressor/configure.ac

This PR adds the first version of Christof compressor code

Add compressor code

---

offline/packages/trackreco/PHGenFitTrkFitter.cc

This allows to run genfit on MDC1 hit files that contain no truth information

Allow to run GenFit when truth information is no present

---

offline/QA/modules/QAG4SimulationMicromegas.cc
offline/QA/modules/QAG4SimulationMicromegas.h

I will update jupyter plots accordingly

Added ADC distributions to micromegas QA

---

offline/packages/micromegas/MicromegasClusterizer.cc

sum cluster's belonging hits' ADC values and assign to cluster

sum cluster's belonging hits' ADC values and assign to cluster

---

offline/packages/trackreco/PHActsVertexFinder.cc
offline/packages/trackreco/PHActsVertexFinder.h

This PR adds a function to associate secondaries to the primary vertex, which ACTS does not do by default.

Check secondary vertex association

---

simulation/g4simulation/g4eval/EventEvaluator.cc
simulation/g4simulation/g4eval/EventEvaluator.h

[comment]: This PR fixes unwated crashes when using the inner HCAL and provides a basis for a new feature (a geometry tree).

EventEvaluator additions

---

simulation/g4simulation/g4main/Makefile.am
simulation/g4simulation/g4main/PHG4PhenixStackingAction.cc
simulation/g4simulation/g4main/PHG4PhenixStackingAction.h
simulation/g4simulation/g4main/PHG4Reco.cc
simulation/g4simulation/g4main/PHG4Reco.h
simulation/g4simulation/g4main/PHG4StackingAction.cc
simulation/g4simulation/g4main/PHG4StackingAction.h
simulation/g4simulation/g4main/PHG4Subsystem.h

This PR adds a hook to the stacking action (called when a new track is created). This is needed for the Panda dirc which implements efficiencies this way (terminating optical photons which won't make it)

Stacking action

---

offline/packages/trackbase/Makefile.am
offline/packages/trackbase/TpcSeedTrackMap.cc
offline/packages/trackbase/TpcSeedTrackMap.h
offline/packages/trackbase/TpcSeedTrackMapLinkDef.h
offline/packages/trackbase/TpcSeedTrackMapv1.cc
offline/packages/trackbase/TpcSeedTrackMapv1.h
offline/packages/trackbase/TpcSeedTrackMapv1LinkDef.h
offline/packages/trackreco/PHSiliconTpcTrackMatching.cc
offline/packages/trackreco/PHSiliconTpcTrackMatching.h
offline/packages/trackreco/PHTrackCleaner.cc
offline/packages/trackreco/PHTrackCleaner.h

When we run multi-pass tracking the TpcSeedTrackMap that is created in PHSiliconTpcTrackMatching for later use by PHTrackCleaner will have to be written to the pass 1 output DST. This PR makes it a versioned class and puts it on the node tree as a PHIODataNode. It has never been written out before, so this causes no harm. …

Version tpc seed track map

---

simulation/g4simulation/g4detectors/BeamLineMagnetDetector.cc
simulation/g4simulation/g4detectors/BeamLineMagnetDetector.h
simulation/g4simulation/g4detectors/BeamLineMagnetSteppingAction.cc
simulation/g4simulation/g4detectors/BeamLineMagnetSubsystem.h

1. Allow detectors be installed into magnet's cavities in macros
2. When beamline magnet is set to be black hole, the total absorption feature is now only apply to the magnet iron and allow particle to pass through its central opening. 

Beamline magnet updates

---

offline/packages/tpccalib/Makefile.am
offline/packages/tpccalib/TpcSpaceChargeMatrixInversion.cc

use frog in order to be able to load and aggregate matrices from files that are on e.g. dcache

---

offline/packages/CaloBase/RawTowerDefs.h
offline/packages/CaloReco/BEmcRec.cc
offline/packages/CaloReco/BEmcRec.h
offline/packages/CaloReco/BEmcRecEEMC.cc
offline/packages/CaloReco/BEmcRecEEMC.h
offline/packages/CaloReco/RawClusterBuilderTemplate.cc
simulation/g4simulation/g4eval/EventEvaluator.cc
simulation/g4simulation/g4eval/EventEvaluator.h

- code changes which are necessary to incorporate the hybrid PbWO4/sci-glass electron endcap EMC

Preparations for hybrid Electron End-cap EMC

---

.gitignore
offline/packages/CaloBase/RawTower.h
offline/packages/CaloBase/RawTowerContainer.cc
offline/packages/CaloBase/RawTowerContainer.h
offline/packages/CaloBase/RawTowerDefs.h
offline/packages/CaloBase/RawTowerGeom.h
offline/packages/CaloBase/RawTowerGeomv3.cc
offline/packages/CaloBase/RawTowerGeomv3.h
offline/packages/CaloBase/RawTowerv1.cc
offline/packages/CaloBase/RawTowerv1.h
offline/packages/CaloBase/RawTowerv2.h
offline/packages/CaloReco/Makefile.am
offline/packages/CaloReco/RawTowerCalibration.cc
simulation/g4simulation/g4calo/Makefile.am
simulation/g4simulation/g4calo/RawTowerBuilderByHitIndexLHCal.cc
simulation/g4simulation/g4calo/RawTowerBuilderByHitIndexLHCal.h
simulation/g4simulation/g4calo/RawTowerDigitizer.cc
simulation/g4simulation/g4eval/EventEvaluator.cc
simulation/g4simulation/g4eval/EventEvaluator.h

- this commit is the basis for the introduction of a longitudinally separated HCal for EIC
https://github.com/eic/fun4all_eicdetectors/pull/18
https://github.com/eic/fun4all_eicmacros/pull/45
https://github.com/eic/fun4all_eiccalibrations/pull/13

Additions to base classes for introducing a longitudinally separated Calo

---

calibrations/calorimeter/calo_tower_slope/Makefile.am

This PR just adds the Makefile.am so this can be added to the build packages without crashing the builds. The main change will be in the next PR which will then be checked by jenkins

add missing Makefile.am

---

calibrations/calorimeter/calo_tower_slope/LiteCaloEval.cc
calibrations/calorimeter/calo_tower_slope/LiteCaloEval.h
calibrations/calorimeter/calo_tower_slope/macro/Fun4All_G4_SlopeCal.C

This PR makes the slope calibration work, lots of cleanup as well

Fix slope cal

---

offline/packages/trackreco/ActsEvaluator.cc
offline/packages/trackreco/ActsEvaluator.h
offline/packages/trackreco/Makefile.am
offline/packages/trackreco/PHActsTrkFitter.cc
offline/packages/trackreco/PHActsTrkFitter.h

This PR updates the ActsEvaluator class to function with the current tracking chain. 

Acts evaluator update

---

offline/packages/trackreco/MakeActsGeometry.cc

This updates the magnetic field map for ACTS to the recent version in the calibroot directory

Update mag field file path

---

simulation/g4simulation/g4detectors/BeamLineMagnetDetector.cc
simulation/g4simulation/g4detectors/BeamLineMagnetDetector.h
simulation/g4simulation/g4detectors/BeamLineMagnetSubsystem.cc
simulation/g4simulation/g4main/PHG4Detector.h
simulation/g4simulation/g4main/PHG4PhenixDetector.cc

This pull request fix two problem in field setup: 
1. if a magnet is nested under volume of another subsystem 
2. if a magnet holds other subsystems
Both a feature recently enabled by https://github.com/sPHENIX-Collaboration/coresoftware/pull/1210 , which allowed assembly of  beamline magnet and detection system using just macros. 
Problem 1 induced a shifted field in the case of quadrupoles, which is fixed by a separate parameter set the field using global coordinate system. Problem 2 voided the field setup in daughter subsystem …

Beam magnet fix

---

simulation/g4simulation/g4eval/EventEvaluator.cc
simulation/g4simulation/g4eval/EventEvaluator.h

[comment]: Fix for reported crash of the EventEvaluator when processing hits. 

EventEvaluator crash fix for hits

---

simulation/g4simulation/g4eval/SvtxClusterEval.cc
simulation/g4simulation/g4eval/SvtxClusterEval.h
simulation/g4simulation/g4eval/SvtxEvaluator.cc
simulation/g4simulation/g4eval/SvtxTruthEval.cc
simulation/g4simulation/g4eval/SvtxTruthEval.h

Rearranged the internal caching scheme to speed up the Evaluator.
Test event took 431 sec before change, now takes 81

evaluator speedup

---

offline/packages/trackreco/PHActsTrkFitter.cc

Fixes a bug in the prototrack evaluation piece of the ActsEvaluator.

Acts Evaluator Fix

---

offline/packages/PHField/PHField3DCartesian.cc

This PR adds the rescaling of the magnetic field for the 3d carthesian fieldmap

implement rescaling of 3d carthesian field

---

offline/packages/trackreco/MakeActsGeometry.cc

This PR updates the ACTS magnetic field to function with the 3D field map in simulation. 
It should NOT be merged until this [PR](https://github.com/sPHENIX-Collaboration/coresoftware/pull/1235) and the corresponding macros [PR](https://github.com/sPHENIX-Collaboration/macros/pull/425) are merged. The QA should be messed up completely as this PR flips the magnetic field sign in ACTS to be compatible with the 3D map, which makes it …

Magnetic Field Update

---

simulation/g4simulation/g4detectors/PHG4HcalCellReco.cc
simulation/g4simulation/g4detectors/PHG4HcalCellReco.h

This PR increases the dimension of the cell array for the hcals. The inner hcal for ecce needs an increase from 24 to 27 for the columns 

increase column dim to 27 to cover ecce inner hcal

---

simulation/g4simulation/g4eval/SvtxClusterEval.cc
simulation/g4simulation/g4eval/SvtxTruthEval.cc

Remove extraneous verbosity statements from previous PR.

remove verbosity

---

offline/packages/CaloBase/RawTowerDefs.h
simulation/g4simulation/g4detectors/PHG4ZDCDetector.cc
simulation/g4simulation/g4detectors/PHG4ZDCDetector.h
simulation/g4simulation/g4detectors/PHG4ZDCDisplayAction.cc
simulation/g4simulation/g4detectors/PHG4ZDCDisplayAction.h
simulation/g4simulation/g4detectors/PHG4ZDCSteppingAction.cc
simulation/g4simulation/g4detectors/PHG4ZDCSteppingAction.h
simulation/g4simulation/g4detectors/PHG4ZDCSubsystem.cc
simulation/g4simulation/g4detectors/PHG4ZDCSubsystem.h

Add ZDC Geant4 simulation.
Detector geometry is based on ZDC PHENIX simulation code.
Add D0 magnet simulation
Add supporting structures

Added ZDC Geant4 setup

---

simulation/g4simulation/g4eval/EventEvaluator.cc
simulation/g4simulation/g4eval/EventEvaluator.h

- this commit is intended to remove from the sPHENIX event-evaluator all EIC detectors
https://github.com/eic/fun4all_eicmacros/pull/53
https://github.com/eic/fun4all_eicdetectors/pull/27

deconvoluted EventEvaluator for sPHENIX and EIC

---

simulation/g4simulation/g4tpc/PHG4TpcCentralMembrane.cc
simulation/g4simulation/g4tpc/PHG4TpcCentralMembrane.h
simulation/g4simulation/g4tpc/PHG4TpcDirectLaser.cc
simulation/g4simulation/g4tpc/PHG4TpcDirectLaser.h
simulation/g4simulation/g4tpc/PHG4TpcElectronDrift.cc
simulation/g4simulation/g4tpc/PHG4TpcElectronDrift.h

This PR follows up on introducing TPC directed lasers and central membrane G4Hits
it 
- moves both classes out of PHG4TpcElectronDrift to independent subsysreco, to make it simpler to run and have better compartimented code
- use PHParameterInterface to be able to set parameters from calling macro, such as number of electrons per cm and per stripe, as well as number of electrons per GeV. The latter must be kept in sync with what is used for PHG4TpcElectronDrift
- generalizes the intersection of laser lines to all surfaces in the TPC including readout planes. This way, and for debugging, one can put a laser virtually anywhere inside the TPC and get the right intersections
Some minor issues have been fixed in the process, …

Tpc lasers followup

---

offline/packages/trackreco/PHSimpleKFProp.cc

Fixes crash in PHSimpleKFProp that occurs when there are zero TPC clusters in any given layer.
In certain single-pion events, there can sometimes be zero TPC clusters in a layer. In those cases, the nanoflann nearest-neighbor search used by PHSimpleKFProp returns zero results, which results in a crash when the cluster map is asked to find a cluster that doesn't exist. Fixed by skipping the layer if no nearest neighbors are found. …

Fixed no-neighbor crash in PHSimpleKFProp

---

simulation/g4simulation/g4trackfastsim/PHG4TrackFastSim.cc

Add ECHal projection option

---

simulation/g4simulation/g4eval/DSTEmulator.cc
simulation/g4simulation/g4eval/DSTEmulator.h
simulation/g4simulation/g4eval/Makefile.am

Initial DSTEmulator implementation

---

simulation/g4simulation/g4tpc/PHG4TpcDirectLaser.cc

Makes the code easier to read and more efficient.

use std::optional rather than std::pair<bool,T> to transport extrapolation failure

---

simulation/g4simulation/g4trackfastsim/PHG4TrackFastSim.cc

[comment]: <>Simple additions to allow projections to the ECCE BECAL  and LFHCAL 
[comment]: <> 
https://github.com/ECCE-EIC/macros/pull/45

Add BECAL and LFHCAL projections

---

generators/phhepmc/PHHepMCGenHelper.cc
generators/phhepmc/PHHepMCGenHelper.h

This pull request implement the simulation of the collision vertex in space-time using beam bunch parameters as described in 
https://github.com/eic/documents/blob/d06b5597a0a89dcad215bab50fe3eefa17a097a5/reports/general/Note-Simulations-BeamEffects.pdf 
Test, validate and update macros 
Not yet submitted.

Introduce vertex simulation via beam bunch interactions

---

simulation/g4simulation/g4detectors/BeamLineMagnetDetector.cc
simulation/g4simulation/g4detectors/BeamLineMagnetDetector.h
simulation/g4simulation/g4detectors/BeamLineMagnetDisplayAction.cc
simulation/g4simulation/g4detectors/BeamLineMagnetSteppingAction.cc
simulation/g4simulation/g4detectors/BeamLineMagnetSteppingAction.h
simulation/g4simulation/g4detectors/BeamLineMagnetSubsystem.cc
simulation/g4simulation/g4detectors/BeamLineMagnetSubsystem.h

This PR fixes the behavior of the beamline magnets when absorbers (magnet volumes) are saved. It crashed before in the stepping action. In general hits are only saved if the absorber is active (in the beam pipe and in the magnet)

Fix beamline magnet

---

offline/packages/trackreco/Makefile.am
offline/packages/trackreco/PHActsSiliconSeeding.cc
offline/packages/trackreco/PHActsTrackProjection.cc
offline/packages/trackreco/PHActsTrackProjection.h
offline/packages/trackreco/PHActsTrkFitter.cc
offline/packages/trackreco/PHActsTrkFitter.h
offline/packages/trackreco/PHActsVertexFinder.cc
offline/packages/trackreco/PHActsVertexFinder.h
offline/packages/trackreco/PHActsVertexPropagator.cc
offline/packages/trackreco/PHActsVertexPropagator.h
offline/packages/trackreco/PHMicromegasTpcTrackMatching.cc
offline/packages/trackreco/PHMicromegasTpcTrackMatching.h
offline/packages/trackreco/PHSiliconTpcTrackMatching.cc
offline/packages/trackreco/PHSiliconTpcTrackMatching.h
offline/packages/trackreco/PHSimpleKFProp.cc
offline/packages/trackreco/PHSimpleKFProp.h
offline/packages/trackreco/PHSimpleVertexFinder.cc
offline/packages/trackreco/PHSimpleVertexFinder.h
offline/packages/trackreco/PHTpcTrackSeedCircleFit.cc
offline/packages/trackreco/PHTpcTrackSeedCircleFit.h
offline/packages/trackreco/PHTruthVertexing.cc
offline/packages/trackreco/PHTruthVertexing.h

This PR introduces a major refactoring of the tracking chain to remove any dependence of the vertex position in the track fit. The track reconstruction can proceed vertex independently; once all tracks are fitted, vertices can be found and then tracks are propagated to that vertex position to obtain the final track position parameters. This PR thus removes the need for initial vertex finding, the need for a second final track fit as only one track fit is needed to get the parameters at the track position WRT to the beam line., and the need for any truth information in the entire reconstruction process.
Tests in HIJING …

Track Fitting Without Vertex

---

offline/packages/trackreco/PHSimpleVertexFinder.cc

Reduces number of low n track vertices found by the simple vertex finder

Vertexing Fix

---

simulation/g4simulation/g4detectors/PHG4SpacalDetector.cc
simulation/g4simulation/g4detectors/PHG4SpacalDetector.h
simulation/g4simulation/g4detectors/PHG4SpacalSubsystem.cc
simulation/g4simulation/g4detectors/PHG4SpacalSubsystem.h

This PR adds a switch to the PHG4Spacal subsystem to run cosmics sims. Only one double sector is produced and put in the center of the coordinate system when the PHG4SpacalSubsystem::CosmicSetup(1) is set in the macro

Cemc cosmic

---

simulation/g4simulation/g4dst/Makefile.am

Add `libkfparticle_sphenix_io` to the convenience DST readback lib `libg4dst`

Add `libkfparticle_sphenix_io` to the convenience DST readback lib `libg4dst`

---

simulation/g4simulation/g4detectors/PHG4OuterHcalSteppingAction.cc

This PR uses the oHCAL tile map response measured by MEPHI to modify the oHCAL light yield generated from energy deposits in the scintillator to reflect the measured non-uniformity in the scintillating tiles. 
This PR adds a more realistic light yield response from the oHCAL scintillating tiles based on the measured tile response. As such, the light yield will more accurately reflect the features of the fiber embedded in the tile, proximity to the light blocker, etc. Because the scintillator in G4 is implemented as a single subdivided volume (no boundaries) this will also have the effect of introducing boundaries between …

Add oHCAL tile map response

---

offline/packages/CaloBase/RawTowerDefs.h

From https://github.com/abylinkin, ID additions necessary to run B0 Ecal Tower digitization, clusterization and evaluation

Adding IDs for B0 ECal

---

simulation/g4simulation/g4gdml/PHG4GDMLUtility.cc
simulation/g4simulation/g4gdml/PHG4GDMLUtility.hh
simulation/g4simulation/g4main/PHG4Reco.cc
simulation/g4simulation/g4main/PHG4Reco.h

Importing a useful feature at https://github.com/ECCE-EIC/coresoftware/pull/4,  thanks to @kkauder
"Added a function PHG4GDMLUtility::Dump_G4_GDML and corresponding PHG4Reco::Dump_G4_GDML that uses G4GDMLWriteStructure instead of PHG4GDMLWriteStructure. This way patches and version updates to geant get picked up without having to be ported in."

native GDML writer addition

---

offline/packages/tpc/TpcClusterizer.cc
offline/packages/tpc/TpcClusterizer.h
offline/packages/trackreco/Makefile.am
offline/packages/trackreco/PHCASeeding.cc
offline/packages/trackreco/PHCASeeding.h
offline/packages/trackreco/PHSiliconTpcTrackMatching.cc
offline/packages/trackreco/PHSimpleKFProp.cc
offline/packages/trackreco/PHTpcDeltaZCorrection.cc
offline/packages/trackreco/PHTpcDeltaZCorrection.h
offline/packages/trackreco/PHTpcTrackSeedCircleFit.cc
offline/packages/trackreco/PHTpcTrackSeedCircleFit.h

This PR introduces a per-track delta_z correction to the TPC clusters, to account for particle's finite velocity and propagation in the TPC. 
Consequently simplified Delta_z correction in TpcClusterizer to a single constant value that accounts for the TPC shaping time.
See details at: https://indico.bnl.gov/event/13716/contributions/57178/attachments/38262/63057/talk.pdf
Also included small cleanup/optimizations to visited tracking modules  …

Tpc deltaz correction

---

offline/packages/centrality/CentralityInfo.h
offline/packages/centrality/CentralityInfoLinkDef.h
offline/packages/centrality/CentralityInfov1.cc
offline/packages/centrality/CentralityInfov1.h
offline/packages/centrality/CentralityInfov1LinkDef.h
offline/packages/centrality/Makefile.am
offline/packages/centrality/autogen.sh
offline/packages/centrality/configure.ac
simulation/g4simulation/g4centrality/Makefile.am
simulation/g4simulation/g4centrality/PHG4CentralityReco.cc
simulation/g4simulation/g4centrality/PHG4CentralityReco.h
simulation/g4simulation/g4centrality/autogen.sh
simulation/g4simulation/g4centrality/configure.ac
simulation/g4simulation/g4dst/Makefile.am

This PR superseeds Dennis's centrality PR, it fixes a compilation problem and applies some cosmetic changes. I can't modify it and this is the fastest way to get this in

Centrality

---

offline/framework/frog/CreateFileList.pl

This PR updates the CreateFileList.pl for the mdc2 output files

update for MDC2 production output

---

offline/packages/trackbase_historic/ActsTransformations.cc
offline/packages/trackbase_historic/ActsTransformations.h
offline/packages/trackreco/ALICEKF.cc
offline/packages/trackreco/ALICEKF.h
offline/packages/trackreco/Makefile.am
offline/packages/trackreco/PHCASeeding.cc
offline/packages/trackreco/PHCASeeding.h
offline/packages/trackreco/PHSimpleKFProp.cc
offline/packages/trackreco/PHSimpleKFProp.h

Caches global cluster positions so that cluster position look up isn't performed many times. Improves speed of modules without loss in functionality.

Cache global in TPC Seeding

---

offline/packages/tpc/Makefile.am
offline/packages/tpc/TpcDistortionCorrection.cc
offline/packages/tpc/TpcDistortionCorrection.h
offline/packages/tpc/TpcDistortionCorrectionContainer.h
offline/packages/tpc/TpcDistortionCorrectionObject.h
offline/packages/tpc/TpcLoadDistortionCorrection.cc
offline/packages/tpc/TpcLoadDistortionCorrection.h
offline/packages/trackreco/ALICEKF.cc
offline/packages/trackreco/ALICEKF.h
offline/packages/trackreco/PHCASeeding.cc
offline/packages/trackreco/PHCASeeding.h

This PR introduces new classes to handle TPC distortion corrections in the tracking on a "on-demand" basis
Distortion corrections are loaded on the node tree at initialization via TpcLoadDistortionCorrection. Distortion corrections are stored in TpcDistortionCorrectionContainer
Subsysreco in need of distortion correction must retrieve the TpcDistortionCorrectionContainer from the node tree, and use the utility class TpcDistortionCorrection to correct a given 3D position in the TPC.
As an illustration, TPC distortion corrections have been implemented in PHCaSeeding, immediately after global coordinates are retrieved for a given cluster, via ActsTransform.
Also 
- removed broken (and ill-named) TpcSpaceChargeCorrection module …

Tpc distortion correction

---

offline/framework/frog/CreateFileList.pl

Add Charm/Bottom D0 and nopileup flag

---

offline/database/dbtools/Makefile.am
offline/database/dbtools/autogen.sh
offline/database/dbtools/configure.ac
offline/database/dbtools/xclient.cc

This PR adds the first tool for our new conditions DB, more to come

add first DB tool, just dumping calibration files

---

simulation/g4simulation/g4detectors/BeamLineMagnetDetector.cc
simulation/g4simulation/g4detectors/BeamLineMagnetSteppingAction.h
simulation/g4simulation/g4detectors/PHG4BbcDetector.cc
simulation/g4simulation/g4detectors/PHG4BbcDisplayAction.cc
simulation/g4simulation/g4detectors/PHG4BbcSteppingAction.cc
simulation/g4simulation/g4detectors/PHG4BeamlineMagnetDetector.cc
simulation/g4simulation/g4detectors/PHG4BlockDetector.cc
simulation/g4simulation/g4detectors/PHG4CEmcTestBeamDetector.cc
simulation/g4simulation/g4detectors/PHG4ConeDetector.cc
simulation/g4simulation/g4detectors/PHG4ConeSubsystem.cc
simulation/g4simulation/g4detectors/PHG4CylinderDetector.cc
simulation/g4simulation/g4detectors/PHG4CylinderGeomv1.cc
simulation/g4simulation/g4detectors/PHG4CylinderGeomv1.h
simulation/g4simulation/g4detectors/PHG4CylinderGeomv2.cc
simulation/g4simulation/g4detectors/PHG4CylinderGeomv2.h
simulation/g4simulation/g4detectors/PHG4CylinderSteppingAction.cc
simulation/g4simulation/g4detectors/PHG4EnvelopeDetector.cc

This PR puts the display actions back and re-enables the saving of support structure hits

Bbc visatt

---

simulation/g4simulation/g4centrality/PHG4CentralityReco.cc

Fixing edge cases and improving debug output

---

offline/packages/trackreco/PHActsTrkFitter.cc
offline/packages/trackreco/PHActsTrkFitter.h
offline/packages/trackreco/PHTpcTrackSeedCircleFit.cc

This PR fixes a few rare crashes that Chris found well exercising the new MDC hardware with the tracking.

Rare Crash Fix

---

offline/framework/frog/FROG.cc
offline/framework/frog/FROG.h

This PR adds a dedicated search for files in lustre. It is eanbled by adding LUSTRE to the GSEARCHPATH. Caveat: lustre is only mounted to our test hardware, for the time being this is to be used by the mdc only

add lustre dedicated search

---

simulation/g4simulation/g4intt/Makefile.am
simulation/g4simulation/g4intt/PHG4InttDigitizer.cc

in g4intt/Makefile.am: add PHG4InttDeadMapLoader.h so that this file can be included in $OFFLINE_MAIN/include/g4intt/; g4intt/PHG4InttDigitizer.cc: store hits on deadchannel first and remove those hits from TRKR_HITSET and TRKR_HITTRUTHASSOC. …

update on Makefile.am and PHG4InttDigitizer.cc in simulation/g4simulation/g4intt

---

offline/packages/trackreco/PHSimpleKFProp.cc

PHSimpleKFProp uses a KF to take a proto-track from the CA seeder and collect all associated clusters. This was previosly done by projecting the track to the nominal layer radius and searching around it for the nearest cluster. But with large (i.e. static) distortions, the corrected clusters are at a different radius and the search often fails, resulting in 67% tracking efficiency for low occupancy. This PR adds a step to estimate the radius that the distortion corrected …

Fix to PHSimpleKFProp cluster association with distortions

---

simulation/g4simulation/g4calo/HcalRawTowerBuilder.cc
simulation/g4simulation/g4calo/HcalRawTowerBuilder.h
simulation/g4simulation/g4detectors/PHG4HcalCellReco.cc
simulation/g4simulation/g4detectors/PHG4HcalCellReco.h

This PR adds the hooks for decalibration via file, setting individual cells or complete towers

Hcal decal

---

simulation/g4simulation/g4detectors/PHG4OuterHcalField.cc
simulation/g4simulation/g4detectors/PHG4OuterHcalField.h

This PR adds the printout fo some debug info for the rare assert failures we see in the mdc2 in the field lookup in the outer hcal

Debug hcal field

---

offline/database/dbtools/xclient.cc

This PR updates the example xpload client for the new version 0.6.0

update for new xpload version (0.6.0)

---

offline/framework/frog/FROG.cc
offline/framework/frog/FROG.h

This PR adds the return of a MinIO URL for files in lustre. With this files in lustre become available on the shared pool and the interactive nodes

Frog minio

---

simulation/g4simulation/g4eval/SvtxClusterEval.cc

This PR has the cluster evaluator check the corrected cluster map size to ensure that it is not 0. When running with distortions and the truth seeding, no seeds are currently found because the truth seeder looks in the corrected cluster node which is empty. This PR adds a catch that if the corrected cluster map has 0 size, the cluster evaluator uses the distorted cluster map.
With this change, the truth seeder produces seeds with the distortions and can return fitted tracks. …

Fix truth seeding with distortions

---

simulation/g4simulation/g4calo/HcalRawTowerBuilder.cc
simulation/g4simulation/g4calo/HcalRawTowerBuilder.h

allow for flexible binning in decal

---

calibrations/calorimeter/calo_emc_pi0_tbt/CaloCalibEmc_Pi0.cc
calibrations/calorimeter/calo_emc_pi0_tbt/CaloCalibEmc_Pi0.h
generators/PHPythia6/Makefile.am
generators/sHijing/Makefile.am
offline/packages/jetbackground/Makefile.am
simulation/g4simulation/g4centrality/Makefile.am
simulation/g4simulation/g4detectors/Makefile.am
simulation/g4simulation/g4jets/Makefile.am

This PR replaces the hardcoded linking of libCGAL by fastjet-config --libs. The latest version of CGAL (5.3.1) is header only. Since fastjet is linked with cgal, using fastjet-config makes a test for libCGAL (which would be complicated in our build system) unneccessary

Use fastjet config

---

offline/packages/micromegas/CylinderGeomMicromegas.cc
offline/packages/micromegas/CylinderGeomMicromegas.h
offline/packages/micromegas/MicromegasClusterizer.cc
offline/packages/trackbase/ActsTrackingGeometry.h
offline/packages/trackbase_historic/ActsTransformations.h
offline/packages/trackreco/MakeActsGeometry.cc
offline/packages/trackreco/MakeActsGeometry.h
offline/packages/trackreco/PHMicromegasTpcTrackMatching.cc
simulation/g4simulation/g4eval/TrackEvaluation.cc
simulation/g4simulation/g4main/PHG4Reco.cc
simulation/g4simulation/g4main/PHG4Reco.h
simulation/g4simulation/g4micromegas/PHG4MicromegasDetector.cc
simulation/g4simulation/g4micromegas/PHG4MicromegasDetector.h
simulation/g4simulation/g4micromegas/PHG4MicromegasHitReco.cc
simulation/g4simulation/g4micromegas/PHG4MicromegasHitReco.h
simulation/g4simulation/g4micromegas/PHG4MicromegasSteppingAction.cc
simulation/g4simulation/g4micromegas/PHG4MicromegasSubsystem.cc
simulation/g4simulation/g4micromegas/PHG4MicromegasSubsystem.h

This implements the latest TPOT geometry directly into geant 4. 
See https://indico.bnl.gov/event/14546/contributions/59761/attachments/39625/65748/talk.pdf for details
Depends on https://github.com/sPHENIX-Collaboration/macros/pull/488 and https://github.com/sPHENIX-Collaboration/coresoftware/pull/1400
- [] Breaking change (fix or feature that would cause existing functionality to not work for users) …

Tpot new geometry

---

offline/packages/KFParticle_sPHENIX/KFParticle_particleList.h
offline/packages/trackbase/ActsSurfaceMaps.h
offline/packages/trackbase/TpcSeedTrackMap.h
offline/packages/trackbase/TpcSeedTrackMapv1.h

A few small fixes when trying to compile coresoftware locally.

Small fixes

---

offline/framework/fun4all/Fun4AllDstInputManager.cc
offline/framework/fun4all/Fun4AllDstOutputManager.cc
offline/framework/fun4all/Fun4AllHistoManager.cc
offline/framework/fun4all/Fun4AllMemoryTracker.cc
offline/framework/fun4all/Fun4AllServer.cc
offline/framework/fun4all/Fun4AllSyncManager.cc
offline/framework/fun4all/configure.ac
offline/framework/phool/PHCompositeNode.cc
offline/framework/phool/PHCompositeNode.h
offline/framework/phool/PHDataNode.h
offline/framework/phool/PHFlag.cc
offline/framework/phool/PHIODataNode.h
offline/framework/phool/PHMessage.cc
offline/framework/phool/PHNode.cc
offline/framework/phool/PHNode.h
offline/framework/phool/PHNodeIOManager.cc
offline/framework/phool/PHNodeIntegrate.cc
offline/framework/phool/PHNodeIterator.cc
offline/framework/phool/PHNodeReset.cc
offline/framework/phool/PHObject.cc
offline/framework/phool/PHObject.h
offline/framework/phool/PHRandomSeed.cc
offline/framework/phool/PHTimeServer.cc
offline/framework/phool/PHTimeStamp.cc
offline/framework/phool/configure.ac
offline/framework/phool/getClass.h

This PR cleans up phool. We get a lot of compilation warnings from it which makes downstream life difficult. This should take care of that

Fixup phool

---

offline/packages/tpc/TpcClusterizer.cc

next memeory leak fix

---

simulation/g4simulation/g4main/PHG4Reco.cc
simulation/g4simulation/g4main/PHG4Reco.h

This PR takes care of an API difference between G4 10.04.p02 and 11.0.0

Prep g4 v11

---

simulation/g4simulation/g4detectors/PHG4InnerHcalSteppingAction.cc
simulation/g4simulation/g4detectors/PHG4InnerHcalSteppingAction.h
simulation/g4simulation/g4detectors/PHG4InnerHcalSubsystem.cc

Update light yield in PHG4InnerHcalSteppingAction.cc with iHCAL MEPHI maps

---

offline/framework/ffamodules/configure.ac
offline/framework/ffaobjects/configure.ac
offline/packages/CaloReco/BEmcCluster.cc
offline/packages/CaloReco/PHMakeGroups.h
offline/packages/CaloReco/RawClusterBuilderFwd.cc
offline/packages/CaloReco/RawClusterBuilderGraph.cc
offline/packages/CaloReco/RawTowerDeadMapLoader.cc
offline/packages/CaloReco/configure.ac

This PR adds -Wshadow to CalorReco and fixes the shadowed variables. No change in the output

Add wshadow

---

simulation/g4simulation/g4gdml/PHG4GDMLWrite.cc
simulation/g4simulation/g4gdml/PHG4GDMLWriteMaterials.cc
simulation/g4simulation/g4gdml/PHG4GDMLWriteMaterials.hh
simulation/g4simulation/g4gdml/PHG4GDMLWriteStructure.cc

Update the code to compile with G4 11.0 along with current versions

merge for changes in G4.11.0

---

offline/packages/tpccalib/Makefile.am
offline/packages/tpccalib/PHTpcCentralMembraneClusterizer.cc
offline/packages/tpccalib/PHTpcCentralMembraneClusterizer.h
offline/packages/tpccalib/PHTpcCentralMembraneMatcher.cc
offline/packages/tpccalib/PHTpcCentralMembraneMatcher.h
offline/packages/trackbase/CMFlashDifference.h
offline/packages/trackbase/CMFlashDifferenceContainer.h
offline/packages/trackbase/CMFlashDifferenceContainerLinkDef.h
offline/packages/trackbase/CMFlashDifferenceContainerv1.cc
offline/packages/trackbase/CMFlashDifferenceContainerv1.h
offline/packages/trackbase/CMFlashDifferenceContainerv1LinkDef.h
offline/packages/trackbase/CMFlashDifferenceLinkDef.h
offline/packages/trackbase/CMFlashDifferencev1.cc
offline/packages/trackbase/CMFlashDifferencev1.h
offline/packages/trackbase/CMFlashDifferencev1LinkDef.h
offline/packages/trackbase/Makefile.am

Adds a new module to match central membrane clusters to central membrane stripes. Modifies the central membrane cluster reconstruction module to better handle radius determination for the clusters. 

Central membrane cluster reconstruction and matching modules

---

offline/framework/frog/CreateFileList.pl
offline/framework/frog/FROG.cc

This switches the reading via minio to an endpoint served by 5 servers

S3 endpoint

---

simulation/g4simulation/g4detectors/Makefile.am
simulation/g4simulation/g4detectors/PHG4FullProjSpacalDetector.cc
simulation/g4simulation/g4detectors/PHG4InnerHcalSteppingAction.cc
simulation/g4simulation/g4detectors/PHG4PSTOFDetector.cc
simulation/g4simulation/g4detectors/PHG4ZDCDetector.cc

The temporary use of fastjet-config --libs to find the cgal dependencies resulted in a dependency of libg4detectors on fastjet. Since we don't have to support the old cgal version anymore, it is enough to link against libgmp.
Also with this PR valgrind is functional again. Nobody noticed that valgrind quit with an exception from cgal via fastjet and what we have seen so far is just from loading libraries until libg4detector resulted in an exception. The valgrind report from this …

Fix g4detectors

---

offline/framework/fun4all/Fun4AllDstInputManager.cc
offline/framework/fun4all/Fun4AllInputManager.cc
offline/framework/fun4all/Fun4AllInputManager.h

Today it took us a while to debug a fun4all crash. The underlying reason was an empty list file but that was not apparent from any error message. This change targets this particular problem. We cannot quit when reading an empty listfile since there may be more than one, but the user now gets a warning. The resulting crash in a completely different place is now handled with an exit and a message asking if the list file was empty and if not to ask for help since this may …

Empty listfile

---

offline/framework/ffaobjects/FlagSavev1.cc
offline/framework/ffaobjects/FlagSavev1.h
offline/framework/phool/PHFlag.cc
offline/framework/phool/PHFlag.h
offline/framework/phool/recoConsts.cc
simulation/g4simulation/g4main/HepMCNodeReader.cc
simulation/g4simulation/g4main/PHG4PhenixDetector.cc

This PR adds a uint64 type flag to store our 64 bit timestamp. This is also saved on the DST's ClassDef of FlagSavev1 version was set to 2

Add uint64 flag

---

simulation/g4simulation/g4main/Makefile.am
simulation/g4simulation/g4main/PHG4Reco.cc

This PR reads the fieldmap from the conditions DB if the magnetic field is set to CDB (it is the same 3d fieldmap, that should not change anything)

use cdb to fetch fieldmap when magnetic field is set to CDB

---

offline/framework/ffarawmodules/EventCombiner.cc
offline/framework/ffarawmodules/EventCombiner.h
offline/framework/ffarawmodules/Makefile.am
offline/framework/ffarawmodules/autogen.sh
offline/framework/ffarawmodules/configure.ac
offline/framework/fun4all/Fun4AllInputManager.h
offline/framework/fun4allraw/Fun4AllEventOutStream.cc
offline/framework/fun4allraw/Fun4AllEventOutStream.h
offline/framework/fun4allraw/Fun4AllEventOutputManager.cc
offline/framework/fun4allraw/Fun4AllEventOutputManager.h
offline/framework/fun4allraw/Fun4AllPrdfInputManager.cc
offline/framework/fun4allraw/Fun4AllPrdfInputManager.h
offline/framework/fun4allraw/configure.ac

This PR adds the Fun4All based event combiner

Ffa eventcombine

---

offline/packages/trackreco/PHActsTrkFitter.cc

This PR adds in the PID mass hypothesis as well as the PDG value to the Acts propagator. This will affect the material integration of Acts for different PID hypotheses.

Add PID mass to propagation

---

offline/packages/KFParticle_sPHENIX/KFParticle_DST.cc
offline/packages/KFParticle_sPHENIX/KFParticle_Tools.cc
offline/packages/KFParticle_sPHENIX/KFParticle_Tools.h
offline/packages/KFParticle_sPHENIX/KFParticle_eventReconstruction.cc
offline/packages/KFParticle_sPHENIX/KFParticle_sPHENIX.cc
offline/packages/KFParticle_sPHENIX/KFParticle_sPHENIX.h
offline/packages/KFParticle_sPHENIX/KFParticle_truthAndDetTools.cc

There is a better method to truth match reco'd tracks. I switched to this method.

Changed truth association for tracks

---

offline/packages/tpc/Makefile.am
offline/packages/tpc/TpcSimpleClusterizer.cc
offline/packages/tpc/TpcSimpleClusterizer.h

This PR introduces a simple TPC clusterizer that convert every single TPC hit into a cluster
This is used as an experiment for the direct laser reconstruction. 
Right now the module is not included in any reconstruction macro, so the change is armless. 

Tpc simple clusterizer

---

simulation/g4simulation/g4mvtx/PHG4MvtxDetector.cc
simulation/g4simulation/g4mvtx/PHG4MvtxSupport.cc
simulation/g4simulation/g4mvtx/PHG4MvtxSupport.h

Disabled hard-coded overlap check in MVTX support material 

Disabled overlap check

---

offline/packages/trackreco/AssocInfoContainer.cc
offline/packages/trackreco/AssocInfoContainer.h
offline/packages/trackreco/AssocInfoContainerLinkDef.h
offline/packages/trackreco/AssocInfoContainerv1.cc
offline/packages/trackreco/AssocInfoContainerv1.h
offline/packages/trackreco/AssocInfoContainerv1LinkDef.h
offline/packages/trackreco/Makefile.am

This PR adds the old AssocInfoContainer back to make old DSTs readable again

Assoc info container

---

offline/framework/phool/PHRandomSeed.h
simulation/g4simulation/g4main/PHG4Reco.cc

Adding debug features to print out G4 random number engine status at higher `PHRandomSeed::Verbosity()` settings

G4 random number checks

---

offline/framework/fun4all/Fun4AllMonitoring.cc
offline/framework/fun4all/Fun4AllMonitoring.h
offline/framework/fun4all/Fun4AllServer.cc
offline/framework/fun4all/Fun4AllServer.h
offline/framework/fun4all/Makefile.am

This PR adds an event wise heap tracker, if enabled the allocated heap memory is printed into a file for every event (before it is cleared)

Heaptracker

---

offline/packages/intt/InttClusterizer.cc
offline/packages/micromegas/MicromegasClusterizer.cc
offline/packages/mvtx/MvtxClusterizer.cc
offline/packages/tpc/TpcClusterizer.cc
offline/packages/tpc/TpcClusterizer.h
offline/packages/tpc/TpcSimpleClusterizer.cc
offline/packages/tpccalib/PHTpcCentralMembraneClusterizer.cc
offline/packages/trackbase/Makefile.am
offline/packages/trackbase/TrkrClusterContainer.cc
offline/packages/trackbase/TrkrClusterContainer.h
offline/packages/trackbase/TrkrClusterContainerv2.cc
offline/packages/trackbase/TrkrClusterContainerv2.h
offline/packages/trackbase/TrkrClusterContainerv3.cc
offline/packages/trackbase/TrkrClusterContainerv3.h
offline/packages/trackbase/TrkrClusterContainerv4.cc
offline/packages/trackbase/TrkrClusterContainerv4.h
offline/packages/trackbase/TrkrClusterContainerv4LinkDef.h
offline/packages/trackreco/PHSiliconTpcTrackMatching.cc
offline/packages/trackreco/PHTpcClusterMover.cc
offline/packages/trackreco/PHTruthClustering.cc
offline/packages/trackreco/PHTruthSiliconAssociation.cc

This pull request introduces a new cluster container that stores clusters in a std::vector rather than a std::map
Performances are discussed here: https://indico.bnl.gov/event/15452/contributions/62759/attachments/40662/67929/talk.pdf
Also cleaned up TPC clusterizer and TPC simple clusterizer, and used std::thread instead of pthread.
The former is more modern, does the same under the hood, but should be more future proof (and platform independent, which is irrelevant here)
[comment]: <> ( In case this is a draft PR, e.g. for running …

Cluster container

---

offline/packages/trackreco/PHActsTrackProjection.cc

The fatal crash has since been fixed by Acts such that we can catch it, therefore we don't need the fatal logging anymore.

change Acts log to info instead of fatal

---

offline/framework/frog/CreateFileList.pl
simulation/g4simulation/g4mvtx/PHG4EICMvtxSteppingAction.cc
simulation/g4simulation/g4mvtx/PHG4MvtxCable.h
simulation/g4simulation/g4mvtx/PHG4MvtxDigitizer.cc
simulation/g4simulation/g4mvtx/PHG4MvtxDisplayAction.cc
simulation/g4simulation/g4mvtx/PHG4MvtxHitReco.cc
simulation/g4simulation/g4mvtx/PHG4MvtxSteppingAction.cc
simulation/g4simulation/g4mvtx/PHG4MvtxSubsystem.cc
simulation/g4simulation/g4mvtx/PHG4MvtxSupport.cc
simulation/g4simulation/g4mvtx/PHG4MvtxSupport.h

CreateFileList.pl picked up pythia embedded into hijing files as hijing files (the G4Hits nobody really uses)
Include What You Use for simulation/g4simulation/g4mvtx as continuous maintenance

Getfilelist

---

offline/packages/trackreco/PHTruthTrackSeeding.cc
offline/packages/trackreco/PHTruthTrackSeeding.h

... , to ensure reproducibility if needed

use PHRandomSeed and gsl for momentum random smearing

---

simulation/g4simulation/g4main/CosmicSpray.cc
simulation/g4simulation/g4main/CosmicSpray.h
simulation/g4simulation/g4main/EcoMug.h
simulation/g4simulation/g4main/Makefile.am

A cosmic muon generator that gives realistic energy and angular distribution. The output agrees with the real cosmic muon data( https://arxiv.org/pdf/1606.06907.pdf).
See the presentation at:
https://indico.bnl.gov/event/15107/
The simulation results for oHCal have the MIP distribution agree with the 912 oHCal cosmic testing result. 
https://indico.bnl.gov/event/15279/ …

cosmic muon generator

---

offline/framework/fun4allraw/Fun4AllFileOutStream.cc
offline/framework/fun4allraw/Fun4AllFileOutStream.h
offline/framework/fun4allraw/Fun4AllRolloverFileOutStream.cc

This PR increases the maximum prdf output filesize from 10GB to 100GB. This limit is just a safeguard against users doing completely crazy things 

100 gb prdf

---

simulation/g4simulation/g4tpc/PHG4TpcCentralMembrane.cc
simulation/g4simulation/g4tpc/PHG4TpcCentralMembrane.h

This PR makes sure that central membrane flashes generates G4Hits on both sides of the central membrane instead of positive-z only. 
Also removes unused code and class members

Central membrane

---

offline/packages/trackbase/Makefile.am
offline/packages/trackbase/TrkrHitTruthClusters.h
offline/packages/trackbase/TrkrHitTruthClustersLinkDef.h
offline/packages/trackbase/TrkrHitTruthClustersv1.cc
offline/packages/trackbase/TrkrHitTruthClustersv1.h
offline/packages/trackbase/TrkrHitTruthClustersv1LinkDef.h
simulation/g4simulation/g4tpc/PHG4TpcElectronDrift.cc
simulation/g4simulation/g4tpc/PHG4TpcElectronDrift.h

[comment]: <
This update add a the object `TrkrHitTruthClusters` which calculates and stores the mean and standard deviation of the phi, eta, and R, location of the clusters of hits resulting from each electron from an embedded track. 
> (Please tell us something about this pull request)

Pull request to node for TrkrHitTruthCluster

---

calibrations/calorimeter/calo_tower_slope/macro/README.md
offline/framework/fun4all/CreateSubsysRecoModule.pl

mark dtor override instead of virtual
[skip ci]

Fix createsubsys

---

offline/packages/centrality/CentralityInfo.h
simulation/g4simulation/g4centrality/EpFinder.C
simulation/g4simulation/g4centrality/EpFinder.h
simulation/g4simulation/g4centrality/EpInfo.C
simulation/g4simulation/g4centrality/EpInfo.h
simulation/g4simulation/g4centrality/Makefile.am
simulation/g4simulation/g4centrality/PHG4CentralityReco.cc
simulation/g4simulation/g4centrality/PHG4CentralityReco.h

This PR adds event plane information from the sPHENIX EPD to the existing centrality module.

Add sEPD event plane info to centrality module

---

simulation/g4simulation/g4ihcal/PHG4IHCalDetector.cc
simulation/g4simulation/g4ihcal/PHG4IHCalDetector.h

This PR fixes the mapping. It now is identical to the mapping of the previous inner hcal so subsequent code works unmodified. Using geantinos the input theta/phi is reflected by the theta/phi of the tower which gets hit

Ihcal mapping

---

offline/framework/frog/CreateFileList.pl

This PR adds a pileup rate selection to the CreateFileList.pl. No need to kick off jenkins for this 
[skip ci]

Add pileup rate selection

---

simulation/g4simulation/g4ihcal/PHG4IHCalDetector.cc
simulation/g4simulation/g4ihcal/PHG4IHCalDetector.h
simulation/g4simulation/g4ihcal/PHG4IHCalSteppingAction.cc
simulation/g4simulation/g4ihcal/PHG4IHCalSubsystem.cc

This PR saves the sector id in the inner hcal PHG4Hits. The sector id is not propagated further yet, we need to discuss if we want that. It might turn out useful for data/simulation comparisons and alignments

Ihcal mods

---

offline/packages/trackreco/PHSiliconTpcTrackMatching.cc

This just speeds up the search loop in PHSiliconTpcTrackMatching so that it handles very large events more efficiently. 

Speed up search loop in track matcher

---

offline/framework/frog/CreateFileList.pl

The nopileup selection for MB pp returned pileup files - fixed 
[skip ci]

add -nopileup handling to type 3 (pp mb)

---

offline/packages/tpccalib/TpcDirectLaserReconstruction.cc
offline/packages/tpccalib/TpcDirectLaserReconstruction.h

This adds setting of the TPC drift velocity in tpccalib/TpcDirectLaserReconstruction, which I overlooked in PR#1547.

Global drift velocity

---

offline/packages/CaloReco/BEmcCluster.cc
offline/packages/CaloReco/BEmcCluster.h
offline/packages/CaloReco/BEmcProfile.cc
offline/packages/CaloReco/BEmcProfile.h
offline/packages/CaloReco/BEmcRec.cc
offline/packages/CaloReco/BEmcRec.h
offline/packages/CaloReco/PHMakeGroups.h
offline/packages/CaloReco/RawClusterBuilderFwd.cc
offline/packages/CaloReco/RawClusterBuilderGraph.cc
offline/packages/CaloReco/RawClusterBuilderTemplate.cc
offline/packages/CaloReco/RawClusterBuilderTemplate.h
offline/packages/CaloReco/RawTowerDeadMapLoader.h
simulation/g4simulation/g4main/PHG4Reco.cc

This PR adds the capability to read the fieldmap for the sims and the cemc profile thresholds from the DB (if enabled).
Also fixed a ton if cppcheck warnings in offline/packages/CaloReco. The math in BEmcRec is not stable, looks like float precision is not good enough to ensure reproducibility. There are last digit diffs after fixing the cppcheck warnings (reduced scope?)  …

Use xpload

---

offline/packages/mvtx/MvtxClusterizer.cc

this PR comments out the printing of
pitch: 0.002688
length: 0.002924
no need to run jenkins
[skip ci]

remove leftover printout

---

offline/QA/modules/QAG4SimulationMicromegas.cc

This was a consequence from https://github.com/sPHENIX-Collaboration/coresoftware/pull/1552, resulting in Micromegas QA plots all being broken. 
Now fixed (hopefully)

fixed micromegas QA

---

offline/QA/modules/Makefile.am
offline/QA/modules/QAG4SimulationTruthDecay.cc
offline/QA/modules/QAG4SimulationTruthDecay.h
offline/QA/modules/truthDecayTester.cc
offline/QA/modules/truthDecayTester.h

Adding the truth decay QA module, truthDecayTester

---

offline/packages/tpc/TpcClusterizer.cc
offline/packages/trackbase/ActsGeometry.cc
offline/packages/trackreco/PHActsTrkFitter.cc

This PR removes the various places where we would pull the TPC surface and do a manual transformation for local->global or vice versa and replaces it with the simpler `transform` method. This is cleaner and requires less code to be passed around.

TPC cluster transform simplification

---

offline/packages/trackbase/sPHENIXActsDetectorElement.h
offline/packages/trackreco/PHActsGSF.cc

This PR fixes two clang warnings which prevent this from compiling with clang

fix clang warnings

---

offline/packages/tpc/TpcClusterCleaner.cc
offline/packages/tpc/TpcClusterCleaner.h
offline/packages/trackbase/ClusterErrorPara.h
offline/packages/trackreco/ALICEKF.cc
offline/packages/trackreco/ALICEKF.h
offline/packages/trackreco/PHActsSiliconSeeding.cc
offline/packages/trackreco/PHActsSiliconSeeding.h
offline/packages/trackreco/PHActsTrkFitter.cc
offline/packages/trackreco/PHActsTrkFitter.h
offline/packages/trackreco/PHSimpleKFProp.cc
simulation/g4simulation/g4eval/SvtxEvaluator.cc

This pull request put all the code in place to use cluster version 4.. Cluster version 4 does not explicitly store the errors per cluster, but uses a lookup from a cluster error parameterization instead. Current default remains to use cluster version 3, so this PR should be transparent. Once all formal code checking is done, we will update the defaults to change the code behaviour.  …

prepare switch to cluster version 4

---

calibrations/calorimeter/calo_tower_slope/LiteCaloEval.cc
calibrations/calorimeter/calo_tower_slope/LiteCaloEval.h
calibrations/calorimeter/dbfile_accessor_calo/CEmcCaloCalibSimpleCorrFilev1.cc
calibrations/calorimeter/dbfile_accessor_calo/CEmcCaloCalibSimpleCorrFilev1.h
calibrations/calorimeter/dbfile_accessor_calo/CaloCalibSimpleCorrFile.h
calibrations/calorimeter/dbfile_accessor_calo/HcalCaloCalibSimpleCorrFilev1.cc
calibrations/calorimeter/dbfile_accessor_calo/HcalCaloCalibSimpleCorrFilev1.h
offline/packages/particleflow/Makefile.am
offline/packages/particleflow/ParticleFlowReco.cc
offline/packages/particleflow/ParticleFlowReco.h

This PR removes the truth information from the PF algorithm and replaces the truth tracks with the reco tracks. The algorithm itself otherwise looks identical.
macros [pr](https://github.com/sPHENIX-Collaboration/macros/pull/534) that should be merged before this PR is merged.

Remove truth tracks from ParticleFlow

---

simulation/g4simulation/g4main/PHG4HeadReco.cc
simulation/g4simulation/g4main/PHG4HeadReco.h

This PR removes the flag saving from the PHG4HeadReco module. This is now done by the FlagHandler which then also restores them properly and saves possibly added flags

remove flagsave, now done by flag handler

---

simulation/g4simulation/g4detectors/PHG4SpacalSteppingAction.cc
simulation/g4simulation/g4detectors/PHG4SpacalSteppingAction.h
simulation/g4simulation/g4detectors/PHG4SpacalSubsystem.cc
simulation/g4simulation/g4detectors/PHG4SpacalSubsystem.h
simulation/g4simulation/g4detectors/PHG4ZDCSteppingAction.cc
simulation/g4simulation/g4detectors/PHG4ZDCSubsystem.cc

This PR moves the G4HIT_CEMC and G4HIT_ABSORBER_CEMC node under the CEMC composite node together with all the other cemc nodes

Cemc dstbranch

---

offline/packages/trackreco/ALICEKF.cc

the logs get filled with  
lversion: 3
This PR comments this out - no need to run ci
[skip ci]

comment out lversion printout

---

offline/packages/tpc/TpcClusterizer.cc

This fixes the TPC cluster z error and should fix both the TPC cluster QA and the high pT DCA_z resolution.

fix cluster z error

---

offline/packages/intt/InttClusterizer.h
offline/packages/micromegas/MicromegasClusterizer.h
offline/packages/mvtx/MvtxClusterizer.h
offline/packages/tpc/TpcClusterCleaner.h
offline/packages/tpc/TpcClusterizer.h
offline/packages/trackreco/ALICEKF.h
offline/packages/trackreco/PHActsSiliconSeeding.h
offline/packages/trackreco/PHActsTrkFitter.h
simulation/g4simulation/g4eval/SvtxEvaluator.h

change to cluster v4. For real this time

---

offline/packages/trackbase/ClusterErrorPara.cc

updated error parametrization

---

offline/packages/intt/InttClusterizer.h
offline/packages/micromegas/MicromegasClusterizer.h
offline/packages/mvtx/MvtxClusterizer.h
offline/packages/tpc/TpcClusterCleaner.h
offline/packages/tpc/TpcClusterizer.h
offline/packages/trackreco/ALICEKF.h
offline/packages/trackreco/PHActsSiliconSeeding.h
offline/packages/trackreco/PHActsTrkFitter.h
simulation/g4simulation/g4eval/SvtxEvaluator.h

Reverts sPHENIX-Collaboration/coresoftware#1590 and moves us back to cluster v3

Revert "change to cluster v4. For real this time"

---

offline/database/PHParameter/PHParameterInterface.cc
offline/database/PHParameter/PHParameterInterface.h
simulation/g4simulation/g4calo/HcalRawTowerBuilder.cc
simulation/g4simulation/g4calo/HcalRawTowerBuilder.h
simulation/g4simulation/g4calo/RawTowerBuilder.cc
simulation/g4simulation/g4calo/RawTowerBuilder.h
simulation/g4simulation/g4calo/RawTowerBuilderByHitIndex.cc
simulation/g4simulation/g4calo/RawTowerBuilderByHitIndex.h
simulation/g4simulation/g4calo/RawTowerDigitizer.cc
simulation/g4simulation/g4calo/RawTowerDigitizer.h

This PR adds the capability to add an offset to the tower phi for the hcal. It turns out the phi coverage in the simulations is shifted with respect to the tower geometry we assign. This will be followed by a macro change which will then implement the correct offsets 

Fix tower geom

---

calibrations/tpc/fillSpaceChargeMaps/Makefile.am
calibrations/tpc/fillSpaceChargeMaps/Shifter.cc
calibrations/tpc/fillSpaceChargeMaps/Shifter.h
calibrations/tpc/fillSpaceChargeMaps/configure.ac
calibrations/tpc/fillSpaceChargeMaps/fillSpaceChargeMaps.cc
calibrations/tpc/fillSpaceChargeMaps/fillSpaceChargeMaps.h
calibrations/tpc/fillSpaceChargeMaps/fillSpaceChargeMapsLinkDef.h

This PR is mainly a cleanup - fix cppcheck warnings, remove superfluous includes,...

Fix fill space charge maps

---

simulation/g4simulation/g4detectors/PHG4InnerHcalSteppingAction.cc
simulation/g4simulation/g4detectors/PHG4OuterHcalSteppingAction.cc
simulation/g4simulation/g4ihcal/PHG4IHCalSteppingAction.cc
simulation/g4simulation/g4main/PHG4Hit.cc
simulation/g4simulation/g4main/PHG4Hit.h
simulation/g4simulation/g4main/PHG4Hitv1.h
simulation/g4simulation/g4ohcal/PHG4OHCalSteppingAction.cc

This PR adds a raw_light_yield property to the G4Hits. Hijacking eion to store the raw light yield will be too confusing in the long run and we probably want to be able to check the effect of those efficiency maps occasionally

Raw light yield

---

simulation/g4simulation/g4tpc/PHG4TpcCentralMembrane.cc
simulation/g4simulation/g4tpc/PHG4TpcCentralMembrane.h
simulation/g4simulation/g4tpc/PHG4TpcDetector.cc
simulation/g4simulation/g4tpc/PHG4TpcDetector.h
simulation/g4simulation/g4tpc/PHG4TpcDigitizer.cc
simulation/g4simulation/g4tpc/PHG4TpcDirectLaser.h
simulation/g4simulation/g4tpc/PHG4TpcDisplayAction.cc
simulation/g4simulation/g4tpc/PHG4TpcDistortion.cc
simulation/g4simulation/g4tpc/PHG4TpcDistortion.h
simulation/g4simulation/g4tpc/PHG4TpcElectronDrift.cc
simulation/g4simulation/g4tpc/PHG4TpcElectronDrift.h
simulation/g4simulation/g4tpc/PHG4TpcEndCapDetector.cc
simulation/g4simulation/g4tpc/PHG4TpcEndCapDetector.h
simulation/g4simulation/g4tpc/PHG4TpcEndCapDisplayAction.h
simulation/g4simulation/g4tpc/PHG4TpcPadBaselineShift.h
simulation/g4simulation/g4tpc/PHG4TpcPadPlane.h
simulation/g4simulation/g4tpc/PHG4TpcPadPlaneReadout.cc
simulation/g4simulation/g4tpc/PHG4TpcPadPlaneReadout.h
simulation/g4simulation/g4tpc/PHG4TpcSteppingAction.cc
simulation/g4simulation/g4tpc/PHG4TpcSteppingAction.h
simulation/g4simulation/g4tpc/PHG4TpcSubsystem.cc

This PR puts an old issue to rest, prevent accidental running of the tpc without stepsize by initializing it to 1cm. fixed cppcheck warnings, include what you use and clang-format

Remove tpc g4steps

---

simulation/g4simulation/g4jets/Jet.h

feature
This PR adds three additional jet properties to the Jet object which enables the tagging of truth jets as photons, or from heavy flavor.

added three additional jet properties to enable HF and photon tagging

---

offline/framework/frog/CreateFileList.pl

clarify description for jet samples (mention pt cut instead of R), no need for jenkins
[skip ci]

change type 11,12 description to GeV cut

---

simulation/g4simulation/g4detectors/BeamLineMagnetSubsystem.cc
simulation/g4simulation/g4detectors/PHG4BbcSubsystem.cc
simulation/g4simulation/g4detectors/PHG4InnerHcalSubsystem.cc
simulation/g4simulation/g4detectors/PHG4OuterHcalSubsystem.cc
simulation/g4simulation/g4detectors/PHG4PSTOFSubsystem.cc
simulation/g4simulation/g4detectors/PHG4SectorConstructor.h
simulation/g4simulation/g4detectors/PHG4SpacalSubsystem.cc
simulation/g4simulation/g4detectors/PHG4ZDCSubsystem.cc

This PR fixes some benign cppcheck warnings to trigger jenkins to test the new cppcheck version (2.8).

fix new cppcheck warning

---

simulation/g4simulation/g4detectors/PHG4DetectorSubsystem.cc
simulation/g4simulation/g4detectors/PHG4DetectorSubsystem.h
simulation/g4simulation/g4detectors/PHG4FullProjTiltedSpacalDetector.cc
simulation/g4simulation/g4detectors/PHG4GDMLDetector.cc
simulation/g4simulation/g4detectors/PHG4GDMLDetector.h
simulation/g4simulation/g4detectors/PHG4GDMLSubsystem.cc
simulation/g4simulation/g4detectors/PHG4GDMLSubsystem.h
simulation/g4simulation/g4detectors/PHG4GenHit.cc
simulation/g4simulation/g4detectors/PHG4GenHit.h
simulation/g4simulation/g4detectors/PHG4HcalDetector.cc

This PR adds reading from the conditions DB to the PHG4DetectorSubsystem base class

Phg4 detector subsystem use cdb

---

offline/packages/NodeDump/DumpCdbUrlSave.cc
offline/packages/NodeDump/DumpCdbUrlSave.h
offline/packages/NodeDump/Makefile.am
offline/packages/NodeDump/PHNodeDump.cc
simulation/g4simulation/g4calo/HcalRawTowerBuilder.cc
simulation/g4simulation/g4calo/HcalRawTowerBuilder.h
simulation/g4simulation/g4calo/RawTowerDigitizer.cc

This PR adds the capability to add another "detector" to the HcalRawTower builder so one can fill more than one input (light yield, raw light yield, eion or edep) for easier comparison
Add dump of CdbUrl node

Build multiple towers

---

simulation/g4simulation/g4detectors/PHG4BbcDetector.cc
simulation/g4simulation/g4detectors/PHG4BbcDisplayAction.cc
simulation/g4simulation/g4detectors/PHG4DetectorGroupSubsystem.cc
simulation/g4simulation/g4detectors/PHG4DetectorGroupSubsystem.h

This PR makes the bbc cables which stick out 125cm vertically visible in the display

Bbc cables

---

offline/packages/NodeDump/DumpTrkrClusterContainer.cc
offline/packages/trackbase/TrkrClusterContainerv3.cc
offline/packages/trackbase/TrkrClusterContainerv4.cc
offline/packages/trigger/CaloTriggerInfov1.cc
offline/packages/trigger/CaloTriggerInfov1.h
offline/packages/trigger/CaloTriggerSim.cc
offline/packages/trigger/CaloTriggerSim.h

Parts of the TrkrClusterContainer identify was piped to cout instead of the ostream from the argument. Also removed obsolete values from the trkrclustercontainer dump

Dump fixes

---

.clang-tidy

add clang-tidy to start with clang-tidy

start with clang-tidy

---

offline/packages/trackreco/MakeActsGeometry.cc

This PR checks if the Acts fake surfaces were already built so that we don't inadvertently write over them. The problem arises because the TGeoManager is a singleton, so it persists on the DST.

Check surfaces

---

simulation/g4simulation/g4ihcal/PHG4IHCalSteppingAction.cc
simulation/g4simulation/g4ohcal/PHG4OHCalSteppingAction.cc

Until the new maps for the light corrections exist, this is commented out in the inner/outer hcal stepping action for the new gdml based hcals

Light maps gdml

---

simulation/g4simulation/g4detectors/PHG4InnerHcalSteppingAction.cc
simulation/g4simulation/g4detectors/PHG4OuterHcalSteppingAction.cc
simulation/g4simulation/g4detectors/PHG4ZDCSteppingAction.cc
simulation/g4simulation/g4main/PHG4SteppingAction.cc

performance suggestions by clang-tidy: This PR uses const & references for some variables in the stepping actions to avoid copying the data. 
Main reason is to trigger jenkins with the new hcals 

Use consts

---

simulation/g4simulation/g4jets/JetMapv1.cc

fixes a crash in g4jets (missing std::)
[skip-ci]

fix compilation crash

---

simulation/g4simulation/g4ihcal/PHG4IHCalDetector.cc

The inner hcal prints out the sectors - removing this
[skip-ci]

remove ihcal sector printout

---

simulation/g4simulation/g4tpc/PHG4TpcDetector.cc
simulation/g4simulation/g4tpc/PHG4TpcEndCapSubsystem.cc
simulation/g4simulation/g4tpc/PHG4TpcSubsystem.cc

- [] Bug fix (non-breaking change which fixes an issue)
This PR implements an update to the TPC hanger beams to reflect an updated design. The key change is the removal of 2 stainless steel rods which ran the full length of the TPC and the replacement of them with 4 short stainless steel rods and the addition of two carbon fiber tubes which run the full length of the TPC. Additionally the material has been extended in length to reflect their size in the engineering drawings.
[comment]: <> ( In case this is a draft PR, e.g. for running …

modified the TPC hanger materials to reflect updated design

---

offline/framework/frog/CreateFileList.pl

This PR prints out the existing single particle dst types (since we now have more than just G4Hits)
[skip-ci]

print out dst types for single particles

---

offline/framework/frog/CreateFileList.pl

This PR adds a flag to select the last segment in the returned lists (useful for selections in batch jobs)
[skip-ci]

add switch for last segment

---

simulation/g4simulation/g4mvtx/PHG4MvtxSupport.cc

This PR fixes one of the many memory leaks in the mvtx support

fix one of many memory leaks in the mvtx support

---

offline/framework/frog/CreateFileList.pl

This PR just adds the listing for special productions (those which don't fit anywhere). It is just the perl script, no point to run jenkins
[skip-ci]

add special production listing

---

offline/packages/trackbase/TrkrHitSetContainerv1.cc
offline/packages/trackbase/TrkrHitSetv1.cc
offline/packages/trackreco/ALICEKF.h
offline/packages/trackreco/PHCASeeding.cc
offline/packages/trackreco/PHSimpleKFProp.cc
offline/packages/trackreco/PHSimpleKFProp.h
simulation/g4simulation/g4eval/SvtxTruthRecoTableEval.cc
simulation/g4simulation/g4eval/SvtxTruthRecoTableEval.h
simulation/g4simulation/g4mvtx/PHG4MvtxHitReco.cc

This PR aims to clean up some of the memory leaks in the tracking.

Tracking memory leak clean up

---

offline/packages/CaloReco/CaloWaveformProcessing.cc

Simple fix to CaloWaveformProcessing in order to remove a warning during compilation in Jenkins

fixed a bug causing compilation warnings to CaloWavefromProcessing

---

.clang-tidy
offline/packages/NodeDump/DumpCentralityInfo.cc
offline/packages/NodeDump/DumpEventHeader.cc
offline/packages/NodeDump/DumpInttDeadMap.cc
offline/packages/NodeDump/DumpObject.cc
offline/packages/NodeDump/DumpPHFieldConfig.cc
offline/packages/NodeDump/DumpPHG4BlockCellGeomContainer.cc
offline/packages/NodeDump/DumpPHG4CellContainer.cc
offline/packages/NodeDump/DumpPHG4HitContainer.cc
offline/packages/NodeDump/DumpPHG4ParticleSvtxMap.cc
offline/packages/NodeDump/DumpPHGenIntegral.cc
offline/packages/NodeDump/DumpPHGenIntegral.h
offline/packages/NodeDump/DumpRunHeader.cc
offline/packages/NodeDump/DumpSvtxPHG4ParticleMap.cc
offline/packages/NodeDump/DumpTrkrClusterContainer.cc
offline/packages/NodeDump/Dumper.cc
offline/packages/NodeDump/Makefile.am
offline/packages/NodeDump/PHNodeDump.cc

This PR adds the ascii printout for the PHGentIntegral node. Implemented suggestions by clang-tidy, added more checks to clang-tidy config

Dump ph gen integral

---

offline/framework/frog/CreateFileList.pl

This add D0 Jets to CreateFileList.pl as type 16 
[skip-ci]

Add type 16 for d0 Jets in CreateFileList.pl

---

simulation/g4simulation/g4tpc/TpcClusterBuilder.cc
simulation/g4simulation/g4tpc/TpcClusterBuilder.h

This PR fixes the fallout from merging several tracking PRs this morning.

Fix master

---

generators/PHPythia8/PHPy8GenTrigger.cc
generators/PHPythia8/PHPy8JetTrigger.cc
generators/PHPythia8/PHPy8ParticleTrigger.cc
generators/PHPythia8/PHPythia8.cc
offline/framework/ffamodules/SyncReco.cc
offline/framework/ffamodules/SyncReco.h
offline/framework/ffamodules/XploadInterface.cc
offline/framework/ffaobjects/CdbUrlSavev1.cc
offline/framework/ffaobjects/SyncObject.h
offline/framework/ffaobjects/SyncObjectv1.h

This PR adds the capability to change the segment number from the macro. This is needed for embedding where the segment number is taken from the background file but you want to use the background file multiple times

Force sync segment

---

.clang-tidy
simulation/g4simulation/g4detectors/PHG4InnerHcalSteppingAction.cc
simulation/g4simulation/g4detectors/PHG4InnerHcalSubsystem.cc
simulation/g4simulation/g4detectors/PHG4OuterHcalSteppingAction.cc
simulation/g4simulation/g4detectors/PHG4OuterHcalSubsystem.cc
simulation/g4simulation/g4ihcal/PHG4IHCalDetector.cc
simulation/g4simulation/g4ihcal/PHG4IHCalDetector.h
simulation/g4simulation/g4ihcal/PHG4IHCalSteppingAction.cc
simulation/g4simulation/g4ihcal/PHG4IHCalSubsystem.cc
simulation/g4simulation/g4ohcal/PHG4OHCalDetector.cc
simulation/g4simulation/g4ohcal/PHG4OHCalSteppingAction.cc
simulation/g4simulation/g4ohcal/PHG4OHCalSubsystem.cc

This PR moves the hardcoded Mephi maps to PHParameters so we keep a record of what was used and can change them in the macro for testing, the new hcal uses an empty string right now since the mal does not exist yet

Mephi map params

---

offline/packages/trackreco/ALICEKF.cc
offline/packages/trackreco/ALICEKF.h

Attempt to fix SimpleKf execution speed

simplekf speed fix

---

simulation/g4simulation/g4eval/SvtxEvaluator.cc

This PR checks that the track has a vertex before calculating the DCA, which catches a seg fault that occurs when running with low occupancy distorted seeds only.

Check vertex in evaluator

---

offline/packages/NodeDump/DumpJetMap.cc
offline/packages/NodeDump/DumpPHG4CellContainer.cc
offline/packages/NodeDump/DumpPHG4HitContainer.cc
offline/packages/NodeDump/DumpPHG4ParticleSvtxMap.cc
offline/packages/NodeDump/DumpSvtxPHG4ParticleMap.cc
offline/packages/NodeDump/DumpTrkrHitTruthClusters.cc
offline/packages/NodeDump/DumpTrkrHitTruthClusters.h
offline/packages/NodeDump/Makefile.am
offline/packages/NodeDump/PHNodeDump.cc
offline/packages/trackbase/Makefile.am
offline/packages/trackbase/TrkrHitTruthClusters.h
offline/packages/trackbase/TrkrHitTruthClustersLinkDef.h
offline/packages/trackbase/TrkrHitTruthClustersv1.cc
offline/packages/trackbase/TrkrHitTruthClustersv1.h
offline/packages/trackbase/TrkrHitTruthClustersv1LinkDef.h

Removing the TrkrHitTruthClusters killed the readback of existing DSTs, this PR adds them back

Putback trkr hit truth clusters

---

offline/packages/trackreco/PHActsGSF.cc
offline/packages/trackreco/PHActsGSF.h
offline/packages/trackreco/PHActsTrkFitter.cc

This PR updates the GSF to use clusterv4. It also uncovers that Acts still segfaults in single electron cases. Bug report and reproducibility logs sent to primary Acts::GSF developer.

Update GSF to use clusterv4

---

offline/packages/CaloReco/CaloWaveformProcessing.cc
offline/packages/CaloReco/CaloWaveformProcessing.h

This PR generalizes the CaloWaveformProcessing module to work with any of the calorimeter systems. 
This PR improves the generalization of the waveform processing module in order to enable it to work without change on any of the calorimeter systems. This change as it is no longer compatible with the old template files on the CDB, modified versions of the files have been requested to be updated in the CDB. This should not effect any end user. …

modified the name of the template profile being pulled from the CDB

---

simulation/g4simulation/g4micromegas/PHG4MicromegasHitReco.cc
simulation/g4simulation/g4micromegas/PHG4MicromegasHitReco.h

Add smearing factors to allow to adjust Micromegas resolution to measured values
By default no smearing is added 

Micromegas fix

---

simulation/g4simulation/g4ohcal/PHG4OHCalSteppingAction.cc
simulation/g4simulation/g4ohcal/PHG4OHCalSteppingAction.h
simulation/g4simulation/g4ohcal/PHG4OHCalSubsystem.cc

This PR adds the mephi maps for the new ohcal. Attached are relevant pdfs of the maps. The 4 chimney tiles are not unique. They are modified clones of existing maps as indicated in chimneytiles.pdf.
[Regular_tiles.pdf](https://github.com/sPHENIX-Collaboration/coresoftware/files/9792472/Regular_tiles.pdf)
[Chimney_tiles.pdf](https://github.com/sPHENIX-Collaboration/coresoftware/files/9792473/Chimney_tiles.pdf)
[chimneytiles.pdf](https://github.com/sPHENIX-Collaboration/coresoftware/files/9792476/chimneytiles.pdf)

adding mephi maps for new ohcal 

---

offline/framework/phool/onnxlib.cc
offline/framework/phool/onnxlib.h

Removed an unused function that included a memory leak. 

removed an unused function

---

offline/packages/tpc/TpcClusterMover.cc

Wrap this warning into a verbosity statement for tracking expert use.

Verbosity statement

---

offline/packages/trackreco/Makefile.am
offline/packages/trackreco/PHCASeeding.h
offline/packages/trackreco/configure.ac

This PR removes the compiler checks before building our acts code - we will not run without acts and keeping this functionality just introduces room for problems (awk says 12.1 < 8.3) 

Always build acts

---

simulation/g4simulation/g4eval/SvtxHitEval.cc
simulation/g4simulation/g4eval/SvtxHitEval.h

SvtxHitEval: truth matching with trkrid as an additional argument

---

offline/packages/trackbase/Makefile.am
offline/packages/trackbase/TrkrTruthClusters.cc
offline/packages/trackbase/TrkrTruthClusters.h
offline/packages/trackbase/TrkrTruthTrack.cc
offline/packages/trackbase/TrkrTruthTrack.h
offline/packages/trackbase/TrkrTruthTrackContainer.cc
offline/packages/trackbase/TrkrTruthTrackContainer.h
offline/packages/trackbase/TrkrTruthTrackv1.cc
offline/packages/trackbase/TrkrTruthTrackv1.h
simulation/g4simulation/g4tpc/PHG4TpcElectronDrift.cc
simulation/g4simulation/g4tpc/TpcClusterBuilder.cc

Classes updated are:
TrkrTruthClusters
TrkrTruthTrack
TrkrTruthTrackContainer
See comments above. This is a little light refactoring to make base classes to be not pure virtual classes.

Make base classes not pure virtual

---

offline/packages/trackreco/PHActsTrackProjection.cc
offline/packages/trackreco/PHActsTrackProjection.h

This PR makes the track projection module dependent on only the usual sPHENIX DST nodes so that it can be run as a part of either the full production or at user analysis level.

Make track projections standalone

---

offline/packages/tpc/TpcClusterZCrossingCorrection.cc
offline/packages/tpc/TpcClusterZCrossingCorrection.h
offline/packages/tpccalib/PHTpcResiduals.cc
offline/packages/tpccalib/PHTpcResiduals.h
offline/packages/tpccalib/TpcSpaceChargeReconstruction.cc
offline/packages/tpccalib/TpcSpaceChargeReconstruction.h

This PR updates the distortion correction code to use proper rphi and z errors for the clusters version 4, as provided by the ClusterErrorPara code from Christof
Also added some consts. 

More distortion fixes

---

calibrations/calorimeter/calo_tower_slope/configure.ac
calibrations/tpc/generator/configure.ac
offline/QA/modules/configure.ac
offline/database/cdbobjects/CDBTTree.cc
offline/database/cdbobjects/CDBTTree.h
offline/packages/KFParticle_sPHENIX/configure.ac
offline/packages/PHField/configure.ac
offline/packages/TrackerMillepedeAlignment/configure.ac
offline/packages/compressor/configure.ac
offline/packages/tpccalib/configure.ac
offline/packages/trackbase/configure.ac
offline/packages/trackreco/configure.ac
simulation/g4simulation/g4eval/configure.ac
simulation/g4simulation/g4tpc/PHG4TpcElectronDrift.cc

This PR adds some compiler flags to get this through clang 14. Testing if this is compatible with our current compilers

add warning suppression for build with clang 14

---

calibrations/calorimeter/calo_emc_pi0_tbt/CaloCalibEmc_Pi0.cc
calibrations/calorimeter/calo_emc_pi0_tbt/CaloCalibEmc_Pi0.h
calibrations/calorimeter/calo_emc_pi0_tbt/Makefile.am
calibrations/calorimeter/calo_emc_pi0_tbt/configure.ac
offline/packages/trackbase/configure.ac
simulation/g4simulation/g4detectors/configure.ac

This PR adds a few more warning suppressions for clang 14 so we can make a daily build with it, warnings need to be revisited individually in the future

suppress warnings from clang 14 until they will be fixed

---

offline/packages/trackbase/TrkrClusterHitAssocv3.cc

This PR simplifies TrkrClusterHitAssocv3::Reset by removing unnecessary code (following up on private discussion with Tony and others). It also fixes a gcc12 error message.

fix TrkrClusterHitAssocv3::Reset

---

offline/packages/trackreco/PHCASeeding.cc

Greatly improves CA seeding speed without any significant efficiency penalty. Also greatly improves the speed of PHSimpleKFProp due to the reduced seed population output from PHCASeeding. Should also fix an issue where no tracks were found at phi=0.

CA seeding speed upgrade

---

offline/packages/tpccalib/PHTpcResiduals.cc
offline/packages/tpccalib/PHTpcResiduals.h
offline/packages/tpccalib/TpcSpaceChargeReconstruction.cc
offline/packages/trackreco/PHGenFitTrkFitter.cc
offline/packages/trackreco/PHGenFitTrkFitter.h

This PR continues adapting the track-based distortion reconstruction code to the new cluster error parametrization. 
It also fixes a bug introduced in the previous pull request on this, resulting in using the incorrect cluster key for lookups. 

Adapt to new errors

---

simulation/g4simulation/g4tpc/TpcClusterBuilder.cc

The code spews hundreds of message with a problem, this PR just removes the printout - it does not fix the problem

remove printout from simulation/g4simulation/g4tpc/TpcClusterBuilder.cc

---

offline/packages/trackbase/TrkrClusterIterationMap.cc
offline/packages/trackbase/TrkrClusterIterationMap.h
offline/packages/trackbase/TrkrClusterIterationMapLinkDef.h
offline/packages/trackbase/TrkrClusterIterationMapv1.cc
offline/packages/trackbase/TrkrClusterIterationMapv1.h
offline/packages/trackbase/TrkrClusterIterationMapv1LinkDef.h
offline/packages/trackreco/Makefile.am
offline/packages/trackreco/PHActsTrkFitter.h
offline/packages/trackreco/TrackingIterationCounter.cc
offline/packages/trackreco/TrackingIterationCounter.h

This PR adds a simple module to fill the `TrkrClusterIterationMap` object and put it on the node tree. It also cleans up some things with the map object itself.  To be used for development of iterative track reconstruction.

Tracking Iteration

---

offline/QA/modules/QAG4SimulationTracking.cc

This adds a check for the TPC seed in the QA so that the QA modules can be run over any type of seeding configuration (e.g. silicon only, TPC only, or full SvtxSeeds).

Check TPC seed in QA

---

offline/database/pdbcal/pg/PgPostCalBank.h
offline/framework/frog/FROG.cc
offline/framework/phool/PHFlag.cc
offline/packages/CaloReco/CaloWaveformProcessing.cc
offline/packages/PHField/PHFieldUtility.cc
offline/packages/decayfinder/Makefile.am
offline/packages/trackreco/MakeActsGeometry.cc
offline/packages/trackreco/PHCASeeding.cc
offline/packages/trackreco/PHSimpleKFProp.cc
simulation/g4simulation/g4dst/Makefile.am
simulation/g4simulation/g4mvtx/PHG4MvtxSubsystem.cc

scan build with llvm 14 produced new warnings. This PR should take care of them. No change in results when running our standard macro

Scan build 14

---

offline/packages/TrackerMillepedeAlignment/HelicalFitter.cc
offline/packages/TrackerMillepedeAlignment/HelicalFitter.h

Updates HelicalFitter to allow matching of fitted tpc seeds to silicon clusters in low occupancy events, and then helical fitting of the full track. This module is probably not necessary, since the full track fitter now seems to be able to handle misaligned surfaces. It is a backup that could be used for pre-alignment in case of unforseen issues with the Acts fitting if there are severe misalignments.
[comment]: <> ( In case this is a draft PR, e.g. for running checks …

Updates to HelicalFitter 

---

offline/database/cdbobjects/CDBHistos.cc
offline/packages/trackreco/Makefile.am

This PR adds a dependency on libtrack_io to libtrack_reco, somehow our linker trick did not pick this up. I have seen more of these in the past - if somebody has time and the knowledge to crawl after this - that would be appreciated

Fix trackreco lib

---

simulation/g4simulation/g4epd/PHG4EPDDetector.cc
simulation/g4simulation/g4epd/PHG4EPDDetector.h
simulation/g4simulation/g4epd/PHG4EPDDisplayAction.cc
simulation/g4simulation/g4epd/PHG4EPDSteppingAction.cc
simulation/g4simulation/g4epd/PHG4EPDSubsystem.cc

The epd created two stepping actions resulting in a memory leak, removed the wrong one. minor mods by clang-tidy --fix

Fix epd memory leak

---

offline/packages/TrackerMillepedeAlignment/HelicalFitter.cc
offline/packages/TrackerMillepedeAlignment/HelicalFitter.h
offline/packages/TrackerMillepedeAlignment/MakeMilleFiles.cc
offline/packages/TrackerMillepedeAlignment/MakeMilleFiles.h

Adds the ability to fix layers or layer/parameter combinations to MakeMilleFiles and HelicalFitter.

Updates to add fixed layers and parameters

---

generators/flowAfterburner/main.cc
simulation/g4simulation/g4calo/HcalRawTowerBuilder.cc
simulation/g4simulation/g4ihcal/PHG4IHCalDetector.cc
simulation/g4simulation/g4ohcal/PHG4OHCalDetector.cc

This PR makes the phi angles between geometric and gdml based hcals consistent (geometric hcals are the reference)

Fix gdml hcal phi

---

offline/packages/trackbase/ActsSourceLink.h
offline/packages/trackbase/ActsTrackFittingAlgorithm.h
offline/packages/trackbase/Calibrator.h
offline/packages/trackbase/Makefile.am
offline/packages/trackbase/TrackFittingAlgorithmFunctionsGsf.cc
offline/packages/trackbase/TrackFittingAlgorithmFunctionsKalman.cc
offline/packages/trackbase/configure.ac
offline/packages/trackreco/PHActsGSF.cc
offline/packages/trackreco/PHActsGSF.h
offline/packages/trackreco/PHActsTrkFitter.cc
offline/packages/trackreco/PHActsTrkFitter.h

This PR refactors the Acts source link class into our `trackbase` package so that we can use it with other sPHENIX type objects, e.g. those defined in `TrkrDefs`.
It also fixes up the GSF to use this and a custom implemented GSF track fitter, analogously to the KalmanFitter.

Acts source link into trackbase

---

offline/database/cdbobjects/CDBHistos.cc
offline/database/cdbobjects/CDBHistos.h

I forgot to provide access to the restored histograms from the cdb

make histos accessible

---

offline/packages/CaloBase/TowerInfov1.cc
offline/packages/CaloBase/TowerInfov1.h
offline/packages/CaloReco/CaloTowerCalib.cc
offline/packages/CaloReco/CaloTowerCalib.h
offline/packages/CaloReco/Makefile.am

This code grab the ToweInfo node from the DST, and add calibrated TowerInfo to the node tree

Calorimeter Calibration

---

calibrations/calorimeter/calo_tower_slope/LiteCaloEval.cc
calibrations/calorimeter/calo_tower_slope/LiteCaloEval.h

expand functionality for tower slope
same macros as in macros area from last checkin - macros/calibrations/calo/*tower_slope/  may be some updates soon on that too

 update for inner hcal fitting, other small devs

---

offline/packages/KFParticle_sPHENIX/KFParticle_truthAndDetTools.cc

Fixed small naming issue with true track PV z output

---

offline/packages/TrackerMillepedeAlignment/MakeMilleFiles.h
offline/packages/trackbase/ActsGsfTrackFittingAlgorithm.h
offline/packages/trackbase/ActsSourceLink.h
offline/packages/trackbase/ActsTrackFittingAlgorithm.h
offline/packages/trackbase/TrackFittingAlgorithmFunctionsKalman.cc
offline/packages/trackbase_historic/ActsTransformations.cc
offline/packages/trackbase_historic/ActsTransformations.h
offline/packages/trackreco/ActsAlignmentStates.h
offline/packages/trackreco/MakeActsGeometry.cc
offline/packages/trackreco/MakeActsGeometry.h
offline/packages/trackreco/Makefile.am
offline/packages/trackreco/PHActsGSF.cc
offline/packages/trackreco/PHActsGSF.h
offline/packages/trackreco/PHActsTrackProjection.cc
offline/packages/trackreco/PHActsTrkFitter.cc
offline/packages/trackreco/PHActsTrkFitter.h

This PR cleans up a lot of the deprecated Acts code in the tracking packages. It minimizes the dependence on the `Examples` packages in Acts, which the main developers do not necessarily support and moves the functionality into our areas. There is still some `Examples` dependencies, and how we move these into `Acts/Core` longer term is being discussed with the development team.

Refactor: Acts cleanup

---

offline/packages/trackbase_historic/Makefile.am

I missed removing these unused Acts linked libraries from `trackbase_historic` - this PR fixes it.

fix: missed acts examples cleanup

---

offline/packages/TrackerMillepedeAlignment/HelicalFitter.h
offline/packages/TrackerMillepedeAlignment/MakeMilleFiles.h

Adds the correct cluster version setters to the alignment workflow.

fix: use correct cluster version

---

offline/packages/tpc/TpcClusterizer.cc
offline/packages/tpc/TpcClusterizer.h
simulation/g4simulation/g4detectors/PHG4TpcCylinderGeom.cc
simulation/g4simulation/g4detectors/PHG4TpcCylinderGeom.h

clusterizer speedup

---

simulation/g4simulation/g4tpc/PHG4TpcDigitizer.cc
simulation/g4simulation/g4tpc/PHG4TpcDigitizer.h

This PR adds noise to all TPC phi and time bins in PHG4TpcDigitizer before testing to see if the bin is above threshold. Previously, only phi bins that contained a g4 hit had noise added to their time bins.
The results are summarized in an addition to my talk at the last tracking meeting:
https://indico.bnl.gov/event/18112/ …

Tpc digitizer upgrade

---

simulation/g4simulation/g4epd/PHG4EPDDetector.cc

PR rotates epd sectors counter clockwise with sector 0 starting at phi=0

epd sector re-arrangement

---

simulation/g4simulation/g4mvtx/PHG4MvtxDetector.cc
simulation/g4simulation/g4mvtx/PHG4MvtxDetector.h
simulation/g4simulation/g4mvtx/PHG4MvtxSubsystem.cc
simulation/g4simulation/g4mvtx/PHG4MvtxSupport.cc
simulation/g4simulation/g4mvtx/PHG4MvtxSupport.h

This PR update the MVTX geometry, we replaced the ITS EW design to the real MVTX and position. In addition we include others support elements like Services Barrel Al flanges and CYSS Al Flanges

update MVTX geometry

---

simulation/g4simulation/g4decayer/EDecayType.hh
simulation/g4simulation/g4decayer/EvtGenExtDecayerPhysics.cc
simulation/g4simulation/g4decayer/EvtGenExtDecayerPhysics.hh
simulation/g4simulation/g4decayer/G4EvtGenDecayer.cc
simulation/g4simulation/g4decayer/G4EvtGenDecayer.hh
simulation/g4simulation/g4decayer/G4Pythia6Decayer.cc
simulation/g4simulation/g4decayer/G4Pythia6Decayer.hh
simulation/g4simulation/g4decayer/G4Pythia6DecayerMessenger.cc
simulation/g4simulation/g4decayer/G4Pythia6DecayerMessenger.hh
simulation/g4simulation/g4decayer/Makefile.am
simulation/g4simulation/g4decayer/P6DExtDecayerPhysics.cc
simulation/g4simulation/g4decayer/P6DExtDecayerPhysics.hh
simulation/g4simulation/g4decayer/PHEvtGenRandomEngine.cc
simulation/g4simulation/g4decayer/PHEvtGenRandomEngine.hh
simulation/g4simulation/g4decayer/Pythia6.cc
simulation/g4simulation/g4decayer/Pythia6.hh
simulation/g4simulation/g4decayer/configure.ac

Ran include what you use to reduce the number of includes to what is needed, clang-tidy auto fixes to apply some of our coding standards and clang-format to reformat the code according to our standards. Should not change the functionality

G4decayer cosmetics

---

calibrations/tpc/generator/ChargeMapReader.cc

The previous version erroneously assumed that input histograms would have no contents in under/overflow bins, causing erroneous charge elements on the edge bins after resampling.  This corrects that.
This fixes a bug which caused the spacecharge (and hence distortions) to be miscalculated.  Resampling effects introduce a few-percent error still, which will be addressed in a future pull request.

correction to spacecharge summing

---

offline/framework/frog/CreateFileList.pl

This PR adds datasets with single particles like upsilons or the embedded pi0's to CreateFileList.pl (type 14, needed command is printed out)
[skip-ci]

Createfilelist single

---

simulation/g4simulation/g4calo/RawTowerBuilder.cc

This PR removes the unconditional printout of the partial node tree which just confuses everybody
[skip-ci]

remove node tree printout

---

simulation/g4simulation/g4detectors/PHG4BbcDetector.cc
simulation/g4simulation/g4detectors/PHG4BbcDetector.h
simulation/g4simulation/g4detectors/PHG4BbcDisplayAction.cc

Added MBD/BBC Supports

---

simulation/g4simulation/g4micromegas/PHG4MicromegasDetector.cc

- adjusted TPOT radial position to better match surveyed positions
- next PR will be to implement actual rotation/translations to match survey data for all modules

tpot_geometry_2

---

offline/packages/CaloBase/TowerInfov1.h
offline/packages/jetbackground/CopyAndSubtractJets.cc
offline/packages/jetbackground/CopyAndSubtractJets.h
offline/packages/jetbackground/DetermineTowerBackground.cc
offline/packages/jetbackground/DetermineTowerBackground.h
offline/packages/jetbackground/RetowerCEMC.cc
offline/packages/jetbackground/RetowerCEMC.h
offline/packages/jetbackground/SubtractTowers.cc
offline/packages/jetbackground/SubtractTowers.h
simulation/g4simulation/g4calo/RawTowerDigitizer.cc
simulation/g4simulation/g4jets/Jet.h
simulation/g4simulation/g4jets/TowerJetInput.cc
simulation/g4simulation/g4jets/TowerJetInput.h

This is a PR to move the jet reconstruction from using rawtower objects to using towerinfo objects.
https://github.com/sPHENIX-Collaboration/macros/pull/588

updated the complete jet reconstruction to enable use of TowerInfo objects

---

offline/packages/trigger/CaloTriggerSim.cc
offline/packages/trigger/CaloTriggerSim.h

according to clang-tidy, vector indices are of type std::vector<type>::size_type which translates to long not int. Not critical, just to trigger jenkins

Fix trigger for loop type

---

offline/packages/CaloBase/Makefile.am
offline/packages/CaloBase/TowerInfoContainer.cc
offline/packages/CaloBase/TowerInfoContainer.h
offline/packages/CaloBase/TowerInfoContainerv1.cc
offline/packages/CaloBase/TowerInfoContainerv1.h
offline/packages/CaloReco/CaloTowerBuilder.cc
offline/packages/CaloReco/CaloTowerBuilder.h
offline/packages/CaloReco/CaloTowerCalib.cc
offline/packages/CaloReco/RawTowerCalibration.cc
offline/packages/NodeDump/DumpTowerInfoContainer.cc
offline/packages/jetbackground/CopyAndSubtractJets.cc
offline/packages/jetbackground/DetermineTowerBackground.cc
offline/packages/jetbackground/RetowerCEMC.cc
offline/packages/jetbackground/SubtractTowers.cc
simulation/g4simulation/g4calo/HcalRawTowerBuilder.cc
simulation/g4simulation/g4calo/RawTowerBuilder.cc
simulation/g4simulation/g4calo/RawTowerDigitizer.cc
simulation/g4simulation/g4epd/PHG4EPDModuleReco.cc
simulation/g4simulation/g4jets/TowerJetInput.cc

- [ x] Breaking change (fix or feature that would cause existing functionality to not work for users)
This PR modifies the way one interfaces with the towerinfocontainer object. If people's implementation use the previous interface it will break. 

updated the interface to towerinfocontainer to remove the use of maps

---

simulation/g4simulation/g4main/PHG4Reco.h

This PR makes EvtGen the default decayer again

make EvtGen default decayer

---

offline/framework/frog/CreateFileList.pl

We have a couple of new file types which need to be taken care of in the file selection sql string. This PR should fix the hijing and single particle with embedding selections
no need to run jenkins - this is not tested by it anyway
[skip-ci]

fix hijing selection (exclude single and special for type 4), fix single particle embedding selection

---

simulation/g4simulation/g4decayer/EvtGenExtDecayerPhysics.cc

allow for local decayer file override before consulting with the standard decayer file folder at https://github.com/sPHENIX-Collaboration/calibrations/tree/master/EvtGen 
https://github.com/sPHENIX-Collaboration/macros/pull/594 
https://github.com/sPHENIX-Collaboration/coresoftware/pull/1833

Allow for local decayer file override before consulting with the standard decayer file folder

---

simulation/g4simulation/g4epd/PHG4EPDModuleReco.cc

This PR fixes the update for the epd parameters with the macro settings

add forgotten update with macro

---

offline/database/dbtools/InsertCalib.cc
offline/database/dbtools/InsertCalib.h
offline/database/dbtools/ReadCalib.cc
offline/database/dbtools/ReadCalib.h
offline/database/pdbcal/base/PdbCalBank.cc
offline/database/pdbcal/base/PdbParameterMap.h

The return for the full file changed, giving a weird error
nlohmann::detail::type_error caught: [json.exception.type_error.305] cannot use operator[] with a numeric argument with string
which means it did not return an array of strings anymore

Fix dbtools

---

offline/packages/micromegas/Makefile.am
offline/packages/micromegas/MicromegasClusterizer.cc
offline/packages/micromegas/MicromegasClusterizer.h
offline/packages/micromegas/MicromegasRawDataDecoder.cc
offline/packages/micromegas/MicromegasRawDataDecoder.h
simulation/g4simulation/g4micromegas/PHG4MicromegasHitReco.cc
simulation/g4simulation/g4micromegas/PHG4MicromegasHitReco.h

This is a first shot at implementing a raw data decoder for TPOT, based on code from Martin (thanks !)
This was tested in fun4all, from raw data acquired last week at 1008.
Implements some temporary (and hard-coded) mapping from FEE ID ( = fiber ID in felix) and FEE index (0 to 7), and 
Fills some basic histograms:
- ADC distribution vs channel (0 to 8*256),
- pedestal vs channel (0 to 8*256)
- rms vs channel (0 to 8*256)
obtained distributions are identical to that obtained with ad-hoc  code at 1008, and shown e.g at https://indico.bnl.gov/event/18560/contributions/73830/attachments/46357/78416/talk.pdf (slide 10)
Also added some unrelated benign cleanup in other modules
[comment]: <> ( What types of changes does your code …

Micromegas raw data decoder

---

offline/framework/frog/CreateFileList.pl

This PR adds new types to CreateFiLeList.pl (D0 to pi-k)
no point running jenkins - it doesn't test this
[skip-ci]

Add type 17,18 for D0 to pi/k jets

---

offline/packages/micromegas/Makefile.am
offline/packages/micromegas/MicromegasCalibrationData.cc
offline/packages/micromegas/MicromegasCalibrationData.h
offline/packages/micromegas/MicromegasMapping.cc
offline/packages/micromegas/MicromegasMapping.h
offline/packages/micromegas/MicromegasRawDataCalibration.cc
offline/packages/micromegas/MicromegasRawDataCalibration.h
offline/packages/micromegas/MicromegasRawDataDecoder.cc
offline/packages/micromegas/MicromegasRawDataDecoder.h
simulation/g4simulation/g4micromegas/PHG4MicromegasHitReco.h

This PR implements a calibration module that gets RMS and pedestal out of Micromegas noise data
The rms and pedestals are stored into a dedicated MicromegasCalibrationData IO object, that is interface to the cddb using Chris' CDDBTTree object. 
The MicromegasRawDataDecoder can read the calibration data, apply the zero suppression to the data, map FEE and channel id into physical strips and store Hits into TrkrHitsSets when signal above threshold is found.
[comment]: <> ( In case this is a draft PR, e.g. for running checks using …

Micromegas raw

---

offline/QA/modules/QAG4SimulationIntt.cc
offline/QA/modules/QAG4SimulationMicromegas.cc
offline/QA/modules/QAG4SimulationMvtx.cc
offline/QA/modules/QAG4SimulationTpc.cc
offline/packages/intt/InttClusterizer.cc
offline/packages/micromegas/MicromegasClusterizer.cc
offline/packages/mvtx/MvtxClusterizer.cc
offline/packages/tpc/TpcClusterizer.cc
offline/packages/trackbase/ClusterErrorPara.cc
offline/packages/trackbase/ClusterErrorPara.h
offline/packages/trackbase/Makefile.am
offline/packages/trackbase/TrkrClusterContainerv5.cc
offline/packages/trackbase/TrkrClusterContainerv5.h
offline/packages/trackbase/TrkrClusterContainerv5LinkDef.h
offline/packages/trackbase/TrkrClusterv4.h
offline/packages/trackbase/TrkrClusterv5.cc
offline/packages/trackbase/TrkrClusterv5.h
offline/packages/trackbase/TrkrClusterv5LinkDef.h
offline/packages/trackreco/ALICEKF.cc
offline/packages/trackreco/PHActsGSF.cc
offline/packages/trackreco/PHActsSiliconSeeding.cc
offline/packages/trackreco/PHActsTrkFitter.cc
offline/packages/trackreco/PHCASeeding.cc
offline/packages/trackreco/PHGenFitTrkFitter.cc
offline/packages/trackreco/PHSimpleKFProp.cc
simulation/g4simulation/g4eval/SvtxEvaluator.cc
simulation/g4simulation/g4eval/TrackEvaluation.cc
simulation/g4simulation/g4eval/TrackEvaluationContainerv1.h

cluster error parametrization update

---

offline/packages/tpc/TpcClusterizer.cc

fixed printout

---

offline/packages/TrackingDiagnostics/KshortReconstruction.cc
offline/packages/TrackingDiagnostics/KshortReconstruction.h
offline/packages/TrackingDiagnostics/Makefile.am
offline/packages/TrackingDiagnostics/autogen.sh
offline/packages/TrackingDiagnostics/configure.ac
offline/packages/TrackingDiagnostics/helixResiduals.cc
offline/packages/TrackingDiagnostics/helixResiduals.h

Reopening pull request after git malfunction 

Move mass reco

---

simulation/g4simulation/g4eval/TruthRecoTrackMatching.cc
simulation/g4simulation/g4eval/TruthRecoTrackMatching.h
simulation/g4simulation/g4intt/Makefile.am
simulation/g4simulation/g4intt/PHG4InttHitReco.cc
simulation/g4simulation/g4intt/PHG4InttHitReco.h
simulation/g4simulation/g4intt/TruthInttClusterBuilder.cc
simulation/g4simulation/g4intt/TruthInttClusterBuilder.h
simulation/g4simulation/g4mvtx/Makefile.am
simulation/g4simulation/g4mvtx/PHG4MvtxHitReco.cc
simulation/g4simulation/g4mvtx/PHG4MvtxHitReco.h
simulation/g4simulation/g4mvtx/TruthMvtxClusterBuilder.cc
simulation/g4simulation/g4mvtx/TruthMvtxClusterBuilder.h

Fills TrkrClusterv4 into TrkrClusterContainer for the truth tracks
There are no known errors, but I am pushing as a draft now to start working through anything that comes up from Jenkins while I also look at plots of the output before changing to a full pull request

Generate Truth Clusters from Intt + Mvtx 

---

offline/packages/trackreco/MakeActsGeometry.cc
offline/packages/trackreco/MakeActsGeometry.h

The TPOT is installed, which I'm pretty sure means there is no way we are running without it :D
This PR builds the TPOT in Acts by default and if it isn't there then throw an error.

Build tpot by default

---

generators/FermiMotionAfterburner/FermiMotion.cc
generators/FermiMotionAfterburner/FermiMotion.h
generators/FermiMotionAfterburner/FermimotionAfterburner.cc
generators/FermiMotionAfterburner/FermimotionAfterburner.h

Added pTspec(default 50MeV) to spectators along the event plane angle for testing v1 reconstruction ability.

add pTspec

---

offline/packages/TrackingDiagnostics/Makefile.am
offline/packages/TrackingDiagnostics/TrkrNtuplizer.cc
offline/packages/TrackingDiagnostics/TrkrNtuplizer.h
offline/packages/trackbase/ClusterErrorPara.cc

add trkrntuplizer

---

offline/packages/TrackingDiagnostics/KshortReconstruction.cc
offline/packages/TrackingDiagnostics/KshortReconstruction.h
offline/packages/TrackingDiagnostics/helixResiduals.cc
offline/packages/TrackingDiagnostics/helixResiduals.h

Modifications to user interaction with output files 

Modifications for processing output files

---

simulation/g4simulation/g4histos/G4RawTowerTTree.cc
simulation/g4simulation/g4histos/G4RawTowerTTree.h
simulation/g4simulation/g4histos/G4RootScintillatorTower.cc
simulation/g4simulation/g4histos/G4RootScintillatorTower.h
simulation/g4simulation/g4histos/G4RootScintillatorTowerContainer.cc
simulation/g4simulation/g4histos/G4RootScintillatorTowerContainer.h
simulation/g4simulation/g4histos/G4ScintillatorTowerTTree.cc
simulation/g4simulation/g4histos/G4TowerNtuple.cc

Went through and modified all of the G4Histos area to remove any and all implementations of the RawTower and RawTowercontainer. 

updated g4histos area to remove RawTowerContainers

---

offline/packages/trackreco/PHActsSiliconSeeding.h

Restores Acts seeding performance for new cluster version

Tune seeder for clusterv5

---

offline/packages/CaloReco/CaloTowerBuilder.cc
offline/packages/CaloReco/CaloTowerBuilder.h
offline/packages/TrackingDiagnostics/KshortReconstruction.cc
offline/packages/TrackingDiagnostics/KshortReconstruction.h
offline/packages/TrackingDiagnostics/Makefile.am
offline/packages/TrackingDiagnostics/TrkrNtuplizer.cc
offline/packages/TrackingDiagnostics/TrkrNtuplizer.h
offline/packages/TrackingDiagnostics/configure.ac
offline/packages/TrackingDiagnostics/helixResiduals.cc
offline/packages/TrackingDiagnostics/helixResiduals.h
simulation/g4simulation/g4bbc/BbcSimReco.cc
simulation/g4simulation/g4bbc/BbcSimReco.h
simulation/g4simulation/g4bbc/BbcSimRecoLinkDef.h
simulation/g4simulation/g4bbc/BbcVertex.h
simulation/g4simulation/g4bbc/BbcVertexFastSimReco.cc
simulation/g4simulation/g4bbc/BbcVertexFastSimReco.h
simulation/g4simulation/g4bbc/BbcVertexMapv1.cc
simulation/g4simulation/g4bbc/BbcVertexMapv1.h
simulation/g4simulation/g4bbc/BbcVertexv1.cc
simulation/g4simulation/g4bbc/Makefile.am
simulation/g4simulation/g4bbc/configure.ac

This PR removes the double "newing" of the waveform fitting in the calo tower builder. It's tested that this doesn't change the results. In the meanitme a bunch of errors have crept into our code base which make jenkins fails. This PR should contain the fixes for those

Fix calotowerbuilder

---

offline/packages/CaloReco/RawTowerDeadTowerInterp.cc
offline/packages/CaloReco/RawTowerDeadTowerInterp.h
offline/packages/ClusterIso/ClusterIso.cc
offline/packages/trackreco/PHActsTrackProjection.cc
offline/packages/trackreco/PHActsTrackProjection.h
offline/packages/trackreco/PHGenFitTrackProjection.cc
offline/packages/trackreco/PHTrackClusterAssociator.cc
offline/packages/trackreco/PHTrackClusterAssociator.h
offline/packages/trigger/CaloTriggerSim.cc

This PR goes through largely tracking and some Calo/Cluster code to remove references to the RawTowerContainer and replace it with TowerInfoContainer objects.

Updating of reconstruction code to use TowerInfo objects rather than RawTower objects

---

offline/packages/CaloBase/Makefile.am
offline/packages/CaloBase/TowerInfoDefs.h
offline/packages/CaloBase/TowerInfoDefsLinkDef.h

This PR introduces a new class to the CaloBase that contains the useful commands to go from channel number to a variety of other useful parameters (such as etabin, phibin, geometry key).

created a towerinfodefs class

---

offline/packages/CaloBase/TowerInfoDefs.h

This PR simply adds new calls to the towerinfodefs code. Software was developed by the zdc-smd development team (Blair Seidlitz) and implemented into the existing structure.

updated towerinfodefs to include information for the zdc and smd

---

offline/packages/trackreco/ActsPropagator.cc
offline/packages/trackreco/ActsPropagator.h
offline/packages/trackreco/PHActsTrackProjection.cc
offline/packages/trackreco/PHActsTrackProjection.h
offline/packages/trackreco/PHActsTrackPropagator.cc
offline/packages/trackreco/PHActsTrackPropagator.h

Acts track parameters
This consolidates code into one function that Acts tools can call to make the Acts EDM track parameter object.

Consolidate Acts track param code

---

offline/packages/bbc/BbcOut.cc
offline/packages/bbc/BbcPmtContainer.cc
offline/packages/bbc/BbcPmtContainerV1.cc
simulation/g4simulation/g4bbc/BbcSimReco.cc

fixed issue with writing bbcpmtcontainer to DST

---

offline/packages/micromegas/MicromegasMapping.cc
offline/packages/micromegas/MicromegasMapping.h

updated Micromegas fiber mapping to final configuration

---

offline/packages/trackbase/TrackFitUtils.cc
offline/packages/trackreco/PHSiliconHelicalPropagator.cc
offline/packages/trackreco/PHSiliconHelicalPropagator.h

PHSiliconHelicalPropagator previously used HelicalFitter internally; now it uses TrackFitUtils instead.

Switched over PHSiliconHelicalPropagator to TrackFitUtils

---

offline/packages/trackbase/TrkrCluster.h
offline/packages/trackbase/TrkrClusterv4.cc
offline/packages/trackbase/TrkrClusterv4.h
offline/packages/trackbase/TrkrClusterv5.cc
offline/packages/trackbase/TrkrClusterv5.h
simulation/g4simulation/g4tpc/PHG4TpcElectronDrift.cc

This PR adds some functions to the TrkrCluster base class which are in v5 but not in the base class currently. Having this will prevent any casting gymnastics to occur

add base class functions

---

offline/packages/CaloBase/TowerInfoDefs.h

The compilation crashes with a signed/unsigned int comparison. Just use all unsigned ints here

fix signed/unsigned comparison

---

offline/packages/KFParticle_sPHENIX/KFParticle_Tools.cc
offline/packages/KFParticle_sPHENIX/KFParticle_Tools.h
offline/packages/KFParticle_sPHENIX/KFParticle_nTuple.cc
offline/packages/KFParticle_sPHENIX/KFParticle_nTuple.h
offline/packages/KFParticle_sPHENIX/KFParticle_sPHENIX.cc
offline/packages/KFParticle_sPHENIX/KFParticle_sPHENIX.h

Changes some cpp check recommendations of pasing by reference
Previous update introduced a flag to propogate track parameters to the SV during the reco stage, this wasn't added to the nTuple stage so there was a difference in values in the reco and output files

KFP: Cleaning and bug fix

---

offline/packages/CaloBase/Makefile.am
offline/packages/CaloBase/TowerInfoDefs.cc
offline/packages/CaloBase/TowerInfoDefs.h

Updated the TowerInfoDefs to include the EPD information as well as clean up wasteful memory and processing cycles

updated the tower info defs class to include EPD

---

offline/packages/CaloReco/RawClusterBuilderTopo.cc

Topo-clusters code is being updated to use TowerInfo objects.

Update for TowerInfo objects

---

offline/packages/particleflow/ParticleFlowReco.cc

Removing rawtower objects in order to make it compatible to towerinfo objects.

making it compatible to towerinfo

---

offline/QA/modules/Makefile.am
offline/QA/modules/QAG4SimulationDistortions.cc
offline/QA/modules/QAG4SimulationDistortions.h
offline/packages/tpccalib/PHTpcResiduals.cc
offline/packages/tpccalib/PHTpcResiduals.h

This PR adds a module to the QA repo that performs some basic QA on the track based residuals. To be integrated with a macros branch and new jupyter notebook.

Track based distortions QA

---

offline/packages/TrackerMillepedeAlignment/HelicalFitter.cc
offline/packages/TrackerMillepedeAlignment/MakeMilleFiles.cc
offline/packages/TrackingDiagnostics/TrkrNtuplizer.cc
offline/packages/trackbase/ClusterErrorPara.cc
offline/packages/trackbase/ClusterErrorPara.h
offline/packages/trackreco/ALICEKF.cc
offline/packages/trackreco/PHActsGSF.cc
offline/packages/trackreco/PHActsTrkFitter.cc
simulation/g4simulation/g4eval/SvtxEvaluator.cc
simulation/g4simulation/g4eval/TrackEvaluation.cc

 sector edge error modification for cluster v5

---

offline/framework/frog/CreateFileList.pl

This PR adds the Jet40 files to CreateFileList.pl as type 19. No need to run jenkins which does not test this anyway
[skip-ci]

add type 19 for JS Jet 40GeV, remove test files from printout

---

offline/QA/modules/QAG4SimulationDistortions.cc
offline/QA/modules/QAG4SimulationDistortions.h

Adds the tree of residual information to the distortion QA module

Add QA tree

---

offline/database/sphenixnpc/sphenixnpc.cc
offline/database/sphenixnpc/sphenixnpc.h

This PR triggers a jenkins run of the sphenixnpc package which is now part of our build

clang-tidy, clang-format to trigger jenkins

---

offline/packages/CaloBase/TowerInfoDefs.cc

changes the values of the hcal phibin offset array to the correct values. 

fixed an error in the HCAL phibinoffset values

---

offline/packages/CaloReco/CaloTowerCalib.cc
offline/packages/CaloReco/Makefile.am

This PR puts the CalibTowerCalib class back, using the new sphenixnpc client

new cdb client interface (still rough)

---

simulation/g4simulation/g4epd/PHG4EPDModuleReco.cc

Minor change- Clean up: remove duplicate <calobase/TowerInfoDefs.h>

remove duplicate include file in epd reco

---

offline/packages/micromegas/MicromegasDefs.h
offline/packages/micromegas/MicromegasMapping.cc
offline/packages/micromegas/MicromegasMapping.h
offline/packages/micromegas/MicromegasRawDataCalibration.cc
offline/packages/micromegas/MicromegasRawDataCalibration.h

This pull request implements the mapping from FEE channel ID to physical strip ID for TPOT
how the mapping is constructed from FEE channel mapping, transition cable and detector strip to channel is documented in the code. 

Tpot mapping

---

calibrations/calorimeter/calo_emc_pi0_tbt/CaloCalibEmc_Pi0.cc
generators/FermiMotionAfterburner/Makefile.am
offline/database/sphenixnpc/sphenixnpc.cc
offline/framework/ffamodules/CDBInterface.cc
offline/framework/ffamodules/CDBInterface.h
offline/framework/ffamodules/Makefile.am
offline/framework/ffaobjects/Makefile.am
offline/packages/tpc/Makefile.am

This PR adds the first test version for the new cdb interface as pop in replacement for xpload

Cdbinterface

---

offline/packages/trackreco/PHActsSiliconSeeding.cc
offline/packages/trackreco/PHActsSiliconSeeding.h

This PR adds some more parameters to our Acts::seeding implementation that gives us more knobs to turn with misaligned surfaces. Should not affect the default behavior at all since the default values are set to those that are currently implicitly used by Acts.

Add misalignment parameters

---

offline/packages/trackreco/PHActsSiliconSeeding.cc

Somehow cleanup from the last PR caused this line to disappear which needs to be done to set an additional seeding parameter

Set new param

---

offline/packages/trackbase/ClusterErrorPara.cc

Title says it all.
@pinkenburg I know you don't like asserts, but
- this is a corner case that really should not happen
- this is better than no message at all
- if you insist I can switch to a proper std::cout and exit() call. 
Hugo

prevent silent crash

---

offline/packages/trackbase_historic/TrackSeed_v1.cc
offline/packages/trackreco/PHSiliconTpcTrackMatching.cc

A bug was introduced in the matching code which slows it down substantially. This fixes that bug while maintaining the functionality

Speed up matching

---

offline/packages/CaloBase/Makefile.am
offline/packages/CaloBase/configure.ac

This PR adds --enable-online to the configure of the CaloBase package so the online part can be build 

add --enable-online to build online version

---

offline/packages/trackbase_historic/Makefile.am
offline/packages/trackbase_historic/TrackAnalysisUtils.cc
offline/packages/trackbase_historic/TrackAnalysisUtils.h

This adds a helper class where track analysis utilities can be added such that we have a centralized location in our build for general track analysis tools. For now all that is added is a function that calculates the DCA, but there will surely be more to come.

Track Analysis Utils

---

offline/packages/ResonanceJetTagging/ResonanceJetTagging.cc

Removing double D0 from MC jets

---

offline/database/sphenixnpc/sphenixnpc.cc
offline/database/sphenixnpc/sphenixnpc.h

This PR makes sphenixnpc compatible with the nopayload update

compatible with nopayload update

---

offline/database/sphenixnpc/sphenixnpc.cc
offline/database/sphenixnpc/sphenixnpc.h
offline/framework/ffaobjects/CdbUrlSavev1.h
offline/framework/fun4all/Fun4AllBase.cc

This PR triggers jenkins with the sphenixnpc adjustments for the nopayload update

cosmetic changes to trigger jenkins

---

offline/packages/CaloBase/Makefile.am
offline/packages/CaloBase/TowerInfoDefs.cc

This makes the towerinfodefs available online

install TowerInfoDefs online

---

simulation/g4simulation/g4vertex/Makefile.am

This fixes autoconf warnings which make jenkins fail compilation test [skip-ci]

remove libg4vertex_io remnants

---

offline/packages/trackreco/MakeActsGeometry.cc

Read the fieldmap from the CDB if it is available, per Chris' suggestion.

read from cdb if file is available

---

offline/packages/TrackingDiagnostics/Makefile.am
offline/packages/TrackingDiagnostics/TrackResiduals.cc
offline/packages/TrackingDiagnostics/TrackResiduals.h

This PR adds a module that dumps reconstructed track, cluster, and state information into a nearly flat tuple with the track info + std:vectors of the cluster and state information associated to it, in both local and global coordinates. Useful for alignment testing and debugging.

Track Residual Module

---

offline/packages/CaloReco/CaloWaveformFitting.cc

This change adds the pedestal subtraction to the software zero suppression so that it returns values consistent with the nominal data.

Add pedestal subtraction to the software zero suppression

---

offline/packages/intt/InttDeadMapHelper.cc
offline/packages/intt/InttDeadMapHelper.h

Added helper class for dead channel analysis

---

offline/framework/frog/CreateFileList.pl

This PR adds type 20 = pAu to CreateFileList.pl. It's not tested by jenkins so lets skip the ci [skip-ci]

Add p au createfilelist

---

simulation/g4simulation/g4detectors/Makefile.am
simulation/g4simulation/g4detectors/PHG4InnerHcalDetector.cc
simulation/g4simulation/g4detectors/PHG4InnerHcalDetector.h
simulation/g4simulation/g4detectors/PHG4InnerHcalSteppingAction.cc
simulation/g4simulation/g4detectors/PHG4InnerHcalSteppingAction.h
simulation/g4simulation/g4detectors/PHG4InnerHcalSubsystem.cc
simulation/g4simulation/g4detectors/PHG4OuterHcalDetector.cc
simulation/g4simulation/g4detectors/PHG4OuterHcalDetector.h
simulation/g4simulation/g4detectors/PHG4OuterHcalSteppingAction.cc
simulation/g4simulation/g4detectors/PHG4OuterHcalSteppingAction.h
simulation/g4simulation/g4detectors/PHG4OuterHcalSubsystem.cc
simulation/g4simulation/g4ihcal/Makefile.am
simulation/g4simulation/g4ihcal/PHG4IHCalDetector.cc
simulation/g4simulation/g4ihcal/PHG4IHCalDetector.h
simulation/g4simulation/g4ihcal/PHG4IHCalSteppingAction.cc
simulation/g4simulation/g4ihcal/PHG4IHCalSteppingAction.h
simulation/g4simulation/g4ihcal/PHG4IHCalSubsystem.cc
simulation/g4simulation/g4main/PHG4SteppingAction.h
simulation/g4simulation/g4ohcal/Makefile.am
simulation/g4simulation/g4ohcal/PHG4OHCalDetector.cc
simulation/g4simulation/g4ohcal/PHG4OHCalDetector.h
simulation/g4simulation/g4ohcal/PHG4OHCalSteppingAction.cc
simulation/g4simulation/g4ohcal/PHG4OHCalSteppingAction.h
simulation/g4simulation/g4ohcal/PHG4OHCalSubsystem.cc

This PR add a new stepping action that add light yield with certain time window to the towerinfo object in order to reduce the memory cost coming from creating G4Hits.
one to one tower energy comparison by fixing the seed for 10 HIJING events
Two stepping actions results are almost consistent with each other. Outliers are possible coming from applying the timing cut on G4Step vs. G4Hit level.
Need to modify the corresponding macros. Need to modify the eval code to have the option of only using towerinfo.
[comment]: <> ( In case this is …

a new alternative stepping action that directly add light yield to the towerinfo object

---

offline/packages/trackbase/Makefile.am
offline/packages/trackbase/TrkrDefs.h
offline/packages/trackbase/configure.ac

This PR adds --enable-online to the configure so it installs only the needed header file for online use, fixed up the Makefile.am, so lets run jenkins

enable online build (just install TrkrDefs.h), clean up Makefile.am

---

offline/packages/trackbase/Makefile.am

This PR adds TrkrDefs.cc to the online trackbase lib

compile TrkrDefs.cc into shared libs for online

---

offline/packages/micromegas/MicromegasRawDataCalibration.cc
offline/packages/micromegas/MicromegasRawDataDecoder.cc

Thanks @blackcathj  for finding this out !

fixed memory leak

---

offline/packages/KFParticle_sPHENIX/KFParticle_eventReconstruction.cc
offline/packages/KFParticle_sPHENIX/KFParticle_eventReconstruction.h
offline/packages/KFParticle_sPHENIX/KFParticle_sPHENIX.cc
offline/packages/KFParticle_sPHENIX/KFParticle_sPHENIX.h

This is yet another fresh pull request to fix the KFParticle magnetic field. Again, we messed up with git rebase and included unnecessary files in the previous 2 pull request attemps #1987 and #1999. Here is the final fix for the KFParticle magnetic field by properly loading the magnetic field from the file name in CDB and get the proper unit in kG. 

Fix KFParticle Magnetic Field by Loading the Field Map Properly from CDB

---

offline/packages/TrackerMillepedeAlignment/MakeMilleFiles.cc

The v5 cluster never got the proper units converted in MakeMilleFiles, this fixes that.

Fix cluster uncertainty unit

---

offline/packages/tpccalib/PHTpcCentralMembraneClusterizer.cc
offline/packages/tpccalib/PHTpcCentralMembraneMatcher.cc
offline/packages/tpccalib/PHTpcCentralMembraneMatcher.h

Updated code to identify diffuse laser flash to be more robust in high occupancy events. Same update is used to improve performance of meta-clustering in high occupancy events.
Updated debugging ntuple for CM Flash reco to include more information.
Separated application of distortion corrections in CM Flash matching into static and average.

Diffuse Laser Flash High Occupancy Improvements

---

simulation/g4simulation/g4main/Makefile.am
simulation/g4simulation/g4main/PHG4Reco.cc
simulation/g4simulation/g4main/PHG4Reco.h

The EAST physics list was cobbled together from the east project. We don't use it, it was never verified by us and it is likely outdated by now. Leaving this as an option will just cause problems. If there is interest (accompanied by manpower implementing and verifying it) it can be put in at any time. Once this PR is through the east physics list itself will be removed from our repo …

Remove EAST physics list

---

offline/packages/TrackingDiagnostics/TrkrNtuplizer.cc
offline/packages/tpccalib/PHTpcResiduals.cc
offline/packages/tpccalib/TpcSpaceChargeReconstruction.cc
offline/packages/trackbase/ClusterErrorPara.cc
offline/packages/trackbase/ClusterErrorPara.h
offline/packages/trackbase/TrackFitUtils.cc
offline/packages/trackreco/PHActsGSF.cc
offline/packages/trackreco/PHActsKDTreeSeeding.h
offline/packages/trackreco/PHActsTrkFitter.cc
offline/packages/trackreco/PHGenFitTrkFitter.cc
simulation/g4simulation/g4eval/SvtxEvaluator.cc
simulation/g4simulation/g4eval/TrackEvaluation.cc

This PR removes the circular dependency in trackbase -> trackbase_historic

fix: circular dependency in trackbase

---

offline/packages/tpc/Makefile.am
offline/packages/tpc/TpcRawDataTree.cc
offline/packages/tpc/TpcRawDataTree.h

Simple `ddump` translation to `TTree`, which is used for quick online debugging purposes, and for seeding formal reconstruction and calibration modules. 
Example use: https://indico.bnl.gov/event/19236/#1-tpc-pedestal-calibration-too 

TPC online debug tree

---

offline/framework/fun4all/Fun4AllDstOutputManager.cc
offline/framework/fun4all/Fun4AllDstOutputManager.h
offline/framework/fun4all/Fun4AllOutputManager.h
offline/framework/fun4all/Fun4AllRunNodeInputManager.cc
offline/framework/fun4all/Fun4AllRunNodeInputManager.h
offline/framework/fun4all/Fun4AllSyncManager.cc
offline/packages/NodeDump/DumpPHG4CylinderGeomContainer.cc

This PR fixes the crash in the run node dst input manager, it now runs over more than just one event

Fix runnode reader

---

offline/packages/micromegas/MicromegasDefs.h
offline/packages/micromegas/MicromegasMapping.cc
offline/packages/micromegas/MicromegasRawDataCalibration.cc
offline/packages/micromegas/MicromegasRawDataDecoder.cc
offline/packages/micromegas/MicromegasRawDataEvaluation.cc
offline/packages/micromegas/MicromegasRawDataEvaluation.h

Fixes PRDF decoding to adapt to two endpoints on felix boards. TPOT now has 2 packet numbers, one per end point
Also update Detector to FEE mapping, following swapping fiber connections in the IR. on May 23

Micromegas mapping update

---

offline/packages/intt/InttRawDataDecoder.cc
offline/packages/intt/InttRawDataDecoder.h
offline/packages/intt/Makefile.am

Added draft of RawData -> DST for the INTT (following the micromegas code)

Added draft of raw data to dst for intt (still need to implement some things)

---

offline/packages/trackreco/MakeActsGeometry.cc

Suppresses some inadvertently added alignment verbosity.

Suppress alignment verbosity

---

offline/database/sphenixnpc/SphenixClient.h
offline/database/sphenixnpc/configure.ac

This PR gets the cdb code through clang 

use pragma to suppress warning coming from nopayloadclient

---

offline/database/sphenixnpc/SphenixClient.cc
offline/packages/CaloReco/CaloWaveformProcessing.cc
offline/packages/CaloReco/CaloWaveformProcessing.h

The client changed its behavior if a calibration isn't found. Instead of returning an empty string it returned an error message which was then interpreted as a filename. This PR restores the old behavior - the client returns an empty string if no calibration can be found 

Fix cdb calo

---

offline/framework/frog/CreateFileList.pl

This PR adds type 21 for JS Jet >= 20GeV, 
added possible options to -embed
pau --> embedded into pAu hijing
none or auau --> embedded into AuAu hijing
[skip-ci]

add type 21, Jet >= 20GeV, add embed in pAu

---

offline/packages/micromegas/MicromegasRawDataCalibration.cc
offline/packages/micromegas/MicromegasRawDataDecoder.cc
offline/packages/micromegas/MicromegasRawDataEvaluation.cc

do not exit if packet is not found, now that we have several

---

offline/database/sphenixnpc/CDBUtils.cc
offline/database/sphenixnpc/CDBUtils.h

This PR adds the cloning of global tags to our CDBUtils. It does a deep copy (somewhat expensive operation - do not abuse)

add global tag cloning

---

offline/database/sphenixnpc/CDBUtils.cc
offline/database/sphenixnpc/CDBUtils.h
offline/database/sphenixnpc/SphenixClient.cc
offline/database/sphenixnpc/SphenixClient.h

unlocking/locking a non existing global tag resulted in an unintelligible error message, this PR fixes this. Adds a bool existGlobalTag(gt_name) method which can be used to check for a gt where needed

print error if non existing gt is locked/unlocked

---

offline/packages/intt/InttFelixMap.cc
offline/packages/intt/InttFelixMap.h
offline/packages/intt/InttFelixMapObsolete.cc
offline/packages/intt/InttFelixMapObsolete.h
offline/packages/intt/InttMapping.cc
offline/packages/intt/InttMapping.h
offline/packages/intt/InttRawDataDecoder.cc
offline/packages/intt/Makefile.am

Added multiple structs for physical mapping conventions and defined conversions between them, fixed memory leak in RawDataDecoder

---

offline/packages/TrackingDiagnostics/TrkrNtuplizer.cc
offline/packages/TrackingDiagnostics/TrkrNtuplizer.h
offline/packages/tpc/TpcClusterizer.h

Added setter for clusterizer pedestal value. 
Removed hidden g4truth dependence in TrkrNtuplizer

prep for rawdata

---

offline/packages/TrackerMillepedeAlignment/HelicalFitter.h

Expands HF matching window to accommodate O(mm) TPC misalignments

Expand HF matching window

---

offline/packages/micromegas/MicromegasClusterizer.cc

Title says it all.
This is harmless but improves code clarity

fix stripcount in micromegas clustering

---

offline/packages/tpc/TpcRawDataDecoder.cc

Fixed a bug with 0 layer in the TPC.

Fixed a bug with 0 layer

---

simulation/g4simulation/g4eval/CaloEvaluator.cc
simulation/g4simulation/g4eval/CaloEvaluator.h
simulation/g4simulation/g4eval/TruthRecoTrackMatching.cc
simulation/g4simulation/g4eval/g4evaltools.cc
simulation/g4simulation/g4eval/g4evaltools.h

This PR fixes the calo evaluator. Starting event number can be now set from the outside. Some shadowed variables and using the std version of math functions

Fix g4eval

---

offline/packages/CaloReco/CaloTowerCalib.cc
offline/packages/CaloReco/CaloTowerCalib.h

removed global tag setting

---

offline/packages/jetbase/Makefile.am
offline/packages/jetbase/configure.ac

The PR adds the forgotten include install which kills our current macros, merging this before jenkins finishes to create a working build

Fix jetbase

---

offline/framework/frog/CreateFileList.pl

This PR fixes running over datasets with > 100k segments. [skip-ci]

fix for > 100k segments

---

offline/packages/micromegas/MicromegasRawDataDecoder.cc
offline/packages/micromegas/MicromegasRawDataEvaluation.cc
offline/packages/micromegas/MicromegasRawDataEvaluation.h

Cummulative update for Micromegas raw data decoding and evaluation

Micromegas raw data evaluation

---

offline/packages/CaloReco/CaloTowerBuilder.cc

Updated the code so that it puts the emcal information in the CEMC, HCALIN, HCALOUT,... in the correct composite nodes

updated node creation to use established detector composite node structure

---

offline/packages/tpc/TpcRawDataDecoder.cc

Fixed a bug in TPC raw data decoder, which was using the wrong sector numbering 

Padplane readout phi

---

offline/packages/trackbase_historic/TrackSeed_v1.cc

This change avoids a rare segfault that Chris came upon.

Avoid rare segfault

---

offline/packages/tpc/Makefile.am
offline/packages/tpc/TpcLoadDistortionCorrection.cc
offline/packages/tpc/TpcMap.cc
offline/packages/tpc/configure.ac

This PR makes the TpcMap available online via conditional compilation. Add -Wshadow to the compilation flags and fixed shadowed variable

make TpcMap usable for online

---

offline/packages/tpc/TpcMap.cc
offline/packages/tpc/TpcRawDataDecoder.cc
offline/packages/tpc/TpcRawDataDecoder.h

bugfixes to the tpc raw data decoder

bugfixes to the tpc raw data decoder

---

offline/packages/CaloReco/RawClusterBuilderTemplate.h

added only a set method for using no zvtx flag: also set default to use no zvtx.
If you Chris prefer to not have that as the default just change the = 2 back to =0 in the header file change...

added set method for using no zvtx flag

---

offline/packages/CaloReco/Makefile.am
offline/packages/CaloReco/RawTowerDeadMapLoader.cc
offline/packages/CaloReco/RawTowerDeadMapLoader.h

DeadMap loader will read the CDB instead of .xml file
DeadMap url on CDB is "detector" + "DEADMAP". Ex. for EMCAL the url is "CEMCDEADMAP".

Changing DeadMap loader to read CDB

---

offline/packages/CaloReco/Makefile.am
offline/packages/CaloReco/RawClusterDeadAreaMask.cc
offline/packages/CaloReco/RawClusterDeadAreaMask.h

Updating RawClusterDeadArea to use towerinfo objects.

Updating cluster dead area to towerinfo

---

offline/packages/TrackerMillepedeAlignment/AlignmentDefs.cc
offline/packages/TrackerMillepedeAlignment/AlignmentDefs.h
offline/packages/TrackerMillepedeAlignment/HelicalFitter.cc

Add methods to return a list of all global alignment parameters for a subsystem, given the surface grouping level.

Add methods to return all global alignment parameters for a grouped subsystem

---

offline/framework/fun4all/InputFileHandler.cc
offline/framework/fun4all/InputFileHandler.h
offline/framework/fun4all/Makefile.am
offline/framework/fun4allraw/Fun4AllPrdfInputPoolManager.cc
offline/framework/fun4allraw/Fun4AllPrdfInputPoolManager.h
offline/framework/fun4allraw/SinglePrdfInput.cc
offline/framework/fun4allraw/SinglePrdfInput.h

This PR fixes the memory leaks of the pool input manager. The file handling is now done in a separate class which will be ported to the Fun4AllInputManager at some point.

Fix poolinput

---

offline/framework/fun4allraw/Fun4AllEvtInputPoolManager.cc
offline/framework/fun4allraw/Fun4AllEvtInputPoolManager.h
offline/framework/fun4allraw/Makefile.am
offline/framework/fun4allraw/SingleEvtInput.cc
offline/framework/fun4allraw/SingleEvtInput.h

This PR is the nucleus of the streaming readout combiner

start with evt pool manager

---

offline/packages/CaloReco/CaloTowerBuilder.cc

Trivial PR to fix the implementation of the PHComposite nodes to make sure the relevant subsystems are put under the correct nodes.

modified the nodestructure to put detector systems in the relevant composite nodes

---

offline/packages/intt/InttMapping.cc
offline/packages/intt/InttRawDataDecoder.cc

Fixed issue with index mapping

---

offline/packages/micromegas/MicromegasCalibrationData.h
offline/packages/micromegas/MicromegasRawDataEvaluation.cc
offline/packages/micromegas/MicromegasRawDataEvaluation.h

Another round of update to the micromegas raw data evaluation. 
Add pedestal and rms to the waveform and sample structure so that one can plays with the zero suppression offline

Micromegas evaluation update

---

offline/packages/CaloReco/CaloWaveformFitting.cc

Moved the creation of the TThreadExecutor to global and changed it to a pointer to enable the setting of the number of threads during the initalization stage. Appears to resolve all per-event memory leaks.

fixed a memoryleak issue

---

offline/packages/intt/InttMapping.cc
offline/packages/intt/InttMapping.h
offline/packages/intt/InttRawDataConverter.cc
offline/packages/intt/InttRawDataConverter.h
offline/packages/intt/InttRawDataDecoder.cc

Touchups and standardizations to event decoding (for INTT)

---

offline/packages/CaloReco/CaloTowerCalib.cc

updated the calib name to be consistent with the 1008 cosmic absolute calibration file just uploaded.   

Update CaloTowerCalib.cc, update the calib name

---

offline/packages/micromegas/Makefile.am

This PR adds a missing include path for online, no need to run jenkins [skip-ci]

add missing include path

---

simulation/g4simulation/g4eval/SvtxEvaluator.cc

ntp_track and ntp_gtrack now have counts of how many clusters 
- sit at phi sector edges
- sit at r sector edges
- are bigger than average
- are overlapping with other clusters
Corresponding info is also added to ntp_cluster

added cluster quality counts to tracks

---

offline/packages/TrackingDiagnostics/TrackResiduals.cc
offline/packages/TrackingDiagnostics/TrackResiduals.h
offline/packages/trackbase/TrackFitUtils.cc
offline/packages/trackbase/TrackFitUtils.h
offline/packages/trackreco/ActsEvaluator.cc
offline/packages/trackreco/ActsEvaluator.h
offline/packages/trackreco/Makefile.am
offline/packages/trackreco/PHActsTrkFitter.cc
offline/packages/trackreco/PHActsTrkFitter.h
offline/packages/trackreco/PHCASeeding.cc
offline/packages/trackreco/PHSimpleKFProp.cc

This PR updates several diagnostic tools in our tookit for use
1. Adds additional cluster diagnostic tools to TrackResiduals
2. Moves residual-to-circle-fit-trajectory functions from TPC seeding code into TrackFitUtils for global access
3. Revives the ActsEvaluator tool and puts it back into our build
Okay, now to use them...

fix: Diagnostic tools

---

offline/packages/NodeDump/DumpEpInfo.cc
offline/packages/NodeDump/DumpPHG4CylinderGeomContainer.cc
offline/packages/NodeDump/DumpPHG4TpcCylinderGeomContainer.cc
offline/packages/NodeDump/DumpPHG4TpcCylinderGeomContainer.h
offline/packages/NodeDump/Makefile.am
offline/packages/NodeDump/PHNodeDump.cc

Adds another node dump, this one to make sure the copied object is identical among sim productions

add dump of PHG4TpcCylinderGeomContainer

---

simulation/g4simulation/g4tpc/PHG4TpcElectronDrift.cc

fix: nullptr check

---

offline/framework/frog/CreateFileList.pl

This PR adds an explanation for the DST_BBC_EPD dst type [skip-ci]

Add new DST_BBC_G4HIT type

---

offline/framework/phool/Makefile.am
offline/framework/phool/configure.ac
offline/packages/bbc/Makefile.am
offline/packages/bbc/configure.ac

This PR adds --enable-online to phool and the bbc to compile the online version of the bbc code

Bbc online

---

offline/framework/fun4allraw/Fun4AllPrdfInputPoolManager.cc
offline/framework/fun4allraw/Fun4AllPrdfInputPoolManager.h
offline/framework/fun4allraw/SinglePrdfInput.cc

This PR adds gathering stats of dropped packets so we can see low (and high) level problems

gather stats of dropped packets

---

offline/packages/CaloReco/CaloGeomMapping.cc
offline/packages/CaloReco/CaloGeomMapping.h

Added getter and setter methods for m_Detector. These are to be used in the main calo production macro (macros/CaloProduction/Fun4All_CaloProduction.C), see related pull request
https://github.com/sPHENIX-Collaboration/macros/pull/657

Added getter and setter for CaloGeomMapping m_Detector

---

simulation/g4simulation/g4calo/HcalRawTowerBuilder.cc
simulation/g4simulation/g4ihcal/PHG4IHCalDetector.cc
simulation/g4simulation/g4ohcal/PHG4OHCalDetector.cc

shift hcal tower index so that match with real data

---

offline/framework/ffarawmodules/EvtCheck.cc
offline/framework/ffarawmodules/EvtCheck.h
offline/framework/ffarawmodules/Makefile.am
offline/framework/fun4allraw/Fun4AllEvtInputPoolManager.cc
offline/framework/fun4allraw/Fun4AllEvtInputPoolManager.h
offline/framework/fun4allraw/Makefile.am
offline/framework/fun4allraw/PacketList.cc
offline/framework/fun4allraw/PacketList.h
offline/framework/fun4allraw/SingleEvtInput.cc
offline/framework/fun4allraw/SingleEvtInput.h

this PR adds the first version of the aligning via the beamclock, works for the simplest case (intt), beam clocks have to match across prdf files

Intt combiner

---

offline/framework/fun4allraw/Fun4AllEvtInputPoolManager.cc
offline/framework/fun4allraw/PacketList.cc
offline/framework/fun4allraw/PacketList.h
offline/framework/fun4allraw/SingleEvtInput.cc
offline/framework/fun4allraw/SingleEvtInput.h
offline/framework/fun4allraw/SinglePrdfInput.cc

Add packet list iterator accessors

Intt combiner 2

---

offline/packages/CaloReco/DeadHotMapLoader.cc
offline/packages/CaloReco/DeadHotMapLoader.h
offline/packages/CaloReco/Makefile.am
offline/packages/CaloReco/RawClusterDeadHotMask.cc
offline/packages/CaloReco/RawClusterDeadHotMask.h
offline/packages/CaloReco/TowerInfoDeadHotMask.cc
offline/packages/CaloReco/TowerInfoDeadHotMask.h

Adding TowerInfoDeadHotMask module to mask dead and hot towers. 
After conversation with Anthony and Tim, we decided to change the name of two modules to better reflect their functionality:
RawTowerDeadMapLoader -> DeadHotMapLoader
RawClusterDeadAreaMask -> RawClusterDeadHotMask

Adding Mask for towers and changing module names

---

offline/packages/CaloBase/TowerInfoContainerv1.cc

Changed the number of channels in the EPD to 786 to match what the EPD experts say is reality

fixed the number of channels in the EPD

---

simulation/g4simulation/g4calo/HcalRawTowerBuilder.cc
simulation/g4simulation/g4calo/Makefile.am
simulation/g4simulation/g4calo/RawTowerBuilder.cc
simulation/g4simulation/g4calo/RawTowerBuilder.h
simulation/g4simulation/g4calo/RawTowerDigitizer.cc
simulation/g4simulation/g4calo/RawTowerDigitizer.h
simulation/g4simulation/g4calo/g4hitshift.cc
simulation/g4simulation/g4calo/g4hitshifthcal.cc
simulation/g4simulation/g4calo/g4hitshifthcal.h

add code that shift the g4hit index for hcal

---

offline/packages/intt/InttMapping.cc

Finally fixed ladder mapping convention

---

offline/framework/ffarawmodules/EvtCheck.cc
offline/framework/fun4allraw/PacketMap.cc
offline/framework/fun4allraw/PacketMap.h
offline/framework/fun4allraw/SingleEvtInput.cc
offline/packages/intt/InttClusterizer.cc
offline/packages/intt/InttCombinedRawDataDecoder.cc
offline/packages/intt/InttCombinedRawDataDecoder.h
offline/packages/intt/Makefile.am

This PR adds a template for the combined reading of intt prdfs. It just prints out the selected hits with beam clock - the next step is for the intt to fill the data into a HitSet. The decoding for the intt is too opaque for me - I don't have the time to figure this out

Intt combiner 4

---

offline/packages/CaloReco/TowerInfoDeadHotMask.cc

Changed masked tower time from 0 to -10 for easier identification and treatment.

Changed masked tower time to -10

---

offline/packages/intt/InttCombinedRawDataDecoder.cc

Implemented combiner so it appends to DST

---

offline/packages/CaloReco/TowerInfoDeadHotMask.cc

Removing a cout that should not be there!

Removing cout that should not be there

---

offline/framework/ffarawmodules/EventNumberCheck.cc
offline/framework/ffarawmodules/EventNumberCheck.h
offline/framework/fun4allraw/Fun4AllPrdfInputPoolManager.cc
offline/framework/fun4allraw/Fun4AllPrdfInputPoolManager.h
offline/framework/fun4allraw/SingleEvtInput.cc
offline/framework/fun4allraw/SinglePrdfInput.cc
offline/framework/fun4allraw/SinglePrdfInput.h

Seems functional re-aligning the mbd with the cemc for run 20508. It re-synchronizes after the mdb drops an event and skips over hickups in the mbd clock counter. It doesn't handle rollovers between the reference beam clock from the mbd  and the subsystem bclk counter yet - which is an issue for the hcals in this run (40 bits would be very helpful here).
If the number of dropped events is at the pool depth it discards all events (to be looked at), the depth is currently set to 100 events to patch this over. Sadly events in the pool will be dropped during …

Prdfcombiner 2

---

offline/packages/TrackingDiagnostics/TrkrNtuplizer.cc
offline/packages/TrackingDiagnostics/TrkrNtuplizer.h
simulation/g4simulation/g4detectors/PHG4TpcCylinderGeom.cc
simulation/g4simulation/g4detectors/PHG4TpcCylinderGeom.h

adding fractional pad and time bin access to TPC geo and TrkrNtuplizer

---

offline/packages/trackreco/PHSiliconHelicalPropagator.cc
offline/packages/trackreco/PHSiliconHelicalPropagator.h

Fixes a seg fault in the helical propagator when trying to add silicon clusters to track seeds with less than 3 clusters. Also clang-formats the files.

fix: seg fault in helical propagator

---

offline/framework/fun4allraw/Fun4AllPrdfInputPoolManager.cc

This PR puts the couts of the pool input mgr behind verbosity > 1, no more 500MB logs...

Prdfpoolinput quiet

---

offline/packages/bbc/Makefile.am

This PR takes care of the missing bbc pcm files warning when running our default macro

create pcm files for BbcPmtInfoV1 and BbcPmtInfoContainerV1

---

simulation/g4simulation/g4tpc/TpcClusterBuilder.cc

Hide verbosity in digitization

fix: remove verbosity

---

offline/packages/intt/InttVertex.h
offline/packages/intt/InttVertexFinder.cc
offline/packages/intt/InttVertexFinder.h
offline/packages/intt/InttVertexLinkDef.h
offline/packages/intt/InttVertexMap.cc
offline/packages/intt/InttVertexMap.h
offline/packages/intt/InttVertexMapLinkDef.h
offline/packages/intt/InttVertexMapv1.cc
offline/packages/intt/InttVertexMapv1.h
offline/packages/intt/InttVertexMapv1LinkDef.h
offline/packages/intt/InttVertexv1.cc
offline/packages/intt/InttVertexv1.h
offline/packages/intt/InttVertexv1LinkDef.h
offline/packages/intt/Makefile.am

add Vertex finding code

---

offline/packages/trackreco/ALICEKF.cc
offline/packages/trackreco/ALICEKF.h
offline/packages/trackreco/ActsAlignmentStates.cc
offline/packages/trackreco/ActsAlignmentStates.h
offline/packages/trackreco/PHActsTrackProjection.cc
offline/packages/trackreco/PHActsTrackProjection.h
offline/packages/trackreco/PHActsTrkFitter.cc
offline/packages/trackreco/PHActsTrkFitter.h
offline/packages/trackreco/PHActsVertexPropagator.cc
offline/packages/trackreco/PHActsVertexPropagator.h
offline/packages/trackreco/PHCASeeding.cc
offline/packages/trackreco/PHCASeeding.h
offline/packages/trackreco/PHSiliconTpcTrackMatching.cc
offline/packages/trackreco/PHSiliconTpcTrackMatching.h
offline/packages/trackreco/PHSimpleKFProp.cc
offline/packages/trackreco/PHSimpleKFProp.h
offline/packages/trackreco/PHTpcDeltaZCorrection.cc
offline/packages/trackreco/PHTpcDeltaZCorrection.h
simulation/g4simulation/g4eval/TrackSeedTrackMapConverter.cc
simulation/g4simulation/g4eval/TrackSeedTrackMapConverter.h

Adds some code that allows running with a constant field set to a very small value for cosmic testing

feat: Add constant field

---

offline/packages/trackreco/PHSiliconHelicalPropagator.cc

This fixes a bug in PHSiliconHelicalPropagator that associates clusters in the INTT on the opposite hemisphere to a track. This happens because of the 2-half layer structure of the INTT. The fix involves checking that the INTT clusters are in the same quadrant as the identified MVTX clusters.

fix: Match INTT clusters correctly

---

offline/framework/fun4allraw/InttPool.cc
offline/framework/fun4allraw/InttPool.h
offline/framework/fun4allraw/Makefile.am
offline/framework/fun4allraw/SingleInttInput.cc
offline/framework/fun4allraw/SingleInttInput.h

This PR is the first stab at implementing proper pooling for the intt - basically a copy of Martins pool class

Intt input

---

offline/packages/micromegas/MicromegasCalibrationData.cc
offline/packages/micromegas/MicromegasCalibrationData.h
offline/packages/micromegas/MicromegasRawDataDecoder.cc
offline/packages/micromegas/MicromegasRawDataDecoder.h
offline/packages/micromegas/MicromegasRawDataEvaluation.cc
offline/packages/micromegas/MicromegasRawDataEvaluation.h

implemented min_adc cut, consistently with online monitoring
added more debugging tools 

Tpot min adc

---

offline/framework/fun4all/Fun4AllServer.h
offline/framework/fun4allutils/Makefile.am
offline/framework/fun4allutils/TimerStats.cc
offline/framework/fun4allutils/TimerStats.h
offline/framework/fun4allutils/autogen.sh
offline/framework/fun4allutils/configure.ac

This PR adds a module which stores the runtime for each event for each module in a cdbttree to get more detailed info than just the average time for each module

Timerstats

---

offline/framework/frog/CreateFileList.pl

This PR handles the -embed correctly for all types (pau results in pAu files) [skip-ci]

use embed flag correctly for all systems

---

offline/framework/ffarawobjects/InttRawHit.h
offline/framework/ffarawobjects/InttRawHitv1.cc
offline/framework/ffarawobjects/InttRawHitv1.h
offline/framework/fun4allraw/Makefile.am
offline/framework/fun4allraw/SingleInttInput.cc

Intt packetid

---

offline/framework/fun4allraw/SingleTPCInput.cc
offline/framework/fun4allraw/SingleTPCInput.h

add forgotten files

---

offline/framework/fun4allraw/Fun4AllEvtInputPoolManager.cc
offline/framework/fun4allraw/Fun4AllEvtInputPoolManager.h
offline/framework/fun4allraw/SingleInttInput.cc
offline/framework/fun4allraw/SingleInttInput.h

Looks like the INTT combining is working with this one

intt seems to work now

---

offline/framework/ffarawmodules/InttCheck.cc

[comment]: <This PR checks the beam clock counter consistency for the intt (only one bco per event)> ( What does this PR do? Linking to talk in software meeting encouraged )

add intt beam clock check module

---

calibrations/calorimeter/calo_emc_pi0_tbt/macro/Fun4All_G4_Pi0_Tbt.C
calibrations/tpc/fillSpaceChargeMaps/macros/Fun4All_FillChargesMap_300evts_MDC2.C
calibrations/tpc/generator/generate_distortion_map.C
offline/packages/PHGeometry/macros/PHGeom_DSTInspection.C

Fix some cppcheck warnings from macros, jenkins does not test them, so [skip-ci]

fix some cppcheck warnings

---

calibrations/tpc/generator/generate_distortion_map.C
offline/framework/fun4allraw/Fun4AllEvtInputPoolManager.cc
offline/framework/fun4allraw/Fun4AllEvtInputPoolManager.h
offline/framework/fun4allraw/Makefile.am
offline/framework/fun4allraw/SingleTpcInput.cc
offline/framework/fun4allraw/SingleTpcInput.h

This PR adds the Single Tpc input manager to the pool manager, still need to sort out the bco to the tpc

add tpc to pool manager

---

offline/packages/TrackerMillepedeAlignment/HelicalFitter.cc
offline/packages/TrackingDiagnostics/TrkrNtuplizer.cc
offline/packages/TrackingDiagnostics/TrkrNtuplizer.h

I somehow inadvertently closed Christof's PR by doing a force push as there was some git mixup. In any case this PR supersedes https://github.com/sPHENIX-Collaboration/coresoftware/pull/2237 by removing the dependency on the HelicalFitter and just calling the relevant functions in TrackFitUtils. Credit goes to @bogui56 for the changes, my mistake for screwing up the git history.

feat: Ntuplizer update
